modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
There was a crash due to incorrect string formatting as episode limit changed from a number to an enum.
I'll need to investigate why Lint didn't fail on CI because the error was highlighted by it in the IDE.
1. Go to a subscribed podcast.
2. Go to the podcast's settings.
3. Go to the auto archive settings.
4. Change the episode limit to 1 episode.
5. Go back to the podcast episode list.
6. Show unarchived episodes.
7. Open an archived episode details.
8. Unarchive the episode from the details.
9. App should not crash and you should see `It won't be auto archived by your new episode limit of 1` message.
=> Use correct argument for episode limit string formatting

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
This fixes latest badge disappearing on podcasts list view 
Fixes #2281
1. Login with an account subscribed to many podcasts
2. Arrange podcasts by release date in the Podcasts tab
3. Tap more options in the app bar and select list layout
4. Scroll the list forward and backward
5. ✅  Notice that the latest badges doesn't disappear on scrolling backward
6. Smoke test latest/ unfinished badge visibility on grid/ list layouts, inside and outside folder
7. ✅  Notice that badges visibility is as expected
Before 
https://github.com/Automattic/pocket-casts-android/assets/1405144/3ebf3df4-464a-4c1f-a64a-55165388957b
After
https://github.com/Automattic/pocket-casts-android/assets/1405144/c7f1b677-18a8-43bc-9496-26f07ef6ae23
=> Fix latest badge disappearing on podcasts list view 

CHANGELOG.md, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
- Just fixes the wrong color of subscribe button in discover's carousel 
Fixes #2187 
- Code review should be enough, but you can try to check the subscribe button in carousel from Discover page
- You can try with different themes
|![Screenshot_20240508_113352](https://github.com/Automattic/pocket-casts-android/assets/42220351/8d8c3815-40e0-474d-bc9a-1623fdbd9938) |![Screenshot_20240508_113047](https://github.com/Automattic/pocket-casts-android/assets/42220351/26e838ed-7c12-40d6-8f4d-2a9663ac0ae8) |
=> Fix: Subscribe button is highlighted in green instead of gray in the carousel

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
Part of https://github.com/Automattic/pocket-casts-android/issues/157
We sync episode progress every minute at `syncEpisodeProgress(playbackState: PlaybackState)`. If the episode is paused before the next progress sync, and there's a background refresh, the playback may skip backward. This is captured below (playback skipped 8 secs backward at 00:51). When I resumed playback, I could hear repeated words.
https://github.com/Automattic/pocket-casts-android/assets/1405144/6608311e-b311-408e-b7fc-87b128392eb9
This PR
- Tracks negative seek on sync
- Increments backward threshold to update time from sync from 2 to 5 seconds 
I confirmed that the analytic event is properly sent:
```
🔵 Tracked: playback_episode_position_changed_on_sync, Properties: …
```
=> Add logs to track negative seek on sync

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt, modules/features/podcasts/src/main/res/layout/adapter_podcast_grid.xml
This fixes podcast title talkback.
Fixes #2294
1. Open the system settings
2. Search for Talkback and turn it on
3. Open Pocket Casts app
4. Drag your finger over the podcast artwork
5. ✅ It should say the podcast title 
6. Smoke test talkback for list view item. It should continue to say the podcast title
=> Fix podcast title talkback

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
This includes `Discover` tab carousel's sponsored podcasts in the featured podcast analytics.
Internal ref: p1717644686886349-slack-C028JAG44VD
1. Go to Discover tab
2. Tap on first (sponsored) podcast in the carousel
3. ✅ Notice that `discover_featured_podcast_tapped` is tracked along with `discover_list_podcast_tapped`
4. Subscribe to this sponsored podcast from the podcast details page
5. ✅ Notice that `discover_featured_podcast_subscribed` is tracked along with `discover_list_podcast_subscribed`
6. Unsubscribe the podcast
7. Return to the carousel and subscribe to the same podcast using the plus button for sponsored podcast
8. ✅  Notice that `discover_featured_podcast_subscribed` is tracked along with `discover_list_podcast_subscribed`
=> Fix discover carousel analytics

modules/services/views/src/main/res/menu/navigation.xml
This changes up next tab order.
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/1803
Internal discussion: p1717555337043659-slack-C029BMLUGRX
2. ✅ Notice the up-next tab position is updated to match the iOS
3. Install the app from main branch
4. Open the app and select a tab like Filters
5. Kill the app
6. Install the app from this branch
7. Open the app 
8. ✅ Notice that the last selected tab is shown without any crash
Merge only when the corresponding iOS PR is merged.
=> Change up next tab position

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
The threshold to track negative seek on sync (for the currently paused episode) was set to 5 secs in PR #2292. Looking at early tracks for `playback_episode_position_changed_on_sync`, 99% of values are under 60 secs. This PR gets this threshold value from Firebase remote config, allowing us to experiment with the value. 
I updated threshold from 5 to 10 secs in Firebase remote config and tested that the value is properly fetched in the release build:
It should be sufficient to just code-review the changes.
=> Configure threshold for negative seek on sync using Firebase remote config

CHANGELOG.md, modules/features/podcasts/src/main/res/layout/adapter_episode.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt, modules/services/views/src/main/res/layout/view_file_status_icons.xml
Attempt to fix: #2291
A podcast may have several episodes (can be even more than 2000). Writing all of them into a database in a single transaction may grow WAL size substantially, and shrinking it can lead to unexpected ANR as noticed in https://github.com/Automattic/pocket-casts-android/issues/2291.
This PR inserts podcast episodes in chunks to reduce chances of UI locking at the time of automatic checkpoint to shrink WAL file.
I also set initial visibility to false for episode row icons like bookmarks in f00eb9c8699204549e7c34e8cbc352b470295e0c to minimize icon flashing between tab switches.
1. Switch to `main` branch
2. Fresh install the app while being connected to adb 
3. Search for `truncating` in the logs
4. Login with an account having podcasts with lots of (> ~500) episodes. You …
=> Attempt to fix app freezing when writing several podcast episodes to WAL 

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoSelectionTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImplTest.kt
This PR moves chapter selection from `PlaybackManager` to `ChapterManager` and make it transactional. I'm doing it in a preparation for adding chapters to episode details. 
Test chapter selection. Deselect and select different chapters, check syncing, check skipping chapters in the player, etc.
=> Move chapter selection to chapter manager

CHANGELOG.md, lint.xml, modules/features/player/lint-baseline.xml, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt, modules/features/podcasts/lint-baseline.xml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragmentViewModel.kt, modules/services/localization/lint-baseline.xml, modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This PR adds chapters preview to episode details. It also improves couple of other things:
- Data set changes in player container are now applied selectively with appropriate `notifyItemInserted()` and `notifyItemRemoved()`.
- Chapters are now available in player view before playing the episode. They are not extracted beforehand so embedded chapters still require playing but once extracted and saved in the database they will be there before playing.
- I removed snackbar feedback about deselecting last chapter because it is now blocked in the UI.
- `ChaptersViewModel` is now extensively tested.
Test both episode details and player chapters. They should behave almost the same. The only difference is that tapping on an already playing chapter in the episode details doesn't navigate to …
=> Add chapters to episode details screen

CHANGELOG.md, modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/BottomNavigator.kt
- This removes the flickering when taps on the current selected navigation tab bar
- See the video in https://github.com/Automattic/pocket-casts-android/issues/2149
Fixes #2149 
2. Tap on the current selected navigation item bar
3. ✅ Ensure you don't see the flickering anymore
[Screen_recording_20240610_125111.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/ae8c6272-5a8b-4c7e-b9f5-c250b9c99d17)
=> Remove flickering when double-tapping an item in the tab bar

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt, modules/features/nova/build.gradle.kts, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherSubscribedPodcast.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This PR bumps the Nova SDK and uses latest APIs to sync subscribed podcasts. I removed syncing of all other catalogs to test them separately as I'll migrate to the new SDK.
2. Open Nova Launcher. You don't have to set is a default launcher app but make sure you can use it.
4. Open the app.
5. Subscribe to some podcasts.
```
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 1cfb4398-1b4a-4f58-b483-b93dcf370409) - Enqueued Nova Launcher one-off sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 1cfb4398-1b4a-4f58-b483-b93dcf370409) - Staring Nova Launcher sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: …
```
=> Use latest Nova SDK to sync subscribed podcasts

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Adds the missing `listening_history_clear_history_button_tapped ` track event for when the user taps the clear listening history button
Fixes #2337
1. Have some episodes in your listening history
2. Go to `Profile` -> `Listening history`
3. Tap on the 3 dots at the top 
4. Tap on `Clear Listening History` to open the modal
5. Tap on `Clear all`
6. ✅ Ensure 🔵 Tracked: `listening_history_clear_history_button_tapped` was tracked
=> Fix: Listening History - event not track when tap on clean listening history

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/AuthenticationNavGraph.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithEmailScreen.kt
It isn't easy to login on emulators for testing. This brings back login with an email option (which was removed in https://github.com/Automattic/pocket-casts-android/pull/1357) for debug builds.
1. Install debug/ debugProd build on Wear emulator
2. Tap login
3. ✅  Notice you can see Log in with email option
4. Login using a paid account
5. ✅  Login should be successful
1. Install the release build on Wear emulator
2. Tap login
3. ✅  Notice you do not see Log in with email option
Debug | Release
---|---
=> Wear app: Bring back email login for debug build

CHANGELOG.md, metadata/release_notes.txt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeSearchView.kt
- This PR reverts https://github.com/Automattic/pocket-casts-android/pull/2286 while was tying to fix https://github.com/Automattic/pocket-casts-android/issues/1320. This PR introduced another issue: https://github.com/Automattic/pocket-casts-android/issues/2352
Fixes #2352
- Follow the steps from #2352 and make sure you can't reproduce this issue anymore
=> Revert #2286 in order to avoid Search Term gets cleared when scrolled off-screen issue

CHANGELOG.md, metadata/release_notes.txt, modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/BottomNavigator.kt
- Due the feedbacks we received [here](https://github.com/Automattic/pocket-casts-android/pull/2326) we decided to revert  
https://github.com/Automattic/pocket-casts-android/pull/2326 and come with another solution later
Internal ref: p1718627578962219/1718626748.174429-slack-C028JAG44VD
=> Revert PR 2326

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/96.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt
This changes chapter indices to be 0 based instead of 1 based. The change is needed to have a consistent experience between different platforms when syncing.
Internal ref: p1718625500938109-slack-C029BMLUGRX
1. Install the app from d7e81be215f2f9e8f357b2ceb21ad80775e4387c.
2. Sign in and deselect chapters from different episodes.
3. Install the app from this branch.
4. Sign in and make sure that the same chapters are still deselected.
1. Test syncing chapters deselection between Android devices.
2. Test syncing chapters deselection between Android and iOS.
=> Make chapter indices 0 based

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This PR syncs trending podcasts with Nova Launcher.
2. Open Nova Launcher. You don't have to set it as a default launcher app but make sure you can use it.
4. Open the app and go to Discover tab to see trending podcasts.
```
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 4c6d16ca-381f-48e0-ac25-068a3260e01f) - Enqueued Nova Launcher one-off sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 4c6d16ca-381f-48e0-ac25-068a3260e01f) - Staring Nova Launcher sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 4c6d16ca-381f-48e0-ac25-068a3260e01f) - Nova Launcher sync complete. Success: [Subscribed podcasts: 75, Trending …
```
=> Sync trending podcasts with Nova

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
This PR syncs new releases with Nova Launcher.
2. Open Nova Launcher. You don't have to set it as a default launcher app but make sure you can use it.
4. Subscribe to some podcasts that have releases from at most 2 weeks ago that you haven't listened to.
```
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 334a8900-0842-4874-9893-9524820e380f) - Enqueued Nova Launcher one-off sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 334a8900-0842-4874-9893-9524820e380f) - Staring Nova Launcher sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 334a8900-0842-4874-9893-9524820e380f) - Nova Launcher sync complete. Success: …
```
=> Sync new releases with Nova

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
This PR syncs in progress episodes with Nova Launcher.
2. Open Nova Launcher. You don't have to set it as a default launcher app but make sure you can use it.
4. Have some episodes played but not finished.
```
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 136bdd40-f9a4-450b-ac6c-c9eaa3f00370) - Enqueued Nova Launcher one-off sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 136bdd40-f9a4-450b-ac6c-c9eaa3f00370) - Staring Nova Launcher sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 136bdd40-f9a4-450b-ac6c-c9eaa3f00370) - Nova Launcher sync complete. Success: [Subscribed podcasts: 75, Trending podcasts: 25, New …
```
=> Sync in progress episodes with Nova

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherRecentlyPlayedPodcast.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This PR syncs recently played podcasts with Nova Launcher.
2. Open Nova Launcher. You don't have to set it as a default launcher app but make sure you can use it.
4. Have some podcasts that you listened to in the past 2 months.
```
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 3ef6ed87-82ab-4def-ab64-f4ad062cb244) - Enqueued Nova Launcher one-off sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 3ef6ed87-82ab-4def-ab64-f4ad062cb244) - Staring Nova Launcher sync
BgTask: NovaLauncherOneOffSyncWorker (Worker ID: 3ef6ed87-82ab-4def-ab64-f4ad062cb244) - Nova Launcher sync complete. Success: [Subscribed podcasts: 75, …
```
=> Sync recently played podcasts with Nova

modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
A simple cleanup to not repeat code that creates intents for Nova actions.
You can verify if analytics for different Nova cards are still the same but a code review should be enough.
=> Refactor creating Nova Launcher intents

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Rename `settings_headphone_controls_bookmark_confirmation_sound` to `settings_headphone_controls_bookmark_sound_toggled`
- Rename the property from value to enabled
This was a pending task we had in Track Events doc for Android
Fixes #2350
1. Log with a premium account
2. Go to Profile tab - > Settings -> Headphone Controls
3. Set Add Bookmark as next or previous action
4. Toggle the Bookmark confirmation sound
5. ✅ Ensure 🔵 Tracked: `settings_headphone_controls_bookmark_sound_toggled, Properties: {"enabled"` is tracked
=> Rename both track name event and property for Headphone Controls

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt, modules/features/player/src/main/res/layout/fragment_share.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt
Introduction of a feature flag and entry points to the sharing clip feature.
1. Play a podcast episode.
2. Use share action from the shelf.
3. You should see `Clip` option.
4. Go to `Beta features` and disable `Share episode clips`.
5. Use share action from the shelf.
6. You shouldn't see `Clip` option.
| Podcast details | Episode details |
| - | - |
| ![Screenshot_20240619-095041](https://github.com/Automattic/pocket-casts-android/assets/30936061/3787f5a8-6510-4ee1-9405-06692645aff4) | ![Screenshot_20240619-095056](https://github.com/Automattic/pocket-casts-android/assets/30936061/f35fe168-5000-45dc-8fcd-c3479881f68a) |
=> Add sharing clips option

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Updates privacy track event name to match with the one listed in our `Pocket Casts Tracking Plan` spreadsheet
- Fixes #2360 
- Code review should be enough
=> Update Privacy Track event name

CHANGELOG.md, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
`Context` was never set when multi-selecting episodes from a podcast details or a filter episode list. This prevented episodes from being shared.
2. Long press to select a single episode.
3. Tap on overflow menu in the toolbar.
4. Tap on share.
5. A bottom share dialog should appear.
6. Go to any filter.
4. Long press to select a single episode.
5. Tap on overflow menu in the toolbar.
9. Tap on share.
10. A bottom share dialog should appear.
=> Fix episode sharing action when using multi-selection

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextDaoTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherBridge.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherQueueSync.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/SubmissionResult.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheetFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt, modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/LargePlayerWidgetState.kt, modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/MediumPlayerWidgetState.kt, modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/SmallPlayerWidgetState.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/97.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherQueueEpisode.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextEpisode.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt
This PR syncs Up Next with Nova Launcher. The approach to syncing is different in this PR. All other data is synced using Worker APIs and is done only when app is moved to the background. Syncing while app is running is necessary to keep Up Next card in Nova launcher in sync with other stuff like media center or widgets.
1. Install the app from 479258f56ed9c1047a70d082dbd98f3853ee1647.
2. Launch the app, subscribe to some podcasts, etc.
3. Install the app from this branch.
4. You shouldn't lose any data.
Smoke test if large player widget still works correctly and displays queued items.
---
> [!note]
> You should execute tests below with Nova Launcher from this link: p1718205443795369-slack-C028JAG44VD.
> Make sure to have it installed and check that you can use it.
1. Add episodes to Up …
=> Sync Up Next queue with Nova Launcher

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
- This PR fires `up_next_shown` event with `tab_bar` source when tapping on navigation bar 
- NOTE: Both discover and up next navigation bar button should trigger these `up_next_shown` and `discover_shown` events once, but due the opened issue we have https://github.com/Automattic/pocket-casts-android/issues/2149 we are recreating the fragment every time we tap on navigation bar so the event will be fired every time the navigation is tapped
Fixes #2363
2. Tap on Up Next bottom navigation bar button
3. ✅ Ensure `🔵 Tracked: up_next_shown, Properties: {"source":"tab_bar"` is tracked
=> Track `up_next_shown ` when tapping on navigation bar

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
- Adds `time`, `episode_uuid` and `podcast_uuid` properties to `bookmark_created`
- See: https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=A564
Fixes #2371 
1. Log with a premium account
2. Add Bookmark to a episode
3. ✅ Ensure `🔵 Tracked: bookmark_created, Properties: {"source":"player","time":1718813261779,"episode_uuid":"{episode_uuid}","podcast_uuid":"{podcast_uuid}"` is tracked
4. Go to Profile and add a mp3 file
5. Play the file and add a bookmark
6. ✅ Ensure  `🔵 Tracked: bookmark_created, Properties: {"source":"player","time":1718813283979,"episode_uuid":"{episode_uuid}","podcast_uuid":"user_file"`
=> Add properties to `bookmark_created ` track event

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModel.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This is a preparatory PR  that
1. Adds feature flag for caching the entire streaming episode to minimize streaming while playing (this is different from on-the-fly caching introduced earlier).
2. Adds advanced setting if the above feature flag is enabled (it is disabled by default, we can revisit the default state, and summary text later).
3. Extracts data source factory to helper singleton so that they can be reused later to cache entire episode.
2. Go to `Profile` -> `Settings`-> `Advanced`
3. ✅ Notice there is an advanced setting to enable caching the playing episode 
4. Toggle the setting
5. ✅ Notice that `settings_advanced_cache_entire_playing_episode` is tracked
6. Go to `Profile` -> `Settings`->  `Beta features` 
7. ✅ Disable "Cache entire playing episode" …
=> Cache playing episode feature flag + advanced setting

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Adds `playback_failed` track. We can add more properties if we wanted to this event
Fixes #2368
Code review should be enough
=> Track playback_failed event

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
- `discover_featured_page_changed` track event was being tracked even if the screen was not visible
- See: p1718795716620289/1718795055.315149-slack-C028JAG44VD
Fixes #2379
1. Remove any already installed pocket casts app to have a fresh install
2. Install the app from this branch 
3. ✅ When you see the Log in / Sign in screen, ensure `discover_featured_page_changed` does not continue firing
4. Close the Log in / Sign in screen
5. Go to Discover
6.  ✅ Ensure `discover_featured_page_changed` is tracked
7. Go to another screen
8.  ✅ Ensure `discover_featured_page_changed` is not tracked
=> Fix: Track `discover_featured_page_changed` event only when Discover is visible

modules/features/clip/build.gradle.kts, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/Clip.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipCard.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipColors.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipModule.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipPlayer.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipSelector.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/FakeClipPlayer.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModelTest.kt
This adds playback to the clip page. Since there is currently no start and end selection implemented the clip is using 15 seconds and 30 seconds as respective timestamps.
I wasn't sure how to provide the best implementation for clip playback. I decided to opt-in for a second instance of `ExoPlayer` that is used temporarily only for this screen. I can't use what we already use in our main player for couple of reasons:
* Our app isn't modularized in a way that would allow that.
* `SimplePlayer` is not a singleton and can have different `ExoPlayer` instances.
* I'm afraid that `SimplePlayer` is too coupled with other things and reusing it would cause some side effects.
* `SimplePlayer` uses for configuration things like `ProgressiveMediaSource` that prevent playing clips.
1. Play a not …
=> Play clips on clip page

modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt
This PR implements clip link sharing.
Smoke test sharing podcast, episode, position, bookmarks, etc.
1. Tap on share icon on any episode and select `Clip`.
2. Tap on `Clip` button.
3. You should see share dialog.
4. Share the link somewhere.
5. Open that link in the browser on your computer.
6. A clip player should open in the web.
https://github.com/Automattic/pocket-casts-android/assets/30936061/3cc5e362-d73d-40cb-9569-759460d70ca2
=> Share clip links

modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/HorizontalClipCard.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/VerticalClipCard.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
This PR adds landscape view to the clip sharing.
Designs: [Figma](https://www.figma.com/design/HR2vcQrWcS0scsolKZBitg/Sharing?node-id=2889-14798&t=6MYRnxAe5EbwWA7O-4)
Implemented padding is a little bit different to accommodate for small devices.
1. Start clip sharing in landscape orientation.
2. Verify designs.
3. You can smoke test if clip playback and sharing still work.
| A | B | small |
| - | - | - |
| ![Screenshot_20240620-142449](https://github.com/Automattic/pocket-casts-android/assets/30936061/e4a1177e-84a5-44aa-bb60-8b826fbbfd93) | ![Screenshot_20240620-142245](https://github.com/Automattic/pocket-casts-android/assets/30936061/c976114d-c9c8-4cd9-986c-f41fabf409de) | ![small](https://github.com/Automattic/pocket-casts-android/assets/30936061/844c3a29-1c81-493a-a2ab-69cfdc3c2b56) …
=> Add landscape orientation for clip sharing

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Adds `chapter_link_clicked` event when taps on chapter link
Fixes #2374
1. Log with a premium account
2. Go to a podcast that has chapters, such as `The Changelog: Software Development, Open Source`
3. Open the `Chapters` tab
4. Tap on the chapter URL link icon (see screenshot below)
5. ✅ Ensure `🔵 Tracked: chapter_link_clicked, Properties: {"chapter_title":"name","episode_uuid":"uuid","podcast_uuid": "uuid"`
6. Go to the podcast page
7. Tap on an episode to open the episode detail screen
8. Go to `Chapters tab`
9.  ✅ Ensure `🔵 Tracked: chapter_link_clicked, Properties: {"chapter_title":"name","episode_uuid":"uuid","podcast_uuid": "uuid"`
| Chapter link |
|--------|
| <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/47108c3e-a446-4264-8377-4437cc33d50b" …
=> Add `chapter_link_clicked` event

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Adds `filter_options_modal_option_tapped` for when tap on ellipse menu in filter screen
Fixes #2344
1. Go to filters tab
2. Create a filter
3. Tap on the filter
4. Tap on the ellipse menu
5. Tap on the options and make sure you see the `filter_options_modal_option_tapped` event with the `option`
See the examples:
> 🔵 Tracked: filter_options_modal_option_tapped, Properties: {"option":"sort_by"}
🔵 Tracked: filter_options_modal_option_tapped, Properties: {"option":"play_all"}
🔵 Tracked: filter_options_modal_option_tapped, Properties: {"option":"download_all"}
🔵 Tracked: filter_options_modal_option_tapped, Properties: {"option":"filter_options"}
🔵 Tracked: filter_options_modal_option_tapped, Properties: {"option":"delete_filter"}
| Filter Menu |
|--------|
| <img width="223" alt="image" …
=> Add `filter_options_modal_option_tapped` event

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/PlayButtonListener.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudBottomSheetViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/NotificationBroadcastReceiver.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncJob.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/WarningsHelper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
- 9a68697a53e053b4dcdd059709d7724921321446 : Refactor `addEpisodeToQueue` method to receive `source` as parameter
-  a70e64a663e74b675ebe1412018dab3e438aa952 : Add `source` to `episode_download_finished` event
Fixes #1039
- Try to download episodes from different sources such as `filters`, `starred`, `podcasts`, etc and ensure `🔵 Tracked: episode_download_finished` with `source`
=> Add `source ` to `episode_download_finished `

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This adds a feature flag for the Transcripts project.
1. Install debug/ debugProd build
2. Go to `Profile` -> `Settings` -> `Beta features`
3. ✅ Notice `Transcripts` in the feature flags list 
4. ✅ Notice that feature flag is disabled for release build and has no remote flag configured yet 
** Feature tier is set to free temporarily
=> Transcripts - Add feature flag

CHANGELOG.md, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselItemViewHolder.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RankedListAdapter.kt, modules/features/discover/src/main/res/layout-h560dp/item_carousel.xml, modules/features/discover/src/main/res/layout/item_carousel.xml
- Increase maxLine to 3 and add ellipsize="end" for discover carousel title
- Updates font size if the title size is longer than 35 characters
See: p1718908711900259/1718869041.638049-slack-C04DRL2839S
Fixes #2400
- See https://github.com/Automattic/pocket-casts-android/pull/2389
=> Discover - Update carousel title size

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This adds `autoplay_started` and `autoplay_finished_last_episode` track events
- `autoplay_started`: whenever an autoplay session starts
- `autoplay_finished_last_episode`: when the last episode of a playlist finishes playing
Fixes #2372
1. Go to settings -> General -> Enable `AutoPlay` toggle
2. Have some episodes starred
3. Go to Profile -> Starred
4. Play episodes from this list (Make sure you have empty Up next)
5. Scroll to finish the episode
6. The auto play will add an episode from the starred list
7. ✅ Ensure 🔵 `Tracked: autoplay_started, Properties: {"episode_source":"starred"` is triggered
8. Play the last episode from the starred list
9. Finish this episode
10. ✅ Ensure 🔵 `Tracked: autoplay_finished_last_episode, Properties: {"episode_source":"starred"` is triggered
You can …
=> Add missing auto play track events

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt
While refactoring sharing in #2385 I made an error where `null` would be used instead of an empty string when sharing episodes. This resulted in links like `https://pca.st/episode/c510a66f-f9c0-45c8-bca2-8c0cc1d5f055null`.
1. Share an episode.
2. Notice that the link doesn't contain `null` at the end
=> Fix sharing null time marks in episode

app/src/main/java/au/com/shiftyjelly/pocketcasts/di/AppModule.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/Clip.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipSelector.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipSelectorState.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipPage.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipRangeTest.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModelTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt
This PR adds starting clip sharing position. Initial clip is 15 seconds long with the center at the current played up to position. If the clip range would be invalid (start below 0 seconds or end above episode duration) than clip position is adjusted.
1. Play an episode.
2. Start clip sharing.
3. Notice that the initial clip position matches current played up to position and the timeline is scrolled to make it visible.
4. Repeat steps 2 and 3 with some different positions of the player.
5. Clip an episode that has no played up to timestamp.
6. Clip should be between 0 and 15 seconds.
7. Clip an episode that you've played to the end.
8. Clip should be positioned at 15 seconds till the end of this episode.
9. Test that the clip position is not being reset to the initial state due to the …
=> Start clip sharing from the playback position

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/97.json, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/98.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/TranscriptDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Transcript.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt
This parses transcripts tag for an episode in the show notes endpoint and saves the best transcript metadata in the database.
1. Check that `Transcripts` feature flag is enabled
2. Add a break point at line 84 of `ShowNotesProcessor.kt` 
3. Play an episode from "Cautionary Tales" (https://pcast.pocketcasts.net/8zpmjiru)
4. ✅ Notice that the breakpoint is hit and all transcripts for the playing episode are parsed
5. Continue from breakpoint
6. ✅ Notice that the best transcript metadata of the supported [SRT, VTT] formats or the first available transcript (with not null URL and type) is inserted into db.
Smoke test db migration
=> Transcripts - Parse and save transcript metadata for episode

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt, modules/features/podcasts/src/main/res/layout/view_podcast_header_bottom.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowOutlinedButton.kt, modules/services/localization/src/main/res/values/strings.xml
- This PR includes some UI updates to match with the latest UI proposal -> pdeCcb-3ic-p2#comment-2763
- Adds the `Rate` button to open the give rating screen
- Adds the average rating button
- Adds divider below of give rating view
- Makes Rate button as single entry point for the next screen
- See [Figma](https://www.figma.com/design/sQk9KlwngN1g8iJbQGAMva/Ratings-%26-Reviews?node-id=1-2&t=dR66g9ZWgwViot63-0)
> [!NOTE]  
> I noticed that the stars are yellow in the current implementation, but in Figma they are gray. I am waiting for someone to confirm this here p1719846426918249-slack-C077XU4GF9D . I will address it to another PR
Fixes #2418
Fixes #2419
Fixes #2420
| Before |
|--------|
| <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/e0425f46-e284-463d-a837- …
=> [Give rating] Update Give rating view

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/TranscriptDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/PlayerModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/UrlUtil.kt
This displays an episode transcript in the player container's "temporary" `Transcripts` tab.
2. Play an episode from "Cautionary Tales" (https://pcast.pocketcasts.net/8zpmjiru)
3. Open player tab
4. ✅ Notice there's a new `Transcripts` tab
5. Tap on the `Transcripts` tab
6. ✅ Notice that the episode's transcript is displayed on the tab (ignore all styling)
7. Play an episode that does not have a transcript 
8. ✅ Notice `Transcripts` tab is not shown for the episode
<image width=250 src="https://github.com/Automattic/pocket-casts-android/assets/1405144/abaf2dc9-6b8a-425a-b50d-1898d790f9c3"/>
-  If this is a user-facing change, I have added an entry in CHANGELOG.md - N/A
- Any jetpack compose components I added or changed are covered by compose previews - Not added as …
=> Transcripts -  Integrate (temporary) UI container to show transcript in the Player

.buildkite/pipeline.yml, .buildkite/release-builds.yml
Cherry picking https://github.com/Automattic/pocket-casts-android/commit/746f752011c66573535de73575a938e6b026c279 (https://github.com/Automattic/pocket-casts-android/pull/2430) from `trunk`, so that the release branch also uses the `android` queue by default.
=> [Tooling] Use Android Queue by Default

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt
- Fix the start color for give rating view to match with figma designs
- See: p1719920946149709/1719846426.918249-slack-C077XU4GF9D
Fixes #2428
- Check the star color for all themes
| Before |
|--------|
| <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/48c142a0-072b-4fb3-9a82-64ebcd6d3007" width="300"> | 
| ![image (1)](https://github.com/Automattic/pocket-casts-android/assets/42220351/1a3c09ea-841a-43e1-967b-f70dc19735ed) | ![image (2)](https://github.com/Automattic/pocket-casts-android/assets/42220351/0a9b2a27-91f9-4e12-a70d-3e79ba49357e) |
|:---:|:---:|
| ![image (3)](https://github.com/Automattic/pocket-casts-android/assets/42220351/a843658f-53ce-493c-b34b-ee756fe57090) | ![image (4)](https://github.com/Automattic/pocket-casts-android/assets/42220351/3e16a …
=> [Give rating] Fix star color

.buildkite/schedules/dependency-analysis.yml, build.gradle.kts, gradle.properties, gradle/libs.versions.toml
Project Thread: paaHJt-6yU-p2
Required By: [BuildkiteCI#466](https://github.com/Automattic/buildkite-ci/pull/466)
This PR adds the dependency analysis Android Gradle plugin to this project, for dependency analysis purposes.
For now, only the main `buildHealth` task is going to be utilized and produce data once every week on CI (see this [commit](https://github.com/Automattic/pocket-casts-android/pull/2433/commits/176e2b5e39726205f7ad702c4a51fc1541e0e446) and [this](https://github.com/Automattic/buildkite-ci/pull/466) PR). Amongst other, this data will include the following:
- Number of modules (`projectCount`)
- Unused dependencies which should be removed (`unusedCount`)
- Transitive dependencies which should be declared directly (`undeclaredCount`)
- Existing dependencies which should be …
=> [Dependency Analysis] Add Android Gradle Plugin

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
I've made a small change to fix the sync logging. I noticed while testing in staging that my sync data has a production podcast UUID, which causes a sync error. The logging method has the message and exception parameters arranged the wrong way.
The error goes from:
to this
I also fixed a small typo.
Reading the code and checking that sync still works is probably enough testing. But you could manually throw an exception if you wanted to check the line runs.
=> Fix sync logging

modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CacheWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CastPlayer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/LocalPlayer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/Player.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
This update entire episode caching as follows:
1. Denies it if the episode is downloading
2. Allows it if media is streaming on any network 
> [!WARNING]  
> Targets 7.67
1. Delete cache directory if it exists at `/data/data/au.com.shiftyjelly.pocketcasts.debug/cache/pocketcasts-exoplayer-cache`
2. Open a podcast and long-press an episode
3. Tap download from the top bar (multi-select) menu 
4. Play the episode
5. ✅ Notice that the episode is not cached in Device Explorer at `/data/data/au.com.shiftyjelly.pocketcasts.debug/cache/pocketcasts-exoplayer-cache`
6. Smoke test that episode can be cast properly
1. Delete cache directory if it exists at `/data/data/au.com.shiftyjelly.pocketcasts.debug/cache/pocketcasts-exoplayer-cache`
2. Make sure that "Warn before using data" setting is enabled …
=> Caching updates

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingNotAllowedToRateScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/SwipeableStars.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
- Updates the rating screen to match with the colors proposed in Figma
- Implement the logic to display the not allowed to rate message when the user did not listen any episode from a podcast that is trying to rate
- [Figma](https://www.figma.com/design/sQk9KlwngN1g8iJbQGAMva/Ratings-%26-Reviews?node-id=1-2&t=thV0O4CaLw1UPn0v-0)
Fixes #2434
Fixed #2435
Make sure `GIVE_RATINGS` feature flag is enabled
1. Open a podcast that you did not listen any episode before
2. Tap on `Rate` button
3. ✅ Ensure you see the rating screen with the not allowed to rate messages
4. Listen any episode from this podcast you are trying to rate until `played_up_to` is updated
5. Tap on `Rate` button
6. ✅ Ensure you see the rating screen with the option to rate the podcast …
=> [Give Rating] Update Rating screen

modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipSelector.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipSelectorState.kt
Previously zooming tipping point for switching tick resolution was hardcoded to 5. But it didn't account for minor ticks which contribute to overall space between major ticks. This PR addresses this issue.
Smoke test zooming of clip timeline.
=> Improve zooming feature of the timeline

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
The recent change to add 5x playback speed changed the behaviour of tapping the speed label. We have received lots of negative user feedback, so until we figure out a better way, this will restore the original functionality. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/2427
3. Tap on the effects icon
4. Tap the + button to increase the speed to 1.2
5. Tap the speed label
6. ✅ Verify the speed returns to 1x
7. Tap the speed label
8. ✅ Verify the speed changes to 1.5x
9. Tap the speed label
8. ✅ Verify the speed changes to 2x 
Tap the speed label
8. ✅ Verify the speed changes to 1x 
https://github.com/Automattic/pocket-casts-android/assets/308331/c52697a0-88a8-4965-b6a4-301eef0cd5c2
=> Revert playback speed label taps

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt
This removes intermediate (on-the-fly) caching feature.  It wasn't sufficient to disable it remotely if the advanced setting for caching playing episode was toggled off. In this scenario, intermediate caching would still be active with cache size zero.
> [!WARNING]
> Targets 7.67
Caching entire playing episode should still work as before (https://github.com/Automattic/pocket-casts-android/pull/2380).
=> Remove on-the-fly caching

wear/src/main/AndroidManifest.xml
This adds `FOREGROUND_SERVICE_DATA_SYNC` permission for the Wear app.
Internal ref: p1720357905284329-slack-C02A333D8LQ
Smoke test that syncing and episode download works.
=> Add FOREGROUND_SERVICE_DATA_SYNC permission for Wear app

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/loading/LoadingView.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt
This styles cues into paragraphs.
** I also refactored the code so the transcript is parsed only when the `Transcript` tab is selected. 
1. Play an episode from "Cautionary Tales" (https://pcast.pocketcasts.net/8zpmjiru)
2. Open full screen player
3. Go to the `Transcript` tab
4. ✅ Notice that the transcript is styled as paragraphs
=> Transcripts - Style cues into paragraphs

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingNotAllowedToRateScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt
- This addresses all feedbacks given to https://github.com/Automattic/pocket-casts-android/pull/2438
- Adds Jetpack Compose preview
- Fixes scroll to top
- Changed from `outlinedButtonColors ` to `buttonColors `
See: https://github.com/Automattic/pocket-casts-android/pull/2438
=> Address feedbacks for #2438 PR

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
- Update restriction to rate
```
Episode listened: played_up_to is greater than half the duration
Podcast listened: at least two episodes "listened" (based on above criteria)
``` 
- See: p1720130797705289/1720101621.153249-slack-C077XU4GF9D
- See: https://github.com/Automattic/pocket-casts-sync-api/pull/987
- See: p1720101621153249-slack-C077XU4GF9D
Fixes #2457
Have `GIVE_RATINGS` feature flag enabled
1. Open a podcast that you did not listen any episode
2. Tap `Rate` button
3. ✅ Ensure you can't rate
4. Listen any episode from this podcast. Seek to almost the end of the episode 
5. Repeat the same step 4 for another episode
6. Try to rate again this podcast
7. ✅ Ensure you can rate
=> [Give rating] Update restriction to rate

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowBookmarkDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
> [!note]
This PR migrates showing bookmark deep linking to the new module.
You can test it by assigning `Add bookmark` action to your headphones, and then triggering it while the app is in background and tapping on the notification. If you can't test it this way do the following:
1. Create a bookmark.
2. Using app manger find an UUID of a bookmark.
3. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity  -a INTENT_OPEN_APP_VIEW_BOOKMARKS -e bookmark_uuid <BOOKMARK_UUID>`.
4. The bookmarks page …
=> Refactor bookmark show deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeleteookmarkDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
> [!note]
This PR migrates deleting bookmark deep linking to the new module.
You can test it by assigning `Add bookmark` action to your headphones, and then triggering it while the app is in background and choosing `Delete` option. If you can't test it this way do the following:
1. Create a bookmark.
2. Using app manger find an UUID of a bookmark.
3. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity  -a INTENT_OPEN_APP_DELETE_BOOKMARK -e bookmark_uuid <BOOKMARK_UUID>`.
4. The bookmark should be …
=> Refactor bookmark delete deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowPodcastDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/nova/build.gradle.kts, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
> [!note]
This PR migrates opening podcast deep linking to the new module.
1. Subscribe to [The Daily](https://pca.st/thedaily).
3. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a INTENT_OPEN_APP_PODCAST_UUID -e podcast_uuid 4eb5b260-c933-0134-10da-25324e2a541d`.
4. The Daily podcast page should open.
=> Refactor open podcast deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowEpisodeDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
> [!note]
This PR migrates opening episode deep linking to the new module.
1. Subscribe to [The Daily](https://pca.st/thedaily).
3. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a INTENT_OPEN_APP_EPISODE_UUID -e episode_uuid ebc07cd8-10b6-4ca6-bfae-2994ee215012`.
4. A page for [this episode](https://pca.st/34oj7fwg) should open.
1. Subscribe to some podcasts.
2. Enable notifications for them.
3. Trigger new episode notification from the Developer menu.
4. Tapping on …
=> Refactor open episode deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowPageDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt
> [!note]
This PR migrates opening app from shortcut deep linking to the new module.
Test opening the app using different shortcuts.
=> Refactor shortcuts deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates opening app with PC website in data deep linking to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://pocketcasts.com"`.
2. App should simply open.
=> Refactor PC website deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtilTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates Podlove subscription deep linking to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "pktc://subscribehttps/v4-feed-test.podlove.org/feed/"`.
2. App should open and load [Podlove Test](https://pca.st/RKAS) podcast.
=> Refactor Podlove podcast deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/sonos/SonosAppLinkActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates Sonos deep linking to the new module.
1. Sign in.
3. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "pktc://applink?state=hello"`.
4. Connect to Sonos screen should open.
=> Refactor Sonos deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingFragment.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates share list  deep linking to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://lists.pocketcasts.com/regularly-scheduled-programming"`.
2. App should open and load `Regularly Scheduled Programming` list.
4. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d …
=> Refactor share list deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates subscribe on Android deep linking to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://subscribeonandroid.com/blubrry.com/feed/podcast/"`.
2. App should open and load `Podcast Insider` podcast.
=> Refactor subscribe on Android deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates Apple deep linking to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://itunes.apple.com/us/podcast/within-reason/id1458675168"`.
2. App should open and load `Within Reason` podcast.
4. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://podcasts.apple.com/us/podcast/within-reason/id145867 …
=> Refactor Apple deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/CloudFilesDeepLinkTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/profile/build.gradle.kts, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates cloud files deep linking to the new module.
1. Go to your file manager and find an audio file.
2. Share it to Pocket Casts.
3. Add the file in Pocket Casts.
4. App should open Files page.
=> Refactor cloud files deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
> [!note]
This PR migrates deep linking of account upgrade to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "pktc://upgrade"`.
2. App should open with the account upgrade flow. Note that the flow itself currently is broken. p1720433730195029-slack-C028JAG44VD
=> Refactor account upgrade deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
> [!note]
This PR migrates deep linking promo codes to the new module.
1. Execute `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "pktc://redeem/promo/111222333"`.
2. App should open with the promo code flow.
=> Refactor promo code deep linking

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/99.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Transcript.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt
This adds the capability to highlight and scroll cues. It is used to highlight text at the current playback position (although not accurately). If not for playback position sync, we can use the logic to highlight and scroll to searched text in a future PR.
1. Play an episode from "Cautionary Tales" (https://pcast.pocketcasts.net/8zpmjiru)
3. Go to the Transcripts tab
4. ✅ Notice that the cue is highlighted based on its event time and it scrolls to visible area of the screen
In 783c390c2682a70db848fd559753265107218b73, I modified the index on `episode_uuid` to be unique as we only insert the best transcript for an episode.  
1. Checkout commit 1d4cde0e
3. Checkout this branch
4. Re-install the app
5. ✅ Make sure that migration gives no …
=> Transcript - Highlight and scroll cues

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/FocusManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This improves logs for audio focus feature and does a minor refactor.
Internal ref: p1720364784529929-slack-C02A333D8LQ
1. Play an episode.
2. Trigger audio focus change in some other app like Google Maps giving directions.
3. Audio should duck volume or stop depending on your local settings.
=> Improve logs and refactor focus changes

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/NativeShareDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/SharingUrlTimestampParser.kt, modules/services/deeplink/src/test/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/SharingUrlTimestampParserTest.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/IntentUtil.kt
This PR migrates sharing deep linking to the new module. It also fixes a bug with incorrect link recognition.
I didn't update changelog yet because the changelog file isn't ready yet for `7.69`. I'll update it once we release new beta.
Closes #2405
Do regression tests of opening links in mobile app that are shared from web app and from mobile app.
1. Play an episode.
2. Share the episode from current position.
3. Open the link using the app.
4. App should recognize episode and the playback timestamp.
5. Share clip link to the episode.
6. Open the link using the mobile app.
7. App should open embedded web view clip player.
=> Migrate sharing to deep link module

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
This PR migrates last two deep links to the new module.
=> Migrate search and assistant deep linking

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
This PR aligns behavior of opening the app from an episode timestamp link with iOS. Previously we started playback automatically. Now it is started only when user taps play.
Internal ref: p1720591839992879-slack-C029BMW150R
1. Open the app with a bookmark link or an episode at a position link.
2. The episode page should open.
3. Playback for the episode should not start.
4. Tapping on play should start playback at the timestamp position.
=> Do not play episode automatically when app is opened from a link

app/src/main/AndroidManifest.xml
Add auto verification to our sharing URL hosts. This allows to open them automatically by our app.
Internal ref: p1720591839992879-slack-C029BMW150R
Code review should be enough. Note that this works only with `release` variant at the moment because our debug variants are not verified correctly on the server due to wrong hash.
=> Auto verify pca.st and pcast.pocketcasts.net hosts

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingNotAllowedToRateScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This PR adds tracks events for rating screen
Fixes #2446
1. Open a podcast that you did not listened any episode before
2. Tap on podcast image to open more details
3. Tap on `Rate` button
4. Ensure 🔵 Tracked: rating_stars_tapped is tracked
5. ✅ Ensure 🔵 Tracked: not_allowed_to_rate_screen_shown is tracked
6. Dismiss this screen
7. ✅ Ensure 🔵 Tracked: not_allowed_to_rate_screen_dismissed is tracked
8. Listen some episodes from this podcast
9. ✅ Ensure 🔵 Tracked: rating_stars_tapped is tracked
10. ✅ Ensure 🔵 Tracked: rating_screen_shown is tracked
11. Dismiss this screen
12. ✅ Ensure 🔵 Tracked: rating_screen_dismissed is tracked
13. Back to the rating screen again and submit a rate
14. ✅ Ensure 🔵 Tracked: rating_screen_submit_tapped is tracked
=> [Give rating] Add tracks

.buildkite/pipeline.yml, .buildkite/release-builds.yml, .buildkite/schedules/dependency-analysis.yml, .buildkite/shared-pipeline-vars
This PR updates `a8c-ci-toolkit` to [3.4.2](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/releases/tag/3.4.2). To be more specific, this PR actually also migrates from the old `bash-cache` to the new `a8c-ci-toolkit` naming convention ([context](https://github.com/Automattic/pocket-casts-android/pull/2433#discussion_r1664015761)).
FYI: The breaking change in `3.0.0` is due to removing the `nvm_install` command, but this repo doesn't use that anywhere anyway. As such, it is safe to apply this update.
- Make sure CI is green (🟢).
=> [Dependency Update] Update `a8c-ci-toolkit` to 3.4.2

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
In #2479 I aligned clip playback with iOS. However in doing so I introduced a potential crash because `PlaybackManager` suspending methods are not thread safe. This should be fixed in the manager but doing it there right now is a too far reaching task.
The crash doesn't happen always. In my testing it happened mainly during cold starts.
```
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.kt:444)
at androidx.room.SharedSQLiteStatement.assertNotMainThread(SharedSQLiteStatement.kt:52)
at androidx.room.SharedSQLiteStatement.acquire(SharedSQLiteStatement.kt:74)
at au.com.shiftyjelly.pocketcasts.models.db.dao.EpisodeDao_Impl.updatePlayedUpToIfC …
```
=> Do not interact with playback manager on the main thread

CHANGELOG.md, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/player/src/main/res/layout/adapter_shelf_item.xml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/PlayButtonListener.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfItem.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/WarningsHelper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
- Reverts https://github.com/Automattic/pocket-casts-android/pull/2325
Closes #2477
1. Install a version of the app that contains the download button as shelf item. For example: 3ed768730322da4f1c495b3f021e803631cf7503
2. Install the app from this branch
4. Open the Now Playing
5. Tap on the 3 dots
6. ✅ Make sure the app does not crash
7. ✅ Make sure the download button is not visible in shelf
=> Revert PR #2325

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
- This PR handles an edge case that the user wants to rate a podcast that has only one episode. For this case, if the user listened this episode, we will let them to rate.
- See: p1720619863257859/1720578266.711749-slack-C077XU4GF9D
Fixes #2488
Have `GIVE_RATINGS` feature flag enabled
1. Run the app
2. Open discover 
3. Add RSS https://anchor.fm/s/f68090c0/podcast/rss that has only episode
4. Do not listen to the episode
5. Try to rate
6. ✅ Ensure you can't rate
7. Listen to the episode (scroll to almost the end)
8. ✅ Ensure you can rate the podcast
- Make sure the restriction still works for podcasts that has more than 1 episode: https://github.com/Automattic/pocket-casts-android/pull/2461
=> [Give Rating] Let the user rate a podcast that has only one episode

app/build.gradle.kts, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/ShareActionsTest.kt, modules/features/sharing/build.gradle.kts, modules/features/sharing/lint-baseline.xml, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ShareActions.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ShareStarter.kt, settings.gradle.kts
Currently our sharing is split into multiple different classes that are hard to use and are not tested - `SharePodcastHelper`, `ShareDialog`, `ShareFragment`. This PR introduces a new classes that will be used for all sharing. I'll replace the old ones in the following PRs.
There will be a small change to analytics for podcast sharing. Previously it didn't send `podcast_share` event. More infor here: p1721652688414179-slack-C029BMLUGRX
Code review and green tests are enough since this code is not used yet.
=> Redesign sharing actions

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Enables the remote `give_ratings` feature flag
Fixes #2503
- ✅ Make sure the feature flag name matches with the same one in Firebase
=> [Give ratings] Enable remote feature flag

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
When testing the podcast refresh we found that Android wasn't setting the latest episode uuid and publish date on the podcast when first signing in. This would mean that the latest episode uuid would be sent to the server as null. If a new episode was never released, then every time the server would return episodes. This will speed up the refresh for lots of users. Do you think I should add it to the change log?
Parameters before. I have replaced `%2C` with `,` to make it easier to read.
```
podcasts=bb793090-0424-012e-f9a0-00163e1b201c,2743d720-0edf-0133-2204-059c869cc4eb,04364440-031e-012e-f99b-00163e1b201c,4eb5b260-c933-0134-10da-25324e2a541d,b1090430-da7a-0135-9e62-5bb073f92b78
last_episodes=null,null,null,null,null
```
Parameters after
``` …
```
=> Add missing latest episode info to the podcast

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ShareDialogFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampFragment.kt
This PR adds entry points for the Reimagine Sharing feature. Right now it redirects to dummy screen.
1. Enable`Use new sharing designs` feature flag.
2. Share podcast from a podcast page.
3. You should see podcast dummy screen.
4. Share any bookmark.
5. You should see bookmark dummy screen.
6. Share episode.
7. You should see episode dummy screen.
8. Share episode at current position.
9. You should see episode timestamp dummy screen.
10. Disable `Use new sharing designs` feature flag.
11. All sharing should act normally without navigating to dummy screens. This also disables clip sharing.
| Podcast | Episode | Episode timestamp | Bookmark |
| ![pod](https://github.com/user-attachments/assets/1ee99d18-e0dc-40c1-8254-1a2c6f14478a) | …
=> Add reimagine sharing entry points

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CardType.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastImage.kt, modules/services/localization/src/main/res/values/strings.xml
Adds a square card variant for sharing. Card image isn't `120 dp` like in the designs but instead 40% of the card size. This is done to accommodate for different screen sizes.
Podcast card design: HR2vcQrWcS0scsolKZBitg-fi-2120_7557
Episode card design: HR2vcQrWcS0scsolKZBitg-fi-2118_6892
Since code isn't used anywhere yet you can compare code and previews with the designs.
=> Add square sharing card

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt
Automotive, and perhaps Wear, doesn't support a default launcher intent and crashes the app when trying to access it. This PR adds a check before creating filter shortcuts.
1. Sign in on an automotive device.
2. Sign in on a phone.
3. Create a filter on the phone.
4. Sync account on the phone.
5. Sync account on the automotive device.
6. App should not crash
=> Fix crashes due to deep link creation on non phones

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt
This writes filters load exception to Log Buffer to debug https://github.com/Automattic/pocket-casts-android/issues/2365
Internal Ref: p1721842681929319/1717944583.209849-slack-C02A333D8LQ
=> AAOS: Write filters load exception to LogBuffer

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerControlsHelper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/player/src/main/res/layout-land/adapter_player_header.xml, modules/features/player/src/main/res/layout/adapter_player_header.xml, modules/features/player/src/main/res/layout/player_controls.xml, modules/features/player/src/main/res/values-land/dimens.xml, modules/features/player/src/main/res/values/dimens.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowCloseButton.kt
When the transcript shelf item is clicked, a blank transcript screen opens with an animation.
** I've tried to match [animation on iOS](https://github.com/Automattic/pocket-casts-ios/pull/1899).
1. Play an episode from "Cautionary Tales" (https://pcast.pocketcasts.net/8zpmjiru)
2. Open full screen player
3. Tap on the Transcript shelf icon
4. ✅ Notice that a blank Transcript screen is shown with a transition, player controls are shown at the bottom
5. Drag up on the Transcript screen
6. ✅ Notice that the up next screen is not shown
7. Tap on the close button on Transcript screen
8. ✅ Notice that Transcript screen is closed
9. Drag up on the Player screen
10. ✅ Notice that the up next screen is shown
Portrait - Phone
https://github.com/user-attachments/assets/62ee69ea-3406-4441-8470-5919b6a …
=> Transcript - Transition from player screen

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/social/PlatfromItem.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CloseButton.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/Devices.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ShareColors.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt
This PR displays podcast reimagine sharing page. It is only UI and without view pager for card selection. Also, the issue with tablets described [here](https://github.com/Automattic/pocket-casts-android/pull/2518#pullrequestreview-2198387211) should be fixed now.
Designs: HR2vcQrWcS0scsolKZBitg-fi-2203_2359
1. Share a podcast.
2. Verify the UI and the page's behavior.
Because it is the first integration of social platforms bar you can also test it. Check if the app detects correctly if the apps installed on your device. Note that the page doesn't update itself live for installed apps. You need to reopen the page to verify installations.
| Portrait | Landscape |
| - | - |
| ![Screenshot_20240725-121040](https://github.com/user-attachments/assets/2e3545cf-f8a1-4950-a383-ee92adad59f8) | …
=> Display podcast sharing UI

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml
This PR displays episode reimagine sharing page. It is only UI and without view pager for card selection.
Designs: HR2vcQrWcS0scsolKZBitg-fi-2203_2362
1. Share an episode.
2. Verify the UI and the page's behavior.
| Portrait | Landscape |
| - | - |
| ![Screenshot_20240725-142250](https://github.com/user-attachments/assets/d13dd262-ce05-464f-af71-af995ebdc60c) | ![Screenshot_20240725-142258](https://github.com/user-attachments/assets/803c02e1-8cf3-4622-ba67-8dfb5fea2957) |
=> Display episode sharing UI

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/TimestampType.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml
This PR displays episode timestamp reimagine sharing page. It is only UI and without view pager for card selection.
Designs: HR2vcQrWcS0scsolKZBitg-fi-2203_2447
1. Share an episode at current position.
2. Verify the UI and the page's behavior.
3. Tapping on social icons should mock-share it as an episode.
4. Share a bookmark.
5. Tapping on social icons should mock-share it as a bookmark.
| Portrait | Landscape |
| - | - |
| ![Screenshot_20240725-144517](https://github.com/user-attachments/assets/cf79cf4a-3599-4e7c-afc1-08bb20bc4b79) | ![Screenshot_20240725-144525](https://github.com/user-attachments/assets/a6a40d2b-e52a-4414-8b8e-059aeb92fe02) |
=>  Display episode timestamp sharing UI

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
We received user reports that the autoplay on Android Auto didn't work. The autoplay code needs to know where the episode was played from, this is now set.
Internal reference: p1721726696532059-slack-C02A333D8LQ
1. Plug in real device
2. Start the Android Auto emulator
```
cd ??/android-sdk/extras/google/auto/
chmod +x ./desktop-head-unit
./desktop-head-unit --usb
```
3. In Android Auto, open the podcasts tab
4. Open a podcast
5. Play an episode
6. Move the playback position to the end and let the episode complete
7. ✅ Verify another episode from the podcast is started
8. Open a filter
9. Play an episode
10. Move the playback position to the end and let the episode complete
11. ✅ Verify another episode from the filter is started
=> Fix autoplay on Android Auto

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CardData.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CardType.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ShareColors.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PagerDotIndicator.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PagerDotIndicator.kt
This PR adds paging to sharing. Paging is available only in the portrait mode. Landscape always displays horizontal card. This is because the vertical card would look really bad on non-tablet devices.
1. Start podcast sharing flow. You should be able to page between different cards.
2. Start episode sharing flow. You should be able to page between different cards.
3. Start episode position sharing flow. You should be able to page between different cards.
4. Start bookmark sharing flow. You should be able to page between different cards.
=> Add card paging to sharing

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
A user reported in the beta that tapping a user file in the Up Next no longer opened the episode dialog. This fixes that issue. I believe this was introduced in 7.69 so I haven't added a change log entry and have targeted the release branch. 
1. Add a user file episode
2. Add the episode to the Up Next, in the Up Next and not the playing episode
3. Tap the "Up Next" tab
4. Tap the user episode
5. ✅ Verify the user file dialog is opened
6. Close the dialog
7. Tap the Up Next icon in the mini player
8. Tap the user episode
9. ✅ Verify the user file dialog is opened
https://github.com/user-attachments/assets/1a5146f5-e54b-4ac4-8c3b-e70ce273add5
=> Fix Up Next user files opening episode dialog

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/ShareActionsTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ShareActions.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ShareStarter.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/social/SocialPlatform.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CardType.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/services/localization/src/main/res/values/strings.xml
This PR adds `SharingClient` and uses it for podcast sharing. It will eventually replace `ShareActions`, but more features like analytics and support for other media types need to be added before it can fully replace it.
Currently, the copy link feedback message is displayed in a Toast instead of a Snackbar. I will add Snackbar support in a different PR.
1. Share a podcast to Stories. It should fail with a toast message.
2. Share a podcast to WhatsApp, Telegram, X, and Tumblr. You need to have these apps installed on your device for them to be displayed in the social sharing bar. Also they are displayed in that precedence. So if you have Instagram and WhatsApp you won't see Telegram.
3. Share a podcast using `Copy link`. On SDK >= 33, you'll see a native feedback prompt. On SDK < 33, …
=> Share podcasts to different platforms

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/services/localization/src/main/res/values/strings.xml
This PR uses `SharingClient` for episode sharing.
Currently, the copy link feedback message is displayed in a Toast instead of a Snackbar. I will add Snackbar support in a different PR.
1. Share an episode to Stories. It should fail with a toast message.
2. Share an episode to WhatsApp, Telegram, X, and Tumblr. You need to have these apps installed on your device for them to be displayed in the social sharing bar. Also they are displayed in that precedence. So if you have Instagram and WhatsApp you won't see Telegram.
3. Share an episode using `Copy link`. On SDK >= 33, you'll see a native feedback prompt. On SDK < 33, you'll see a Toast.
4. Share an episode using `More`. It should open a sharing sheet.
When sharing, you can verify card and source selection through logs using the …
=> Share episodes to different platforms

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/social/SocialPlatformTest.kt, modules/services/localization/src/main/res/values/strings.xml
This PR uses `SharingClient` for episode position sharing.
Currently, the copy link feedback message is displayed in a Toast instead of a Snackbar. I will add Snackbar support in a different PR.
1. Share an episode at current position to Stories. It should fail with a toast message.
2. Share an episode at current position to WhatsApp, Telegram, X, and Tumblr. You need to have these apps installed on your device for them to be displayed in the social sharing bar. Also they are displayed in that precedence. So if you have Instagram and WhatsApp you won't see Telegram.
3. Share an episode at current position using `Copy link`. On SDK >= 33, you'll see a native feedback prompt. On SDK < 33, you'll see a Toast.
4. Share an episode at current position using `More`. It should open a sharing …
=> Share episode positions to different platforms

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampListener.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ShareColors.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt
This PR displays sharing feedback messages in a Snackbar instead of Toast. I didn't use the default Snackbar implementation because I have to control theming based on a podcast and the deafult implementation doesn't have an easy way to control text's color.
Designs: HR2vcQrWcS0scsolKZBitg-fi-2345_20311
1. Share a podcast to Instagram.
2. You should see a snackbar feedback message.
3. Share an episode to Instagram.
4. You should see a snackbar feedback message.
5. Share an episode position to Instagram.
6. You should see a snackbar feedback message.
=> Display sharing feedback in a snackbar

gradle/libs.versions.toml, modules/features/sharing/build.gradle.kts
This PR adds FFmpeg in debug variants only. Release is skipped for now since the binary is quite big and we don't need it yet in production.
Green CI is enough. But you can smoke test different app variants if they do not crash.
=> Include ffmpeg in debug variants

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextDao.kt
Boolean constants were added to SQLite in [`3.23`](https://www.sqlite.org/releaselog/3_23_0.html) which is SDK 30. The query crashed on older devices.
=> Fix pre SDK 3.23 SQL boolean constants

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt
This removes highlighting and scrolling capabilities for transcripts as the audio <-> text sync is currently inaccurate. 
This matches iOS behavior ([Ref](https://href.li/?https://github.com/Automattic/pocket-casts-ios/pull/1867#pullrequestreview-2172307195)).
2. Play an episode having a transcript
3. Open full-screen player
4. Tap on the transcript bottom shelf icon
5. ✅ Notice that the transcript is shown but cues are not highlighted or scrolled based on playback position
** I also do not parse the transcript until the transcript view is open in eaa17369026170eb8514c249fcf6575b22e05472. Verify that newly added tests are green.
=> Transcripts - Disable highlight and scroll

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, gradle/libs.versions.toml, modules/features/sharing/build.gradle.kts, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalytics.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipListener.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt, modules/services/localization/src/main/res/values/strings.xml
This PR adds clip link sharing. Link is always copied to the clipboard.
1. Go to the clip creation.
2. Share a clip as link.
3. It should be copied to your clipboard. Currently, on older devices feedback message is displayed in a Toast instead of a Snackbar.
=> Add clip link sharing

.gitignore
They're generated if `configure_update` detects a conflict between existing files and these from recent mobile secrets
Internal reference: p1722587393513229-slack-CC7L49W13
=> Ignore `*.bak` files

CHANGELOG.md, app/src/main/AndroidManifest.xml
This PR improves deep linking capabilities. Before, only exact `https://pocketcasts.com/get` opened the app. Even `https://pocketcasts.com/get/` failed. Now, any `https://pocketcasts.com/get**` should be handled.
Context: p1722525720721999-slack-C06EHRAPW12
> [!note]
> Test this with the `release` variant signed with the production key.
1. Open this PR on your device or copy the instructions somewhere where you can access links from your device.
2. Tap on this link - https://pocketcasts.com. It should open the website.
3. Tap on this link - https://pocketcasts.com/podcast-producers. It should open the website.
4. Tap on this link - https://pocketcasts.com/gettysburg. It should open the not found website.
5. Tap on this link - https://pocketcasts.com/get. It should open the app.
6. Tap on …
=> Handle all https://pocketcasts.com/get deep links

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
When refactoring sharing code to use the `SharingClient` I forgot to use `podcast_screen_share_tapped` event. I'm not adding it to the `SharingClient` because it is a legacy event and it's a bit awkward to put it there when it is a very specific event for a very specific screen.
1. Go to a podcast.
2. Tap on share icon.
3. `podcast_screen_share_tapped` should be tracked.
=> Bring back podcast_screen_share_tapped event

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalytics.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingLogger.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/di/SharingModule.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelector.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt
Some small cleanup of the sharing code.
* Removed unnecessary Showkase annotations.
* Decoupled `SharingClient` from analytics and logging via listeners.
Smoke test sharing and check if analytics and logging still work.
=> Sharing code cleanup

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt, modules/services/images/src/main/java/au/com/shiftyjelly/pocketcasts/images/PocketCastsIcons.kt, modules/services/images/src/main/java/au/com/shiftyjelly/pocketcasts/images/icons/StarEmpty.kt, modules/services/images/src/main/java/au/com/shiftyjelly/pocketcasts/images/icons/StarFull.kt, modules/services/images/src/main/java/au/com/shiftyjelly/pocketcasts/images/icons/StarHalf.kt
This change tweaks the new ratings UI to match the designs. It moves the "Rate" closer to the right, reduces the space below ratings section, and switches the star icons from Material to our designs.
1. Open the podcast page
2. ✅ Verify the rating section looks correct.
| --- | --- |
| ![Screenshot_20240802_222151](https://github.com/user-attachments/assets/4f10e0cd-86d3-4bb5-9e07-f07d2739a11e) | ![Screenshot_20240802_222047](https://github.com/user-attachments/assets/996913f7-5531-4154-a248-0c31443729d0) |
**Design**
=> Tweak podcast page ratings UI

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/toolbars/textselection/CustomMenuItemOption.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/toolbars/textselection/CustomTextToolbar.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/toolbars/textselection/FloatingTextActionModeCallback.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/toolbars/textselection/TextActionModeCallback.kt
This adds select text capability.
Default text selection  in Compose Text view only allows `Copy` option: https://issuetracker.google.com/issues/235259768
I added a custom menu `Select All` to select all text and `Share` for older devices (API level < 33). In newer devices,  `Copy` option allows you to share copied text.
EDIT: `Select All` is added to [Compose 1.7.0-alpha08](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-beta06:~:text=Added%20%22Select%20all%22%20to%20all%20text%20contextual%20menus%20in%20SelectionContainer.). We will not need this custom action once 1.7.0 gets stable and we switch to it.
1. Play an episode with transcript
3. Tap on the transcript bottom shelf icon
4. Long-press on the transcript text
5. ✅ …
=> Transcripts - Add select text capability

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ClipPageState.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelectorState.kt, modules/services/localization/src/main/res/values/strings.xml
This PR adds animation for clip sharing between creating and sharing states.
Figma: HR2vcQrWcS0scsolKZBitg-fi-2345_20387
1. Start clip sharing.
2. Tap on the `Next` button.
3. Screen should animate to the sharing state.
4. Tap on the `Edit clip` button.
5. Screen should animate to the editing state.
=> Animate transition between clip sharing steps

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt
- This fixes the issue reported here https://github.com/Automattic/pocket-casts-android/issues/2577
Fixes #2577
1. Open the Rating menu of any podcast
2. Dismiss the overlay by swiping it down
3. Put the app in background
4. Reopen the app
5. ✅ Make sure you don't see the rating bottom sheet reopen again
[Screen_recording_20240806_141712.webm](https://github.com/user-attachments/assets/49e230ba-4be5-4db6-b725-9a03a4c95494)
=> [Give Rating] Fix: Ratings Overlay reappears when swiped down

modules/features/kids/build.gradle.kts, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsBottomSheetDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsSendFeedbackDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/feedback/FeedbackManager.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/viewmodel/KidsSendFeedbackViewModel.kt, modules/features/kids/src/test/java/au/com/shiftyjelly/pocketcasts/KidsSendFeedbackViewModelTest.kt, modules/features/kids/src/test/java/au/com/shiftyjelly/pocketcasts/kids/feedback/FeedbackManagerTest.kt, modules/services/protobuf/src/main/proto/sync_api.proto, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
- This sends the anonymous feedback using the `/anonymous/feedback` endpoint. I will add another PR to handle an non anonymous feedback, witch is for the case the user is logged in.
- This PR does not handle UI feedback after sending the request. I will work on the snack bar feedback in a later PR
- See: p1722564959720889/1722564947.563029-slack-C07CGGZR59U
1. Have the Kids Feature flag enabled
2. Go to Profile -> Request Early access -> Send Feedback
3. Type something to enable the Send Feedback button
4. Send feedback
5. ✅ Ensure the `/anonymous/feedback` is called (check on logcat) 
6. If you want to see the feedback sent to the email you can follow these steps: p1722955409841369/1722954751.866389-slack-C07CGGZR59U
[Screen_recording_20240806_123157.webm](https://github.com/user-attachme …
=> [Kids Profile] Send Anonymous feedback

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPageColorPreview.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelector.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Devices.kt
A simple cleanup for the clip sharing page. I want to do this in a separate PR to minimize changes when adding paging. Some changes to the code:
1. `Devices` are moved to the common `:compose` module and I added a foldable device.
2. I added ability to override size for cards. I'll need it to manage displayed cards on different devices like foldables.
3. I added a visibility animation to showing sharing page content. It most likely won't have much of an effect but it might help in cases where SQL queries get slow.
=> Clip sharing page cleanup

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CardType.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/EpisodeCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/PodcastCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt
This PR uses scrolling card pattern established in #2579 in other sharing screens.
Test UI of podcast, episode, and episode timestamp sharing pages.
| Pixel 6 | Small device |
| - | - |
| ![Screenshot_20240807-201319](https://github.com/user-attachments/assets/edc1b0d9-4c81-45e5-849f-56e6bf695582) | ![Screenshot_20240807_201517](https://github.com/user-attachments/assets/30785f62-6523-4980-87e5-e7447728084b) |
=> Use scrolling card pattern in sharing screens

CHANGELOG.md, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsBottomSheetDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsSendFeedbackDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/feedback/FeedbackManager.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/viewmodel/KidsSendFeedbackViewModel.kt, modules/features/kids/src/test/java/au/com/shiftyjelly/pocketcasts/KidsSendFeedbackViewModelTest.kt, modules/features/kids/src/test/java/au/com/shiftyjelly/pocketcasts/kids/feedback/FeedbackManagerTest.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
- After implementing the anonymous feedback here https://github.com/Automattic/pocket-casts-android/pull/2581 this PR includes the non anonymous feedback, which is for the case the user is logged in.
- This uses the other endpoint `/support/feedback`
- Also, displays an snack bar after sending the feedback form
Fixes #2511
- Have the Kids Feature flag enabled
- Follow these steps: p1722955409841369/1722954751.866389-slack-C07CGGZR59U to verify if your feedback was sent
1. Make sure you are logged in
2. Go to Profile -> Request Early access -> Send Feedback
3. Type something to enable the Send Feedback button
4. Send feedback
5. ✅ Ensure your feedback was sent. (check the testing instructions section)
6. ✅ Ensure you see the snack bar with a message
1. Make sure you are not logged in
2. Go …
=> [Kids Profile] Send feedback 

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
Attempt to fix [the crash from Sentry](https://a8c.sentry.io/issues/5690494505/?project=6711064&query=release%3Aau.com.shiftyjelly.pocketcasts.debug%407.70-rc-2%2B9257&referrer=release-issue-stream) in beta.
From the stack trace it looks like the lambda for requesting early access is getting called. ~I'm not entirely sure how is that possible because the feature is disabled. Maybe someone is experimenting with it and enabling it on its own with memory or code manipulation.~ Ok, now I know. It is from one of our devices because the crash happened in the `.debug` version. It's still better to fix in beta.
In any case, I'm not able to reproduce the bug. But I think I found the root cause. We're using `childFragmentManager` when instantiating `KidsBottomSheetDialog`. This is wrong because …
=> Use parent fragment manager instead of the child's one when creating Kids dialog

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt
- This replaces the toast to use snackbar
1. Rate a podcast
2. ✅ See the message is displayed in a snackbar
=> [Give Ratings] Display snackbar instead of toast after rating a podcast

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PocketCastsPill.kt
Follow-up to https://github.com/Automattic/pocket-casts-android/pull/2592#issuecomment-2275087479. Scaling font sizes in card assets doesn't make a lot of sense since they are supposed to be shared to other platforms and not look like 💩.
Inspect UI of sharing cards with different font sizes. The text content in cards shouldn't scale.
=> Make texts in cards non-scaling

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt
In #2530 I introduced a paging bug UI to upsell screens. The pager indicator was no longer centered below the cards.
1. Install `release` variant of the app.
2. Sign in with a brand new account.
3. You should see the onboarding upsell screen with a correctly positioned pager indicator.
4. Go to your profile.
5. You should see the embedded upsell cards with a correctly positioned pager indicator.
| Onboarding before | Onboarding after | Profile before | Profile after |
| ![upsell-2-pre](https://github.com/user-attachments/assets/1926041e-fa0d-4a2c-b63a-72ab852deffd) | ![upsell-2-post](https://github.com/user-attachments/assets/97e58dfc-2ec4-460d-831b-fdf7ff21ff28) | ![upsell-1-pre](https://github.com/user-attachments/assets/db16a79a-436a-409a-a2b3-8b2cf089fb63) | …
=> Fix pager indicator position

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt
This PR adds the landscape layout for clip sharing. It supports only horizontal card.
On large devices the card is too big. I will change it in a separate PR.
1. Start clip sharing.
2. Change your device's orientation to the horizontal one.
3. Check the sharing flow.
4. Sharing state should be persistent across configuration changes between portrait and landscape orientation.
=> Add landscape layout to clip sharing

CHANGELOG.md, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
Car manufacturers using Pocket Casts have reported that when they change the episode star it doesn't update. I believe this is because we aren't setting the rating in the media session. We don't say it's an action we support and instead use custom actions but as they are adding the action and we do support setting the value it seems like a good change to make. 
1. As this isn't possible to test in the Automotive emulator as a Timber below the `putRating` call.
2. Deploy to the Automotive emulator
4. Open the full screen player
5. Tap the overflow dots
6. Star the episode
7. ✅ Verify the media session is updated
8. Unstar the episode
9. ✅ Verify the media session is updated
=> Update the episode star value in the Media Session

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt, modules/services/localization/src/main/res/values/strings.xml
This adds a search UI for Transcripts.
Internal discussion: p1723120902384739/1723091130.165579-slack-C078746V6UX
1. Open transcript view for episode supporting transcripts e.g. ()
2. ✅ Notice search icon at the end of toolbar
3. Tap on search icon
4. ✅ Notice that a search bar is shown with an animation
5. Tap ">" arrow leading icon of the search bar
6. ✅ Notice that search bar closes with animation and search icon is visible
7. Tap on the search icon again
8. Tap close (x) icon while search bar is displaying
9. ✅ Notice that instead of screen closing, search bar is closed (this is done to prevent accidentally closing the screen while thinking that the close (x) button is to close the search bar)
10. Tap close (x) icon again while search bar is collapsed
11. ✅ Notice that the screen …
=> Transcripts - Search UI

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ClipAnalytics.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ClipShareType.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampFragment.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampViewModel.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FakeTracker.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipViewModelTest.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodeViewModelTest.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastViewModelTest.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Implementation of analytics for sharing. 
Verify these events:
* [Old sharing event](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=312:312)
* [New sharing events](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=482:485)
=> Add sharing analytics

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptFilter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptFilterTest.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt
This 
- Updates regex filters for transcripts to match iOS (mostly 1:1 mapping of iOS's `ComposeFilter`)
- Displays HTML transcripts in ComposeView (to avoid different search highlight and scrolling logic for Android and Compose views in future PRs)
1. Open transcript view for an episode with HTML mime-type (E.g. episode from `If books could kill` https://pca.st/tqib657g)
2. ✅ Notice that it is rendered properly
3.  Open transcript view for an episode with non-HTML mime-type (E.g. episode from `Cautionary Tales` https://pcast.pocketcasts.net/8zpmjiru)
4. ✅ Notice that it is rendered properly
=> Transcripts - Update filters 

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/episode/ShareEpisodePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/podcast/SharePodcastPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/timestamp/ShareEpisodeTimestampPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/EpisodeCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/PodcastCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt
Allowing cards to occupy the whole available space is wrong because when it is shared as an image or a video we scale it down to `1080x1920` bitmap. This would make fonts extremely small. This PR address this issue by constraining card sizes.
1. Preview UI in landscape layout for clip and podcast sharing on a tablet or a foldable device.
2. Preview UI in portrait mode for podcast, episode, and episode timestamp sharing on a tablet or a foldable device.
Example of a constrained square card
| - | - |
|  ![Screenshot 2024-08-12 at 09 17 29](https://github.com/user-attachments/assets/d80c8d42-8fb3-49ba-a377-ba294794e24f) | ![Screenshot 2024-08-12 at 09 17 11](https://github.com/user-attachments/assets/f5357faf-ef9b-49f7-b073-5532054b95ee) |
=> Constraint max sharing card size on all screens

modules/features/profile/src/main/res/layout/fragment_account_details.xml
When signed in with Google, the change avatar button text is incorrectly aligned. The text is set to align with the change email icon, and the change email and password buttons are hidden when signed in with Google, so this is causing an issue.  
Fixes #2621 
1. Sign in with a Google account
2. Tap the profile tab
3. Tap the account button
✅ Verify the change avatar button text is in the correct place
4. Sign out and sign in with an email and password
2. Tap the profile tab
3. Tap the account button
✅ Verify the change avatar button text is still in the correct place
| --- | --- |
| <img width="540" alt="Screenshot_20240813_153102" src="https://github.com/user-attachments/assets/2e7dba12-eac7-4308-81aa-9739beb59a6a"> | <img width="540" alt="Screenshot_20240813_152529" …
=> Fix change avatar button text alignment

.buildkite/commands/prototype-build.sh, .buildkite/pipeline.yml, fastlane/Fastfile
Based on implementation of same feature on WooCommerce-Android.
This PR introduces a feature of commenting PRs with links to build artifacts.
In WooCommerce Android, we have 2 CI job: one for mobile, and one for wear projects. It makes sense there, as mobile and wear projects have different codebases.
Because Pocket Casts is modularized, it benefits from reusing intermediate build artifacts i.e. wear or automotive apps can use the same outputs of compilation of modules, generated for mobile app.
For this reason, I think there's no point in preparing 3 different jobs. This strategy shouldn't also increase CI check overall time, as instrumentation tests step is either way longer.
If this PR will be approved, I'll:
- ~remove "required" restriction on `assemble-release-apk ` job~
- ~add …
=> Build prototype mobile app and comment on PR

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/BetaFeaturesFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/BetaFeaturesViewModel.kt
Minor tweaks to the features page
1. Play an episode so it's in the mini player
2. Open the features page
✅  Verify there is no padding at the bottom of the page and the items are sorted by title
| --- | --- |
| ![Screenshot_20240814_234837](https://github.com/user-attachments/assets/8b8d9b51-a209-496f-b36b-fbd2a6709331) | ![Screenshot_20240815_000609](https://github.com/user-attachments/assets/699a375a-6ab6-4f1b-a30d-28c006ec5a83) |
=> Tweaks to the features page

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/sharing/src/debug/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt, modules/features/sharing/src/debugProd/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ClipPlayer.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/DurationUtil.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/DurationUtilTest.kt
This PR introduces the ability to create sub-second clips with a resolution of 100 milliseconds. The key changes are as follows:
* Adjusted the frame rate of clips to 10 fps to support this finer resolution.
* Updated the format of generated filenames to use the `S.x` format (e.g., `12.3` for 12300 milliseconds) instead of the `hh:mm:ss` format for time marks.
* Modified the player to ensure it always starts playback from the specified clip position.
* Clip links are now generated with sub-second time marks to be in line with generated audio or video clips.
* Timestamp links continue to use a seconds-only resolution. This can be easily changed but I didn't want to change existing behavior and interop with bookmarks which support seconds only.
I also improved video quality by specifying …
=> Support sub-second clip resolution

modules/features/sharing/src/debug/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt, modules/features/sharing/src/debugProd/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt
QuickTime being QuickTime has issues with the standard `libmp3lame` codec. Switching to `aac` to help it.
See: p1723683477741549-slack-C02LGFKP0AE 
1. Share a video clip so you can download it on your desktop.
2. Play the clip in QuickTime.
3. It should work.
=> Use aac codec for mp4 audio

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/KMPSearch.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptSearchViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/KMPSearchTest.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptSearchViewModelTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/DispatcherModule.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/String.kt
This implements transcript search logic.
Not in scope:
- Scroll to highlighted text
- Text styling Figma match
1. Load transcript view for an episode with transcript (e.g. Cautionary Tales https://pcast.pocketcasts.net/8zpmjiru)
2. ✅ Notice that search icon is visible when transcript is shown
3. Tap on search icon
4. Search a text
5. ✅ Notice that 
- Search occurrences text is updated in the search bar (if search results are not found, 0 is displayed)
- Up, down arrow buttons are enabled if search results found
- Search occurrences are highlighted in the transcript
8. Tap on up arrow in the search bar
9. ✅ Notice that next search result is highlighted (scroll to highlighted text is not added in this PR)
10. Tap on previous arrow in the search bar
11. ✅ Notice that previous search result …
=> Transcripts - Search logic

modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsBanner.kt
The "Request Early Access" button text was looking a bit small. I have increased it after talking to the designer. While I was here I made some other tweaks so it was closer to the design.
✅  Verify the design.
Design
| --- | --- |
| ![Screenshot_20240815_132143](https://github.com/user-attachments/assets/b4083bee-3d02-4497-8530-21df772a36cc) | ![Screenshot_20240815_145008](https://github.com/user-attachments/assets/e930bb82-e4f5-4ce6-bf24-578c995f916c) |
=> Tweak kids banner style

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeLayoutFeatures.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradePlusLayoutExperiment.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/BaseRowButton.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- This adds the first changes for the paywall redesign. I will address the feature cards in a later PR and also the text below of the button
- See: SEQe6JBDCeegcpa9Bfg5Ww-fi-3_756
- The background will be the same for all themes: p1723556268631729-slack-C07G1MH890E 
- This redesign is currently behind a temporary local feature flag. We are going to change in a later PR for the testing experiment
Fixes #2630
1. Apply this [paywall.patch](https://github.com/user-attachments/files/16612993/paywall.patch)
2. Run in `debug`
3. Make sure PAYWALL_EXPERIMENT feature flag is enabled
4. Make sure you have the same account logged in Play Store
5. Go to Profile -> Settings -> Pocket Casts Plus
6. Verify the Paywall redesign
7. ✅ Make sure the background is black
8. ✅ Make sure you `Not now` button …
=> [Paywall redesign] Add the new paywall 

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt
This supports scrolling to highlighted search text **
** Currently, the view scrolls to the sentence with search text. It works well with reasonable font sizes and sentence lengths. I will get back to adding more precision after completing other important tasks for the project.
1. Load transcript view for an episode
2. Search for a text with several occurrences
3. Tap on up, next arrows
4. ✅ Notice that the view scrolls to the sentence with the search item
https://github.com/user-attachments/assets/d9e1d597-c4dd-4748-9abe-2f8af957d3d1
=> Transcripts - Scroll to highlighted search text

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt
We would like to show the user's rating on the podcast page as soon as they rate. This is done by refreshing after the rating has been sent and ignoring the cache on refresh. 
1. Search for a podcast that has no ratings
2. Open the podcast page
3. Wait for over 10 seconds (a server fix will remove this later)
4. Rate the podcast
✅  Verify the rating changes
https://github.com/user-attachments/assets/4d23ecfe-f607-482e-83bb-b1b743550296
=> Refresh the podcast rating after rating

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
The application crashes, when clicking the chapter title. The code assumes the capters index starts from 1 but instead it now starts at 0.
Fixes https://github.com/Automattic/pocket-casts-android/issues/2647
<details><summary>Exception</summary>
<p>
```
Process: au.com.shiftyjelly.pocketcasts.debug, PID: 9543
java.lang.IllegalArgumentException: Index should be non-negative (-1)
at androidx.compose.foundation.lazy.layout.LazyAnimateScrollKt$animateScrollToItem$2.invokeSuspend(LazyAnimateScroll.kt:120)
at androidx.compose.foundation.lazy.layout.LazyAnimateScrollKt$animateScrollToItem$2.invoke(Unknown Source:8)
at androidx.compose.foundation.lazy.layout.LazyAnimateScrollKt$animateScrollToItem$2.invoke(Unknown Source:4)
at androidx.compose.foundation.gestures.DefaultScrollableState$scroll$2$1. …
```
=> Fix crash when clicking on chapter title within player

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt, modules/services/localization/src/main/res/values/strings.xml
- Adds the action tapping to stars to open the rate screen
- We are going to keep the Rate button
- See: p1723652426719639/1723638851.314939-slack-C05RR9P9RAT
Fixes #2638
1. Open an podcast to rate
2. Tap on stars
3. ✅ Make sure the rate screen is open
4. Back to the previous screen
5. ✅ Tap on rating average
6. ✅ Make sure the rate screen is open
[Screen_recording_20240814_134952.webm](https://github.com/user-attachments/assets/3fa0991c-112f-4ade-a8ad-b464d14aad9f)
=> [Give Rating] Add action tapping to stars

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/social/PlatfromItem.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelector.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CloseButton.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ShareColors.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt
This PR aligns color specification with the designs. You can find it here: pdeCcb-6h3-p2#comment-5098
Test sharing colors in different contexts:
- Portrait layout
- Horizontal layout
- Podcast sharing
- Episode sharing
- Episode position sharing
- Clip sharing
- Clip sharing with TalkBack enabled
- Vertical card export to Instagram Stories
=> Adjust sharing colors

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/sharing/src/debug/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt, modules/features/sharing/src/debugProd/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/MediaService.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipPage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/clip/ShareClipViewModel.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/social/PlatfromItem.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelector.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/CloseButton.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ShareColors.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SharePage.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/VerticalCard.kt, modules/features/sharing/src/release/kotlin/au/com/shiftyjelly/pocketcasts/sharing/FFmpegMediaService.kt, modules/features/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt
This is an improvement to caching for clip sharing. Previously cache didn't take into account the shared card. This could result in wrong video background being shared because we used cached one.
1. Share a clip as a a video.
2. Without closing the sharing screen edit the clip and select a different card.
3. Share again as a video.
4. You should see a card selected in the 2nd step as a video background.
=> Improve video sharing cache

fastlane/Fastfile
Context: p1723805743869889-slack-CC7L49W13
During code freeze, after creating the `release/N` branch, we set GitHub Branch Protection settings on it to require Pull Requests with at least one reviewer etc.
But until now, we were using our `set_branch_protection` action (from our `release-toolkit` fastlane plugin), which is nowadays legacy because this action were only setting a minimal set of branch protection settings on the branch. In particular, it didn't set any "required checks" from CI to pass before allowing a PR to be merged.
This PR changes this to use the more recent `copy_branch_protection` action from our `release-toolkit`, which copies the same branch protection settings from `trunk` on the `release/N` branch instead, thus also copying the "required CI checks" from the trunk …
=> [Tooling] Apply required CI checks too when setting branch protection settings on release branch

fastlane/Fastfile
We don't have CI managed releases yet so the introduced change will prevent release manager from pushing to a release branch
See: https://github.com/Automattic/pocket-casts-android/pull/2659#issuecomment-2293569537
=> Revert copying branch protection from the main branch

fastlane/Fastfile
Add a comment to `set_branch_protection` to prevent it inadvertently being changed to `copy_branch_protection` again.
=> [Tooling] Add comment to `set_branch_protection` call

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
This change fixes the issue that when a podcast share link using an iTunes ID it fails to open the podcast. An example of a share link is [https://pca.st/itunes/1671087656](https://pca.st/itunes/1671087656). Tapping the URL should open the Pocket Casts app instead of the share web page. The issue is that we don't handle /itunes or other paths such as /feed. It seems safer to pass the URL on to search instead of handling each case in the code. 
1. Install the debugProd variant
2. Tap on this link [https://pca.st/itunes/1671087656](https://pca.st/itunes/1671087656)
✅ Verify the app is opened and the podcast page for 'This Day in AI Podcast' is shown.
3. Close the podcast page
4. Tap on this link [https://pca.st/feed/feeds.transistor.fm/this-day-in-ai](https://pca.st/feed/feeds.transistor.fm/ …
=> Handle more podcast share links

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManagerImpl.kt
- This is an attempt to fix this issue here p1724091189386829/1724091158.301499-slack-C028JAG44VD
- I believe the root cause was that we were not catching Http Exceptions when refreshing ratings after submit a new rate, so I am catching all exceptions for `RatingsManager.refreshPodcastRatings` to avoid this issue
- Smoke test give ratings feature
- Try to rate an podcast
- Update your rate
=> [Give ratings] Catch all exceptions when refreshing ratings

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeLayoutFeatures.kt, modules/services/localization/src/main/res/values/strings.xml
- Add the label for trial or 50% offer below of subscribe button
- Opens the existing upgrade bottom sheet dialog
- See: SEQe6JBDCeegcpa9Bfg5Ww-fi-3_756
- I will update the bottom sheet in a later PR
> [!NOTE]  
> 50% offer is not available for India, South Africa and Brazil. Trial offer is available for them instead 
Fixes #2628
Apply this [paywall.patch](https://github.com/user-attachments/files/16612993/paywall.patch) and run in `debug`
1. Log with a free user account
2. Access the paywall
3. ✅ Ensure you see the secondary text below of `Get Pocket Casts Plus Button`
4. Tap on this button
5. ✅ Ensure the bottom sheet upgrade opens
6. Tap on subscribe button
7. ✅ Ensure the Google play bottom sheet opens
[new.webm](https://github.com/user-attachments/assets/25ced3d3-0fcd-4a2f-9a12-c49cba …
=> [Paywall Experiment] Updates the Paywall experiment screen

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt
Since changing how the show notes endpoint works, they weren't being cached correctly, this change fixes that. 
1. Freshly install the app
2. Open the "App Inspection" window and the "Network Inspector" tab
3. Open a podcast page
4. Clear the network data
5. Tap an episode row
✅ Notice there are two requests, one to podcast-api.pocketcasts.net and one to shownotes.pocketcasts.net
✅ Verify the show notes load
6. Rerun the app and connect the app inspection window again
7. Open a podcast page
8. Clear the network data
9. Tap an episode row
✅ Verify there is only one request to podcast-api.pocketcasts.net and the show notes load
10. Rerun the app and connect the app inspection window again
11. Put the phone in airplane mode
12. Open a podcast page
13. Tap an episode row
✅ Verify the show …
=> Fix show notes cache

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptJsonParser.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt
This supports JSON transcript format.
1. Prioritise `TranscriptFormat.JSON_PODCAST_INDEX` in `TranscriptsManagerImpl.supportedFormats` at line 22
2. Install the app 
3. Play [this episode](https://pca.st/episode/cadc4a0f-97c3-47c6-9e7d-16452a2cf18a) from `Chaosradio`
4. Open transcript view
5. Notice that JSON format transcript is loaded
Loaded from [transcript content](https://chaosradio.de/cr291-vorratsdatenspeicherung?podlove_transcript=json_podcastindex)
=> Transcripts - Support json format

CHANGELOG.md, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterChipFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterContainerFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterViewModel.kt
While looking through the Google Play console crashes, I noticed this issue. It's not common, but I thought it was worth fixing. The issue happens on the create filter screen, as the `playlists` variable is a `lateinit`. It seems like the variable isn't being initialised quickly enough before some users call `CreateFilterContainerFragment.onDetach` which assumes the variable has been initialised.
```
Crash: Fatal crash.
kotlin.UninitializedPropertyAccessException: lateinit property playlist has not been 
at au.com.shiftyjelly.pocketcasts.filters.CreateFilterViewModel.getPlaylist
at au.com.shiftyjelly.pocketcasts.filters.CreateFilterViewModel$clearNewFilter$1.
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at …
```
=> Fix create filter crash

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowEpisodeDeepLinkTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowPodcastDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt, modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
Engage SDK has these required attributes on the `PodcastEpisodeEntity`.
Currently we don't have automatic playback capability from a deep link. This PR adds support for it. I also added support for a source view. Even though Enage SDK adds their own `source_tag` query parameter I prefer to have our custom one so it has a wider support.
Do regressions tests on opening episode details. Open it from different contexts and make sure that they don't auto play.
Use this for deep linking into episodes:
```
adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://pca.st/episode/<EPISODE_ID>?auto_play=<VALUE>"
```
Episode should start auto playing only when `auto_play` is present and is set to `true`.
=> Handle automatic playback from deep links

.github/dependabot.yml
It would be good to use GitHub Dependabot to help us keep the project libraries up to date. This PR adds the configuration file. 
I asked the apps infrastructure team for some advice setting this up.  p1724292683965449-slack-CC7L49W13 
We might have to test this by trying it. If the pull requests are too noisy or incorrect, we can change this configuration.
=> Upgrade libraries with Dependabot

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/HorizontalCard.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/SquareCard.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PocketCastsPill.kt
This PR adds logo to shared horizontal and square cards. See: pdeCcb-50w-p2#comment-5190
1. Share something to IG with a horizontal card. It should contain PC logo.
2. Share something to IG with a square card. It should contain PC logo.
| Horizontal | Square |
| - | - |
| ![h](https://github.com/user-attachments/assets/6d3b3acc-7498-4509-8dc4-84b9c7615341) | ![s](https://github.com/user-attachments/assets/911b892c-003a-4913-9c03-34b74729f7aa) |
=> Add Pocket Casts logo to all cards

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
- Opens the upgrade bottom sheet dialog with the last selected tier from Profile
Fixes #2675
1. Run the app in `debug`
2. Disable `PAYWALL_AB_EXPERIMENT ` feature flag
3. Log with a free user account
4. Go to Profile -> Account
5. Tap on `Subscribe to Plus` button
6. ✅ Ensure bottom sheet dialog opens with Plus option
7. Back to Account -> Swipe right on upgrade view
8. Tap on `Subscribe to Patron` button
9. ✅ Ensure bottom sheet dialog opens with Patron option
=> Fix: Upgrade bottom sheet was not opening with the last selected tier

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfBottomSheetViewModel.kt
This disables the transcript shelf menu item if transcript is not available for an episode
2. Play an episode
3. Move transcript icon in the mini player to shelf menu
4. Play an episode with transcript
5. ✅ Notice that transcript icon in shelf menu is enabled
6. Play another episode without transcript
7. ✅ Notice that transcript shelf menu is disabled
https://github.com/user-attachments/assets/f6cbbe27-dc00-4b1e-9b74-5fcbc667c269
=> Transcripts - Disable transcript from shelf more options if transcript not available

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelector.kt, modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ui/ClipSelectorState.kt
Some small improvements to clip sharing:
- Added scrolling to timeline handles on long pressing the time label.
- Added small empty space at the end of the timeline to provide easier end handle grabbing.
1. Start clip sharing.
2. Put handles in some positions and scroll them out of your view.
3. Long press start label. It should scroll you back to the start handle.
4. Scroll timeline selector out of your view.
5. Long press end label. It should scroll you back to the end handle.
6. Scroll to the very and of the timeline. There should be small empty space.
=> Improve clip timeline interactions

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptError.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptJsonConverter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/TranscriptJsonConverter.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/TranscriptCuesInfo.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptCuesInfoBuilder.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptCuesInfoBuilderTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/exception/EmptyDataException.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/exception/ParsingException.kt
This extracts cue building from the VM to a builder and loads cues from the manager. 
This will help us know empty transcripts while downloading episodes, allowing fallback to alternative transcripts later ([PR](https://github.com/Automattic/pocket-casts-android/pull/2704)). 
1. CI should be green
2. Smoke test that you can still load transcripts as before
3. Notice that currently, you see an empty transcript error for any episodes from chaosRadio (eg. https://pca.st/r2ct46up)
=> Transcripts - Extract cue building to builder and load cues from manager

base.gradle, gradle/libs.versions.toml, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/BetaFeaturesFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/ManualCleanupFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt
This change upgrades the fragment library to 1.8.2. Starting with the Fragment 1.7 release, a new `content` extension removes some of the old boilerplate code, so I have applied this to some classes to try it out. 
1. Go to the Profile tab
2. Tap Bookmarks
3. Go back
4. Tap on the settings cog
5. Tap on Advanced
6. Go back
7. Tap on Beta features
8. Go back
9. Tap on Headphone controls
10. Go back
11. Tap on Storage settings
12. Go back to the Profile page
13. Tap on Downloads
14. Tap the three dots in the toolbar
15. Tap Clean up
✅  Verify all the pages load correclty.
=> Upgrade to Fragment 1.8.2

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptDefaults.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt
This reduces landscape search scroll offset to minimize hiding of text behind the keyboard (pdcxQM-43M-p2#comment-3190).
1. Open transcript view in landscape mode
2. Search a term
3. ✅ Notice that the highlighted search item text offset from the top is reduced now
Floating | Expanded
----|---
=> Transcripts - Reduce landscape search scroll offset

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallfeatures/FeaturesPaywallCards.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallfeatures/UpgradeLayoutFeatures.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
- Adds the new featured cards in the paywall experiment
- Updates the Plus pill to have gradient effect
Fixes #2631
1. Apply this [paywall.patch](https://github.com/user-attachments/files/16612993/paywall.patch) and run in `debug`
2. Have `PAYWALL_AB_EXPERIMENT` feature flag enabled
3. Open paywall
4. ✅ Ensure plus pill has gradient effect
5. ✅ The new featured cards are displayed added here https://github.com/Automattic/pocket-casts-android/pull/2660
Try with different screen sizes and font sizes
| Regular Device | Small Device |
| <img src="https://github.com/user-attachments/assets/cea97c62-ae69-4e00-9d39-07d0d9d4dcdb" width="400px"> | <img src="https://github.com/user-attachments/assets/a35b9d14-1a34-4745-991a-372879d6ae06"  width="400px"> |
=> [Paywall Experiment] Add new featured cards instead of the old ones

.github/ISSUE_TEMPLATE/bug_report.yml, .github/dependabot.yml
As we are reorganising the project labels, this changes the default label for new issues and for Dependabot PRs.
I don't think we can test this until we merge it.
1. Go to the issues tab
2. Click "New issue"
3. Next to Bug report click "Get started"
✅  Verify the label added is `[Type] Bug`
=> Change the labels for new issues and Dependabot PRs

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt
This removes search leading icon from the search bar to make more space for search text (pdcxQM-43M-p2#comment-3201)
1. Open search bar on the transcript view
2. ✅ Notice search leading icon is removed from the search bar 
Before
After
Touch ripple
The space between the cursor and the done arrow is to accommodate the ripple circle in touch mode.
=> Transcripts - Remove search leading icon

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
- This excludes the Patron subscription upgrade flow from the paywall experiment, which means when the user tries to upgrade their account and have the A/B test enabled we are going to keep displaying the original paywall layout for Patron
- See: p1724680026883349/1724675119.013999-slack-C07G1MH890E
Fixes #2719
1. Have an Pocket Casts Champion account. See how to get it set PdNHOb-2Q-p2
2. Have `PAYWALL_AB_EXPERIMENT` and `PAYWALL_AA_EXPERIMENT` feature flag enabled
3. Go to Profile -> Account -> Tap on `Upgrade to Patron`
4. ✅ Ensure the original Patron paywall is shown
5. Repeat the steps above with `PAYWALL_AB_EXPERIMENT` and `PAYWALL_AA_EXPERIMENT` feature flag disabled
6. ✅ Ensure the original Patron paywall is shown
=> [Paywall Experiment] Exclude patron from experiment

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt
- Adds source to rating tapped event
- See slack thread: p1724418630334649/1723689598.833749-slack-C077XU4GF9D
- See iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/2090
Fixes #2721
1. Run the App
3. Expand the header
4. Tap on Rate Button
5. Make sure you see 🔵 Tracked: rating_stars_tapped ["source": "button", "uuid": PODCAST_UUID]
6. Close the rate screen
7. Tap on the stars
8. Make sure you see 🔵 Tracked: rating_stars_tapped ["source": "stars", "uuid": PODCAST_UUID]
=> [Give Rating] Add new source for rate tapping event 

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptDefaults.kt, modules/features/player/src/main/res/layout-sw600dp/adapter_player_header.xml, modules/features/player/src/main/res/values-land/bools.xml, modules/features/player/src/main/res/values-land/dimens.xml, modules/features/player/src/main/res/values-sw600dp/bools.xml, modules/features/player/src/main/res/values-sw600dp/dimens.xml, modules/features/player/src/main/res/values/bools.xml, modules/features/player/src/main/res/values/dimens.xml
This updates large screens landscape layout to be the same as the portrait layout so that player controls and seek bar are centered horizontally, similar to iOS. This helps in reusing the same transition we use for the portrait mode when going to the transcript screen and enabling the player controls (pdcxQM-43M-p2#comment-3193).
1. Open the app on a tablet in landscape mode
2. Play an episode having transcript (e.g. [Cautionary tales](https://pca.st/episode/1a31aba0-9d4f-416c-abb3-0945431fc2c9))
3. ✅ Notice that the landscape mode layout is same the portrait one
4. Open transcript view
5. ✅ Notice the player controls are transitioned to the transcript view
**Before**
https://github.com/user-attachments/assets/faf1a01a-889e-4678-b8f3-922c68dcb579
**After** …
=> Transcripts - Display player controls on landscape large screens 

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJobTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeActionTest.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectAction.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarkAction.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeAction.kt
We have received user feedback that their re-ordering of the multi-select toolbar action is getting reset. This happens after a new version is released, as the resource IDs change with the new build. This change switches to using a hardcoded string ID, and there is a migration to make sure the users action orders aren't changed again. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/2492
1. Subscribe to a podcast
2. Open the podcast page
3. Long press an episode 
4. Tap the three dots in the toolbar
5. Tap the pencil to edit the order
6. Change the order
7. Tap the back arrow
✅ In the "Device Explorer" open the shared preference file `/data/data/au.com.shiftyjelly.pocketcasts.debug/shared_prefs/au.com.shiftyjelly.pocketcasts.debug_preferences.xml`.
Check the …
=> Fix multi-select tool bar action order

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/res/drawable/ic_gift.xml, modules/features/profile/src/main/res/layout-land/fragment_profile.xml, modules/features/profile/src/main/res/layout/fragment_profile.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This adds a local feature flag for the referrals project and a gift icon on the Profile screen to test it.
**Figma**: FVJPaWlRMlosEpsRhqxnSD-fi-2189_9583 (there's an open question about screen title)
** active passes icon count added in https://github.com/Automattic/pocket-casts-android/pull/2746
Closes #2728
1. Launch app without sign in or sign in as free account
2. Go to `Profile` -> `Settings` -> `Beta features`
3. ✅ Notice that `Referrals` beta feature flag is enabled for debug build
4. Go back to the `Profile` screen
5. ✅ Notice that a gift icon is not present
6. Sign in with a paid account (plus or patron)
7. ✅ Notice that a gift icon is present
- on the top start of the screen in portrait mode
- before settings icon in landscape mode
8. Disable `Referrals` beta feature flag …
=> Referrals: add feature flag

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt
During #2735 I missed adding the `User-Agent` interceptor for the downloads client. This fixes it.
Smoke test downloading some episodes.
=> Add missing user agent interceptor

modules/services/crashlogging/build.gradle.kts, modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/FilteringCrashLogging.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
This PR include feature flags state in Sentry reports and in user logs.
1. Go to our developer settings and long press "Report a crash".
2. Set a custom message.
3. Tap a couple of time on "Report a crash" to send a report to Sentry. You need to tap a couple of times due to sampling.
4. Go to Sentry and find your crash.
5. You should see `feature_` tags.
6. Go back to the app.
7. Go to "Help & feedback".
8. Open logs.
9. Notice feature flag entries in the logs.
=> Include feature flags state in reports

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.yml
This change improves our create issue page. It will help with triaging new issues by not labelling everything as a bug, there is new an enhancement form. I have linked the feature request to the forums instead of the GitHub discussions. The HEs assist with answering these messages in the forums and feature requests can often be cross platform.
**🐞 Bug report**
Report a bug if something isn't working as expected in the Pocket Casts Android app.
**✨ New enhancement**
If you have a suggestion to improve an existing feature in the Android app please let us know.
**Report a security vulnerability**
Please review our [security policy](https://github.com/Automattic/pocket-casts-android/security/policy) for more details.
**🚀 Feature request**
Suggest a new feature on the forum. We'll consider …
=> Improved create issue screen

app/proguard-rules.pro, base.gradle, gradle/libs.versions.toml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AlbumArtContentProvider.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/images/ThemedImageTintTransformation.kt, wear/proguard-rules.pro
We have a pending Glide update in #2755. But I think it is pointless to keep this library. The only real place where it is used is `AlbumArtContentProvider`, which is used for integration with the notification center, Auto, and Automotive. This can be easily replaced with simply downloading a file. The other uses have been long replaced with `Coil`.
There also a Glide transformation but the code is shared with a Coil transformation and we don't load images with Glide anywhere so AFAIK it is safe to remove.
1. Install clean version of the app so nothing is cached.
2. Test that images in the media notification center are not low quality.
4. Test that images in Android Auto load.
5. Test that images in Android Automotive load.
=> Remove Glide dependency

Dangerfile
To help with our QA reports, all our pull requests should have a `[Type]` label and either an `[Area]` or `[Project]` label. This PR changes Danger to remind us. 
Documentation on the Danger labels checker [can be found here](https://gemdocs.org/gems/danger-dangermattic/1.1.2/Danger/LabelsChecker.html).
It worked on this PR.
=> Change labels required on a PR

app/build.gradle.kts, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
Remove Engage SDK integration for now. Until we get approval from Google it'd be better to not have it in the codebase to not include any unnecessary review checks.
=> Remove Engage integration

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
Fixes the UI glitch for Subscribe button in Original Paywall when you hold your 
Fixes #2772
1. Log with a free account
2. Have `PAYWALL_AB_EXPERIMENT` disabled
3. Open paywall
4. ✅ Ensure you don't see the glitch reported on #2772
=> Fix: UI glitch for Subscribe button in Original Paywall

Gemfile, Gemfile.lock
This PR: 
1. Updates the `rexml` gem to `3.3.6` to fix the recent CVE. 
2. Removes the `pluginfile` section from the `Gemfile` since we don't use `pluginfile`s. The `pluginfile` section was also producing an error for Dependabot's PR auto-creation: https://github.com/Automattic/pocket-casts-android/security/dependabot/66
=> RubyGems: Fix rexml vulnerability

.github/dependabot.yml
During the tech debt upgrade of the dependencies, it will be easiest if we turn off Dependabot.
=> Temporarily disable Dependabot

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/IconButtonSmall.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt, modules/services/localization/src/main/res/values/strings.xml
This updates
- Transcripts search bar (tzuqhOmpPVu5TjKK1XMhf5-fi-598_1999) icon size and height
- Close button action to only close the screen
Internal Ref: pdcxQM-43M-p2#comment-3215
1. Open transcript view
2. Tap the search icon
3. ✅ Notice that search bar leading and trailing icons size** is reduced, along with spacing between the close button and search bar 
4. Tap close (x) button
5. ✅  Notice that it closes the screen instead of the expanded search bar 
** I reduced search bar leading and trailing icon size from default `48dp` to `32dp`. Reducing it further made them too close but it might just be me. 
Before | After
----|----
Ripple
Before | After
----|---
|Landscape|
|-----|
|<img width=800 src="https://github.com/user-attachments/assets/2471a748-a7c2-4f6a-90aa-dbbd9f2a96a8"/>| …
=> Update transcripts search bar

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountActivity.kt
- This removes the deprecated android onBackPressed
- https://developer.android.com/reference/androidx/activity/ComponentActivity#onBackPressed()
1. Run the app
2. On the Sign Up / Log in screen
3. Press back
4. ✅ Ensure the screen is closed
5. Open the Sign Up and press back
6.  ✅ Ensure the screen is closed
7. Open Log in -> Forgot password and press back
8.  ✅ Ensure the screen is closed
=> [Tech Debt] Remove deprecated onBackPressed from Account

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/activity/WebViewActivity.kt
- Removes the onBackpressed from WebView and clean up unused variable
> [!note]
> Before starting the test make sure in the settings that the app is able to intercept the links.
1. Install the app in debugProd and sign in.
3. Send intent via ADB with start and end timestamps. For example: `adb shell am start -a android.intent.action.VIEW -d https://pca.st/y0ebrkcc\?t=20,60`.
4. Press back button
5. ✅ Ensure the screen is closed
=> [Tech Debt] Remove deprecated onBackPressed from WebView

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
- This removes the deprecated onBackPressed
1. Run the Automotive App
2. Go to Automotive Settings
3. Press back
4. ✅ Ensure it returns to the previous screen
5. Go to Automotive Settings -> About
6. Press back
7. ✅ Ensure it returns to the previous screen
8. Press back again
9. ✅ Ensure it returns to the previous screen
=> [Tech Debt] Remove deprecated onBackPressed from Automotive Settings

modules/services/media-ffmpeg/src/main/kotlin/au/com/shiftyjelly/pocketcasts/media/FFmpegMediaService.kt
This makes exported file names prettier. Previously we replaced all non word characters with and underscore. This keeps blank space in the file name.
1. Share an audio or video clip as a file somewhere.
2. The file name should have a format of `<podcast> <episode> <timestamps>(optional card type)`.
=> Use spaces instead of underscores in clip file names

app/build.gradle.kts
Fixes missing Showkase preview in the app.
Context: p1725672825089339-slack-C07J5LNP4SF
Check if you can preview Showkase components in the app.
=> Use showkase KSP processor in the :app module

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
- Remove deprecated `setUserVisibleHint` from Filters code
- Smoke test Filters
=> [Tech Debt] Remove deprecated code from filters

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
I've noticed [this issue](https://a8c.sentry.io/issues/5790904916/?project=6711064&query=release%3Aau.com.shiftyjelly.pocketcasts) in Sentry. It is related to my changes introducing auto play through deep link. When trying to avoid auto playing on configuration changes I inadvertently prevented view model from being set up during process death.
1. Start the app.
2. Go to any episode details.
3. Minimize the app.
4. Run `adb shell am kill au.com.shiftyjelly.pocketcasts.debug`.
5. Reopen the app.
6. There should be no crash.
1. Run `adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.ui.MainActivity -a android.intent.action.VIEW -d "https://pca.st/episode/49900dc4-d6de-4673-b894-2da321b307d0?auto_play=true"`
2. The episode should start playing.
3. Pause …
=> Fix deep link auto play crash

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt, modules/features/podcasts/src/main/res/layout/fragment_podcast.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
The background colors on the podcast page didn't look right in the dark theme so I have improved them. I have also changed the Plus text from white to black.
1. Change the theme to dark
2. Subscribe to a podcast with only a few episodes such as "How to do everything" by NPR
3. Open a podcast page
4. ✅ Verify the loading background is the same color as the final page
5. ✅ Verify the bottom of the episodes and bookmarks tab are the same color
| --- | --- |
| ![Screenshot_20240907_101707](https://github.com/user-attachments/assets/6b76e111-214b-410b-9acf-2b906ccd059c) | ![Screenshot_20240907_101852](https://github.com/user-attachments/assets/38dd5d22-55fe-44c6-9dc2-11f432078918) | 
| ![Screenshot_20240907_101730](https://github.com/user-attachments/assets/6e66d255-d4db-44b1 …
=> Improve the podcast page background color

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
Fixes showkase compilation issues introduced in 361590b7fe37d1ffbe8583d410808140ad0733dc.
Green CI is enough.
=> Fix showkase default style compilation error

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/SwipeableStars.kt
- This PR addresses the alpha animation to the submit rating button reported here https://github.com/Automattic/pocket-casts-android/issues/2656
- For the stars issue reported on #2656 I could not reproduce, so that's why this PR addresses only one part of the reported issue
2. Listen to some episodes to be able to rate this podcast
3. Rate the podcast
4. Open the rate screen to rate again the podcast
5. Select a different rate so the button can be visible again
6. Ensure the submit button has some animation when changing their visibility
[Screen_recording_20240910_135652.webm](https://github.com/user-attachments/assets/0b75857a-a63b-435e-9245-09efde34efdb)
=> [Ratings] Tweak to Ratings

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Deletes `GIVE_RATINGS` and unused `CATEGORIES_REDESIGN` feature flags
Smoke test rating.
=> Remove ratings feature flag

build.gradle.kts, gradle/libs.versions.toml
Compose Compiler is now embedded into Kotlin and there is no need to declare it as a separate option.
Smoke test running the app.
=> Do not declare Compose compiler version

.gitignore
K2 uses new `.kotlin` directory that should not be committed to projects. https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects
CI is enough.
=> Add .kotlin directory to .gitignore

.github/dependabot.yml
We are keeping Dependabot on to help us keep the libraries up to date, but to help us organise our work, we are going to reduce the interval of the updates to weekly.
=> Reduce the Dependabot interval to weekly

modules/features/referrals/build.gradle.kts, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml
This updates UI for unlimited passes (Internal Ref: pdeCcb-6Ac-p2#comment-5345)
Phone
ToolTip | Send Pass
----|-----
Phone Landscape
Tablet
ToolTip | Send Pass
----|-----
Tablet Landscape
=> Referrals: update UI for unlimited passes

modules/features/referrals/build.gradle.kts, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/services/localization/src/main/res/values/strings.xml
This adds Referrals claim pass page.
1. Go to Profile 
2. Tap Claim your 2-Month Guest Pass to Plus banner
3. ✅ Notice that claim guess pass page is shown (Figma: FVJPaWlRMlosEpsRhqxnSD-fi-2189_8613)
|Phone|
|--|
|<img width=320 src="https://github.com/user-attachments/assets/80bb76ef-b24f-4379-99d7-228d0eb62a3d"/>|
|Tablet|
|--|
|<img width=400 src="https://github.com/user-attachments/assets/2f402c32-ba2c-41d6-b2ba-1f3e95c9335d"/>|
=> Referrals: claim pass page

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProflieEpisodeListSearchBar.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This adds search analytics in Listening History.
1. Login with an account with some listening history
2. Go to Profile -> Listening History
3. Search for an episode
4. ✅ Notice in logs `Tracked: search_performed, Properties: {"source":"listening_history"`
5. Clear search query
6. ✅ Notice in logs `Tracked: search_cleared, Properties: {"source":"listening_history"`
Also, code review feature flag changes: 9492ea3f6a806cb3a539cb3ae9c26f91e159a488
=> Listening History: Add search analytics, enable feature

.buildkite/release-builds.yml
For easier debugging if release build fails
=> Add lint results artifacts to release build step

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt
The developer page feature to test episode notifications shows a toast error as it was being sent on the wrong thread.
```
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:168)
at android.widget.Toast.getLooper(Toast.java:186)
at android.widget.Toast.<init>(Toast.java:171)
at android.widget.Toast.makeText(Toast.java:502)
at android.widget.Toast.makeText(Toast.java:491)
at au.com.shiftyjelly.pocketcasts.settings.developer.DeveloperViewModel.forceRefresh(DeveloperViewModel.kt:42)
at au.com.shiftyjelly.pocketcasts.settings.developer.DeveloperViewModel$triggerNotification$1.invokeSuspend(DeveloperViewModel.kt:75)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit …
```
=> Fix the developer page new episode notification

app/build.gradle.kts, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ReferralsDeepLinkTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
This change adds support for the referral claim URL deep link. 
1. Check the Referrals feature flag is on
2. Click on this link on the device https://pocket-casts-main-development.mystagingwebsite.com/redeem-guest-pass/secret-referral-code
3. ✅ Verify the claim screen is shown to the user
4. Click on this link https://pocket-casts-main-development.mystagingwebsite.com
5. ✅ Verify the website is opened and the app isn't
6. Click on this link https://pocket-casts-main-development.mystagingwebsite.com/get
7. ✅ Verify the app is opened
8. Turn off the Referrals feature flag
9. Click on this link on the device https://pocket-casts-main-development.mystagingwebsite.com/redeem-guest-pass/secret-referral-code
10. ✅ Verify the claim screen isn't shown to the user …
=> Deep link the referral claim

gradle.properties, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionFrequency.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPlatform.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionTier.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionType.kt, proguard-rules.pro
This PR cleans up our R8 configuration by removing several rules that are now provided by the libraries themselves. I’ve added descriptions for all the applied rules or linked them to the relevant issues.
The main risk involves missing the `@JsonClass(generateAdapter = false)` annotation on some classes. However, I have extensively tested the app and analyzed the code to the best of my ability to identify any issues. The core flows are functioning correctly. If any issues arise, they should be easy to detect and resolve once users engage with the app.
Test the release variants of the app. I have tested the following:
* All three apps
* Major features:
* Signing in
* Subscriptions
* Playback
* Google Cast
* Sharing
* Bookmarks
* Folders
* Chapters
* Discover
* Filters
=> Clean up R8 configuration

.github/dependabot.yml, .github/workflows/submit-gradle-dependencies.yml
`gradle-build-action` started failing because it is not available to us. It wasn't detected in the PR because the action is not used for pull requests and there was no mention of it in the release notes.
> Error: Bad request - gradle/actions/setup-gradle@v3.5.0 is not allowed to be used in Automattic/pocket-casts-android. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: ruby/setup-ruby@*, gradle/wrapper-validation-action@*, gradle/gradle-build-action@*.
CI check is fine.
=> Revert gradle-build-action to v2

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/search/BookmarkSearchHandler.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/search/EpisodeSearchHandler.kt
There are other ways to fix this. For example, both handlers can be cleared in the viewModel's `onCleared` method. But to me, these two handlers shouldn't have been singletons in the first place.
Fixes #1320
See the original issue
=> Make search handlers non-singletons to fix persisting search text

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralCardAnimatedGradientView.kt
This PR addresses designers feedback about the animation:
* Reduce blur to increase vibrancy of blobs.
* Make animation less chaotic and lightly move the blobs.
Other notable code changes:
* When sensor data is not available on the device the blobs no longer roll around the card. Instead I fake sensor data and move the blobs in and out.
* Animation is now driven by arc tangent function instead of a cubic one. It fits the floating animation better.
Context: p1726669050569879/1724256575.844749-slack-C07HDV91FBQ
1. Install the app on a device with accelerometer and magnetometer. Most devices should have the,
2. Play around with referral cards and notice that the blobs correspond to device's orientation.
1. Install the app on a device without accelerometer and magnetometer. It might be hard …
=> Change the background animation of referral cards

proguard-rules.pro
This fixes an issue where the media notification might not appear and keep playback alive. I was able to replicate it only during the initial playback but we have different reports of it in the wild: https://www.reddit.com/r/pocketcasts/comments/1fk8cx2/background_playback/
We had this old R8 rule which was supposed to handle it
```
-keep class au.com.shiftyjelly.pocketcasts.core.player.** { *; }
```
However, this package no longer exists and it is hard to determine what the rule is supposed to guard against since it is very broad. Most likely it is an optimization step as I discovered while investigating this issue. Using R8 optimization on the `PlaybackService` class creates the issue.
I haven't investigated deep enough to determine which methods of the `PlaybackService` shouldn't be …
=> Do not optimize PlaybackService class

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModel.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
[This Sentry issue:](https://a8c.sentry.io/share/issue/ff59c3ae1092401c91210d2ba28cf390/) points to `au.com.shiftyjelly.pocketcasts.models.db.dao.EpisodeDao_Impl$65 in call at line 11261` which is at `EpisodeDao`'s `filteredPlaybackHistoryFlow()`. It is an `IllegalStateException` while possibly reading a large list. 
To fix the issue, I'm annotating the query with `Transaction` based on this recommendation: https://issuetracker.google.com/issues/73859920#comment2
and added a check for an empty search term in 6f03d19.
Smoke test that you can search properly in `Listening History`.
=> Fix illegal state exception in filteredPlaybackHistoryFlow

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
The show notes web views have an issue that they jump after loading. I found the solution on Stackoverflow that seems to work https://stackoverflow.com/questions/18744743/android-webview-jumping-to-the-bottom. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/2716
1. Subscribe to "10% Happier with Dan Harris"
2. Tap on an episode row
3. Scroll down the page
✅ Verify the page doesn't jump.
4. Open the full screen player
5. Swipe to the show notes
✅ Verify the show notes page doesn't jump.
https://github.com/user-attachments/assets/72775130-2d81-418f-8b65-bf891164515e
=> Stop the show notes web view jumping after loading

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/PlayerModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt
This PR updates the code so that a transcript format can have multiple valid mime types.
Internal ref: p1727088168724749-slack-C078746V6UX
1. Start the app
2. Open the following podcast (SRT mimetype: "application/application/x-subrip"): https://pca.st/episode/2cb385e0-e8f2-4b5d-be50-69b203630174
3. Play it and open the full screen player
4. Tap on the Transcript icon
5. Check if the transcript shows correctly
6. Smoke test that the other SRT mimetype ("application/srt") format transcript loads properly: https://pca.st/cqw2vgr7
** Target 7.73 but we can wait a few days and release it with other possible fixes.
=> Support multiple possible mimetypes for a transcript format

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModel.kt
This removes `trim() `function in the search query changes to allow spaces. I accidentally added it while adding tracks thinking it will remove leading and trailing spaces for the entire search string.
1. Go to Profile
2. Login with an account with some listening history
3. Search for an episode title with in-between spaces
4. ✅ Notice that the episode is listed in the search results
=> Listening History - Allow spaces in search

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassError.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralManagerImplTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServiceManager.kt, modules/services/sharing/build.gradle.kts, modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt
This gets referral code using the endpoint while displaying the send guest pass screen.
1. Switch to "debug" build variant
2. Launch the app and login as a paid user
3. Go to `Profile` tab
4. Tap on gift icon
5. Notice that send guest pass screen is shown
6. Tap "Share Guest Pass" and copy the share text
7. ✅ Notice that there is a real referral code appended to the share URL
8. Close the screen
9. Disable internet
10. Tap on gift icon again
11. ✅ Notice that you see an error screen (this is just a placeholder)
12. Enable internet
13. Tap try again
14. ✅ Notice that data is loaded again.
=> Referrals: Get referral code from endpoint

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
- This restore the original player volume after restarting sleep timer by shaking the device
Fixes #2440
1. Set timer and start episode. I would set 1 minute for this step
2. When time starts to fade out, shake device. It starts fading out when have 5 seconds left, but to see the issue I recommend to shake the device when it has 2 or 3 seconds left
3. Wait for sleep timer being restarted
4. ✅ Ensure the player volume returns to the original one before shaking the device
=> [Sleep Timer] Fix - Volume doesn't return to original level if device is shaken during fade-out

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt
`RoundedCornersTransformation` performs poorly with large bitmaps, especially in conjunction with `RecyclerView`, resulting in a subpar experience. The `PodcastGridRow` component uses a corner radius of 0, which triggers unnecessary calculations. This PR omits those calculations.
I plan to remove `RoundedCornersTransformation` altogether, as it seems unnecessary except for widget support on older devices (but I think we can live without that). However, I didn't want to make such a significant change here. Since this PR targets `7.73`, I aimed to make the smallest impact possible.
Context: p1727269586207829-slack-C02A333D8LQ
1. Open the Discover section.
2. Got to "Podcasts with Transcripts"
3. Scrolling should not stutter.
=> Do not apply rounded corners transformation if radius is 0

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptFilter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptFilterTest.kt
This 
- Cherry picks https://github.com/Automattic/pocket-casts-android/commit/2695c16362e8c8e1095b43b229951de1ec0f3bfe into `release/7.73` to match with iOS: https://github.com/Automattic/pocket-casts-ios/pull/2192
- Adds `type` and `show_as_webpage`  param to `transcript_shown` event (cherry-picks https://github.com/Automattic/pocket-casts-android/commit/5378c61d4dfe8b9f23ecf0f099cd491d9d300b29, https://github.com/Automattic/pocket-casts-android/commit/db4ff33123c58d6ca613aa155448729696b9b416)
1. Open transcript for episode: https://pca.st/episode/dba650aa-f34b-453c-9e16-f4e73d2ef1e3
2. ✅ Notice that HTML entities like `&#39;` and `&quot;` are decoded properly
3. Open transcript for https://pca.st/episode/3abf8b43-0ed0-4713-b073-37b379418378
4. ✅ Notice in logs that `transcript_shown` …
=> Transcripts -  decode html entities & update tracks

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/GridListAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridFragment.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridRow.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastListFragment.kt
Some small improvements to the grid layout I didn't want to include in #2932.
1. Compare identity using UUID instead of the whole object.
2. Do not instantiate listeners on bind and instead do it in the constructor.
3. Do not copy image request factory on bind and instead do it when image size changes.
1. Go to the Discover page.
2. Open "Podcasts with Transcripts".
3. Tapping on a podcast should open it.
4. Tapping on a subscribe button should subscribe to a podcast.
=> Improve performance of discover grid layout

modules/services/analytics/build.gradle.kts, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt, modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProviderTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
- This is to avoid issues after the user signs out and tap on any of our paywalls after that without restart the app. 
- This PR initializes the experiments again after the user signs out
1. Have a fresh install
2. Open any paywall
3. Ensure you don't see any crash
4. Log in using a free account
5. Open any paywall again
6. Ensure you don't see any crash
7. Sign out
8. Open any paywall again (last time)
9. Ensure you don't see any crash
=> [Paywall Experiments] Refresh Experiments

CHANGELOG.md, modules/features/engage/src/main/AndroidManifest.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This enable Engage SDK in our app. I'll still need to contact Google once we rollout in production to 100%.
Context: pdeCcb-6Ck-p2#comment-5525
=> Enable Engage SDK in production

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralGuestPassCardView.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/ReferralsOfferInfo.kt, modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/services/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt
This updates referral strings (for dynamic duration) for translations before the `7.74` code-freeze.
ToolTip FVJPaWlRMlosEpsRhqxnSD-fi-2189_9583 | Send Pass FVJPaWlRMlosEpsRhqxnSD-fi-2189_9583|  Claim Pass Banner FVJPaWlRMlosEpsRhqxnSD-fi-2189_8773 | Claim Pass Page FVJPaWlRMlosEpsRhqxnSD-fi-2189_8613 | Share Text FVJPaWlRMlosEpsRhqxnSD-fi-2189_9583
----|---|---|---|----
=> Referrals - Update strings for translations

CHANGELOG.md, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml
- This is an attempt to fix the crash when the user uploads a file from files screen. After analyzing the code and googling about it I had 3 hypothesis:
1. This issue is caused a generic error when uploading a file. This generic error throws an exception that we are not catching inside the coroutine
2. The URI that we are trying to upload is invalid and we are not checking it. This could also be caused if the user removed or moved the file path after selecting this one to be downloaded. I was able to reproduce a crash with this scenario
3. I thought that it could be related to permissions because this issue is happening mostly on SDK 34, but since we are not trying to access others apps files I would say that we are good in terms of permission and we don't need to do anything else. See …
=> Fix: Crash when uploading file

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ArtworkConfiguration.kt
This PR displays artwork (including episode one) in the podcast view. If the setting is disabled no artwork is displayed.
We had a GH discussion about it but it is now gone since we closed the discussions. But there was a follow up on the forums here: https://forums.pocketcasts.com/forums/topic/show-episode-artwork-in-podcast-view/#post-5955
1. Go to the `Appearance` settings.
2. Go to the `Advanced episode artwork settings`.
3. Enable `Podcasts` setting.
4. Go to a podcast that uses episode artwork like [Darknet Diaries](https://pca.st/darknetdiaries).
5. Notice that you see artwork. You might not see episode artwork immediately due to missing image URLs. If you don't see them go to any episode details so that the show notes are parsed.
6. Disable `Podcasts` setting in the `Advanced …
=> Display episode artwork in the podcast view

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/referrals/build.gradle.kts, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModelTest.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModelTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/protobuf/src/main/proto/sync_api.proto
This validates the referral claim offer. It is validated after login or sign-up if the user is not signed in.
** It does not yet start the IAP flow
Prerequisites
1. Login as a paid user
2. Go to the `Profile` tab
3. Notice that referral profile banner is not shown
4. Tap gift icon to open `Send Guest Pass` screen
5. Tap `Share Guest Pass`
6. Copy the share URL 
7. Logout
1. Tap the share URL to open the referral claim screen 
2. Tap `Activate my pass`
3. Notice that login or sign-up screen is shown
4. Login with a free account
5. ✅ At the end of login, notice that a loading view is shown, this is when the referral code is validated
1. Tap the share URL to open the referral claim screen 
2. Tap `Activate my pass`
3. Notice that login or sign-up screen is shown
4. Sign up
5. ✅ At the end of …
=> Referrals - validate claim offer

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Experiment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/PaywallABTestCustomTreatment.kt, modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProviderTest.kt
- This PR replaces the AA experiment for AB experiment
- See Experiment: 22042-explat-experiment
- See iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/2214
Fixes #2963
- ⚠️ Need help from data team to test this PR. See: p1727781176287829-slack-C07DLM97HRQ
=> [Paywall Experiment] Set AB experiment 

CHANGELOG.md, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
We had a report that searching over a large listening history was very slow. The cause of this was that it could return a large number of results. I have added a limit to the search results query to speed up this. 
1. Subscribe to lots of podcasts
2. Run the following query in the Android Studio window "App Inspection" `UPDATE podcast_episodes SET last_playback_interaction_date = 1700000000000`
3. In the app open the Profile tab
4. Tap on Listening History
4. Search using a simple term so lots of results are return
✅ Verify the search results load quickly.
https://github.com/user-attachments/assets/a4f8fe4f-7e19-4143-9b37-712cd56aefea
=> Speed up listening history search by limiting the number of results

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralOfferInfoProvider.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This 
- replaces referral product and offer id
- adds failure logs in the referrals claim VM
- adds a check (00c3642483769f612510895a0c0828300ae9e6cf) so that after purchase when the sign-in state is updated, the redeem code is not re-validated and the user is not shown the invalid offer while the screen is closing in the view model scope. 
Code review should be sufficient. 
https://github.com/user-attachments/assets/23100ab2-cc05-4f8e-a7b2-431e413f8d90
=> Referrals - Replace IDs, add failure logs

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/features/settings/src/main/res/xml/preferences_auto_download.xml, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoDownloadLimitSetting.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- This PR updates the UI for auto downloading settings (global) by adding the limit setting
- Adds local feature flag to wrap this change
- Add tracks for when the user selects a limit downloading
- Context: pdeCcb-744-p2
- Figma: VvERCFIopLjFL8Fnczsf8r-fi-1_756
Fixes #2970
1. Have the FF disabled
2. Go to Profile -> Settings -> Auto Download
3. ✅ Ensure that New Episodes toggle does not have description
4. ✅ Ensure you don't see the limit download section
1. Have the FF enabled
2. Go to Profile -> Settings -> Auto Download
3. ✅ Ensure that New Episodes toggle has description
4. ✅ Ensure you see the limit download section
5. Tap on limit downloads label and select one option
6. ✅ Ensure your option is selected
7. ✅ Ensure 🔵 Tracked: settings_auto_download_limit_downloads_toggled, …
=> [Auto Downloading] Update UI for Global Auto Downloading

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt, modules/features/podcasts/src/main/res/xml/preferences_podcasts.xml, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/101.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/PodcastAutoDownloadLimitConverter.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/AutoDownloadLimitSetting.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
- This adds the auto download settings to podcast setting
- Persist the download limit in database d0b94ac7cd763b924628274e217ce209d44221ca
- Figma: [VvERCFIopLjFL8Fnczsf8r-fi-1_756](https://href.li/?https://www.figma.com/file/VvERCFIopLjFL8Fnczsf8r/?node-id=1-756)
**Note:** Default behavior: Two latest episodes
**Note2**: I will align and address in another PR with designs if we should reset the auto download limit to two latest download limit after toggle `Auto Download` off
**Note 3**: I will address in another PR the database update after the user subscribes to a podcast
Fixes #2971 
1. Have the FF disabled
2. Go to some podcast -> Subscribe to this podcast -> Tap on Settings
3. Toggle the `Auto Download` ON
4. ✅ Ensure you don't see the limit download section
1. Have the FF enabled …
=> [Auto Downloading] Update UI for Podcast Auto Downloading

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt
An automotive manufacturer asked if we could add the progress bar to the browse view. There is a [Google guide for this](https://developer.android.com/training/cars/media#browse-progress-bar).
1. Start the Android Auto emulator. 
```
cd /Applications/android-sdk/extras/google/auto/
chmod +x ./desktop-head-unit
./desktop-head-unit --usb
```
2. Plugin in your device over USB
3. Play an episode and skip to move progress along
4. Open the podcast page
✅  Verify the episode row now shows a progress bar
You may need to go to one level higher in the menu and back again for the episode row to update. I don't believe there is a way to fix this in Android Auto or Automotive. 
Before
After
=> Android Auto: Update the progress bar in the browse view

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CacheWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerDataSourceFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerEvent.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
This correctly updates the buffer position for a cached episode and disposes of the buffer update timer when caching is complete.
Fixes https://github.com/Automattic/pocket-casts-android/issues/2861
1. Apply [this patch](https://github.com/user-attachments/files/17304506/caching.patch)
2. Search for `tag:Test` in Android Studio log viewer
3. Play an episode that you haven't played before and open full-screen player
4. ✅ Notice that you see that episode is buffering
5. Wait until you see "Caching complete" in the logs
6. ✅ Notice that you see the buffer position updated to the end of episode duration
https://github.com/user-attachments/assets/ca1dbfdb-13c6-4b75-b45c-4b5d9e869110
=> Media - Update buffer position for cached episode

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/repositories/src/debug/kotlin/com/android/billingclient/api/ProductDetailsModule.kt, modules/services/repositories/src/debugProd/kotlin/com/android/billingclient/api/ProductDetailsModule.kt
This hides the Profile tab referral banner on validation failure and long press.
p1728384201675269/1728383119.381479-slack-C07HDV91FBQ
1. Launch the app and open a referral link
2. Go to `Profile` tab
3. Long press on the referral banner
4. Notice that a pop-up is shown to hide the banner
5. Tap on the banner
6. ✅ Notice that referral banner is hidden
7. ✅ Notice that `referral_pass_banner_hide_tapped` is tracked
https://github.com/user-attachments/assets/0870328e-3bc8-47d0-97ee-77fd42e4bad0
https://github.com/user-attachments/assets/59c0b8df-6c93-4ced-8b53-9973656228c3
=> Referrals - Hide banner on validation failure and long press

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastRatingsDaoTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/102.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastRatingsDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserPodcastRating.kt, modules/services/protobuf/src/main/proto/sync_api.proto, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServiceManager.kt
This adds syncing of user ratings. Initially I wanted to add `user_rating` column to the `podcasts` table but this made it inefficient when it came to synchronization. A separate table that consists only of ratings is simpler to manage.
1. Install the app from 85d7c1f0e3e6b77fd8d286b23a26b79e9fdad6ce
2. Sign in.
3. Install the app from this branch.
4. The app shouldn't crash and you should not lose any data.
1. Rate a podcast on the device A.
2. Sync the device B.
3. Verify that rating synced. `SELECT p.title, rating FROM user_podcast_ratings JOIN podcasts AS p ON podcast_uuid = p.uuid ORDER BY title ASC`
1. Rate a podcast.
2. Verify that the rating is stored locally. `SELECT p.title, rating FROM user_podcast_ratings JOIN podcasts AS p ON podcast_uuid = p.uuid ORDER BY title ASC`
=> Sync user ratings

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This enables remote FF flag for `Referrals`. 
Firebase remote config for `referrals` is currently set to false. 
I'm targeting 7.75 for releasing the feature but not sure if the feature will be enabled for 7.75, so I haven't yet added a changelog for it. 
=> Referrals - Enable remote FF

modules/services/localization/src/main/res/values/strings.xml
This improves transcript not available message.
Fixes https://github.com/Automattic/pocket-casts-android/issues/2990
=> Transcripts - Improve transcript not available message

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivityContract.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModel.kt, modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModelTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingExitInfo.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This displays welcome screen after user signed up and referral flow is complete
- Referrals FF enabled for release build
- License testing account
- Valid referral link
1. Install release build after enabling `Referrals` FF for release build
2. Open referral link
3. Notice that claim referral pass screen is shown
4. Tap `Activate my pass`
5. Sign up and complete purchase flow
6. Wait until the referral flow completes
7. ✅ Notice that the welcome screen is shown
https://github.com/user-attachments/assets/c9ec7540-eda4-433e-b052-e8e5b3f89244
https://github.com/user-attachments/assets/c17270f7-95b7-454e-8b9c-5675e58e2a42
=> Referrals - Show welcome screen after user signed up and referral flow is complete

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassError.kt, modules/services/localization/src/main/res/values/strings.xml
This updates failed to load offer message and updates error screen to match with the Figma design (FVJPaWlRMlosEpsRhqxnSD-fi-2189_9583)
1. Append a random string to `REFERRAL_OFFER_ID` in `ReferralOfferInfoProvider`
2. Open a referral link
3. ✅ Notice that an error screen is loaded with an updated error message 
4. ✅ Notice that the error screen design matches Figma design (FVJPaWlRMlosEpsRhqxnSD-fi-2189_9583)
=> Referrals  - Update error message + screen style 

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModelTest.kt
This 
- hides tooltip on tooltip click
- moves tooltip tap tracking from gift icon click to tooltip click. Both actions dismiss the tooltip but the description for `referral_tooltip_tapped` says to track it only on tooltip tap.
`referral_tooltip_tapped – User taps the tooltip to dismiss it`
1. Fresh install the app and login as a paid user
2. Go to Profile screen
3. Notice that you see referral tooltip 
4. Tap on the tooltip
5. ✅ Notice that tooltip is dismissed
6.  ✅ Notice that `referral_tooltip_tapped` is shown in logs
7. Clear app storage
8. Go to Profile screen
9. Notice that you see referral tooltip 
10. Tap on gift icon
11. ✅ Notice that tooltip is dismissed
12. ✅ Notice that `referral_tooltip_tapped` is not shown in logs
13. ✅ Notice that referral send pass screen is shown
=> Referrals - Hide tooltip on tooltip click

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/AutoDownloadLimitSetting.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
- This PR, introduces the auto download after subscribing to a podcast.
- I've deleted the OFF option for the auto download limit option since I don't think we will need. After getting back from the designs I will update in another PR in case it's necessary
- There are some pending questions questions that I did not get back any update, but since we are putting this behind a feature flag, I can safety merge this PR. p1728497690817009/1728311298.538509-slack-C07QMC2GB1B
- The global disabling will be handled in another PR
- Auto Clean feature is not implemented yet
Fixes #2972
1. Have auto download feature flag enabled
2. Fresh install
3. Subscribe to some podcast
4. ✅ Ensure the latest 2 episodes sorted by publish date start downloading
5. Open this podcast setting
6. ✅ Ensure the Auto …
=> [Auto Downloading] Download episodes after subscribing to a podcast

modules/features/player/src/main/res/layout/view_player_bottom_sheet.xml, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt, modules/services/ui/src/main/res/values/dimens.xml
When mini player was visible it could obstruct advanced artwork settings making them unusable. This PR adds an empty space to account for the player.
I'm not adding it to the changelog because the changes is so small and we don't have any reports about it.
1. Install the app on a small device.
2. Play something.
3. Go to the advanced artwork settings.
4. Notice that you can scroll the screen and see all entries.
| - | - |
| ![before](https://github.com/user-attachments/assets/6ed86d79-98d0-4720-a82b-dab31f66a46d) | ![after](https://github.com/user-attachments/assets/a635d2dd-47c7-43ed-a3e7-cc7dba243f67) |
=> Add empty space to artwork settings to account for mini player

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
There is a user on the forums that says they have [Episodes are stuck in downloads](https://forums.pocketcasts.com/forums/topic/episodes-are-stuck-in-downloads/?view=all#post-6103). This fix is a bit of a guess, but it's possible to see how it would happen. If the episode was in the middle of a download, the app was killed, and the Work Manager download tasks were cleared, then the episodes could be left with a `download_task_id` value. The clean up method wouldn't be able to find the task, so it wouldn't be removed from the downloads page. 
1. Open the Android Studio window App Inspection
2. Connect to the running app
3. Tap the "Open New Query Tab"
4. Run the following SQL to set the download_task_id to one that doesn't exist
```SQL
UPDATE podcast_episodes SET download_task_id = …
```
=> Fix episodes stuck on the downloads page

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
- This PR disables auto-download after the user logs in because, during login, we refresh the podcasts, which was triggering a batch download of the first episodes of the podcasts the user is subscribed to
> [!NOTE]  
>  There are some pending questions questions that I did not get back any update, but since we are putting this behind a feature flag, I can safety merge this PR. p1728497690817009/1728311298.538509-slack-C07QMC2GB1B
> [!NOTE]  
> The global disabling will be handled in another PR
> [!NOTE]  
>Auto Clean feature is not implemented yet
Fixes #3000
1. Have an account with existing podcast subscribed
3. Log in
4. ✅ Ensure that does not trigger any auto download
5. Subscribe to a new podcast
6. ✅ Ensure you get the latest two episodes from this podcast …
=> [Auto Downloading] Exclude auto download after login

modules/features/endofyear/build.gradle.kts, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearSyncImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This PR maps EoY stats to stories and pushes them to a basic UI.
Figma with all stories listed: lH66LwxxgG8btQ8NrM0ldx-fi-3070_28391
1. Sign in with a paid account that listened to at least 5 minutes of episodes this year.
2. Sync your profile data.
4. Reopen the app.
5. Open Playback 2024 either by using the bottom sheet or the banner in the profile.
6. You might see a loading progress bar and it might take some time to sync your data.
7. Once data is synced tapping on the right edge side of a story should move you forward and tapping on a left edge of a story should move you backwards.
8. Verify that you can see all stories except for the `PlusInterstitial`.
9. Sign out.
10. Sign in with a non-paid account.
11. Verify that you can see the `PlusInterstitial` story.
=> Display End of Year stories skeleton UI

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/HistoryManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
- This PR excludes auto download from OPML files import
> [!NOTE]  
> The global disabling will be handled in another PR
> [!NOTE]  
>Auto Clean feature is not implemented yet
Fixes #2998
- For the tests, I recommend to try different combinations of Log in, Import OPML files and regular podcast subscribing
- The episodes should only be downloaded when the user manually subscribes to a podcast
Here are some scenarios you can try:
1. Fresh install 
2. Log in with an account that already has podcasts subscribed
3. ✅ Ensure that does not download episodes from the podcasts when syncing account after logging
4. Subscribe to a podcast
5. ✅ Ensure that downloads the latest 2 episodes of this podcast
6. Import OPML file
7.  ✅ Ensure that does not download episodes from the podcasts imported 
1. …
=> [Auto Downloading] Exclude Auto Downloads After Importing Podcasts

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
Add close button to EoY stories.
1. Open Playback 2024.
2. Notice that there is close button in the top right corner.
3. Tapping on it should close the stories.
=> Add close button to EoY stories

modules/services/localization/src/main/res/values/strings.xml
This PR reverts the Paywall title to `Everything you love about Pocket Casts, plus more`
This matches the iOS change https://github.com/Automattic/pocket-casts-ios/pull/2273
1. Use an account without Pocket Casts Plus
2. Go to Profile -> Settings -> Pocket Casts Plus
3. ✅ Verify the text is updated
4. Change [the following line](https://github.com/Automattic/pocket-casts-android/blob/main/modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt#L112) to `UpgradeLayout.Features`
5. Go to Profile -> Settings -> Pocket Casts Plus
6. ✅ Verify the text is updated
| Default | Feature Variant |
| -------- | ------- |
| ![Screenshot_20241015_215354](https://github.com/user-attachments/assets/04352be5-821e-44b0-8121-0c14848db446) …
=> Revert paywall title

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
- Add logs for auto download after subscribing to a podcast
=> [Auto Downloading] Add logs for Auto Download

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/List.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/extensions/ListTest.kt
This adds number of shows story.
Figma: lH66LwxxgG8btQ8NrM0ldx-fi-3054_3820
As I commented on Figma I'm missing sticker asset so right now I'm mocking it with rounded rectangle shape. There's also an issue on small devices with an overlapping sticker and the text, which I also asked about.
> [!note]
> Edge to edge is not supported ATM due to the legacy code. Enabling it would break the UI in the whole app. I'll work on supporting it as a separate task.
1. Sign in with an account that listened to at least 5 minutes of episodes this year.
2. Sync your profile data.
4. Reopen the app.
5. Open Playback 2024.
6. You might see a loading progress bar and it might take some time to sync your data.
7. Once data is synced go to the number of shows story and verify it.
| Regular | …
=> Display Number Of Shows story

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
- Uses the global `New Episodes` toggle to control if we will download the latest episodes after the user subscribes to a podcast e90f3c84b46cb4e319bc603f51ca56b8bc2c1f52
- Changed the behavior of the `New Episodes` toggle. Before this PR, turning the `New Episodes` toggle OFF would reset the auto-download limit value and remove the podcasts selected in the `Choose Podcast` list. We have now removed this behavior to align with iOS 571a3f8bd0b75554047902c2283bafcb4e62a9c3. Context here: p1728920687960259/1728629479.247849-slack-C07QMC2GB1B
- Keeps the `New Episodes` toggle ON even if we don't have any podcast selected. Also to align with iOS
Fixes #2999
2. Go to Profile -> Auto Download
3. ✅ Ensure you have `New Episodes` ON and `Limit Downloads` with `2 Latest Episodes` …
=> [Auto Downloading] - Use new episodes global toggle to download episodes

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CoverStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/NumberOfShowsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/RatingsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowsStory.kt, modules/services/images/src/main/res/drawable/eoy_star_text_stop.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/RatingStats.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/RatingStatsTest.kt
This adds ratings story UI.
Figma: lH66LwxxgG8btQ8NrM0ldx-fi-3070_21275
1. Sign in with an account that listened to at least 5 minutes of episodes this year.
2. Sync your profile data.
4. Reopen the app.
5. Open Playback 2024.
6. You might see a loading progress bar and it might take some time to sync your data.
7. Once data is synced go to the ratings story and verify it.
| High ratings | Low ratings | No ratings | No ratings small device |
| ![high](https://github.com/user-attachments/assets/55c88835-edf3-4f99-94a2-86d27ce78508) | ![low](https://github.com/user-attachments/assets/642ae455-35e1-4055-b36f-6719eb462adf) | ![Screenshot_20241016-172428](https://github.com/user-attachments/assets/51840efa-c9c3-400a-923b-f8d1c23cef30) | ![Screenshot …
=> Display Ratings story

modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
- We want to enable the `New Episodes` toggle by default for New Users Only
- See the context here: p1729146760964459/1729083057.704669-slack-C07QMC2GB1B
Fixes #3034
2. Don't Log in
3. Go to Profile -> Settings -> Auto Download
4. ✅ Ensure `New Episodes` toggle is **ON**
5. Go to Profile -> Account -> Create a new account
6. ✅ Ensure `New Episodes` toggle is **ON**
2. Don't Log in
3. Go to Profile -> Settings -> Auto Download
4. ✅ Ensure `New Episodes` toggle is **ON**
5. Go to Profile -> Account -> Log in with existing account
6. ✅ Ensure `New Episodes` toggle is **ON**
1. Checkout to d76d68717ca94253a12b4ee9cadb99b5e3e8e7de
2. Install the app
3. Log in
4. Go to Profile -> Settings -> Auto Download -> Disable  `New Episodes`
5. Checkout …
=> [Auto Downloading] - Enable New Episodes toggle by default for New Users Only

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsWorkerTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, automotive/src/main/AndroidManifest.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/JobIds.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, wear/src/main/AndroidManifest.xml, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
This migrates `VersionMigrationsJob` to worker.
Fixes #3009
Code review should be sufficient. 
`Optional`
1. Change version code to `375` in `version.properties`
3. Change version code to `376` in `version.properties`
4. Reinstall the app 
5. Notice  `VersionMigrationsWorker - finished` in `Help & feedback` -> `Logs`
=> Migrate `VersionMigrationsJob` to worker

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Adds the remote feature flag
- See: p1729260716519079-slack-C07QMC2GB1B
- I am also updating the changelog here since it's enabling the feature in `7.76`
- You can also check if the name of the feature flag matches with the name in Firebase
=> [Auto Downloading] -  Add Remote Feature Flag

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CompletionRateStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CoverStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/EndingStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/LongestEpisodeStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/NumberOfShowsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/RatingsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TotalTimeStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/YearVsYearStory.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PagerProgressingIndicator.kt
This displays story progress indicator and auto pages the stories.
1. Start PB24 flow.
2. Stories should auto page every 7 seconds. 
4. Story progress should reset upon manually changing a story.
5. Plus Interstitial story (only free accounts can see it) should not have auto progress.
6. Ending story should close the flow upon reaching 7 seconds.
=> Display story progress indicator

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionTier.kt
This PR adds handling of the upsell flow and story navigation.
> [!note]
> Test this with the release variant so you can complete a purchase.
1. Apply [this patch](https://github.com/user-attachments/files/17463085/eoy.patch).
2. Sign in with a paid account.
3. Start Playback 2024.
4. Verify that navigation works as expected.
5. Navigate back to the Profile tab.
6. Sign out.
7. Sign up with a new account.
8. Start **Playback 2024**.
9. Confirm that navigation works, but note that navigating forward on the Plus Interstitial story skips two stories and jumps to the Ending story.
10. Navigating backwards on the Ending story should return to the Plus Interstitial story.
11. Tap the upsell button.
12. Verify that the upsell flow starts.
13. Close the upsell flow.
14. Confirm that you are still …
=> Handle upsell flow in the End of Year flow

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/RatingsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/services/localization/src/main/res/values/strings.xml
This adds navigation to learn about ratings if users gave none.
1. Start PB24 with an account that gave no ratings.
2. Navigating to the Ratings story.
3. Tap on the button.
4. A web view with the ratings support page should open.
=> Navigate to ratings info page

modules/features/profile/src/main/res/layout/fragment_profile.xml
This PR moves EoY banner to the top.
You can play around with different banner configurations but reviewing the screenshots should be enough.
| Both | EoY | Referrals | None |
| ![both](https://github.com/user-attachments/assets/f3d2e1f1-325d-4959-b857-fb56e6767c88) | ![eoy](https://github.com/user-attachments/assets/25d7855d-c449-4fdb-96d9-70c7579ea87a) | ![ref](https://github.com/user-attachments/assets/c367e2bf-60dc-42f7-8f46-7b294adb9a0d) | ![none](https://github.com/user-attachments/assets/18dd37c5-ab3b-4606-be78-2b8f5fd6f079) |
=> Change order of profile banners

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
This adds error state to the End of Year.
1. Apply [this patch](https://github.com/user-attachments/files/17486631/eoy-err.patch).
2. Start the app and sync your account so you can start PB24.
3. Turn off the Internet connection.
4. Start PB24.
5. You should see the error screen.
6. Tap on "Retry".
7. It should still fail to load the data.
8. Turn on the Internet connection.
9. Tap on "Retry".
10. You should see the loading screen.
11. After a while you should see the stories.
https://github.com/user-attachments/assets/0a4ce365-15f1-430d-aa32-ae54546154a4
=> Add End of Year failure state

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/EndingStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
This adds navigation back to the beginning of the Plabyack flow.
1. Start PB24.
2. Go to the Ending story.
3. Tap on "Play again".
4. PB24 should jump back to the Cover story.
=> Navigate to the End of Year Cover story

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearSyncImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Two small improvements to the syncing process:
* Add a separate feature flag. This will allow me to enable syncing before enabling End of Year feature to let users sync data earlier and have better UX.
* Assume that data is in sync when it was synced at most a 1 day ago instead of 6 hours. This only affects users with multiple devices and from testing 6 hours period seems too small to me.
=> Control syncing End of Year data with a separate flag

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt
This pauses auto progress of stories when users hold their finger on the screen.
1. Start PB24.
2. Check that the navigation by tapping on the screen still works.
3. Hold a finger on a story. The auto progress should pause.
4. Release the finger. The auto progress should resume.
5. Check that the navigation still works.
=> Pause and resume story auto progress with the hold gesture

fastlane/Fastfile
The prototype APKs show a browser warning when clicked, not using the CloudFront domain fixes this for now.
Slack discussion: p1729710669676249/1729685360.539729-slack-CC7L49W13 
Check the prototype links don't show the warning when clicked.
=> Change the prototype domain

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This add the track event for when we toggle the shuffle on/off
- This event also has the source like the other up next events:
` mini_player, now_playing, player, up_next_shortcut
`
Fixes #3063
1. Have the shuffle feature flag enabled
2. Add some podcast to Up Next
3. Open Up Next
4. Toggle shuffle ON
5. ✅ Ensure  `🔵 Tracked: up_next_shuffle_enabled, Properties: {"value":true,"source":"source"` is tracked
6. Toggle shuffle OFF
7. ✅ Ensure  `🔵 Tracked: up_next_shuffle_enabled, Properties: {"value":false,"source":"source"` is tracked
=> [Project] Up Next Shuffle - Add Tracks

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerSeekBar.kt
@geekygecko  reported:
> I have just noticed that the time remaining can go to a positive value if the duration is incorrect which it seems to be with the podcast I’m testing with.
> The old code used to stop this happening by limiting it to 0.
> 
> It was https://pca.st/podcast/4010e110-45d0-0131-8293-723c91aeae46 while I was testing Chromecast
> I was testing it loaded the next episode in the Up Next
I can't replicate the issue but the fix is simple.
I'm targetting `7.75` since it was introduced there and the change is very harmless.
Not sure. Smoke the remaining time. But code review should be enough.
=> Coerce remaining time to display at least 0 seconds

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
- The shuffle button should be hidden when there is no episode in progress
Fixes #3089
1. Have the shuffle feature flag on
2. Remove all in progress episode
3. Tap on Up next tap
4. ✅ Ensure you don't see the shuffle button
5. Play an episode
6. Open Up next
7. ✅ Ensure you see the shuffle button
|-------------|--------------|
| ![Before](https://github.com/user-attachments/assets/546f6dcd-11d9-4f5f-a115-19b26b0d1eab) | ![After](https://github.com/user-attachments/assets/0fd534f4-3f76-4490-a2e6-bb061d40416f) |
=> [Project] Up Next Shuffle - Hide shuffle button when there is no current playing episode

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/ui/PlaybackServiceTest.kt, app/src/main/AndroidManifest.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerNotificationManager.kt
Chromecasting from Pocket Casts has an issue that the Pocket Casts PlaybackService doesn’t run in the foreground, so the system kills off the service while it's still needed. This means that the episode progress would not be tracked, and when the episode ends, the next episode in the Up Next would not start. For the service to run in the foreground, we need to create a notification. We didn't create a notification as the Chromecast library creates a separate playback notification causing  two playback notifications but it seems recent versions of Android only show one notification. 
2. ✅ Verify there is a playback notification
3. Cast the episode 
4. ✅ Verify there is only a casting playback notification
5. ✅ Verify logcat doesn't contain the following message "can't …
=> Keep the playing service in the foreground when casting

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Story.kt, modules/services/sharing/src/main/AndroidManifest.xml, modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ItemSharedReceiver.kt, modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/services/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt
This adds EoY analytics.
Test analytics events from the "End of Year" section [here](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=506:506).
=> Add end of year analytics

fastlane/Fastfile
Currently the Release Scenario instructs to download the universal, signed APK from Google Play Console (under `App bundle explorer > Downloads`) manually, and also rename and attach those `.apk` to the GitHub Release manually.
But we now have an action to automate that in our `release-toolkit`, so we can automate all those!
- This PR automates the download of the universal, signed APKs from GPC for all 3 apps (mobile, wear, automotive), then attaching them to the GitHub Release that gets created (alongside the `.aab` files that were already attached)
- This also means that we'll be able to remove a lot of tedious manual tasks from the Release Scenario in Release V2 🎉 
**Companion diff** updating the MC Release Scenario template: D164732-code
To avoid waiting for a new beta build to be …
=> [Tooling] Automate the download of the signed APK from Google Play into the GitHub Release during beta/final builds

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Experiment.kt
- This PR just sets the AB experiment for release `7.76`
- Context: p1729790811044969/1729729858.793479-slack-C046HLX37K2
- Note: The AA experiment was set to release `7.75` -> https://github.com/Automattic/pocket-casts-android/pull/3092
=> [Paywall Experiment] Set AB Experiment

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtil.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtilTest.kt
- This PR adds a requirement to display the banner on the Downloads screen.
- The banner displays when the user has downloaded episodes and the device has low storage.
- Low storage is defined as less than 10% of total storage available
- See: p1729915373575909/1729892350.532779-slack-C07TL9YK9V1
The `lowStorageThreshold` from  `modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtilTest.kt`  represents the percentage of available space on user's device that we are going to consider low. Currently is set to `10%`
Fixes #3101 
1. Ensure the device has less than 10% storage available (or adjust lowStorageThreshold in StorageUtilTest.kt to simplify testing; it’s currently set to 10%).
2. Enable the Manage Downloaded Episodes feature flag.
3. Download a few …
=> [Project] Manage Downloaded Episodes - Show the banner only if it has downloaded episodes and the device has low storage

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt, modules/features/podcasts/src/main/res/layout/fragment_profile_episode_list.xml, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/ManualCleanupViewModel.kt, modules/services/images/src/main/res/drawable/pencil_cleanup.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtil.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/StorageUtilTest.kt
- This PR adds the banner to downloads screen
- For this PR, the banner will always show when there is episode downloaded. In a later PR I will update the logic to handle the visibility
- Also the background color is different the one we have in figma. I am proposing these colors and asked p1729890721860929-slack-C07TL9YK9V1
- See VvERCFIopLjFL8Fnczsf8r-fi-119_1272
Fixes #3100
1. Have downloaded episodes
2. Have the Manage Downloaded Episodes feature flag enabled
3. Go to Profile -> Downloads
4. ✅ Ensure you see the banner
5. Tap on Manage Downloads
6. ✅ Ensure Downloaded files screen opens 
7. Select the Played option and Clean Up
8. Back to Downloads screen
9. ✅ Ensure you don't see the banner
10. Go to Profile -> Starred
11.  ✅ Ensure you don't see the banner
12. Go to Profile -> …
=> [Project] Manage Downloaded Episodes - Add banner to downloads screen to manager downloads

fastlane/Fastfile
Internal Ref: p1730124628114649/1730120910.298079-slack-C028JAG44VD
As discussed in Slack, the GitHub Release that gets created every time we do a new build had an empty description body.
This PR simply uses the content of `metadata/release_notes.txt` file—already extracted from the CHANGELOG during code-freeze—as the body when creating the GitHub Release.
> [!NOTE]
> This PR targets the `release/7.76` so that the tooling fix could already be beneficial to the current code-frozen `7.76` version and so that any potential betas and the future final build of `7.76` that will be made from `release/7.76`.
I'm not sure this is really worth it given how small and straightforward the change is, but if you want to test the change before it lands, you could:
- Change the `private_lane …
=> [Tooling] Make the created GitHub Releases use the extracted `metadata/release_notes.txt` file for their description body

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/worker/CuratedPodcastsCrawler.kt, modules/features/discover/src/test/kotlin/au/com/shiftyjelly/pocketcasts/discover/worker/CuratedPodcastsCrawlerTest.kt, modules/features/engage/src/main/kotlin/au/com/shiftyjelly/pocketcasts/engage/ClusterService.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/104.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/ExternalEntities.kt
This adds support for landscape images in the Trending cluster for Engage SDK integration.
1. Apply [this patch](https://github.com/user-attachments/files/17539221/engage.patch).
2. Install fresh version of the app.
3. Open the app
5. Wait a bit so that the Discover page is crawled.
6. Proceed with the [Engage integration workflow](https://developer.android.com/guide/playcore/engage/workflow) until the 3rd step.
7. Check that the trending cluster uses landscape images.
=> Use landscape images in the Featured cluster

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
- Update the shuffle button visibility. It will be visible only when the up next is not empty
- Context: p1730257991386309/1730230283.156089-slack-C07T08CTND9
Fixes #3089
1. Have the shuffle feature flag on
2. Play an episode and have up next empty
3. Tap on Up next tap
4. ✅ Ensure you don't see the shuffle button
5. Add episodes to up next
6. Open Up next
7. ✅ Ensure you see the shuffle button
[Screen_recording_20241030_085326.webm](https://github.com/user-attachments/assets/02d2ae5d-f750-4643-ac38-1b65ccedfe75)
[Screen_recording_20241030_085412.webm](https://github.com/user-attachments/assets/1c8a5be1-d117-4666-b7d4-71d3cd5d002f)
=> [Project] Up Next Shuffle - Update Shuffle Button Visibility

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt
- The Manage Downloads had extra bottom padding. I am removing this padding due this feedback: p1730045912253859/1729890721.860929-slack-C07TL9YK9V1
- The TextButton already has padding, that's why I don't need extra padding for this button coming from parent
Fixes #3117
1. Ensure the device has less than 10% storage available (or adjust lowStorageThreshold in StorageUtilTest.kt to simplify testing; it’s currently set to 10%).
2. Enable the Manage Downloaded Episodes feature flag.
3. Download a few episodes.
4. Navigate to Profile > Downloads.
5. ✅ Verify that Mange downloads from the banner has bottom padding reduced
=> [Project] Manage Downloaded Episodes - Reduce bottom padding under “Manage downloads”

modules/features/player/src/main/res/layout-land/adapter_player_header.xml, modules/features/player/src/main/res/layout-sw600dp/adapter_player_header.xml
The download podcast icon was added only to base layout configuration resulting in a missing icon when device was using, for example, the landscape orientation. Initially reported here: p1730362239561269-slack-C02A333D8LQ
Ideally we should rewrite the code so we don't have to maintain 3 different layouts for this but I'm not going to do this in this task.
There's also a separate issue where the "More actions" bottom sheet has accessibility issues in the landscape orientation on most devices and the title doesn't scroll which obstructs the actions and the whole content doesn't fit when scrolled to the bottom.
1. Play something.
2. Open the player.
3. Make the download action one of the shelf actions.
4. Switch your device to the landscape orientation.
5. Notice that the download action is …
=> Add missing download icon to shelf in all configurations

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- This PR opens the paywall with shuffle copy updated for plus card when a free user taps on shuffle button
- Figma: KjyDLK1DPPg3snPBMVGWHw-fi-148_3551
- Context: p1730305046943719/1730077568.183099-slack-C07T08CTND9
Fixes #3128
2. Add episodes to Up Next
3. Have a free user logged in
4. Go to Up Next
5. Tap on Shuffle Button
6. ✅ Ensure you see the paywall with the `Shuffle your episodes with Pocket Casts Plus, and more` copy for plus card
7. ✅  `plus_promotion_shown` event is tracked with `source = up_next_shuffle`
8. Swipe to Patron
9. ✅ Ensure you see the original Patron copy
10. Go to Bookmarks and open the paywall from there
11. ✅ Ensure you don't see the shuffle copy for plus card
[Screen_recording_20241030_141146.webm](https://github.com/user-attachments/assets/6 …
=> [Project] Up Next Shuffle - Display Paywall for free users

CHANGELOG.md, modules/features/profile/src/main/res/layout-land/fragment_profile.xml, modules/features/profile/src/main/res/layout/fragment_profile.xml
Fixes an issue where settings were not scrolling with the content in the landscape mode. Initially reported here: p1730362239561269-slack-C02A333D8LQ
I took the liberty of resizing the gift icon to match it size-wise with the cog icon so they align a bit better.
1. Sign in with a paid account.
2. Go to the Profile tab.
3. Switch orientation to the landscape mode.
4. Notice that the app bar icons scroll with the content.
| - | - |
| <video src="https://github.com/user-attachments/assets/dc2ee699-69f5-41f0-8501-47a6b39f3b44"> | <video src="https://github.com/user-attachments/assets/6ad1f596-b4fa-47fd-9216-6468d34eeb77"> |
=> Make profile app bar icons part of the scrollable content

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt, modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProviderTest.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
We saw this error in an user logs and we are trying to put a fix for this, but we are not sure what could be causing this issue. So this PR is just an attempt by adding some improvements
> E 24/10 09:52:19 ExPlat: anonymousId is null or empty, cannot fetch assignments. Make sure ExPlat was initialized.
java.lang.IllegalStateException: ExPlat: anonymousId is null or empty, cannot fetch assignments. Make sure ExPlat was initialized.
at ab.c1.f(SourceFile:1967)
at vu.v1.b(SourceFile:165)
at vu.d1.b(SourceFile:5)
at ab.b2.invokeSuspend(SourceFile:72)
at bu.a.resumeWith(SourceFile:9)
at su.j0.run(SourceFile:107)
at su.u0.Y(SourceFile:24)
at xu.a.j(SourceFile:141)
at su.a.m0(SourceFile:103)
at su.b0.y(SourceFile:24)
at su.b0.z(SourceFile:13)
at …
=> [Paywall Experiment] - Tweaks for Explat

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Experiment.kt
- This removes the AB for this release and keeps the AA experiment since we decided to postpone the AB experiment to release 7.77
- See: p1730365088978039/1730364878.300049-slack-C07DLM97HRQ
- Experiment: 21899-explat-experiment
=> [Paywall Experiment] Set AA Experiment for release 7.76

CHANGELOG.md, modules/features/podcasts/src/main/res/layout-land/view_podcast_header_top.xml, modules/features/podcasts/src/main/res/layout/view_podcast_header_top.xml, modules/services/localization/src/main/res/values/strings.xml
We want to rename the subscribe button to follow. See discussion pdeCcb-7cS-p2
I considered renaming the strings key but thought it would be best to keep the old translations until they were converted, as they are an important string label in the app.
Checking the strings file and screenshots is probably enough but if you want to find them on a device these are the steps.
1. Tap the Discover tab
2. Open a podcast you aren't subscribed to
3. ✅ Verify the label says follow
4. Tap the follow button
5. ✅ Verify the label says following while animating to a tick
6. Tap the green tick button
7. ✅ Verify the dialog uses unfollow 
8. Try steps 1 to 7 in landscape
9. Go to the Podcasts tab, tap the three dots, tap Share podcasts
10. Create a list and copy the URL
11. Unsubscribe from the podcasts …
=> Rename 'Subscribe' to 'Follow'

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
This updates `distinctUntilChanged` condition for `effectsSettingsSegmentedTabBar` to include global effects override state. 
3. Tap on effects view
4. Change playback speed in "All podcasts" view
5. Tap on "This podcast"
6. ✅ Notice that "This podcast" tab is selected and displays playback effects for the selected podcast. If podcast playback effects were never changed, it should display `1x, off, off` (p1730208229140779-slack-C07QMR40VV3)
=> Custom Playback Settings: Update distinctUntilChanged condition for selecting effects tabs

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Debouncer.kt
This updates analytics for playback effects settings.
Part of: #3042 
- Run the app and make sure the `custom_playback_settings` FF is off
- Open the player full screen and tap the Effects to prompt the sheet
- Enable/Disable the trim silence
- Event `🔵 Tracked: playback_effect_trim_silence_toggled ["enabled": SELECTED_VALUE, "source": "player_playback_effects", "content_type": "audio"]`
- Change the value of the Trim Silence
- Event `🔵 Tracked: playback_effect_trim_silence_amount_changed ["content_type": "audio", "source": "player_playback_effects", "amount": SELECTED_VALUE]`
- Enable/Disable the Volume Boost
- Event `🔵 Tracked: playback_effect_volume_boost_toggled ["enabled": SELECTED_VALUE, "content_type": "audio", "source": "player_playback_effects"]`
- Change the playback speed and …
=> Custom Playback Settings - Analytics

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt, modules/services/sharing/src/test/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingAnalyticsTest.kt
This PR adds `year` property to all End of Year analytics events.
=> Add year property to End of Year analytics

CHANGELOG.md, modules/services/repositories/src/main/res/values/colors.xml
The bug got introduced back in 2017 when the accent color got changed and it propagated forwards. [Here](https://github.com/Automattic/pocket-casts-android-private/commit/8528bb6336c94ebaeb560141b22f80613ac3d2de#diff-3406701c069879a69173ef9a1d12baf2a71b85b5881a36a21255fe0efb521d42L28) is the change that introduced it.
1. Trigger new episode notification from the developer options menu.
2. Notice that the icon uses red color as its background.
| - | - |
| ![share_6998091212107933246](https://github.com/user-attachments/assets/e34de4de-ddc2-4e61-9f74-a264ab68a896) | ![share_2330159640879517981](https://github.com/user-attachments/assets/43df17c4-30e7-402a-9ae6-d990a91bd8eb) |
=> Fix notification color

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt
- This removes the dash from the anon uuid in order to avoid this issue reported by data team: p1730400542921179/1730118881.270029-slack-C07DLM97HRQ
Code review is fine
=> [Paywall Experiment] - Update anon uuid 

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Settings.kt
This change improves the General settings page by removing the separators that were in the wrong place. Also, it removes the indent so the descriptions don't wrap over so many lines.
There is a `SettingSection` component, but the way the page is laid out it can't be used. In future commits I would like to improve the other settings pages to match this page.
Slack discussion p1730421542295429/1730421438.913309-slack-C05RR9P9RAT
2. Tap the settings cog
3. Tap General
4. ✅ Verify the page looks right 
| --- | --- |
| ![Old Settings](https://github.com/user-attachments/assets/b301c7d0-ec8f-4bfb-8e8c-076fd256281b) | ![New Settings](https://github.com/user-attachments/assets/dff0d213-9294-492b-a2db-7e6dc1fb66c3) |
=> Improve general settings

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt, modules/features/player/src/main/res/color/trim_mode_background.xml, modules/features/player/src/main/res/color/trim_stroke_color.xml, modules/features/player/src/main/res/layout/fragment_effects.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SegmentedTabBar.kt, modules/services/ui/src/main/res/values/dimens.xml, modules/services/ui/src/main/res/values/styles.xml
This updates trim mode component and segmented bar
Internal Ref: pdeCcb-7bh#comment-5868
Part of #3042 
Normal Font | Large Font| Plans
---|---|----
=> Custom Playback Effects - Update trim mode component and segmented bar

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This enables remote FF inside the app. It is still disabled in Firebase. 
Fixes #3042 
=> Custom Playback Settings - Enable remote FF

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Story.kt
Part of feedback from #3169
> Like I suggested for iOS, let's add 3s to the amount of time each story persists before jumping to the next one.
1. Start PB24.
2. Notice that stories auto-progress every 10 seconds instead o 7.
=> Extend story preview duration to 10 seconds

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
- This add tracks for managing downloads
- See: pdeCcb-7pb-p2
Fixes #3102
1. Apply this [track-mock.patch](https://github.com/user-attachments/files/17621355/track-mock.patch)
2. Download an episode
3. Go to Profile -> Downloads
4. ✅ Ensure you see the free up space banner and `free_up_space_banner_shown` event is tracked
5. Tap on Manage Downloads
6. ✅ Ensure `free_up_space_manage_downloads_tapped, Properties: {"source":"downloads"` is tracked
7. Go to Profile -> Storage & data usage
8. See the free up space modal
9. ✅ Ensure you see the free up space modal and `free_up_space_modal_shown, Properties: {"source":"storage_and_data_usage"` event is tracked
10. Tap on Manage Downloads
11. ✅ Ensure `free_up_space_manage_downloads_tapped, Properties: {"source":"storage_and_data_usage"` event is …
=> [Project] Manage Downloaded Episodes - Add Tracks

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/localization/helper/DurationUtilTest.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/LongestEpisodeStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TotalTimeStory.kt, modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/DurationUtil.kt, modules/services/localization/src/main/res/values/strings.xml
Part of feedback from #3169
> In this screen, I'm realising that values like these (which should be common) look a bit dumb. To make it better, I'm suggesting we change the logic to show anything that's below 100 hours in hours (for example, this would be "41 hours") and anything greater in days/hours. Can we add the number of minutes too?
It updates all displayed duration texts as requested here: p1730808072188289/1730808008.565789-slack-C041BGTFQ5R
1. Start PB24.
2. Have less than 100 hours listened or fake this data in `EndOfYearViewModel`.
3. Navigate to the Total Time story.
4. Time should be displayed in hours and not in days.
| - | - |
| ![Screenshot 2024-11-05 at 14 37 42](https://github.com/user-attachments/assets/78a79f8c-1a23-4c8a-b834-0326a5a1e851) | …
=> Add configurable duartion formatting

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
If episodes are auto downloading there is no need also to download the content type and file size in a separate task.  The content type logic is also [found here](https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt#L590) in the download episode task.
2. Subscribe to a podcast
3. Cause a new episode by tapping Profile -> Settings cog -> Developer -> Delete first episodes and then Force refresh
4. In Android Studio open the App Inspection tool window and the Background Task Inspector task
5. ✅ Verify that no metadata tasks have run `UpdateEpisodeDetailsTask`
=> Don't download episode metadata when already downloaded

CHANGELOG.md, modules/services/servers/build.gradle.kts, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptor.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt, modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptorTest.kt
This PR adds fallback to non-PC requests when hosts refuse to serve content.
Closes #3164
1. Go to [Questions & Answers](https://pca.st/SxW3) podcast.
2. Episodes should play and download.
=> Retry streaming and downloading with different headers

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/YearVsYearStory.kt
Part of feedback from #3169
>  I'm not sure what's happening here with the sphere sizes, since 2024 is supposedly more than 500% higher than 2023. Is the number wrong or the sphere size wrong?
1. Start PB24 as a paid user.
2. Go to the Year vs Year story.
3. Verify the UI.
4. You can repeat the steps with different ratios by modifying the code below.
https://github.com/Automattic/pocket-casts-android/blob/6ef064fd7ccd4008dc4d08fbfaab11effa7eb210/modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt#L151-L155
=> Update Year vs Year story UI

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModel.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/Common.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt, modules/features/endofyear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/endofyear/EndOfYearViewModelTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PagerProgressingIndicator.kt
This update aligns the PB24 progress bar with the design specifications. Previously, seen stories were displayed as active segments, but now they are shown as inactive, consistent with the intended design.
Additionally, if a story does not auto-progress, it will now appear as an active segment on the progress bar, providing a clearer visual cue for the user.
1. Start PB24 as a free user.
2. Navigate forward to some story.
3. Notice that the progress bar doesn't show previous segments as active.
4. Navigate to the Plus Interstitial story.
5. It should be shown as active in the progress bar.
| - | - |
| ![Screenshot 2024-11-06 at 10 52 58](https://github.com/user-attachments/assets/1da34290-48d5-4173-85c2-c40efd85293d) | ![Screenshot 2024-11-06 at 10 52 …
=> Update EoY progress bar

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt
This PR changes screenshot capturing logic in the Top Show story. Previously the animation was being reset to the initial state but it doesn't make much sense for this animations since it is an infinite loop and screenshots are more interesting and varied this way.
1. Start PB24.
2. Go to the Top Show story.
3. Share the story at different points of the animation.
4. Each time the cutout shape should be in the correct position.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/4878380e-4a19-4c7b-87e4-8a472bd9e8a5"></td>
<td><img src="https://github.com/user-attachments/assets/75634f08-2326-4f31-807e-0b441fbdb94d"></td>
<td><img src="https://github.com/user-attachments/assets/5ce972f7-f962-4b3b-bb75-0a9f6ae1a53f"></td>
</tr>
</table>
=> Do not reset Top Show animation for screenshots

build.gradle.kts
This is a followup to the discussion about transitive dependencies. To sum up it is useful for others and it doesn't hinder us in any meaningful way. For more context see here: pdnsEh-1QL-p2#comment-4100
1. Run `./gradlew buildHealth`.
2. Verify that the report contains transitive dependencies warnings.
=> Warn about transitive dependencies

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
- We decided to run the experiment only from onBoarding and Profile source. The others source will always open the original paywall layout
- See: p1730319424980979/1730077568.183099-slack-C07T08CTND9
Fixes #3143
1. Apply [updated.patch](https://github.com/user-attachments/files/17647669/updated.patch) to mock the experiment to run Reviews Layout
2. Run the app
4. Start the account creation flow
5. ✅ After tap on `Not now` from recommendation screen, you should see the Reviews Layout Paywall Experiment
6. Go to Profile
7. Scroll down and tap on the learn more banner about plus
8.  ✅ You should see the Reviews Layout Paywall Experiment
9. Try to open the paywall from others sources such as folders, bookmark, etc
10. ✅ You should see the original paywall layout …
=> [Paywall Experiment] - Run Experiment only from onboarding and profile

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLogInViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/IdentifyingTracker.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/di/ExperimentModule.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt, modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProviderTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
- We encountered an issue where data from the AA experiment was not being collected. After investigation, the data team identified the problem: we were using different UUIDs for Tracks and Explat when we should have been using the same one. So this PR make sure we use the same uuid for both cases.
- See: p1730936149575659/1729729858.793479-slack-C046HLX37K2
Fixes #3193
1. Apply [log-track.patch](https://github.com/user-attachments/files/17670975/log-track.patch) to log the uuid every time an event is tracked
3. Look for `ExperimentsProvider` in logcat
4. See what uuid the explat was initialized: ExperimentsProvider: Initializing experiments with uuid: {uuid}
5. Navigate to some screen to track event
6. ✅ Ensure the event tracked has the same uuid you saw in step 4 …
=> [Paywall Experiment] - Use the same UUID for both Tracks and Explat

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
This is a simple change to fix the Up Next timing, clean up the repeating logging statement a little, and remove a log we don't need. I'm making this change as I'm working on tracking down what's slow in a refresh, I have another change but I'm splitting it into another PR as it's bigger. 
```
BgTask: Refresh - podcasts response - 1917 ms
BgTask: Refresh - sync complete - 48 ms
BgTask: Refresh - sync up next - 2917 ms
BgTask: Refresh - sync settings - 359 ms
BgTask: Refresh - sync play history - 6 ms
BgTask: Refresh - checkForEpisodesToAutoArchive - 17 ms
BgTask: Refresh - checkForUnusedPodcasts - 5 ms
BgTask: Refresh - playlist checkForEpisodesToDownload - 1 ms
BgTask: Refresh - podcast checkForEpisodesToDownload - 17 ms
BgTask: Refresh - updateNotifications - 1 ms
```
There isn't much …
=> Logging Refresh call times

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
- This PR adds the ability back to disable all auto download podcast status after disabling the global Auto download flag
- Put back the code that was removed here: https://github.com/Automattic/pocket-casts-android/pull/3020/files
- To handle cases where users have already configured global auto-download, I refactored `autoDownloadNewEpisodes` to be a `UserSetting<Int>` instead of a `UserSetting<Boolean>`. This change allows me to determine whether the user manually disabled the `New Episodes` toggle or if it was simply unset due to using an app version prior to `7.76`, which does not yet include the autoDownloadNewEpisodes toggle
- This issue was reported here: pdeCcb-7pt-p2#comment-5894 in our Beta Testing
1. Fresh install
2. Subscribe to a podcast
3. ✅ Verify the episodes are auto …
=> [Auto Downloading] - Disable all podcasts auto download status when disabling the Global Auto Download

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt
This PR makes sure that screen doesn't go to sleep while in the End of Year flow.
1. Go to devices settings and set the screen timeout settings to the lowest possible value. Disable any additional settings, like "Screen attention" that can prevent screen from turning off.
2. Make sure that your device is not connected to a power source.
4. Start PB 24 flow.
5. Let it run.
6. Screen shouldn't go to sleep while in the EoY flow.
=> Keep screen alive during EoY flow

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ExternalDataDaoTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/utils/FakeFileGenerator.kt, app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/PodcastFolderHelperTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/PodcastFolderHelper.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/PodcastsSortType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
This PR makes the following changes 
1. `Cross-Platform Sorting`: The "Sort by" order on Android matches iOS and Web:
- Name
- Episode Release Date
- Date Added
- Drag and Drop
2. `Date Added Sorting`: New podcast subscriptions are added to the top of the list instead of at the bottom
Internal Ref: p1730854048067249-slack-C06EHRAPW12
1. Login with an account with podcasts and folders
2. Go to the `Podcasts` tab 
3. Open `Sort By` options using more menu in the top bar
4. ✅ Notice that sort options are displayed in the following order
- Name
- Episode Release Date
- Date Added
- Drag and Drop
5. Go to `Discover` tab and follow a podcast
6. Tap on `Podcasts` tab and notice that the podcast is added to the top of the list
7. Go to Discover and follow another podcast
8. Add this podcast to an …
=> Update date added podcast display sort order

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ExternalDataDaoTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ExternalDataDao.kt
Follow up to #3192. Since the sort order changed its meaning it should be updated in the query as well.
Code review should be enough since the data access is covered by tests.
=> Apply correct sort order in ExternalDataDao

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
This contains two changes:
- On Wear OS and Android Automotive, it disables the background job that checks the episode content type and file size. As these both have limited resources and neither play video I think it would be good not to add this processing when the app finds new episodes.
- There could be the case that these jobs would retry forever. To stop this happening I have added a retry limit for three.
1. Apply this patch to make it easier to test [testing.patch](https://github.com/user-attachments/files/17674050/testing.patch)
2. Deploy the app to an Automotive emulator
3. In the app play an episode to subscribe to the podcast
4. Tap the settings cog and refresh
5. ✅ Verify no tasks have been created by filtering logcat for `UpdateEpisodeDetailsTask` 
6. Deploy the app to a …
=> Don't update episode metadata on Wear OS or Automotive

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/ServiceStatusChecker.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/CastsWorkerFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerDataSourceFactory.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServiceManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt
`UpdateEpisodeDetailsTask` and `ServiceStatusChecker` didn't use DI for `OkHttpClient` which can lead to performance degradation and generally is harder to maintain as we update our network layer.
1. Test if status check still works.
2. Play an episode and check if you can see the episode details.
=> Inject OkHttpClient to episode details task and to status checker

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CrashMessageDialog.kt
Use a correct resource for screenshot dialog title.
Code review should be enough. But you can test screenshot detection.
| - | - |
| ![Screenshot 2024-11-13 at 07 15 33](https://github.com/user-attachments/assets/f22f4602-f834-434b-b4d5-23edb35c01a8) | ![Screenshot 2024-11-13 at 07 15 28](https://github.com/user-attachments/assets/a6b81ae2-b883-4024-a95c-4d6906b3c6d2) |
=> Fix dialog title

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerSeekBar.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
When the app is first open or playback is paused, the player doesn't show that the playback effects are enabled. The reason is that a new PlaybackState is created without these effects. 
I have tried to group the initialisation logic and put it in the PlaybackState object to stop the repeating code.
Fixes https://github.com/Automattic/pocket-casts-android/issues/3057
1. Go to Profile tab -> Settings -> General
2. Turn on "Adjust remaining time"
4. Open the full screen player
5. Take note of the time remaining
6. Tap on the effects icon
7. Increase the playback speed to 2
8. Close the effect dialog
9. ✅ Verify the time remaining has decreased
10. Pause the episode
11. Move the seekbar to a different position in the episode 
12. ✅ Verify the playback effect icon stays …
=> Fix effects being lost when paused

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/PackageValidator.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt
We need to make a few upgrades before changing the `targetSdkVersion` and `compileSdkVersion` to 35. The main change is upgrading to edge to edge and I will try to do this in another PR. The changes in this PR are caused by errors while trying to build using 35.
These changes are strange to test while we aren't targeting SDK 35. The round corner change is because the method changed from @NotNull to @Nullable. And I'm not sure it's possible to test the PackageValidator.kt change as it's related to Automotive.
- Open the mobile app
- ✅ Check the podcast image corners are rounded
- Open the Automotive app
- ✅ Check you can play an episode
=> Start Android 15 upgrade

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/MenuShelfItems.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfItemRow.kt
This updates shelf row item ripple configuration to have a light color as the background is always dark.
Noticed in: https://github.com/Automattic/pocket-casts-android/pull/3214#discussion_r1839164893
1. Choose a dark theme
2. Play an episode 
3. Open the full-screen button and tap more button in the shelf
4. Long press a shelf item in the more actions dialog
5. ✅ Notice that the ripple is light in color (before compose migration we used `selectableItemBackground` as item background in the XML which also uses a white color ripple)
https://github.com/user-attachments/assets/55444626-2b72-4807-af1c-b325e831d33f
=> Shelf Row Item - Update ripple configuration

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/StoriesPage.kt
This changes PB24 segments filing back.
See: p1731478656991879-slack-C041BGTFQ5R
1. Start PB24.
2. Make sure that segments for seen stories are filled in with an active color.
| - | - |
|  ![Screenshot 2024-11-06 at 10 52 24](https://github.com/user-attachments/assets/7bb0722f-7b50-4be7-990d-a3327aee9b2c) | ![Screenshot 2024-11-06 at 10 52 58](https://github.com/user-attachments/assets/1da34290-48d5-4173-85c2-c40efd85293d) |
- [z] Ensure the linter passes (`./gradlew spotlessApply` to automatically apply formatting/linting)
=> Make seen EoY segments filled

build.gradle.kts, modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/clip/ShareClipViewModel.kt, modules/services/media-ffmpeg/src/main/kotlin/au/com/shiftyjelly/pocketcasts/media/FFmpegMediaService.kt
`FFmpegKitConfig` retains session history. Sessions hold references to callbacks, which, in turn, hold references to view models and fragments. There is no mechanism in the FFMpegKit library to clear a single session or to retain no history. For this reason, I clear the entire history after a session completes its task.
Issue reported here: https://github.com/arthenica/ffmpeg-kit/issues/1066
1. Share an audio or a video clip.
2. Close the sharing flow.
3. Using Leak Canary or Android Studio's memory profiler verify that `ShareClipFragment` and `ShareClipViewModel` do not leak.
=> Fix clip sharing memory leak

Gemfile, Gemfile.lock, fastlane/Fastfile
This PR automates 🤖  the creation of the backmerge PR after having triggered a new beta build (post-code-freeze or post-beta) and after having finalized the final release.
It also removes the `complete_code_freeze` lane after having moved the action that it did (triggering a new build) directly in the `code_freeze` lane. That way, Release Managers don't have to run `code_freeze` then `complete_code_freeze` lanes back-to-back every time, and will instead now just have a single `code_freeze` lane to run instead of two. 🎉 
> [!NOTE]
> This PR has a corresponding diff on the ReleasesV2 scenario (see D166226-code) to adjust the tasks in the checklist accordingly.
The whole scenario is not easily testable without going through the real release steps.
But if there are new commits on the current …
=> [Tooling] Automate creation of backmerge PRs

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt, modules/features/podcasts/src/main/res/layout/fragment_profile_episode_list.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/lowstorage/LowStorageDialog.kt
During beta testing, it was noticed that the theming on the low storage card wasn't correct. The icon color didn't work on different themes and the background around the card was incorrect. 
1. In the method `ProfileEpisodeListFragment.updateManageDownloadsCard` change the `isVisible` to true while testing
2. Tap the Profile tab -> Downloads
3. ✅ Verify the theme looks correct
|  |  |  |
|--------|--------|--------|
| ![Screenshot_20241115_115558](https://github.com/user-attachments/assets/b7ea6e0b-98dd-4c86-aece-ddc274bd50b7) | ![Screenshot_20241115_115544](https://github.com/user-attachments/assets/9e3426d6-4c03-4754-9e9a-33cec4ed187b) | ![Screenshot_20241115_115515](https://github.com/user-attachments/assets/fc5160aa-23ff-4340-9807-56b03afe6e7c) |
| …
=> Fix low storage card theme colors

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerDataSourceFactory.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This removes `EXO_OKHTTP` flag and leaves the code that assumed it was true.
Smoke test playback and downloading.
=> Remove ExoOkHttp feature flag

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt, modules/features/filters/src/main/res/layout/fragment_filters.xml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreatePodcastsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateTitlePage.kt, modules/features/podcasts/src/main/res/layout/fragment_podcast.xml, modules/features/profile/src/main/res/layout-land/fragment_profile.xml, modules/features/profile/src/main/res/layout/fragment_profile.xml, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchEpisodeResultsPage.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchPodcastResultsPage.kt, modules/features/search/src/main/res/layout/fragment_search.xml, modules/services/ui/src/main/res/layout/settings_pocketcasts_settings_fragment.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/component/StatusBarSpacer.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Toolbar.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/View.kt
This change focuses on all the screens in the podcasts tab. Please ignore the other tabs for now.
One issue I'm struggling to solve at the moment is the bottom sheet navigation bar color. I will have another attempt at fixing it in a future PR.
There will be multiple pull requests required to support Android 15 edge-to-edge but I'm going to break them down into smaller PRs. I will merge them all into a `task/android-15` branch, and after all the work is completed, raise a PR to merge into `main`.
It would be good if you could try tapping around in the podcasts tab to find issues with the edge-to-edge changes. Areas I have found issues with are:
- Older versions of Android versions
- Themes
- Content under the system bars 
- End of pages / lists under the bottom navigation or mini player …
=> Support edge-to-edge for the whole podcasts section

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileUpgradeSection.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt, modules/features/profile/src/main/res/layout-land/fragment_profile.xml, modules/features/profile/src/main/res/layout/fragment_profile.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This migrates Plus offer to Compose UI.
1. Start with a fresh install.
2. Do not sign in.
3. Go to the Profile tab.
4. Scroll down.
5. You should see the Plus offer.
6. Play any podcast.
7. Go back to the Profile tab.
8. Scroll down and notice that mini player does not obstruct the UI.
9. Sign in.
10. Notice that there is no Plus offer in the Profile tab.
11. Sign out.
12. Scroll down to the Plus offer.
13. Tap on the close button.
14. Plus offer should be gone.
15. Close the app.
16. Reopen the app.
17. Plus offer should still be gone.
* Verify UI in landscape mode.
* Verify UI with different themes.
=> Migrate Plus upgrade in profile tab to Compose UI

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EndOfYearDao.kt
This PR updates how the longest episode is calculated for the PB24. Previously it used episode's duration, not it uses played up to time. It's late into the beta release but the feature is heavily tested in different layers so I feel safe about changing it.
1. Sign up with a new account.
2. Play some episode and scrub it until the end.
3. Play this episode https://pca.st/iytpbo1t and pause it after a couple of seconds of playback.
4. Start PB24.
5. You should see the episode you scrubbed to the end as the longest episode.
=> Use played up to time for longest episode calculation

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
There was an issue in the sync process that would cause the deselect chapters to keep syncing. This was because the modified value wasn't set to null after it was synced, causing the new sync to send it again.
- Fresh install the app
- Create a new account
- Upgrade it to Plus 
- Subscribe to a podcast with chapters for example Upgrade https://pca.st/upgrade
- Play an episode
- Open the full screen player and chapters tab
- Tap "Preselect chapters" 
- Unselect a chapter and tap Done
- Open the Android Studio window "App Inspection" and the "Network Inspector" tab
- Back in the app tap the Profile tab -> refresh button
- Find the `/sync/update` call
- The request is encoded but you should be able to see the `deselected_chapters` being sent and an episode being returned in the response
- …
=> Improve syncing of deselected chapters

Dangerfile
This is a change related to an update in the Linter CI Agent to make sure Rubocop is run with `bundle exec`.
CI should be 🟢
=> [Tooling] Update `Dangerfile` to run Rubocop with `bundle exec`

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileHeader.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfilePage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileSections.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileStats.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Devices.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
After completing migration this is the last PR that cleans things up:
* Moved the whole Profile screen to a separate composable.
* Decoupled referrals card and tooltip from the view model.
* Moved logic from `ProfileFragment` to the view model.
Do monkey testing of the profile screen. Check orientation, theming, tapping on things, different accounts, etc.
=> Profile screen cleanup

CHANGELOG.md, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
Closes #3263
1. Run the Automotive app.
2. Login to a Pocket Casts account.
3. Sign out.
=> Do not stop view setup when there is no toolbar

CHANGELOG.md
This got cherry-picked (https://github.com/Automattic/pocket-casts-android/pull/3227) to `7.77` and is available in that changelog.
Green CI.
=> Remove effects bug fix from 7.78 changelog

app/build.gradle.kts, app/lint-baseline.xml, app/src/main/AndroidManifest.xml, build.gradle.kts, gradle/libs.versions.toml, modules/features/settings/build.gradle.kts, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LicensesFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
This PR replaces OSS Gradle Plugin with, already used in `automotive`, About Libraries to display list of dependencies, and their licenses, in "Acknowledgments" section of the app.
This change is motivated by lack of support of OSS Gradle Plugin for Gradle's Configuration Cache
1. Open Settings > About > Legal and more > Acknowledgements
2. Verify that you can see dependencies used in the app. Tapping on a dependency shows details about its license
https://github.com/user-attachments/assets/a7f9051c-9b0b-4e9d-8c9e-a61defaa184c
https://github.com/user-attachments/assets/263e869b-6203-4a9c-9829-27ed88d5c678
- [-] Any jetpack compose components I added or changed are covered by compose previews (list of dependencies won't be rendered, so I don't think it's necessary to provide a preview)
=> Migrate to `about libraries` in mobile app

modules/features/player/src/main/res/layout-sw600dp/adapter_player_header.xml
This fixes shelf row position for tablets. It was broken in  #3254
1. Play an episode on tablet
2. Open full screen player
3. ✅ Notice that Player UI elements are rendered properly
Before #3254 | In #3254 | Now
-----|---|----
=> Fix shelf row position for tablet

gradle/libs.versions.toml
This reverts #3241 which causes crashes on Wear OS.
1. Install Wear OS app.
2. Play any episode.
3. It should not crash.
=> Revert Compose ConstraintLayout bump

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
I noticed on Wear OS that there's an issue with the current episode not being loaded into the Now Play page. When building the initial playback state I missed setting the state variable.
[Screen_recording_20241126_210132.webm](https://github.com/user-attachments/assets/5287da37-6b19-4186-b37d-6a4d02c1ec8a)
1. Open Wear OS
2. Play an episode so there is an episode loaded in the now playing page
3. Reload the app
4. Tap the now playing chip
✅ Verify episode is loaded
=> Fix episode not loading on Wear OS

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt
This issue fixes a crash on SDK 26 when starting PB24. The crash happens due to an issue in SDK 26 where an `Activity` with a translucent window cannot be shown on top of another `Activity` and request orientation.
I've decided to remove orientation request completely instead of only on SDK 26. I want to avoid any potential issues with some obscure OEMs, etc. While a landscape preview suffers from it users can always rotate their device.
1. Start PB24 on a device with SDK 26.
2. It should not crash.
=> Do not request orientation in StoriesActivity

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountSections.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PocketCastsColors.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/GradientRowButton.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PocketCastsPill.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserAvatar.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Brush.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
This PR standardizes colors used for PC, Plus, and Patron. Also I added `ColoredDark` theme to the `SubscriptionBadge` component to match it with the `UserAvatar` component.
Smoke testing if badges, upsell buttons and avatar use correct colors should be enough.
=> Clean up Pocket Casts colors

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingWelcomePage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeButton.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeLayoutComponents.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallfeatures/UpgradeLayoutFeatures.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallreviews/UpgradeLayoutReviews.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PocketCastsColors.kt
- This just moves the brush gradient to Pocket Casts Colors
- Code review and CI should be fine, but you can check the gradient background colors and subscription badge if you wanted
=> Move Brush Gradient to Pocket Casts Colors

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountHeader.kt
This fixes label positioning under account header and matches it with how they behaved before Compose migration.
1. Sign in with an account that would show 2 labels. Like, for example, a champion account.
2. Go to the account details.
3. Increase the OS font size.
4. Verify labels under the profile header.
| - | - |
| ![vef](https://github.com/user-attachments/assets/af40aec1-f1e5-4a32-8d57-901b7110a723) | ![Screenshot 2024-11-29 at 11 17 23](https://github.com/user-attachments/assets/5f18a2ab-136b-4df1-bb37-b48e1aa066af) |
=> Fix account header label weights

fastlane/Fastfile
- 🆕  Introduce a new lane to update rollout of all 3 variants (app, automotive, wear), e.g. `fastlane update_rollouts percent:0.20`
- 🧹  Migrate the `Fastfile` syntax to use keyword params for lanes and improve lane YARD documentation
Once this PR is merged I'll follow-up with a diff in the MC Scenario template to replace the manual 3 tasks about updating the rollout manually with a single one to run the lane instead.
> [!NOTE]
> This PR targets `release/7.78` so that it the new lane can already be tested as part of `7.78`. That way if we confirm it works as expected, we'll already be able to include it in scenarios for `7.79` onwards (instead of only starting testing this as part of `7.79` and adopt it fully only in `7.80`)
Depending on the stage at which the current release is in Google …
=> [Tooling] Introduce lane to automate rollout update

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/features/settings/src/main/res/xml/preferences_auto_download.xml, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
- This splits the responsibility of New Episodes toggle in order to have the new toggle On Follow Podcast exclusive for auto download episodes when following new podcasts
- Context: p1732795876867519-slack-C06EHRAPW12
- This new toggle will be enabled by default for new users only 65ee94b3e966fed4a0f264e5a06bd7deb5b40323
- Added the new event for On Follow toggle: `settings_auto_download_on_follow_podcast_toggled`
- I reverted the New Episodes toggle being enabled by default to new users: [2968919](https://github.com/Automattic/pocket-casts-android/pull/3303/commits/296891957a0141a00aea99b1a961c1ae3b8fa2cf)
1. Have a fresh install
2. Open the App
3. Go to Profile -> Settings -> Auto download
4. Verify you have Limit download sets to two latest as default ✅
5. Verify you have `On Follow` …
=> [Auto Downloading] - Add the auto download toggle for new podcast following

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, app/src/main/res/layout/activity_main.xml, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/services/localization/src/main/res/values/strings.xml
- Displays snackbar when toggling shuffle on
- Cherry-picked https://github.com/Automattic/pocket-casts-android/pull/3272/commits/0d2cc39fb279bef5118013bccb7d2679f45ab83a and copied some changes from `task/android-15` to fix snackbar position
- I noticed that our current Snackbar experience does not work well with TalkBack. After the Snackbar is displayed, TalkBack does not have enough time to read it before it disappears
Fixes #3327
1. Log with a plus account
2. Add some episodes to Up next
3. Toggle shuffle on
4. See the snackbar ✅
5. Toggle the shuffle off
6. You should not see the snackbar ✅
=> [Up Next Shuffle] - Add snackbar confirmation for when enabling shuffle

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Experiment.kt
- We had to postpone again the AB experiment for `7.78` instead of `7.77` due an issue that we found that we were not collecting data for AA experiment. See for more context: p1730987811857399/1729729858.793479-slack-C046HLX37K2
- This PR replace the AA experiment for AB experiment
Fixes #3142
Code review is fine
=> [Paywall Experiment] Set AB Experiment for 7.79

CHANGELOG.md, modules/features/player/src/main/res/menu/upnext.xml, modules/services/localization/src/main/res/values/strings.xml
After user feedback we have changed the Up Next clear all button.
Fixes https://github.com/Automattic/pocket-casts-android/issues/3313#issuecomment-2521170083
1. Add some episodes to the Up Next
2. Open the Up Next
3. ✅ Verify the clear all button has change.
| --- | --- |
| ![Screenshot_20241206_150716](https://github.com/user-attachments/assets/96180928-3176-49c6-bd95-084399bd63bd) | ![Screenshot_20241206_150438](https://github.com/user-attachments/assets/ee63cf46-5ffc-4264-903d-c8b5951c793a) |
=> Improving the Up Next clear all button

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfRowItem.kt
This moves `Add bookmark` shelf item after the `Go to podcast` item to align with iOS. See: p1733730713364929-slack-C028JAG44VD
1. Don't have a custom shelf items order.
2. Play a podcast episode.
3. Go to player.
4. Tap on the overflow menu on the shelf.
5. Notice that `Add bookmark` is positioned after `Go to podcast`
| - | - |
| ![before](https://github.com/user-attachments/assets/ffc17650-62cf-44a9-b75f-f8e98672d4af) | ![after](https://github.com/user-attachments/assets/1414758a-aab9-488e-ae4d-7bc9b705da4d) |
=> Position bookmark shelf item after podcast navigation item

CHANGELOG.md, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/LogsViewModel.kt, modules/features/settings/src/main/res/menu/menu_help.xml
Requesting a user's log is difficult, so this change aims to help improve this.
- When sharing a log it prefills the support email to make it easier for users.
- The logs toolbar action has been moved into the overflow menu to make it easier to explain rather than saying to tap the hamburger.
Slack discussion: p1733458200619619/1733441524.933739-slack-C029BMW150R
1. Tap Profile
2. Tap Help & feedback
3. Tap the three dots in the toolbar
4. Tap Logs
5. Tap Share
6. ✅ Verify the support email add been added
| |  |
| --- | --- |
| <img width="510" alt="Screenshot 2024-12-08 at 8 03 31 am" src="https://github.com/user-attachments/assets/783476ce-fee9-475e-82ee-b4fc11822990"> | <img width="510" alt="Screenshot 2024-12-08 at 8 03 56 am" …
=> Improve user log sharing

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
- Add auto download on follow toggle to support file
1. Go to Profile -> Auto download screen
2. Enable On Follow toggle
3. Go to Profile -> Help & feedback
4. Tap the three dots in the toolbar
5. Tap Log
6. See that you have On Follow toggle enabled
=> [Auto Downloading] Add auto download on follow toggle to support file

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoryCaptureController.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtil.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/BitmapUtilTest.kt
Instagram has an expectation of `9:16` aspect ratio when sharing content to it but different devices have different screen sizes. This PR ensures that a captured Playback Story conforms to IG requirements by adding black padding strips to edges.
Previously, sharing a story to IG caused our images to be cropped and users had to manually zoom it out.
https://github.com/user-attachments/assets/0c60453a-c7ff-45be-915e-485cd8f68e6d
1. Start PB24.
2. Share a story to Instagram.
3. It should not be cropped and should fit the screen.
| - | - |
| ![regular-before](https://github.com/user-attachments/assets/29382c13-35e1-4960-b33c-ec11ece16d54) | ![regular-after](https://github.com/user-attachments/assets/bf923f75-756b-41c7-b297-f05f3c8e2a5b) |
=> Share Playback Stories in 9:16 aspect ratio

CHANGELOG.md, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
- Auto download screen was updating podcast auto download setting when this screen was opened
Fixes #3338
- Follow the steps from https://github.com/Automattic/pocket-casts-android/issues/3338 to make sure the issue was fixed
[Screen_recording_20241209_130121.webm](https://github.com/user-attachments/assets/b6b802ff-1b32-4336-a6ff-da5ffc66c530)
=> Fix: Disabled global Auto download new episodes setting overrides podcast specifc one

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountHeader.kt
Champion users navigating to the account details would see incorrect information about their account. This happened during account details migration to Compose UI where I made a mistake of considering Champion status only for paid accounts and not supporter accounts. Now the Champion status is applied correctly across all subscriptions.
Reported here: https://pocketcastsbeta.slack.com/archives/C013F9S9C2W/p1733998102685089
I also went ahead and informed the community: https://www.reddit.com/r/pocketcasts/comments/1hcis87/pocket_casts_champion_ui_bug_in_779_beta/
Hard to test it without a real Champion account and not one created through the Admin tool. But code review should be enough as the change is covered by previews. The old logic applying champion status looked like this: …
=> Fix issue where Champion information was not considered in the UI

.buildkite/pipeline.yml, .buildkite/release-builds.yml, .github/workflows/gradle-wrapper-validation.yml
Reference: p7H4VZ-59z-p2
PocketCasts Android doesn't use one of the GitHub Actions about to have its older versions deprecated as `actions/upload-artifact`, `actions/download-artifact` or `actions/cache`, but I used this opportunity to upgrade the Action `gradle/actions/wrapper-validation` and to move the Buildkite Gradle Wrapper Validation to the Linter queue.
=> [Tooling] Update GitHub Actions

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/NotificationPermissionHelper.kt
- This is part of https://github.com/Automattic/pocket-casts-android/pull/3350 whether we are removing the notification permission request from the first screen in order to request when is actual needed.
- This PR, requests the notification permission when the user tries to enable the `Notify me` toggle from Notification screen.
- Here, I am proposing to disable the `Notify Me` toggle when the user had this one previous enabled, but removed the notification permission after that because does not make sense to let the user with the Notify me enabled when this one removed the notification permission
Fixes: #3358
1. Have a fresh install
2. Go to Profile -> Settings -> Notification
3. Enable Notify me toggle
4. ✅ Ensure you see the notification request permission
5. Allow it
6. ✅ Have Notify …
=> Request permission before enabling Notify Me

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/NotificationPermissionHelper.kt
- This is the first PR to improve the notification permission request. Here, I am proposing to request the notification permission when is actually needed. This PR removes the notification permission request from the first screen and move it to when  the user tries to enable the notification for a podcast.
- I did not change the notification message the we already have in the app. 
- ⚠️ I am going to handle the `Warm before using data` notification in another PR
Fixes #3360
1. Have a fresh install 
2. Open the app and ensure you don't see the notification request in Log in page ✅
3. Go to some podcast
4. Follow this podcast 
5. Tap to enable the notification
6. Ensure you see the notification permission
7. **Allow it**
8. Ensure you see the toast with notification ON ✅
1. Have a fresh …
=> Don't show the notification permission request as the first screen

.github/workflows/run-danger.yml
Reference: p1734116587744489-slack-C02KLTL3MKM
Changes in this PR:
- Run Danger when a PR is Ready for Review (previously, this was triggered by CI but we updated to avoid the extra full build).
- Run Danger when a PR has been edited (this is required by the ViewChecker Danger plugin)
- Uses Dangermattic GHA workflow latest `v1` version instead of an specific version
- Some workflow file clean-up
CI should be 🟢 
I've also confirmed Danger ran properly when the PR moved from Draft to Ready For Review, as well as when editing the description.
=> [Tooling] Danger GitHub Actions configuration update

CHANGELOG.md, app/src/test/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModelTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
This fixes an issue in beta, where the podcast rating page doesn't load. It seems to relate to the `UserManager.getSignInState` combining a Flowable and Flow. If I change the Coroutines dispatcher to IO it appears to fix the issue but until we switch the whole method to Flow, I have added a Flowable version that fixes the issue as well. Please let me know if you have any ideas why this code might cause the method to hang.
```
.combineLatest(syncManager.emailFlow().map { Optional.of(it) }.asFlowable())
```
I have also improved the ratings page to not use this as it only needs to know if the user is logged in and not the full sign in state.
1. Don't be signed into an account
2. Open a podcast page
3. Expand the header
4. Tap on "Rate"
5. ✅ Verify you are asked to login
6. Sign into a Pocket …
=> Fix podcast ratings not loading

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/FolderDaoTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/PromoCodeViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/FolderDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServiceManager.kt
The aim is to slowly remove the Rx from the project, this change continues to switch parts of the user sync task to Coroutines.
1. Install a fresh version of the app
2. Sign in with an account
3. ✅ Verify there aren't any new errors in logcat and the sync completes successfully.
=> Converting user sync from Rx to Coroutines

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/extensions/SpannedKtTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/105.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastResponse.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Spanned.kt
The server now returns a HTML formatted version of the podcast description. The podcast page has been updated to support the HTML.
There is one issue that I haven't been able to resolve. When using HTML in the view, the three dots to show that you can expand doesn't work. I’m not quite sure how to fix it yet so I will leave it for now. 
1. Follow the podcast Dirtbag Rich https://pca.st/zkf1jxjd
2. Open the podcast page
3. Expand the header
4. Tap on the podcast description
5. ✅ Check the description is using HTML and split into paragraphs
1. Go to Profile -> Settings -> Beta features
2. Toggle off "Use HTML in the podcast description"
3. Go back to the podcast page
4. ✅ Check the description is not using HTML
| --- | --- |
| …
=> Use HTML in the podcast description

CHANGELOG.md, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/PlusInterstitialStory.kt
We received feedback that one of the transitions of "Thanks" on the second to last page of the 2024 Playback is incorrect. In Italian, "Aspettare" means "To wait", not "Wait". The correct translation is "Aspetta".
As this is just a text change reviewing the code will be enough.
=> Fix end of year translation

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Just adds the missing event track for `Discover Podcasts` button
- Context: p1734591702871389-slack-C029BMLUGRX
1. Start the app from scratch
2. Go to Podcasts tab
3. You should screen the screen above
4. Tap on the Discover Podcasts
5. ✅ Ensure the `podcasts_list_discover_button_tapped` event is tracked
=> Add event to track Podcasts list discover button tap

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerState.kt
- This is the last part of the sleep timer refactor that started here: https://github.com/Automattic/pocket-casts-android/pull/3377
- The goal of this PR is to extract the End Of Chapter Logic out for PlaybackManager
Fixes #3384
1. Add episodes that contains chapters to Up next
2. Set end of chapter for Sleep timer
3. Switch from a chapter to another chapter
4. ✅ Ensure the end of chapter count decreases
5. Seek the scrabble, but make sure you don't switch the chapter
6. ✅ Ensure the end of chapter count does not change
7. Finish the current episode
8. ✅ Ensure the end of chapter count decreases
1. Add episodes that does not contain chapters to Up next
2. Set end of chapter for Sleep timer
3. Finish the current episode
4. ✅ Ensure the end of chapter count decreases
- Feel free to smoke …
=> [Tech Debt] Extract end of episode code out of PlaybackManager

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileManageDownloadsCard.kt, modules/services/localization/src/main/res/values/strings.xml
- This updates the manage download banner to use a X icon to dismiss the banner instead of opening a bottom sheet dialog
- See: p1735928599201419/1734454637.773259-slack-C07TL9YK9V1
Fixes #3404
1. Apply [patch.patch](https://github.com/user-attachments/files/18201084/patch.patch)
2. Download an episode
3. Open downloads screen
4. See the low storage banner
5. Tap on the X button to dismiss the banner
6. Ensure the banner is hidden ✅
7. Wait more than 10 seconds (this is the mocked by the patch instead of 14 days)
8. Go to other screen
9. Back to Downloads screen
10. Ensure you see the banner back again ✅
=> [Manage Download] Update manage download dismiss banner

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BatteryRestrictionsSettingsFragment.kt
- Add the missing events for battery restrictions
1. Have a fresh install
2. Play an episode to see the battery restrictions warning (if you see the warning, tap to open the settings) or go to settings and open the battery screen
3. ✅ Ensure the new event `battery_restrictions_shown` is tracked when see the battery restriction screen
4. Toggle the restriction
5. ✅ Ensure the event `Tracked: battery_restrictions_toggled, Properties: {"current_status":"optimized"` is tracked
=> Tracks Audit: Battery restrictions events

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This disables End of Year feature flags for debug builds. They're already disabled in the Remote Config so it's just to have the same behavior during development.
1. Go to the Profile tab.
2. PB24 shouldn't be present.
=> Disable End of Year feature flags

fastlane/Fastfile
> [!NOTE]
> This is a re-opening of https://github.com/Automattic/pocket-casts-android/pull/3371 (PR targeting wrong branch) then from https://github.com/Automattic/pocket-casts-android/pull/3382 (closed because it didn't land in time before `7.79` submission and `release/7.79` branch deletion
Introduce a `publish_release` lane to automate:
- The publication of the GitHub Release of the final build (once the version submitted to Google on Friday have been approved)
- ~~The creation of the final backmerge PR if needed~~[^1]
- The deletion of the release branch
[^1]: Note that the initial PR https://github.com/Automattic/pocket-casts-android/pull/3382 included the creation of a final backmerge PR at that stage, but after https://github.com/Automattic/pocket-casts-android/pull/3382#discussion …
=> [Tooling] Introduce publish_release lane

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
- This adds track events for all row's click in About page
1. Go to About screen
2. Verify the all row items track event
=> Tracks Audit: Add About Track event

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/paywallreviews/UpgradeLayoutReviews.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This adds more events that were not listened in out Tracks sheet related to subscriptions 
- I also added `rate_us_tapped` because I was already working near by since we can rate the app from the new paywall reviews that has a button to open the store. I am going to track this new events for others cases in another PR
1. Open the paywall
2. Ensure the `🔵 Tracked: plus_promotion_subscription_tier_changed, Properties: {"value":"plus"` is tracked
3. Swipe to patron
4. Ensure the `🔵 Tracked: plus_promotion_subscription_tier_changed, Properties: {"value":"patron"` is tracked
5. Set Monthly 
6. Ensure the `🔵 Tracked: plus_promotion_subscription_frequency_changed, Properties: {"value":"monthly"` is tracked
7. On the cards, tap on Privacy and Policy link
8. Ensure `🔵 Tracked: …
=> Tracks Audit: Add new subscriptions events

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Add events for this screen
1. Go to Settings -> Appearance
2. Tap on Advanced episode artwork settings
3. Ensure `🔵 Tracked: settings_advanced_episode_artwork_shown` is tracked
4. Disable Use Episode Artwork toggle
5. Ensure `🔵 Tracked: settings_advanced_episode_artwork_use_episode_artwork_toggled, Properties: {"enabled":false` is tracked
6. Enable it again
7. Uncheck Up Next element
8. Ensure `🔵 Tracked: settings_advanced_episode_artwork_customization_element_toggled, Properties: {"enabled":false,"element":"upnext",` is tracked
=> Tracks Audit: Add Advanced episode artwork settings events

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Track crash report toggle change event
1. Go to Settings -> Privacy
2. Toggle Crash reports
3. Ensure `🔵 Tracked: crash_reports_toggled, Properties: {"enabled":true` is tracked
=> Tracks Audit: Track Crash Report Event

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt
- This adds events for podcast screen selection
This screen can be opened from different screens, so we are going to use the same event name, but changing the source property
1. Follow some podcasts
2. Go to Settings -> Notifications
3. Enable Notify me
4. Tap on Choose podcasts
5. Ensure `🔵 Tracked: settings_select_podcasts_shown, Properties: {"source":"notifications"` is tracked
6. Tap on Select none
7. Ensure `🔵 Tracked: settings_select_podcasts_select_none_tapped, Properties: {"source":"notifications"` is tracked
8. Tap on select all
9. Ensure `🔵 Tracked: settings_select_podcasts_select_all_tapped, Properties: {"source":"notifications"` is tracked
10. Uncheck one podcast
11. Ensure `🔵 Tracked: settings_select_podcasts_podcast_toggled, Properties: …
=> Tracks Audit: Add events for podcast screen selection

gradle/libs.versions.toml
I keep experiencing the following build issue:
```
* What went wrong:
lateinit property buildMetricsPreparedAction has not been initialized
* Try:
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
* Exception is:
kotlin.UninitializedPropertyAccessException: lateinit property buildMetricsPreparedAction has not been initialized
at com.automattic.android.measure.reporters.InMemoryMetricsReporter.getBuildMetricsPreparedAction(InMemoryMetricsReporter.kt:9)
at com.automattic.android.measure.reporters.InMemoryMetricsReporter.report(InMemoryMetricsReporter.kt:21)
at com.automattic.android.measure.lifecycle.BuildFinishedFlowAction.execute(BuildFinishedFlowAction.kt:69)
at com.automattic.android.measure.lifecycle.BuildFinishedFlowAction.execute(B …
```
=> Upgrade Automattic measure builds library

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
- This adds some missing events for Bookmark
1. Log with plus / patron account
2. Go to a podcast, follow and play an episode
3. Open shelf and tap on Bookmark
4. Ensure `🔵 Tracked: bookmark_edit_form_shown` 
5. Dismiss this form
6. Ensure `🔵 Tracked: bookmark_edit_form_dismissed,` 
7. Back to the screen and tap to save the bookmark
8. Ensure `🔵 Tracked: bookmark_edit_form_submitted`
9. In Now Playing screen, switch to bookmark tab
10. Long press the bookmark
11. Tap to share
12. Ensure `🔵 Tracked: bookmark_share_tapped` 
13. Close the screen
14. Tap to dele the bookmark
15. Ensure `🔵 Tracked: bookmark_delete_form_shown`
16. Delete
17. Ensure `🔵 Tracked: bookmark_delete_form_submitted`
1. Have some bookmarks
2. Go to Profile -> Bookmarks
3. Search something like "sdfsdf" to see the `no …
=> Tracks Audit: Add missing bookmark events

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/ViewExtensions.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/clip/ShareClipFragment.kt, modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/clip/ShareClipPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ArtworkConfiguration.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SystemBatteryRestrictions.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BatteryRestrictionsSettingsFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt
- This PR adds some minor changes. 
- Creates `analyticsValue` for enum to avoid using `enum.name.lowercase()`
- Tracks `share_screen_navigation_button_tapped`, `share_screen_edit_button_tapped` and `share_screen_close_button_tapped` for sharing clip
- Tracks `podcast_screen_podcast_description_tapped` for when expands podcast description
1. Open a podcast that has long description
2. Tap on podcast's description to expand
3. Ensure `🔵 Tracked: podcast_screen_podcast_description_tapped`
[Screen_recording_20250110_083044.webm](https://github.com/user-attachments/assets/a8c12701-03e9-467d-b272-f0e98036b17a)
2. Tap to share episode -> Clip
4. Tap on Next button
5. Ensure `🔵 Tracked: share_screen_navigation_button_tapped`
6. Tap on Edit Clip
7. Ensure `🔵 Tracked: …
=> Tracks Audit: Tweaks for tracking

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This tracks the discover share button tap
1. Run the app in `debugProd`
3. Tap on Show All button from [New In History]
4. Tap on toolbar share button
5. Ensure `🔵 Tracked: discover_list_share_tapped_tapped`
=> Tracks Audit: Track Discover Share

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/PodcastOptionsFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Adds more events for filters feature
1. Open Filters 
2. Tap on + button to create a filter
3. Ensure `🔵 Tracked: filter_create_button_tapped`
4. Tap on All Your Podcasts chip
5. Toggle All your podcasts
6. Ensure `🔵 Tracked: settings_select_podcasts_select_all_podcasts_toggled, Properties: {"source":"filters","enabled":false`
=> Tracks Audit: Add more eventos for Filters

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/OfferClaimedPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/services/images/src/main/res/drawable/ic_sparkle_1.xml, modules/services/images/src/main/res/drawable/ic_sparkle_2.xml, modules/services/images/src/main/res/drawable/ic_sparkle_3.xml, modules/services/localization/src/main/res/values/strings.xml
This PR adds claimed winback offer confirmation UI.
I implemented the sparkle icon as a composite one. I think it is better to do it this way so we don't have to keep multiple different XML resources.
Designs: G22KfZwL1Gv5yyxdTheF9H-fi-1_738
Theming: p1734627943400829-slack-C080ZKX4UCV
1. Sign in with an account that has a monthly or a yearly subscription.
2. Go to account details.
3. Tap on "Cancel subscription".
4. Tap on "Claim offer".
5. Verify the UI and navigation. Using back button should close the whole winback flow.
6. Test this with different themes.
=> Add claimed winback offer UI

modules/features/podcasts/src/main/res/layout/fragment_profile_episode_list.xml, modules/services/ui/src/main/res/values/themes.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt
After moving to Android 15 the multi-select toolbar appeared under the status bar, this change fixes that.
1. Go to the Podcasts tab
2. Open a podcast page
3. Long press on an episode row
4. ✅ Verify the multi-select toolbar doesn't appear under the status bar
Testing one of the pages that uses the multi-select toolbar should be enough but here are some more just in case.
5. Open the full screen player
6. Tap the Up Next icon
7. Tap the multi-select icon in the toolbar
8. ✅ Verify the multi-select toolbar doesn't appear under the status bar
9. Go to the Profile tab
10. Tap Files
11. Long press a file 
12. ✅ Verify the multi-select toolbar doesn't appear under the status bar
| --- | --- |
| ![multiselect-player-up-next-before](https://github.com/user-attachments/assets/59 …
=> Fix multi-select with edge-to-edge

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/BillingClientWrapper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
The previous implementation of interactions with the Billing API was challenging to work with due to several design issues:
- **Lack of Structured Concurrency**: Operations were spread across a mix of callback-based and suspending methods, making the code harder to reason about.
- **Connection Management**: There was no guarantee that the billing client was connected before performing operations, leading to potential failures.
This PR introduces a significant redesign of the billing client operations to address these issues and improve the reliability and maintainability of the code.
1. Structured Concurrency
* The global application scope is no longer injected. Instead, consumers are responsible for managing concurrency by using suspending functions or launching operations within an …
=> Improve Billing API communication

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
- This is an attempt to fix the reported chromecast issues: 
> Pocket Cast pauses less than a second into playing a podcast through Chromecast. Hit play, and it starts for a half second again and immediately pauses
- In my investigations, I noticed that we are receiving the stop command from MediaSession when casting an episode, and this is causing the episode to stop. We are overriding the `stop` method in `MediaSessionManager.kt`, which stops the episode when this command is received. However, upon reviewing the code, I noticed that this overridden `stop` method is being called only when attempting to cast an episode. It is not being triggered for the `App`, `Wear`, or `Automotive` platforms, as suggested by the comments in the stop method. All platforms call the `pause` method instead …
=> Fix: Casting not working correctly to Google Devices

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfilePage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassError.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsInvalidOfferPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/services/ui/src/main/res/values/themes.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt
This change fixes a few issues:
- The Profile tab and account page have a fixed status bar and toolbar. The page content scrolls under these with a solid background color. 
- When logged in to a Plus Pocket Casts account if your last tab was the Profile tab when you reopen the app you can't scroll to see the refresh button. This was fixed by changing from a `Column` with a verticalScroll modifier to a `LazyColumn`.
1. Login to a Pocket Casts account.
2. Open the Profile tab.
3. Scroll down the page.
4. ✅ Verify the page toolbar and status bar aren't opaque.
5. Tap on the account button.
6. Scroll down the page.
7. ✅ Verify the page toolbar and status bar aren't opaque.
8. Reopen the app
9. ✅ Verify you can scroll down the Profile page to see the refresh button …
=> Fix Profile tab edge-to-edge

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfilePage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt, modules/features/profile/src/main/res/layout/activity_add_file.xml, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassError.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsInvalidOfferPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt, modules/services/ui/src/main/res/values/themes.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt, modules/services/views/src/main/res/layout/layout_plus_callout.xml
Upgrading to Android 15 edge-to-edge caused the adding of a user file toolbar to be under the status bar, this change fixes that and cleans up the page.
1. Go to the Profile tab
2. Tap Files
3. Tap the Plus + FAB 
4. Pick a media file
5. ✅ Verify the Add File page looks correct and no page content if hidden under the status or navigation bar.
=> Fix add user file edge-to-edge

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistUpdateAnalytics.kt
- This includes the `duration_longer_than` and `duration_shorter_than` when the user creates a filter and set a duration
- This is to improve the existing event `filter_created`
Fixes # 
1. Log with a plus account
2. Create a filter
3. Set a duration
4. ✅ Ensure you see the new properties
=> Add duration size property for Filter event

fastlane/Fastfile
_Note: [iOS companion PR here](https://github.com/Automattic/pocket-casts-ios/pull/2633)_
[Internal Refs]
- Slack Thread about the hotfix process feedback: p1733831549430849/1733504114.702699-slack-C028JAG44VD
- Related MC scenario PR: 170061-ghe-Automattic/wpcom
Addressing some feedback reported by devs / release managers on the process during the last time they did a hotfix
- Ensure the hotfix branch is pushed to upstream after it has been created
- Ensure we close the GitHub hotfix milestone at the end of the hotfix
This won't really be testable until next time we do a hotfix, unfortunately, as testing those lanes would otherwise create side effects.
=> [Tooling] Fix hiccups in hotfix process

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
- This updates the upgrade banner dismiss event to align with iOS and track in other missing areas. See: p1737040220122109/1736977627.026869-slack-C088L7YF8BY
- Track the save / edit button when uploading a file. See: p1737037979177609/1737034289.387959-slack-C088L7YF8BY
1. Log in with free account / No account to see the upgrade banner
2. Go to Profile and scroll down to see the upgrade banner
3. Dismiss this banner
4. Ensure `upgrade_banner_dismissed` event is tracked
5. Go to Appearance and dismiss the banner
6. Ensure `upgrade_banner_dismissed` event is tracked
7. Go to Files and try to upload a file
8. Dismiss the banner
9. Ensure `upgrade_banner_dismissed` event is tracked
10. Go to Files -> Files Settings
11. Dismiss the banner
12. Ensure `upgrade_banner_dismissed` event is tracked …
=> Track Event Tweaks part 3

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/profile/build.gradle.kts, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackOfferPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralOfferInfoProviderTest.kt, modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/MainCoroutineRule.kt
This PR adds Winback VM with logic for fetching available plans and matching user's subscription with them. It makes a lot of assumptions about the subscriptions:
* Only a single acknowledged purchase is allowed.
* Purchase must have an order ID.
* Purchase cannot have multiple products.
This matches iOS behavior and is done this way because there's no UI to handle different cases. Also, in practice, it should be the only viable option as Google Play prevents users from having multiple subscriptions and we don't have single-purchase products.
There's nothing to test here manually.
=> Add Winback view model

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/services/localization/src/main/res/values/strings.xml
- Updates the upgrade text for trial offer
- See: p1736962037937059/1736902416.257099-slack-C06EHRAPW12
1. We need to have our account added to the [license-tester](https://play.google.com/console/u/0/developers/7957760354032996428/license-tester)
2. Log in with this account in Play Store
3. Run the app in `release` mode
4. @Automattic/pocket-casts-android I am not able to see the offer, so it's hard for me to test. I know the trial offer is available only for Brazil, India and South Africa. I will take a look at this tomorrow
=> Update Paywall CTA Upgrade Button

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/MenuShelfItems.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfRearrangeActionsPage.kt
The end of the "Rearrange Actions" page list wasn't visible while scrolling under the navigation bar. Instead, the navigation bar was a solid colour. This change fixes this and some other minor issues such as the previous dialog flashing when opening.
1. Open the full screen player
2. Tap the three dots in the action shelf
3. ✅ Verify the background of the dialog doesn't flash
4. Tap the edit pencil 
5. Scroll to the bottom of the list
6. ✅ Verify the list goes under the navigation bar and that the last actions don't stop under the navigation bar
Before
After
=> Fix player actions pages

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeActionTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/ui/src/main/res/values/ids.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectAdapter.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeAction.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectFragment.kt
- This PR just adds the remove listening history individual / group of episodes action. I need to understand how sync will work with this, that's why I am going to handle in another PR.
- The proposed design was discussed here: https://github.com/Automattic/pocket-casts-android/issues/2814#issuecomment-2587233165
| More Options | Rearrange Actions |
| ![Screenshot_20250115_120453](https://github.com/user-attachments/assets/46d114ef-13f4-4d37-bb34-d29c268d8249) | ![Screenshot_20250115_120501](https://github.com/user-attachments/assets/29cc0691-dfd2-41c1-8a63-b961faf814b8)| 
1. Play some episodes
2. Open Profile -> Listening History
3. Long press an episode to open the menu toolbar
4. Tap on 3 dots to show the bottom sheet options
5. **See** the `Remove from listening …
=> Remove multiple listening history UI

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeActionTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/ui/src/main/res/values/ids.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectAdapter.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeAction.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectFragment.kt
- This PR just adds the feature to the `main`. The feature was already reviewed in https://github.com/Automattic/pocket-casts-android/pull/3443 and https://github.com/Automattic/pocket-casts-android/pull/3452
Fixes #2814
[Screen_recording_20250117_102646.webm](https://github.com/user-attachments/assets/89156160-7c8f-4a9d-bee9-8006ad2d3bda)
=> Add Listening History Individual / Multiple Removal feature to `main` branch

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ThemeSetting.kt
- See the request: p1737091811075529-slack-C088L7YF8BY
- Play around the app and make sure the new properties were added to the events track
=> Add Theme info to default track events properties

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
- This is to align the same behavior that iOS fixed: https://github.com/Automattic/pocket-casts-ios/pull/2661/files
[Screen_recording_20250121_120555.webm](https://github.com/user-attachments/assets/0fca08a2-1db6-424f-9dff-39d15439794b)
1. Start the app
2. Open the Profile tab
3. Tap on Files and ensure you upload at least one file
4. Tap on one of the files
5. Tap on bookmark
6. Select one of the bookmarks
7. Ensure you don't see the share option ✅
8. Play an public episode
9. Bookmark something
10. and try to share the bookmark
11. Ensure you see the share option ✅
=> Remove the option to share bookmarks for user files

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/AvailablePlansPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This PR adds logic for changing a subscription plan during the Winback flow. I had to clean up how we calculate the replacement mode to fit it into the flow. During my testing I discovered that using `DEFERRED` replacement mode is not suitable for us. Our backend treats such a subscription as a cancelled one. Also we can't effectively query it from the Billing API because it is not recurring yet.
> [!note]
> Test this with the `release` variant of the app.
1. Have a device using a Google Play tester account with no Pocket Casts subscriptions.
2. Sign in into the app with an account without a subscription.
3. Purchase any subscription through Google Play.
4. Go to the Account Details page.
5. Tap on the `Cancel subscription` button.
6. Tap on `Looking for a different plan?` option.
7. Try …
=> Add subscription plan change logic

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt
- See: p1737473309658669-slack-C088L7YF8BY
1. Go Profile -> Settings -> Auto Download
2. Toggle `New Episodes` ON
3. Tap on Choose podcasts
4. Back to the previous screen
5. Ensure `🔵 Tracked: settings_select_podcasts_dismissed, Properties: {"source":"downloads",`
=> Track Podcast Selection Screen Dismiss event

CHANGELOG.md, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notification/MediaActionsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notification/MediaActionsPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notification/MediaActionsViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
As part of fixing the Samsung Galaxy Watch skip buttons the Pixel Watch skip buttons no longer work. There is an issue with the watch media controller app, it doesn't support custom actions. Unfortunately, there isn't a good fix for both Samsung and Google watches. 
This change adds a new setting under General -> Customise media actions -> Pixel Watch skip buttons. It explains that to support skip we need to use the next/previous track buttons.
1. Play an episode on your phone
2. On your Pixel watch home screen tap the media controller icon at the bottom of the page
3. ✅ Verify that the skip buttons don't work
4. On your phone pause the episode
5. Go to settings -> General -> Customise media actions
6. Turn on "Pixel Watch skip buttons"
7. Tap play
8. ✅ Verify the skip buttons on the …
=> Add Pixel Watch skip buttons setting

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This just fixes a typo
- See: p1737653224212379-slack-C088L7YF8BY
=> [Tracks Audit] Fix track typo

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountSections.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt
This PR adds logic for handling subscription cancellation.
> [!note]
> Enable `WINBACK` flag in the code and test this with the `release` variant.
1. Sign in with this account: p1737624995796789-slack-C028JAG44VD
2. Go to Account Details.
3. Tap on `Cancel subscription`.
4. Tap on `Yes, Cancel my Subscription`.
5. You should see FAQ about how to cancel a subscription.
1. Sign in with an account that has a Google subscription.
2. Go to Account Details.
3. Tap on `Cancel subscription`.
4. Tap on `Yes, Cancel my Subscription`.
5. You should see your subscription in the Play Store.
=> Handle subscription cancellation

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
This PR adds Tracks events to the Winback flow.
1. Apply [this patch](https://github.com/user-attachments/files/18521218/winback.patch) to be able to enter Winback flow and see the logs.
2. Build and install the `debugProd` variant.
3. Verify the Tracks events.
I recommend applying this filter to the Logcat output: `package:mine tag:Tracks message:winback`
=> Add Winback analytics

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
- We should keep the screen opened instead of archiving an episode
Fixes #3442
2. Tap on Episode to open the episode detail
3. Tap on Archive button
4. The episode detail screen should not be closed ✅
5. The Archive button text should be updated to `Unarchive` ✅
[Screen_recording_20250122_092743.webm](https://github.com/user-attachments/assets/4c4a229e-f662-4643-899e-ab7a1f82b8d8)
=> Fix: Do not close episode details when archiving an episode

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectAdapter.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt
- This removes the button instead of hide to avoid this issue https://github.com/Automattic/pocket-casts-android/pull/3453#issuecomment-2605485990
- Smoke test the remove individual listening history
- ✅ Ensure this button displays only for when the user played the episode
- ✅ Ensure this button is not available for when the user favorited / downloaded an episode without playing it
=> Update Remove Listening History Button

CHANGELOG.md, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values-ar/strings.xml, modules/services/localization/src/main/res/values-ca/strings.xml, modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-en-rGB/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nb/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, modules/services/localization/src/main/res/values/strings.xml
Internal reference: pbMoDN-4vZ-p2#comment-7289 
This change renames Twitter to X and updates the URL.
1. Go to the about page
2. ✅ Verify the label has changed to X and tapping opens our x.com page.
| --- | --- |
| ![Screenshot_20250126_092251](https://github.com/user-attachments/assets/e3302c13-ab0d-43ed-b113-58b7c45da1d5) | ![Screenshot_20250126_092853](https://github.com/user-attachments/assets/64ef9407-3b85-407e-aa03-aa64a7fb6b31) |
=> Rename Twitter to X

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This is to align the same free up space events with iOS
- I am deleting the unused `free_up_space_manage_downloads_more_options_tapped` event
- I use `free_up_space_maybe_later_tapped` event to hide the banner in Downloads screen instead of `free_up_space_manage_downloads_more_options_tapped` to align with iOS
- See context: 
Code review should be fine, but if you want to track the event you can:
1. Modify the code to return true https://github.com/Automattic/pocket-casts-android/blob/ab6bb0c3f9cec6e52c7f74b8ee3c321a28ab758c/modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/DeviceStorageUtil.kt#L10
2. Build the App
3. Download an episode
4. Go to Downloads screen
5. See the free up space banner
6. Dismiss the banner
7. Ensure `free_up_space_maybe_later_tapped` is …
=> Rename Free Up Space Event

fastlane/Fastfile
During his last run of the release scenario, @geekygecko noticed that, by the time the release manager is supposed to run `update_rollouts percent:1` to roll out the production build to 100% after it has been approved by Google, that command updates the rollout of the wrong build / track. [Internal ref: p1737528474331869-slack-CC7L49W13]
The reason this happens is because, so far, `update_rollouts` was always using the version stored in the `version.properties` file of the current branch to figure out which version name and code to update the rollout of.
But, by the time one wants to update the rollout of version `x.y` in production track to 100%, the `release/x.y` branch for that version has already been deleted (by the release manager running the `publish_release` lane earlier in the …
=> [Tooling] Allow `update_rollouts` to specify the track to update

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/podcasts/src/main/res/layout/fragment_podcast.xml
- This PR adds the refresh layout to implement the pull down action
- I will update the tracks in another PR
Fixes #3485
2. Pull Down to refresh podcast
3. After 2 seconds you should see the snackbar with ok result
[Screen_recording_20250124_111942.webm](https://github.com/user-attachments/assets/6cd3a3d4-d439-446f-af48-a6ccf385f168)
=> [Podcast Feed Update] Add Refresh Layout to Pull Down and Refresh Podcast List

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaEventQueue.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaEventQueueTest.kt
This PR changes processing of media session events to use coroutines. I did this in order to have comprehensive tests for handling it and fix the reported bug introduced by #3297. This was happening because `KEYCODE_MEDIA_NEXT` is followed by `KEYCODE_MEDIA_PLAY` event when using Pixel Buds. I don't know if other brands experience it.
Fixes #3487
1. Listen to an episode with Pixel Buds Pro 2.
2. Double tap a bud to advance by 30 seconds, or triple tap to rewind 10 seconds.
3. Playback should not pause.
=> Fix media session controls

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt, modules/features/podcasts/src/main/res/layout/fragment_episode.xml, modules/features/podcasts/src/main/res/layout/fragment_episode_container.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/MatchParentFrameLayout.kt
This fixes the episode's bottom sheet. The status bar icons were the wrong colour, and the bottom padding was causing issues with the bottom of the page. 
1. Tap on an episode row.
2. ✅ Check you can scroll to the bottom of the page and see all the show notes.
**Before**
**After**
The navigation bar icons aren't correct for API 24 but that is happening throughout the whole app.
=> Fix episode bottom sheet edge-to-edge

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/AvailablePlansPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/CancelConfirmationPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/BottomSheetAppBar.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/ThemedTopAppBar.kt
Some minor tweaks for edge-to-edge support.
| | | | |
| ![Screenshot_20250128-140751](https://github.com/user-attachments/assets/b56ea274-8223-49d6-8dd8-beaeaa3f20a1) | ![Screenshot_20250128-140756](https://github.com/user-attachments/assets/45299904-a82b-46a9-9dbc-a196c1361327) | ![Screenshot_20250128-140802](https://github.com/user-attachments/assets/2381e582-ed4d-4777-90e0-ad5620815f21) | ![Screenshot_20250128-140808](https://github.com/user-attachments/assets/c02ccaec-de6b-404e-b87d-b82fa5fde7a7) |
| | | | |
| ![1](https://github.com/user-attachments/assets/77ba89ec-3ffb-4dcd-9d2e-6f7fcd457c3b) | ![2](https://github.com/user-attachments/assets/e2309bc2-3927-47c3-8e2f-4d6d1140680a) | …
=> Adapt Winback for edge-to-edge

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/localization/src/main/res/values/strings.xml
- This updates the message when founds a new episode
- See: pdeCcb-8oU-p2
2. Pull down to refresh
3. See the `New Episode Found!` snackbar message after 2 seconds
4. Open more options (tap on 3 dots icon)
5. Tap on Refresh episode list
6. See the `New Episode Found!` snackbar message after 2 seconds
[Screen_recording_20250128_085824.webm](https://github.com/user-attachments/assets/816df067-622b-4ec2-b283-2be193092d43)
=> [Podcast Feed Update] Update New Episode Found message

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
- Center version name in About screen
Check if the version name is aligned (center) for large fonts
| ![before](https://github.com/user-attachments/assets/676103c4-8cde-47f8-ab4a-5b178c5ed9c9) | ![after](https://github.com/user-attachments/assets/33497e7c-c958-4bd0-b715-89efaa485307) |
=> Fix App version in About screen for large fonts

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Updates the tracks
Fixes #3498 
2. Pull down to refresh
3. Ensure `Tracked: podcast_screen_refresh_episode_list, Properties: {"podcast_uuid":"uuid","action":"pull_to_refresh"`
4. Tap on 2 dots menu
5. Tap on Refresh episode list
6. Ensure `Tracked: podcast_screen_refresh_episode_list, Properties: {"podcast_uuid":"uuid","action":"refresh_button"`
=> [Podcast Feed Update] Update Tracks

modules/features/discover/src/main/res/layout/row_podcast.xml
- This fixes the discover subtitle list items for large font sizes
1. Increase device font size
2. Check the small list in discover page
| ![before](https://github.com/user-attachments/assets/a955f6a3-b59e-4d1e-8619-f23defd62e79) | ![after](https://github.com/user-attachments/assets/6e7858b4-1781-4dca-a08b-35882d6a1882) |
=> Fix Discover Subtitle List for Large Font Sizes

.buildkite/commands/save-cache.sh
Project Thread: paaHJt-7CE-p2
---
This PR uses the custom `init.gradle.kts` related file, defined within the Android AMI itself (see [buildkite-ci#585](https://github.com/Automattic/buildkite-ci/pull/585)), which now contains this custom `downloadDependencies` task.
With this change, instead of individually calling a number of `assemble/lint` related tasks to download as many dependencies as possible prior to saving the cache, any project can now utilize this globally defined `downloadDependencies` task to replace all this boilerplate and streamline the overall dependency cache process.
Notably, with this change, the dependency cache process:
1. Will no longer be broken on issues like [this](https://github.com/wordpress-mobile/WordPress-Android/pull/21627), making the process more robust. …
=> [Dependency Cache] Use Custom Init Gradle Task to Download Dependencies

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpPage.kt
This fixes missing padding in the overflow menu.
Fixes #3518
1. Go to Help & feedback page.
2. Tap on the overflow menu.
3. It should be positioned correctly.
| - | - |
| ![before](https://github.com/user-attachments/assets/27caa2f4-3c40-45d2-bc14-e61125eeaa6a) | ![after](https://github.com/user-attachments/assets/7ce2181e-3033-47d0-ad3b-c2341a39559d) |
=> Fix Help page overflow menu position

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
- This PR cancels the refreshing and also hide the snackbar if there is a refreshing in progress and the user switched to another screen
- See: p1738161669692569-slack-C088RDU8HAN
1. Run the app in `debug`
3. Open more options and tap on refresh episode list button
4. You will see the snackbar with in progress state
5. Switch to another screen
6. ✅ The snackbar should be hidden
[Screen_recording_20250130_131519.webm](https://github.com/user-attachments/assets/87ea79bc-f304-406e-bbe2-c6e5bf33a4d6)
=> [Podcast feed update] Cancel refresh if switch screen

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/activity/WebViewActivity.kt
This PR adds missing padding to the toolbar in the `WebViewActivity`.
Fixes #3517
| - | - |
| ![b](https://github.com/user-attachments/assets/e486473f-4c0d-49ad-b521-c8abcdce2484) | ![a](https://github.com/user-attachments/assets/cea66ca5-4731-428d-807f-9ff162b09426) |
=> Fix padding in WebViewActivity

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Adds two more events for when finding a new episode and when did not find a new episode
- See: p1738273764465099-slack-C088RDU8HAN
code review should be fine
=> [Podcast feed update] Add tracks for refresh result

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Theme.kt
Some more improvements for Winback's edge-to-edge experience. I can't find a good solution to #3519 that doesn't break other fragment uses so instead I'm making specific changes to the Winback fragment. The main issues were that it used the whole screen instead of acting like a bottom sheet and the parallax effect while scrolling.
| - | - |
| ![a](https://github.com/user-attachments/assets/cc2c881a-4d8f-40b3-90eb-594bd764d2ed) | ![b](https://github.com/user-attachments/assets/2e58aae6-5129-405b-ac29-a52117b18ffc) |
=> Improve Winback edge-to-edge experience

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
This change stops the About page from going under the status bar. When we have upgraded to Material 3 it would be good to change the toolbar scroll behaviour so the toolbar disappears on scroll when you go down the page but comes straight back when you scroll up, similar to how apps like Gmail do it.
Fixes https://github.com/Automattic/pocket-casts-android/issues/3516
2. Tap the settings cog 
3. Tap About
4. ✅ Verify the page content doesn't go under the status bar
| Top | Bottom |
| --- | --- |
| ![Screenshot_20250203_153519](https://github.com/user-attachments/assets/ca0ea7a8-9008-4af7-aa89-d6d1a0c6e621) | ![Screenshot_20250203_153525](https://github.com/user-attachments/assets/2b026aca-90c4-4a6b-b60f-6fb34cae52db) | 
| …
=> Fix the About page edge-to-edge status bar issue

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateViewModel.kt
There was unintended interaction between #3507 and #3513 where `startActivity` import got removed and it started failing builds. This PR fixes it by removing usage of the deprecated function.
🟢 CI is enough
=> Do not use deprecated startActivity function

fastlane/Fastfile
Context: p1738584698791939/1738269556.705039-slack-C028JAG44VD
Removes the call to `ensure_git_branch` during `code_freeze`.
This is because `ensure_git_branch`'s default implementation relies on CI env vars to determine the git branch, instead of checking the current branch using git commands. But since, during `code_freeze`, we change the branch after the CI build started, the env var exposed by Buildkite (`BUILDKITE_BRANCH=main`) to the build would not match the current branch after `code_freeze` has just created the `release/*` branch, thus making the `ensure_git_branch` action mistakenly assume the current git branch was still `$BUILDKITE_BRANCH` aka `main`.
_Note: We could have bypassed this by using `ENV['FL_GIT_BRANCH_DONT_USE_ENV_VARS'] = 'true'` (see …
=> [Tooling] Fix `code_freeze` lane when run on CI

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServiceManager.kt
This small change removes some more RxJava from the sync task.
1. Device 1: add a filter, remove another, and manually refresh.
2. Device 2: manually refresh.
3. ✅ Device 2: Verify one filter is added and one is removed.
https://github.com/user-attachments/assets/801bd8ab-96cc-4d22-b08e-e5e37d4f2b98
=> Tech debt: Migrate import filters sync from RxJava to Coroutines

fastlane/Fastfile
Noticed when looking at https://github.com/Automattic/pocket-casts-android/pull/3537 but it was too late to suggest an edit.
_I removed the rest of the PR description template because this is just a typo fix in a comment._
=> Fix a typo `s/iscalled/is called`

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/winback/WinbackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/winback/WinbackManagerImpl.kt
This PR wraps interactions with `SubscriptionManager` inside `WinbackViewModel` to use the new `WinbackManager` instead. 
`SubscriptionManager` is quite a bloated class, making it difficult to test without mocking. Having a specialized interface alleviates this problem. 
I made this change primarily because, while developing winback offer claiming, I had to add interactions with the referral manager, which made testing overly complicated. Now, I'll be able to encapsulate these 
1. Install the `release` app variant.
2. Have an account with Google Play subscription.
3. Go to the profile details.
4. Smoke test cancellation—see if available plans are shown, if you can change them, and if you can cancel your subscription.
=> Add WinbackManager

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/winback/WinbackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/winback/WinbackManagerImpl.kt
This PR adds claiming Winback offer Right now it is available only in staging due to Winback codes being available only there.
1. Apply this [winback.patch](https://github.com/user-attachments/files/18671187/winback.patch).
2. Install the `debugProd` variant of the app.
3. Sign in with an account without a subscription.
4. If it is a new account wait for 3 minutes to make it old enough in the staging environment to make it eligible for the Winback offer.
5. Subscribe to any plan.
6. Go to the account details.
7. Tap on "Cancel subscription".
8. You should see a Winback offer.
9. Tap on the Claim button.
10. Play Store sheet should appear.
11. Close the sheet without making a purchase.
12. There should no loading dialog on top of UI.
13. Claim the offer again.
14. Finish the flow.
15. You …
=> Handle claiming winback offer

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
- This hides the swipe to refresh icon behind a feature flag. We were only hiding the refresh button. 
- I am disabling this for 7.82 and we will enable it in 7.83 instead
1. Have `Podcast Feed Update` feature flag disabled
2. Go to Podcast page
3. Ensure you can't pull down to refresh
4. Open more options
5. Ensure you don't see the refresh episode list button
6. Have `Podcast Feed Update` feature flag enabled
2. Go to Podcast page
3. Ensure you can pull down to refresh
4. Open more options
5. Ensure you see the refresh episode list button
=> [Podcast Feed Update] Hide pull to refresh behind feature flag

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastRefresherImpl.kt
Internal reference p1738686765061199-slack-C02A333D8LQ
There's an issue that if: 
- You aren't following a podcast.
- It was added to the database (viewed in Discover) over 7 days ago.
- Have interacted with it, such as starred, archived, downloaded, completed, listened to, or have it in your Up Next.
It won’t delete the podcast from your database but will delete all the other episodes you haven’t interacted with. If the user goes back to the podcast page the episodes won't be added back to the podcast.
To be able to repeat this issue you need to make the following code change as it only happens to podcasts added over a week ago.
1. Apply this [patch](https://github.com/user-attachments/files/18689492/testing.patch)
2. Be signed out
3. Tap the Discover tab
4. Subscribe to one podcast (so …
=> Fix missing episodes with unfollowed podcasts

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This PR adds makes `Chapters` implement `List<Chapter>` interface and removes all now redundant methods.
Smoke test chapters interactions with podcasts that use chapters like [Upgrade](https://pca.st/upgrade) or [The Changelog](https://pca.st/changelog).
=> Make Chapters implement List

fastlane/Fastfile
During code freeze and after the creation of the new `release/*` branch, replaces the call to `set_branch_protection` with `copy_branch_protection` instead, so that it replicates the same branch protections as the ones set on the `main` branch.
In particular, this will require the same CI checks on PRs targeting the `release/*` branch than the ones set for the `main` branch
=> [Tooling] Protect the `release/*` branch with the same settings as `main`

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolders.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- This PR creates the suggested folder UI with folders mocks, so for this PR you can ignore the folder part
- I will be using the same Folder component that we use in Podcasts screen to keep the consistency 
- This feature will be behind a feature flag
- See: QmqtGNKfPivyq5BrVRPpyV-fi-41_7024
Fixes #3549
1. Ensure the suggested folder feature flag is enabled
2. Log with a Pus / Patron account
3. Go to Podcasts tab
4. Tap to create a Folder
5. See the new screen and check the layout
6. Tap on Create custom folders
7. Ensure you see the create folder screen
[Screen_recording_20250205_093219.webm](https://github.com/user-attachments/assets/e0239f5b-f2e2-4e1a-ac95-e28d86f8bcd8)
| Theme 1 | Theme 2 | Theme 3 | Theme 4 |
|--------|--------|--------|--------|
| …
=> [Suggested Folder] Create suggested folder screen UI

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/ArtworkSection.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/107.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/DbChapter.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChapterTest.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChaptersTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/EpisodeFileMetadata.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt
This PR introduces filtering out chapters that should not be in the table of contents. See [the specification](https://github.com/Podcastindex-org/podcast-namespace/blob/main/chapters/jsonChapters.md) for more details.
The implementation relies on splitting real index and UI index. Real index is stored and is always used for syncing pre-selected chapters. While UI index is computed on-the-fly after we filter out all invalid chapters, etc.
In the database migration I had to delete all cached remote chapters as we don't have information whether such chapters should be displayed or not.
Fixes #3480
1. Install the app from the `main` branch.
2. Subscribe to the [No Agenda](https://pca.st/noagenda) podcast.
3. Play the [1728 - "Hatchet Man" - No Agenda](https://pca.st/uxlj8oi0) episode.
4. See …
=> Filter out non-toc chapters

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt
This PR adds Winback offer reloading when subscription plan changes. It is needed because we do not close the flow and different plans have different offers.
1. Apply this [winback.patch](https://github.com/user-attachments/files/18671187/winback.patch).
2. Install the `debugProd` variant of the app.
3. Sign in with an account without a subscription.
4. If it is a new account wait for 3 minutes to make it old enough in the staging environment to make it eligible for the Winback offer.
5. Subscribe to any plan.
6. Go to the account details.
7. Tap on "Cancel subscription".
8. You should see a Winback offer. Remember its details.
9. Tap on the plan change row.
10. Change your subscription to any different plan. Preferably with a different billing cycle.
11. Go back to the main Winback offer …
=> Reload Winback offer after subscription plan changes

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, app/src/main/res/layout/activity_main.xml, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastTooltip.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/podcasts/src/main/res/layout/fragment_podcast.xml, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
- This adds the tooltip for podcast update feed
- While I was testing I noticed that the tooltip is not being displayed in a very specific scenario:
1. Small device
2. The user did not dismiss the tooltip yet
3. and open a podcast that does not follow
- This is happening because we are aligning the tooltip with the more options button, which is not visible. I asked David about this here: p1738863222122779/1738285496.288959-slack-C088RDU8HAN
- See: p1738782693924129/1738285496.288959-slack-C088RDU8HAN
1. Have the podcast update feed feature flag disabled
2. Open an podcast
3. You should not see the tooltip
1. Have the podcast update feed feature flag enabled
5. Open an podcast
6. If the more options button is visible, you should see the tooltip
7. Tap out of the tooltip
8. The tooltip …
=> [Podcast Update Feed] Add Tooltip

CHANGELOG.md, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
- Fix the unresponsive issue after seeing the upgrade modal bottom sheet
Fixes #3462
See the issue's video here: https://github.com/Automattic/pocket-casts-android/issues/3462
1. Log in with free account
2. Go to Profile -> Account
3. Tap on Subscribe button
4. See the upgrade modal bottom sheet
5. Tap out of the modal to close it
6. Ensure you can interact with the screen ✅
7. Open the modal again
8. Press device back button
9. Ensure you can interact with the screen ✅
Smoke test the paywalls, open the paywalls from different sources and ensure they continue working as expected ✅
[Screen_recording_20250210_143727.webm](https://github.com/user-attachments/assets/099d396a-7a70-4470-a0d7-63aee64f3c73)
=> Fix: Page becomes unresponsive after seeing an offer

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfRowItem.kt
Fixes #3540
1. Install the app from `main`.
2. Play something.
3. Change your shelf items order.
4. Install the app from `task/default-share` branch.
5. Go to the player. Notice that the order of shelf items has not changed.
6. Clear app data.
7. Start the app.
8. Play something.
9. Notice that sharing is the 4th item in the shelf.
=> Make sharing default 4th shelf action

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
- This PR displays the modal for free and logged-out users when opening the podcasts screen. Since we are not fetching the suggested folders from server yet, I am mocking 2 seconds of fetching and then display the modal.
- I am ignoring if the user follows any podcasts for now, so they can see the modal even if does not follow a podcast. I will update this later
- See: pdeCcb-8AH-p2
Fixes #3572
1. Have the feature flag ON
2. Go to Podcasts tab
3. Wait for 2 seconds (mock)
4. Ensure you **see** the Suggested Folder Paywall modal ✅
5. Tap on Maybe Later Button
6. Go to another screen
7. Back to Podcasts tab again
8. Ensure you **don't see** the Suggested Folder Paywall modal anymore ✅
9. Tap to create a folder in folder toolbar icon
10. Ensure you **see** the Suggested Folder Paywall modal …
=>  [Suggested Folders] Update flow for free users

fastlane/Fastfile
This is especially so that `use-bot-for-git` can push version bumps and translation updates to the `release/*` branch directly during beta and final builds—so that when a new beta build is triggered from our ReleasesV2 tool it will be able to do everything needed from CI directly.
See internal ref p1739269381050279-slack-C029BMLUGRX for context
I've tested this by:
- Commenting all the lines in the `code_freeze` lane except the ones calling `copy_branch_protection` and `set_branch_protection`
- Modified the branch protection settings for the current `release/*` branch in GitHub Settings, to remove a couple of required CI checks and enable back "Do not allow bypassing the above settings"
- Then running that stripped-out `bundle exec fastlane code_freeze` lane so that those …
=> [Tooling] Allow admins to push on release branch

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt
Episode Artwork settings app bar was scrollable making it inaccessible when scrolled up and hidden behind notification status bar.
Fixes #3567
1. Increase font size so that Episode Artwork screen doesn't fit in a single screen.
2. Go to the settings.
3. Go to the Appearance page.
4. Go to the Advanced episode artwork.
5. Scroll content.
6. Notice that the the app bar does not scroll with the content.
=> Do not scroll episode artwork settings app bar

.buildkite/shared-pipeline-vars
This change fixes incorrect duration of buildkite groups by updating `a8c-ci-toolkit` to [3.10.1](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/releases/tag/3.10.1).
For more info see: [Do not echo three dashes at the end of restore cache script #146](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/146)
---
- Verify that all the CI checks are successful.
- Verify that the duration of Buildkite groups is now correct.
---
=> [CI] Fix Incorrect Duration of Buildkite Groups

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
- This was reported here: p1739368346370609-slack-C02A333D8LQ
- Sleep timer end of episode was not marking the episode as played when it has skip last set. This was causing an issue that the episode was not finishing as the number of episode expected
1. Open a podcast and set a skip last time for it
2. Add some episodes to Up next from this podcast you set skip last
3. Play the first up next episode
4. Set sleep timer end of episode
5. Ensure the episode finishes according to the skip last set ✅
6. Ensure the sleep timer end of episode updates the remaining end of episode counter ✅
=> Fix Sleep Timer end of episode when skip last is set

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderCreateFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolders.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywall.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Adds tracks to suggested folders feature
Verify events
1. Log with free account
2. Open Podcasts tap 
3. See the suggested folder paywall and check the paywall events
1. Log with paid account
2. Open Podcasts tap 
3. Tap to create a folder
4. Check the suggested folders modal events
=> [Suggested Folders] Add Tracks

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
- See: p1739448836612389-slack-C07J5LNP4SF
1. Go to Podcasts tab
2. Ensure you don't see any crash
=> Fix Suggested Folders Crash

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastTooltip.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
- See: p1739457691184399/1738908720.486589-slack-C088RDU8HAN
- This also addresses this minor request to update the font size: https://github.com/Automattic/pocket-casts-android/pull/3561/files/84b8428794c0395982232b44ebd17e924b606bd9#r1951700152
3. Ensure you don't see the tooltip ✅
4. Remove the app and install from `release/7.82` branch
5. Log in with an account
6. Close the app
7. Install from `update/tooltip-rule` branch
8. Open a podcast
9. Ensure you see the tooltip ✅
=> [Podcast Update Feed] Do not show tooltip for new installations 

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Add Remote feature flag
Fixes #3544
=> [Podcast Update Feed] Add Remote feature flag

.buildkite/commands/checkout-release-branch.sh, .buildkite/commands/release-build.sh, .buildkite/release-pipelines/finalize-hotfix-release.yml, .buildkite/release-pipelines/finalize-release.yml, .buildkite/release-pipelines/new-beta-release.yml, .buildkite/release-pipelines/new-hotfix-release.yml
During release process we need the lanes invoked from the `release-pipelines/*.yml` and that will require to do a `git push` to the release branch to actually `git fetch` + `git checkout` those release branches explicitly, otherwise the `git push` will fail (e.g. unknown `refspec`)
- We still need to checkout the `release/*` branch before the compilation in `release-build.sh`, because we want to ensure that we include the latest commit that was just pushed by the `new_beta_release` / `finalize_release` lanes from previous job, instead of building the commit that the CI build was initially created on
- But we **also** need to checkout the `release/*` in `release-pipelines/*.yml` before calling any of the lanes that would do a version bump and push the commit, otherwise it won't try to do …
=> [Tooling] Fix `finalize_release` and the `release/*` branch checkout

wear/build.gradle.kts
We get the following error when we try to upload the Wear OS app. So we need to reduce the target SDK to 34 (Android 14).
```
[2025-02-17T08:45:26Z] [08:45:26]: Preparing aab at path '.../pocket-casts-android/artifacts/wear-7.83-rc-1.aab' for upload...
[2025-02-17T08:45:50Z] [08:45:50]: Google Api Error: Invalid request - SDK version used by APK is too high. - Retrying...
```
1. Build the Wear OS APK `./gradlew wear:assembleDebug`
```
adb uninstall au.com.shiftyjelly.pocketcasts.debug
adb install wear/build/outputs/apk/debug/wear-debug.apk
adb shell am start -n au.com.shiftyjelly.pocketcasts.debug/au.com.shiftyjelly.pocketcasts.wear.MainActivity
```
3. Sign into a Pocket Casts account
4. Try out some features such as playing an episode
=> Change the Wear target SDK to 34

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt, modules/services/localization/src/main/res/values/strings.xml
- This updates the free user flow to open the upgrade screen when a free user tries to use this paid feature instead of opening the upgrade bottom sheet.
- See: p1739510234779639/1739475147.971979-slack-C08BRS7N9UL
1. Apply [suggested-folders.patch](https://github.com/user-attachments/files/18803575/suggested-folders.patch)
2. Run in `debugProd`
3. You don't need to follow any podcast since we are mocking here, so go to Podcast tab
4. See the suggested folders bottom sheet
5. Tap on `Use these folders`
6. See the upgrade bottom sheet
7. Subscribe to any plan
8. You will see the suggested folders bottom sheet
9. Tap on `Use these folders`
10. You should see the Suggested Folders screen ✅
[Screen_recording_20250214_154552.webm](https://github.com/user-attachments/assets/f56d24aa-8ddc-4c78-a6 …
=> [Suggested Folders] Open upgrade screen instead of bottom sheet modal

CHANGELOG.md
The Android 15 upgrade wasn't in the changelog, so this includes an entry.
You don't need to do any testing.
=> Add Android 15 upgrade to the changelog

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
As part of adding the tooltip to explain the podcast feed update feature, the podcast page header is always expanded. This would be annoying if you want to play the latest episode as you have to scroll down the page. This reverts the change so the header is collapsed if you are subscribed to the podcast. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/3612
1. Open the podcast page for a podcast you aren't following.
2. ✅ Verify the podcast header is expanded.
3. Open the podcast page for a podcast you are following.
4. ✅ Verify the podcast header is collapsed.
Check the tooltip position
1. In the class `modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt` change the `shouldShowPodcastTooltip` to the following, so …
=> Revert podcast header to collapsed when subscribed

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/Folder.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersMapper.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywall.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
- Populates the suggested folders paywall with data fetched
- Applies random color for folders
> [!IMPORTANT]  
> There is an issue with the current podcast follow list. If you follow or unfollow a podcast, it will not be automatically updated in the Podcast tab for suggested folders. To get the updated list of followed podcasts sent to the suggested folders API, you will need to navigate away from the Podcast tab, go to another screen, and then return to the Podcast tab. This was already addressed in https://github.com/Automattic/pocket-casts-android/pull/3606
> [!NOTE]  
> I am going to check with the server team if it's possible to get empty list in success response because currently I ignore if I get empty response since I am getting 400 error code, but this is leading a weird …
=> [Suggested Folders] Populate paywall with suggested folders

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/SuggestedFoldersDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SuggestedFoldersManager.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SuggestedFoldersManagerTest.kt
- This opens the suggested folders screen when tapping on create folder button only if has pre cached for paid users
- Opens the suggested folders paywall for free users only if has pre cached them
- Run the app in `debug`
2. Do not follow any podcast
3. Go to Podcasts tab and ensure you don't follow any podcast
4. Ensure you don't see the suggested folders paywall ✅
5. Try to create a folder
6. Ensure you see the regular upgrade account screen ✅
7. Follow some podcasts
8. Go to podcasts tab again
9. Wait a few seconds
10. Ensure you see the suggested folders paywall ✅
11. Try to create a folder
12. Ensure you see the suggested folders paywall ✅
2. Do not follow any podcast
3. Go to Podcasts tab and ensure you don't follow any podcast
4. Try to create a …
=> [Suggested Folders] Open suggested folders only if has pre cached them

.buildkite/commands/checkout-release-branch.sh, .buildkite/commands/release-build.sh, .buildkite/release-pipelines/finalize-hotfix-release.yml, .buildkite/release-pipelines/finalize-release.yml, .buildkite/release-pipelines/new-beta-release.yml, .buildkite/release-pipelines/new-hotfix-release.yml, .buildkite/release-pipelines/publish-release.yml
For all `release-pipelines/*.yml` that are triggered from the `release/` branch by ReleasesV2, we need to `checkout-release-branch.sh` to ensure they are not run on a detached HEAD and will thus be able to create commits and push on the remote branch
This includes most of all `release-pipelines/*.yml`, except for:
- `code-freeze.yml` and `new-hotfix-release.yml` — which by definition will run from the default branch in order to _create_ the `release/` branch to begin with
- `update-rollouts.yml`, which runs from the default branch so that it can also be run after Production build has started rollout and `publish-release.yml` was run and has already deleted the `release/` branch.
> [!NOTE]
> See also:
> - [PCiOS counterpart PR](https://github.com/Automattic/pocket-casts-ios/pull/2761)
> - …
=> [Tooling] Ensure to checkout `release/` branch on CI release-pipelines

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
- This moves the autoplay setting out of sleep timer group
- See: p1739548975417339-slack-C028JAG44VD
- Open general settings and check if autoplay setting is not within sleep timer group setting
| ![before](https://github.com/user-attachments/assets/61f44945-25d3-41d2-8a09-1a745fce0fca) | ![Screenshot_20250219_092245](https://github.com/user-attachments/assets/caaa845e-3c1a-4f6f-998c-bea13384820b) |
=> Improve Autoplay setting position

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
- This is to remove the extra padding for bookmarks multiselecting
1. Log in with paid account
2. Play an episode that you have bookmarks
3. Go to Bookmarks tab
4. Long press the bookmark row
5. Ensure the toolbar does not have extra space ✅
[Screen_recording_20250219_154221.webm](https://github.com/user-attachments/assets/85e56434-4b15-4783-a25a-a957ca88daa3)
=> Fix bookmarks selection toolbar

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/res/layout/fragment_podcast.xml, modules/features/podcasts/src/main/res/layout/fragment_podcast_redesign.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This PR introduces the **Podcast View Changes** feature flag and integrates its handling in `PodcastFragment`. To ensure a smooth transition without unexpected issues, I abstracted some logic and introduced a wrapper for XML bindings. This wrapper enables better management of pre- and post-design changes, primarily handling custom toolbar logic.
I considered alternative approaches but found significant drawbacks:
- Handling the feature flag with `if/else` statements is highly error-prone, especially for UI updates (e.g., color changes). Additionally, configuration changes could become tricky since a feature flag's value might change dynamically, leading to inconsistencies.
- Using a separate fragment risks desynchronization between versions.
2. Verify that the old UI …
=> Add Podcast View Changes feature flag

modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModelTest.kt
- This ignores the test to not keep the `main` branch broken 
- Make sure CI is 🟢
=> Ignore flaky test

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/FolderDaoTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/FolderDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SuggestedFoldersManager.kt
- This will clean the existing folders when accepting the suggested ones
- See for context: p1739971321715109-slack-C08BRS7N9UL
1. Run the app in `debug`
2. Have an account with some folders
3. Tap to create a new folder
4. See the suggested folders screen
5. Tap on `Use these folders`
6. Ensure the new folders were created and the existing ones were removed ✅
https://github.com/user-attachments/assets/c48be6b9-8634-4c11-8a0c-4b78f6d5335f
[Screen_recording_20250220_094630.webm](https://github.com/user-attachments/assets/1c3925f9-5676-4a6a-9674-6c10ceab5131)
=> [Suggested Folders] Remove existing folders when accepting suggested folders

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
- This PR  fixes some missing paddings for folders, update text weight and podcast size.
- I am not putting this change behind a feature flag because iOS already has these paddings in production
- Check folders spacings for the 3 layouts
| ![before1](https://github.com/user-attachments/assets/6f4b5ecf-37ff-4105-bc7b-3127dd813ee4) | ![before2](https://github.com/user-attachments/assets/6b3fe864-4072-46a4-9bfa-f433c6323fe1) | ![before3](https://github.com/user-attachments/assets/03c0b325-3f58-4347-8c39-bc9eed2f78ef) |
| --- | --- | --- |
| ![after1](https://github.com/user-attachments/assets/b3442dc2-c2ba-49a8-b21d-06e9eab536fd) | ![after2](https://github.com/user-attachments/assets/fb61352d-164d-4389-b73c-d8337696e74a) | ![after3](https://github.com/user-attachments/assets/7bab7581-b024-494 …
=> Folders UI tweaks

modules/features/podcasts/build.gradle.kts, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastToolbar.kt, modules/services/repositories/build.gradle.kts, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageColorAnalyzer.kt
This PR adds background artwork images to the podcast view. On SDK 31 and above, it applies a blurred artwork effect. On lower versions, vertical scrims are used instead.  
1. Start the app on a device running SDK 31 or higher.  
2. Go to **Settings**.  
3. Enable the `Podcast view changes` feature flag.  
4. Open any podcast.  
5. Observe the blurred artwork.  
6. Scroll through the content and check if the status bar icons maintain good contrast at all times. Some complex artworks may cause contrast issues when the toolbar is transparent, though I haven't encountered such cases.  
7. Test with different themes and podcasts.  
1. Start the app on a device running SDK 30 or lower.  
2. Go to **Settings**.  
3. Enable the `Podcast view changes` feature flag.  
4. Open any podcast.  
5. …
=> Add background artwork to podcast view

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
Fixes #3617
2. Tap on "Help & feedback"
3. Tap on the Help button
4. Tap on the "Send a message..." box
5. Ensure you can see the whole AI message by scrolling the screen ✅
[Screen_recording_20250221_135942.webm](https://github.com/user-attachments/assets/52e31fe7-af5c-40f7-9a72-47f5ba91655e)
=> Fix: Support AI Assistant keyboard hides the message box

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt, modules/services/images/src/main/res/drawable/ic_chevron_small_up.xml, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/109.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
This PR adds expand and shrink animations to the podcast header. I added a new column to the database so the expanded state is persisted. By default, the header is expanded.
Designs: 3LuZimaaH5tGKxIkOpjYAZ-fi-1071_23719
1. Install the app from 3e65ae6a441b8213e6773dc72989b4afd09a1b09.
2. Have some active follows.
3. In settings, enable `Podcast view changes` flag.
4. Install the app from the `task/expandable-header` branch.
5. Open any followed podcast.
7. Tap on the image or the title to toggle the expanded state.
8. Keep the header in a collapsed state.
9. Close the app.
10. Reopen the app and go back to the podcast.
11. The header should be collapsed.
12. Go to any non-followed podcast.
13. Collapse the header.
14. Close the app.
15. Reopen the app and go back to that podcast.
16. The …
=> Make header expandable

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTest.kt, gradle/libs.versions.toml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
We are seeing the following exception from version 7.82.
```
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStopInTimeException: 
A foreground service of type dataSync did not stop within its timeout: 
ComponentInfo{au.com.shiftyjelly.pocketcasts/androidx.work.impl.foreground.SystemForegroundService}
```
There's a [Google issue on the crash](https://issuetracker.google.com/issues/364508145). The recommended fix is to upgrade Work Manager. The [release notes of 2.10.0-alpha04](https://developer.android.com/jetpack/androidx/releases/work#2.10.0-alpha04) have the following:
> Add the stop reason STOP_REASON_FOREGROUND_SERVICE_TIMEOUT for when a foreground worker is stopped due to execution timeout based on the foreground service type.
I have targeted the 7.83 beta as a …
=> Increase the Work Manager version to 2.10.0

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ExpandableText.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/text/Extension.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This PR adds podcast details to the header UI with the collapse animation.
1. Open any podcast with long enough description.
2. Tap on the description.
3. It should expand.
4. Tap on it again.
5. It should collapse.
6. Tap on the artwork.
7. The whole bottom section should collapse.
https://github.com/user-attachments/assets/401fca32-fb67-473a-bd23-22738cf82586
=> Include podcast details in header

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
This PR shows snackbar when users enable podcast notifications. This change affects also current UI.
Design: 3LuZimaaH5tGKxIkOpjYAZ-fi-1062_37213
2. Follow it.
3. Enable notifications.
4. A snackbar should appear.
5. Disable notifications.
6. There should be no snackbar.
=> Show notification feedback message in a snackbar

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/FolderDaoTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolders.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/FolderDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt
- This syncs the list of podcasts after accepting the suggested folders. While I was testing, I faced a scenario that my folders were not getting synced. In order to fix this issue, I am refreshing the podcasts list after the user applies the suggested folders
1. Log in with a paid account
2. Have a list of podcasts in device A
3. Open the suggested folders screen and use the suggested folders
4. Go to a device B and log in with the same account
5. Sync the account
6. Go to podcasts tab
7. You should see the suggested folders there
=> [Suggested Folders]  Sync Podcasts after updating folders

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastInfoView.kt
Some minor UI tweaks to the podcast header.
Context: p1740413419003659-slack-C08DPN79CN8
Check the podcast header UI.
Screenshots don't reflects that but I also fixed the spacing in podcast info UI in 9cdd49f.
| - | - |
| ![b1](https://github.com/user-attachments/assets/acff141a-717f-4849-8229-95a19f5c85e5) | ![a1](https://github.com/user-attachments/assets/bf1546b7-a039-425d-9b13-e0ea00c0381d) |
| ![b2](https://github.com/user-attachments/assets/d0230610-ca13-4185-82ed-b5c8e1373f47) | ![a2](https://github.com/user-attachments/assets/676d10cc-ee72-4cf5-b355-9975fdcaa9ad) |
=> Update header UI

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywall.kt
- Just adds a missing bottom padding for paywall
1. Log in with free account
2. Follow a podcast
3. Go to Podcasts tab
4. Ensure the suggested folders paywall has bottom padding ✅
=> [Suggested Folders] Add missing padding for paywall

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersMapper.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/services/localization/src/main/res/values/strings.xml
- These are some minor UI changes requested:
- cycle folder colors instead of random numbers to avoid repeating colors next to each other.
- `Maybe later` instead `Maybe Later`
- set alphabetical sort after accepting suggested folders
- update suggested folders paywall copy
- Request: p1740630237193229/1740621534.095339-slack-C08BRS7N9UL
- Request 2: p1740631091561499/1740626371.709879-slack-C08BRS7N9UL
1. Using paid account with some followed podcasts
2. Open the suggested folder screen
3. You should not see folders with the same color side by side ✅
4. Accept the new suggested folders
5. The folders should be sorted by Name ✅
[Screen_recording_20250227_101501.webm](https://github.com/user-attachments/assets/bc5d7fa6-2c7e-4a26-89c3-a23e78614051)
=> [Suggested Folders] General UI updates

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/text/Extension.kt
When podcast HTML description was trimmed the spans inside of it were not adjusted for the trimmed padding causing a crash when visiting a podcast. This PR fixed that.
The crash was introduced in `7.84` so there's no need to mention the fix in the changelog.
1. Open the [Embedded](https://pca.st/podcast/f6ffd000-c8fc-0133-2e8b-6dc413d6d41d) podcast.
2. The app shouldn't crash and you should be able to see the description.
=> Fix HTML podcast description crashing

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/text/Extension.kt
Fixes #3660
1. Open a podcast like [Dirtbag Rich](https://pca.st/zkf1jxjd) that has a HTML description or like [No Such Thing](https://pca.st/hourucli) that has a plain text description.
2. Tap on link in the description.
3. The link should open.
https://github.com/user-attachments/assets/d43750f7-5f27-4d5c-86f1-b00057cded44
=> Add description link navigation

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This PR enables remote control of the feature.
=> Enable podcast view remote feature flag

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolders.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- This adds some missing tracks
1. With free account. Follow some podcasts
2. Go to Podcasts tab and see the suggested folders paywall
3. Tap on Use these folders button
4. Ensure 🔵 Tracked: suggested_folders_paywall_modal_use_these_folders_tapped
1. Follow some podcasts
2. Have some existing folders
3. Go to suggested folder screen
4. Tap on use these folders
5. See the Replace folders modal
6. Ensure 🔵 Tracked: suggested_folders_replace_existing_folders_modal_shown
7. Tap on Replace folders button
8. Ensure 🔵 Tracked: suggested_folders_replace_folders_tapped
=> [Suggested Folders] Add missing tracks

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
This ads missing mapping for the technology category.
1. Open [TechSurge](https://pca.st/jb1ui8gd) podcast.
2. Tap on the "Technology" category in the header.
3. It should open it in the Discover page.
=> Add missing technology category mapping

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/AndroidManifest.xml, build.gradle.kts, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
To support the Web Player share pages, we need to add a new intent filter and logic similar to the pca.st share page. 
The assetlinks.json file is only available in staging at the moment so this will only work in our debug version.
1. Install the `debug` build variant
2. Click on the following links. They won't work if you use them directly in the browser. I posted them to a private Slack channel and clicked them from the posted message. Or you could use this PR message.
3. Tap the podcast share https://play.pocketcasts.net/podcasts/4eb5b260-c933-0134-10da-25324e2a541d
4. ✅ Verify it opens The Daily podcast page
5. Tap the episode share https://play.pocketcasts.net/podcasts/4eb5b260-c933-0134-10da-25324e2a541d/1c82ee02-01cb-4c36-bc13-020c8c15cd8c
6. ✅ Verify it opens The Daily - A …
=> Support the Web Player share pages

CHANGELOG.md, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfilePage.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/RecyclerView.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/TopScrollable.kt
This PR prevents reloading fragments when they are at the root of the back stack and instead ensures they smoothly scroll to the top when navigated to. This aligns with iOS behavior but removes a previous side effect. Previously, the Filters screen toggled between showing all filters and the last opened one when tapping on the navigation bar icon. Now, this behavior is no longer possible, as the screen will always smooth scroll to the top.
Fixes #2149
If you experience animation stuttering try testing this fix with the release variant first.
1. Scroll the content of a fragment and tap on its icon in the navigation bar. The content should smooth scroll to the top without flickering.
2. Perform regression tests to check for any unintended navigation side effects. …
=> Fix screen flicker upon nav bar navigation

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
This fixes an issue where playback was not resuming when using back and forward actions.
1. Play something with headphones connected.
2. Pause the playback.
3. Using the headphones action skip forward.
4. The playback should resume.
5. Do the same test but with the skip back action.
=> Add play action to skipping back and forward headphone actions

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/log/LogBuffer.kt
Add some more logs to diagnose media events. It also increases the resolution of our logs to milliseconds.
=> Improve media event logging

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SuggestedFoldersManager.kt
- This address some small changes
- Rename to Smart folders: p1740723674015329/1740626371.709879-slack-C08BRS7N9UL
- Update the dismiss rule: p1740739349215759/1740662999.868259-slack-C08BRS7N9UL
- Show paywall only when following at least 4 podcasts: p1740753502698749/1740745238.160689-slack-C08BRS7N9UL
- Fix this small issue: p1740719275171009-slack-C08BRS7N9UL
To test the dismiss rule, I recommend to change from `7.days` to `7.seconds` here: https://github.com/Automattic/pocket-casts-android/pull/3675/files#r1975639312
1. Fresh install
2. Do not follow any podcast
3. Go to Podcasts tab
4. Ensure you don't see the paywall ✅
5. Follow 4 podcasts
6. Go to Podcasts tab again
7. Ensure you see the paywall ✅
8. Tap outside of the modal to dismiss it
9. Go to Discover
10. Back to Podcasts tab …
=> [Suggested Folders] Tweaks part 3

.github/workflows/high-prio-issue-notify-slack.yml
Background: https://a8c.slack.com/archives/C07J5LNP4SF/p1740664911286009
When a new or existing issue is labelled with `[Priority] High`, the message is sent to pocket-casts-android Slack channel.
The webhook URL is added as a repo secret, and the channel to be used is defined in the Slack app webhook settings. So, both are configured outside the file added by this PR.
I believe there's no way to test the PR unless it's merged. If this helps, the exact same YML file was tested in my private sandbox repo, using the same webhook reference, and it worked ([see this Slack message](https://a8c.slack.com/archives/C028JAG44VD/p1740765498787409)):
=> [Slack Webhook] A new workflow to trigger Slack Webhook when high prio label is applied.

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ExpandableText.kt
This fixes wrong color for the header icons.
Check header icons with different themes, especially Dark Constrast.
| - | - |
| <img width="415" alt="Screenshot 2025-03-03 at 21 42 06" src="https://github.com/user-attachments/assets/139decc9-efe6-4ef4-a75f-188385b71bb7" /> | <img width="415" alt="Screenshot 2025-03-03 at 21 41 51" src="https://github.com/user-attachments/assets/c51e2a50-d289-4feb-8ff6-263bfc1d8d6c" /> |
=> Update header icon color

CHANGELOG.md, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
Updating mini player position only once is incorrect as there is a race condition between updating bottom insets and said position. This PR changes the logic to update the bottom offset properties whenever the layout changes.
Fixes #3568
This change potentially deals with #3631 as well but I don't really know as I can't replicate that behavior at all.
It's hard to give the steps as the bug is not deterministic but try to replicate #3568.
=> Update bottom controls position with every layout change

fastlane/Fastfile
Context: p1740990351304109/1740786797.612419-slack-CC7L49W13
@geekygecko reported during last release that the `finalize_release` automation running on CI failed to download Gradle, which made the lane and CI build fail.
```
[18:47:07]: Exit status of command './gradlew aggregatedLintRelease' was 1 instead of 0.
Downloading https://services.gradle.org/distributions/gradle-8.12.1-all.zip
Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-8.12.1-all.zip failed: timeout (10000ms)
at org.gradle.wrapper.Install.forceFetch(SourceFile:4)
at org.gradle.wrapper.Install$1.call(SourceFile:8)
at org.gradle.wrapper.GradleWrapperMain.main(SourceFile:67)
Caused by: java.net.SocketTimeoutException: connect timed out
```
This PR temporarily …
=> [Tooling] Workaround: disable running `lint_task` during `finalize_release`

.buildkite/release-pipelines/code-freeze.yml, .buildkite/release-pipelines/download-translations.yml, .buildkite/release-pipelines/finalize-hotfix-release.yml, .buildkite/release-pipelines/finalize-release.yml, .buildkite/release-pipelines/new-beta-release.yml, .buildkite/release-pipelines/new-hotfix-release.yml, .buildkite/release-pipelines/publish-release.yml, .buildkite/release-pipelines/update-rollouts.yml, fastlane/Fastfile
- Follow-up on https://github.com/Automattic/pocket-casts-android/pull/3688
- Slack context: p1740990351304109/1740786797.612419-slack-CC7L49W13
@geekygecko reported during last release that the `finalize_release` automation running on CI failed to download Gradle, which made the lane and CI build fail.
```
[18:47:07]: Exit status of command './gradlew aggregatedLintRelease' was 1 instead of 0.
Downloading https://services.gradle.org/distributions/gradle-8.12.1-all.zip
Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-8.12.1-all.zip failed: timeout (10000ms)
at org.gradle.wrapper.Install.forceFetch(SourceFile:4)
at org.gradle.wrapper.Install$1.call(SourceFile:8)
at org.gradle.wrapper.GradleWrapperMain.main(SourceFile:67) …
```
=> [Tooling] Split `download_translations` from `finalize_release`

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CacheWorker.kt
This adds exception details to debug logs when episode caching fails to troubleshoot playback issues.  
9265401-zen
=> Improve logs when episode caching fails

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/RecyclerView.kt
Tapping on a search bar didn't scroll to a correct position due to toolbar not being part of the same layout.
Context: https://pocketcastsbeta.slack.com/archives/C013F9S9C2W/p1741109744236849
1. Open a podcast with enough episodes that they don't fit on screen.
2. Tap on the search field.
3. The screen should scroll to top but the toolbar should still be visible.
=> Include toolbar height in podcast search scrolling offset

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/110.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
This makes pre-subscribed podcasts headers collapsed by default.
Context: p1741043280164069-slack-C08DPN79CN8
1. Install the app from the `release/7.84` and follow some podcasts.
2. Go to any followed podcast. Its header should be expanded.
3. Update the app with the code from the `task/header-expanded-state` branch.
4. Go to any followed podcast. Its header should be collapsed.
5. Go to any not followed podcast. Its header should be expanded.
6. Clear the app's storage.
7. Open the app.
8. Sign in.
9. Your follows should have headers collapsed.
=> Make header state collapsed when a podcast is already followed

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/log/LogBuffer.kt
When looking through the production exceptions I noticed the following:
It doesn't seem to be a common issue but thought it would be worth fixing. I didn't find the route cause of the log format breaking but I have caught the exception to stop the app crashing. 
I also tried to clean up the warnings in the class while I was there.
1. Change the app started log in `PocketCastsApplication.kt` to the following:
```
LogBuffer.i("Application", "App started. ${settings.getVersion()} (${settings.getVersionCode()}) %s %i %d", 1, 2, 3)
```
2. ✅  Verify the app doesn't crash and the log still has the message in it.
```
Application: App started. 7.84-rc-2 (9317) %s %i %d (Unable to format log message with args [1, 2, 3])
```
=> Fix log format exception

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPopupPolicy.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPopupPolicyTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SuggestedFoldersManager.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SuggestedFoldersManagerTest.kt, modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/MutableClock.kt
This PR defines the rules for showing smart folders popup.
> [!note]
> The current UI and logic of applying folders is most likely broken or has some bugs. This PR is only about showing the popup. Nothing else.
1. Start the app without being signed in.
2. Follow at least 8 podcasts.
3. Go to the Podcasts page.
4. A popup with smart folders should appear.
5. Dismiss the popup.
6. Navigate to a different page.
7. Return to the Podcasts page.
8. The popup should not appear.
9. Close the app.
10. Open device settings.
11. Set the date on your device to 7 days in the future.
12. Open the Pocket Casts app. You might experience network request failures due to the changed date, but ignore them.
13. Go to the Podcasts page.
14. You should see the smart folders popup.
15. Dismiss the popup.
16. Go …
=> Define policy for showing smart folders incetive

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
Reverts https://github.com/Automattic/pocket-casts-android/pull/3473
Context: p1741092431617609/1733996004.946999-slack-C02A333D8LQ
1. Open a podcast.
2. Tap on an episode to open the episode details.
3. Tap on the Archive button.
4. The episode details screen should close.
=> Close episode details upon archiving

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolderPodcastsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
This PR adds navigation to podcast list after tapping on the suggested folder.
Designs: QmqtGNKfPivyq5BrVRPpyV-fi-347_3478
1. Follow at least 8 podcasts.
2. Start the suggested folders flow either from the popup as a free user or folders button as a paid one.
3. Tap on any folder.
4. Notice that you see it's details.
5. Navigate back either with back button or top left arrow.
https://github.com/user-attachments/assets/e9a5b871-5d20-4cae-bfa8-06b0b43dffe3
=> Navigate to folder details

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
This adds suggested folder flow to our regular folder button and onboarding flow to custom folder.
1. Start the app as an unsigned or a free user.
2. Go to the podcasts page.
3. Tap folder icon.
4. You should see the onboarding flow.
5. Dismiss it.
6. Follow at least 8 podcasts.
7. Go back to the podcasts page.
8. Dismiss the folders popup.
9. Tap on the folders icon.
10. You should see the suggested folders flow.
11. Tap "Use these folders".
12. Onboarding should start.
13. Go back.
14. Tap "Create custom folder".
15. Onboarding should start.
=> Handle free users suggested folders flow

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/refresh/RefreshServiceManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/refresh/RefreshServiceManagerImpl.kt
There's a new exception in production, `UnknownHostException.` This was because if the device was offline, our server call was failing, but we weren't catching the exception. 
As part of this I also moved the HTTP status code and header logic out of the `PodcastManagerImpl.kt` and into `RefreshServiceManagerImpl.kt` as it seems cleaner.
1. Turn off WiFi and mobile data.
2. Follow a podcast.
3. Open the podcast page.
4. Pull down to update the podcast.
5. ✅  Verify the app doesn't crash.
6. ✅  Verify the update is happening by filtering the log by "Refresh podcast".
=> Fix crash with podcast update when offline

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
Tracks events for suggested folders.
Verify suggested folders events from [the Tracking Plan](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0).
=> Add suggested folders analytics

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModel.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModelTest.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This removes `search_in_listening_history` feature flag.
=> Remove `search_in_listening_history` feature flag

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This removes transcripts feature flag.
=> Remove `transcripts` feature flag

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/player/src/main/res/layout/fragment_effects.xml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This removes `custom_playback_settings` feature flag.
=> Remove `custom_playback_settings` feature flag

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt
- Updates source value
- See: p1741265599104839/1741184037.466609-slack-C08BRS7N9UL
- Code review is fine.
- In case you want to test, follow the steps from [here](https://github.com/Automattic/pocket-casts-android/pull/3724) and make sure we track with `podcasts_list` source instead of `podcasts`
=> Update suggested folder analytics value

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChaptersTest.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This removes `deselect_chapter` feature flag and patron exclusive tier criteria as the feature is available to all Plus users.
1. Launch the app without login or with a free account
2. Play an episode with chapters (e.g. episode for podcast `Upgrade`)
3. Go to `Chapters` tab
4. Notice upsell for `Preselect chapters` (for Plus)  
5. Tap upsell for `Preselect chapters`
6. Notice that the feature is listed under `Plus` plan and the title is "Preselect chapters and more with Pocket Casts"
7. Repeat steps 2-3 with a paid account (Plus or Patron)
8. Notice that you can preselect chapters properly.
Chapters| Upsell
---|----
=> Remove `deselect_chapter` feature flag and patron exclusive tier criteria

modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModelTest.kt
- Adding back tests for `SuggestedFoldersViewModelTest` after ignoring them due to flakiness. https://github.com/Automattic/pocket-casts-android/pull/3627
Make sure CI is 🟢
=> Add SuggestedFoldersViewModelTest

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This adds a feature flag for podcasts sorting changes.
1. Open `Profile` -> `Settings` -> `Beta features`
2. Notice that `Podcasts Sort Changes` feature flag is present and enabled for the debug build
=> Add feature flag for podcasts sorting changes

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
This PR makes headset back action not resume playback. In general it was inconsistent in the past between different headsets. Now that we have better control over headset actions, skipping back and not resuming playback while it's paused sounds like a more logical option.
Context: p1741274210042099-slack-C05RR9P9RAT
1. Connect headset that can trigger skip back or skip forward actions.
2. Play something and scroll to the middle.
3. Pause playback.
4. Skip back using the headset.
5. Playback should skip back but not resume.
6. Skip forward using the headset.
7. Playback should skip forward and resume.
=> Do not resume playback when skipping back with a headset action

.buildkite/commands/diff-merged-manifest.sh, .buildkite/pipeline.yml, .buildkite/shared-pipeline-vars
Project Thread: paaHJt-7Tl-p2
Tested By: #3731
---
This PR introduces the `Merged Manifest Diff` CI job that is aiming to help revealing merged manifest changes a PR might introduce.
The main problem this script is trying to address is the fact that:
1. Although explicit `AndroidManifest.xml` changes are visible on a PR review, just by looking at the `Files changed` tab for that specific change, this doesn't necessarily mean that the actual, auto-generated, merged `AndroidManifest.xml` file should have the same amount of changes.
2. Sometimes, implicit `AndroidManifest.xml` changes can occur (think new/updated dependency). Those changes are actually invisible for both, to the author and reviewer of that specific PR.
For more info on the technical/workflow side of things see: …
=> [AndroidManifest] Reveal Manifest Changes in PR

.github/dependabot.yml
With this configuration Dependabot (:dependabot:) should update both, the `Kotlin` and `KSP` related dependencies in one go, on a single Dependabot related PR.
FYI: Using the `applies-to key` is optional. If the `applies-to key` is absent from a set of grouping rules, it defaults to `version-updates` for backwards compatibility. I chose to use `applies-to` in order to be explicit about this and avoid any confusion related to the defaults.
For more info see: [Configuration options for the dependabot.yml file -> groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
---
FYI: The very same configuration was already tested on [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android) and works …
=> [Deps] Group Kotlin & KSP Dependabot Updates

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/SwipeToArchiveCallback.kt
This fixes pull to refresh on swiping episode item sideways on the Podcast page.
Fixes #3608
1. Go to Podcast screen
2. Start swiping Episode sideways to archive
3. In the same swipe, start swiping a bit downwards
4. ✅ Notice that pull to refresh doesn't override the swipe action
[swipe_pull-to-refresh.webm](https://github.com/user-attachments/assets/64ea785c-5d0d-4e74-b6d8-493e5081f9eb)
=> Podcast Page: Fix pull-to-refresh on episode swipe

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptError.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptsPaywall.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfViewModelTest.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModelTest.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/111.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/TranscriptDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Transcript.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptCuesInfoBuilderTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This PR adds generated transcripts support.
1. Install the `debug` variant on a device running Android 12 or higher.  
2. Use either no account or a free account.  
3. Play [this episode](https://href.li/?https://nodeweb.pocketcasts.net/admin/podcasts/1213868/episodes/1237292002).  
4. Go to the transcripts.  
5. You should see a blurred paywall.  
6. The content should not be interactive.  
7. Sign in with a Plus or Patron account.  
8. Go back to the transcripts.  
9. You should no longer see the paywall.  
10. Repeat the steps on a device running Android below version 12.  
11. Everything should work the same, except instead of a blur, a blank background should be shown.  
12. Disable the `Generated transcripts` flag.
13. Play a different episode.
14. Play again the episode from 3rd …
=> Parse generated transcripts

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptDefaults.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptError.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/res/values-sw600dp/dimens.xml, modules/features/player/src/main/res/values/dimens.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/FadedLazyList.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Modifier.kt
This PR restructures the transcripts page UI. Previously, all content was placed inside a `Box` with padding applied to create the illusion of a column-like layout. Now, the components are inside a `Column`, making it easier to support the "generated transcripts" info header.
To simplify edge fading and eliminate the need for gradients, I introduced a FadedLazyColumn type. It automatically applies edge fading based on the scroll position. When the content is scrolled to the top, the top edge does not fade. Likewise, when scrolled to the bottom, the bottom edge remains clear.
Smoke test transcripts UI.
=> Restrcuture transcripts page UI

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/PlayerHeadingSection.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/PlayerShelf.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptError.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModelTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
This PR handles upselling and onboarding when subscribing via the generated transcripts paywall. To avoid using a global event bus, I refactored the transcripts view model so that it can listen to the subscription status. This ensures that the paywall is hidden once the subscription is made.
1. Enable the `GENERATED_TRANSCRIPTS` feature flag in the code.
2. Install the `release` variant.
3. Open the app.
4. Play an episode with generated transcripts, such as [this one](https://pca.st/episode/08140cb7-aa73-4da9-bc47-30c0303e2555).
5. Tap the "Subscribe to Plus" button.
6. Complete the onboarding flow and purchase Plus.
7. Once the flow finishes, you should see the generated transcript.
https://github.com/user-attachments/assets/2f536433-8f77-4cd5-a772-91cd8a684a7b
=> Upsell transcripts

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/PlayerHeadingSection.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt, modules/features/player/src/main/res/values-sw600dp/dimens.xml, modules/features/player/src/main/res/values/dimens.xml, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModelTest.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Springs.kt, modules/services/views/src/main/res/values/ids.xml
This PR simplifies transcripts transition state and improves animations.
1. Play an episode with generated transcripts, such as [this one](https://pca.st/episode/08140cb7-aa73-4da9-bc47-30c0303e2555).
2. Toggle transcripts and notice the animation.
3. Repeat the same for an episode with regular transcripts.
| - | - |
| <video src="https://github.com/user-attachments/assets/5228a18e-dd69-4d92-a572-73584991af22"/> | <video src="https://github.com/user-attachments/assets/e5787f43-2ed2-4bc0-95c0-bbdd351b7ea2"/> |
=> Improve transcript transition animation

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPageWrapper.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
This PR adds analytics for the generated transcripts.
Verify these events are triggered with podcast ID and episode ID properties.
Starting the upsell flow should use `generated_transcripts` as the `source` property.
=> Add generated transcripts Tracks

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
Internal Ref: p1741726917427339-slack-C078746V6UX
1. Enable the `GENERATED_TRANSCRIPTS` feature flag in the code.
2. Install the `release` variant.
3. Open the app.
4. Play an episode with generated transcripts, such as [this one](https://pca.st/episode/08140cb7-aa73-4da9-bc47-30c0303e2555).
5. Tap the "Subscribe to Plus" button.
6. Complete the onboarding flow and purchase Plus.
7. You should not see the recommendations screen during the onboarding.
=> Do not show recommendation page when subscribing via transcripts

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateEpisodeTask.kt
Cherry picked from commit 829e6a4116742e6cdb3da9f0e9369ec67236ea3b (https://github.com/Automattic/pocket-casts-android/pull/3764)
=> Improve logs for episode download url updates

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
This PR adds a new analytics event.
Internal ref: p1741859946460429/1741859769.286699-slack-C08DPN79CN8
1. Open podcast.
2. Tap on a link in the podcast details info.
3. Notice `podcast_screen_podcast_details_link_tapped` event tracked.
=> Add podcast_screen_podcast_details_link_tapped event

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkFragment.kt
Fixes #3732
1. Start bookmark creation for an episode.
2. Notice that the button is not hidden behind the keyboard.
3. Hide the keyboard.
4. The button should be at the bottom of the screen.
| - | - |
| ![b](https://github.com/user-attachments/assets/b29e81af-048f-4331-88d2-05418a694834) | ![a](https://github.com/user-attachments/assets/cddffff4-ffd8-4f45-a79e-cc7f4de68e7f) |
=> Add IME padding to the bookmarks page

modules/features/podcasts/src/main/res/layout/fragment_podcast_redesign.xml
Multi-select toolbar added unnecessary spacing to podcast content. Now it is aligned with the toolbar.
2. Long press an episode or a bookmark.
3. Notice that the multiselect toolbar doesn't offset the content and is displayed over it instead.
| - | - |
| ![b](https://github.com/user-attachments/assets/5cf75dfa-a1c3-43a5-b436-177dc54ba1d4) | ![a](https://github.com/user-attachments/assets/a1c64dec-91a1-4843-b0a8-eb2310144e1d) |
=> Fix multiselect toolbar position

CHANGELOG.md, modules/features/widgets/src/main/res/xml/large_player_widget.xml, modules/features/widgets/src/main/res/xml/medium_player_widget.xml, modules/features/widgets/src/main/res/xml/small_player_widget.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/res/xml/widget.xml
This updates the widget existing titles and adds the new descriptions field. These are now more similar to how Google labels their widgets, for example:
| | |
| ![Screenshot_20250213_173941 (1)](https://github.com/user-attachments/assets/30d5bbfe-61d3-495c-9691-e8d9c93ca7f8) | ![Screenshot_20250213_173921 (1)](https://github.com/user-attachments/assets/14a2b8a3-d44d-4076-be72-e67872de44eb) | 
Internal reference: p1739426473618099/1739426442.471469-slack-C05RR9P9RAT
1. Long press on the home screen
2. Tap "Widgets"
3. Scroll down to the Pocket Casts widget
4. ✅ Verify the widget text 
| --- | --- |
| ![Screenshot_20250314_141441](https://github.com/user-attachments/assets/94aaca1d-1908-4301-88bb-d4e1b09d219e)  | …
=> Widgets: update titles and add descriptions

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
A remote feature flag for generated transcripts.
=> Add generated transcripts remote feature flag

CHANGELOG.md, modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt, modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
This improves the small widget by reducing the number of targets that TalkBack selects. One of them removed is the target that's below the touch target requirement of 48dp.
1. Turn on TalkBack (In the emulator use the "Device UI Shortcuts" to toggle it)
2. Hove your finger over an element above
3. Swipe from left to right to move through the elements
4. ✅ Verify it's possible to pause and play an episode
Internal reference: p1739426497274879/1739426442.471469-slack-C05RR9P9RAT
You can't hear the TalkBack voice in these videos but there is the text output at the bottom of the screen.
**After**
https://github.com/user-attachments/assets/1f1607e9-21cc-486b-bd5b-decfd0b42196
**Before**
https://github.com/user-attachments/assets/74979826-aaa5-4271-b9a2-763fa97ef70d
=> Improve small widget accessibility

modules/services/preferences/build.gradle.kts, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This PR adds local override for default data collection value.
Internal Ref: p1741847895036839-slack-C07J5LNP4SF
1. Make a fresh installation.
2. Go to the privacy settings.
3. Notice that analytics and crash reporting is enabled.
4. Add `au.com.shiftyjelly.pocketcasts.data.collection=false` to your `local.properties` file.
5. Reinstall the app.
6. Go to the privacy settings.
7. Notice that the tracking settings are disabled.
=> Read data collection default value from local.properties

CHANGELOG.md, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
If the mini player wasn't open, the podcast grid didn't add the surrounding padding. 
1. Fresh install the app.
2. Follow some podcasts.
3. Go to the Podcasts tab.
4. ✅ Verify the podcast grid has padding on the side so the artwork lines up with the Podcasts title.
| --- | --- |
| ![Screenshot_20250317_171710](https://github.com/user-attachments/assets/bebcc989-c6e7-4c61-bac8-dce2a7fa264a) | ![Screenshot_20250317_171625](https://github.com/user-attachments/assets/d0f3c061-7dbe-40f2-9936-069dfa24a463) |
=> Add padding to the podcast grid

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/toolbars/textselection/CustomTextToolbar.kt
I noticed that when selecting text in a transcript and clicking the share button, the text was incorrect. This only happens on API < 33 when the share button is shown. The current Compose components make it impossible to copy the selected text, but this is coming to a future version. In the meantime, a workaround is to copy the text to the clipboard using the copy function.
1. Use an Android older than API 33
2. Follow the podcast Conan O'Brien
3. Play the latest episode
4. Open the full screen player
5. Tap the more options in the player shelf
6. Tap Transcript
7. Highlight some text
8. Tap Share
9. ✅ Verify the shared text is correct
https://github.com/user-attachments/assets/83fe8241-48df-44a3-bf42-90a5ccc8d9e3
=> Fix share transcript text when API less than 33

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/res/layout/fragment_podcast.xml, modules/features/podcasts/src/main/res/layout/fragment_podcast_redesign.xml
This PR addresses an issue related to window insets. The fix consists of reordering how views are being drawn. Compose modifier for window insets consumes them which means that the multi-select toolbar didn't receive the dispatch event. By moving `ComposeView` containing regular toolbar to be drawn as the last element we allow multi-select toolbars to receive insets.
I also removed outer `LineaerLayout` which is no longer needed after the redesign.
Fixes #3790
1. Select a podcast on a device with a lower Android version.
2. Long press an episode.
3. Notice that the multi-select toolbar does not coincide with the status bar.
4. Test this with different SDKs.
| - | - |
| ![Image](https://github.com/user-attachments/assets/d1148e1b-cb52-4c88-a949-74626be42b1b) | …
=> Apply window insets to multi-select toolbar across all Android versions

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPage.kt
- Update text color to match with design
- Removes extra bottom padding
- Design: QmqtGNKfPivyq5BrVRPpyV-fi-383_4220
- Addresses this: pdeCcb-93P-p2#comment-7099
1. Fresh install the app using free user account
2. Follow at least 8 podcasts
3. Go to Podcasts
4. See the Smart Folders screen
5. Check the changes
| ![before](https://github.com/user-attachments/assets/f47e72c9-6b4f-4d88-bd71-827e8eea01ed) | ![after](https://github.com/user-attachments/assets/c0eef0ac-652b-4478-ab37-87c9d3419d9f) |
=> [Suggested Folders] Update text color and remove extra bottom padding

CHANGELOG.md, modules/services/localization/src/main/res/values/strings.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ConfirmationDialog.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
When using the multi-select toolbar and deleting over three episodes, it will now show a confirmation dialog. This was a user request after they accidentally deleted over 200 downloads.
1. Open a podcast page
2. Download four of the episodes
3. Long press on an episode row to change into multi-select mode
4. Select the four episodes
5. Tap the delete downloads button in the toolbar
6. ✅ Verify a confirmation is shown and tapping it deletes the episode files.
=> Confirm download file deletes.

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralOfferInfoProviderTest.kt
This is a very ugly fix for the issue where users only see the yearly offer when a 1-month free trial is available.
The root cause of the issue is that the `SubscriptionMapper` logic is highly sensitive to any changes in our Play Console configuration. When the Winback offer was added, it wasn’t properly filtered out in most of the scenarios. I added a boolean flag to determine whether it should be filtered out or not. As mentioned, this is a temporary and inelegant workaround to restore expected behavior.
I believe our approach to retrieving subscription data needs a significant redesign and rewrite. We shouldn't be in a situation where adding an offer in the Play Console causes issues in unrelated parts of the app.
> [!note]  
> You need to test with an account signed in to the Play …
=> Fix subscription mapper not using all offers

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextHistoryDaoTest.kt, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/112.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextHistoryDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextHistory.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextHistoryEntry.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/history/upnext/UpNextHistoryManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/history/upnext/UpNextHistoryManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/history/upnext/UpNextHistoryManagerImplTest.kt
This adds a database, dao, and manager classes to support the "Up Next" history.
2. ✅ Notice that `up_next_history` table is created in the database inspector 
3. Delete the app 
4. Install commit ac5a7b15
5. Install code from this branch
6. ✅ Notice that migration is successful and the `up_next_history` table is created in the database inspector 
7. Review database, dao, and manager classes
**I haven't added any query to restore up next history as I plan to use `PlaybackManager`'s `playEpisodesLast()` method which internally saves given episodes to the end of the "Up Next" queue.
=> Up Next History - Add db, dao, manager classes

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextHistoryDaoTest.kt, modules/features/settings/build.gradle.kts, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/history/HistoryFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/history/HistoryPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/history/upnext/UpNextHistoryPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/history/upnext/UpNextHistoryViewModel.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/history/upnext/UpNextHistoryViewModelTest.kt, modules/services/images/src/main/res/drawable/ic_history.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/112.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextHistoryDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextHistory.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UpNextHistoryEntry.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/history/upnext/UpNextHistoryManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/history/upnext/UpNextHistoryManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncWorker.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/history/upnext/UpNextHistoryManagerImplTest.kt
This snapshots "Up Next" queue and displays them under `Settings` -> `Restore from local history` -> `Up Next History`
2. Add a few episodes to "Up Next"  queue
3. Long press mini player and clear queue
4. Go to `Profile` -> `Settings` -> `Restore from local history` -> `Up Next History`
5. ✅ Notice a snapshot entry at the current time with the episodes count
6. Continue from above 
7. Re-add a few episodes to the "Up Next"  queue
8. Login with an existing account with up next queue
9. Wait until refresh completes
10. ✅ Notice that a snapshot entry is created for local episodes before login under `Profile` -> `Settings` -> `Restore from local history` -> `Up Next History`
Settings | Restore options | Up Next History 
---|--|---
See screencast in …
=> Up Next History - Snapshot and display history entries

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerClickListener.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/player/src/main/res/drawable/up_next_card.xml, modules/features/player/src/main/res/layout/adapter_up_next_footer.xml, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml
- Updates the empty state view for Up next
- I confirmed with Dom that we will not center the new empty state view vertically and will keep the current alignment instead: p1742345128275369/1741960558.481799-slack-C08HR9DR065
- Design: 2MA6Bz3Vi36BOhuR9pitCU-fi-50_7599
2. Have empty up next
3. Check the empty view layout
4. Tap on Go to discover button
5. Ensure Tracked: `up_next_discover_button_tapped`
|  | |
| ![Screenshot_20250319_144005](https://github.com/user-attachments/assets/fbfc4a8e-da81-497e-a7b0-eabbd08adc22) | ![Screenshot_20250319_144013](https://github.com/user-attachments/assets/5202203b-948b-47d5-88ff-ac3ccefce40a) |
=> [Empty states] Update for Up next

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CollectionListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastCollectionItem.kt, modules/features/discover/src/main/res/layout/collection_header.xml, modules/features/discover/src/main/res/layout/item_collection_list.xml, modules/features/discover/src/main/res/layout/podcast_collection_item.xml, modules/features/discover/src/main/res/layout/row_collection_list.xml, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml
- This PR adds the header to the collection
- Track header tapping event
- Add subscribe button 
- Design: [zfZ5UzmdLBk3k4CwaFIN3E-fi-3646_53376](https://href.li/?https://www.figma.com/file/zfZ5UzmdLBk3k4CwaFIN3E/?node-id=3646-53376)
1. With `GUEST_LISTS_NETWORK_HIGHLIGHTS_REDESIGN` ON
2. Open Discover
3. Scroll until you see the Guest list, Guest Curator or Network highlight collection 
4. See that the collection shows a header only for the fist page ✅
5. Tap on the header
6. Ensure 🔵 Tracked: discover_list_collection_header_tapped, Properties: {"list_id":"ilst-name", ✅
7. Ensure the collection opens ✅ (same behavior as tapping on show all button)
| Regular device | Large font size | Landscape |
|--------|--------|--------|
| ![Screenshot_20250319_123111](https://github.com/user-attachmen …
=> [Guest List and Network Highlight] Add header

modules/features/discover/src/main/res/layout/collection_header.xml
- Just fixes the header size for collection
1. Run the app in debugProd
3. Look for Guest List / Guest Curator list
4. Ensure the header (author) image has the same height of the podcasts
=> Fix header size for collection

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeaderTooltip.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/RecentlyPlayedSortOptionTooltip.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PopupDropdownMenuTooltip.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Tooltip.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This displays a tooltip for the "Recently played" sort option.
(It extracts the already available tooltip added for the Podcast screen as it now appears to be a common component.)
Designs: 4F4PokoLUFmOl5eIT57B5z-fi-34_1951
1. Install and open the app from the main branch
2. Install the app from this branch (as the tooltip should be shown only for existing users)
3. Open the podcasts tab
4. ✅ Notice that the tooltip is shown
5. ✅ Notice in logs `episode_recently_played_sort_option_tooltip_shown` 
6. Dismiss the tooltip either by tapping the close button or by tapping outside the tooltip
8. ✅ Notice in the logs `episode_recently_played_sort_option_tooltip_dismissed`
=> Podcasts Sorting: Show tooltip

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ExternalDataDaoTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ExternalDataDao.kt
This updates `ExternalDataDao` `getSubscribedPodcasts(sortOrder: PodcastsSortType, ...)` query for the "Recently played" sort option, just for completeness sake.
✅ CI should be green
Nothing needs to be tested as the entry point for `NovaLauncher`, where the query is used, is removed (pdeCcb-520-p2#comment-5832).
=> Podcasts Sorting - Update external data dao query for the "Recently played" sort option

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoView.kt
This temporarily fixes video not playing in landscape mode issue.
It appears there was a race condition where the video view's surface was destroyed immediately after creation while transitioning from portrait to landscape mode. That caused the video to appear black or frozen.
I've added a small delay so that the surface is in a stable state before attachment. While it improves the behavior while transitioning between portrait and landscape mode, I've noticed that the picture-in-picture mode may still have the issue. 
Partially fixes #3807
1. Play a video (eg. from Ted Talks HD)
2. Rotate the device
3. ✅ Notice that the video keep playing
[before.webm](https://github.com/user-attachments/assets/25c2fcfd-bc48-4327-bfa4-1f2e7a12693a) …
=> Temporary fix for video not playing in landscape mode

modules/services/views/build.gradle.kts, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/viewmodels/PodcastSelectViewModel.kt, modules/services/views/src/test/java/au/com/shiftyjelly/pocketcasts/views/viewmodels/PodcastSelectViewModelTest.kt
- Extracts tracks to viewModel
- Removes rxJava 
- Adds unit tests
- Smoke test `Settings -> Notifications -> Choose podcasts`
=> Refactor PodcastSelectFragment

modules/services/views/src/main/res/layout/settings_fragment_podcast_select.xml, modules/services/views/src/main/res/layout/settings_row_podcast.xml
- Fixes the subtitle text and podcast selected count
1. Increase device font size
2. Follow some podcasts
3. Open Settings -> Notifications
4. Enable Notify me
5. Open Choose podcasts
6. Check the screen 
| ![Screenshot_20250328_104807](https://github.com/user-attachments/assets/818080ab-bf31-4f69-8468-297c8ac98418) | ![Screenshot_20250328_103847](https://github.com/user-attachments/assets/8c02f59e-dca0-466b-a935-965766c66a4c) |
=> Fix text clipping at large font sizes on the Podcast Select screen

app/src/test/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModelTest.kt, app/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModelTest.kt, modules/features/filters/build.gradle.kts, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersTooltip.kt, modules/features/filters/src/main/res/layout/fragment_filters.xml, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
- Adds the tooltip for when have empty state in Filters screen
- There is a small difference between the implementation and the designs: the overlay does not cover the navigation bar. Same thing we did for #3650
- Designs: 2MA6Bz3Vi36BOhuR9pitCU-fi-50_7599
1. Fresh install 
2. Go to Filters
3. You should see the tooltip
4. Tap outside of tooltip or close button
5. Tooltip should be closed
6. Close the app and open it again
7. Go to Filters
8. Ensure you don't see the tooltip anymore
=> [Empty State] Update for Filters

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/PrivacySettingsScreen.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/PrivacySettingsViewModel.kt
These are changes for the Apps Flyer integration:
- Adds a feature flag.
- A new setting for the user to decide whether to enable third-party analytics. 
- An extra option is added to the Privacy page to change the settings.
1. Check the AppsFlyer feature flag is turned on
2. Go to the Settings -> Privacy page
3. ✅ Verify there is a new third-party analytics setting and it's off by default
4. Toggle it on
5. Restart the app
6. ✅ Verify it's still turned on
7. Turn the feature flag off
8. Go to the Settings -> Privacy page
9. ✅ Verify the new third-party analytics setting is no longer visible
| Feature Flag Off | Feature Flag On |
| --- | --- |
| ![Screenshot_20250331_114332](https://github.com/user-attachments/assets/6ff11b79-4956-43d8-a493-f5d0a892b2f9) | …
=> AppsFlyer setting

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/consent/TrackingConsentDialog.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowOutlinedButton.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
Presents a consent dialog to new users, allowing them to choose whether to allow tracking or ask the app not to track their activity. Respects user privacy choices by updating settings accordingly. 
2. Tap "Allow" notifications
3. ✅ Verify the consent dialog is shown to you
4. Tap "Allow"
5. Tap "Sign up"
6. ✅ Verify logcat has the entry "Starting AppsFlyer"
7. ✅ Verify logcat has the entry "sendTrackingWithEvent: setup_account_button_tapped"
8. Navigate to Profile tab -> settings cog -> Privacy
9. ✅ Verify Third-party analytics is turned on
2. Tap "Allow" notifications
3. ✅ Verify the consent dialog is shown to you
4. Tap "Ask App Not to Track"
5. Tap "Sign up"
6. ✅ Verify logcat doesn't have the entry "Starting AppsFlyer"
7. ✅ Verify …
=> Adds tracking consent dialog to onboarding flow

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/history/HistoryFragment.kt, modules/services/compose/build.gradle.kts, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Transition.kt
This updates "Up Next History" screen transitions.
Relevant discussion: pdeCcb-9hl-p2#comment-7225
1. Add a few episodes to "Up Next" queue
2. Clear the queue
3. Go to `Settings` -> `Restore from local history`
4. Tap `Up Next History` and navigate in and out
5. Notice that the fade in/ fade out transitions are replaced by slide in/ slide out transitions.
[up_next_history_transition.webm](https://github.com/user-attachments/assets/2b3c0cfa-dd15-4781-8325-a1550ead9b33)
=> Update up next history transition

modules/features/discover/src/main/res/layout/row_podcast.xml
This fixes a minor issue I noticed while working on another feature. The podcast title and subtitle alignment isn't vertically centred when viewing a podcast list in the Discover section. We may have accidentally broken this in a [recent accessibility PR](https://github.com/Automattic/pocket-casts-android/pull/3500). 
I also added some padding so a long subtitle doesn't get too close to the subscribe button.
1. Open the Discover tab
2. Tap on "Show all" on a podcast list
3. ✅ Verify the text is vertically centered
| --- | --- |
| ![Screenshot_20250407_110850](https://github.com/user-attachments/assets/28dd062f-88b1-4ddb-a188-b4e3ccfc9a1d) | ![Screenshot_20250407_111824](https://github.com/user-attachments/assets/e34c3f77-01de-4d27-b00d-2fdb8a0cbcf3) |
=> Podcast list: align podcast details vertically

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt, modules/features/settings/src/main/res/xml/preferences_notifications.xml, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- This PR adds the Daily reminders section to notifications screen
- Wrap the new toggle behind feature flag
- Track event when the new toggle changes
- There is a slight difference between the proposed design and the implementation. The proposed design requires extra padding for the notification setting. I believe we can fix this by converting this screen to Jetpack Compose in a later PR.
- See: hVHQ8RgGQf1afBWybZExD2-fi-0_618
2. Go to Settings -> Notifications
3. Ensure you don't see the `Daily Reminders` toggle ✅
1. Fresh install the app and have the feature flag enabled
2. Go to Settings -> Notifications
3. Ensure you see the `Daily Reminders` section ✅
4. Ensure the toggle is enabled by default ✅
5. Turn off the toggle `Notify me` toggle from daily reminders …
=> [Push Notifications Revamp] Add Daily reminders group to Notifications screen

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowFiltersDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
- Supports the deep link for opening filters tab. This will be used for the new Filters notification that will be implemented in the next PRs: `pktc://filters`
2. In Android Studio terminal, run: adb shell am start -a android.intent.action.VIEW -d "pktc://filters"
3. Ensure Filters tab opens ✅
=> [Push Notifications Revamp] Support deeplink for Filters tab

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ImportDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
- Supports the deep link for opening import opml screen: `pktc://settings/import`
2. Run the command line in Android Studio's terminal: `adb shell am start -a android.intent.action.VIEW -d "pktc://settings/import"`
3. Ensure the Import & Export OPML screen opens ✅
=> [Push Notifications Revamp] Support deeplink for Import

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/UpsellDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
- Supports the deep link for opening up sell. This will be used for the new up sell notification that will be implemented in the next PRs: `pktc://upsell`
2. Do not log in
3. In Android Studio terminal, run: `adb shell am start -a android.intent.action.VIEW -d "pktc://upsell"`
4. Ensure the app opens in Upsell screen ✅
5. Tap to subscribe to Plus
6. Ensure you see the Sign in screen ✅
2. Log in with a free user account
3. In Android Studio terminal, run: `adb shell am start -a android.intent.action.VIEW -d "pktc://upsell"`
4. Ensure the app opens in Upsell screen ✅
5. Tap to subscribe …
=> [Push Notifications Revamp] Support deeplink for Upsell 

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowPageDeepLinkTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/ShowUpNextTabDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
- Supports the deep link for opening  upnext tab. This will be used for the new Up next notification that will be implemented in the next PRs: `pktc://upnext?location=tab`
2. In Android Studio terminal, run: `adb shell am start -a android.intent.action.VIEW -d "pktc://upnext?location=tab"`
3. Ensure Up next tab opens ✅
=> [Push Notifications Revamp] Support deeplink for UpNext tab

CHANGELOG.md, fastlane/Fastfile, modules/services/localization/src/main/res/values-el/strings.xml
The Greek [GlotPress translations](https://translate.wordpress.com/projects/pocket-casts/android/) are at 99%. I believe this is the method for including a locale in the regular release process to include the translations. Please let me know if I have missed anything.
Fixes https://github.com/Automattic/pocket-casts-android/issues/3851
I have added one translation manually to test the strings file works.
1. Go to the Profile tab -> settings cog
2. ✅  Verify the General section title is translated
| | |
| --- | --- |
| ![Screenshot_20250409_153858](https://github.com/user-attachments/assets/7d84ae15-51f7-4b22-8dde-e824b8cfb2cc) | ![Screenshot_20250409_154018](https://github.com/user-attachments/assets/0c4a13f0-1c30-4b67-847f-ef4e9c266e5f) |
=> Adds Greek locale support

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfilePage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Banner.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This PR adds free account banner to the profile tab.
Designs: SzmGxNTLiuwUr2IecE3m07-fi-416_17546
1. Install the app.
2. Go to the profile page.
3. Notice the banner.
4. Tap on the CTA.
5. Sign in or sign up.
6. Go back to the profile.
7. The banner should no longer be there.
8. Sign out.
9. Got back to the profile.
10. The banner should be visible.
11. Go to the beta settings and disable the account creation FF.
12. Restart the app.
13. Go to the profile.
14. The banner should not be there.
15. Go to the beta settings and enable the feature flag.
16. Restart the app.
17. Go to the profile.
18. Dismiss the banner.
19. The banner should not be visible.
20. Restart the app.
21. Go to the profile.
22. The banner should not be visible.
=> Add free account banner to profile page

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AppsFlyerAnalyticsTracker.kt
Internal discussion: p1744280693940599-slack-C08HG81SZGV   
We want to track the application install event. As it's sent before the consent we need to send it to AppsFlyer after the consent has been given. 
2. Tap Allow when asked for consent
3. ✅ Verify in logcat that the event 'application_installed' is sent by filtering for the event name.
```
AppsFlyer analytic event: application_installed properties: {}
[General] ******* sendTrackingWithEvent: application_installed
```
=> Track app install event after consent

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyRenderersFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
Audio session ID is no longer immediately available but only through a callback in a listener. From [the release notes](https://github.com/androidx/media/releases/tag/1.6.0):
> Initial audio session id is no longer immediately available after creating the player. You can use `AnalyticsListener.onAudioSessionIdChanged` to listen to the initial update if required.
1. Play anything.
2. Verify that volume boost still works.
3. Check other effects.
=> Initialize volume boost when audio session ID is available

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/StaffPicksDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/discover/build.gradle.kts, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/util/DiscoverDeepLinkManager.kt, modules/features/discover/src/test/kotlin/au/com/shiftyjelly/pocketcasts/discover/util/DiscoverDeepLinkManagerTest.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
- Supports the deep link for opening discover stuff picks. This will be used for the new Stuff Picks notification that will be implemented in the next PRs: `pktc://discover/staffpicks`
2. In Android Studio terminal, run: `adb shell am start -a android.intent.action.VIEW -d "pktc://discover/staffpicks"`
3. Ensure Stuff Picks screen ✅
=> [Push Notifications Revamp] Support deeplink for Staff Picks

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/profile/accountmanager/PocketCastsAccountAuthenticatorTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/servers/account/SyncAccountTest.kt, app/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModelTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModelTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImplTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImplTest.kt
- Rename `trackUserInteractedWithFeature` to `updateUserFeatureInteraction`
- Updates user interaction for: `Sync`, `Import`, `Up next` and `Theme` feature.
- See the rules: p1744338501260579/1744127181.427989-slack-C08KX131YRJ 
1. Create an account
2. Inspect `user_notifications` database
3. Ensure `interacted_at` was updated for `notification_id = 21483653`
1. Import OPML file
2. Inspect `user_notifications` database
3. Ensure `interacted_at` was updated for `notification_id = 21483654`
1. Add an episode to up next
2. Inspect `user_notifications` database
3. Ensure `interacted_at` was updated for `notification_id = 21483655`
1. Change a theme
2. Inspect `user_notifications` database
3. Ensure `interacted_at` was updated for `notification_id = 21483657`
=> [Push Notifications Revamp] Update user interaction onboarding features part 1

modules/features/discover/src/main/res/drawable/header_text_linear_gradient.xml, modules/features/discover/src/main/res/layout/collection_header.xml, modules/features/discover/src/main/res/layout/item_collection_list.xml, modules/features/discover/src/main/res/layout/podcast_collection_item.xml
- This addresses the feedbacks provided here: p1743011376465069-slack-C08HC6RUH40
- Fixes spaces between podcasts
- Update shadow
- Adds background for header texts
- Align header and podcasts
- I am currently wait for David so we can decide the hexadecimal value for the rectangle background text
1. Go to Discover
2. Check the Guest list section redesign
[Screen_recording_20250402_154810.webm](https://github.com/user-attachments/assets/f6dcb216-44a8-4eec-b8aa-95917d456890)
=> [Guest List and Network Highlight] UI Tweaks

modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelperImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/OnboardingNotificationWorker.kt
- Setup `Trending & Recommendations`, `New Features & Tips` and `Pocket Casts Offers` channel
- Rename `Daily Reminders` channel
2. Open system notification settings for Pocket Casts
3. ✅ Ensure the channels were created
=> [Push Notifications Revamp] Setup remaining notifications channels

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/AccountBenefit.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/AccountBenefitsDialog.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/AccountBenefitsFragment.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/AccountBenefitsPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingAccountBenefitsViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
This PR adds analytics for the account encouragement feature.
Verify these events:
For testing steps you can check these PRs: #3869, #3870, #3871, #3887, #3890
=> Add account encouregement analytics

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
This PR removes podcasts recommendation step from the login flow when starting it from some of the paid features.
Fixes #3774
Verify that going through the upsell flow from these features doesn't offer you podcast recommendations:
- Bookmarks
- Preselect Chapters
- Up Next Shuffle
- Themes
- Generated Transcripts
=> Skip recommendations when upselling from some features

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DownloadsDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculator.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationScheduler.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationSchedulerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculatorTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerTest.kt
- This PR adds the new Re-engagement notifications group that will display notifications if the user does not open the app for more than 7 days and we will keep notifying them every week.
- To archive this, I schedule the notification worker to daily check this and send a notification
- Rules: hVHQ8RgGQf1afBWybZExD2-fi-35_552
- For this PR, we have two types of re-engagement notifications: `WeMissYou` and `CatchUpOffline`
- If the user downloaded episodes and did not play them, we will display the `CatchUpOffline` otherwise we will display the `WeMissYou` 
> [!NOTE]  
> WorkManager’s periodic work is inexact due to battery optimizations. The actual execution may be delayed (in my tests I observed up to ~2 minutes of drift).
- Apply this …
=> [Push Notifications Revamp] Implement Re-engagement notifications

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/CreateAccountDeepLinkTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DownloadsDeepLinkTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculator.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationScheduler.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationSchedulerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/OnboardingNotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/OnboardingNotificationWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculatorTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerTest.kt
- This PR updates the onboarding notifications intent in order to make them to open the correct screen
Originally, notifications were triggered once per day, but I prepared this patch to simplify testing so that they trigger every 10 seconds after the app is installed.
[onboarding-notification-scheduler.patch](https://github.com/user-attachments/files/19777723/onboarding-notification-scheduler.patch)
1. Apply the patch above
2. Install the app
3. Grant notification permission
4. Wait 10 seconds until the first notification being displayed
5. Ensure each notification redirects you to the right screen according to the context ✅
https://github.com/user-attachments/assets/bdcf2fa6-afc2-4b30-a351-da2ed0c9e781
=> [Push Notifications Revamp] Update onboarding notifications intent

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/PodcastListViewModel.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/worker/CuratedPodcastsCrawler.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/categories/CategoriesManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListWebService.kt
Before raising the recommendations change, I have done a small cleanup so I'm not changing multiple methods, for example, an Rx and Coroutine version. 
1. Clean install the app
2. Open the Discover section
3. ✅ Verify the lists load
4. Tap one of the category pills
5. ✅ Verify the page loads
6. Subscribe to podcast
7. Open the podcast page
8. Tap on the Bookmarks tab
9. Tap the Get Bookmarks buton
10. Tap the Upgrade to Plus button
11. Sign up with a new account
12. ✅ Verify the onboarding recommendation lists load
13. Install the Automotive app
14. ✅ Verify the Discover section loads.
=> Refactors Discover feed loading to use coroutines

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/worker/CuratedPodcastsCrawler.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/worker/CuratedPodcastsSyncWorker.kt, modules/features/discover/src/test/kotlin/au/com/shiftyjelly/pocketcasts/discover/worker/CuratedPodcastsCrawlerTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListWebService.kt
The new recommendations are only available in version 3 of the Discover content JSON. This change switches over to the new JSON. Future pull requests will handle the new recommendations lists.
1. Go to the Discover section 
2. ✅ Scroll down and check the "You Might Like" list title is visible
3. Go to Profile -> settings -> Beta features
4. Toggle off Recommendations
5. Restart the app
6. ✅ Check the "You Might Like" list is not visible
| Feature Flag On | Feature Flag Off |
| --- | --- |
| ![Screenshot_20250417_195350](https://github.com/user-attachments/assets/cb140e41-e630-4f0b-a4a3-e0514bd47bd2) | ![Screenshot_20250417_195420](https://github.com/user-attachments/assets/53669582-dfa4-4cbe-a229-f608004feb1d) |
=> Switch to version 3 of the Discover content JSON

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/AvailablePlansPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml
This PR adds weekly price to the offers.
Designs: G22KfZwL1Gv5yyxdTheF9H-fi-1075_9457
> [!note]
> Test this with the debug variant and [this patch](https://github.com/user-attachments/files/19793722/winback.patch) applied.
1. Create a new account and subscribe to any plan.  
2. Go to your account details.  
3. Tap on the cancellation row.  
4. Check available plans.
5. Notice that yearly offers have per week value.
6. Notice that yearly Plus has the best value sticker.
| - | - |
| ![b](https://github.com/user-attachments/assets/fc602434-ffa6-43af-90d9-568b537a9b25) | ![a](https://github.com/user-attachments/assets/23ff3544-7308-45ac-b7ba-479a13297f0d) |
=> Add weekly price to yearly offers during winback flow

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
As title says. 
During my investigation I discovered that the file upload process consits of multiple steps. To call out the most important ones:
- Upload the file itself
- Upload the image (when applicable). The image will be uploaded by using a URL that is unique to the previously uploaded file.
After the sequence completes, we sync files with the server. However at this point the server might not have `ServerFile.imageUrl` property. Image gets uploaded to an aws bucket, and I assume it requires some time until our backend gets notified about the image upload completion. We then overwrote our db record with the data we got from the server -- effectively erased the image from the records. If you refresh the files list after a few seconds, the server will send the image.
I modified the …
=> Fix issue with disappearing file image right after upload completes

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
While testing the Discover section I found an issue that if you tap on the subscribe button on the artwork and then quickly tap the artwork to open the podcast, it can open the podcast page with the podcast as not being followed. After looking into the issue it seems like in the `SubscribeManager` the podcast is being added as followed and unfollowed at the same time. 
I'm really not sure of the best approach to solve this issue. My solution does not download and add the podcast to the database on the podcast page if it is already being subscribed to. It will wait for a second and retry that five times. Please let me know if you have a better solution. 
2. Go to the Discover tab
3. Scroll down to a podcast large list
4. Tap the subscribe button on the artwork and …
=> Handles podcast subscription race condition

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/ArtworkSection.kt
It's been reported that the expanded player won't display player controls while the phone is in landscape.
I traced down the issue to `ArtworkSection` composable, there was a piece of code that incorrectly selected orientation and hence layout configuration. 
The original conditions made sure to select the proper configuration for previews, but since we are running the app on a real device, that code path was never selected.
Fixes #3901 
1. Install and run app on your phone
2. Optional: Connect to headless auto emulator
3. Start playing a podcast episode while your phone is in portrait mode
4. Rotate your phone to landscape (and make sure you've turned off 'lock to portrait' in settings)
| --- | --- |
| ![Screenshot_20250421_142531](https://github.com/user-attachments/as …
=> Respect orientation when laying out artwork and player controls

modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResult.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResultTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/SubscriptionPlansTest.kt
This PR adds data models for Pocket Casts-specific subscription types. There are a few key assumptions:
1. All base plans (Plus Monthly, Plus Yearly, Patron Monthly, Patron Yearly) must be present.
2. A base plan has only a single pricing phase.
Our current code already somewhat assumes this, but it's not explicitly modeled in the types, which makes it harder to manage. The proposed approach makes these assumptions explicit.
I considered creating specific types for offer subscriptions. For example, we expect that Winback offers consist of a single discounted pricing phase followed by the base one. However, I don't believe that's the right approach. I think such specific handling should live in repositories or view models that deal with offer logic. This way, all subscription offers can be …
=> Add subscription types to the payment module

CHANGELOG.md, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextDao.kt
This PR attemts to fix the crash that a user has reported. See [slack](https://a8c.slack.com/archives/C02A333D8LQ/p1745423604825769)
I never managed to reproduce the issue on my end, and to be honest it made me scratch my head.
The reported stack trace looked like this:
```
java.util.NoSuchElementException: Cannot find value for key 87
at androidx.collection.MutableLongIntMap.androidx.collection.LongIntMap.get(SourceFile:122)
c0.MutableLongIntMap.get
at au.com.shiftyjelly.pocketcasts.models.db.dao.UpNextDao$getUpNextBaseEpisodes$suspendImpl$$inlined$sortedBy$1.androidx.compose.foundation.text.selection.SelectionManager$getSelectionLayout-Wko1d7g$$inlined$compareBy$1.compare(SourceFile:45)
```
Checked our code and the `sortedBy` clause had this: `idToPosition[it.uuid]`. The brackets are …
=> Attempt to fix NoSuchElementException crash

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/payment/build.gradle.kts, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResult.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentDataSource.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResultTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/TestLogger.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This PR connects the basic logic of loading subscription plans with the app. Currently, it is only enabled for debug builds to allow testing and verification.
The `PaymentDataSource` interface is an abstraction that, in the real implementation, communicates with the Billing APIs. However, for tests and debug builds, we can use `FakePaymentDataSource` to verify feature interactions.
To simplify the dependency injection logic, I temporarily extracted the public API of the old `BillingClientWrapper` into `PaymentDataSource`. I will remove these methods one by one as I migrate functionality to use the new code.
1. Install `debug` or `debugProd` variant.
2. Open the app.
3. Wait 10 seconds.
4. Check Logcat and filter by `Payments` log tag.
5. You should see fake subscriptions plans. You can …
=> Load subscriptions plans

modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResult.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapper.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResultTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapperTest.kt, modules/services/payment/src/test/kotlin/com/android/billingclient/api/ProductDetails.kt
Continuation of Billing APIs improvements. This PR adds purchase related types and integrations. I also added some improvements to the `PaymentResult` type. Failure type now has enumerated code to improve decision making and `recover()` method to map from failures to other results.
Code review is enough as there's nothing to test yet.
=> Add purchase APIs to the payment module

CHANGELOG.md, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/components/ProductAmountVerticalText.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionProductAmountHorizontal.kt
This PR delivers the first batch of accessibility updates on the Upgrade screen - now secondary texts have better contrast against the background.
[We had a discussion](https://pocketcastsp2.wordpress.com/2025/04/25/eu-accessibility-act-tasks/#comment-7481) on the implementation whether it should be introduced as a local change exclusive to the Upgrade screen or change themes across the app. We ultimatetly agreed on the former one.
Closes #3930 
Just check the code please.
| --- | --- |
| ![Screenshot_20250429_111533](https://github.com/user-attachments/assets/0e7bc874-d0e9-4376-99f0-1bbcbafe093b) | ![Screenshot_20250429_111433](https://github.com/user-attachments/assets/8b148dc7-89a7-497b-947e-21269891c20b) |
- ~[ ] I have considered whether it makes sense to add tests …
=> Increase contrast on Upgrade screen for better readability

modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingFlowRequest.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapper.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapperFlowParamsTest.kt
This PR adds support for finding the correct Billing flow parameters when making purchases through the new APIs. Because `BillingFlowParams` type doesn't implement equality methods I created intermediate `BillingFlowRequest` type. This let me write tests for different scenarios.
There are some assumptions in the code. For example a single purchase doesn't contain more than one products. Also users can have only a single active purchase. This makes sense for our app since we operate only on subscriptions and you should have only a single active one.
Code review the API and tests.
=> Add billing flow parameters mapping

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
This PR adds the `source` property to the Analytics events `purchase_*`.
Internal discussion: p1745971854757569-slack-C06EHRAPW12
1. Use a real device
2. Use the debugProd variant
3. Apply the Git patch file [purchase-test.patch](https://github.com/user-attachments/files/19996212/purchase-test.patch)
4. Sign in with your Google account on your phone that can do test purchases, in the "Google Play - License testing" list
5. Change your phone Pocket Casts account to free
6. Find a place to upgrade, for example settings -> Appearance -> Plus theme
7. Tap "Upgrade to Plus"
8. ✅ Verify the `purchase_successful` event is shown in the logs with the property `"source":"themes"`
https://github.com/user-attachments/assets/0ce76f28-4436-4056-9a52-d17df4c6386c
=> Adds source property to purchase analytic

modules/services/payment/build.gradle.kts, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResult.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PurchaseApprover.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapper.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/TestPurchaseApprover.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapperFlowParamsTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/ServerPurchaseApprover.kt
This is the last major PR before I can begin integrating the new APIs with the existing code. It adds support for launching the billing flow. I retained all of the logic from the current `SubscriptionManagerImpl`, with a few small improvements:
- The purchase event is dispatched only after all purchases are confirmed. While this doesn't affect us much—since our purchases can only contain one item. It is generally safer.
- In some edge cases, there were no purchase confirmations. These events will now be present.
- Pre-existing purchases no longer trigger purchase confirmation events.
Code review the changes.
=> Add billing flow API

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
The analytics event to help us improve the funding button now includes the podcast.
1. Open the podcast page for [The Changelog](https://pca.st/podcast/70d13d50-9efe-0130-1b90-723c91aeae46)
2. Tap the funding button
3. ✅ Verify the analytic event `podcast_screen_funding_tapped` includes the property `podcast_uuid`
=> Adds podcast to funding tap analytics

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModelTest.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentResult.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentDataSource.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/ServerPurchaseApprover.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/winback/WinbackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/winback/WinbackManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SubscriptionModel.kt
This PR replaces the purchase confirmation logic in `SubscriptionManagerImpl` with the new implementation from `PaymentClient`. This isn't the final form, as I plan to remove `Flowable<PurchaseResult>` entirely, but for migration and review simplicity, it's implemented this way for now.
> [!note]
> Apply [this patch](https://github.com/user-attachments/files/20036518/debug-as-prod.patch) when testing.
Test that subscriptions work as expected in the following scenarios:
* Subscribing while creating an account.
* Subscribing with a free account from the account details screen.
* Subscribing from a paid feature.
* Changing the plan during the winback flow — see a [sample test](https://github.com/Automattic/pocket-casts-android/pull/3466).
* Applying the winback flow — this must be tested in …
=> Use payment logic in subscription manager

modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This PR adds the `AcknowledgedSubscription` type to the API. These represent purchases that have been confirmed by both the Billing API and our backend. The main motivation for introducing this type is that the `Purchase` type can include multiple associated products, making it difficult to determine which active subscription a user has. The mapping logic from `Purchase` to `AcknowledgedSubscription` resolves this by filtering out items with multiple products. This is safe in our case because, as the [documentation states](https://developer.android.com/reference/com/android/billingclient/api/Purchase#getQuantity()):
> `public int getQuantity()`
> 
> Returns the quantity of the purchased product.
> Always returns 1 for `SkuType#SUBS` items; could be greater than 1 for `INAPP` items.
Code …
=> Add acknowledged purchases API

CHANGELOG.md, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/components/ProductAmountVerticalText.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionProductAmountHorizontal.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/AutoResizeText.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ClickableTextHelper.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt
This PR attempts to address the issues listed in #3931 
- vertical focus order is mostly correct, you can vertically traverse the main screen elements - title, period selector, subscription tier selector, cta.
- title is now focusable
- CTA focus issues have been adressed
~~However there are still 2 major issues open:~~
~~- Feature card items cannot be selected via keyboard arrows~~
~~- Dislaimer text (with the PP and TNC links) is not selectable~~
Fixes #3931 
1. Open the upgrade screen (Profile -> Settings -> Upgrade to Plus)
2. Enable TalkBack (System Settings -> Accessbility -> TalkBack)
3. Start navigating up and down using the keyboard 
https://github.com/user-attachments/assets/e2ca384a-934c-45c1-be9b-258ef1b57512
~~- [ ] I have considered whether it makes sense to add tests for my …
=> TalkBack improvements

modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentDataSource.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/TestPurchaseApprover.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This simplifies the testing logic of `PaymentClient`. Previously, it was designed to emulate real behavior: we had to launch the purchase flow asynchronously, and while the task was running, we had to emit a set of events like receiving or acknowledging manually. I realized that the previous approach isn't what we really wanted as it would put too much burden on higher-level tests without any real benefit.
This change automates those emissions. While we lose some flexibility in testing, it significantly simplifies the process. We no longer need to spin up a background job to monitor purchases or explicitly emit events. If we want to simulate a failure, we can simply set the appropriate `PaymentResultCode` properties before launching the purchase. By default, without setting anything, we …
=> Simplify payment client testing

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/AvailablePlansPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/OfferClaimedPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackOfferPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/profile/src/test/kotlin/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModelTest.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapper.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/SubscriptionPlansTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapperFlowParamsTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapperTest.kt
This PR rename `SubscriptionBillingCycle` to `BillingCycle`. It is a frequently use type so it makes it a bit easier to use it. The old `BillingCycle` got renamed to `PricingSchedule`. `PricingSchedule` is not really used anything other than determining `BillingCycle` and now it aligns more with naming from the Billing API.
Code review the changes.
=> Rename payment types

modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/Data.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/FakePaymentDataSource.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapper.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/SubscriptionPlansTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/billing/BillingPaymentMapperTest.kt
This PR adds the intro offer that we have configured in the Play Console. I didn't add it earlier because it is at the moment deactivated but it is still used in the existing code and we might switch back to it.
N/A
=> Add missing intro offer configuration

CHANGELOG.md, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptor.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt, modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/CleanAndRetryInterceptorTest.kt, modules/services/ui/build.gradle.kts, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/di/UiModule.kt
We started getting 403s when fetching Buzzsprout images. Our `User-Agent` header was missing. I also fixed an issue in the retry interceptor that didn't account for 304 response codes.
Context: p1746686650407509-slack-C02A333D8LQ
1. Enable in the appearance settings episode artwork.
2. Check that the artwork for [this podcast](https://nodeweb.pocketcasts.com/admin/podcasts/5422321) works.
=> Add "Pocket Casts" User-Agent to image requests

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/AndroidManifest.xml, build.gradle.kts, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt
As the Web Player is migrating to our marketing site, the Web Player share pages are now at pocketcasts.com instead of play.pocketcasts.com. This change fixes it so these pages open the Android app.
1. Open this PR in Chrome and click this link https://pocketcasts.net/podcasts/e6d1eff0-244e-012e-04d4-00163e1b201c
2. ✅ Verify it opens "The Book Review" podcast page
https://github.com/user-attachments/assets/38002e6d-e358-4cf3-b5ea-3b59e679a4a1
=> Adds deep link support for podcast URLs at pocketcasts.com

CHANGELOG.md, app/build.gradle.kts, gradle/libs.versions.toml, wear/build.gradle.kts
Force the use of the latest Datastore library version to address a crash. The issue is the Google Play Console:
`androidx.datastore.preferences.protobuf.InvalidProtocolBufferException.<init>`
<details><summary>Stacktrace</summary>
<p>
```
Exception d5.c: Unable to parse preferences proto.
at androidx.datastore.core.CorruptionException.<init> (CorruptionException.java:25)
at androidx.datastore.preferences.PreferencesMapCompat$Companion.readFrom (PreferencesMapCompat.java:34)
at androidx.datastore.preferences.core.PreferencesSerializer.readFrom (PreferencesSerializer.java:46)
at androidx.datastore.core.okio.OkioReadScope.readData$suspendImpl (OkioStorage.kt:180)
at androidx.datastore.core.okio.OkioReadScope.readData (OkioStorage.kt:1)
at …
```
=> Updates datastore dependency to prevent crashes

CHANGELOG.md, app/build.gradle.kts, gradle/libs.versions.toml, wear/build.gradle.kts
The Datastore library upgrade causes the release build of the app to crash. This change reverts the library change. 
1. Create a release build
2. Try to open the app
=> Reverts datastore dependency

CHANGELOG.md, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/compose/text/ExtensionTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/text/Extension.kt
There's an HTML description that causes the podcast page to crash. It happens because the start of the description has a BR tag that causes the front of the string to have a new line character. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/3993
1. Use the debug variant
2. Search for https://pcast.pocketcasts.net/yap4gwzx
3. Tap on the artwork to open the podcast page
4. ✅ Verify the page doesn't crash
5. Search for https://pcast.pocketcasts.net/embd
6. Tap on the artwork to open the podcast page
4. ✅ Verify the page doesn't crash
=> Fixes podcast description crash

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/HelpViewModel.kt
This PR removes the forums barrier when contacting us as a free user.
See: pdzxoO-E7-p2#comment-630
1. Open the app as an unsigned or a free user.
2. Go to the `Help & feedback` page.
3. Scroll down.
4. Tap `Get in touch` button.
5. Tap `Get support` button.
6. You should be able to send an email.
https://github.com/user-attachments/assets/0eb74518-7f69-4366-9158-f27feb6c040a
=> Redirect free users to e-mail support

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt
Small changes to the podcast page.
See: p1747286334037309-slack-C08DPN79CN8
2. Verify that there is larger elevation of the podcast image.
3. Verify that the podcast image is below toolbar.
| - | - |
| ![Screenshot_20250515-122936](https://github.com/user-attachments/assets/3fa93842-c57d-41c5-a569-ee8dcaf262aa) | ![a](https://github.com/user-attachments/assets/a5aa0ee6-f716-4476-99b7-383f227680b3) |
=> Podcast UI tweaks

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/services/payment/src/main/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClient.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/PaymentClientTest.kt, modules/services/payment/src/test/kotlin/au/com/shiftyjelly/pocketcasts/payment/TestListener.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/payment/AnalyticsPaymentListener.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/payment/LoggingPaymentListener.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/payment/AnalyticsPaymentListenerTest.kt
This PR moves tracking purchase events to a `PaymentClient.Listener`.
Closes #4000
1. Apply this patch.
```
curl -L https://github.com/user-attachments/files/20201283/debug-as-prod.patch | git apply
```
2. Install the app.
3. Start purchase flow.
4. Verify `purchase_cancelled` event by dismissing the Play Store confirmation sheet.
5. Verify `purchase_failed` event by using error test purchase card.
6. Verify `purchase_successful` event by completing a purchase.
=> Centralize purchase tracking

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheetFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingLauncher.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
While working on streamlining Smart Folders after Onboarding I had to launch the Onboarding for result from a fragment. However, we don't have any APIs to do that. While closing #3967 requires more work I wanted to add this change to minimize future PR.
Smoke test creating an account.
=> Add Onboarding launch intent

.buildkite/commands/assemble-release-apk.sh, .buildkite/commands/diff-merged-manifest.sh, .buildkite/commands/lint.sh, .buildkite/commands/prototype-build.sh, .buildkite/commands/run-instrumented-tests.sh, .buildkite/commands/run-unit-tests.sh, .buildkite/commands/should-skip-job.sh, .buildkite/pipeline.yml, .buildkite/shared-pipeline-vars
Internal reference: paaHJt-7Ss-p2
The main goal of this PR is to optimize the wait time for PRs with minor, non-code related changes, specially the ones related to the release process.
I've updated the original script to cover build, validation and localization jobs:
- `should-skip-job.sh --job-type [build|lint]`: skips if the changes are limited to documentation, tooling, metadata, etc
- `should-skip-job.sh --job-type validation`: same as above, but also skip on localization changes. The idea is that it can be valuable to run things as a Prototype build when localization changes
I've created the PR https://github.com/Automattic/pocket-casts-android/pull/4009 to test a few scenarios skipping jobs:
- App version bump: https://buildkite.com/automattic/pocket-casts-android/builds/11842
- ++ …
=> [Tooling] Skip jobs if there are no relevant code changes

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Tooltip2.kt
This change adds the tooltip component. It's not used anywhere at the moment and it is named `Tooltip2` because we still have a mixed bag of old ones. I'll also need to add an API that allows using the current `Tooltip2` as a popup component.
Designs: gsO93aLSqOtaUQnlNKUVZmC7-fi-4185_7143
Verify if previews match the designs.
=> Add tooltip component

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/podcast/RecommendationsHandler.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/podcast/RecommendationsHandlerTest.kt
This resolves the issue of the podcast page search not functioning when there was a problem with the recommendations list. This problem was seen when the call to retrieve the recommendation list was timing out, and since this occurred after the search and before the UI state update, it caused the page updates to take a long time. This change separates the recommendations list call so that any changes to the page, such as the episode search or toggling the podcast to show or hide archived episodes, do not depend on the recommendations. 
Check that the logic is separate from the recommendations list do the following: 
1. Filter logcat by `/recommendations/podcast/`
2. Open a podcast page 
3. ✅ Verify there is a server call to get the list
4. Tap the "Show archived" button
5. ✅ Confirm there …
=> Refactor recommendations handling in PodcastViewModel

modules/features/discover/src/main/res/layout/row_podcast_large_list_with_podcast.xml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/podcast/RecommendationsHandler.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/podcast/RecommendationsHandlerTest.kt, modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/LocaliseHelper.kt, modules/services/localization/src/main/res/values/strings.xml
This pull request includes the following changes:
1. On the podcast page, if the category list is used, then the current podcast is filtered. 
p1747280739738859/1747280730.317709-slack-C08FYE3MUGN
2. Changes translation from "If you like" text to "Because you follow". 
p1747212809024149/1747207915.288179-slack-C08FYE3MUGN
3. Keeps the list title to one line and makes sure it doesn't overlap the show all button.
p1747275520818429/1747207676.004529-slack-C08FYE3MUGN
Testing number 1.
1. Use the variant "debugProd"
2. Change the region on the Discover page to "Australian"
3. Open the [Mushroom Case Daily](https://pca.st/mushroom) podcast page
4. Tap the "You might like" tab
5. ✅ Verify the podcast doesn't appear in the recommendations
Testing number 2 and 3.
Apply [this …
=> Recommendation list title improvements and remove current podcast

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Tooltip.kt
This fixes tooltip positioning around the anchor. In the last PR I only did it for the `TopStart` position and forgot to do it for the other ones.
1. Apply [this patch](https://github.com/user-attachments/files/20281992/tooltip-playground.patch).
```
curl -L https://github.com/user-attachments/files/20281992/tooltip-playground.patch | git apply
```
2. Go to the Settings.
3. Tap the Developer row.
4. You should see the tooltip playground.
5. Move sliders to change the anchor size.
6. Select option to change the tip position of the tooltip.
7. At all times tooltip should be centered around the anchor.
=> Position tooltip correctly based on its tip

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/account/build.gradle.kts, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivityContract.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModel.kt, modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingExitInfo.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt
This change removes the need to tap the Smart Folders action after completing the onboarding flow.
There are some existing issues you might encounter that are unrelated to these changes but pertain to applying Smart Folders in general:
- When a user who already has folders signs in, Smart Folders may not apply due to a race condition between account sync and new folder creation.
- When a user who already follows some podcasts signs in, podcasts they previously followed but that are not recognized locally won’t be added to folders. This happens because the Smart Folders flow is not dynamic. New podcasts may appear after sign-in that weren't accounted for during the initial flow launch.
Closes: #3967
> [!note]
> I recommended to start each test with a fresh installation / cleared data to …
=> Streamline Smart Folders onboarding flow

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/LargeListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/SmallListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/PodcastListViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsParameter.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTrackerExtensions.kt
To help improve the recommendations, this change includes the list date in the analytics. We are using the date of the recommendation lists as a version so we can tell if changes are helping. 
- Filter logcat by `list_datetime`
- Login with a Pocket Casts account that you have history on so you get recommendations
- Go to the Discover tab
- Scroll down to "You Might Like"
- Tap on the artwork follow button 
- ✅ Verify the event `discover_list_podcast_subscribed` with the properties `list_id`, `list_datetime`, and `podcast_uuid`
- Tap on the artwork to open the podcast page
- ✅ Verify the event `discover_list_podcast_tapped` with the properties `list_id`, `list_datetime`, and `podcast_uuid`
- Tap the follow button
- ✅ Verify the event `discover_list_podcast_subscribed` with the properties …
=> Recommendation run analytics

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEmptyState.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt, modules/features/player/src/main/res/layout/fragment_upnext.xml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/EmptyListViewHolder.kt, modules/features/podcasts/src/main/res/layout/fragment_profile_episode_list.xml, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt, modules/features/profile/src/main/res/layout/fragment_cloud_files.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/EmptyState.kt
This PR adds a secondary CTA to the empty state component and cleans things up a little bit. I removed embedded vertical padding from the component itself. Having it there makes it more difficult to position it correctly.
Design: 2MA6Bz3Vi36BOhuR9pitCU-fi-50_7563
This also includes some updates to the empty states of the Cloud Files and Bookmarks screens. On the Cloud Files screen, I centered the empty state. On the Bookmarks page, I made some minor improvements to the background colors and positioning. It’s not ideal, but I can't do a full overhaul of the Bookmarks page at the moment.
Check the component preview and verify it with the designs.
| Bookmarks before | Bookmarks after | Files before | Files after |
| …
=> Add secondary button to the empty state.

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This pull request enables the new sorting option for podcasts "Recently played".
1. Install the release variant
```
./gradlew app:assembleRelease
adb install -r app/build/outputs/apk/release/app-release.apk
```  
2. Go to the Podcasts tab
3. ✅ Check the new "Sort by" option "Recently played" is visible and works
=> Enables Recently Played sorting option for podcasts

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextNoContentBanner.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoMatchingBookmarksBanner.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/EmptyListViewHolder.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/NoContentBanner.kt, modules/services/localization/src/main/res/values/strings.xml
Small tweaks to the empty state:
- Rename `EmptyState` to `NoContentBanner`. I think using "state" for the UI component is misleading as state types are typically data types.
- Rename subtitle parameter to body to align with Figma designs.
- Improve ripple color to make it visible in contrast themes.
- Capitalize "podcast" string to match other action buttons.
=> Empty state tweaks

CHANGELOG.md, app/build.gradle.kts, gradle/libs.versions.toml, wear/build.gradle.kts
This change attempts to upgrade the DataStore library to prevent one of the app's most common crashes. We tried this with version 1.1.6 in the PR https://github.com/Automattic/pocket-casts-android/pull/3982 but it was later found that it crashes the release build. I have tested 1.1.7 with a release build and the release notes contain the following:
> Fixed missing Proguard rules issue in the Android artifact of datastore-preferences-core. ([3f3f6e](https://android-review.googlesource.com/#/q/3f3f6ecadb0f3beb755a27fb5859e238e81b7ea3), [b/413078297](https://issuetracker.google.com/issues/413078297))
Although I haven’t been able to reproduce the crash, the issue appears related to the DataStore usage in the Glance widget and Horologist libraries. Please focus testing on widgets and Wear OS …
=> Updates DataStore dependency to prevent crashes, attempt 2

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/util/DiscoverDeepLinkManager.kt, modules/features/discover/src/test/kotlin/au/com/shiftyjelly/pocketcasts/discover/util/DiscoverDeepLinkManagerTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsScreen.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/components/NotificationPreferenceCategory.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/data/NotificationFeaturesProvider.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/data/NotificationsPreferencesRepositoryImpl.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/model/NotificationPreferenceType.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/settings/NotificationsPreferencesRepositoryImplTest.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/settings/NotificationsSettingsViewModelTest.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModelTest.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculator.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelperImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationScheduler.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationSchedulerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationWorker.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculatorTest.kt
This PR adds the `Trending & Recommendations` category to the notification settings screen and schedules 2 notifications a week when the app is launched or when the `Notify me` toggle is enabled.
Also included some improvements:
- Advanced settings rows now properly route to the given notification channel's setting screen
- `RecommendationDeepLink` now properly routes to `recommendations_user_podcast` list
1. Apply
[this patch](https://github.com/user-attachments/files/20383979/show_trending_and_recommendations_in_10_sec.patch) to make notifications appear in 10 seconds
2. Build and install the app, make sure `Notifications revamp FF is ON`
3. Allow notifications!
4. Enable Trending and Recommendations category on the Notification Settings (Notify me -> ON!)
5. Wait for 10 seconds
6. Tap …
=> [Notifications Revamp] Trending and Recommendations

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
During coroutines migration I didn't account for the drag & drop state which is kept separately from the UI state. This fixes it by applying the previous solution of updating the `adapterState` with each new UI state. Ideally this would be a part of the UI state but I don't want to make too many changes in a beta fix.
1. Follow some podcasts.
2. Go to the podcasts tab.
3. Ordering podcasts by drag & drop should work.
=> Fix podcasts drag & drop

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/podcast/RecommendationsHandler.kt, modules/features/podcasts/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/podcast/RecommendationsHandlerTest.kt
Podroll recommendations were ignored when they were the only recommendations.
Internal ref: p1748447347766299-slack-C028JAG44VD
1. Open [Podcasting 2.0 podcast](https://pca.st/s7qtomm0).
2. Go to "You might like" tab.
3. You should see its Podroll.
=> Fix displaying podroll podcasts when it's the only recommendation

.buildkite/commands/should-skip-job.sh
We should run build checks in cases of Gradle wrapper or dependencies changes.
=> Do not skip CI checks when only Gradle changes are present

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
In the latest beta `7.90-rc-2` I noticed a crash on `PodcastsFragment.showTooltip`:
https://a8c.sentry.io/issues/6634171842/?project=6711064&query=release%3Aau.com.shiftyjelly.pocketcasts%407.90-rc-2%2B9342&referrer=release-issue-stream
It seems like a timing issue, posting a `Runnable` to invoke `showTooltip` on the `binding.toolbar` may be called after `onDestroy` so the `realBinding` reference is cleared.
I have removed the `post` call because we're on the main thread anyways.
Fixes #4057 
1. Apply this patch  [show_tooltip.patch](https://github.com/user-attachments/files/20503340/show_tooltip.patch)
2. Build and install the app
3. Select the podcasts tab
- ~[ ] If this is a user-facing change, I have added an entry in CHANGELOG.md~
- ~[ ] I have considered whether it makes sense to …
=> Don't post showTooltip task

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/data/NotificationsPreferencesRepositoryImpl.kt, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculator.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationSchedulerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculatorTest.kt
This PR is the last step of the notifications revamp project, putting all the missing pieces into their places.
- Reengagement notifications are scheduled to repeat every 7 days (when applicable)
- Enable all notifiactions by default
- Properly schedule notifications
- Update notifications setting screen order of categories
- Track event when the notification banner cta is tapped
Just check the code please
- ~[ ] If this is a user-facing change, I have added an entry in CHANGELOG.md~
- ~[ ] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`~
- ~[ ] Any jetpack compose components I added or changed are covered by compose previews~
- ~[ ] I have updated (or requested that someone edit) [the …
=> [Notifications Revamp] Missing pieces and changes

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PlayerColors.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PodcastColors.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Theme.kt
This PR adds a `PlayerColors` type. I need it to contextualize ad colors that can be displayed either in our regular UI or in the player. Since the player uses its own theming, I need access to the appropriate colors—and we don’t currently have anything like that in our theme type. I’ve decided to introduce a new `CompositionLocal`. If `LocalPodcastColors` is present, then `PlayerColors` will be available. This allows to dynamically update the colors and their availability when needed.
Code review and green CI.
=> Define player colors

modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/InMemoryFeatureFlagRule.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/di/FirebaseModule.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/FeatureFlag.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/FeatureProvider.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/FeatureFlagTest.kt
This PR allows to observe feature flags via `Flow`. I need it to properly support ads feature detection in the player as I'm running into some edge cases which block my progress without doing a lot of work.
1. Apply [this patch](https://github.com/user-attachments/files/20606727/firabase-test.patch).
```
curl -L https://github.com/user-attachments/files/20606727/firabase-test.patch | git apply
```
2. Install `debugProd` variant.
3. Open Logcat and filter by `Testing` tag.
4. Notice `TEST_FREE_FEATURE enabled: true` log.
5. Go to the Firebase Remote config and modify `test_free_feature` key. Publish the changes.
6. Wait 10 seconds.
7. You should see`TEST_FREE_FEATURE enabled: <value>` in the Logcat.
8. Repeat steps 5-7 a couple of times to verify updates.
=> Allow to observe feature flags

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/BannerAdAdapter.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/ad/AdBanner.kt
Internal ref: p1749068013674719-slack-C08U02AG7C5
1. Use a tablet.
2. Open the app as a free user.
3. Go to the podcasts tab.
4. Notice that the ad doesn't stretch across the whole screen.
| - | - |
| ![Screenshot_20250605_110428](https://github.com/user-attachments/assets/b01cbf41-8546-430a-950c-90c8befcbd94) | ![Screenshot_20250605_110647](https://github.com/user-attachments/assets/ef9f7fac-8642-4742-a7c1-3520127bf803) |
=> Make AdBanner at most 400dp wide

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModelTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/PodcastColors.kt
This includes ads in the player UI.
Designs: aVoIMJy9cdDZzNloBIv9jr-fi-1_1684
1. Open the app as a free user.  
2. Add something to the queue.  
3. Navigate to the Player.  
4. You should see an ad.  
5. Tap the ad.  
6. You should be redirected to the ad's destination link.  
7. Go to **Beta Features** and disable the *Banner Ads* feature flag.  
8. Return to the Player.  
9. You should no longer see ads.  
10. Go to **Beta Features** and enable the *Banner Ads* feature flag again.  
11. Sign in as a free user.  
12. You should still see the ad in the Player.  
13. Sign in as a **paid** user.  
14. You should **not** see the ad in the Player.
| Podcast episode | Custom file | Animation |
| - | - | - |
| ![ep](https://github.com/user-attachments/assets/6c819f1a-448d-4e02-b2b7-abf3843896cd) …
=> Display ads in the player

modules/features/transcripts/build.gradle.kts, modules/features/transcripts/src/main/kotlin/au/shiftyjelly/pocketcasts/transcripts/TranscriptEntry.kt, modules/features/transcripts/src/main/kotlin/au/shiftyjelly/pocketcasts/transcripts/ui/TransciptLines.kt, modules/features/transcripts/src/main/kotlin/au/shiftyjelly/pocketcasts/transcripts/ui/TranscriptColors.kt, settings.gradle.kts
In order to support transcripts in the episode view we need to decouple them from the player. Currently all the code lives in the player's module and uses things like `ShelfSharedViewModel`. This is a first PR that simply adds component to display transcript lines.
=> Add transcripts module

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscripSanitization.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptSanitizationTest.kt
This PR adds transcript sanitization logic. Currently, it addresses the following issues:
- Excessive white space in the text.
- Sentences split across multiple entries. Transcripts can appear like the example below. We need to detect and concatenate such strings to improve readability. Some logic for this already exists, but it is as exhaustive and isn't applied across all types of transcripts.
```
Some start of a sentence
that is continued here. But now we have a new one
That goes here. So what should we do? We need to join them.
```
- Grouping utterances by the same speaker. This works in combination with sentence detection.
- Filtering out empty entries.
> [!note]
> Sentence detection heuristics aren't perfect, as they don't account for characters like the [Japanese Full …
=> Add transcript entries sanitization

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/TranscriptDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Transcript.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/TranscriptType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptParser.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/TranscriptsManagerImplTest.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptManagerTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/TranscriptService.kt
Currently, the transcripts API requires ping-pong calls, which are handled in `TranscriptsViewModel`. This responsibility should reside in lower layers such as repositories or managers. This PR introduces improved transcript management logic. I haven’t integrated it yet to keep the code review surface minimal, but I will do so in the next PR.
The new `TranscriptManager` offers several advantages over the current implementation:
- Encapsulates all loading logic, including selecting the most appropriate transcripts.
- Caches the 20 most recent processed transcripts using an `LruCache`.
- Applies transcripts sanitization.
- Contains well-tested logic.
=> Add new transcripts loading logic

CHANGELOG.md, app/src/release/AndroidManifest.xml, modules/services/localization/src/release/res/xml/backup_scheme.xml, modules/services/localization/src/release/res/xml/extraction_rules.xml
Slack thread: p1749613256594919-slack-C02A333D8LQ
Previous attempt: [pr](#4031) 
This is yet another attempt to fix the crash that happens around `glance` or `horologist` when they're trying to backup their saved preferences.
It is clear that those two libraries define `androidx.datastore` as dependency, we've explicitly added datastore to our project with its latest version `1.1.7` so those libraries will use this version as well. However, it seems that didn't do the trick.
The [deobfuscated stacktrace](https://a8c.sentry.io/issues/6643782109/events/6f8796de3c4e4098bed36edb71b76e09/?query=) isn't too telling either, the component where the crash comes from is called `h5.PreferenceDataStoreFactory`.
My next best guess was to start looking around how backup works on Android since some …
=> Update extraction rules for Android 12 and above

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
Remove the bottm padding on the episodes list when no episodes are visible
Fixes #4030
1. Follow a podcast
2. Open the podcast page
3. Tap the three dots next to "Seach episodes"
4. Tap "Archive all"
5. Scroll down the page
Notice the large padding described in the issue is not present anymore
=> Remove bottom padding with empty episode list

modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/TranscriptFragment.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/ui/Toolbar.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/ui/TranscriptPage.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
This adds ability to play and pause transcripts from the episode details transcript.
Designs: tzuqhOmpPVu5TjKK1XMhf5-fi-939_7392
I'll update changelog if this gets merged to a different milestone than #4143.
1. Open episode details with a transcript.
2. Tap on the transcript excerpt.
3. In the transcript sheet tap on the play/pause button.
4. The playback of the episode should act accordingly.
https://github.com/user-attachments/assets/4e9f18d0-e462-4bcf-adec-e4785b5a90c9
=> Add play/pause buton to transcript page

CHANGELOG.md, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
A user has reported a crash that occurs after unfollowing a podcast. A requirement is to have many podcasts followed.
We faced a similar issue before (#1589). After a short reading, it turns out that the Sqlite driver has a limit of 2MB that a Cursor can hold.
A possible solution is to treat large queries as transactional queries, so cursors can be swapped.
I simply added `@Transaction` to the podcast `@Query`s that may result large set of results and that seemingly solved the issue, at least I was never able to repro again when playing the scenario described in the testing instructions.
Fixes #4139 
1. Import [podcasts_opml.txt](https://github.com/user-attachments/files/20887409/podcasts_opml.txt)
2. Once everything settled, go to Podcasts tab
3. Select and show and unfollow it
4. Repeat …
=> Add `@Transcation` to podcast queries that might get too large

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/ArtworkImage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/ArtworkOrVideo.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/ad/AdBanner.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/AnimatedNonNullVisibility.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Float.kt
Currently when there is very limited space vertical player doesn't look great. This PR address it by changing artwork's corner radius if artwork is small, hiding artwork when there is no space for or it would look bad, and decreasing font scaling of text on ads.
Test player with various font sizes on a small device.
| - | - |
| ![a1](https://github.com/user-attachments/assets/2e69b6dc-3c61-4671-8395-a2f869ec9c01) | ![b1](https://github.com/user-attachments/assets/52778815-7650-434c-afe5-f3d528ad2a26) |
| ![a2](https://github.com/user-attachments/assets/517c18d0-bfd5-4638-ad5b-5f980eb5d158) | ![b2](https://github.com/user-attachments/assets/d0391114-c4a9-4cfe-ba68-f3f92cd465aa) |
| ![a3](https://github.com/user-attachments/assets/75d6a8fa-b1ab-4ec1-8777-aea333950984) | …
=> Imporve vertical player experience on smaller devices

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/notifications/EnableNotificationsPromptFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
Fixes #4160
1. Start the app and do not give notification permission.
2. Go to the podcasts tab.
3. Drag down the notifications prompt.
4. Go to another tab.
5. Go back to the podcasts tab.
6. Notifications prompt should not appear.
7. Clear app's storage data.
8. Start the app and do not give notification permission.
9. Go to the podcasts tab.
10. Tap the X button.
11. Go to another tab.
12. Go back to the podcasts tab.
13. Notifications prompt should not appear.
14. Clear app's storage data.
15. Start the app and do not give notification permission.
16. Go to the podcasts tab.
17. Tap "Allow Notifications".
18. Do not grant permission.
19. Go to another tab.
20. Go back to the podcasts tab.
21. Notifications prompt should not appear.
=> Fix notifications prompt showing too often

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/compose/PodcastRow.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CollectionListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt, modules/features/discover/src/main/res/layout/collection_header.xml, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/EpisodeTitles.kt
The scaling of the image for the guest lists and network highlight wasn't working correctly. I figured out it is related to the placeholder image being a different aspect ratio. I have removed the placeholder for this image view as it isn't square. I did try setting the image size, but we usually deal with a square image, and it was starting to get complicated. Please let me know if there's a different way you'd like me to approach this.
This change also fixes the issue with the title and author placeholder text being displayed.
Fixes https://github.com/Automattic/pocket-casts-android/issues/4158
1. Use the debugProd variant
2. Open the Discover tab
3. Scroll down to the Network Highlight
4. ✅ Verify the image looks correct
| --- | --- |
| …
=> Fixes Discover collection image scaling

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeScreen.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This PR adds the FF and conditionally renders the frame of the new screen.
It's worth noting that the screen is not functional at this point, I only included the main elements like the header, scrolling content, and the footer.
All the data you'll see on it is hardcoded.
Designs: PviUP0aiZctOprDuuYRwpb-fi-4999_5992
1. Make sure `new_onboarding_upgrade` FF is ON
2. Tap the Settings -> Pocket Casts Plus to navigate to this new screen
=> [Onboarding] Upgrade Screen skeleton

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextQueueTest.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoPlaySource.kt, modules/services/preferences/src/test/kotlin/au/com/shiftyjelly/pocketcasts/preferences/model/AutoPlaySourceTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
Update to Kotlin `2.2.0` changed initialization order of `object`s. Previously `AutoPlaySource.None` was initialized before `companion object`. Now it happens after. This caused an issue because `None` was resolved to `null` causing a crash.
There might be other classes and properties defined like this but I couldn't find any.
1. Open app.
2. Go to filters.
3. App should not crash.
=> Make AutoPlaySource constants lazy

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/UpgradeFeatureItem.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/UpgradeTrialTimeline.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeScreen.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt, modules/services/localization/src/main/res/values/strings.xml
Next step of the saga, connecting the dots. Just not on the data level... yet.
This PR adds new capabilities to the previously introduced `OnboardingUpgradeScreen`.
Now it's able to display the desired content, altough it still uses hardcoded data.
Another improvement is that now it can receive a new argument, `Variants` that is an enum type and meant to represent the A/B experiment options.
You can control how 
Designs: PviUP0aiZctOprDuuYRwpb-fi-4999_5992
Fixes https://linear.app/a8c/issue/PCDROID-14/implement-generic-upgrade-screens
1. Make sure `new_onboarding_upgrade` is ON
2. Settings -> Pocket Casts Plus
3. Test the app on smaller devices and etc.
4. Apply this patch and rebuild the app: [variant_b.patch](https://github.com/user-attachments/files/21110053/variant_b.patch)
5. Repeat …
=> [Onboarding] Connect screen content

CHANGELOG.md, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/activity/WebViewActivity.kt
Our `WebView` configuration caused infinite deep linking to a clip resource because of launching a new Activity every time we received an URL. `pca.st` redirected to `pocketcasts.com` allowing to skip check for the same URL.
1. Open a clip link like `https://pca.st/episode/9adc6b43-7b23-4a0e-b2bc-7ed7922bdc6e?t=15,51.6` in the `debugProd` or the `release` app.
2. You should see the Web player with a clip.
=> Fix clips link causing infinite deep linking

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationWorker.kt
There's a bug in our notification display logic, so `OnboardingNotificationType.PlusUpsell` notifications are still being displayed even if the user has already subscribed.
This PR addresses that issue.
Fixes https://linear.app/a8c/issue/PCDROID-29/upsell-notification-still-showing-when-the-user-is-subscribed
1. Apply this patch and build the app
[notifications.patch](https://github.com/user-attachments/files/21143063/notifications.patch)
2. Grant notifications permission when prompted
3. Sign in with an account that doesn't have an active subscription
4. Navigate to Settings->Notifications
5. Disable then enable 'Pocket Casts Offers' toggle
6. Wait for 5 seconds
7. Dismiss the notification
8. Now disable and enable 'Daily reminders' toggle
9. Now gift yourself a sub on the admin page and …
=> Fix upsell notification display criteria

CHANGELOG.md, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, app/src/main/res/layout/activity_main.xml, modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/ActivityDelegate.kt, modules/features/navigation/src/main/java/au/com/shiftyjelly/pocketcasts/navigation/BottomNavigator.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/component/BottomNavigationView.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/View.kt
This PR improves the handling of window insets on older Android versions. Material's `BottomNavigationView` applies the bottom inset automatically, but it's not reliable with our UI configuration. I replaced it with a custom view that is more or less a copy of Material's component, but without the inset application. Instead, I apply the insets manually in `MainActivity`.
I also changed the hidden player's visibility from `gone` to `invisible`. I'm not entirely sure why, but when it's set to `gone`, the window insets don't update correctly the first time we change visibility, leading to missing insets in the player UI.
Fixes #4209
1. Test player on a device with SDK 29. System navigation bar should not obstruct our navigation tab or player's shelf.
2. Do the same test with a newer SDK.
| …
=> Improve window insets handling on Android pre SDK 30

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/UpgradeTrialTimeline.kt
This PR adds small touches to `UpgradeTrialTimeline` as we have clarified some design questions: p1752052567390479-slack-C0932TFPUDC
1. Make sure `new_onboarding_upgrade` FF is ON
2. Navigate to Settings -> Pocket Casts Plus to see the new onboarding screen
3. Tap the 'How does the free trial work?' cta or just scroll vertically
4. Check screen
| --- | --- | 
| <img width="291" height="300" alt="Screenshot 2025-07-14 at 14 53 57" src="https://github.com/user-attachments/assets/4fd4bed1-9d8d-4bef-9a7b-c40f16c26a37" /> | <img width="291" height="355" alt="Screenshot 2025-07-14 at 14 53 33" src="https://github.com/user-attachments/assets/b1f71e17-6844-4c7a-b109-9b038c349da0" /> |
=> Update timeline component design

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
Episode details can have forced dark theme. I didn't account for it when styling the transcript banner.
1. Have device theme set to a light one.
2. Add some episodes with transcripts to Up Next.
3. Open Up Next.
4. Tap on an episode in the queue.
5. The transcript banner should use dark theme.
| - | - |
| <img width="1080" height="2400" alt="Screenshot_20250716-084855" src="https://github.com/user-attachments/assets/eb30551c-9899-4afa-b2c6-dc65fc84aab9" /> | <img width="1080" height="2400" alt="Screenshot_20250716-084812" src="https://github.com/user-attachments/assets/5c5452de-e32e-4d29-b04d-e3c5324291d3" /> |
=> Use correct activeTheme for transcript banner

CHANGELOG.md, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
This PR fixes icon color of the feature items on the upgrade banner that appears on your Account page.
| --- | --- | 
| <img width="1080" height="2400" alt="Screenshot_20250717_213140" src="https://github.com/user-attachments/assets/9e12be0d-804f-4643-a0d3-c0164d74fb51" /> | <img width="1080" height="2400" alt="Screenshot_20250717_213100" src="https://github.com/user-attachments/assets/a8012ccf-fb4a-4a78-8c66-b140f0f2593f" /> |
Just review pls.
=> Fix icon color on feature item on profile upgrade banner

modules/features/filters/build.gradle.kts, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsOnboardingFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsWorker.kt
This adds skeleton UI and logic for showing playlists onboarding.
1. Checkout previous version of the app.
```
git checkout 7.92
```
2. Install previous version of the app
3. Open the app.
4. Checkout this branch.
```
git checkout task/playlist-onboarding
```
5. Install the app.
6. Open the app.
7. Go to the Playlists page.
8. You should see the bottom sheet with onboarding.
9. Close the app.
10. Open the app.
11. Go to the Playlists page.
12. You should not see the onboarding.
13. Close the app.
14. Clear the app's data.
15. Open the app.
16. Go to the Playlists page.
17. You should not see the onboarding.
=> Add Playlists onboarding support

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SmartRules.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/SmartRulesTest.kt
This PR introduces the `SmartRules` type. Currently, the logic for mapping rules to SQL `WHERE` clauses resides in `SmartPlaylistManagerImpl`:
https://github.com/Automattic/pocket-casts-android/blob/1af3fb7b371d4c920e467707b465406bc94877b0/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImpl.kt#L383-L529
However, this code is untested, making it difficult to detect regressions. This may become an issue as I continue working on filters.
This PR does not yet integrate the new code with the existing one For now, review the `SmartRules` API.
=> Add SmartRules type

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastRefresherImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartSmartPlaylistManagerImplTest.kt
Podcasts like the "The Louis Theroux" podcast list the file size at 0 bytes in the [feed XML](https://feeds.megaphone.fm/GLT1948741183). 
```
<enclosure 
url="https://traffic.megaphone.fm/GLT1154972783.mp3?updated=1750753094" 
length="0" 
type="audio/mpeg"/>
```
There are a few podcasts that do this, and it means we can't list the download file size. However, it will be listed after the file has been downloaded. The issue is that the size is getting wiped when we try to update the podcast information from the server. It might be enough to ignore the new size if it's zero or if the episode has already been downloaded.
1. Subscribe to a podcast that doesn't list the episode file sizes in the XML. Such as [Scott Sigler's Galactic Football League (GFL) Series](https://pca.st/djJO). 
2. Open …
=> Fix missing file sizes on episode page

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistPreviewRow.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds swipe to delete interaction to playlists.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-767_40373
1. Start the app. Do not sign in to avoid any syncing issues due to fake data.
2. Execute this query in the Database Inspector.
```sql
INSERT INTO smart_playlists ('_id', 'uuid', 'title', 'sortPosition', 'manual', 'unplayed', 'partiallyPlayed', 'finished', 'audioVideo', 'allPodcasts', 'podcastUuids', 'downloaded', 'downloading', 'notDownloaded', 'autoDownload', 'autoDownloadWifiOnly', 'autoDownloadPowerOnly', 'sortId', 'iconId', 'filterHours', 'starred', 'deleted', 'syncStatus', 'autoDownloadLimit', 'filterDuration', 'longerThan', 'shorterThan', 'draft') VALUES
(100, "uuid-100", "Filter 100", 100, 0, 1, 1, 1, 0, 1, NULL, 1, 1, 1, 0, 0, 0 ,0, 23, 744, 0, 0, 1, 10, 0, 20, 40, 0),
(101, …
```
=> Add swipe to delete playlists

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/ThemedTopAppBar.kt, modules/services/localization/src/main/res/values/strings.xml
This PR adds empty state to playlists page.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-920_43443
Closes: #4212
1. Install the app.
2. Delete all your playlists.
3. You should see the empty state.
=> Add playlists empty state

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/SmartPlaylist.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/PlaylistEpisodeSortType.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SmartRules.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/SmartRulesTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistUpdateAnalytics.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImpl.kt
This PR removes the code related to the system downloads filter. After gaining a deeper understanding of the filters code, I see no reason for this filter to exist.
https://github.com/Automattic/pocket-casts-android/blob/70a92539eb625bac9d48ab4b84b17825e7d7e89f/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImpl.kt#L543-L560
This filter was created in-memory on demand and was never persisted. Moreover, its rules were never applied anywhere. It was only used as an identifier in the `PlaybackService` to locate downloaded episodes. The logic was unnecessarily convoluted. Removing the filter also allowed us to remove the `LastDownloadAttempt` sorting type.
https://github.com/Automattic/pocket-casts-android/blob/70a92539eb625b …
=> Remove system downloads filter

.buildkite/commands/lint.sh, .buildkite/shared-pipeline-vars
So the results are not overwritten.
Relates to: AINFRA-943
This PR is a follow up to #4236 . After this PR, Lint results from `wear` module started overwriting these from `app` and `automotive`. This PR fixes the problem by providing `category` when uploading the `sarif` file. 
Implementation details: https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/183.
Lint is failing but not because of this PR: it'll be fixed in #4260
Compare [main results](https://github.com/Automattic/pocket-casts-android/security/code-scanning) and these from [this PR](https://github.com/Automattic/pocket-casts-android/security/code-scanning?query=is%3Aopen+pr%3A4265).
=> Specify category when uploading `sarif` files

CHANGELOG.md, modules/services/localization/src/main/res/values/strings.xml
This change improves the "Trending this week" notification message.
1. Go to Profile -> Settings -> Developer -> Notifications testing
2. Change the "Select notification type" to trending
3. Tap "Fire now"
4. ✅ Verify the notification text looks correct
| --- | --- |
| ![Screenshot_20250724_073850_One UI Home (1)](https://github.com/user-attachments/assets/cc5ed911-08eb-4a6e-abe8-bcecd067e770) | <img width="1080" height="433" alt="Screenshot_20250724_120349" src="https://github.com/user-attachments/assets/82d3e656-5732-4e81-8154-0884fcba5c37" /> |
=> Fixes notification message

CHANGELOG.md, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/TopScrollable.kt
Allows the user to open the podcast search quickly by tapping the Discover navigation button when the Discover page is already displayed. This is a common feature in Android apps like Google Photos, Play Store, and Immich that I miss when using Pocket Casts.
I am curious if the analytics source should be different, though technically it is launched from Discover as it currently says. Please let me know if anything is out of place. Thank you!
1. Navigate to the Discover tab
2. Tap the Discover navigation button
3. The search fragment should open as if the user tapped the top search bar
[Screen recording of double-tapping the Discover button and the keyboard popping up](https://github.com/user-attachments/assets/6df8c91b-b1b8-4584-8e57-3d69bf4fe48a)
=> Open podcast search by tapping the Discover button when the Discover page is displayed

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/repositories/src/main/AndroidManifest.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationOpenReceiver.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/TokenErrorNotification.kt
This PR cherry brings in the `notification_open` event that has been recently added to `main` (#4261), but this time we're targeting beta.
Since this has been already tested, just make sure that the pipe is green
=> Add missing `notification_open` event

modules/features/filters/build.gradle.kts, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/SmartPlaylistPreviewPage.kt
1. Start playlist creation
2. Tap Smart Playlist button.
3. You should see a blank screen.
4. Using system back navigation should close the sheet.
=> Add playlist creation page navigation

modules/features/ads/src/main/kotlin/au/com/shiftyjelly/pocketcasts/ads/AdReportFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsOnboardingFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/notifications/EnableNotificationsPromptFragment.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackFragment.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/TranscriptFragment.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/ad/AdReportContent.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt
Our `BaseDialogFragment` doesn't have a good way of setting correct dialog shape. This is a workaround. It allows classes inheriting from `BaseDialogFragment` to apply correct shape that accounts for insets, etc. 
Open transcripts from episodes details in the landscape mode. The content should not draw behind camera cutout. You can also test other fragments that were modified in this PR.
| - | - |
| <img width="1200" height="540" alt="Screenshot_20250729-195121" src="https://github.com/user-attachments/assets/7a84f910-36ed-41f8-9faa-1cf107768b60" /> | <img width="1200" height="540" alt="Screenshot_20250729-195309" src="https://github.com/user-attachments/assets/454c083d-adaa-4de5-83da-3e2c00936e0f" /> |
=> Add function for dialog shape

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingSubscriptionPlan.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeScreen.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Bookmarks.kt, modules/services/localization/src/main/res/values/strings.xml
This is the next contextual upgrade screen, Bookmarks.
Figma: PviUP0aiZctOprDuuYRwpb-fi-4996_2995
Animation: https://video.wordpress.com/v/ibeq2XXi
Fixes https://linear.app/a8c/issue/PCDROID-16/upgrade-screen-bookmarks
1. Log in with an account that doesn't have any subscriptions
2. Navigate to Profile -> Bookmarks -> Get bookmarks
3. Observe animation
https://github.com/user-attachments/assets/493afd44-35ab-405b-9e12-3f3188b79664
=> [Onboarding] Bookmarks

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/EpisodeDurationRulePage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/SmartPlaylistPreviewPage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/RulesBuilderTest.kt, modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/TimeHelper.kt, modules/services/localization/src/main/res/values/strings.xml
This adds episode duration smart rule management. The control buttons are a bit bigger in the designs because designs do not account for the accessibility and min tap target.
Designs:
- 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85778
- 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85444
Fixes PCDROID-57
1. Start a playlist creation.
2. Continue with Smart Playlist.
3. Tap "Duration".
4. Verify the screen with the designs.
5. Saving the rule will navigate you back to the playlist preview page.
| Rule | Applied rule 1 | Applied rule 2 |
| - | - | - |
| <img width="1080" height="2400" alt="Screenshot_20250731-123936" src="https://github.com/user-attachments/assets/b25f68e4-f874-431e-a1b6-922f45435016" /> | <img width="1080" height="2400" alt="Screenshot_20250731-123717" …
=> Control episode duration rule

modules/features/filters/build.gradle.kts, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/PodcastsRulePage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/SmartPlaylistPreviewPage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml
This adds podcasts smart rule management.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-766_37538
Fixes PCDROID-54
1. Start a playlist creation.
2. Continue with Smart Playlist.
3. Tap "Podcasts".
4. Verify the screen with the designs.
5. Saving the rule will navigate you back to the playlist preview page. It will be empty because active preview is not implemented yet. However the create button should be enabled.
| All | None | Some |
| - | - | - |
| <img width="1080" height="2400" alt="all" src="https://github.com/user-attachments/assets/b816a6aa-08a0-4980-904f-bce58845ef65" /> | <img width="1080" height="2400" alt="none" src="https://github.com/user-attachments/assets/d171a03b-4afb-4fbc-92f2-9800fa40a3dc" /> | <img width="1080" height="2400" alt="some" …
=> Control podcasts smart rule

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds a way to observe episodes that are conform to smart rules.
Relates to PCDROID-67
Code review the changes.
=> Observe episodes via smart rules

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/EpisodeStatusRulePage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/SmartPlaylistPreviewPage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml
This adds episode status smart rule management.
Designs:
- 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85650
- 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85444
Fixes PCDROID-56
1. Start a playlist creation.
2. Continue with Smart Playlist.
3. Tap "Episode status".
4. Verify the screen with the designs.
5. Saving the rule will navigate you back to the playlist preview page.
| Rule | Applied rule |
| - | - |
| <img width="1080" height="2400" alt="a" src="https://github.com/user-attachments/assets/0dcd89c5-534f-40b9-a790-8213908fb274" /> | <img width="1080" height="2400" alt="Screenshot_20250731-072526" src="https://github.com/user-attachments/assets/47e0f346-9e34-4c0a-854f-eb0e42ed6db2" /> |
=> Control episode status rule

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/DownloadStatusRulePage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/SmartPlaylistPreviewPage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt
This adds download status smart rule management.
Designs:
- 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85899
- 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85444
Fixes PCDROID-58
1. Start a playlist creation.
2. Continue with Smart Playlist.
3. Tap "Media Type".
4. Verify the screen with the designs.
5. Saving the rule will navigate you back to the playlist preview page.
| Rule | Applied rule |
| - | - |
| <img width="1080" height="2400" alt="rule" src="https://github.com/user-attachments/assets/de84e565-b67d-441d-bf4c-7399a7381fde" /> | <img width="1080" height="2400" alt="Screenshot_20250801-074124" src="https://github.com/user-attachments/assets/635fbbc4-965c-42cc-a76a-66d227c876ec" /> |
=> Control download status rule

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/build.gradle.kts, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistPreviewRow.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/SmartPlaylistDraft.kt
This adds support for Smart Playlist creation. Starred rule is not supported due to design being clarified.
1. Create a Smart Playlist.
2. You should see a screen with its title.
3. Navigate back using system gestures.
4. You should see all playlists.
5. Tap on any playlist.
6. It should open a screen with its title.
=> Create Smart Playlists

.github/dependabot.yml
Similar:
- [JP/WPAndroid#22082](https://github.com/wordpress-mobile/WordPress-Android/pull/22082)
- [WCAndroid#14419](https://github.com/woocommerce/woocommerce-android/pull/14419)
---
Having #4236 merged, we now have one more of our libraries that are stored in S3 and have a custom versioning scheme which doesn't work with :dependabot:. Thus this library should be ignored as well, just like the rest.
FYI: At least for now and until we make this whole :dependabot: process work for such S3 libraries of ours as well.
---
Not needed, we just make sure that no :dependabot: PRs (like [this](https://github.com/wordpress-mobile/WordPress-Android/pull/22063)) gets opened from here onwards and for this repo. 
---
=> [Dependabot] Add `wordpress-lint` to Ignore Configuration

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/AppliedRulesPage.kt
This fixes how rule titles and descriptions are displayed in the builder rows.
Fixes PCDROID-68
It's hard to give any testing steps to test it. You can play around with large font and the episode status rule. But code review and screenshots preview should be enough.
| - | - |
| <img width="1080" height="2340" alt="image" src="https://github.com/user-attachments/assets/76c36326-5b4c-4945-bd4b-efcf7a7c13fb" /> | <img width="1080" height="2340" alt="image" src="https://github.com/user-attachments/assets/5d326643-fca8-48b2-8fdb-f4fe3f3854c7" /> |
=> Fix row long texts in rule rows

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
This PR implements the analytics for the first iteration of the New onboarding project: events that are related to the new upgrade screens.
The requirements (copied from the [linear project](https://linear.app/a8c/project/new-onboarding-new-upgrade-screens-5e53ce5c4955/overview)):
```
We are keeping the previous analytics events for the upgrade screen and will add a version parameter that will have the value 1 for this new version of the screen.
plus_promotion_show
plus_promotion_dismissed
plus_promotion_upgrade_button_tapped
plus_promotion_not_now_button_tapped
plus_promotion_subscription_frequency_changed
plus_promotion_privacy_policy_tapped
plus_promotion_terms_and_conditions_tapped
We will also add a parameter called variant to track what type of screen was show that will hold the …
```
=> [Onboarding] Analytics

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistHeaderAdapter.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistFragment.kt
This adds support for displaying playlist header.
1. Open any playlist.
2. Notice the dummy header with playlist's name.
=> Display dummy playlist header

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistHeader.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistFragment.kt, modules/services/localization/src/main/java/au/com/shiftyjelly/pocketcasts/localization/helper/DurationUtil.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SmartPlaylistMetadata.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/SmartPlaylist.kt
This adds an episode count and playback duration left to the playlist page.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-792_22015
Relates to PCDROID-38
1. Open a playlist with some episodes.
2. Verify playlist's metadata
=> Display playlist's metadata

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/SubscriptionPlanRow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/UpgradeTrialTimeline.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeScreen.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Bookmarks.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Folders.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/PreselectChapters.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Shuffle.kt
This PR adds accessibility improvements and talkback support for the upgrade screens.
You can try and enable TalkBack on your device and use your keyboard to shift focus and traverse the semantic items of the screen. This assumes that you're running the app on an emulator or you're mirroring your device on your computer.
Alternatively, you can just tap on the screen to focus on your selected ui element.
Fixes https://linear.app/a8c/issue/PCDROID-43/accessibility-checks
1. Connect to your device via USB
2. Launch the app and log in with an acocunt that is not subscribed
3. Enable TalkBack service
4. Mirror your phone in AS so you can use your keyboard to traverse the semantics tree
5. Navigate to an onboarding screen (e.g. Profile -> Settings -> Pocket casts plus)
6. Start shifting focus …
=> [Onboarding] Accessibility & Talkback

CHANGELOG.md, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/SubscriptionPlanRow.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/UpgradeTrialTimeline.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeScreen.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Bookmarks.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Folders.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/PreselectChapters.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/contextual/Shuffle.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfBottomSheetPage.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This includes changes related to the generic upgrade screens that we've collected in the linked Linear ticket. Please refer to it to learn the scope.
We're aiming to target 7.95 with the release of the 1st milestone of the New Onboarding project, hence I've set the milestone appropriately
Fixes https://linear.app/a8c/issue/PCDROID-70/make-upgrade-screen-skippable
You should check the upgrade screen on multiple devices and configs (tables/phones + land/port mode).
| Scrolling demo |  TnC linebreaks | TnC centered | 
| --- | --- | --- | 
| <video src="https://github.com/user-attachments/assets/60e65d3b-4d95-412b-92bf-90cc506a94ea"/> | <img width="1080" height="2400" alt="Screenshot_20250801_160948" src="https://github.com/user-attachments/assets/b22ca0f5-81e8-414e-bba6-cbcc4a92c2e1" /> | …
=> [Onboarding] Upgrade screen touchups

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/AppliedRulesPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/EpisodeRow.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/StarredRulePage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaylistEpisodeMetadata.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds starred rule UI.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-1573_85959
Closes PCDROID-60
1. Have some starred episodes.
2. Start Smart Playlist creation.
3. Play around the starred rule.
| Enabled | Disabled | Applied Enabled | Applied Disabled |
| <img width="324" height="720" alt="image" src="https://github.com/user-attachments/assets/c9656d70-5171-449e-8e58-e6c753d13d6a" /> | <img width="324" height="720" alt="image" src="https://github.com/user-attachments/assets/6a71c4fa-43db-445d-a314-8aef8f94a889" /> | <img width="324" height="720" alt="image" src="https://github.com/user-attachments/assets/d95517e1-7d86-4fa8-ac43-07fca437500b" /> | <img width="324" height="720" alt="image" src="https://github.com/user-attachments/assets/54e41064-8c49-4275-9454-61a2e669923b" /> …
=> Add starred rule control

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/AppliedRulesPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/RulesColumn.kt
This extracts common component for the rules UI that will be used for Smart Playlist editing.
Relates to: PCDROID-73
Smoke test rules UI during Playlist creation.
=> Extract rules UI component

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/edit/SmartRulesEditor.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt
This PR extracts rules editing logic from a view model to the `SmartRulesEditor` class. It is needed to share the code between playlist creation and playlist editing. The view model is heavily covered with tests so it is a very safe refactor.
Relates to PCDROID-73
Smoke test playlist creation.
=> Extract rules editing logic

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/edit/SmartRulesEditFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/edit/SmartRulesEditViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/rules/AppliedRulesPage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/SmartPlaylist.kt
This adds the capability to edit rules of existing Smart Playlists. The implementation differs a bit from the designs. When the edit page is open for the first time it show episodes preview immediately instead of waiting until rules are applied. It would too much work to add something that feels like a drawback.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-1719_90945
Closes PCDROID-73
Test editing rules of an existing Smart Playlist.
https://github.com/user-attachments/assets/8b345f6a-91fe-451a-825d-247a89ece489
=> Add Smart Playlist rules editing

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistArtwork.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistHeader.kt
Open a playlist and notice the shadow behind foreground artwork.
| - | - |
| <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/66559706-c196-454b-8ca9-a523b50f6654" /> | <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/96545c8b-23ac-4427-9600-6cc54e4f2c76" /> |
=> Add playlist header artwork elevation

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModel.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/DefaultPlaylistsInitializater.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds inserting new playlists to the top instead of to the bottom.
Context: p1754604672773389/1754589090.779989-slack-C093RV9N8DR
1. Go to playlists page.
2. Create a new one.
3. Go back to the playlists page.
4. Your new playlist should be at the top.
=> Insert new playlists first in order

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistHeader.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistHeaderAdapter.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/SmartPlaylistViewModel.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/RecyclerView.kt
This adds Smart Playlist episode filtering. I considered whether it should be implemented on the database side or in the view model, but ultimately decided to use the database. The main advantage is that it can include episodes not shown in the UI, since we limit them to 500 in the UI.
Designs: p1755069694308299/1755063206.427129-slack-C093RV9N8DR
Closes PCDROID-99 
1. Open any playlist with episodes.
2. Use a search query that would yield some episodes.
3. Tap "Play All".
4. The displayed episodes should start playing. Not the one from the whole playlist.
5. Clear search.
6. Search using a query that doesn't yield any results.
7. You should see the empty state.
| Empty state | Slowed down video |
| - | - |
| <img width="360" alt="Screenshot_20250813-175027" …
=> Add Smart Playlist search

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/sharing/SharingClientTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/TranscriptFragment.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/TranscriptViewModel.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/ui/TranscriptLines.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/ui/TranscriptPage.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/transcript/TranscriptManagerTest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/TranscriptService.kt, modules/services/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/SharingClient.kt
This includes the following changes:
- With the podcasters' transcripts, the fade was always hiding the header. I caused this when I moved the generated transcript warning into the list.
- Every time the episode dialog was opened, a server call to get the transcript would happen, causing a delay in displaying the view transcript button. 
- Added missing analytics properties for the share transcript button.
- Fixed some minor typos.
- Go to a podcast that has their own transcripts. For example The Rework Podcast.
- Tap on an episode row and the "View transcript" button.
- ✅  Verify the first line of the transcript is not hidden by the fade. 
- Go to a podcast with transcripts.
- Tap on an episode row that you haven't been to before but recent enough it has a transcript.
- ✅ Notice there is …
=> Fix transcript fade on podcaster transcripts

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/FeatureCarousel.kt
Design has requested to animate the carousel index indicator similarly to Instagram.
> ... we should animate the gray bars on top, same as Instagram stories
They fill up as the time for the next story progresses
Context: p1755525987234659-slack-C0932TFPUDC
1. Build and install `debug` variant
2. Observe the progress indicators on the landing page
https://github.com/user-attachments/assets/b9e0a28c-73e1-448a-b3fa-21db49345604
=> [Onboarding] Animate carousel progress indicators

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/CarouselAnimations.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/FeatureCarousel.kt
This PR addresses the latest design feedbacks on the carousel behavior.
We now support manual stepping when the user taps the horizontal edges of the carosel (left edge steps to previous page, right edge steps to next one)
Also, the carousel no longer infinitely loops, it will stop when reaches the last item.
I've simplified the animation states of `CarouselAnimations` and created a state machine for the carousel to contain all the stepping logic.
Figma + questions: PviUP0aiZctOprDuuYRwpb-fi-5076_9088
Related to https://linear.app/a8c/issue/PCDROID-83/feature-carousel
1. Build a `debug` version => FF is enabled in debug builds by default
2. Launch the app
https://github.com/user-attachments/assets/11a999ff-c116-4046-a969-c89e5102c56a
=> [Onboarding] Update intro carousel behavior

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/data/DataSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/data/DeviceSync.kt
This is continuation of migration described in #4390.
Relates to PCDROID-119
I don't really understand this behavior and how it works. I just copied the logic from the `PodcastSyncProcess`.
1. Enable the proto syncing feature flag.
2. Listen to something with an increased speed to x5.
3. Pause it after a minute or so.
4. Go to stats from the profile tab.
5. Sync your devices.
6. The other device should reflect the changes.
The current syncing code, which I reused here, has cache stats function:
https://github.com/Automattic/pocket-casts-android/blob/ceb9b511acda8c8429c0f9e3632aab860001bf56/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt#L641-L644
Which is called during full and incremental sync: …
=> Sync device using Protobuf

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/data/DataSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/data/PodcastSync.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
This is a continuation of the migration described in #4390. Adding syncing was fairly simple, as it only required calling `UpNextSyncWorker` during the sync process. However, I noticed a potential bug: our `UpNextSyncWorker` was cancellable, and enqueuing one work item would cancel another. Since syncing could be interrupted at any point, this might have left the process in an incomplete state.
To address this, I changed the Up Next syncing to use a unique work with the `APPEND_OR_REPLACE` policy. This ensures that all enqueued changes are processed sequentially, even if they occur too frequently or if the sync process overlaps with the periodic Up Next sync.
Additionally, I added extensive logging and improved error handling to the entire data sync process in this PR.
Relates to …
=> Add Up Next syncing to new sync

modules/features/account/build.gradle.kts, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/InterestCategoryPill.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsViewModel.kt, modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsViewModelTest.kt
The interests screen is now populated from `CategoriesManager`. Please note that this might change in the future as we're planning to introduce a new API to get the data from. Context: p1755858078317389-slack-C0932TFPUDC
Designs: PviUP0aiZctOprDuuYRwpb-fi-5109_15632
Fixes https://linear.app/a8c/issue/PCDROID-130/implement-interest-items
1. build `debug` version so the FF will be enabled
2. Tap 'Get started' on the intro carousel
3. Check the screen
https://github.com/user-attachments/assets/dd8779b7-47a1-4db6-aa30-4798a70b0fb8
=> [Onboarding] Functional Interests screen

modules/features/account/build.gradle.kts, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/InterestCategoryPill.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsFlow.kt, modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsViewModelTest.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This PR adds the interets screen with hardcoded data and very simple category pill selectors.
Upcoming PRs will take care of the rest.
Fixes https://linear.app/a8c/issue/PCDROID-129/implement-interest-selection-frame
1. Build `debug` version of the app so the FF will be enabled by default
2. Clean intall the app to see the new onboarding 
3. Press Get started on the intro carousel
https://github.com/user-attachments/assets/714ac3f5-45c8-4d5a-b51b-1087c63f6b87
=> [Onboarding] Interests frame

CHANGELOG.md, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt, modules/features/profile/src/main/res/layout/fragment_cloud_settings.xml
File Settings page wasn't setting bottom padding to the page.
Closes PCDROID-134
1. Increase font on your device.
2. Play something so that the Mini Player is present.
3. Go to File Settings.
4. You should be able to scroll to the bottom and see the "Only On WiFi" setting.
| - | - |
| <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/fd5a4db0-d8d0-4399-99b3-f20444eb47a6" /> | <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/bb690ebe-6792-4880-90df-00ab7f519525" /> |
=> Fix File Settings accessibility issue

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/InterestCategoryPill.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsPage.kt
This PR adds the last bits linked to the interests screen visuals: animations!
The pills are now animated when the user selects them.
The animation is a spring-like combination of scale-up and rotate.
Animation expectations: https://www.figma.com/proto/PviUP0aiZctOprDuuYRwpb/Onboarding?page-id=5104%3A13933&node-id=5109-16262&viewport=538%2C659%2C0.25&t=98NAUVqpaKl4YL9f-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5109%3A16262
Fixes https://linear.app/a8c/issue/PCDROID-130/implement-interest-items
1. Build `debug` version so the FF will be ON by default
2. Fresh install app, tap 'Get started' on the intro carousel
3. Tippy-tap those interest pills
https://github.com/user-attachments/assets/29011ece-2625-4315-827e-a5b8e5ce6fc0
=> [Onboarding] Animate interest pills upon selection

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt, modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPageViewModelTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/categories/CategoriesManager.kt
Prioritize selected interest categories on the recommendations page.
When the user has selected at least 3 interest categories, we should promote them to the top of the recommendations list. Promoted categories will be followed by the regular recommendations (Featured, Trending, and the rest of discover categories)
If there aren't any interests selected, or the FF is disabled, we should return the usual recommendations (Featured, Trending, discover categories)
Bonus: Added tests to verify this behavior
Fixes https://linear.app/a8c/issue/PCDROID-131/adapt-to-interests-on-recommendations
1. build `debug` so the FF will be enabled
2. On the intro carousel, select Get started
3. On the interests screen, try two scenarios:
- A - tap Not now
- B - select at least 3 then continue
4. Observe …
=> [Onboarding] Respect user's interests on Recommendations

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/CreatePlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/PlaylistFragment.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/CreatePlaylistViewModelTest.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/DefaultPlaylistsInitializater.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds inserting new Manual Playlists to the database.
Closes PCDROID-108
1. Go to playlists page.
2. Start creation process.
3. Change the name.
4. Tap the create button.
5. You should see a mock page.
6. Go back to playlists.
7. Tap on your new playlist.
8. You should see a mock page.
=> Create manual playlist

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/ManualPlaylistEpisodeSource.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This PR adds support to fetch data for this flow: 5sC4z4Mu42LvL4MAAIbQVi-fi-764_7768 
Relates to PCDROID-109
Code review my changes. There is nothing to test manually yet.
=> Load episode sources for manual playlists

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditColorPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderListRow.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchFolderItem.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImageSmall.kt
Our `FolderImageSmall` could be used for image preview when adding episodes to a playlist but it is written inefficiently and doesn't fully match the specification. This PR fixes both of those problem.
Relates to PCDROID-109
1. Have some folders.
2. Go to podcasts page.
3. Change layout setting from a grid to a list.
4. Folders should display.
=> Simplify folder artwork image

CHANGELOG.md, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/compose/PodcastRow.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/LongestEpisodeStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/NumberOfShowsStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowStory.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/TopShowsStory.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/smart/rules/PodcastsRulePage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditPodcastsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolderPodcastsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastHeader.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateBuildingPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateTitlePage.kt, modules/features/reimagine/src/main/kotlin/au/com/shiftyjelly/pocketcasts/reimagine/ui/CardData.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchEpisodeRow.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastCover.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastImage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImageSmall.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/podcast/ListPodcastSubscribeRow.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/podcast/PodcastSelectImage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/podcast/PodcastSubscribeImage.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastScreen.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsScreen.kt
Our current `PodcastImage` is fundamentally broken but I'm worried that fixing it will break stuff in our app as it might be relying on its incorrect behavior or some quirks. This PR deprecates it and introduces a new component.
Fixes PCDROID-52
Relates to PCDROID-109
1. Follow a podcast.
2. Collapse the header / artwork.
3. Go back to the podcasts grid.
4. Go back to the podcast page.
5. Expand the header / artwork.
6. There should be no UI glitches.
| - | - |
|  <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/1463aa24-3d25-44d7-9beb-d101ddd131e3" /> | <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/4d779a28-6b60-4a16-aeed-bba00a99030a" /> |
=> Fix broken podcast image animation

gradle/libs.versions.toml, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/AccountBenefitsPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingCreateAccountPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingNotAllowedToRateScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingsErrorScreen.kt, modules/services/compose/build.gradle.kts, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bars/ThemedTopAppBar.kt, modules/services/images/src/main/res/drawable/ic_anim_close_back.xml
This adds new button type for the toolbar which can animate between back and close actions.
Relates to PCDROID-110
Code review my changes. You can test the animation with the Compose preview in IDE if you want to.
https://github.com/user-attachments/assets/9f128820-9b16-4fae-a1f4-141adf9220fb
=> Add toolbar button animation

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/EpisodeSourcesColumn.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/EpisodesColumn.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/navigation/NavController.kt, modules/services/images/src/main/res/drawable/ic_add_episode.xml, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds episode preview when build manual playlists.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-764_7821
Relates to PCDROID-110
1. Create a manual playlist.
2. Tap "Add episodes"
3. Select any podcast.
4. You should see its episodes.
=> Show episodes in manual playlist build flow

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationOpenReceiverActivity.kt
Another issue came up in regards to the notifications, this time a user has reported that the Downloads notification no longer opens the app.
The issue was that I didn't parse the intent's `data` prop when converting the original intent to a wrapper that goes through `NotificationOpenReceiverActivity`. 🤦 
Fixed that and voila, it works again.
Fixes https://linear.app/a8c/issue/PCDROID-138/clicking-on-the-download-in-progress-notification-no-longer-takes-me
https://github.com/user-attachments/assets/c5d92b00-559f-40f8-aeb4-757f740e47c9
=> Pass intent.data when receiving/opening a notification

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/EpisodesColumn.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ThemedSnackbarHost.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
As the title says. Note that the snackbar doesn't show the alert icon as the designs didn't account for Android components that we use. This was clarified here: 5sC4z4Mu42LvL4MAAIbQVi-fi-831_13279#1363225140
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-2600_36431
Closes PCDROID-110
1. Apply [this patch](https://github.com/user-attachments/files/22092522/ep-limit.patch).
```
curl -L https://github.com/user-attachments/files/22092522/ep-limit.patch | git apply
```
2. Create a manual playlist.
3. Tap "Add Episodes".
4. Navigate to any podcast.
5. Start adding episodes.
6. The sheet's title should update with added episodes.
7. When you reach limit you should see a snackbar.
8. Close the sheet.
9. Tap "Add Episodes".
10. You should see a snackbar.
11. You can test added episodes by inspecting the …
=> Add episodes to manual playlists

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/AddEpisodesViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/EpisodeSourcesColumn.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/episode/EpisodesColumn.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/smart/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/smart/PlaylistViewModel.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/text/SearchFieldState.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
This adds search feature when building manual playlists. Podcast/folder search is independent of the episode search.
Closes PCDROID-111
Closes PCDROID-112
1. Create a manual playlist.
2. Tap "Add Episodes".
3. Searching should podcasts and folders. Note: folder search includes podcasts instead the folder.
4. Tap a folder.
5. Search term should still be the same.
6. Go to a podcast.
7. Search term should be cleared.
8. Search for episodes.
9. Go back.
10. Search term should change back to the one you used for podcasts.
https://github.com/user-attachments/assets/97b5d441-54af-4815-a4a6-c6d3475a9b10
=> Filter episodes when adding them to manual playlists

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/CreatePlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/PlaylistHeader.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/PlaylistHeaderAdapter.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/PlaylistToolbar.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/smart/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/smart/rules/EditRulesFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/smart/rules/ManageSmartRulesPage.kt, modules/features/filters/src/main/res/layout/playlist_fragment.xml, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/NoContentBanner.kt
This changes the empty state UI for smart playlists. The empty state icon has a bit different colors but it is because designs do not account for how we're styling icon. Having it this way makes it consistent with other empty states in the app.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-3622_26652
Closes PCDROID-146
1. Have a smart playlists without any episodes.
2. Notice empty state.
3. Tapping button should allow you to edit rules.
=> Update Smart Playlists empty state

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/PlaylistViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/NoContentBanner.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
As the title says. States aren't top aligned because it's not possible without hardcoding some top padding. In practice it doesn't matter because they are never displayed next to each other so it's better to just center them in the UI.
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-3618_25973
Closes PCDROID-113 
1. Don't have any podcasts followed.
2. Create a playlist.
3. Tap the CTA button.
4. You should see Discover.
5. Follow any podcast.
6. Go back to the playlist.
| No followed | Followed |
| - | - |
| <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/8f0d03a2-21cd-4db9-8e34-35f494a1b1d0" /> | <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/8cfd0f3b-b28f-4c2c-8160-b06e139c661e" /> |
=> Display empty state in Manual Playlists

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerManualTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/PlaylistEpisodesAdapterFactory.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/UnavailableEpisodeFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/UnavailableEpisodePage.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-2615_52293
Closes PCDROID-145
1. Create a manual playlist.
2. Execute this query.
```sql
INSERT OR REPLACE INTO manual_playlist_episodes(playlist_uuid, episode_uuid, podcast_uuid, title, added_at, published_at, download_url, episode_slug, podcast_slug, sort_position, is_synced)
VALUES ((SELECT uuid FROM playlists WHERE deleted IS 0 AND manual IS 1 LIMIT 1), 'mock-uuid', 'mock-uuid', 'Mock episode', (SELECT strftime('%s','now') * 1000), (SELECT strftime('%s','now') * 1000), '', '', '', 0, false)
```
3. Tap on the unavailable episode.
4. You should see modal.
5. Dismiss it.
6. Tap again on the episode.
7. Confirm episode deletion.
8. The episode should be removed.
=> Show unavailable episode modal

CHANGELOG.md, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingInterestsPage.kt
Credits/original PR: https://github.com/Automattic/pocket-casts-android/pull/4471 🙇 
Make the FlowRow layout flexible and fix layout spacing in onboarding interests page.
Fixes #4469
Designs: PviUP0aiZctOprDuuYRwpb-fi-5109_15632
* Launch the app
* Click 'Get started'
* Click the "Show more categories" label
| Small collapsed | Small expanded | Modern collapsed | Modern expanded |
| --- | --- | --- | --- |
| <img width="720" height="1280" alt="Screenshot_20250909_183307" src="https://github.com/user-attachments/assets/21e306d7-eefa-48e2-8939-638a1a9fac76" /> | <img width="720" height="1280" alt="Screenshot_20250909_183313" src="https://github.com/user-attachments/assets/963f80e4-965a-4b90-a2e0-354f01293f71" /> | <img width="1080" height="2400" alt="Screenshot_20250909_183845" …
=> Fix interests spacing

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/EpisodeAvailableViewHolder.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/EpisodeUnavailableViewHolder.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/PlaylistEpisodesAdapterFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/swipe/SwipeAction.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/swipe/SwipeActionViewModel.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/swipe/SwipeSource.kt
This adds support for playlist swipe actions.
Closes PCDROID-117
Test different swipe actions for both manual and smart playlists.
=> Handle playlist swipe actions

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/di/SharingModule.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/AddToPlaylistFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/PlayerShelf.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/shelf/ShelfBottomSheetPage.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt, modules/services/images/src/main/res/drawable/ic_add_to_playlist_action.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfRowItem.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/swipe/AddToPlaylistFragmentFactory.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/swipe/SwipeAction.kt, modules/services/views/src/main/res/drawable/background_dialog_fragment.xml
Designs: 5sC4z4Mu42LvL4MAAIbQVi-fi-831_13302
Closes PCDROID-121
1. Add podcast and user episodes to your up next.
2. Open the player.
3. When podcast episode plays shelf action should be available.
4. When user episode plays shelf action should not be available.
5. Disable the feature flag in dev settings.
6. Close the app and force stop it so there is no background process running.
7. Open the app and go to the player.
8. Shelf action should not be available to any episode.
| Shelf | More | All |
| - | - | - |
| <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/19441e70-6005-46c9-9105-f4d8f65da42f" /> | <img width="1080" height="2400" alt="image" src="https://github.com/user-attachments/assets/fed9658e-fa45-4593-bc7c-079388284bf …
=> Add "add to playlist" shelf action

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerDsl.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/PlaylistPreviewRow.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/Playlist.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistPreview.kt
This changes `PlaylistPreview` from a `data class` to a `sealed interface`. This change is needed to support controlling auto-downloads in different contexts as the podcast settings control needs to know whether is used in a playlist.
Relates to PCDROID-97
Code review is fine.
=> Refactor playlist preview

wear/build.gradle.kts
This is only a minor change to fix the following build warning by switching to the `compilerOptions` DSL.
```
w: ./pocket-casts-android/wear/build.gradle.kts:46:9: 'freeCompilerArgs: List<String>' is deprecated. 
Please migrate to the compilerOptions DSL. More details are here: https://kotl.in/u1r8ln
```
Without this flag the following error happens:
```
e: ./pocket-casts-android/wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/WearAboutScreen.kt:35:27
Horologist API is experimental. The API may be changed in the future.
```
A successful build should be enough.
=> Fix freeCompilerArgs build warning

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerDsl.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLogInViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/SignInViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/MembershipFeature.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/MembershipTest.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ads/BlazeAdsManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsWorker.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/ServerPurchaseApprover.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SubscriptionModel.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Flow.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
This ads `Membership` type that has features from the backend attached to it. 
Closes PCDROID-173
1. Install the app from the `release/7.98` branch.
2. Sign in with a Plus account.
3. Enabled airplane mode.
4. Install the app from this branch.
5. Open the app.
6. You should still see your subscription and no Plus incentives.
1. Install the staging `debug` app.
2. Start the app and do not sign in.
3. You should see banner ads.
4. Sign in with this user. p1758782139774569-slack-C08U02AG7C5
5. You should not see the ads.
=> Add user memebership

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusViewModel.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/AndroidManifest.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/InitializerEntryPoint.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/DefaultPlaylistsInitializer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/DefaultPlaylistsStartupInitializer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/Playlist.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistInteractionNotifier.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImplTest.kt
This is some minor cleanup and updates to text copies that do not use "playlists" wording.
Closes PCDROID-96
=> Use playlists nomenclature in the whole app

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistViewModel.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoPlaySource.kt, modules/services/preferences/src/test/kotlin/au/com/shiftyjelly/pocketcasts/preferences/model/AutoPlaySourceTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/AutoPlaySelector.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
Current playlists interactions do not support auto play. This adds it.
1. Have an empty queue.
2. Create a manual playlists.
3. Add episodes to it.
4. Play a single episode from it.
5. Fast forward to the end.
6. A next episode from the playlist should start playing.
=> Add auto play to playlists

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistFragment.kt
When determining content state I incorrectly used `archivedEpisodeCount` instead of `totalEpisodeCount`. This resulted in the empty state being shown instead of the empty search results.
1. Create a playlists.
2. Do not have any archived episodes in it.
3. Search for an arbitrary episode that doesn't yield any results.
4. You should see no episodes found state.
=> Fix playlist empty search state

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ShelfSharedViewModel.kt
It's possible to open the full-screen player with an episode that should have a transcript, but the transcript button is incorrectly disabled. The issue was that the Observable had a distinct on it. So if the current playing episode changed, that would not be classed as a change. I've modified it so that it also considers the UUID of the playing episode. 
Fixes PCDROID-92
1. Clear your Up Next
2. Restart the app
3. Create an Up Next using some old episodes that don’t have transcripts. For example The Daily episodes from 2024
4. Now play an episode with a transcript for example the most recent The Daily episode
5. Open the full screen player
6. ✅  Verify the transcript button isn't greyed out
=> Fix transcript button incorrectly disabled

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingFragment.kt, modules/features/podcasts/src/main/res/layout/fragment_share_incoming.xml
When you open a shared list of podcasts and you have the mini player open, you can't get to the bottom of the list.
Fixes PCDROID-135
1. Click on this list https://lists.pocketcasts.com/strange-tales
2. Try to scroll to the bottom of the page
| --- | --- |
| <img width="1198" height="2531" alt="Screenshot_20251001_172552" src="https://github.com/user-attachments/assets/065d8cb0-7c75-4d29-b811-48cea7fa1e8c" /> | <img width="1198" height="2531" alt="Screenshot_20251001_170013" src="https://github.com/user-attachments/assets/2bf02ec4-890c-46ac-bccb-84613fd1e549" /> | 
| <img width="1198" height="2531" alt="Screenshot_20251001_172620" src="https://github.com/user-attachments/assets/94cb73e4-44ea-4e49-9d11-fee2fdd48810" /> | <img width="1198" height="2531" …
=> Fix shared list under the mini player

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerManualTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
This PR adds support for excluding or including archived episodes when computing playlist time left duration.
1. Create a Manual Playlist.
2. Add some episodes to it.
3. Archive a couple of episodes.
4. Toggle show archived state.
5. Notice that the playback duration responds to the archived state.
=> Improve playlist's time left calculation

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/swipe/SwipeButton.kt
A new error has [appeared in Sentry](https://a8c.sentry.io/issues/6916081511/?notification_uuid=0c72da56-7e67-4e5b-a209-142e315a0241&project=6711064). 
Release: 7.99-rc-1 (9374)
OS: Android 11 - 92%, Android 10 - 8%
```
InflateException
Binary XML file line #6 in au.com.shiftyjelly.pocketcasts:layout/adapter_episode: Binary XML file line #6 in au.com.shiftyjelly.pocketcasts:layout/adapter_episode: Error inflating class au.com.shiftyjelly.pocketcasts.views.swipe.SwipeRowLayout
java.lang.ClassCastException: android.content.res.TypedArray cannot be cast to java.lang.AutoCloseable
at au.com.shiftyjelly.pocketcasts.views.swipe.SwipeButton.<init>(SwipeButton.kt:64)
at java.lang.reflect.Constructor.newInstance0(Constructor.java)
```
This is happening because `TypedArray` did not become …
=> Fix swipe crashing before Android 12

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/coroutines/SyncedAction.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/coroutines/SyncedActionTest.kt
Context : p1759227747944919-slack-C028JAG44VD
Smoke test if your subscription status works.
=> Minimize fetch subscription status call count

CHANGELOG.md, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt
#4477 introduced a bug when adding episodes to Up Next when auto-download feature was enabled. Such episodes got skipped because of the `isExemptFromAutoDownload` condition.
1. Go to the settings.
2. Go to the auto download settings.
3. Disable the "On Follow" setting.
4. Enable the "Episodes added to Up Next" setting.
5. Follow any podcast.
6. Go to it.
7. Swipe left to archive an episode.
8. Show archived episodes.
9. Swipe right on the archived episode.
10. It should be added to the queue and auto-downloaded.
=> Fix auto downloading archived episodes

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerDsl.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerManualTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/ui/PlaybackServiceTest.kt, automotive/src/androidTest/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackServiceTest.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/PlaylistsViewModel.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/component/PlaylistPreviewRow.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/AddToPlaylistFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/AddToPlaylistPage.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/playlists/manual/AddToPlaylistViewModel.kt, modules/features/filters/src/test/kotlin/au/com/shiftyjelly/pocketcasts/playlists/create/FakePlaylistManager.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsHomePage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsPlaylistsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsPlaylistsPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaylistPreviewForEpisode.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playlist/PlaylistPreview.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Flow.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/playlists/PlaylistsScreen.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/playlists/PlaylistsViewModel.kt
This PR addresses performance issues when users are subscribed to many podcasts. Displaying playlist artwork and episode counts requires loading data from the episodes table, which can contain hundreds of thousands of episodes. With multiple playlists, this becomes prohibitively slow.
- Decouple playlist preview from playlist metadata. The preview (containing only uuid, title, and configuration) can now be fetched quickly. Metadata, on the other hand, is cached with a 30-second eviction timeout.  
- In-memory operations for configuration changes. When interacting with playlists to update configurations, all operations are performed in memory first and then dispatched to the database. This improves the responsiveness of controls.  
While these optimizations greatly improve performance, …
=> Optimize playlists performance

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/BaseEpisodeViewHolder.kt
Change archived status separator from `.` to `·`.
Context: p1759832359963469/1759806249.844679-slack-C093RV9N8DR
| - | - |
| <img width="740" height="164" alt="image" src="https://github.com/user-attachments/assets/64637b2a-3cbe-4d18-be68-243993736fb8" /> | <img width="738" height="159" alt="image" src="https://github.com/user-attachments/assets/654d1a62-f694-4b38-95f4-3f68899c0d7c" /> |
=> Change episode status separator

CHANGELOG.md, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextSortFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/UpNextViewModel.kt, modules/features/player/src/main/res/layout/adapter_up_next_footer.xml, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/UpNextViewModelTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextChangeDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/UpNextSortType.kt, modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/UpNextSortTypeTest.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
This adds parity with the Web Player and allows sorting Up Next episodes by date.
1. Add episodes to Up Next.
2. Open Up Next.
3. Tap sort button.
4. Select sorting option.
5. The episodes should get sorted.
https://github.com/user-attachments/assets/97be055c-b205-4673-b46d-ccc96e07b727
=> Add Up Next Sorting

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/interceptors/InternationalizationInterceptor.kt, modules/services/servers/src/test/kotlin/au/com/shiftyjelly/pocketcasts/servers/interceptors/InternationalizationInterceptorTest.kt
This adds`X-App-Language` and `X-User-Region` headers to our HTTP requests.
Closes PCDROID-179
1. Start the app.
2. Check for the headers either in the Logcat or in the Network Inspection.
3. The headers should match your configuration.
4. Go to Discover and scroll to the bottom.
5. Change your region.
6. Value should be reflected in the `X-User-Region` header.
7. Change device's or app's language from the system settings.
8. Value should be reflected in the `X-App-Language` header.
=> Add i18n headers

lint.xml
Context: p1759848936887519-slack-C028JAG44VD
1. Run `./gradlew :app:lintRelease`
2. Open the report.
3. There should be no mention of `UsingMaterialAndMaterial3Libraries`.
=> Disable Material Lint check
