Automattic/pocket-casts-android

modules/features/discover/src/main/res/layout/podcast_grid_fragment.xml

With the last change I fixed the padding of the titles on the full page discover collection view when using a grid. But I broke it for when there is a headshot. 🤦‍♂️ This change fixes that!
| --- | --- |
| ![Screenshot_20221002_084205](https://user-images.githubusercontent.com/308331/193430521-bd567dad-a9b9-4bb0-8dc1-5ea3ab035846.png) | ![Screenshot_20221002_085304](https://user-images.githubusercontent.com/308331/193430505-a86b963d-5736-4778-922e-9e72bde6b1ce.png) |
| ![Screenshot_20221002_084220](https://user-images.githubusercontent.com/308331/193430517-c4ce4c10-fbd0-4e46-b174-a01d96c9eaf9.png) | ![Screenshot_20221002_085312](https://user-images.githubusercontent.com/308331/193430503-3963d687-4076-4396-be18-d8c62b34995b.png) |
| …

Fix the position of the discover collection headshot on the grid layout

---

automotive/src/androidTest/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackServiceTest.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt

This change switches the Automotive OS opening tab between "Podcasts" and "Discover". If the user doesn't have any podcasts it starts with the "Discover" so they aren't presented with an empty screen. Otherwise, the user is shown their podcast collection as the first tab.
Fixes https://github.com/Automattic/pocket-casts-android/issues/347
**Test steps**
1. Open the Automotive app
The "Discover" tab should open first.
2. Tap on a podcast
4. Leave the app, open the Settings app
5. Open the Apps section
6. If the Pocket Casts app and Force stop the app
7. Open the Bluetooth Audio app
8. Open the Pocket Casts app
The "Podcasts" tab should open first.

Improve Automotive OS tab order

---

build.gradle
dependencies.gradle

This change upgrades some of the core libraries.
Upgraded **Android build tools** from 7.2.2 to 7.3.0
https://developer.android.com/studio/releases/gradle-plugin#7-3-0
---
Upgraded **Sentry** from 6.4.1 to 6.4.2
https://github.com/getsentry/sentry-java/blob/main/CHANGELOG.md#642
- Fixed AbstractMethodError when getting Lifecycle 
- Missing unit fields for Android measurements 
- Avoid sending empty profiles
- Fix file descriptor leak in FileIO instrumentation 
---
Upgraded **Firebase BOM** from 30.3.2 to 30.5.0
Which upgrades Firebase Analytics from 21.1.0 to 21.1.1
https://firebase.google.com/support/release-notes/android#2022-09-01
- Fixed a bug where GoogleTagManager (transitively included from the Tag Manager SDK) would rapidly retry DNS lookups whenever it fails.
- Updated …

Upgrade libraries

---

modules/features/discover/src/main/res/layout/row_collection_list.xml

Just updated the `maxLines` to 2, Fixes #48

Update the maxLines property of Discover collection title

---

dependencies.gradle

The ability to create a locally signed release build no longer works for me after the buildkite updates. This restores the previous behavior where the user can define the relevant information locally in a gradle.properties file (as described in the [README](https://github.com/Automattic/pocket-casts-android/blob/main/README.md#signing-a-release)).
1. Set up a signing key and add the relevant properties to one of the gradle.properties files that this project will load
2. Create a release build and ensure that the app runs

Enable creating local signed release builds

---

README.md

Improving the readme header to keep up with iOS, but this version supports dark mode too!

Improve the readme logo

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt

This change allows the user to select text from the show notes on the full-screen episode details view.
Thanks to @karacca for looking into this issue.
Fixes https://github.com/Automattic/pocket-casts-android/issues/143
**Test steps**
1. Tap on the "Podcasts" tab
2. Tap on a podcast
3. Tap on an episode
4. Long press on the show notes to select text
You should be allowed to copy text from the show notes.

Allow select text in show notes from episode details view.

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/res/layout/adapter_player_header.xml

Fixes #370 by adding a top level view to capture the down events that for some reason don't seem to always make it down to the `NestedScrollView` (which results in a crash). 
_h/t to @geekygecko for coming up with this solution. 🙇_
> **Warning**
> I am targeting the `release/7.24` branch because I think we should do a betafix for this. It is a regression in the 7.24 release (probably because of [bumping our target SDK to 33](https://github.com/Automattic/pocket-casts-android/pull/312)) and has a pretty high number of occurrences in Sentry considering it only just started with the 7.24-rc-1 release we put out earlier this week. Let me know if you disagree (or if you think that targeting the release branch like this isn't the right way to proceed with a beta release).
This crash is very …

Fix crash when swiping to open Up Next queue

---

automotive/src/main/AndroidManifest.xml

This PR removes advertising ID permission and disables its collection for the automotive app. 
While creating beta release for the mobile app, publishing failed with the below error:
```
[2022-10-06T06:41:51Z] [!] Google Api Error: Invalid request - This release includes the com.google.android.gms.permission.AD_ID permission but your declaration on Play Console says your app doesn't use advertising ID. You must update your advertising ID declaration.
```
Noticed that advertising ID permission was included for the automotive app in the merged manifest that blocked publishing for the mobile app as well:

Remove ad id permission for automotive

---

app/src/debug/res/xml/shortcuts.xml
app/src/debugProd/res/xml/shortcuts.xml
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextTouchCallback.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/dialog/ClearUpNextDialog.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/dialog/MiniPlayerDialog.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/OptionsDialog.kt

| 📘 Project: #261  |
|:---:|
Adds events to the mini player and up next views
1. Launch the app and play something if you have no miniplayer
2. Long press on the mini player
3. ✅ Verify you see `🔵 Tracked: mini_player_long_press_menu_shown`
4. Dismiss it without taking any action
5. ✅ Verify you see `🔵 Tracked: mini_player_long_press_menu_dismissed`
6. Long press again and select the mark played action
7. ✅ Verify you see `🔵 Tracked: mini_player_long_press_menu_option_tapped ["option": "mark_played"]`
8. Long press again and select the Close and Clear action
9. ✅ Verify you see `🔵 Tracked: mini_player_long_press_menu_option_tapped ["option": "close_and_clear_up_next"]`
1. Launch the app and add some items to your queue if you don't have any
2. Tap the up next queue button in the mini …

Track mini player and up next events

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BasePreferenceFragment.kt

Add `BasePreferenceFragment` and Implemented in `PodcastSettingsFragment` to handle loading state changes. I created a base Fragment to handle this logic because I saw other problems that implements Preferences like this one.
Also when I disabled the RecyclerView animation that handles ListPreference's childeren animations, It still has a small flicker. (not the switches only the child items) Which implementation is better in your opinion @geekygecko 
https://user-images.githubusercontent.com/47274419/194526328-74bbb803-426b-4179-b9ec-67a68f941ea9.mp4 
https://user-images.githubusercontent.com/47274419/194526340-1645ef59-81b5-42b0-9b54-e17e09f91d6f.mp4
Fixes #73

Add BasePreferenceFragment and Implement in PodcastSettingsFragment

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

| 📘 Project: #261 |
|:---:|
Corresponding iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/290
This adds events for the sleep timer:
- `player_sleep_timer_enabled`: When the sleep timer is enabled
- `player_sleep_timer_extended`: When the user extends the sleep timer duration
- `player_sleep_timer_cancelled`: When the user cancels the sleep timer
1. Play an episode if you don't have one playing already
3. Tap the ZZZ icon to show the sleep timer options
4. Tap the 5 minutes option
5. ✅ Verify you see: `🔵 Tracked: player_sleep_timer_enabled ["time": 300]` in console
6. Tap each of the other items except end of episode
7. ✅ Verify the `time` property in the log corresponds with the item you selected
8. Tap the end of episode item
9. ✅ Verify you see …

Track player sleep timer events

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistProperty.kt

| 📘 Project: #261 | 🛫 Depends on: #385 |
| --- | --- |
Adds the `filter_auto_download_updated` and `filter_auto_download_limit_updated` events.
1. Open the filters tab
2. Tap on a filter
3. From the overflow menu select "Filter Settings"
4. Toggle Auto Download  on
5. ✅  Observe the event `filter_auto_download_updated, {"source": "filters", "enabled": "true", ...}`
6. Change the number of episodes to Auto Download
7. ✅  Observe the event `filter_auto_download_limit_updated, {"limit": [SELECTED LIMIT], ...}`
8. Toggle Auto Download off
5. ✅  Observe the event `filter_auto_download_updated, {"source": "filters", "enabled": "false", ...}`
1. Open the profile tab
2. Tap on the Settings cog
3. Tap on Auto download
4. Tap on the Filters setting
5. ✅  Tap the checkboxes for some of the filters …

Tracks for Filters part 3 (auto_download_*)

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Playlist.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistProperty.kt

| 📘 Project: #261 | 🛫 Depends on: #386 |
| --- | --- |
Adding the `filter_sort_by_changed` event.
1. Open the filters tab
2. Tap on a filter
3. From the overflow menu, select "Sort By"
4. Dismiss the sort modal without selecting anything
5. ✅  Observe that there is no `filter_sort_by_changed` event fired
6. Reopen the "Sort By" modal
7. Tap on any sorting option
8. ✅  Observe that a `filter_sort_by_changed` event is fired with an appropriate "sort_order" property of either "newest_to_oldest", "oldest_to_newest", "shortest_to_longest", or "longest_to_shortest"

Tracks for Filters part 4 (filter_sort_by_changed)

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

| 📘 Project: #261 | 🛫 Depends on: #387  |
| --- | --- |
Adding the `filter_edit_dismissed` event.
For each of these tests, start by:
1. From the filters tab, tap on a filter
2. From the overflow menu, select "Filter Settings"
1. Immediately exit from the Filter Settings screen without making any changes by tapping on the navigation arrow
2. ✅  Observe that a `filter_edit_dismissed` event is fired, but all of the setting properties are false (did_change_auto_download, did_change_episode_count, did_change_icon, did_change_name, did_change_color)
3. Reopen the Filter Settings screen
4. Exit from the Filter Settings screen without making any changes by using a back gesture
5. 2. ✅  Observe that a `filter_edit_dismissed` event is fired, but all of the setting properties are false
1. Change the …

Tracks for filters part 5 (filter_edit_dismissed)

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/TrimMode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

| 📘 Project: #261 | 🛫 Depends on: #381 |
|:---:|:---:|
Corresponding iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/291
This adds events for the playback effect settings
- `playback_effect_speed_changed`:  When the user changes the speed the podcast plays
- `playback_effect_trim_silence_toggled`:  When the user toggles the trim silence option
- `playback_effect_trim_silence_amount_changed`: When the user changes the trim select amount
- `playback_effect_volume_boost_toggled`: When the user toggles the volume boost option
1. Play an episode if you aren't already
3. Tap the dial icon to open the playback effects view
4. Tap the + button on the Speed option, then tap outside the playback effects view
5. ✅ Verify you see the following in console: `🔵 …

Track playback effect events 

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

| 📘 Project: #261 | 🛫 Depends on: #383 |
|:---:|:---:|
Corresponding iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/292
This adds an event when the user changes the playback position in the player:
- `playback_seek`: When the user changes the playback position in the player
Tracking is added for seeking from 
- `OnUserSeekListener` - I could find only two sources for seek by user: `player` and `full_screen_video`. 
- Notification drawer/ lock screen - I reused `media_button_broadcast_action` source for it. 
1. Play an episode if you're not already
3. Drag the slider to about half way 
4. ✅ Verify you see the following in console ` 🔵 Tracked: playback_seek ["source": "player", "seek_from_percent": 0, "seek_to_percent": PERCENT]` - Where PERCENT …

Track playback seek

---

CHANGELOG.md
automotive/build.gradle
automotive/src/main/res/xml/preferences_auto.xml
dependencies.gradle
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt

This change adds a setting to allow Automotive OS users to show played episodes.
Fixes https://github.com/Automattic/pocket-casts-android/issues/379
Other changes are:
- Moved the Automotive library dependency versions from the build.gradle to dependencies.gradle.
- Upgraded AboutLibraries from 10.4.0 to 10.5.0
https://github.com/mikepenz/AboutLibraries/releases/tag/v10.5.0
**Test Steps**
1. Install the Automotive app on an emulator
2. Start playing an episode
3. On the full screen play mark the episode as played
4. ✅ Verify you don't see the episode in the list
5. Open the settings page and turn on "Show played episodes"
6. ✅ Verify you do see the episode in the list

Added Automotive setting to show played.

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

| 📘 Project: #261 |
| --- |
Adds the `filter_list_reordered` event.
1. Open the filters tab
2. Long press on one of the filters and then move it to a new position
3. ✅  Observe that a `filter_list_reordered` event is fired
4. Long press on one of the filters but leave it in the same position
5. ✅ Observe that a `filter_list_reordered` event is _not_ fired

Tracks for filters part 6 (filter_list_reordered)

---

CHANGELOG.md
app/build.gradle

This fixes a problem where the in-app log files were not getting updated correctly. Instead of appending to the log file it seems that the last line of the log file was just getting replaced.
It seems this started occurring because Sentry does [byte-code manipulation to some of the File I/O classes](https://docs.sentry.io/platforms/android/configuration/integrations/file-io/). I'm not clear on exactly what they're doing that is causing this problem, but turning that off seems to get our logs working again.
> **Note**
> I believe we should include this as a beta-fix since it basically makes the app logs that get sent with support requests useless. For that reason, I'm targeting the `release/7.24 branch`. Let me know if you disagree.
Fixes #394 
2. Do some things that would …

Turn off Sentry's file IO tracing

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/PodcastListViewModel.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/VideoViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/PlayButtonListener.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudBottomSheetViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerBroadcastReceiver.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerReceiver.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/NotificationBroadcastReceiver.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/WarningsHelper.kt

| 📘 Project: #261 | 📘 Continuation of: #343) |
|:---:|:---:|
> **Warning**
> The PR targets release/7.24 branch
This PR 
1. Explicitly passes `PlaybackSource` instead of setting it on the `PlaybackManager` so that we're sure of where those sources are coming from - da6367c3555639746a7cfad0bd4760ed256e684d
2. Explicitly passes `PlaybackSource` from `warningsHelper.streamingWarningDialg(...)` as suggested in https://github.com/Automattic/pocket-casts-android/pull/343#discussion_r983907170
3. Identifies a few `unknown` playback sources: `up_next`, `media_button_broadcast_search_action`, `chromecast`, `auto_play`, `auto_pause`. 
- `auto_play`,  `auto_pause` sources are skipped from tracking.
-  For `chromecast`, I'm only tracking the cast-connected scenario. Current screen source is tracked …

Identify and skip/track few unknown playback sources

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfItem.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfTouchCallback.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

| 📘 Project: #261  | 
|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/293
This adds events for the "player shelf" actions:
- `player_shelf_action_tapped`: When the user taps on one of the actions located in the player shelf or overflow menu
- `player_shelf_overflow_menu_shown`: When the user taps on the vertical `...` button and the overflow menu is displayed
- `player_shelf_overflow_menu_rearrange_started`: When the user taps the Edit button and the overflow menu enters rearrange mode
- `player_shelf_overflow_menu_rearrange_action_moved`: When the user moves an action in during a rearrange
- `player_shelf_overflow_menu_rearrange_finished`: When the user exits the rearrange mode
1. Play an episode if you're not already
3. Tap each of the …

Track player shelf events

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt

> **Warning**
> Targets release/7.24
Starting Android 13, there can be [more playback controls](https://developer.android.com/about/versions/13/behavior-changes-13#playback-controls) in the `mediastyle` notification. With the current set of custom actions, `mark_as_played` action has started displaying at the end of the notification. An accidental tap on it can mark the episode as played causing a poor user experience. 
This PR reorders `mark_as_played` action below the `star` action so that the `star` action takes precedence. 
Slack convo: p1665681166247159-slack-C02A333D8LQ
Before | After
-----| ----
N/A

Update custom media action order for mediastyle notification

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragment.kt

This change fixes the issue on the light theme that the status bar icons are hidden because they are the same color as the bar. I noticed this when I was working on the Google Sign In but it also affects the share podcasts page. 
| --- | --- |
| ![Screenshot_20221017_152738](https://user-images.githubusercontent.com/308331/196094534-54c02649-f2c9-48cc-9dd9-5db672651cc0.png) | ![Screenshot_20221017_153316](https://user-images.githubusercontent.com/308331/196094550-3bcec50c-226e-48c4-a859-2cbce651987d.png) |
| ![Screenshot_20221017_152745](https://user-images.githubusercontent.com/308331/196094614-a8881b94-7509-4b52-b145-92e39a68342c.png) | ![Screenshot_20221017_153323](https://user-images.githubusercontent.com/308331/196094584-f4e5bd70-6fda-4c3b-ab61-b53a7a6801f2.png) | …

Fix status bar colors

---

fastlane/env/user.env-example

Adds some info about the kind of token needed to the example user env file so the user knows what kind of tokens they need to add. If you think there's a better place to provide this information, please feel free to just update this PR directly.
I do not know if these are the correct token permissions, but I was able to successfully run the `new_beta_release` script with them. I based these permissions on https://github.com/woocommerce/woocommerce-android/blob/trunk/scripts/release-management-prechecks.sh#L53-L55.

Add token info to user.env-example

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adding the following events:
* `filter_multi_select_entered`
* `filter_multi_select_exited`
* `filter_multi_select_all`
* `filter_multi_select_all_above`
* `filter_multi_select_all_below`
1. Open the Filters tab and tap on Filter with multiple episodes to bring up the episode list
2. Long press on an episode to enter multiselect mode
3. ✅  Observe the event `filter_multi_select_entered`
4. Long-press on an episode to bring up the select above/below modal
5. Tap on "Select all above"
6. ✅ Observe the event `filter_multi_select_all_above`
7. Long-press on an episode to bring up the select above/below modal
8. Tap on "Select all below"
9. ✅ Observe the event `filter_multi_select_all_below`
10. Tap on the three-dots to open the overflow menu
11. Tap on "Select all"
12. ✅ Observe the event …

Add Tracks filter events for multiselect

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/res/layout/activity_main.xml
base.gradle
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/BottomSheetContent.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/ModalBottomSheet.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/localization/src/main/res/values/strings.xml

|:---:|
This PR adds a `Compose` modal bottom sheet that prompts the user to check their End of Year. Design (and tablet) is not covered in this task and will be done in a future PR.
2. Run the app
3. ✅ Check that a bottom sheet appears with two buttons: "View My 2022" and "Not Now"
4. ✅ Tap "Not Now" and ensure the bottom sheet collapses
5. Re-run the app
6. When the bottom sheet appears, tap "View My 2022"
7. ✅ Ensure that nothing happens ("View My 2022" is not yet connected to any screen)
8. Rotate the device to landscape mode
9. ✅ Ensure that modal bottom sheet does not collapse and spreads to landscape mode
10. Rotate the device to portrait mode and tap outside the modal view
11. ✅ Ensure that …

End of Year: Add modal structure

---

modules/features/account/build.gradle
modules/features/discover/build.gradle
modules/features/filters/build.gradle
modules/features/podcasts/build.gradle
modules/features/profile/build.gradle
modules/services/compose/build.gradle
modules/services/preferences/build.gradle
modules/services/repositories/build.gradle
modules/services/servers/build.gradle
modules/services/ui/build.gradle
modules/services/views/build.gradle

Just a tiny bit of cleanup to make it easier to see whether a specific module dependency is already declared.
The only change here that is more than moving lines around is the removal of a duplicate declaration of the analytics dependency inside the profile module.
- [N/A] Should this change be included in the release notes? If yes, please add a line in CHANGELOG.md
- [N/A] Have you tested in landscape?
- [N/A] Have you tested accessibility with TalkBack?
- [N/A] Have you tested in different themes?
- [N/A] Does the change work with a large display font?
- [N/A] Are all the strings localized?
- [N/A] Could you have written any new tests?
- [N/A] Did you include Compose previews with any components?

Organize dependency declarations

---

gradle.properties

Build caching is off by default in Gradle
Details https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable

Enable gradle build cache when building pocket casts

---

modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt

Some podcasts don't have an expected next episode date. This happens for shows with an inconsistent release schedule. Previously it would show "Next episode" with no date. Now that section is completely hidden.
Before:
After:
For context, this is what it looks like for episodes where the next date is predicted (both before and after this change)

Hide next episode date if unknown

---

gradle.properties

Disable unused Android Gradle Plugin features to speed up builds
Defaults are documented here:
https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/BuildFeatures?hl=en

Disable unused Android Gradle Plugin features

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt

Setting animate to true so the animation is played when isPlaying changes state
Fixes #207

Fix for fullscreen player button not animating

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt

Just spotted this minor issue, looks like a bad copy paste maybe 😄
The initial value for the skip backwards setting was using the skip forwards value instead of the skip backwards value.

Initial value for skip backwards setting uses the skip forwards value

---

CHANGELOG.md
app/src/main/AndroidManifest.xml

I missed adding the `POST_NOTIFICATIONS` permission when I [updated us to target Android 13](https://github.com/Automattic/pocket-casts-android/pull/312). That meant that our app wouldn't be allowed to post notifications on Android 13 devices 😞 
> **Warning**
> I think this should be a new hotfix, so I created a `release/7.24.2` branch and am targeting that with this PR. I created a separate PR to pull this change into `release/7.25` for a 7.25 betafix release.
Fixes #430 
1. Install on a device running Android 13
2. Verify that if you go into the systems app settings for Pocket Casts that the notifications toggle can be turned on

Add POST_NOTIFICATIONS permission to 7.24.2 release

---

CHANGELOG.md
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Theme.kt

Background color in the compose theme was slightly different to the background color used in non-compose screens
Fixes #251 
Attached matching screenshots from the ones seen in the linked issue with the correct background color:

Fix for different background in Compose theme

---

CHANGELOG.md
app/src/main/AndroidManifest.xml

See https://github.com/Automattic/pocket-casts-android/pull/436 for the description of this PR. This PR is just bringing that hotfix change into the 7.25 release.
> **Warning**
> Note that this is targeting the `release/7.25` branch.

Add POST_NOTIFICATIONS permission to 7.25 release

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt

The webview in the Help & Feedback section was affected by the user's display size settings, which was causing the buttons in the Get in touch modal to overlap. Setting the textZoom to 100 will alleviate the problem on that particular webview. 
Fixes # (Help & Feedback: Get in touch: Buttons overlap out of the container #114)

Sets textZoom to 100 for webview

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/helper/ShowNotesHelperTest.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ShowNotesHelper.kt

A bug occurs in the show notes when a URL contains a text formatted like a timeskip. In this scenario, the text should not be replaced, as it will break the URL.
Fixes #145
I wrote a method that checks whether a potential timeskip is in a URL by finding the nearest HTML closing tag to the potential timeskip. 
I have also written a new test that checks the exact string the issue occurred on.
Video:
https://user-images.githubusercontent.com/116375788/197280193-75359b20-fa41-480e-b8ab-e389556aa872.mp4

Do not replace timeskip when it is in a URL

---

CHANGELOG.md

This just adds a change log entry for an external contribution.

Added a changelog for Help & Feedback buttons being hidden when using text zoom

---

.github/ISSUE_TEMPLATE/feature_request.yml

I updated the label's name from "feature" to "feature request" to make it more descriptive in GitHub, and that seems broke this template so that it no longer adds the "feature"/"feature request" label. I assume this change will fix that.

Update feature request issue template label

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt

System bar wasn't disapearing on full screen after when user tapped on screen
Fixes #115

Fix issue when system bar didn't disappear on full screen video player

---

docs/pull-request-guidelines.md

- Fixes the link for pull request template in `pull-request-guidelines.md`
- Without the fix, the link doesn't redirect to the correct page

Fix pr template link

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/ExportSettingsFragment.kt
modules/features/settings/src/main/res/xml/preferences_export.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt

Added a new OPML import option to import subscriptions from an url
Fixes #480 
https://user-images.githubusercontent.com/22520267/197674251-33ddb923-1f6c-460e-8a19-3d1ef7ff9e34.mp4

Added a new OPML import option to import subscriptions from an url

---

.buildkite/pipeline.yml
CONTRIBUTING.md
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/ComposableBase.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/Extensions.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/ViewModelBase.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/config/ViewModelConfigControlPlayback.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/TimberDebugTree.kt

Have CI start running Spotless so that our formatting conventions are enforced even if a contributor does not have [our pre-commit hook](https://github.com/Automattic/pocket-casts-android/blob/main/scripts/git-hooks/pre-commit.sh) installed.
You can see the formatting check job failing on CI for this branch until I added [709d3fc](https://github.com/Automattic/pocket-casts-android/pull/473/commits/709d3fcdce0afdbea7d262923ce08fe3ac9fa950) to the branch, which fixes the formatting issues currently on `main`: https://buildkite.com/automattic/pocket-casts-android/builds?branch=update%2Fspotless-on-ci
I am a bit concerned that, as I understand it, external contributors cannot see the logs for the Spotless check because they would need access to our Buildkite org. I could see that leading to …

Adding formatting check to CI

---

app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/SignInStateTest.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SignInState.kt

When a user has paid for Plus the sponsors are removed from the discover section. There was an issue that these sponsors were shown after a user had cancelled their paid Plus subscription but it hadn't expired. The change fixes this issue.
We could start checking the expiry date but then we would need to rely on the device time. A safe way seems to be to let the Plus expire the next time the server is called. 
I had trouble testing this as I could buy Plus from my development builds, so instead I wrote some tests.
1. Subscribed to monthly Plus 
1. Confirmed paid placements were removed in Discover
1. Cancelled Plus subscription
1. The Paid Placements had reappeared in Discover

Fix Plus features not working after cancelled but not expired.

---

modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/ComposableBase.kt

As the first time I've ever run an Android application locally or touched a Kotlin file, I'll call this a win.
I plan to follow up on additional improvements to this UI to make it resemble the filters tab, however, that will likely take me a bit as a novice mobile developer so I wanted to push this minor tweak first :)
Related to #471 (does not close)

Add margin to Tasker plugin UI

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/OpmlExporter.kt

Improve nullability of OpmlExporter by using the already null-checked file instead of global var when sharing files - this is in preparation of converting `FileUtil` to Kotlin.
Fixes # (issue)

improve nullability of OpmlExporter when sharing files

---

modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/ComposableBase.kt

The Spotless check is failing. This change fixes that.
```
[2022-10-25T21:04:36Z] FAILURE: Build failed with an exception.
--
| [2022-10-25T21:04:36Z]
| [2022-10-25T21:04:36Z] * What went wrong:
| [2022-10-25T21:04:36Z] Execution failed for task ':spotlessKotlinCheck'.
| [2022-10-25T21:04:36Z] > The following files had format violations:
| [2022-10-25T21:04:36Z]       modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/ComposableBase.kt
| [2022-10-25T21:04:36Z]           @@ -164,9 +164,11 @@
| [2022-10-25T21:04:36Z]            ····fieldContents:·List<TaskerInputFieldState.Content<*>>,
| [2022-10-25T21:04:36Z]            ····onFinish:·()·->·Unit
| [2022-10-25T21:04:36Z]            )·{
| [2022-10-25T21:04:36Z]           -····Box(modifier·=·Modifier
| …
```

Fix Spotless error

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/network_security_config.xml

Makes it easier to use something like Charles proxy to inspect our https calls on debug builds.
I followed the instructions from these two sources:
- [Android documationation](https://developer.android.com/training/articles/security-config#TrustingDebugCa)
- [Charles Proxy documentation](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/)
When testing this on release builds I did get [this crash](https://sentry.io/organizations/a8c/issues/3693580607/?project=6711064&referrer=release-issue-stream) a couple of times, but then it went away and I couldn't recreate it. Not sure if I was just doing something weird with my build or what was going on there.
1. Follow instructions for installing Charles certificate on your device
2. Set your device up to proxy through …

Trust user certificates on debug builds

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/LongPressOptionsFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout/fragment_long_press_options.xml

Redesign the long press option in the fullscreen player to match the rest of the bottom sheet design
Continuation of this work https://github.com/Automattic/pocket-casts-android/pull/451, think all the bottom sheets in the player have the same design now 😄 
Fixes #31 
https://user-images.githubusercontent.com/22520267/197683072-ce296e1f-1d3e-469c-b7e2-608834450ff6.mp4

Redesign the long press option in the fullscreen player

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/FilterSelectFragment.kt
modules/services/views/src/main/res/layout/fragment_filter_select.xml

Fix for wrong title on the filter select screen "Choose podcasts" -> "Select filters" (match iOS design)
- Added separate layout since the filter select screen was using the podcast select layout resulting in the incorrect title
Hide filters option in podcast settings if no filters available to assign the podcast to (match iOS behaviour)
Fixes #49

Fix podcast filter title and hide filter option if no filters available

---

modules/features/endofyear/build.gradle
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesScreen.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/di/EndOfYearModule.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/EndOfYearStoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/Story.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryFake1.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryFake2.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/389
This PR adds a data source to populate the Stories view with stories and also adds a few gestures.
Currently, it just updates the background color of the StoryView. Different story views will be added in future PRs.
https://user-images.githubusercontent.com/1405144/197767780-76d7537a-fac9-40a6-a361-f2222a04e237.mp4
2. Run the app
4. ✅ Check that each story is shown for 2s and that the story indicator (the rectangles at the top) are reflecting the state
5. ✅ Tap and hold, check that the current story is "paused". The rectangle stop progressing and the story doesn't change
6. ✅ While …

End of Year: Add stories datasource + gestures

---

modules/features/endofyear/build.gradle
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/SegmentedProgressIndicator.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesScreen.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/EndOfYearStoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/Story.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryFake1.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryFake2.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/storyviews/StoryFake1View.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/storyviews/StoryFake2View.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/adapter/SearchPodcastViewHolder.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EndOfYearManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/397
Creates "dummy" stories based on randomly generated podcasts and episode. This PR also adds support for dynamic story lengths.
Same as the previous tasks, the designs here are not final and are mainly placeholders.
2. Run the app
3. When the prompt appears tap "View my 2022"
4. ✅ A list of podcasts should appear ¶
5. Wait for 2 seconds
6. ✅ Notice that the next story starts displaying a random episode as the longest played episode
7. Wait for 3 seconds (dynamic time set for the second story)
8. ✅ Notice that stories progress ends
9. Play around with previous/ next taps
10. ✅ Notice that stories are skipped to correct positions
¶ …

End of Year: Generate stories with dummy data + support dynamic lengths

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTracker.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnonymousBumpStatsTracker.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/IdentifyingTracker.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/Tracker.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/73.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BumpStatDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BumpStatsDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/AnonymousBumpStat.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bumpstats/BumpStatsTask.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/bumpstats/AnonymousBumpStatsRequest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/bumpstats/WpComServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/bumpstats/WpComServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt

This adds the ability to anonymously bump a stat. We need this for purposes of allowing users to opt-out of analytics while still allowing us to get the data we need to be able to provide to paid sponsors. 
The only data that is provided with these events are:
1. An event name
2. The time of the event
3. Any specific properties about the event (i.e., the id of the list that the user interacted with in the discover feed)
The second part of this work will involve providing anonymous daily unique stats, which I will address in a follow-up PR. This sets us up to drop Firebase as an analytics provider, and allows us to do a better job of restricting the data we collect.
1. Load the app
2. Go to the discover screen and perform the the following actions:
1. Subscribe to a podcast
2. Tap on "Show …

Anonymous Bump Stats (part 1)

---

modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt

This removes flaky tests inside `StoriesViewModelTest` that checks the progress indicator position. 
I'll consider re-adding them once I address their flakiness.

EoY: Remove flaky tests

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/FirebaseAnalyticsTracker.kt

This removes the bump stats usage of firebase.
> **Note**
> I have this PR is targeting the `release/7.26` branch.
Make sure that we're handling the analytics opt-out appropriately:
1. Turn ON sharing of analytics in `Profile` -> ⚙️ -> `Privacy` -> `Analytics`
2. Go to the discover page and scroll around, click around a bit
3. ✅ Observe that the app logs show various "Analytic event" logs from [here](https://github.com/Automattic/pocket-casts-android/blob/4f154218212ef2f0a34e5ff17b1588ea4f375e83/modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/FirebaseAnalyticsTracker.kt#L267).
4. Turn OFF sharing of analytics in `Profile` -> ⚙️ -> `Privacy` -> `Analytics` 
5. Go to the discover page and scroll around, click around a bit
6. ✅ Observe that there are no …

Remove bump stats

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesScreen.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/EndOfYearStoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/Story.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/SnapShot.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryFake1View.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryFake2View.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtilWrapper.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/404
This PR
- Generates an image for the latest story and passes it to the share intent.
The image generation uses Android's `view.drawToBitmap()` function. Selected story's sharable composable is converted to `ComposeView` and laid out into `AndroidView` otherwise an exception is thrown: `java.lang.IllegalStateException: View needs to be laid out before calling drawToBitmap()`
It only captures the visible screen.
The share button click action invokes a callback that generates the bitmap, saves it, and opens it in `share` view. 
- Two other changes includes in this PR:
- Fix weird state noticed in https://github.com/Automattic/pocket-casts-android/pull/495#issuecomment-1292676258 …

End of Year: Story snapshot and share

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt

Store the state of the mini player when recreating the MainActivity so that the mini player animation can be disabled when changing the theme.
Fixes #25 
1. Navigate to Appearance settings
2. Select a theme different from the currently applied theme
3. Mini player should not animate
https://user-images.githubusercontent.com/20568035/198835613-b27c9045-0dd0-426f-bc44-8c3008ef6778.mp4

PC-I25: Prevent Mini Player From Animating When Changing Theme

---

CHANGELOG.md
app/src/main/AndroidManifest.xml
app/src/main/res/xml/locales_config.xml

Added basic support for Android 13 per-app language preferences
https://developer.android.com/guide/topics/resources/app-languages#app-language-settings
Users can select their preferred language for each app through the system settings. They can access these settings in two different ways:
Access through the System settings:
Settings > System > Languages & Input > App Languages > (select an app)
Access through Apps settings:
Settings > Apps > (select an app) > Language

Added basic support for Android 13 per-app language preferences

---

app/src/main/res/xml/network_security_config.xml

When adding the network-security-config for debug builds, Android apparently also applied a new default to disable clear text traffic for all builds. 😞 You [warned me](https://github.com/Automattic/pocket-casts-android/pull/472#pullrequestreview-1155477910) about something like this @geekygecko ! 🙂 😭 
I think adding this should cover us (FWIW: it's also what [the WordPress Android does](https://github.com/wordpress-mobile/WordPress-Android/blob/trunk/WordPress/src/main/res/xml/network_security_config.xml)).
Alternatively, we could just remove the network security config entirely. I kind of like keeping it myself to make intercepting traffic during development with a proxy easier, but obviously it's caused us problems once already, so I don't feel strongly, and I'm fine just removing it if …

Allow cleartext traffic

---

modules/features/endofyear/build.gradle
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesScreen.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/EndOfYearStoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryListenedCategories.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryTopListenedCategories.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedCategoriesView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/ListenedCategory.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/413
This PR
- Adds two new stories:
* Total categories listened
* Top 5 categories listened
PS: Design not covered, ignore hard-coded strings and design in `StoryView`s
- Attempts to fix story speed issue - ab33f966a4a03aaa6e8258539e2cfbd0f7f93ff6
2. Run the app and login with an account that has a Listening History with at least a few items
4. Skip the first story
5. ✅ Check that the second story shows the total number of categories you listened to
6. ✅ Check that the third story shows the top 5 categories you listened to with the number of different podcasts for each one
1. Set …

End of Year - Show different categories listened

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/EndOfYearStoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryListenedNumbers.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedNumbersView.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/ListenedNumbers.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/414
Adds a story that shows the number of listened podcasts and episodes. (Designs not covered)
1.  Set `END_OF_YEAR_ENABLED` feature flag to `true` in `base.gradle`
4. Skip to the fourth story
5. ✅ Check that the number of played podcasts and episodes is shown
N/A (Added placeholder layouts and strings)

End of Year - Show number of listened podcasts and episodes 

---

CHANGELOG.md
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/base/ViewModelBase.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/config/ViewModelConfigControlPlayback.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/playplaylist/config/ViewModelConfigPlayPlaylist.kt

The Tasker plugin code has an issue that only occurs when code is minified (ie in release builds) that is fixed here. This bug is preventing the Tasker actions from being used at all.
1. Build app with ```minifyEnabled true```
2. Try using any Pocket Casts Tasker action from Tasker
3. Check that it doesn't crash anymore

Fixed crashes with Tasker plugin actions when using minified code

---

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

Auto subscribe is enabled in the main app since the default return value from the settings preferences is set to true instead of false. From some comments I've seen, auto subscribe is only meant to be enabled in the automotive app.
Fixes #544 
1. Open the discover tab and click on any random podcast you aren't subscribed to
2. Play an episode
3. Go back to the podcasts list, and you will notice you are now subscribed to the podcast

Fix for auto subscribe enabled in main app

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java

`ShareCompat` takes care of granting URI permissions so the share sheet can display preview images.
Without this, the share sheet can't (reliably) show preview images.
See https://issuetracker.google.com/issues/173137936
1. Run the app
1. When the prompt appears, tap "View My 2022"
1. Tap "Share"
|Before|After|
|-|-|
|![pocket_casts__share_story__before](https://user-images.githubusercontent.com/218061/200147535-95763d93-7748-4610-94ae-b031aa75ced4.png)|![pocket_casts__share_story__after](https://user-images.githubusercontent.com/218061/200147539-a85f65b5-1ef3-43b0-b2f6-54c53f2a3cee.png)|
Side note: As can be seen in the screenshot, the transparent background is not working that well for the share sheet. You could extend …

Use `ShareCompat.IntentBuilder` to create share intent

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/EndOfYearStoriesDataSource.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/stories/StoryListeningTime.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListeningTimeView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopPodcastView.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/TopPodcast.kt

|:---:|
Add the design for the "listening time" story.
* In order to display some podcasts on this screen, top 10 podcasts are retrieved and then display the last 3.
* Displays dynamic background but does not add any gradient.
4. Navigate to the second story
4. ✅ Check the design
|Pixel 5| Pixel 2|
|----|-----|
| <img width = 320 src="https://user-images.githubusercontent.com/1405144/200987481-10e169d1-009c-4fe0-af7f-04740325f594.png"/> | <img width = 320 src="https://user-images.githubusercontent.com/1405144/200986203-083dbc41-c22e-47f7-96e6-bd33eb66a42c.png"/> …

End of Year: Listening time story design 

---

modules/services/localization/src/main/res/values/strings.xml

|:---:|
This adds EoY project strings for localization (taken from [iOS Strings](https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/en.lproj/Localizable.strings#L3276)).

End of Year: Add strings

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/util/StoryModifierExtensions.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/SegmentedProgressIndicator.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedCategoriesView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListeningTimeView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastImage.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/ListenedCategory.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/453
Adds the design for the "listened categories" story.
* The podcasts cover displayed are determined by getting the list of top categories and reversing it, picking the top 1 podcast for each of them
* Background is picked from the middle podcast in the stack (without any gradient)
4. Navigate to the third story
4. ✅ Check the design
| Phone (Pixel 5) |
| -------- | 
|  <img width = 320 src="https://user-images.githubusercontent.com/1405144/201099562-1486674c-935d-4471-9155-d7680e0eba87.png" …

End of Year: Listened categories design 

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ShareableAssetProvider.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ShareableTextProvider.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/SnapShot.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/LongestEpisode.kt

| 📘 Project: #410  |
|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/478
Adds text content for each story shared and for the top podcast(s) and longest episode add a link to them.
How the shared content is handled is up to the app. Some apps work fine with images + text, and some do not. E.g. Facebook app only allows sharing an image. 
3. Check your 2022 EoY stats (either by tapping "View My 2022" on the modal or going to Profile and tapping the card there)
4. When the first story appears, tap "Share"
5. Share to Notes or Twitter
6. ✅ Check the content and the image for the shared story
7. Repeat these …

End of Year: Share text

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/CategoryPillar.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/utils/StoryModifierExtensions.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
modules/features/endofyear/src/main/res/drawable/rectangle.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/468
Adds the design for the top categories story.
4. Navigate to the 4th story
4. ✅ Check the design
| Pixel 5 | Nexus 7 (2012)|
|----|---|
- Any jetpack compose components I added or changed are covered by compose previews

End of Year: Top categories story design 

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
base.gradle
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/EndOfYearLaunchBottomSheet.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/ModalBottomSheet.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/474
In order to provide better End of Year stats next year, it's required to create an account to see 2022 End of Year stats.
3. Logout
4. Re-run the app
5. ✅ The 2022 prompt should appear, even though you're logged out
6. Tap "View my 2022"
7. You should be prompted to login or create an account
8. Login (or create an account)
11. ✅ The stories should appear
You should see the same behavior when tapping the card under Profile. If you're logged in, the stories should appear. If not, the login/sign up screen should appear.
I also updated min …

End of Year: Require login

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/ListenedCategory.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/TopPodcast.kt

|:---:|
Updates db queries to match with iOS:
1. Use distinct on queries: https://github.com/Automattic/pocket-casts-ios/pull/528
2. Exclude empty categories from top categories: https://github.com/Automattic/pocket-casts-ios/pull/515. 
I tested it by running old and new queries that included podcast uuids with empty and non-empty categories in the where clause. Old query returned the category with empty title and new one did not.

End of Year - Update queries

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/HistoryManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

My listening history sync for the end of year stats was taking 94 seconds, this change speeds it up to 14 seconds. I did this by adding podcasts in parallel and instead using the full podcast JSON to load the episodes rather than calling the server for each individual episode.
Also I have changed the loading page from a circle progress spinner to a linear progress bar. This makes it feel like there is an end rather than with the circular spinner it feels like it's never going to end. 
3. Login to your sync account
4. Re-run the app
5. Tap "View my 2022"
6. ✅ The linear progress bar should appear, followed by the end of year story
https://user-images.githubusercontent.com/308331/202955649-914ac5fa-59 …

Speed up the listening history sync

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/services/localization/src/main/res/values/strings.xml

|:---:|
Adds retry button on error. 
3. Login to your sync account
4. Re-run the app
5. Enable airplane mode
6. Tap "View my 2022"
7. Notice error screen is displayed with retry button
8. Disable airplane mode
9. Tap retry button
10. Notice that stories are loaded.
https://user-images.githubusercontent.com/1405144/202994175-e1a2026d-4dde-4659-9f2a-a4a4116e91eb.mp4

End of Year: Add retry action

---

CHANGELOG.md
base.gradle
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt

|:---:|
This PR enables EoY feature.

End of Year: Enable feature

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/HistoryManager.kt

This change fixes the issue that the end of year history sync would add episodes which no longer exist. This caused an issue because the episodes don't have their sync information so a user would see their played will come back as unplayed.
1. Logout and clear the app
2. Login to your sync account
3. Open the end of year stats
4. ✅ Check your end of year stats still look correct

Don't add listening history episodes which on longer exist.

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt

| 📘 Project: #410  |
| --- |
This fixes an occasional crash when at the time of sharing, the activity from where stories are launched, is moved to the background and killed due to low memory. On returning from share, the activity is recreated and stories are reloaded, but restarting the paused timer, and trying to update the current story when stories are still loading, crashes the app.
The fix ensures that the timer to switch to the next story doesn't start when stories are still loading. Once stories are loaded, the timer starts again.
1. Enable "Don't keep activities" in device developer options
3. Go to Profile tab and tap "Your Year in Podcasts"
6. When the stories appear, tap "Share"
7. …

End of Year: Fix occasional crash on returning from share

---

modules/features/account/build.gradle
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearch.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt
modules/services/images/src/main/res/drawable/plus_simple.xml
modules/services/localization/src/main/res/values/strings.xml

| --- |
Adding search button functionality to the onboarding recommendations screen
I've added the ability for the user to avoid the debounce on the search by tapping the search key on the soft keyboard in 02dd06635dfe33cb3b53ec2992b8a7a9a25900e8. This is a new behavior for the app, but I thought that if the user went to the trouble of tapping the search key, it would be a better user experience and not too much of a strain on our servers to kick off the search immediately.
When tapping on a podcast to subscribe, It can take a bit of time for the podcast manager to reflect that the podcast has been subscribed to, particularly on slow internet connections. Since the UI is listening for these updates from the podcast manager, the UI can be slow to update.
We could avoid …

Onboarding: Recommendations Search

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/HistoryManager.kt
version.properties

Includes EoY bug fixes: https://github.com/Automattic/pocket-casts-android/pull/605, https://github.com/Automattic/pocket-casts-android/pull/606

Merge release 7.27-rc-3 to main

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

| 📘 Project: #410  |
| --- |
This hides the share button from the first and last story.
1. Run the app and make sure you're logged in to an account with a few items on Listening History
2. Go to Profile tab and tap "Your Year in Podcasts"
3. Notice that first and last stories do not show the share button.
P.S. I also added tracking (`🔵 Tracked: end_of_year_story_retry_button_tapped`) for retry button 
which was added in [this PR](https://github.com/Automattic/pocket-casts-android/pull/597). 
https://user-images.githubusercontent.com/1405144/203697957-6ca5328d-0660-46e0-9b7b-f5d3336f9434.mp4

End of Year: Hide share from first and last story

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt

|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/533
This PR fixes 2 issues to match iOS behavior:
* Order top podcasts by total time played instead of number of episodes.
* Track when the user tap the Profile's EOY card
1. Run the app
2. Check your stories
3. ✅ Check your top podcasts
4. Dismiss stories
5. Go to profile
6. Tap the card
7. ✅ `end_of_year_profile_card_tapped` should be tracked

End of Year: Fix to match iOS podcasts ordering

---

.buildkite/pipeline.yml
.buildkite/release-builds.yml
.github/workflows/gradle-wrapper-validation.yml

In https://github.com/Automattic/bash-cache-buildkite-plugin/pull/34 we introduced our own script to validate the Gradle Wrapper which uses the [official documentation](https://docs.gradle.org/current/userguide/gradle_wrapper.html#manually_verifying_the_gradle_wrapper_jar) for its implementation. This PR uses that script to add a prerequisite step to validate the Gradle Wrapper in both pipelines.
The main reason we decided to add our own script as opposed to using the official Github Action was to be able to validate the Gradle Wrapper before running any of the Buildkite steps. As discussed in that PR, there are some edge cases our script doesn't cover. Furthermore, because it's a custom implementation, there is always a chance that it gets outdated. Therefore, we are adding the official …

Gradle Wrapper Validation

---

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt

Effects bottom sheet flickers to the expanded state as the user drags the bottom sheet. The `ensureExpanded()` function is called when the player state changes which can cause the bottom sheet to expand while being dragged. Updated the `BaseDialogFragment` to monitor the dragged state of the bottom sheet and skip setting the expanded state if the user is actively dragging the bottom sheet.
Fixes #571 
1. Play any podcast episode
2. Tap on playback effects to open the bottom sheet
3. Drag the bottom sheet down as seen in the issue

Fix for effects bottomsheet flickering to the expanded state while being dragged

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt

This fixes EoY modal that keeps popping up when opening the app when the user is not logged into the app.
Fixes #622
1. Sign out of your Pocket Casts account
2. Close the app
3. Re-open it and notice the pop-up
4. Dismiss the popup
5. Close the app
6. Re-open the app, close it again
7. Notice on the second time you re-open the app, the Pop-up is not reshown
https://user-images.githubusercontent.com/1405144/205042056-b57bc883-a258-4bb3-b2f3-e9e5848854d5.mp4

End of Year: Fix modal keeps popping up when opening the app (logged out state)

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/res/layout/activity_main.xml
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/EndOfYearLaunchBottomSheet.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bottomsheet/ModalBottomSheet.kt

This PR attempts to fix talkback issues after End of Year launch modal bottom sheet is shown.
From the issue description: 
> The only way to navigate is to use the swipe left/right on the edge of the screen gestures.
It felt strange that we could navigate through talkback by swiping on the x-axis, which means after the modal was dismissed, talkback focus was moved from the bottom sheet to the screen elements. I wonder if this behavior was due to one of the compose modal bottom sheet issues ([1](https://issuetracker.google.com/issues/180101663), [2](https://issuetracker.google.com/issues/230039401)).
As a workaround, I remove EoY compose modal bottom sheet once it is hidden. And re-add it when it is needed again with minimum changes to the existing logic.
>**Warning**
PR targets …

Accessibility: Fix talkback after EoY modal bottom sheet is hidden

---

CHANGELOG.md
dependencies.gradle

This updates Cast SDK to the latest version which supports new media controls style.
[Cast Release Notes october-10,-2022](https://developers.google.com/cast/docs/release-notes#october-10,-2022)
> Updated [MediaNotificationService](https://developers.google.com/android/reference/com/google/android/gms/cast/framework/media/MediaNotificationService) with [Media controls in System UI](https://source.android.com/docs/core/display/media-control).
Fixes #578
> **Warning**
Targets release/7.28
1. Open the app and play an episode.
2. Open "Now Playing" screen.
3. Select Chromecast from the options at the bottom.
4. Check that on the lock screen or notification player, skip forward/skip back buttons are shown while casting.
- …

Fix skip forward/ backward buttons not showing in media notification while casting

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/UserEpisodePodcastSubstitute.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/extensions/Podcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncJob.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt

This avoids an issue I've noticed where if Android Studio is set to automatically add unambiguous imports it will immediately import one of these fields if it sees, for exampple, a uuid field used that hasn't been initialized.
This might avoid a bug where we accidentally have this substitute uuid imported and used somewhere we don't intend to use the substitute.
As long as the app compiles, this should be good since this was a pretty straightforward automated refactoring. Going above and beyond would be to make sure you can play a user-added file.

Give substute fields more descriptive names

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaActionTouchCallback.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaNotificationControlsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/features/settings/src/main/res/layout/adapter_media_action_item.xml
modules/features/settings/src/main/res/layout/adapter_media_action_title.xml
modules/features/settings/src/main/res/layout/fragment_media_notification_controls.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Dialog.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Settings.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt

Add support for media notification controls configuration to support Maximum 3 icons.
Fixes #590 
1. Setup Android Auto emulator https://developer.android.com/training/cars/testing#test-auto
2. Connect the phone using USB
3. Play An episode
4. Open full screen player on auto
5. Click on option (more vert) icon.
6. There will be 3 action displayed
7. Now you can prioritize this action
8. Go To Profile > Settings > General > Defaults.
9. Click on Media Notification controls under defaults setting.
10. Now drag and prioritize your preferred action from the following [ Archive, Mark As Played, Play Next, Playback Speed, Star] options.
11. There will be 2 action on Android 13 media notification player and 3 actions on android auto.

Fix media notification controls configuration to support 3 icons

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt

Adding setup account screen analytics to the initial screen in the onboarding flow.
1. Turn on the onboarding flag in `base.gradle`.
2. Hardcode the `Continue With Google` button to show by commenting out [this if-check](https://github.com/Automattic/pocket-casts-android/blob/dae23f0da1e2dfb2a8be6057faff148ce875417a/modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt#L137).
3. Open the app and load the Initial onboarding screen.
4. Verfiy that the following event is immediately sent: `setup_account_shown, Properties: {"flow":"initial_onboarding"`
5. Verify that tapping on "Continue With Google" fires `setup_account_button_tapped, Properties: {"flow":"initial_onboarding","button":"continue_with_google"`
6. Verify that …

Update analytics for account setup screens

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/podcast/PodcastSubscribeImage.kt
modules/services/localization/src/main/res/values/strings.xml

| --- |
Add the trending section to the recommendation screen
1. Enable onboarding in `base.gradle` file. You may want to consider updating the startDestination [here](https://github.com/Automattic/pocket-casts-android/blob/2c6b39dccba6eb67aa643e17e59fdc3df59db437/modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt#L49) to be `OnboardingRecommendationsFlow.route`.
2. Open the onboarding recommendations screen
3. Observe that you can scroll through the trending podcasts for your region
4. Observe that tapping on any of the podcast subscribes/unsubscribes to that podcast
https://user-images.githubusercontent.com/4656348/206279048-5405ab23-c988-4639-b519-8c4109f2d8de.mov

Onboarding: recommendations trending section

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ProfileCircleView.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/String.kt

Displays gravatar on the profile screen.
1. Create an account in gravatar.com and set your avatar (if you don't have one)
2. Run the app
3. Login with your email
4. Check the Profile tab
5. ✅ It should show your Gravatar
6. Tap on the gravatar + email view
7. ✅ It should show your Gravatar in a slightly bigger size
8. Logout
9. Login with an account without gravatar
10. ✅ The app won't show any gravatar avatar and it will fallback to the way it was before
not_signed_in | without_plus | plus_small
---|--|--
without_plus_big | plus_big
--|--
- All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- Any jetpack compose components I added or changed are covered by …

Display gravatar on profile

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
base.gradle
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

| --- |
This turns on the onboarding feature so it can go out to our open beta testers in 7.29.
I considered leaving this turned off for debug builds by default and having a feature flag that could be used to turn it on for debug builds in order to not make development more difficult, but since this only gets presented a single time after a fresh install (and can be dismissed with a single button tap), I decided that probably wasn't necessary. Happy to add a flag if you disagree though.
Just make sure the feature loads up on a fresh install. Everything else has already been tested, so no other specific testing is needed for this change. Don't hesitate to give the feature a bit of smoke-testing if you're up for it though.

Onboarding: remove feature flag

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingCreateAccountPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingForgotPasswordPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingForgotPasswordViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLogInViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

| --- |
This is moving the analytics logic out of the navigation composable and into the view models for the specific pages. I'm making that change because I don't think it makes sense for the navigation composable to be responsible for analytics like I had it before. Not only does it make the navigation composable more complex, but it also makes it more difficult to reuse the composable views, which we'll be doing once we replace the main app account-creation and plus-upgrade screens with the new screens from the onboarding flow.
1. On load, the `create_account_shown` event is sent
2. Either (a) swiping back or (b) tapping the back arrow sends `create_account_dismissed`
1. On load, the `signin_shown` event is sent
2. Either (a) swiping back or (b) tapping the back …

Onboarding analytics: sign in, create account, forgot password, and recommendations

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt

Adds a safety check so that EoY modal is not shown to newly signed-up users (who do not have a listening history) after the onboarding flow is complete.
While this check is added in MainActivity [here](https://github.com/Automattic/pocket-casts-android/blob/main/app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt#L202), I noticed that EoY modal was shown after creating a new account through the onboarding flow. I updated the initial value for showing the launch modal to consider the listening history eligibility.
1. Create a new account using the onboarding flow.
2. Proceed to the welcome screen and click `Done` button.
3. Notice that EoY modal is not shown. 
- I have considered whether it makes sense …

EoY: Update initial value for the launch modal to check listening history

---

CHANGELOG.md

I forgot to add a release note for the new onboarding flow when I finally turned it on. Note that this PR is targeting the release/7.29 branch.

Add onboarding flow release note

---

CHANGELOG.md
modules/features/podcasts/src/main/res/layout/view_podcast_header_bottom.xml

Enable autolink on podcast descriptions to allow you to click on urls. This should also support email addresses, but I haven't found any podcasts to test that on.
1. Open a podcast with a link in their description. Up First and Waveform have them.
2. Ensure you can tap on them to open the browser
3. Ensure the color of these links matches the tintColor of the podcast

Enable autolink for podcast descriptions

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastCover.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

| --- |
This populates login artwork icons from local DB podcasts if they're available. 
1. Comment out `lines 191, 193, and 195` in `MainActivity` so that onboarding flow is launched every time when app restarts
2. Login with an account with some podcasts
3. Restart the app
4. Notice that 
- Artwork is populated with icons from random podcasts available in local DB
- If local DB podcasts count is less than the max count (6), then default icons are shown
- All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- Any jetpack compose components I added or changed are covered …

Onboarding: Support login dynamic artwork

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt

| --- |
Replacing the Not Now button with a close `X` icon like we use elsewhere in the app.
p1671147105113759/1671091615.388669-slack-C02A333D8LQ
> **Note**
> This PR is targeting the `release/7.29` branch.
Verify that tapping the X button completes the onboarding flow and send off the event: `setup_account_dismissed, Properties: {"flow":"initial_onboarding"`
| Light | Dark | Rose | Indigo |
| --- | --- | --- | --- |
| ![Screenshot 2022-12-16 at 9 07 33 AM](https://user-images.githubusercontent.com/4656348/208116158-969e02a7-e058-47a4-b6a1-ef372d1aa60c.png) | ![Screenshot 2022-12-16 at 9 09 18 AM](https://user-images.githubusercontent.com/4656348/208116324-62d1cf32-9213-4a52-b77b-2fe2dff4382b.png) | ![Screenshot 2022-12-16 at 9 07 52 …

Replace "Not Now" button with X icon

---

dependencies.gradle

Using the `0.28.0` version of Accompanist's SystemUiController was increasing our compose version transitively from `1.2.1` to `1.3` (see note [here](https://github.com/google/accompanist#compose-versions)). I didn't intend to make that change in a beta release, so bumping that version down to `0.25.1` to get us back to `1.2.1`.
Just do a quick smoke test of the onboarding flow to verify that it still works as expected.

Lower version of accompanist

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
base.gradle
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt

This PR disables 2022 EoY feature.
>**Warning**
> Targets 7.29
1. Launch the app.
2. Login with an account with some listening history (>5mins).
3. Go to the `Profile` screen.
4. Notice that EoY profile screen card is not displayed.
5. Relaunch the app.
6. Notice that EoY launch modal is not shown.

Disable 2022 EoY

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DiscoverModel.kt

| --- |
Adds rows for our categories to the onboarding recommendations screen based on @adamzelinski 's [feedback](https://github.com/Automattic/pocket-casts-android/issues/524#issuecomment-1347960181).
I implemented this so that the sections are loaded one at a time. I thought this would be good for users with slow connections so that they didn't have to either wait for all the sections to load or have the sections moving around on them as the network responses came back. Let me know if you think there's a better way to handle this.
1. Open a fresh install of the app so that the onboarding flow is triggered. You may want to also [make this change](https://gist.github.com/mchowning/f60082a45df993dd7c0fffbecb60585b) so that the onboarding flow just goes straight to the …

Add categories to recommendations screen

---

CHANGELOG.md
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt

This change improves the Automotive search. One of our partners has reported search issues. The previous search was based on our voice search which I don't believe works well in this use case. 
Fixes #663
Fixes #664
1. Deploy the Automotive module to an Automotive emulator
2. Tap the search icon (next to the settings cog)
3. Search for 'Tech News'
4. Scroll down to 'Daily Tech News Show'
5. Tap the row
6. Tap the first episode
7. Pause the episode, close the player, tap the back button twice
8. ✅ Verify on the 'Podcasts' tab that the podcast 'Daily Tech News Show' is listed (on Automotive by default, you are subscribed to podcasts)
9. Tap the search icon again
10. Clear the search text
11. Search for 'Tech News'
12. ✅ Verify the top result is now 'Daily Tech News Show' (your subscribed to …

Improving Automotive search

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/services/images/src/main/res/drawable/ic_info_outline.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

This PR disables download for [newly supported HLS stream](https://github.com/Automattic/pocket-casts-android/pull/679) on the episode details screen.
Parent Issue #670
1. Add an RSS link that produces HLS sources (e.g. https://ohdieux.ligature.ca/rss?programme_id=672).
2. Tap on one of the HLS source episodes to go to the episode details screen.
3. Notice that the download button is disabled and displays a message that playback from downloaded HLS files is not supported.
- Any jetpack compose components I added or changed are covered by compose previews
- with different themes
- with a landscape orientation
- with the device set to have a large …

Disable download for newly supported HLS streams

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountAuth.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/PromoCodeFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/PromoCodeViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UploadEpisodeTask.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/AuthResultModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/HttpExceptionMessage.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/LoginResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/login/LoginRequest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/login/LoginResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/register/RegisterRequest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/register/RegisterResponse.kt

As part of the Single Sign-On change, this upgrades from the legacy user login and register endpoints. The iOS app has been using these new endpoints for a long time, so I don't see any danger in switching to them.
This change also switches over to using Retrofit and Coroutines. Hopefully, we can get rid of the [ServerManager](https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt) class as it feels very dated when compared with Retrofit.
1. Clean install the app
2. Tap 'Sign up' on the welcome screen
3. Enter an existing Pocket Casts account email and any password
4. Tap 'Create Account'
5. ✅  Verify an error message is displayed
6. Enter a new email which doesn't exist
7. Tap 'Create …

Switched to using the new user login and register

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingPlusBottomSheet.kt

Fixes the purchase/subscribe button in the [new onboarding flow](https://github.com/Automattic/pocket-casts-android/issues/524) so that its text only indicates there is a free trial if the selected plan has a free trial (issue originally observed [here](https://github.com/Automattic/pocket-casts-android/pull/694#issuecomment-1379932790)).
> **Warning**
> I believe this fix needs to be a hotfix or a betafix. I'm leaning toward making it a hotfix since it is addressing misleading text on probably the most important button in the app for converting users to be subscribers, but let me know if you think a betafix makes more sense.
1. Set the app up to have a free trial available
2. Go through the onboarding flow to the plus upgrade screen
3. Tap "Unlock All Features"
4. Observe that the button …

Update subscribe button text depending on trial availability

---

fastlane/Fastfile
modules/services/localization/src/main/res/values-ko/strings.xml

This pull request adds the Korean language to the import from GlotPress. This happens as part of the `finalize_release` deployment step.
The translations aren't available yet, but here is the empty GlotPress ready to be added.
https://translate.wordpress.com/projects/pocket-casts/android/ko/default/

Add the Korean language

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt

This PR should improve the reliability of our episode sync.
In my testing, all the calls to sync episode data were failing and a NoSuchElementException was getting logged. I think there are two separate causes of this, and fixing either of them solves the issue. This PR includes both fixes.
The [first fix](https://github.com/Automattic/pocket-casts-android/commit/0b84d1502f3e372c2d10f2768fc981ea77eb2863) is that although we were calling `onErrorReturnItem` with our sync poller (which syncs the episode status every 60 seconds), that handler would complete the polling, causing sync to stop. The better approach is to handle the error inside the `concatMap` call because that way the polling doesn't stop if there is an error.
The [second …

Improve episode sync error handling

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountActivity.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateActivity.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt

This PR fixes the placeholders in the onboarding recommendations always reflecting a dark theme even when the theme was light.
This issue was caused by the fact that the theme was not being set on the `OnboardingActivity`, which meant that the app would not be able to get the theme information from the activity context [here](https://github.com/Automattic/pocket-casts-android/blob/d1502d9bf89fec3e19098f3ec78bc41e1473b447/modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt#L41-L57).
In fixing this, I noticed that `MainActivity` was calling `theme.setupThemeForConfig(this, resources.configuration)`, but our other Activities were calling `setTheme(theme.activeTheme.resourceId)`. As a result, when the app was set up to respect the system dark/light mode, …

Fix recommendations placeholder color and have Activities respect dark/light mode

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingWelcomePage.kt

| --- |
On the onboarding welcome screen, this makes the entire row for the newsletter to be tappable as opposed to just having the toggle itself being tappable.
1. Create a new account and advance through the onboarding flow until you get to the welcome screen
2. Confirm that tapping on the newsletter toggle still works
3. Confirm that tapping anywhere on the newsletter row flips the toggle
https://user-images.githubusercontent.com/4656348/213260497-8ca69293-e31f-4100-817f-cf6642f517be.mov

Make entire newsletter row tappable

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingCreateAccountPage.kt
modules/services/localization/src/main/res/values/strings.xml

| --- |
This PR updates the buttons in the onboarding flow to be consistent with [Material Guidelines for buttons](https://m3.material.io/components/buttons/guidelines):
> Use sentence case for button label text, capitalizing the first word and proper nouns.
When signing up for a new account in the onboarding flow, verify the following buttons have been updated to sentence case:
| Screen | Updated button |
| --- | --- |
| Create Account | Create account |
| Recommendations | Not now |
| Plus Upgrade full screen | Not now |
| Plus Upgrade full screen | Unlock all features |
| Plus Upgrade purchase modal (with free trial selected) | Start free trial & subscribe |
| Welcome screen | Find my next podcast |
| Welcome screen | Import podcasts |
<details>
<summary>Create …

Use sentence case for onboarding buttons

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt

Temporarily fixes unresponsive media notifications in Android 13 (#161).
According to [this](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/Service.java#830), 
>  [...] If {@link #STOP_FOREGROUND_DETACH} is supplied, the service's association
with the notification will be severed. [...] 
For the steps outlined in https://github.com/Automattic/pocket-casts-android/issues/161#issuecomment-1191971420, where the service is stopped, I am unable to restart it from the notification media actions if  `STOP_FOREGROUND_DETACH` flag is passed to `stopForeground(...)`.
Until we figure out a proper fix, this PR reverts to using legacy flags with `stopForeground(...)`.
1. Force close the app 
2. Start playback from within the app
3. Stop playback from within …

Temporary fix for unresponsive media notifications in Android 13

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt

| --- |
This PR updates the recommendation screen so that when the user taps to subscribe to a podcast, the UI doesn't wait for the db to reflect the subscription and instead immediately updates to reflect the new subscription state.
1. Create a new account so you are taken to the recommendation screen
2. Tap on a podcast to change it's subscribe status
3. Observe that the UI updates to reflect the new subscription status without any delay
https://user-images.githubusercontent.com/4656348/213270868-f17e2436-a4f6-483b-8e83-7b29af20a11b.mov

Immediately update subscribed UI when user taps

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt

| --- |
Adds a drop shadow to the part of the recommendations screen with the button so it is visually cleaner as content scrolls under the button.
I picked the `8.dp` drop shadow because it looked about right to me, but let me know if you think another value would be better.
1. Create a new account so you are taken to the recommendations screen
2. Confirm that the bottom part of the screen with the `Not Now`/`Continue` button has a slight drop shadow now.
| --- | --- |
| ![Screenshot 2023-01-18 at 1 26 04 PM](https://user-images.githubusercontent.com/4656348/213263805-c574ac42-3605-4a0b-a40f-c79a4f0c0913.png) | ![Screenshot 2023-01-18 at 1 25 00 PM](https://user-images.githubusercontent.com/4656348/213263597-653cd95e-e117-4158-98ab-c0a7628d61a4.png) …

Add drop shadow for recommendations button

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt

| --- |
This is a follow-up to https://github.com/Automattic/pocket-casts-android/pull/717. It adds the same immediately-update-the-UI logic to the recommendations search screen, as suggested [here](https://github.com/Automattic/pocket-casts-android/pull/717#issuecomment-1396468512).
1. Create a new account so you are taken to the recommendation screen
2. Perform a search from the recommendations screen
3. Tap to subscribe-to or unsubscribe-from one of the search results
4. Observe that the UI updates to reflect the new subscription status without any delay
https://user-images.githubusercontent.com/4656348/213539741-91dfc7e1-0085-4160-9bd8-2303c02c446b.mov

Update UI immediately when tapping on search result

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastEffectsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adds tracks for the podcast settings screen:
- `podcast_settings_feed_error_tapped`: When the user taps the feed error item in the podcast settings
- `podcast_settings_feed_error_update_tapped`: When the user taps the update button on the feed error alert
- `podcast_settings_feed_error_fix_succeeded`: If the feed error issue was fixed
- `podcast_settings_feed_error_fix_failed`: If the feed error issue failed for any reason
- `podcast_settings_auto_download_toggled`: When the user toggles the Auto Download option
- `podcast_settings_notifications_toggled`: When the user toggles the Notifications option
- `podcast_settings_auto_add_up_next_toggled`: When the user toggles the Add to Up Next option
- `podcast_settings_auto_add_up_next_position_option_changed`: When the user changes the …

Podcast settings tracks

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaNotificationControlsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlusSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml

Adds tracks for the plus and general section of the settings.
In addition, I updated the "Open Player Automatically" setting to use sentence case like the rest of our settings in 5b9186b8fdb8183b16c8548d4d2b2ba8979c7449.
- `settings_plus_shown` - When the settings plus view is displayed
- `settings_plus_upgrade_button_tapped` - When the user taps any upgrade button on the view
- `settings_plus_learn_more_tapped` - When the user taps the learn more button
- `settings_general_shown` - When the general settings section is displayed
- `settings_general_row_action_changed` - When the user changes the row action option
- `settings_general_episode_grouping_changed` - When the user changes the Podcast Episode Grouping option
- `settings_general_archived_episodes_changed` - When the user changes …

Tracks for Plus and General settings

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt

Adds tracks for notification settings.
In addition, 3705d8942d0be83a7c1e6f3de6d3d4922afd33f4 fixes an issue I noticed where the wrong string label was being used for the vibrate-never setting.
1. Go to the Profile Tab → ⚙️ → Notifications
2. Tap on "Notify me"
3. ✅  Observe the event `settings_notifications_new_episodes_toggled, Properties: {"enabled":[true|false], ... }`
4. Leave "Notify me" toggled on
5. Tap on "Choose podcasts"
6. Change the podcast selection
7. Tap back
8. ✅  Observe the event `settings_notifications_podcasts_changed`
9. Tap on Actions, change the selected actions, and tap "Ok"
10. ✅ Observe the event `settings_notifications_actions_changed, Properties: {"action_archive":[true|false],"action_download":[true|false],"action_play":[true|false],"action_play_next":[true|fal …

Notification Settings Tracks

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adding tracks for the notification settings.
1. Go to the Profile tab → ⚙️ → `Appearance` and check that the following events are being sent.
2. Change your theme to be light: `settings_appearance_theme_changed, Properties: {"value":"default_light", ...}`
3. Toggle "Use Android Light/Dark Mode": `settings_appearance_follow_system_theme_toggled, Properties: {"enabled":true|false, ... }`
4. Select the dark icon: `settings_appearance_app_icon_changed, Properties: {"value":"dark", ... }`
5. Toggle "Show artwork on lock screen" using either the toggle or by tapping on the row: `settings_appearance_show_artwork_on_lock_screen_toggled, Properties: {"enabled":true|false, ... }`
6. Toggle "Use embedded podcast artwork" using either the toggle or by tapping on the row: …

Tracks for notification settings

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/features/search/build.gradle
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsSource.kt

- `search_performed`: When the user enters text and the search is performed
- `search_failed`: If the search results fail for any reason
- `search_result_tapped`: When the user taps one of the items in the search results list
2. Tap on the Podcasts tab
4. Search for a podcast that you are subscribed to
5. ✅ Verify the event isn't performed until you've finished typing
6. ✅ `🔵 Tracked: search_performed ["source": "podcast_list"]`
7. Tap on one of the podcast you search for
8. ✅ `🔵 Tracked: search_result_tapped ["result_type": "podcast_local_result", "uuid": "UUID", "source": "podcast_list"]` - Where the UUID is the uuid of the item that you tapped
9. Tap back, and search for a podcast that you are not subscribed to
10. ✅ `🔵 Tracked: search_result_tapped ["result_type": …

Track search events

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModelTest.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/ComposeUtils.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FolderLocation.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/StorageOptions.kt

Adding tracks for the storage settings.
I also did a minor refactor here so that instead of passing around a `Pair<String, String>` (which would have become a `Triple<String, String, String>` in order to include the analytics info), we're now passing around the `FolderLocation` object, which contains those three strings. I think this is much clearer and makes it more difficult to mix the strings up.
1. Open the app, go to Profile tab → ⚙️ → `Storage & data use`
2. ✅ Observe the event `settings_storage_shown`
3. Tap on "Clear download cache"
4. ✅ Observe the event: `settings_storage_clear_download_cache`
5. Tap on "Store podcasts on"
6. Select a storage option and tap "Ok". 
7. ✅ Observe the event `settings_storage_location, Properties: {"location":"sd_card|phone|custom", ... }`
8. On a …

Storage settings tracks

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adding tracks for the auto archive settings
1. Open the app and to to the Profile tab → ⚙️ → `Auto archive`
2. ✅  Observe the event `settings_auto_archive_shown`
3. Change the setting for "Archive played episodes"
4. ✅ Observe the event `settings_auto_archive_played_changed` with an appropriate `value` property reflecting your selected setting
5. Change the setting for "Archive inactive episodes"
6.  ✅ Observe the event `settings_auto_archive_inactive_changed` with an appropriate `value` property reflecting your selected setting
7. Toggle "Include starred episodes"
8. ✅ Observe the event `settings_auto_archive_include_starred_toggled, Properties: {"enabled":true|false, ... }`

Auto archive settings tracks

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingCreateAccountPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingForgotPasswordPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingWelcomePage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/import/OnboardingImportStartPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsStartPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingPlusFeaturesPage.kt

Updates the "shown" tracks events for the onboarding flow so that they do not get resent on configuration changes.
Fixes # 
Go through the onboarding flow for creating a new account. Make sure that rotating the device doesn't resend the "shown" event for the screen (if that screen has a shown event—there are a couple that don't have one). 
As you go through the flow, make sure you check the initial import screen as well (you have to select that option from the welcome page to see it, you won't automatically see it if you just click through everything).

Prevent onboarding "shown" tracks from firing on configuration changes

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/PodcastOptionsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoAddSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistUpdateAnalytics.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Bundle.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/FilterSelectFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/viewmodels/FilterSelectViewModel.kt

Adding tracks for the auto download settings.
1. Within the app, go to the Profile tab → ⚙️ → `Auto download`
2. Observe the `settings_auto_download_shown` is sent when you open the screen
3. Observe that a configuration change (i.e., rotating the phone to landscape) does _not_ resend the event.
4. Toggle "Episodes added to Up Next" and observe the event `settings_auto_download_up_next_toggled, Properties: {"enabled":true|false, ... }`
5. Toggle "New episodes" and observe the event `settings_auto_download_new_episodes_toggled, Properties: {"enabled":true|false, ... }`
6. With "New episodes" toggled on, tap on "Choose podcasts"
7. Change the podcasts that are set to auto download new episodes
8. Exit the podcast selection screen to return to the Auto downloads settings
9. Observe that when …

Add auto download settings tracks

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoAddSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoAddSettingsViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/PodcastAutoUpNextConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt

Adds tracks for the auto add to Up Next settings.
While doing this, I also switched us to using an `AutoAddUpNext` enum in place of passing around `Int`s. To avoid that change requiring a database migration or cause any issues I am using a `TypeConverter` that converts the new enum into the same `Int` values that we were persisting in the database before. That means that there should be no difference as far as sqlite is concerned. 
With that said, I did separate out the parts of this change that directly impacted the database into a separate commit (81ce815ca809d6f8df6d1396bf00fdbd54eb4a64)—I realize that is the slightly riskier change and if you'd like me to revert that part of the PR, just let me know.
The most likely way I could have messed something up with this is by making a simple …

Tracks for auto add to Up Next settings

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/HelpViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adds the shown event for the Help screen in settings.
1. Go to the Profile tab → ⚙️  → `Help & feedback`
2. Observe that the event `settings_help_shown` is sent
3. Verify the event is not resent with configuration changes

Add shown even to help fragment

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/SearchHistoryDaoTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/74.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/SearchHistoryDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/SearchHistoryItem.kt

Part of: #752
This PR
- Adds a new table `search_history` (+ migration) to the database
- Adds unique indexes to restrict duplicate `search term`/ `podcast`/ `folder`/ `episode` search history item insertion
- Includes `podcast`/ `folder`/ `episode` search history item details as embedded objects (with minimum details to render corresponding search history item) so that search history can be displayed for them even when there's no corresponding local `podcast`/ `folder`/ `episode` in the database.
- Adds `SearchHistoryDao` for search history item operations
- findAll
- insert (or replace)
- delete
- deleteAll
Note: Targets a feature branch to allow modifying the `search_history` table until the feature is ready.
- Ensure that tests in `SearchHistoryDaoTest` cover important scenarios:
- …

Search history: Data layer

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt

Adding tracks for the file setting screen.
1. Log into a Plus account
2. Go to the Profile tab → `Files` → click on `⋮` → `File settings`
3. ✅ Observe the event `settings_files_shown`
4. Toggle "Auto add to Up Next"
5. ✅ Observe the event `settings_files_auto_add_up_next_toggled, Properties: {"enabled":true|false, ... }`
6. Toggle "Delete local file"
7. ✅ Observe the event `settings_files_delete_local_file_after_playing_toggled, Properties: {"enabled":true|false, ... }`
8. Toggle "Delete cloud file"
9. ✅ Observe the event `settings_files_delete_cloud_file_after_playing_toggled, Properties: {"enabled":true|false, ... }`
10. Toggle "Auto upload to cloud"
11. ✅ Observe the event `settings_files_auto_upload_to_cloud_toggled, Properties: {"enabled":true|false, ... }`
12. Toggle "Auto download …

File settings tracks

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/about/AboutFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

This adds the shown event for the about sceen.
1. Open the app and go to the Profile tab → ⚙️ → `About`
2. ✅ Observe the event `settings_about_shown`
3. Verify that rotating the screen does not resend the event.

About screen tracks

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/chromecast/CastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/chromecast/ChromeCastAnalytics.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Menu.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Toolbar.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragmentToolbar.kt

Adding tracks for chromecasting from the app.
1. With a chromecast device available on your local wireless network...
2. Go to the Podcasts tab
3. Tap the chromecast icon in the toolbar (this will only appear if there are chromecast devices available)
4. ✅ Observe the event `chromecast_view_shown, Properties: {"is_connected":false, ... }`
5. Select a speaker to cast to
6. ✅ Observe the event `chromecast_started_casting`
7. Tap the chromecast icon again
8. ✅ Observe the event `chromecast_view_shown, Properties: {"is_connected":true, ... }`
9. Tap "Stop casting"
10. ✅ Observe the event `chromecast_stopped_casting`
In each of the following, verify that tapping on the chromecast icon sends the event `chromecast_view_shown, Properties: {"is_connected":true|false, ... }`.
1. Toolbar on the page …

Chromecast tracks

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/SearchHistoryDaoTest.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/adapter/PodcastSearchAdapter.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/adapter/SearchFolderViewHolder.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModel.kt
modules/features/search/src/main/res/layout/fragment_search.xml
modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModelTest.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalDivider.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImageSmall.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/SearchHistoryDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SearchHistoryEntry.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/searchhistory/SearchHistoryManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/searchhistory/SearchHistoryManagerImpl.kt

Part of #752 
This PR 
- Creates a new page to display the search history
- Adds selected podcast from the search results list to search history
- Adds selected folder from the search results list to search history 
(** folder search history is displayed conditionally based on subscription state and selected tab - Podcasts or Discover)
- Adds search term to search history
- Displays search results
- Adds X button click action
Notes:
- Ignore UI, it does not meet the spec yet
- Episode search, search history row click action, clear all are not added, they'll be taken up separately 
- Login with a Plus account having folders
- Go to Podcasts tab and search for a folder 
- Tap folder in search results
- Go back to Podcasts screen and tap search button again
- ✅ Notice that folder is shown in …

Search history: Display results

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryClearAllConfirmationDialog.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModel.kt
modules/services/localization/src/main/res/values/strings.xml

Part of #752
This adds 
- Navigation for search history item
- Clear all header and a confirmation dialog with a search history threshold (size > 3).
Note: Ignore UI, it doesn't exactly match the specs.
- Build a search history of different types (podcast/ folder/ search term) of at least 4 items 
- Tap on each search history item separately
- ✅ Notice that the appropriate page is opened for podcast, folder and the search is re-triggered for the search term
- Return to search history and tap on Clear All
- ✅ Notice that a confirmation dialog is shown (count > search history threshold)
- Tap on Delete button in the dialog
- ✅ Notice that search history is cleared
- Search another query
- Tap on Clear All
- ✅ Notice that search history is cleared (no dialog shown since count < threshold) …

Search history: Navigation and Clear All

---

.buildkite/release-builds.yml

This PR increases the priority of release builds on Buildkite. This will be useful so that release builds won't get delayed if the CI queue gets backed up. The default priority of a build is 0, so increasing the release builds to 1 will put them before other builds: https://buildkite.com/docs/pipelines/managing-priorities

Add higher CI priority to release builds

---

CHANGELOG.md
app/src/main/AndroidManifest.xml
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

This pull request is a implementation proposal regarding issue #723. The authorization check for notifications will be done upon starting the MainActivity (after the login and register interface), and will only run on devices equipped with Android 13 and higher.
Hope this works for you!😊
CC: @lucile98-ode (thanks for the help)
Fixes #723 
2. Register or login (or skip this step, it doesn't matter)
3. The app asks permission for sending notifications (won't show on your screen if you already launched with Android 13 and already approved this permission)

Ask notif permission

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adding tracks for episode sorting and grouping
1. Open up the episode listing page for a podcast
2. Tap the `⋮`
3. Change the sorting of the episodes
4. Observe the event `podcasts_screen_sort_order_changed, Properties: {"sort_order":___, ... }`
5. Tap the `⋮` again
6. Change the grouping
7. Obseve the event `podcasts_screen_episode_grouping_changed, Properties: {"value":_____, ... }`

Episode grouping and sorting tracks

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt

Tracks when the you-ve-been-signed-out screen. is presented because the token refresh fails.
This turned out to be trickier than I expected because this notification originates from the settings module, but the analytics module depends on the settings module, so I can't directly make the analytics call from the settings module. Instead, I'm passing a function from the server module to be invoked when the UI is presented.
1. The easiest way to trigger this condition is to build with [this change](https://gist.github.com/mchowning/7e56ca55560fa6007c6c147284dcb455) so that we request an invalid token.
2. Attempt to log in to an account from in the app
3. Observe the sign in error notification is presented
4. Observe the event: `signed_out_alert_shown`. Note that the event actually gets fired …

Track signout on token refresh failure notification

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Add track for pull to refresh.
1. Start the app
2. Log in with a Plus account
3. Make sure you are subscribed to at least 1 podcast
4. Go to the podcasts tab
5. Pull to refresh
6. ✅ Observe the event. `pulled_to_refresh, Properties: {"source":"podcasts_list", ... }`
7. Go to the Profile tab → Files
8. Pull to refresh
9. ✅ Observe the event `pulled_to_refresh`. The `source` property will vary depending on whether you have any files. If you have files, it should be "files" and if you do not it should be "no_files".

Track pull to refresh

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingPlusFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingPlusFeaturesViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

This changes the event name for the plus upgrade button tap.
1. With a free account, tap on the folder upgrade icon on the Podcasts tab
2. On the Plus upgrade page, tap "Not now"
3. Observe the event `plus_promotion_not_now_button_tapped, Properties: {"flow":"plus_upsell","source":"folders", ... }`

Track not now button tap

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt

This updates the app to ask the `MediRouter` to check for available Chromecast devices. This avoids the chromecast button disappearing because the `MediaRouterButton` will automatically hide itself if it thinks there aren't any chromecast devices available.
I'm making these changes based on the documentation for `MediaRouteActionProvider` available [here](https://developer.android.com/reference/kotlin/androidx/mediarouter/app/MediaRouteActionProvider).
Fixes #777 
1. Connect your device to a wireless network with at least one chromecast device available (I have multiple chromecast devices on my network, I'm not sure if that is necessary to cause the underlying bug).
2. Go to the Podcasts tab
3. ✅ Observe that the chromecast button is visible (possibly after a very short delay)
4. …

Tell media router to discover cast devices

---

CHANGELOG.md
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

Adds the `discover_shown` event.
1. Open the PC app
2. Navigate to the discover page if you're not already there
3. ✅ Observe the event `discover_shown`
4. Change the screen orientation
5. Observe that the `discover_shown` event is _not_ sent
6. Background the app
7. Reopen the app
8. ✅ Observe the event `discover_shown` is sent again

Add track for when discover is shown

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchEpisodeRow.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchFolderItem.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchPodcastItem.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/podcast/PodcastSubscribeImage.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/EpisodeItem.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/discover/EpisodeSearch.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/discover/GlobalServerSearch.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/discover/PodcastSearch.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt

Part of: #787
This PR 
- Adds podcasts and episodes layout to the new search view
- Adds episodes from the search episodes endpoint
1. Enable search improvements feature flag in `base.gradle`
2. Select `debug` build variant
3. Go to `Podcasts` tab
4. Search a term
5. ✅ Notice that the first 20 podcasts search results are shown under `Podcasts` heading
* Subscribed podcasts and folders are shown under the Podcasts section (pdeCcb-Xe-p2#comment-1431)
6. ✅ Notice that the first 20 (server) episodes search results are shown under `Episodes` heading
7. Go to `Discover` tab
8. ✅ Notice that only server results are shown for both podcasts and episodes 
1. Disable search improvements feature flag in `base.gradle`
2. ✅ Notice that old search works as expected
Note that
* Local episodes not added
* …

Inline search results - podcasts and episodes

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchEpisodeRow.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchPodcastItem.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt
modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModelTest.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/EpisodeItem.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/FolderItem.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt

Part of: #787
This PR adds episode search history row UI (pdeCcb-1iH-p2#comment-1693) and implements actions for
- Subscribe button
- Episode search result row
- Episode search history row
- Enable search improvements feature flag in `base.gradle`
- Select `debug` build variant
1. Go to `Podcasts` tab
2. Search a term 
3. Tap on plus icon for an unsubscribed podcast from podcasts search results
4. ✅ Notice that the podcast is subscribed
5. ✅ Notice in logs `Tracked: podcast_subscribed, Properties: {"source":"podcast_list_search", "uuid":UUID` where `UUID` is uuid of the podcast 
6. Tap on the check icon for the subscribed podcast 
7. ✅ Notice that the podcast remains subscribed (this is done to match the behavior on the `Discover` tab where you can only subscribe a …

Inline search results - Call to actions

---

CHANGELOG.md
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountActivity.kt
modules/features/account/src/main/res/layout-car/fragment_create_email.xml
modules/features/account/src/main/res/layout-car/fragment_reset_password.xml
modules/features/account/src/main/res/layout-car/fragment_sign_in.xml
modules/features/account/src/main/res/layout-land-car/fragment_create_email.xml
modules/features/account/src/main/res/layout-land-car/fragment_sign_in.xml
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt
modules/services/ui/src/main/res/values/styles.xml

This change does the following:
- Forces the Automotive app into car mode as some car companies don't set this and our car layout resources aren't picked up.
- The font sizes for the hint text have increased on the account pages.
- Improved the UI on the forgotten password page.
- Made sure only the dark theme is used in the Automotive version.
Fixes https://github.com/Automattic/pocket-casts-android/issues/786
- Deploy the automotive app to the Automotive emulator
- Open Pocket Casts
- Tap the settings cog
- Tap "Set Up Account" option
- Tap "Create account"
- ✅ Verify the page looks better
- Tap back and the "Sign in"
- ✅ Verify the page looks better
- Tap "I forgot my password"
- ✅ Verify the page looks better
| --- | --- |
| …

Improving the Automotive account pages

---

dependencies.gradle
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt

Updating horologist to 0.3.4
Verify that the scroll wheel still changes the volume on the player page (this doesn't seem to work with me on an emulator, but it works on a physical device).

Update horologist to 0.3.4

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditPodcastsPage.kt
modules/services/localization/src/main/res/values/strings.xml

This fixes hint text for the search bar on create folder screen
1. Launch the app and log in with a plus account
2. Go to the podcasts screen and tap on the plus folder in the app bar
3. Notice that the search bar on the "Create folder "screen has the correct hint text

Beta fix: Update search bar hint text

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchEpisodeResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchInlineResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchPodcastResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchResultsFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchFolderRow.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchPodcastItem.kt
modules/features/search/src/main/res/layout/fragment_search.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/podcast/PodcastSubscribeImage.kt
modules/services/localization/src/main/res/values/strings.xml

Part of #805 
This adds full-screen search results for podcasts and episodes.
- Enable search improvements feature flag in `base.gradle`
- Select `debug` build variant
1. Go to `Podcasts` or `Discover` tab
2. Search a term that returns podcasts and episodes
3. Tap on "Show all" from the podcasts section
4. ✅ Notice that all podcast search results are shown
5. Tap on plus (subscribe) button
6. ✅ Notice that podcast is subscribed (** To unsubscribe, you'll need to go to the details screen that displays a confirmation dialog before unsubscribing)
9. Tap on a podcast
10. ✅ Notice that podcast details are shown
11. Go back to see the search history
12. ✅ Notice that the podcast is added to search history
1. Go to `Podcasts` or `Discover` tab
2. Search a term that returns …

Full screen search results

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchInlineResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/component/SearchEpisodeRow.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/PodcastItem.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImageSmall.kt

Part of #787 and #805
This 
- Addresses search results design review comments: pdeCcb-1iH-p2#comment-1756 and
- Displays podcast and episode search results as they become available.
- Enable search improvements feature flag in `base.gradle`
- Select `debug` build variant
- Launch the app and connect to the debugger
- Filter for `.pocketcasts.net` in logs
- Go to `Discover` tab
- Search a term
- Notice that podcast and episode search results are shown as they become available ([logs](https://user-images.githubusercontent.com/1405144/222134280-de57ab89-bdb0-4ad8-a845-054cbb671b6b.png)) in search results.
https://user-images.githubusercontent.com/1405144/222135053-bbbe3122-226d-46ea-8b1e-62d0274b66e6.mp4

Search results - Design review and improvements

---

base.gradle
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchInlineResultsPage.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/FirebaseConfig.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

This adds a remote feature flag for the search improvement feature.
Prerequisite:
Replace `api_key` for client app with package `au.com.shiftyjelly.pocketcasts.debug` inside `app/google_services.json` with the API key for the debug app. 
1. Install release build 
2. Go to `Discover` tab
3. Search a term
4. Notice that both podcasts and episodes are shown in search results
5. Go to Firebase console
6. Set `feature_flag_search_improvements` to `false` for "Development App" and publish changes
7. Set `setMinimumFetchIntervalInSeconds` to 1 sec for `FirebaseRemoteConfigSettings` inside `SettingsImpl.kt`
8. Reinstall the app
9. Repeat steps 1-3
10. Notice that only podcasts are shown in search results in a vertical layout
11. Go back to Firebase console, reset …

Search Improvements - Add remote feature flag

---

CHANGELOG.md
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt

When entering skip forward and backward times in the Automotive settings area the enter / submit button adds new lines to the skip value, this change fixes that.
1. Load the Automotive app into an Automotive emulator
2. Tap on the settings cog
3. Tap Skip forward time
4. Change the time amount
5. ✅  Verify you can't tap the blue button tick button to add new lines to the amount
| --- | --- |
| ![Screenshot_20230307_155241](https://user-images.githubusercontent.com/308331/223328228-b240af63-4db8-4aad-9627-44253d0613cf.png) | ![Screenshot_20230307_155454](https://user-images.githubusercontent.com/308331/223328359-cccb2e68-08e0-4338-a584-22922b18cc03.png) |

Improve the Automotive skip settings input

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt

When opening the Up Next list in the Automotive app the podcast artwork wasn't loading, this change fixes that.
Fixes https://github.com/Automattic/pocket-casts-android/issues/813
1. Load the mobile app into a mobile emulator
2. Login or create an account
3. Add multiple episodes to the Up Next
4. Make sure the Up Next has synced to the server
5. Load the Automotive app into an Automotive emulator
6. Tap the settings cog
7. Sign into the account
8. Tap to open the full screen player
9. Tap the Up Next list icon
10. ✅  Verify the episode artwork is displayed.
| --- | --- |
| ![Screenshot_20230307_234612](https://user-images.githubusercontent.com/308331/223434630-fe8281b7-e58c-4ebe-9179-ee0be930b7ae.png) | ![Screenshot_20230307_234716](https://user-images.githubusercontent …

Fix Automotive Up Next podcast images not loading

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt

This change fixes the issue when playing an episode without a duration in the feed XML, the seek bar isn't being displayed when using the data from the Media Session. The bug was found in Android Automotive but it's repeatable on mobile too with the notification drawer. The media player reports the episode duration length once it has opened the file and updates the database. This change is now picked up and the media session duration is updated which causes the seek bar to appear.
Fixes https://github.com/Automattic/pocket-casts-android/issues/816
1. Open the mobile app
2. Search for the podcast 'Ted Talk Daily' 
3. Find an episode that has a dash '-' instead of the duration and tap play on the episode
4. ✅ Quickly open the notification drawer. Initially the seek bar won't appear but will …

Update the playing episode in the media session if the duration changes.

---

base.gradle
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/util/AutoScrollHelper.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/util/ScrollingLinearLayoutManager.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt

This adds auto scroll to discover featured carousal
**No auto scroll on default**
2. Open Discover 
3. Notice the Featured Carousel doesn't auto scroll 
**Auto Scroll**
1. Enable `DISCOVER_FEATURED_AUTO_SCROLL` feature flag in `base.gradle`
2. Open Discover 
3. Watch the Featured carousel auto scroll 
4. Watch that on the last item the carousel returns to the first item 
**Auto scroll and manual scroll**
1. Swipe to scroll the carousel forward or backwards
2. See the autoscroll continues to the next item as expected
Additionally, test that the auto-scroll timer doesn't keep running when the app is backgrounded or moving to another screen.
https://user-images.githubusercontent.com/1405144/223427758-5cc81be9-4dc0-444b-a2e2-528003072f11.mp4

Add auto scroll to discover featured carousal

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DiscoverModel.kt

This PR prepares the Discover Carousel to be able to show sponsored podcasts.
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/755
**Tracks will be tackled in a separate task.**
1. Switch to `debug` build variant
2. ✅ Make sure that `Discover` tab -> `Featured` carousel appears just fine
3. Go to `ListWebService.kt` and change line 12 to `@GET("/discover/{platform}/content-carousel.json")` (so it will use the mock)
4. Run the app
5. ✅ The carousel should appear. All the items should display the "Featured" label except the first and the fourth, which displays "Sponsored"

Load carousel sponsored podcasts

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DiscoverModel.kt

This adds tracks for the sponsored podcasts on the Discover Carousel.
1. Switch to `Debug` build variant 
2. Go to `ListWebService.kt `and change line 12 to `@GET("/discover/{platform}/content-carousel.json")` (so it will use the mock)
3. Run the app
4. Open `Discover`
5. ✅ `discover_list_impression ["list_id": "59b88279-f856-4448-9422-8680d4181704"]` should be tracked for Tracks and Firebase
6. ✅ Swipe the carousel, once the next Sponsored podcast is shown `discover_list_impression ["list_id": "e46179c2-4ef7-4ac4-9138-700fe80e2ef2"]` should be tracked for Tracks and Firebase
7. Subscribe to the first sponsored podcast
8. ✅ `discover_list_podcast_subscribe ["podcast_uuid": "f27fe110-584a-0137-f266-1d245fc5f9cf", "list_id": "59b88279-f856-4448-9422-8680d4181704"]` should be tracked for …

Carousel sponsored podcast tracks

---

CHANGELOG.md
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/FolderDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/FolderManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

Fixes https://github.com/Automattic/pocket-casts-android/issues/815 by giving users the option to clear their data when they log out on Android Automotive.
I went with the simplest UI approach here of just presenting a second pop-up when the user signs off, asking them if they want to clear their data. This could certainly be done better, but since this is addressing a bit of an edge case, I didn't want to spend too much time over-optimizing it. With that said, if you have a better idea for the UI, please let me know.
1. Sign into a Plus account on Android Automotive. 
2. Make sure the account has:
1. An episode that is currently playing
3. Some episodes in the up next queue
4. Some podcast subscriptions
5. Some custom filters
6. Some cloud files that have been uploaded under Profile → …

Add option to clear data when logging out of Automotive app

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/searchhistory/SearchHistoryManagerImpl.kt

1. Reduces search history max count to match with iOS (p1678446938002359/1678387434.322809-slack-C03JCLLR9C3)
2. Adds `search_list_shown` track (https://github.com/Automattic/pocket-casts-ios/pull/774#issuecomment-1468243355).
> **Warning**
> Targets release/7.34
It doesn't require any manual testing, it is covered by `testInsertTooManyItemsKeepsMostRecent` test.
1. Tap on the search bar in `Discover` or `Podcasts`
2. Search for something
3. Tap "Show all" on Podcasts
4. ✅ search_list_shown should be tracked with correct source (discover or podcast_list) and displaying: podcasts
5. Go back, tap "Show all" for Episodes
6. ✅ search_list_shown should be tracked with correct source (discover or podcast_list) and displaying: episodes

Search minor updates

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This logs playback state exception in Sentry as part of https://github.com/Automattic/pocket-casts-android/issues/272#issuecomment-1477121237 to explore further patreon podcast not playing consistently in Automotive.
> **Warning**
> Targets release/7.35
I tested it by throwing a playback error explicitly in a release build variant:

Log playback state exception in Sentry

---

CHANGELOG.md
base.gradle
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt

Turning on autoscroll on the Discover carousel by removing the feature flag.
internal ref: p1680117820760509/1680117264.777019-slack-C02ATC80MUM
> **Warning**
> This PR is targeting the 7.35 release branch. Even though we're close to releasing that, I'm thinking we may want to go ahead and cut a new beta so if there is any issue we have a chance to catch it before release, but let me know what you think.
Review the auto scroll testing instructions from https://github.com/Automattic/pocket-casts-android/pull/818
https://user-images.githubusercontent.com/4656348/228649029-094478c6-c4e8-4bff-8b9f-ac59eb28d163.mov

Enable carousel autoscroll

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchInlineResultsPage.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt

This PR 
- Updates scroll position to the start of the list on a new search
- Hides episodes on RSS podcast feed search
> **Warning**
> Targets release/7.35
Prerequisite: Enable search improvements (if you do not have valid `google-services.json`, return `true` from `isFeatureFlagSearchImprovementsEnabled()`)
1. Go to podcasts or discover tab search bar
2. Search for a term
3. Notice that search results are shown
4. Scroll horizontally through the podcasts search results row so that the first visible item is not the first podcast in the search results
5. Update search term 
6. ✅ Notice that the updated podcasts search results row scrolls to the first podcast in the results
7. Scroll vertically so that the first visible episode is not the first episode in the search results
8. Update …

Fix search results scroll position

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt

Adds delay to `Discover` carousel auto-scroll after changing screens.
Fixes #852
> **Warning**
> Targets 7.35
3. Go to other screen (Podcasts, Filters, Profile)
4. Go to Discover
5. Notice the carousel auto-scrolls after a delay 
https://user-images.githubusercontent.com/1405144/228784983-78f6d92e-86d0-4a0a-9852-0d7b638d2d92.mp4

Discover carousel: Add auto scroll delay on screen change

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

This sets up the notification channels on the watch so that notifications will now work. Thanks to @ashiagr for [suggesting this fix](https://github.com/Automattic/pocket-casts-android/pull/821#discussion_r1130613461).
1. Trigger a notification from the watch app. I did it by using adding these changes so that tapping on the Now Playing chip would trigger a notification.
2. Observe that the notification is presented.
[Uploading Screen Recording 2023-03-30 at 1.26.05 PM.mov…](https://user-images.githubusercontent.com/4656348/228917020-cf01b53e-2346-433e-ba16-dc9a006b980a.mov)

Set up notification channels on watch

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/theme/WearAppTheme.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/theme/WearColors.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/NotificationScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/ObtainConfirmationScreen.kt

Updates the scroll position indicator on the watch app from blue to gray. This change was suggested by @geekygecko , and I agree that the blue doesn't really seem to fit. This fix will obviously change more than just the position indicator, but I don't think we necessarily want the blue color anywhere in the watch app currently, so removing it in other places as well seems fine. I'm sure we'll be revisiting how to handle the theming in the watch app again before this ships.
This PR also extracts out some of the raw color declarations we had for wear to a single location (`WearColors`). I don't think moving these colors to a single file is a great solution, but I hope it's at least a (very) small step in the right direction and will, I hope, make it easier to further improve how we handle …

Update scroll position indicator from blue to gray-white

---

modules/services/images/src/main/res/drawable/signin.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
wear/src/main/AndroidManifest.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/theme/WearColors.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ChipScreenHeaders.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ObtainConfirmationScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/downloads/DownloadsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/downloads/DownloadsScreenViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/StreamingConfirmationScreen.kt

Add settings screen for watch app and implements a setting to give a warning before streaming an episode.
1. Pair your watch to a phone
2. Go to the settings screen in the watch 
3. Check the UI for the log in button
4. Log into the app
5. Check the UI for the log out button
6. Toggle the metered data warning on
7. Check the UI for the metered data warning on state
8. With the connected phone using a metered connection, try to play an episode on the watch (if playing from the now playing screen, the currently queued episode should play, if from the episode details screen, that episode should get loaded and played).
9. Confirm that you get a metered data warning before playback starts (you will only get this warning the first time you play a particular episode)
10. Switch the phone to an …

Add watch settings screen with metered data warning

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
base.gradle
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/StarRatingView.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/features/podcasts/src/main/res/layout/view_podcast_header_bottom.xml
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/75.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastRatingsDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastRatings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManagerImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Int.kt

This integrates with the ratings API to display ratings for podcasts.
ℹ️ PR size is big due to the large (1.4K lines) auto-generated `75.json` db schema file. 
ℹ️ There's a lot of scope for UI improvements, the PR is created to build a basic structure to show ratings. 
ℹ️ Since the PR includes DB migration with fields subject to change, it currently targets a feature branch.
2. Navigate to a podcast
3. ✅ Verify nothing displays and the app doesn't crash
4. Enable the `SHOW_RATINGS` feature flag in `base.gradle`
5. Navigate to a podcast again, ✅ verify that the app doesn't crash (notice that the star rating view is displayed without any filled stars - UI/ animation for this will get updated in a future PR (we might want to show a disabled view in case of error or …

Show ratings

---

automotive/src/main/AndroidManifest.xml

This fixes automotive app sentry meta data name. 
> **Warning**
> Targets release/7.36
I tested that the exceptions are caught in Sentry for automotive using this key ([example](https://a8c.sentry.io/share/issue/fab8a515de964f2289b3bd7e3b984062/)).

Fix automotive sentry meta data name

---

modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ChipScreenHeaders.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/UpNextOptionsScreen.kt

Adds a header with "Add to up next?" to the add to up next screen on the watch to match the Figma designs. In addition, I've made that screen scrollable since there is now more content.
The icons on this screen are different from Figma. I think these are the appropriate icons for "adding" to the up next queue (as opposed to moving something within the up next queue), so I've left them as-is. I've left a question for Adam though confirming whether that is ok, and if they need to be changed I'll do that in a separate PR.
1. Ensure that you have at least 1 episode in your Up Next queue
2. Go to the episode details screen for an episode that is not in your Up Next queue
3. Tap the add to up next button
4. Observe that you get the below screen with the "Add to up next?" header. There are no …

Add header to add to up next screen on watch

---

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Flow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ExpandableText.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

Adds an expandable section for the show notes to the episode details screen on the watch.
This is converting the HTML show notes into plain text. This seemed like the best way to deal with this for now since web views are not supported on Wear OS. This does mean that links and other HTML elements are basically not rendered, but I think this implementation is better than nothing and it's something we can address later if it proves to be a problem (I'm skeptical that many will be doing much reading of long show notes on their watch, but maybe I'm wrong).
1. Go to the episode details screen
2. Scroll down and observe that the show notes displays at most three lines and (assuming there is more than 3 lines), there is a gradient fading out the text toward the bottom
3. Tap on the show notes
4. …

Add expandable show notes to watch episode screen

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsViewModel.kt

This adds a refresh button to the watch's settings screen. I'm not sure if this is where it will end up, but I wanted to add the functionality since it will help with development.
> **Note**
> This PR builds on https://github.com/Automattic/pocket-casts-android/pull/873, so you may want to review that PR before this one.
1. Log into an account on the watch.
2. Pick one of the podcasts from the Podcasts screen and remember it
3. Log into the same account on another device
4. Unsubscribe from the podcast you picked on step 2
5. Sync the changes to the server from the other device
6. On the watch, tap the "Refresh now" button on the settings screen
7. Observe that the icon animates while the refresh is in progress
8. Once the refresh is complete, observe that the unsubscribed podcast is no …

Add refresh button to watch

---

dependencies.gradle

This updates compose version from `1.2.1 `to the latest stable version `1.4.1`.
This is mainly done to access `Compose Pager` added in [Compose Foundation Version 1.4.0-alpha03](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.4.0-alpha03).
- Randomly smoke test new screens built using Compose
- Go through release notes to see if anything is a breaking change
[Version 1.3](https://developer.android.com/jetpack/androidx/releases/compose-animation#version_13_2)
[Version 1.4](https://developer.android.com/jetpack/androidx/releases/compose-animation#version_14_2)

Update compose version

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingWelcomePage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt

This renames upgrade screens to remove an explicit plan name like "Plus" in their names. Since the change impacts 10+ classes, I extracted these simple changes to a separate branch. 
Since this does not include any user-facing changes, just make sure that CI is green.
- Since it is built upon `update/compose-version` branch, make sure it is merged before merging this branch to `main`.

Rename upgrade screens

---

CHANGELOG.md
base.gradle
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt

This follows up on https://github.com/Automattic/pocket-casts-android/pull/712 and removes the SSO feature flag. I figure we just should go ahead and remove it now because we probably won't need it again and it will be easy to add back if for some reason we do need it again.
I also added a changelog entry for SSO.
Go to the app's login screen and verify that the "Continue with Google" option is available

Remove SSO feature flag

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/ContinueWithGoogleButton.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/GoogleSignInButtonViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt
modules/features/account/src/main/res/layout-car/fragment_account.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowOutlinedButton.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt

This adds the ability to sign in with google to the automotive app.
> **Warning**
> This PR is targeting the `release/7.37` branch because I think we need to roll SSO out at the same time everywhere as much as we can. Let me know if you feel differently.
1. Go to the sign in screen (⚙️  → "Set Up Account")
2. Observe there is now a "Continue with Google" button
3. Tap "Continue with Google" and select a Google account
1. Go to the sign in screen (⚙️  → "Set Up Account")
2. Observe there is now a "Continue with Google" button
3. Either sign in to a google account on the device or on an Android phone (I didn't see how to test with a connected Android phone using the emulator, maybe you can test that @geekygecko ? )
I am seeing an issue when the automotive device is not already signed into a …

Add google sign in to the automotive app

---

app/proguard-rules.pro
base.gradle
dependencies.gradle
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoView.kt
modules/features/player/src/main/res/layout/fragment_video.xml
modules/features/player/src/main/res/layout/video_view.xml
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/extensions/MediaMetadataCompatExt.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/EpisodeFileMetadata.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyAudioProcessorChain.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyAudioRendererV2.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyRenderersFactory.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ShiftyTrimSilenceProcessor.java
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

Parent https://github.com/Automattic/pocket-casts-android/issues/887
This replaces `ExoPlayer` dependencies with equivalent `Media3` ones that now include `ExoPlayer`.
[Media3 1.0.0](https://github.com/androidx/media/blob/release/RELEASENOTES.md#100-2023-03-22) corresponds to the [ExoPlayer 2.18.5 release](https://github.com/google/ExoPlayer/releases/tag/r2.18.5). In 2ca9d942c39b6744a016d3b43114b04e116946ba, I upgraded `ExoPlayer` to the latest version r2.18.5 before migrating it to `Media3`.
- Clean Project in Android Studio
- Install and smoke test the app, I tested 
- streaming audio-only episode
- playing downloaded episode
- chrome casting an episode
- playing an episode with video (e.g. from Ted Talks HD)
- changing audio effects like playback speed, volume boost
- playing an …

Replace ExoPlayer with equivalent Media3 dependencies

---

CHANGELOG.md
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

It is possible to set the Automotive skip foward and back times to an empty string. This doesn't break the skip buttons as it will use the defaults but in the UI when you open the settings it remains blank. This change improves the input validation and doesn't accept the blank value. 
1. Tap on the settings icon
2. Tap the "Skip forward time" setting
3. Remove the numbers so the field is blank
4. Tap ok
5. Tap the "Skip forward time" setting
6. ✅ Verify the value is not blank  
<hr>
7. Tap the "Skip back time" setting
8. Remove the numbers so the field is blank
9. Tap ok
10. Tap the "Skip back time" setting
11. ✅ Verify the value is not blank
<hr>
12. Tap the "Skip forward time" setting
13. Change the skip time to another value
14. Tap ok
15. ✅ Verify the forward time setting summary …

Stop the Automotive set skip settings accepting a blank value

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoView.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CastPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/LocalPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactory.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PocketCastsPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

This is renaming our `Player` interface to `PocketCastsPlayer` in order to differentiate it from the media3 `Player`. Since that creates a pretty big diff, I thought it would be nice to just separate that out in order to make the other PRs easier to review.
I also took this opportunity to remove the unused `PlaybackManager::isStreaming` method (it's not even used on `main`) in 600d3cb590d3c96a098709a26a5df38c16db7399.
Basically this PR is just an effort to reduce the diffs in future PRs. There are no substantive changes here.
If the code changes look ok and CI is happy, then I think we're good.

Renaming Player interface in preparation for media3

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CastPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/FocusManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/LocalPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactory.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PocketCastsPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

Parent https://github.com/Automattic/pocket-casts-android/issues/887
This PR migrates
- Existing `LocalPlayer` and `CastPlayer` to implement media3 common `Player` interface.
- Local player (`ExoPlayer`) instantiation to `PlaybackService` so that it can be set on the media3 library session.
** Switching to media3 `CastPlayer` in the session will be taken up in a future PR.
- CI is green
- Media can be played

Update media3 player + migrate local player instantiation to PlaybackService

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoView.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/extensions/MediaMetadataCompatExt.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/EpisodeFileMetadata.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

When using `@UnstableApi` when we use an unstable api, anything that uses the annotated method/class will now also get a lint warning. For that reason, I think we should switch to using the not-at-all-pleasant-to-type-or-remember `@androidx.annotation.OptIn(UnstableApi::class)`. Using that does not create lint warnings for callers of the annotated class/method. That's why I was actually able to remove a number of annotations entirely in this PR.
Alternatively, we could just add a rule to ignore this lint warning throughout the project. I'm not at all strongly opposed to that, but since I didn't feel strongly I figured I'd keep the lint check so we're at least aware when we use an unstable API in a new place. Like I said, I don't feel strongly though, so if you'd rather ignore the rule …

Opt-in to UnstableApis instead of creating UnstableApis

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CastPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PocketCastsPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

The `PocketCastsPlayer::bufferedUpToMs` method is basically just exposing the `Player::getBufferedPosition` method. Since `PocketCastsPlayer` now implements `Player`, I think we can drop that method. There are other methods that we can do this with, but I limited it to just the one method for this PR so you can see what it looks like without too much noise and let me know if you're on board with moving in this direction.
The benefits of this change are that it removes some code, and gives us a more consistent interface since the `PocketCastsPlayer` would only have one method (via `Player`) for obtaining the bufferedMs position.
The negative of this change is that our implementation of `PocketCastsPlayer::bufferedUpToMs` took care of making sure it was executed on the main thread. We lose …

Remove bufferedUpToMs method

---

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt

3787dbd introduced AccessToken, missed a conversion to token.value
The latest Android beta can't download cloud files, looking in the debug log the requests being made are:
```
E 21/4 19:03:43 Invalid response returned for episode download. 400  hxxps://api.pocketcasts.com/files/url/62743f70-e11c-11ed-8408-2f2a325ada1f?token=AccessToken(value=eyJ0eX...)
```
when they should be:
```
hxxps://api.pocketcasts.com/files/url/62743f70-e11c-11ed-8408-2f2a325ada1f?token=eyJ0eX...
```
Fixes # 
Use a Plus account with files uploaded to the cloud but not on the local device, try downloading or streaming, confirm that you're no longer getting HTTP/400 responses

Fix downloading cloud files

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CastPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/LocalPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PocketCastsPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

Just trying to simplify a bit more by relying directly on the `Player` interface. Again, there's more that could be done here, but I want to keep these PRs small.
Play a podcast and skip around a bit in the episode.

Remove bufferedPercentage and handleCurrentPositionMs methods

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt

Moving downloads to be above filters on the watch list. Note that Up Next is still in this list for the time being because the pager has not been created yet. 
Internal ref: pdeCcb-2Bu-p2
1. Start up the watch app.
2. Verify that Downloads is between the "Up Next" and "Filters" chips.

Move downloads chip above filters on watch list

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt

This hides the Now Playing chip if there is nothing playing.
Internal ref: pdeCcb-2Bu-p2
1. Do a clean install of the watch app
2. Observe there is no "Now Playing" chip at the top of the watch's main list
3. Log into an account with an episode queued to play
4. Observe that the "Now Playing" chip is visible at the top of the watch's main list screen
| No episode queued | Episode queued |
| --- | --- |
| ![Screenshot 2023-04-23 at 6 11 39 AM](https://user-images.githubusercontent.com/4656348/233833656-820681f6-bae9-4a9a-b1b6-54512690456b.png) | ![Screenshot 2023-04-23 at 6 11 13 AM](https://user-images.githubusercontent.com/4656348/233833628-8267bd6d-42aa-4b4a-9c56-b025a706860c.png) |

Hide Now Playing chip if nothing is playing

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt

After testing, a manufacturer using our Automotive build needs us to hide our custom skip buttons and instead say we respond to the playback events `ACTION_SKIP_TO_PREVIOUS` and `ACTION_SKIP_TO_NEXT`.
1. Add "google" to the list of manufacturers `MANUFACTURERS_TO_HIDE_CUSTOM_SKIP_BUTTONS`
2. Deploy to the Google automotive emulator
4. ✅ Verify the skip buttons don't appear

Hide custom skip buttons for an Automotive manufacturer

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

When I [updated the table name from `episodes` to `podcast episodes`](https://github.com/Automattic/pocket-casts-android/pull/895), I didn't think to check for hardcoded queries. Turns out I should have. This fixes those.
One place this showed up was that the app would include some database errors in the logs when creating the logs file for support.

Update podcast_episodes table name in hardcoded queries

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/LoggingInScreen.kt

The logging in screen on the watch used an ellipsis to indicate overflow before. This updates that to use a gradual fade out only when the email is too long.
I was having some trouble getting this to work right, but I got some great help [in Kotlin's Slack](https://kotlinlang.slack.com/archives/C04TPPEQKEJ/p1682438604723239).
Internal ref: p1682125454156639-slack-C040S9BK7SP
1. While logged in on your phone but not logged into the watch, start the watch app
2. Observe that the "Logging in" screen shows a fade out gradient when the user's email is too long (I manually edited [this line](https://github.com/Automattic/pocket-casts-android/blob/0da3d947fac305fe9c217310e8329fd674be2630/wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/LoggingInScreen.kt#L98) to create the email …

Use fade instead of ellipsis for email overflow

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/LogsViewModel.kt
modules/features/settings/src/main/res/menu/menu_help.xml
modules/services/images/src/main/res/drawable/baseline_view_list_24.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt

This adds a screen to enable the user to more easily access their logs within the app.
> **Note**
> This PR builds on https://github.com/Automattic/pocket-casts-android/pull/910, so you may want to review that one first.
Fixes #833 
1. Go to the Profile tab
2. Tap on the ⚙️ 
3. Tap on "Help & feedback"
4. Tap on the list icon at the top of the screen
5. ✅ Observe that the logs are displayed
6. Tap on the copy icon at the top of the screen
7. ✅  Observe that the logs are copied to the clipboard
8. Tap on the Share icon
9. ✅ Observe that you can share a file with the logs (similar to what happens currently when someone contacts support through the app).
https://user-images.githubusercontent.com/4656348/234631340-cc39fce0-e5be-44a9-8e4d-9e4ea21d391a.mov

Add screen to more easily access logs

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/WearMainActivityViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FiltersScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NowPlayingPager.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt

This adds a three screen pager to the watch app. The first page will be the current page. The second page will always be the now playing screen. The third page will always be the Up Next screen.
I initially wanted to create a `Pager` at the top level and have navigation within the first page, but it looks like that [isn't really possible currently](https://github.com/google/horologist/issues/1181).
Verify that the pager works as expected and is present on the screens you would expect. Transient notification-style screens and the Settings screen are the only ones that should not have the pager. Also check that back navigation works as expected (i.e., swiping back and swiping to exit the app).
Note that you should only be able to swipe back to the previous screen if you are on the `0` page …

Add pager to watch app

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudBottomSheetViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/EpisodeImage.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserEpisodeImage.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UserEpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/UpNextScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ChipScreenHeaders.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/EpisodeChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/EpisodeChipViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NowPlayingPager.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/downloads/DownloadsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/UpNextOptionsScreen.kt

This PR updates the styling of the Up Next screen on the watch.
One trickiness I ran into here was that it does not seem possible to use horologist's scrollable components on multiple pages of a pager when the pager is inside a single navigation context (more info [here](https://github.com/google/horologist/issues/1181#issuecomment-1522555773)). I'm working around that by just hiding the time text from the Up Next screen and using a scrollable composable from foundation there. That way the time text can still be shown on the pager's "main" screen.
> **Note**
> This PR builds on https://github.com/Automattic/pocket-casts-android/pull/908, so you may want to review that first.
1. Load up the app while logged into an account with episodes in the Up Next queue
2. Swipe to the third page in …

Update watch's Up Next UI

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeDateTimeText.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This updates the watch app to handle user episodes. The first part of that is to update the `EpisodeScreen` so it can handle user episodes. The second part is implementing the FIles screeen.
> **Note**
> This PR builds on https://github.com/Automattic/pocket-casts-android/pull/909.
1. Open the app with an account that does not have any user episodes
2. Tap on files
3. Observe the UI informs you that you have no files
1. Open the app with an account that has some files uploaded to the cloud
2. Tap on files
3. Observe the UI lists all your files
4. Tap on one of the files to open the episode screen
5. Confirm the UI of the episode screen looks fine (note that files only have the "Mark played" button and there are no show notes for user episodes). 
6. Observe that the episode screen controls …

Handle user episodes

---

CHANGELOG.md
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt

This fixes a crash that occurred on Android Automotive when signing out and clearing data while playback was in progress.
Fixes #916 
See https://github.com/Automattic/pocket-casts-android/issues/916

Stop playback before signing out if clearing data

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/UpNextScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/EpisodeChip.kt

This hides the up next icons on the up next screen on the watch since the icon would be on every episode on that screen. This is also consistent with the phone's behavior.
internal discussion: p1682536583755259-slack-C040S9BK7SP
1. Go to the Up Next screen
2. ✅ Confirm that none of the episodes show the Up Next icon
3. Download one of the episodes in the Up Next queue
4. Go to the Downloads screen
5. ✅  Confirm that the episode you just downloaded is there with both the up-next icon and the downloaded icon.
| Up Next Screen | Downloads Screen|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4656348/234959100-60dbcf73-b34e-4fdc-aa7d-b6c19de8a5ab.png) | ![image](https://user-images.githubusercontent.com/4656348/234959166-279c4a49-33fe-4673-93ec-1c0062997f75.png) |

Hide up next icons on up next screen

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ClickableTextHelper.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

This introduces upgrade tiers (see this comment on tiers: pdeCcb-2fL-p2#comment-1902) and updates the new upgrade screen to display prices right away, allowing the purchase without the need to show the modal.
P.S. Skip any UI-related feedback, they'll be covered in a future PR
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/11343183/upgrade-testing-patch.patch)
2. Run the app being logged out
3. Subscribe to any podcast
4. Go to Podcasts
5. Tap the folder icon
6. ✅ You should see the upgrade screen that displays only the Plus tier plans
7. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/11343238/upgrade-testing-patch-with-patron.patch) to add new tier
8. ✅ You should see the upgrade screen that displays two features cards, one for …

Patron: Introduce tiers and remove pricing modal on upgrade screen

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/servers/account/SyncAccountTest.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/GoogleSignInButtonViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLogInViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/SignInViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt

This updates the sign-in and create-account events. I think that the SSO changes caused these to stop working the way they should.
2. Create an account using SSO
3. Observe the `user_account_created` event
4. Sign out
5. Sign in using SSO
6. Observe the `user_signed_in` event
1. Delete the account you created in the previous test
2. Create an account using that email, but with a password instead of using SSO
3. Observe the `user_account_created` event
4. Sign out
5. Sign in using email/pass
6. Observe the `user_signed_in` event
7. Sign out
8. Sign in using SSO
9. Observe the `user_signed_in` event

Update sign_in and create_account events

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt

> **Warning**
> I think this PR merits a hotfix, so I have it targeting a new hotfix branch: `release/7.37.1`.
This avoids scenarios where users migrating from a password `SignInType` to the token `SIgnInType` can get stuck in a bad state where the app will always fail to retrieve an updated access token because the app still thought the user was using a password `SignInType` so it would try to use the stored token as a password, which would fail. This causes the app to present notifications saying the user has been signed out, but the app still indicates the user is signed in apart from this error (and all the API calls would fail).
This PR essentially has two fixes for this issue...
1. d13c31b55feaf9fa12dba8bf0ce1a787c8b94283 makes it so that when a user signs in after getting one of …

Make sure app has correct `SignInType` after upgrading

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt

> **Warning**
> I am targetting the `release/7.37.1` hotfix because this seems like a completely safe change and it helps our analytics be more useful in identifying possible authentication issues. This is certainly not a critical fix, so just let me know if you think we're better off not including it in the hotfix.
This improves the situation in #927, but it does not fully fix the issue because although we no longer send the sign-out analytics event every time a logged-out user starts the app, we now can miss sending the sign-out analytics event when the user signs out of their Pocket Casts account from the account management options in the Android OS. I think this is probably not a very common thing for people to do, so this feels like a worthwhile tradeoff, but it would be good to find …

Only send sign out analytics when user was signed in

---

modules/services/images/src/main/res/drawable/ic_upnext.xml

When I [updated the up next icon to be more centered](https://github.com/Automattic/pocket-casts-android/pull/914#issuecomment-1525529334), the svg's width and height were reduced, and I didn't realize this would reduce the icon's size on the podcast settings screen. This increases the size of the new icon to be the same as the old icon.
Reported by a beta user https://pocketcastsbeta.slack.com/archives/C013F9RM6UA/p1683238245603559
> **Warning**
> Because this is a regression from 7.37, I'm targeting the `release/7.38` branch. I don't think we need to release a new beta with this though, and it can just go out with the next beta or the actual prod release.
1. Install the phone app
2. Go to a subscribed podcast
3. Tap on the ⚙️ to open the podcasts settings
4. ✅ Verify that the icon by …

Update up-next icon to be 24dp

---

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt

Follow-up PR to https://github.com/Automattic/pocket-casts-android/pull/931 implementing @ashiagr 's suggested improvement. 🙇 
I'm taking this a bit further and avoiding all sign out work when the user is already fully signed out unless this signout was manually triggered by the user. In theory, it shouldn't be possible for a fully signed out user to manually trigger a sign out, but I figured I'd leave that in as a safety hatch so if a user did somehow get into a weird state they could still possibly recover by manually triggering a sign out.
Fixes #927
2. Start the app
3. ✅  Verify there is no `user_signed_out` event
4. Sign into the app
5. Swipe the app away from recents
6. Restart the app
7.  ✅  Verify there is no `user_signed_out` event
8. Sign out of the …

Only sign out user if they have not already been fully signed out

---

modules/features/account/src/main/AndroidManifest.xml
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/SubscriptionTierPill.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/UpgradeFeatureItem.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeHelper.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeButton.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
modules/features/profile/src/main/res/layout/fragment_account_details.xml
modules/features/profile/src/main/res/values/color.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/ui/src/main/res/values/colors.xml
modules/services/ui/src/main/res/values/themes.xml

This updates account screen's upgrade banner and displays only the modal (without the full-screen features screen behind it) when the upgrade button is tapped from this banner.
Large PR size is due to
- I extracted certain components such as the pager and feature card enum from the `OnboardingUpgradeFeaturesPage` to allow for reuse in the account screen upgrade banner. 
- Most of the changes made to the `OnboardingFlowComposable` class involved reindenting the code (~200 lines).
Prerequisite: Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/11343238/upgrade-testing-patch-with-patron.patch) 
0. Turn off Patron feature flag
2. Go to `Profile` screen
3. Sign in with an account "without Plus"
4. Go to `Accounts` screen
5. ✅ Notice that the …

Patron: Update account screen's upgrade banner

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/features/profile/src/main/res/layout/fragment_account_details.xml
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

This adds "Upgrade to Patron" row in the Account Details screen.
1. Enable feature flag for Patron
2. Fresh install release build
3. Sign in with an in-app billing licence test account without having any plan
4. Go to `Profile` -> `Account`
5. Upgrade to `Plus` plan
6. Once subscribed to `Plus`, notice that "Upgrade to Patron" row is visible
7. Tap on the "Upgrade to Patron"
8. Notice that upgrade screen for only Patron plan features is shown 
- Any jetpack compose components I added or changed are covered by compose previews

Patron: Account Details - Add Upgrade to Patron

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt

This filters the podcast lists used for the discover views so that the list is resent only when changes occur. This avoids rebinding the views unnecessarily and appears to significantly improve the situation reported in https://github.com/Automattic/pocket-casts-android/issues/359  where we were sending off too many `discover_list_impression` events.
"Example 1" in that issue is _not_ entirely fixed by the change in this PR because we still send off an extra `discover_list_impression` event for the specific list episode item that is being played. We don't send off any events for any other of the list items though, so even that example is significantly improved.
In addition to the specific tests below, also do some smoke testing of the Discover feed. In particular, try subscribing to some …

Only rebind discover views when there are changes

---

CHANGELOG.md
dependencies.gradle

Fixes #906 where the keyboard would not appear when attempting to create or edit a folder. This made it almost impossible to create folders or edit the names of folders (for example, see [this comment)](https://github.com/Automattic/pocket-casts-android/issues/906#issuecomment-1535608479).
This issue was introduced when we updated compose to `1.4.1` in https://github.com/Automattic/pocket-casts-android/commit/ecf1f89c. The issue appears to be resolved in compose `1.4.2` (likely via [this commit](https://android.googlesource.com/platform/frameworks/support/+/1763fd0e7b7e11e0ac928762c2c6d16f0c049762) addressing [this issue](https://issuetracker.google.com/issues/262140644#comment16)).
> **Warning**
> I have this PR targeting `release/7.38` because I think the inability to use the soft …

Upgrade compose to 1.4.2 to fix keyboard display issue

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/SubscriptionBadge.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/SubscriptionTierPill.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/UserView.kt
modules/features/profile/src/main/res/layout-car/view_expanded_user.xml
modules/features/profile/src/main/res/layout-land-car/view_user.xml
modules/features/profile/src/main/res/layout-land/view_user.xml
modules/features/profile/src/main/res/layout/fragment_account_details.xml
modules/features/profile/src/main/res/layout/view_expanded_user.xml
modules/features/profile/src/main/res/layout/view_user.xml
modules/features/profile/src/main/res/values/dimens.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SignInState.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionType.kt

This updates "Account Details" screen profile header to include a subscription badge.
1. Enable feature flag for Patron
3. Login with an account without any plan 
4. Go to Profile -> Account screen 
5. Notice there's no subscription badge
1. Logout 
2. Login with an account with a Plus - Gift account
3. Go to Profile -> Account screen 
4. Notice there's a Plus subscription badge
1. Logout 
3. Login with a license test account with a Plus - Gift expiring account
4. Go to Profile -> Account screen 
5. Notice there's a Plus subscription badge
6. Buy Plus plan using upgrade banner
7. Notice there's a Plus subscription badge after the plan is bought
I tested it by setting `isSignedInAsPatron` to true in `SignInState`
```
val isSignedInAsPatron: Boolean
get() = true
``` …

Patron: Update account details header

---

CHANGELOG.md
base.gradle
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/StarRatingView.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt

Removes the flag to enable showing ratings for podcasts. 
Follow the steps here: https://github.com/Automattic/pocket-casts-android/pull/868

Enable the ratings feature

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml

Currently when free users contact support they get an auto-response directing them to use our forums. This avoids that back-and-forth by directing free users to use our forums when they reach out to support from within the app.
1. Log into the app
2. Go to the Profile tab
3. Tap on the ⚙️ 
4. Tap on "Help & feedback"
5. Scroll to the bottom of the screen and tap on "Get in touch"
6. Tap on "Get support"
7. ✅ If the account is free, the user should see a pop-up directing them to our support forums. Otherwise, the same share dialog that we used before is provided to allow the user to email us.
https://github.com/Automattic/pocket-casts-android/assets/4656348/6ec7857d-3a78-4a03-b2c2-627deda20ab0

Direct free users to support forums

---

CHANGELOG.md
modules/services/localization/src/main/res/values-ja/strings.xml

The accepted translations for the show played setting in Android Automotive had been changed to English. This has been fixed. We normally add the translations as part of the release process but I wanted to know which version this was in and include it in the change log.
1. Deploy the Automotive version
2. Go to Settings
3. Tap 'System'
4. Tap 'Languages & input'
5. Tap 'Languages'
6. Change it to 
7. Open Pocket Casts
8. Tap settings and scroll down
9. ✅ Verify there is no English
| --- | --- |
| ![Screenshot_20230512_075358](https://github.com/Automattic/pocket-casts-android/assets/308331/c6cd9c08-03b2-4259-8b01-739f3b57fcd5) | ![Screenshot_20230512_080900](https://github.com/Automattic/pocket-casts-android/assets/308331/57322591-11de-498b-8a91-815029818c90) |

Fixed Japanese show played setting

---

CHANGELOG.md
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt

The device user listening stats require a device id to keep track of the listening stats on different devices. As part of the Google single sign-on change, I removed this. 🤦‍♂️ This change puts it back. 
1. Open the Android Studio panel called 'App Inspection'
2. Tap the 'Network Inspector' tab
3. In the app go to the Profile tab and tap 'Refresh Now'
4. In the 'Network Inspector' find the 'https://api.pocketcasts.net/sync/update' call
5. ✅  Verify the request contains the device parameter with a value

Fix the listening stats

---

CHANGELOG.md
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Gravatar.kt

The default image size for a Gravatar image is 80px. This increases it to 400px. The sizes I could find it being used were 104dp, 100dp, 64dp, and 56dp so I thought 400px would be big enough.
https://en.gravatar.com/site/implement/images/
Fixes https://github.com/Automattic/pocket-casts-android/issues/968
1. Tap on the Profile tab
2. Sign in if you aren't already
3. ✅  Verify the quality of the Gravatar image
| --- | --- |
| ![Screenshot_20230517-211941](https://github.com/Automattic/pocket-casts-android/assets/308331/c591269b-98d9-408f-8628-f50e2b0670dd) | ![Screenshot_20230517-212229](https://github.com/Automattic/pocket-casts-android/assets/308331/84e492a1-5ded-40c2-b3ca-3d293a464f2c) |

Improve the resolution of the Gravatar image

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/log/LogBuffer.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/log/RxJavaUncaughtExceptionHandling.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

This updates the app so that in release builds, when there are uncaught errors in RxJava streams, we log the error but no longer crash the app. On debug builds, however, the current default behavior of crashing the app remains.
I was digging into [this crash](https://github.com/Automattic/pocket-casts-android/issues/958) on the watch app, and it appears to be a fairly tricky race condition. In particular, the problem seems to happen if while the server call is being made inside a `Single.fromCallable` [here](https://github.com/Automattic/pocket-casts-android/blob/5049b0109fa90c0074d5428a77ca990041cf39e8/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt#L521-L524) the downstream disposes of the `Single` source. When that happens …

Avoiding crashing on RxJava errors in production

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/LogsViewModel.kt

When I initially implemented the device logs screen in https://github.com/Automattic/pocket-casts-android/pull/911, I failed to append the `LogBuffer` logs to the output. This PR fixes that.
Before this fix, the logs would end with the "Episode Issues" and would contain none of the timestamped logs like "I 16/5 17:31:44 App started. 7.38 (9094)".
> **Note**
> I am targeting `release/7.39` with this because it seems like a pretty safe change and it would be good to get this out quickly since it fixes a new feature. I don't think we need to do a hotfix for this because emailing the logs (either from the logs display screen or if the user tries to contact support) will still include the full logs, so there is a workaround. I don't think we need to worry about immediately cutting a new beta …

Add LogBuffer output to device logs screen

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt

This change fixes the issue that the media session isn't using our custom skip buttons.
2. Swipe down the notification shade
3. ✅ Verify that our custom skip buttons are used in the notification player view, not the next / previous track buttons.
| --- | --- |
| ![Screenshot_20230518_104156](https://github.com/Automattic/pocket-casts-android/assets/308331/31fceaf3-6ba4-4956-9496-ab86e47e7b4d) | ![Screenshot_20230518_104429](https://github.com/Automattic/pocket-casts-android/assets/308331/75a639cc-a836-4a0a-94b0-a86f616ea07d) |

Fix custom skip buttons not appearing

---

CHANGELOG.md
automotive/src/main/AndroidManifest.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

With Automotive, we are getting reports of issues with the seeking not working, buffering issues and out-of-memory crashes. A fix for this was to add the `largeHeap` configuration to the Automotive manifest file (already in the app manifest) and reduce the player buffer sizes. This is only with certain manufacturers so I have limited the buffer size for those.
1. Deploy to Automotive
2. ✅ Verify you can play an episode, seek to a new position, and use the skip buttons.

Improving the Automotive buffering and seeking

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/PCVolumeScreen.kt

This PR updates the Wear app's "Now Playing" screen to include
- background based on the currently playing podcast
- volume/source options
- Play an episode from any podcast
- Navigate to the player screen in the pager
- ✅ Notice that the background has a tint based on the currently playing podcast
- Notice that there is a volume button at the bottom
- Tap on the volume button
- ✅ Notice that the volume screen opens with a volume stepper and there's an option to select the volume source
- Select a volume source 
- Control volume using the volume stepper
- ✅ Notice that the volume changes for the selected source
ℹ️ The PR uses the horologist-provided volume screen, the screen needs to be updated based on Figma design. 
https://github.com/Automattic/pocket-casts-android/assets/1405144/146ff2 …

Update player background and add volume button

---

CHANGELOG.md
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt

For the Automotive app, we have been asked if we can add the option to clear your data before you can log in or create an account. If you have an Up Next, any podcasts or episodes then it will ask you, otherwise the dialog won't be shown to you.
1. Deploy the Automotive version
2. Tap on the Discover tab
3. Tap a podcast
4. Tap on an episode to play it
5. Close the full screen player with the arrow at the top left
6. Tap the settings cog
7. Tap 'Set up account'
8. ✅ Verify a dialog is shown asking if you want to clear your data
9. Tap 'Clear data'
10. Tap close and back to get back to the app
11. ✅ Verify the mini player has closed
12. Tap the settings cog
13. Tap 'Set up account'
14. ✅ Verify it goes straight to the "Sign in or create account" page and doesn't show the dialog

On Automotive add the option to clear your data before logging in

---

CHANGELOG.md
base.gradle
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt

This adds the removed ratings feature flag, and removes it from the 7.39 change log.
1. Launch the app 
3. Tap on podcasts
4. ✅ Verify the ratings do not appear
5. Go to your subscribed podcasts
6. Tap on one
7. Expand the details
8. ✅ Verify the rating does not appear

Disables the ratings feature

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/EpisodeChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastViewModel.kt

This improves watch app podcast screen UI.
1. Install the watch app
2. Login with an account having podcasts
3. Tap on a podcast to open the podcast details page
4. Tap on a podcast episode and download it
5. Go back, tap on another episode, and download + add to play next
6. Go back and notice that
- Podcast screen UI matches Figma design
- Time text scrolls away on scrolling 
7. Go to "Up Next" screen or "Downloads" screen
8. Notice that episode chips are rendered properly (podcast screen reuses episode chips used on these screens)
https://github.com/Automattic/pocket-casts-android/assets/1405144/5347cc05-a395-4661-b24f-1c26f462a072

Improve watch app podcast screen UI

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt

This opens watch app's Now Playing screen when tapping on episode screen's Play icon
2. Login with an account having podcasts
3. Open `Podcasts` -> `Podcast` -> `Episode` screen
4. Tap play on the `Episode` screen
5. ✅ Notice that `Now playing` screen is shown
6.  Comment out lines 243, 245-247 inside `EpisodeViewModel`'s `fun onPlayClicked(showStreamingConfirmation: () -> Unit)` to show the streaming dialog confirmation
7. Reinstall the app and repeat steps 3-4
8. Notice that Streaming confirmation dialog is shown
9. Tap X
10. Notice that Streaming confirmation dialog is dismissed and you're not navigated to the `Now playing` screen
11. Re-tap play on the Episode screen
12. Notice that Streaming confirmation dialog is shown
13. Tap ✔️ 
14. ✅ Notice that `Now playing` …

Open watch app's Now Playing screen when tapping on episode screen's Play icon

---

dependencies.gradle
wear/build.gradle
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/di/WearNetworkModule.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NowPlayingPager.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingScreen.kt

This updates the horologist lib version from `0.4.2` to `0.4.7` ([release notes](https://github.com/google/horologist/releases))
Changes are made just so that the wear app compiles after the version bump. Improvements like using `StandardToggleChip` added in `0.4.7` to handle the largest font scale will be taken up separately. 
1. Notice that the marque text background is improved on the Now Playing screen after bringing in changes from [0.4.3](https://github.com/google/horologist/releases/tag/v0.4.3) in 2299cf7db23c412f961621e3fd90bc5f75810ce2
2. Play with the pager to see if it is not broken after bringing in new pager APIs from version [0.4.6](https://github.com/google/horologist/releases/tag/v0.4.6) in 7993d15a9f8ef42576120df92b15e0953da8246c
3. Smoke test the app to see if anything …

Bump horologist

---

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Color.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/theme/WearAppTheme.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/theme/WearColors.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FiltersScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/LoggingInScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/NowPlayingChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/UpNextScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ChipScreenHeaders.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/EpisodeChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ErrorScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NotificationScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/ObtainConfirmationScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/WatchListChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/downloads/DownloadsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/DownloadButton.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeDateTimeText.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/PlayButton.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/QueueButton.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/UpNextOptionsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsScreen.kt

This change improves the podcasts page in the following ways.
- Adds a podcast color gradient to the chip.
- Adds a page header. 
It also includes:
- Changing to the extra dark theme. This fixes the issue that you can see Pixel watch bezel if the background isn't black.
- Changing the theme typography to match the design.
1. Tap "Podcasts"
2. ✅  Scroll down the list and verify the tint colours look fine.

Improving the Wear OS podcasts page

---

wear/src/main/AndroidManifest.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/res/drawable/splash_background.xml
wear/src/main/res/values/styles.xml

This adds splash screen to watch app
2. Notice that splash screen is shown :)
https://github.com/Automattic/pocket-casts-android/assets/1405144/e677838d-dd33-4885-8b30-f27c861d6de6

Add splash screen to watch app

---

dependencies.gradle
fastlane/Fastfile

Adding the the wear app to our build pipeline.
For reference, this is [the PR](https://github.com/Automattic/pocket-casts-android/pull/314) adding the automotive build.
I don't know how to test this. Maybe @oguzkocer has some suggestions. Or we just merge it and see what happens when we try to run the release script on Monday, May 29.

Add wear app to build pipeline

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/theme/WearColors.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsViewModel.kt

This adds folders to the podcasts page. It only allows you to view the folders you have created on your mobile or web app in this version, you can't create new ones.
Fixes https://github.com/Automattic/pocket-casts-android/issues/1011
1. On the mobile or web app add some folders to your account and sync.
2. In the wear app check you are signed in with the same user.
3. Tap 'Podcasts'
4. ✅ Verify you can see your folders
5. Tap a folder
6. ✅ Verify you are only viewing the podcasts in that folder
7. Tap a podcast
8. ✅ Verify you are taken to the podcast page
9. Swipe from the left of the screen twice
10. ✅ Verify you are back on the home page
https://github.com/Automattic/pocket-casts-android/assets/308331/306c3835-7017-4db2-832a-3b43191d2f00

Add Wear OS folders

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/di/ConfigModule.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/di/WearAppModule.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/AudioOutputSelectorHelper.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingViewModel.kt

Closes https://github.com/Automattic/pocket-casts-android/issues/1013
This prevents playback on watch speakers. 
1. Make sure that Bluetooth speaker is not connected to watch
2. Launch the app and login with a Plus account having podcasts
3. Select Podcasts -> select a Podcast -> select an Episode
4. Tap play on the selected episode
5. ✅ Notice that a screen is shown to select a Bluetooth device
6. Connect to a Bluetooth speaker
7. ✅ Notice that the episode starts playing 
8. Navigate to the Now Playing screen
9. Tap on the volume button
10. On the volume screen, deselect the Bluetooth speaker
11. ✅ Notice that the player pauses
12. Go back to the Now Playing screen
13. Tap on the play icon
14. ✅ Notice that a screen is shown to select a Bluetooth device …

Prevent playback on watch speakers 

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt

> **Warning**
> Targets release/7.39.1
This replaces `episodes` table name with `podcast_episodes` in continuation of changes made in PR https://github.com/Automattic/pocket-casts-android/pull/910.
Internal Ref: p1685425150749449/1685113399.023749-slack-C028JAG44VD
I also removed 3 unused methods that referenced `episodes` table name:
`countEpisodesNotCompleted`
`countEpisodesDownloading`
`countEpisodesNotDownloaded`

Fix episodes table name in hard-coded query

---

scripts/themes/README.md
scripts/themes/download_themes.rb

This allows us to import our theme colours from a Google Sheets document again.
1. Copy the google_credentials.json to the folder scripts/themes
2. Open Terminal 
3. cd scripts/themes
4. ./run.sh
5. ✅ Verify the script completes successfully

Fixing the themes import script

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/EpisodeChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastViewModel.kt

This displays episode (playback/download) errors on the episode details screen.
Task #1026
1. Disable the internet on your watch device
2. Launch that app and go to the episode screen
3. Tap on the play icon (you're navigated to the Now Playing screen)
4. Wait for a while
5. ✅ Notice that the play icon switches to pause icon
6. Slide to the previous page in the pager to get back to the Episode screen
7. ✅ Notice that you see playback error message
8. Tap on download icon
9. ✅ Notice that the error is cleared
10. Wait for a while
11. ✅ Notice that you see a download error message and the download icon changes to retry icon
Playback | Download 
--- | ---

Display errors on episode screen in watch app

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SentryHelper.kt
wear/build.gradle
wear/src/main/AndroidManifest.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

This sends additional data for an exception "separately" to Sentry using [local scope](https://docs.sentry.io/platforms/python/guides/logging/enriching-events/scopes/#local-scopes). This helps in grouping the exception in Sentry. 
I've used `scope.tags` instead of `scope.extra` as [tags help in searching and grouping](https://docs.sentry.io/platforms/python/guides/logging/enriching-events/tags/?original_referrer=https%3A%2F%2Fduckduckgo.com%2F).
> Tags are key/value string pairs that are both indexed and searchable.
Events with different episode uuids are grouped together:
We can filter using tags

Send Sentry additional data as tags

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/WearMainActivityViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/SettingsViewModel.kt

This refreshes podcasts on app open in the watch app.
Task https://github.com/Automattic/pocket-casts-android/issues/1008
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/11634464/Reduce_refresh_time.patch) to reduce threshold time to refresh on app open to 5 secs
2. Install the app on watch with wifi debugging enabled
3. Login with a plus account having podcasts
4. Search `BgTask: RefreshPodcastsTask` in logs 
5. ✅ Notice that you see `BgTask: RefreshPodcastsTask - runNow - Start` in logs
6. Go to the recent apps
7. Tap and open Pocket Casts app before 5 secs
8.  ✅ Notice that you do not see `BgTask: RefreshPodcastsTask - runNow - Start`  in logs 
9. Go to the recent apps again
10. Tap and open Pocket Casts app after 5 secs
11.  ✅ Notice that you do not see …

Refresh podcasts on app open in watch app

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreenViewModel.kt

This PR adds tracks to the main list screen on the watch (issue https://github.com/Automattic/pocket-casts-android/issues/1007).
1. Install the watch app and log in so that you are brought to the main list screen
2. ✅ Observe that the `wear_main_list_shown` event is sent
3. Tap on each of the buttons on the main list screen
4. ✅ Observe that for each button the appropriate `wear_main_list_[button]_tapped` event is sent.

Adding tracks for the watch's main list screen

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsSource.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncAccountManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/AppPlatform.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Util.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreenViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithGoogleScreenViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingViewModel.kt

This turns on Tracks in the watch app (issue https://github.com/Automattic/pocket-casts-android/issues/1007).
In addition, I am adding a global `platform` property to identify if a given event is coming from a watch, phone, or automotive app. I thought this was better than adding duplicate events/sources for everything that happens on the phone as well as the watch. Let me know if you think this isn't the right way to go though.
Lastly, this PR includes a fix for the user signed in events. Before this PR, the `user_signed_in_watch_from_phone` event was sent for all sign-ins on the watch. This updates that so that event is only sent when the user is automatically signed into the watch from the phone. All user-initiated sign-ins on the watch now send the `user_signed_in` event.
This PR does …

Tracks for watch

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt
modules/services/localization/src/main/res/values/strings.xml
wear/build.gradle
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/WatchListChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/PrivacySettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/PrivacySettingsViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsViewModel.kt

This adds user privacy options for the watch (issue https://github.com/Automattic/pocket-casts-android/issues/1007). For now I'm just going with the same settings we have on the phone.
The privacy settings are available under `Settings` → `Privacy`. 
- Verify that the default settings have "Analytics" and "Crash Reports" toggled on, with "Link your account" toggled off
- Verify that Tracks are only sent off if "Analytics" is toggled on
- Verify that crash reports are only sent off if "Crash reports" is toggled on
- Verify that the crash reports only includes the users email address if "Link your account" is toggled on
https://github.com/Automattic/pocket-casts-android/assets/4656348/d965a1e6-d09d-4974-b7ee-1018200114cd
| Account unlinked | Account linked |
| --- | --- |
| …

Add privacy settings for watch

---

automotive/build.gradle
automotive/src/main/AndroidManifest.xml
wear/build.gradle
wear/src/debug/res/values/titles.xml
wear/src/debugProd/res/values/titles.xml
wear/src/main/AndroidManifest.xml

This uses the radioactive icon by default for debug builds of the automotive and wear apps like we do for the phone app currently. In addition, this uses the "Pocket Debug" app name for the debug builds like the phone app does. It's so much easier to differentiate the apps on your device during development with these changes.
1. Verify that debug builds of the wear and automotive apps have the green radioactive icon by default.
2. Verify that release builds of the wear and automotive apps still have the regular icon by default

Use radioactive icons for debug builds on wear and automotive apps

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/UpNextScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NowPlayingPager.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/filter/FilterScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/filters/FiltersScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsScreen.kt

This PR is adding [support for the rotary input to scroll the screen](https://github.com/Automattic/pocket-casts-android/issues/1045) on the main watch list screen.
I think we just need to import/use the horologist scrollable component instead of the foundation compose one to get this. I'm only making this change on a single screen in this PR so it can be reviewed before we make the same change to all th other screens. I figured we can do that in a follow-up PR, or by updating this PR, but I wanted to get some eyes on this first before investing the additional time.
1. Go to the main watch list screen
2. Verify that you can scroll the list using the rotary spinner

Support scrolling with rotary input on watch list

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/RequirePlusScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/RequirePlusViewModel.kt

This adds tracks for the require plus screen and the login screen on the watch (relevant issue: https://github.com/Automattic/pocket-casts-android/issues/1007).
1. Install the watch app (make sure you're not logged into PC on a connected phone)
2. ✅  Observe that when the require plus screen is shown the `wear_require_plus_shown` event is tracked
3. Proceed to the login screen
4. ✅ Observe that the `wear_signin_shown` event is tracked
5. Tap on each of the signin options and observe that the following events are tracked when appropriate:
- `wear_signin_google_tapped`
- `wear_signin_phone_tapped`
- `wear_signin_email_tapped`

Add tracks for sign in screens on watch

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/SignInViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithEmailScreen.kt

The validations for email and password were present but the message was not displaying due to some bug in the logic. This PR fixes that logic and allows the Wear app to show error screens for invalid email/password.
Fixes #983 
2. Click on Login with email.
3. Observe that whenever you enter invalid email or password less than 6 characters, you get the error message accordingly.
|                                                               Credentials                                                              |                                                                 Screens                                                                |
|:--------------------------------------------------------------------------------------------------------------------------- …

Added validations for email/password wear app

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingCreateAccountPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/components/ContinueWithGoogleButton.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingCreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLogInViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithEmailScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithGoogleScreen.kt

When there is no network connection available, the app used to display a generic message.
In the case of email, the message is "Unable to login to your sync account, sorry. Please try again later". In the case of google sign in, the message is "Unable to launch Google sign in."
This PR just modifies that message to a more specific message "No network connection detected. Please try again later.".
Fixes #1027 
2. Turn on Airplane Mode
3. Attempt to Sign in using either google or email.
4. Observe that a specific message telling that no network connection detected is displayed.

Improve error message during login when no network is present

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImage.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt

Instead of downloading 960 pixel images like we do on the phone, let's just download 480 pixel images on the watch. This will reduce the watch's data usage and improve [the initial login and sync time](https://github.com/Automattic/pocket-casts-android/issues/1047). Thanks for the suggestion @geekygecko . 🙇 
1. Log into a fresh install of the app
2. Use the network inspector to verify that 480 pixel images are being instead of 960 pixel images
3. Check the UI in the app to make sure the images still look good. I believe the larges image we display in the watch app is the podcast artwork we display at the top of the screen for a particular podcast.

Download smaller images on the watch

---

README.md
docs/translations.md

Adding some documentation about how the app gets translated, so it is clear how to contribute translations.

Add translations documentation

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt

This fixes the watch app so that the system's media controls reflect our app's playback state. The fix for this is to not add custom media actions in the watch app. The reason we need to do this is because of a bug in Wear OS 3.5. This has been fixed by Google and will be released at some point in the future.
Fixes https://github.com/Automattic/pocket-casts-android/issues/1050
Thanks to @kul3r4, @yschimke, and the wear os team for their figuring this out. 🙇 
1. Fesh install of the watch app on a physical device
2. Begin playing an episode
3. Go to the watch's home screen and wait a few seconds for the media notification to appear (it takes at least 5 seconds or so in my testing)
4. Tap on the media notification
5. Verify that you're taken back to our app
6. Open the OS's "Media Controls" …

Fix wear media notifications

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/LoggingInScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithEmailScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/LoadingSpinner.kt

This updates the logging in spinner to use the standard material spinner instead of the rotating arrow from the refresh button.
internal discussion: p1686302267124569/1686229326.882529-slack-C040S9BK7SP
2. If you're using an emulator, make sure and slow down the network connection so you have time to enjoy the amazing new spinner
3. Log in using either google or email
4. When there is not an avatar image to display, observe that the placeholder spinner is the standard material spinner
https://github.com/Automattic/pocket-casts-android/assets/4656348/5ac6243d-78e3-41d9-9210-167e3f642064

Update wear logging in spinner

---

CHANGELOG.md
base.gradle
build.gradle
wear/build.gradle
wear/proguard-rules.pro

This adds `Sentry` proguard settings
Ensure that exceptions from the release build are readable in Sentry.

Add Sentry proguard setting for watch app

---

wear/src/main/AndroidManifest.xml

We haven't removed the AD_ID permission from the wear app like we have the other apps. This is removing that so Google doesn't require an advertising id declaration from us.
1. Build a release apk
2. Inspect the merged AndroidManifiest.xml file in the resulting apk and verify that it does not include `    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />`.

Remove AD_ID permission from wear app

---

dependencies.gradle
modules/services/localization/src/main/res/values/strings.xml
wear/build.gradle
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/UrlScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/WearAboutScreen.kt

This is an initial implementation of an about screen for the watch app.
This PR makes progress on, but does not complete, #1070.
1. On the watch, go to Settings
8. Observe there is an about chip at the bottom of the screen
9. Tap on that chip and observe an about screen is loaded
10. Observe that the correct version number is displayed.
11. Tap on either "Terms of service" or "Privacy policy"
12. Observe that a screen is opened which directs the user to the relevant URL and has a button to open that URL on the phone
13. Tap on the button to open the URL on the phone and observe that (a) if a phone is connected to the watch the URL is opened on the phone or (b) if a phone is not connected to the watch a toast message appears after 5 seconds or so advising that it could not open the URL on …

Add about screen for watch

---

CHANGELOG.md
app/build.gradle
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/AppIcon.kt

With the end of June coming up, this updates the app to again use the regular Pocket Casts icon by default (follow-up to https://github.com/Automattic/pocket-casts-android/pull/997). The Pride icon may still be selected by a user under `Profile` → ⚙️  → `Appearance`.
> **Note**
> This change is targeting the `release/7.41` release branch. We should update the release notes to include this.
1. Install a release build of the app without the changes in this PR
2. Observe the app icon is the pride icon
3. Install a release build of the app with the changes in this PR
4. Observe the app icon is the default icon
5. Under `Profile` → ⚙️  → `Appearance`, select the Pride icon
6. Observe that the app launcher contains both the default icon and the Pride icon
1. Install a release build of the app …

Use regular icon for launcher by default

---

build.gradle
wear/build.gradle
wear/src/main/AndroidManifest.xml

I got an error deploying a debug build to Wear OS and upgrading the Gradle tools fixed it for me. I tried to upgrade to 8.0.2 but it was erroring so I thought I would leave that for a future PR.
```
E  java.lang.NoSuchFieldError: No instance field delegate of type Landroid/database/sqlite/SQLiteStatement; in class Landroidx/sqlite/db/framework/FrameworkSQLiteStatement; or its superclasses (declaration of 'androidx.sqlite.db.framework.FrameworkSQLiteStatement' appears in /data/app/~~fFjdLX1TbF6d9sqPi609OQ==/au.com.shiftyjelly.pocketcasts.debug-9JfEpQW9bnvJ98MqSMTmmg==/base.apk!classes17.dex)
E  	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(Unknown Source:0)
E  	at androidx.work.impl.model.WorkSpecDao_Impl.markWorkSpecScheduled(WorkSpecDao_Impl.java:343)
E …
```

Upgrade Gradle tools to 7.4.2

---

modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcasts/PodcastsViewModel.kt

This PR adds a message screen for wear app when the user isn't subscribed to any podcasts, showing message to subscribe to podcasts on their phone.
Fixes #1076
1. Login to the wear app.
2. Click on podcasts.
3. ✅ Verify the subscribe screen is shown when the user doesn't have any subscribed podcasts, telling them to subscribe to podcast on phone
4. ✅ Verify that the previous flow when the user does have subscribed podcast(s) works.

Added empty podcasts screen in watch app

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/NotesViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateShowNotesTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/shownotes/ShowNotesState.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This change switches getting the show notes from the JSON cache.
1. Open a podcast page
2. Tap on an episode row
3. ✅ Verify the show notes are displayed
4. Close the episode fragment
5. Turn on airplane mode
6. Tap another episode row
7. ✅ Verify the show notes are displayed 
8. Turn off airplane mode
9. Go to a different podcast
10. Tap play on an episode row without opening the episode fragment
11. Tap on the mini player
12. Tap on the Notes tab
13. ✅ Verify the show notes are displayed
2. Tap the settings cog
3. Tap General
4. Tap Row action
5. Change it to Download
6. Go to discover and find a podcast that you haven't opened
7. Tap download on the episode row and wait for the download to finish
8. Turn on airplane mode
9. Tap on an episode row
10. ✅ Verify the …

Retrieve show notes from JSON cache

---

app/src/main/AndroidManifest.xml
app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsWearListenerService.kt
app/src/main/res/values/wear.xml
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/LogsViewModel.kt
modules/features/shared/build.gradle
modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/WatchPhoneCommunication.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
wear/src/main/AndroidManifest.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/HelpScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/HelpScreenViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsRoutes.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsScreen.kt

This adds a "Help & feedback" section to the settings and gives users a way to either (1) send an email to support with their watch logs attached or (2) send their watch logs to the phone.
Fixes #1069
> **Warning**
> I am targeting `release/7.41`. I think it is important that we get this in with the initial Wear OS release since it will be critical to helping us debug issues. Let me know if you disagree though.
Since it is not possible to send an email from the watch or send an email-triggering intent directly from the watch to the phone, I'm taking the approach of sending a message from the watch to the phone with the watch's logs. The phone app then takes that message and constructs an appropriate intent with it. This does mean that this functionality will only work if the user has the …

Enable sharing logs from watch

---

dependencies.gradle
wear/build.gradle
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/WatchListChip.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/horologist/SetVolumeButtonStyled.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsScreen.kt

Update Horologist version to `0.4.9` and update usages of components from `base-ui` to `compose-material` library.
Check visual of chip components across all the screens of the app if they didn't get affected.
- [N/A] If this is a user-facing change, I have added an entry in CHANGELOG.md
- [N/A] All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml`
- [N/A] Any jetpack compose components I added or changed are covered by compose previews
⚠️ not fully tested!

Update horologist to 0.4.9

---

modules/services/localization/src/main/res/values/strings.xml

This change fixes the following build error. There is one line for each locale. I have updated the GlotPress entries for all the countries.
```
pocket-casts-android/modules/services/localization/build/intermediates/packaged_res/release/values/
values.xml:1146:4: Multiple substitutions specified in non-positional format of string 
resource string/search_history_row_type_episode_subtitle. Did you mean to add the 
formatted="false" attribute?
```
Sorry this is a small change, I tried to upgrade to Android Gradle Plugin 8.0.2 and failed but I thought I should fix something. 🤦 
1. Tap on Discover
2. Tap on Search
3. Enter a search term
4. Tap on an episode result
5. Tap back until you can search again
6. ✅ Verify the recent search episode is in the following format.

Added a positional value to a string

---

automotive/src/main/AndroidManifest.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

When playing audio in Automotive the following error is in the logs:
```
isServiceRunningInForeground found no matching service
```
The issue is that the playback service with Automotive is AutoPlaybackService and not PlaybackService. The AutoPlaybackService extends the PlaybackService so changing the condition to `this` stops the error message.
The Automotive player is having trouble indicating the correct playback state. For example if you tap on the seek bar sometimes it won't show it is buffering and the playback time with continue to change without any audio playback. I believe there is a few issues happening but the main one is that we have a `seeking` flag to stop events when we think the user is seeking, the issue is that this blocks the event that says playback in buffering. …

Fixing Automotive playback state

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/SignInFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RegionSelectFragment.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ShareResultReceiver.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt

In my last pull request, I found Android KTX could reduce some of our code to handle older versions of Android, this makes the change in other areas of the code. It felt like a nice clean up change.
It also added a changelog entry I missed for the Automotive change.
1. Logout of the Pocket Casts account and clear the data
2. Open the app
3. ✅ Verify you are shown the the onboarding pages
4. Tap the Profile tab
5. Tap settings
6. Tap Auto download
7. Turn on "New episodes"
8. Tap Choose podcasts
9. ✅ Verify the page opens and the app doesn't crash
10. Start playing an episode
11. Simulate the headphone key next being pressed
```
adb shell input keyevent 87
```
12. ✅ Verify the episode skips forward
13. Go to the discover tab
14. Scroll to the bottom
15. Tap the region
16. ✅ Verify the …

Replacing the backwards compatible code with Android KTX methods.

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/log/RxJavaUncaughtExceptionHandling.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

This is a follow-up to #971 . In that PR I began catching raxjava's `UndeliverableException`s because I noticed that they were getting thrown pretty frequently on logout due to a race condition. I wasn't seeing these on the phone app though so I was concerned that I had something set up wrong on the watch app, so I only caught the exceptions on release builds, allowing them to still crash the app on debug builds.
I later noticed that now the phone app was crashing with these exceptions. Turns out I overlooked that the phone app had the same issue and was already catching the `UndeliverableException`s.
This PR consolidates that handling and, since I now understand that this is a longstanding issue and not unique to the wear app, I'm using the phone app's approach of always catching the …

Consolidate rxjava undeliverable exception handling

---

modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/AppIcon.kt

This fixes the fallback default icon id although it's unlikely that `AppIconType.DEFAULT.id` will be null.

Fix fallback default icon id

---

modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/WearMainActivityViewModel.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/LoginWithPhoneScreen.kt

This PR addresses some feedback about the watch login flow by:
1. Updating the toast text for users who log in with a free account to say "xxx@example.com is using a free account" instead of "Please sign with a plus account". The Plus account language was not needed because this toast is displayed over a screen that specifically states a Plus account is required and the updated messaging makes it clearer that there was not a login error.
2. On the login from phone screen, there is added text indicating that users should ensure they have the same version of the app on their watch and phone. I thought about also adding text suggesting that if there are problems to try logging out and back in on their phone, but decided to hold off on that for now. We can always add more later if it turns …

UI updates to wear login flow

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountActivity.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
modules/features/account/src/main/res/layout-car/fragment_account.xml
modules/features/account/src/main/res/layout/fragment_account.xml
modules/services/localization/src/main/res/values-ar/strings.xml
modules/services/localization/src/main/res/values-de/strings.xml
modules/services/localization/src/main/res/values-en-rGB/strings.xml
modules/services/localization/src/main/res/values-es-rMX/strings.xml
modules/services/localization/src/main/res/values-es/strings.xml
modules/services/localization/src/main/res/values-fr-rCA/strings.xml
modules/services/localization/src/main/res/values-fr/strings.xml
modules/services/localization/src/main/res/values-it/strings.xml
modules/services/localization/src/main/res/values-ja/strings.xml
modules/services/localization/src/main/res/values-ko/strings.xml
modules/services/localization/src/main/res/values-nb/strings.xml
modules/services/localization/src/main/res/values-nl/strings.xml
modules/services/localization/src/main/res/values-pt-rBR/strings.xml
modules/services/localization/src/main/res/values-ru/strings.xml
modules/services/localization/src/main/res/values-sv/strings.xml
modules/services/localization/src/main/res/values-zh-rTW/strings.xml
modules/services/localization/src/main/res/values-zh/strings.xml
modules/services/localization/src/main/res/values/strings.xml

For an version of Android less than 11 it is locking up for an Automotive build after a create account. 
1. Deploy the Automotive app
2. Tap the settings cog
3. Tap Set up account
4. On the popup dialog tap sign in
5. ✅ Verify you are taken to the Sign in or create account page
6. Tap Create account
7. Enter an email and password. 
8. Tap Create account
9. ✅ Verify you can successfully create an account
1. In AccountActivity.kt change it to the following line
```
val navigateToSignIn = true
```
2. Deploy the Automotive app
3. Tap the settings cog
4. Tap Set up account
5. On the popup dialog tap sign in
6. ✅ Verify you are taken to the sign in form with an input box for the email and password
7. Enter existing account details and login
8. ✅ Verify you are logged in successfully …

Remove create account for an Automotive build

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/NowPlayingViewModel.kt

I got my account to a state where I had a podcast reporting a duration of 0. Because we were dividing by the duration, that was giving use a `Nan` result, which was causing this crash within horologist on the 7.41 release branch:
```
java.lang.IllegalArgumentException: current must not be NaN
at androidx.compose.ui.semantics.ProgressBarRangeInfo.<init>(SemanticsProperties.kt:499)
at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:52)
at androidx.compose.foundation.ProgressSemanticsKt$progressSemantics$1.invoke(ProgressSemantics.kt:50)
at androidx.compose.ui.semantics.AppendedSemanticsModifierNodeElement.<init>(SemanticsModifier.kt:125)
at androidx.compose.ui.semantics.SemanticsModifierKt.semantics(SemanticsModifier.kt:109)
at …
```

Prevent percent value of Nan

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeButton.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/HorizontalPagerWrapper.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SubscriptionStatus.kt

This updates account details upgrade view as described in testing steps
Prerequisite
- Debug build variant (tier is only available in debug env)
- Changes for debug build variant (see bottom section in pdeCcb-12K-p2)
- Three accounts 
- `Free`
- `Plus` (Expiring - expiry < 30 days)
- `Patron` (Expiring - expiry < 30 days) (`ashita.agrawal+patron@automattic.com` is set for this)
- Enable `Patron` feature flag and restart the app
1. Login with a `Free` account
2. Go to `Profile` -> `Account` screen
3. Notice that upgrade view is shown and upgrade button title is set to 
-  `Subscribe to <plan name>` (if plan has no free trial)
-  `Start my free trial` (if plan has free trial & user is eligible for free trial)
Start free trial | Subscribe
----|----
1. Login with a `Plus` expiring account
2. …

Update account details upgrade button title

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateShowNotesTask.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt

There is an exception happening in Sentry.
```
NullPointerException
au.com.shiftyjelly.pocketcasts.repositories.download.task.UpdateShowNotesTask in <init> at line 33
```
I haven't been unable to figure out the issue. Initially, I thought it might be happening with a user file as they don't have a podcast UUID but there is an if statement to check this before creating the job.
This change adds some more debugging and reduces the chance of a null pointer happening.
1. Open a podcast page you haven't downloaded show notes for
2. Swipe the notification shade down
3. Tap the Internet control and turn off WiFi and mobile data
4. Close the notification shade
5. Tap an episode row, the show notes shouldn't load if the internet is disabled
6. Enable the internet again
7. Tap download on the …

Add more debugging to catch show notes task null pointer

---

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/DefaultReleaseFeatureProvider.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

This adds a setting for auto playing up next to the phone app. No functionality beyond just adding a setting for this is added in this PR—that will be handled in follow-up PRs.
- On debug builds, verify that when the "Auto Play When Up Next Empty Setting" beta toggle is off, the "Continuous playback" setting is not present at the bottom of the "General" settings, and that the setting is present when the toggle is on.
- Verify that both settings persist after the app has been killed and restarted
- Verify that flipping the continuous playback toggle fires off the `settings_general_continuous_playback_toggled` event with the appropriate "enabled" boolean property.
- On a release build, verify that the "Continuous playback" setting is not present at the bottom of the "General" settings
- On …

Add auto play up next setting

---

modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/utils/MainCoroutineRule.kt
modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModelTest.kt
modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/utils/MainCoroutineRule.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModelTest.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/ManualCleanupViewModelTest.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModelTest.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/utils/MainCoroutineRule.kt

This PR cleans up main coroutine rule on the AdvancedSettingsViewmodel, StoriesViewmodel, ManualCleanupViewmodel, StorageSettingsViewModel, AdvancedSettingsViewModel and SearchViewModelViewModel Tests. 
Fixes # N/A

Coroutine Rule Cleanup on Viewmodels

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

This applies recommended proration rate on upgrading to a more expensive plan through Play Store.
- In-app billing sandbox setup
- Release build variant
- Feature flag enabled for the release build variant
`Plus` monthly plan
1. Fresh install the release build
2. Login with a `Free` account and purchase a `Plus` monthly plan
3. Tap `Upgrade to Patron` from `Profile` -> `Account` details screen
4. Choose a `Patron` plan (monthly or yearly)
5. Complete payment flow
6. Notice that recommended proration rate is applied 
`Plus` yearly plan
1. Repeat above steps for the `Plus` yearly plan
2. Notice that recommended proration rate is applied

Upgrade subscription from Plus to Patron

---

app/src/main/AndroidManifest.xml
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt

This adds intent for opml import from share sheet
1. Save an opml to your device 
2. Open files app
3. Select opml file and tap share menu
4. Notice that Pocket Casts app is shown in the share sheet
5. Select the app
6. Notice that podcasts are imported from the opml into the app
https://github.com/Automattic/pocket-casts-android/assets/1405144/189ce08c-8fb6-4e8a-b46e-df92b2f8c3f4

Add intent for opml import from share sheet

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingFlow.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt

This
- Adds global property for the subscription tier and reuses `plus_upsell` analytic value in the "Plus Upsell" flow (Internal ref: p1684957446866019/1684952142.413199-slack-C02ATC80MUM)
- Returns full product id for patron subscriptions in `purchase_`* events
- In-app billing sandbox setup
- Debug build variant
- Patron feature flag enabled
1. Login with a `Free`
2. Purchase a `Patron` plan
3. Notice that `subscription_tier` is shown as a global property in logs
4. Notice that the purchase fails and the `purchase_failed` event is shown in logs with the full product id for the `Patron` plan

Patron: Update tracks

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
modules/services/preferences/build.gradle
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/CloudFilesManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/AutomaticUpNextSource.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt

This adds an initial version of autoplay for users who have no episodes in their up next queue. This feature is still a bit in flux as we figure out exactly what we want this to look like.
I made a few different attempts at doing this by passing the information up from the relevant views, but that just didn't seem to work well at all. One particular difficulty with that approach is that the Episode Details screen can be accessed from so many places and it would need to know how it was created to pass that information up. We could certainly do it, but it seemed overly complicated and required a lot of changes.
The solution I'm going with here uses a global variable—so it feels a bit hacky—but it seems to work well and require much less change. For each screen that should change what is …

Add autoplay functionality

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt

This matches behavior on iOS to show plus upsell screen from plus settings menu
Prerequisites:
- In-app billing sandbox setup
- Debug build variant
- `Patron` feature flag enabled
1. Launch the app (without login)
2. Go to `Profile` -> `Settings` (⚙️)
3. Tap `Pocket Casts Plus` menu
4. Notice that `Plus Upsell` screen is shown
5. Notice in logs that source is `settings` for `plus_promotion_shown` track event
** For the disabled `Patron` feature flag, old plus screen should be shown
https://github.com/Automattic/pocket-casts-android/assets/1405144/45c776ca-134f-41d0-b530-3a9610499b3a

Show plus upsell from plus settings menu

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml

This updates the name of the autoplay setting from "Continuous playback" to "Autoplay"
1. With the feature flag enabled, go to the settings and verify that the setting has been renamed to "Autoplay"
2. Toggle the setting
3. Verify that we are tracking the event: `settings_general_autoplay_toggled` with the appropriate boolean for the "enabled" property

Update autoplay setting name

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

Tracking when an episode is autoplayed.
When referring to the autoplay event in the test steps below, I am referring to the event "playback_episode_autoplayed" with  an "episode_uuid" property reflecting the uuid of the episode being autoplayed.
1. With the autplay feature enabled and an empty up next queue
2. Begin playing an episode
3. Observe that the autoplay event is NOT sent
4. Complete the episode
5. Observe that the autoplay event IS sent
7. Add an episode to your up next queue
8. Complete playing the current episode and the episode in the up next queue
9. Observe that no new autoplay events are sent (should only have 1 autoplay event from following all these test steps)

Track when an episode is autoplayed

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt

This PR adds +-1 increments if the custom timer is <5. 
Fixes # N/A
1. Tap on the Discover tab
2. Tap on any random podcast and hit play
3. Click on  Sleep timer.
4. Click on - +.
5. If the Custom timer is below 5, it reduces /increases by 1 min
https://github.com/Automattic/pocket-casts-android/assets/95022986/6ea0ba14-2f93-4157-873c-9f38ea1c536d

+ - 1 min Custom Increments on the Sleep timer

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/BookmarkDaoTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/77.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Bookmark.kt

This change creates the new bookmarks table and adds a basic DAO.
I don't know if we usually hold back the migration until later in case it changes early on in the project. 
iOS has the following structure.
```
CREATE TABLE IF NOT EXISTS \(Self.tableName) (
\(Column.uuid) varchar(40) NOT NULL,
\(Column.episode) varchar(40) NOT NULL,
\(Column.podcast) varchar(40),
\(Column.time) real NOT NULL,
\(Column.createdDate) INTEGER NOT NULL,
\(Column.deleted) int NOT NULL DEFAULT 0,
PRIMARY KEY (\(Column.uuid))
);
```
but the Android version is slightly different.
```
CREATE TABLE IF NOT EXISTS `bookmarks` (
`uuid` TEXT NOT NULL,
`podcast_uuid` TEXT NOT NULL,
`episode_uuid` TEXT NOT NULL,
`time` INTEGER NOT NULL, 
`created_at` INTEGER NOT NULL,
`deleted` INTEGER NOT NULL,
`sync_status` INTEGER NOT …
```

Bookmarks: Adds database table and DAO

---

modules/features/player/build.gradle
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt

This adds a placeholder `Bookmarks` tab to the player.
1. Open the debug build with the bookmarks `Feature Flag`enabled
2. Play any episode having chapters (https://pca.st/upgrade)
3. Open the full player
4. ✅ Verify the `Bookmarks` tab appears at the correct position
5. ✅ Verify tapping on it opens a placeholder view
6. ✅ Verify swiping between tabs works and opens the current view. 
7. Close the player
8. Disable the `Bookmarks` flag and restart the app
9. Open the full player
10. ✅ Verify you don't see the `Bookmarks` tab
Without Feature Flag | With Feature Flag
-----|-----

Bookmarks: Add new tab on player

---

base.gradle
dependencies.gradle
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/util/MainCoroutineRule.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
modules/services/images/src/main/res/drawable/ic_play.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/DateUtil.kt

This adds bookmarks list on full screen player > `Bookmarks` tab
1. Apply the [patch](https://github.com/Automattic/pocket-casts-android/files/11949580/bookmarks.patch)
2. Install debug build
3. Go to `Discover`
4. Tap a podcast and play an episode
5. Open full player
6. Scroll to the `Bookmarks` tab
7. Notice that the UI matches the `Figma` design (Io7PCz1H1hmOgEE9eljoYW-fi-2033_32210)

Bookmarks: Display bookmarks list

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt

This is a quick fix for a crash that can occur when adjusting the shelf items on the full screen player. I've seen this a fair number of times myself and it looks like around 150 other people have encountered it [according to Sentry](https://a8c.sentry.io/issues/4263540831/events/8d7d69e4d842456687fb26500829a45a/).
I can't recreate this with 100% reliability, but it seems to occur about half the time when I try to move the shelf items on the Now Playing screen immediately after doing a fresh install of the app.
1. Freshly install the app and start playing an episode
2. From the full screen player, tap the overflow menu, then tap the edit pencil to reorganize the icons
3. Move two or three icons in a row from the bottom of the list to the top of the list
4. Observe that the app has not …

Catch out of bounds exception when moving shelf items

---

modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/DefaultReleaseFeatureProvider.kt

Enables the flag to enable showing ratings for podcasts. 
Follow the steps here: https://github.com/Automattic/pocket-casts-android/pull/868

Enable the ratings feature flag

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PodcastGrouping.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This has autoplay take the episode grouping setting for a podcast into account when it selects what episode to play next. This is a follow-up to [this comment](https://github.com/Automattic/pocket-casts-android/pull/1132#issuecomment-1614279942).
1. With the autoplay beta flag turned on (it is on by default), and the autoplay setting turned on (it is on by default for new installs), and with an empty up next queue
2. Start playing an episode from a podcast screen, then complete the episode so that another episode is autoplayed
3. Observe that the next unplayed, unarchived episode below the current episode (based on the user's selected sort order), is played. If there are no episodes below the currently playing episode available, the next nearest episode "above" the current episode will be …

Have autoplay account for podcast grouping

---

CHANGELOG.md
automotive/src/main/res/layout/activity_automotive_settings.xml
modules/features/account/src/main/res/layout-land/car_header.xml

I discovered in Automotive the acknowledgements section is hidden on the About page. It seemed to be an issue with the Constraint Layout, as it was a simple screen I switched it over to a Linear Layout and it worked.
1. Deploy the Automotive app
2. Tap the settings cog
3. Scroll down and tap About
4. ✅ Verify you can see the Acknowledgements menu option
| --- | --- |
| ![Screenshot_20230710_170430](https://github.com/Automattic/pocket-casts-android/assets/308331/85096981-73ac-4070-996e-c63fd6617765) | ![Screenshot_20230710_170055](https://github.com/Automattic/pocket-casts-android/assets/308331/ccfaa27e-ec82-4052-ae91-d745030a84fc) |

Automotive: Show the hidden Acknowledgements

---

base.gradle
build.gradle
modules/services/model/build.gradle
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/PodcastsSortType.kt

Google recommends migrating from kapt to KSP. "[it’s up to 2x faster](https://android-developers.googleblog.com/2021/09/accelerated-kotlin-build-times-with.html)". And it helps with my next PR of introducing Showkase, as it doesn't work well with kapt.
I followed [the guide](https://developer.android.com/build/migrate-to-ksp) to migrate the code. There is an issue that Daggger / Hilt don't support KSP yet but it seems fine to run them along side each other. Room, Moshi, and Glide will be using KSP.
1. Assemble all the builds `./gradlew assemble`.
2. Install the release build to an emulator `app/build/outputs/apk/release/app-release.apk`.
3. ✅ Verify the release installs and runs on the emulator.

Converted from kapt to KSP

---

CHANGELOG.md
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterFragment.kt
modules/services/localization/src/main/res/values/strings.xml

This PR adds 3 episodes on the Filter auto download.  
Fixes # @CookieyedCodes niggles
1. Tap on the Filters tab -->
2. Tap on In Progress
3. Click on the overflow icon
4. Tap filter Settings
5. toggle autodownload 
6. Tap on first
7. Tap on 3 episodes

Filter auto download modification with 3 episodes

---

modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/ExportSettingsViewModelTest.kt

This PR adds ExportSettingsViewModel Tests. Includes test cases for onExportFile, onExportByEmail, onImportByUrlClicked and onImportSelectFile which should track analytics event
Fixes # N/A

Add ExportSettingsViewModel Test

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/FolderDaoTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/utils/FakeFileGenerator.kt

This PR adds Unit tests for the FolderDao
Fixes #

FolderDao Unit Tests

---

CHANGELOG.md
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This fix a bug that was introduced when [we stopped having the showNotesFlow start with a `null`](https://github.com/Automattic/pocket-casts-android/commit/f4e962a3a49daf48d1df68a4eda9c45258cbdf0c#diff-87b79005c0e6fd34c40ee0b5333ed1d800de411a276821016df9fe87660b47ffL166-R171). That change caused the `EpisodeViewModel`'s `stateFlow` to never emit because it would wait for show notes to be emitted, which would never happen for a `UserEpisode` as a result, the watch would only show a blank `EpisodeScreen` for `UserEpisode`s.
The end effect of this is that tapping on a user-uploaded file on the watch would just show a blank screen.
> **Warning**
> I think this should be a betafix, so I'm targeting `release/7.43` with this PR. Let me know if you disagree.
I would like to add a test that …

Fix watch episode screen not working for user episodes

---

modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt

This adds a delete action on the bookmarks list screen
1. Add a few bookmarks for an episode to the bookmark table (with delete = 0) 
2. Install the debug build and login with a Plus account
3. Open the Full Screen Player for the episode selected in step 1
4. Swipe over to Bookmarks
5. Long press on a row
6. From the multiselect toolbar, tap delete icon
7. Notice that a confirmation dialog is shown
8. Confirm "Delete bookmark"
9. ✅ Notice that the bookmark is deleted
10. Repeat it for multiple bookmarks
11. ✅ Notice that bookmarks are deleted
** Bookmarks are marked deleted locally, they will be synced with the server in a separate sync request.
https://github.com/Automattic/pocket-casts-android/assets/1405144/bdf443b1-4a70-4508-ad3f-63085380e86f

Bookmarks: Add delete action

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

The server implementation of bookmark syncing is complete. After testing, I found the field bookmark `uuid` was called `bookmark_uuid` on the server, this change fixes that.
1. Edit the BookmarksViewModel class to add a bookmark when opening the page. Just above the line with `findEpisodeBookmarksFlow` on it.
```
bookmarkManager.add(episode, 42, "My bookmark")
```
2. Deploy the app
3. Sign in with a Plus account
4. Play an episode
5. In Android Studio open the "App Inspection" window and connect to the process
6. Open the full screen player and tap the bookmarks tap to add the bookmark
7. Go to the Profile tab
8. Tap "Refresh now"
9. Look in the "Network Inspector" and find the `/sync/update` call. 
10. ✅ Verify the response contains the 'UserBookmark' element similar to the one below. …

Bookmarks: sync fix

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/UpNextScreen.kt

Adds some padding to watch's up next screen.
Fixes #1153 
1. Load an account with an empty up next queue on the watch.
2. Go to the up next screen.
3. ✅ Verify that text is not too close and there is some gap between the edge of watch and screen
Tested with largest font

Watch: added some padding to Up Next screen

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/BookmarkDaoTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/BookmarksSortByDialog.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/BookmarksSortType.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt

This adds sorting to the bookmarks list.
1. Add a few bookmarks to the bookmarks table with different `create_at` and `time` values
2. Launch the app and login with Plus account
3. Open the Full Screen Player
4. Swipe to the bookmarks list
5. Tap the vertical <kbd>...</kbd> button
6. ✅ Verify you see an options menu with 2 options: Select bookmarks, Sort by
7. ✅ Verify the default sort by option is newest to oldest
8. Tap on Select bookmarks
9. ✅ Verify the view enters multi select mode
10. Tap back arrow, then tap the more (...) button again
11. Tap the Sort by option
12. ✅ Verify a new options menu opens with 3 options: "Newest to oldest", "Oldest to newest", and "Timestamp"
13. Tap on the "Oldest to newest"
14. ✅ Verify the list is now sorted with the oldest bookmarks first
15. Open …

Bookmarks - Add sorting

---

CHANGELOG.md
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodeAction.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
modules/services/views/src/main/res/menu/menu_multiselect.xml

This adds a share option to the multiselect menus as requested in the https://github.com/Automattic/pocket-casts-android/discussions/1168 discussion.
Related iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/969
1. Checkout and run `main`
2. Go to any podcast and long press any episode
3. Tap "..."
4. Tap the pencil icon
5. Reorder and tap "Done"
6. Run this branch
7. Go to any podcast and long press an episode
8. Tap "..."
9. ✅ "Share" should appear
2. Go to any podcast and long press a single episode
3. Tap "..."
4. Tap "Share"
5. ✅ The share sheet should appear
6. Dismiss it
7. Select more episodes
8. ✅ "Share" should not be available (only sharing a single episode is available)
2. Go to any podcast and long press a single episode
3. Tap "..."
4. Tap the pencil icon
5. Move …

Add share option to multiselect menu

---

modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/filter/FilterScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/filter/FilterViewModel.kt

Adds a message in case there are no episodes in the selected filter.
Fixes #1154 
1. Log into a new account with no podcast subscriptions
2. Check the filters screens for New Releases and In Progress.
3. ✅ Verify that the user is displayed a message telling that no results are found.

Watch: Updated empty state for filter screen

---

modules/features/profile/src/main/res/layout/activity_add_file.xml

I just want to preface this with this is my first open source contribution. I use the Pocket Casts app almost everyday and am an aspiring software engineer, so I decided to give a few of the issues tagged as "good first issue" a shot. I figured moving the _Save_ button on the Add File screen would be a good start. As it is now, the _Save_ button is a bit too far to the right of the screen as you can see in the before screenshot below.
Fixes #63 
1. Go to the user account page.
2. Click on the _Files_ button.
3. Click the _Add_ button (Floating Action Button). 
4. Select a file to upload.
5. You will automatically be taken to the _Add File_ screen.
- It's just a minor UI tweak.
- I don't think this change needs any tests updated.
- No strings added.
- No compose components added or …

added left and right padding to toolbar

---

modules/features/player/src/main/AndroidManifest.xml
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfItem.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkActivityContract.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkArguments.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout-land/adapter_player_header.xml
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/FormField.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Modifier.kt
modules/services/images/src/main/res/drawable/ic_bookmark.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/views/src/main/res/layout/activity_blank_fragment.xml

You can now add bookmarks from the full screen player.
It uses another activity so I could add `android:windowSoftInputMode="adjustResize"` and have the "Save bookmark" button just above the keyboard. I'm not really happy with the amount of code to setup the activity but it might be worth it to be able to add a bookmark quickly. 
2. Tap on the mini player to open the full screen player
3. Tap on the shelf three dots icon
4. Tap Add bookmark
5. ✅ Verify the "Add bookmark" page is shown
6. Tap "Save bookmark"
7. ✅ Verify a Snackbar is shown
8. Tap the "View" action in the Snackbar
9. ✅ Verify it takes you to the bookmarks tab and the new bookmark is present
10. Tap the "Now Playing" 
11. Tap on the shelf three dots icon
12. Tap the edit pencil
13. Use the drag handles to …

Add bookmarks from the player shelf

---

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt

This fixes the max icons count for episodes multi-select.
Fixes #1199
- Open a podcast
- Long press an episode
- ✅ Notice that multi-select toolbar appears with 4 icons

Fix max icons count in episodes multi-select

---

CHANGELOG.md
modules/features/player/src/main/res/layout-land/adapter_player_header.xml

Fixes: Swiping up to get to "Up Next" doesn't work when unfolded (p1690329518000709-slack-C028JAG44VD)
Test Device : Pixel Fold
1. Open the app on Pixel Fold emulator - landscape mode
4. Go to Now Playing
5. Swipe up
6. Notice that Up Next is shown
7. Repeat steps 3-6 after fold/ unfold phone
8. Notice that Up Next is still shown
**  The issue is not limited to foldable devices. Swiping up to get to "Up Next" on Now Playing never worked in landscape mode, and I just enabled it.
https://github.com/Automattic/pocket-casts-android/assets/1405144/53b9d9dc-2049-4b81-a9ce-e81b34a5c34c
I also tested that the screen is not shown for Automotive or Android Auto so it does not affect those platforms.
Automotive| Android Auto
----| ----

Enable swipe up in now playing landscape

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/BookmarksFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/TabsViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/features/podcasts/src/main/res/layout/adapter_episode_header.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkItem.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/PodcastBookmark.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Bookmark.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt

This displays bookmarks on the podcast details page.
2. Play an episode and add a few bookmarks
3. Go to corresponding `Podcast Details` page
4. ✅  Notice that tabs are displayed
5. Tap on bookmarks tab
6. ✅ Notice that bookmarks are displayed
P.S. I have not added any empty view/ search/ sorting to keep the PR small and to get validation on the direction. 
A few bigger diffs are due to indentation changes and other changes include supporting a new view holder for tabs and bookmarks.

Bookmarks - Show on podcast page

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/BookmarkDaoTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/search/BookmarkSearchHandler.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/search/EpisodeSearchHandler.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/search/SearchHandler.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkHeaderViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt

This adds bookmark search on the podcast page.
2. Play an episode and add a few bookmarks
3. Go to the corresponding `Podcast Details` page
5. Tap on bookmarks tab
6. Search for bookmark title
7. ✅ Notice that the bookmark is displayed
8. Search for bookmark's episode title
9. ✅ Notice that the bookmark for that episode is displayed
https://github.com/Automattic/pocket-casts-android/assets/1405144/b4a4b9e6-9aee-40fc-b1e3-ea9ee42dd764

Bookmarks - Add search on podcast page

---

CHANGELOG.md
modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsScreen.kt

For the refresh setting we were reusing strings from the app on the watch and they included references to auto download, which does not happen on the watch ([yet](https://github.com/Automattic/pocket-casts-android/issues/1099)). This updates those strings to not reference auto downloading.
In addition, I took this opportunity to shorten the strings since the watch screen is so small.
1. Open the settings on the watch
2. Verify that the text below the "Background refresh" toggle makes sense both when the setting is toggled on and when it is toggled off.
| ![Screenshot 2023-07-27 at 10 51 11 AM](https://github.com/Automattic/pocket-casts-android/assets/4656348/cc3c12d6-3dbf-46fb-ae1f-86e27fc03aca) | ![Screenshot 2023-07-27 at 1 34 54 …

Remove references to auto download on watch

---

app/proguard-rules.pro

Tapping on the Discover tab throws the following error which crashes the app:
```
Caused by: java.lang.IllegalArgumentException: Unable to create call adapter for class go.y
for method ListWebService.getDiscoverFeed
at retrofit2.Utils.methodError(SourceFile:5)
at retrofit2.HttpServiceMethod.createCallAdapter(SourceFile:15)
at retrofit2.HttpServiceMethod.parseAnnotations(SourceFile:69)
at retrofit2.ServiceMethod.parseAnnotations(SourceFile:20)
at retrofit2.Retrofit.loadServiceMethod(SourceFile:25)
at retrofit2.Retrofit$1.invoke(SourceFile:38)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy13.getDiscoverFeed(Unknown Source)
at hd.a.b(SourceFile:5)
at au.com.shiftyjelly.pocketcasts.discover.viewmodel.DiscoverViewModel.K(SourceFile:8)
at t9.h0.w1(SourceFile:42)
at …
```

Fixing app crash with Retrofit on the Discover tab

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/networking/PocketCastsNetworkingRules.kt

We've had a few reports of issues downloading episodes on the watch. We're using the horologist network awareness library for downloads, and this PR logs which network is selected by that library. My thinking is that it could be helpful to see in the logs what network is being selected when the user reports that downloads are failing.
Fixes # 
1. Download an episode in the watch app
2. Verify that the "Preferred network according to networking rules..." line appears in the logs

Add logging for network selected by networking rules

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkItem.kt

This adds bookmarks multi-select on the podcast page.
2. Play an episode and add a few bookmarks
3. Go to the corresponding Podcast Details page
4. Tap on bookmarks tab
5. Long press on a row
6. ✅ Verify you enter multi selection mode and the action bar appears
7. Tap on a row, ✅ verify the item is now selected
8. ✅ Verify the action bar selection count updated
9. ✅ Verify the edit option is visible
10. Tap the row again to deselect it, ✅ Verify the edit option is hidden
11. Tap Select All from more options in the multi-select toolbar
12. ✅ Verify all the items are selected
13. Tap and hold on a row again
14. ✅ Verify you see the 'Select All Above' , 'Select All ' and 'Select All Below' options
15. Tap each option and ✅ verify the correct items are selected
13. Tap and …

Bookmarks - Add multiselect on podcast page

---

modules/services/localization/src/main/res/values/strings.xml

While adding the UK English translations to GlotPress I noticed some of the default locale aren't in US English. Also there is a invalid key "discover_category_governmentGovernment" that I have removed as it isn't being used. 
This is so minor that I don't think it needs test steps.

Spelling fixes as the default locale is US English

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

This adds tracks for the Whats new dialog
For testing this, I would comment out [these lines](https://github.com/Automattic/pocket-casts-android/blob/d4b3363fbdb0793d9c5c9687768be00a19aa047b/app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt#L740-L742) so the what's new dialog is always presented.
1. Run the app
2. When the What's New popup appears you should see a Tracked: whatsnew_displayed ["version": 9115, ...] in the logs
3. If you tap "Maybe later" or tap outside the dialog, you should see Tracked: whatsnew_dismissed ["version": 9115, ...] in the logs. If you tap "Enable it now" you should see Tracked: whatsnew_confirm_button_tapped ["version": 9115, ...] in the logs.

What's new tracks

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/StarRatingView.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt

When a podcast doesn't have any ratings it looks like they have zero stars. This change hides the star if there are no ratings.
1. Tap the Discover tab
2. Tap search
3. Paste in the staging share URL https://pcast.pocketcasts.net/51phk3pk
4. ✅ Verify no stars are visible
5. Go back to search and find The Daily
6. ✅ Verify the stars are visible
| --- | --- |
| ![Screenshot_20230804_140129](https://github.com/Automattic/pocket-casts-android/assets/308331/e858ea23-d563-4b2c-8726-e34b4174a3f8) | ![Screenshot_20230804_135933](https://github.com/Automattic/pocket-casts-android/assets/308331/c9a4dd77-c1b6-4364-ba23-439980b1c270) |

Hide ratings if the podcast doesn't have any.

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt

Fixes #1226 After performing a search, dismissing then reopening the app also opens the keyboard again.
Just follow the same procedure as described in issue #1226
https://github.com/Automattic/pocket-casts-android/assets/52420957/9cb635b9-ab89-466b-9f63-cf92399cdf67

fix #1226 keyboard reopening bug fixed

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt

Hides the Multiselect option when upNext queue is empty, it will be visible when there is at least one item in the queue.
Fixes #1147 
Follow the same steps as described in issue  #1147
https://github.com/Automattic/pocket-casts-android/assets/52420957/ff71cfbe-4ad0-472e-afd2-fa71310799b5

removed multi select options when up next queue is empty

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoArchiveFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoArchiveFragmentViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoArchiveAfterPlayingSetting.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoArchiveInactiveSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt

This updates the archive settings to be user settings.
In doing this, I found that we were persisting some of the archive settings as localized strings. Not surprisingly, this can cause [some issues](https://github.com/Automattic/pocket-casts-android/issues/741#issuecomment-1663067646) when a user changes the language on their phone. This PR fixes this by migrating the settings to a new key in shared preferences that is no longer tied to the app's language.
I also updated our support logs so that the auto archive settings are no longer displayed with a localized string.
For each setting in the "Auto Archive" section:
2. Verify that the setting has the same default value that it had before
3. Change the setting to a new value
4. Force close the app
5. Verify that …

Settings Sync - Refactor archive settings to be UserSettings

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt

This converts the file settings to be UserSettings.
1. Fresh install of build from this PR
2. Log into a Plus account
3. Go to "Profile" tab → "Files" → three-dot-overflow-menu → "Files Settings"
4. Verify that the only setting that defaults to being on is "Only on WiFi". All other settings should be turned off.
1. Fresh install of app built from `main`
2. Log into a Plus account
3. Go to "Profile" tab → "Files" → three-dot-overflow-menu → "Files Settings"
4. Update all the settings to not be their default (so you want them all turned on except "Only on WiFi")
5. Install a build of the app from this PR
6. Verify that all the settings have their updated values
Verify that toggling each setting still works.
- The automatic deletion settings only appear to work when skipping to the end of an …

Settings Sync - Make file settings into UserSettings

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastManagerTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextQueueTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/settings/advanced/AdvancedSettingsTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/helper/PlayButtonListener.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheet.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModelTest.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModelTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsViewModel.kt

This makes the stream warning and background refresh settings into UserSettings.
I also moved the MockUserSetting class out of the separate test classes and instead into the UserSetting class itself. Ideally, we would only include this as a test artifact, and I could do that, but I don't see any way to accomplish that without quite a bit of boilerplate, and I just didn't think it was worth it to avoid bundling this small mock class in the app. Let me know if you disagree or have a better idea how to handle this mock class.
2. Go to "Profile" → ⚙️ → "Storage & data use"
3. Verify that "Background refresh" is defaulted to on (on the watch this defaults to off) and "Warn before using data" is defaulted to off
4. Toggle the warning before using data to be on
5. …

Settings Sync - Make refresh and stream warning into UserSettings

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/PrivacyViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTracker.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/FirebaseAnalyticsTracker.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/PrivacySettingsViewModel.kt

Updating the privacy settings to be UserSettings
1.  Verify that "Analytics" toggle in the Privacy settings defaults to on
2. Verify that tracks come through when the "Analytics" toggle is on, and that they do not come through when it is off.
1. Make a change to the app so you can trigger a recognizable crash by tapping some button
2. Freshly install a release build
3. Log into an account
4. Verify that in the privacy setting for "Crash reports" defaults to off
5. Turn this toggle "on"
6. Leave "Link your account to crashes" to be "off"
7. Trigger a crash
8. Toggle "Link your account to crashes" to be "on"
9. Trigger a crash
10. Toggle "Crash reports" to off
11. Trigger a crash
12. Reopen the app
13. Check Sentry and confirm that you there are only two matching crash events: the first one …

Convert privacy settings into UserSettings

---

modules/features/player/src/main/AndroidManifest.xml
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectHelper.kt

This links multi-select toolbar edit action for bookmarks.
- Add a few bookmarks to an episode
- Open bookmarks view 
- Long press a bookmark
- Tap edit icon on the multi-select toolbar
- ✅ Notice that the change title view is displayed
- Change the title and click save
- ✅ Notice that you're returned to the bookmarks view and the title is changed
** Repeat above for bookmarks on Episode Details, Player, Podcast Details, and User Episodes(Cloud Files) 
https://github.com/Automattic/pocket-casts-android/assets/1405144/093e8fe1-418b-4188-bae2-8a1fc801ef3a

Bookmarks - Link edit action

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/extensions/PlaybackEffects.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt

This refactors the global playback efffets settings to use the UserSettings structure. I really liked how it was easy to just create a UserSetting for the `PlaybackEffects` that delegated to UserSettings for the speed, trim silence, and volume boost settings.
1. Install a build from the `feature/sync-settings-refactor` branch
2. Start playing an episode and update all the playback effects (speed, trim silence, volume boost)
3. Install a build from this PR
4. Verfiy that all the updated settings are carried over
1. Do a fresh install from this branch
2. Check that the speed value is defaulted to 1.0
3. Check that the trim silence setting is defaulted to off
4. Check that the volume boost setting is defaulted to off

Settings Sync - Make global playback effects into UserSettings

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingWelcomeViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

This makes the newsletter preference into a `UserSetting`. I also did a slight tweak to how we indicate whether a setting needs to be synced, but the actual behavior is unchanged.
1. Veriify the newsletter setting value for a PC account
2. Log into that account on a clean install of the app
3. Verify that the account screen reflects the proper newsletter setting value
4. Change the newsletter setting value
5. Sync the app
6. Uninstall and reinstall the app
7. Verify that the new newsletter setting is picked up

Settings Sync - Make newsletter settings a UserSetting

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/PromoCodeFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

This makes the free gift acknowledgement a UserSetting.
I separated this setting out into its own PR because I think the code changes are simple enough to be reviewed on their own since this is just reusing the same settings infrastructure that I've migrated the other Settings to. I don't know a good way to test this without making a lot of code changes, so I wanted to make the code as easy to review as possible.

Settings Sync - Make promo code acknowlegement a UserSetting

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/NotesViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FileStorage.java
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ShowNotesFormatter.kt

This PR is removing mthods from the Settings class where either the setting is never getting read/used or the setting is never getting set (meaning that only the default value ever gets used, which means we don't need the setting). The goal of this is to clean out unused code and to reduce the quite large public interface of our Settings class.
There are a lot of changes here. I considered breaking this out into multiple PRs, but putting each setting in its own PR would lead to a LOT of PRs. Instead, I made each setting that got removed its own commit. In reviewing this, I would go through each commit instead of trying to look at all the changes at once.
One effect this will have is that for settings that are used but never set, it is possible that a user could have set the setting when …

Remove no longer used settings from Settings class

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkHeaderViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/TabsViewHolder.kt
modules/features/podcasts/src/main/res/layout/adapter_episode_header.xml
modules/features/podcasts/src/main/res/layout/view_podcast_header_top.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/ButtonTabs.kt

This updates the podcast page bookmark tabs to match the design.
1. Make sure you are signed into an account with a Plus subscription
2. Go to the 'Podcasts' tab
3. Tap on a podcast artwork
4. ✅ Verify the tabs work correctly
| Light | Dark | Indigo |
| --- | --- | --- |
| ![Screenshot_20230811_084315](https://github.com/Automattic/pocket-casts-android/assets/308331/4d0cb3cc-3020-447d-94b3-7e9fce387171) | ![Screenshot_20230811_084356](https://github.com/Automattic/pocket-casts-android/assets/308331/b2bd3082-aec9-440c-93c5-0c677334b831) | ![Screenshot_20230811_084417](https://github.com/Automattic/pocket-casts-android/assets/308331/1990bd2a-1a5b-4d32-a04c-9e04ef8c71e1) |

Updating bookmark tabs design

---

CHANGELOG.md
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveAboutFragment.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt

This change adds the logs to the Automotive version of the app to help us debug issues one of our Automotive partners is having. 
Thanks @ashiagr, this uses the log viewer from your PR. I didn't include the encrypted upload in this version and instead will ask for a screenshot. To help with this I have scrolled to the bottom of the logs as this is where the latest logs are. 
I also added a link to our "Help & Feedback" section.
1. Tap the settings cog
2. Scroll to the bottom of the page and tap "About"
3. Scroll to the bottom of the page and tap "Help & Feedback"
4. ✅ Verify it shows a link to the support website
5. Tap the back arrow
6. Tap "Logs"
7. ✅ Verify the logs are shown
https://github.com/Automattic/pocket-casts-android/assets/308331/0823cb36-8fd3-4ec7-a264-e2ef1d3989a3

Adding logs to Automotive

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt
modules/services/localization/src/main/res/values/strings.xml

This adds buttons to make it easy to get to the top or bottom of the logs screen (it can get very long).
1. Go to logs screen (Profile tab → ⚙️ → "Help & feedback" → logs button on toolbar)
2. Verify that the toolbar has scroll to top and scroll to bottom buttons and they work as expected
https://github.com/Automattic/pocket-casts-android/assets/4656348/a1eb092f-8848-420f-9556-ff19d241cb74

Add scroll to top/bottom to logs screen

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

This PR addresses an issue where we were not using the notifications enabled setting to determine the state of the notifications enabled toggle. Instead we were checking whether any podcasts had notifications enabled. This PR updates this and makes the behavior consistent with iOS.
This issue exists on `main` and is not a result of the recent Settings refactorings.
This change feels a bit tricky, so let me know if you can think of any undesireable behavior that these changes might introduce.
I am targeting the settings sync refactor branch with this change because it is easier to just include this with the other settings changes, and I anticipate that I'll be merging this branch to `main` pretty soon. 
1. Go to the notification settings
2. Change the notification setting
3. Exit the …

Improve handling of notification enabled setting

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/UpNextQueueTest.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
automotive/src/main/res/xml/preferences_auto.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/LastPlayedList.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt

This makes the automotive settings for subscribing to played podcasts, showing played podcasts, and the setting for the last played list into UserSettings. 
In addition, this fixes a bug whereby auto play on automotive was not updating the autoPlay user setting. It was just updating the persisted setting directly, which meant the UserSetting's flow was not updated and would not reflect the new value until the app was restarted. I introduced this bug when I refactored the auto play setting to be a `UserSetting` (https://github.com/Automattic/pocket-casts-android/pull/1213), so it never got released.
On the automotive app, ensure that toggling the subscribe to played podcast setting 
- is defaulted to true
- controls whether played podcasts get automatically subscribed to
- is persisted …

Settings Sync - convert remaining settings to UserSettings

---

CHANGELOG.md
TESTING-CHECKLIST.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
base.gradle
dependencies.gradle
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SignInState.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt

This addressses an issue where the upgrade flow for logged-out users would exit after the user signed in with a google account. Basically, it's a follow-up to https://github.com/Automattic/pocket-casts-android/pull/1204 that further improves the flow.
As part of this I added test scenarios for the onboarding flow to our testing checklist. I also created a very basic first step toward testing the onboarding flow's navigation. All it does now is test the start destination though because this ended up taking a bit to get working and I ran out of time. I suspect we may be better off moving as much of the navigation logic as we can into a view model and testing that in isolation. If you think it's not worth adding the integration test here since it's not doing much yet, just let me know and I …

Ensure upgrade flow continues after signing into account with google sign in

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/ManualCleanupViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

This change fixes the issue that if any episodes in the Up Next are downloaded when the downloads are cleared in the settings area they are removed from the Up Next. 
1. Tap on the 'Profile' tab
2. Tap on the settings cog
3. Tap on 'Auto download'
4. Turn on 'Episodes added to Up Next'
5. Add multiple episodes to the Up Next
6. Open the Up Next
7. ✅ Verify the downloaded icon is on the episode rows
8. Go back to the settings section
9. Tap on 'Storage & data use'
10. Tap on 'Downloaded files'
11. Tick all the checkboxes and tap 'Clean up'
12. ✅ Verify the Up Next episodes haven't been removed
https://github.com/Automattic/pocket-casts-android/assets/308331/6396fe63-b5b8-4f2b-a332-de6458a49c00

Stop episodes being removed from the Up Next when clearing downloads.

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt

This
- Updates headphone controls options layout from `SettingRadioDialogRow` to `OptionsDialog`
- Displays "Add bookmark" option only if the user is eligible for `Bookmarks` feature
- Returns default values for headphone controls if the previous value is "Add bookmark" and the user is not eligible for the `Bookmarks` feature
Slack discussion p1692252268904039/1692162285.498199-slack-C055BDMU095
P.S: Since Android didn't have a skip chapters option for headphone controls, we only focussed on adding skip actions and "Add bookmark" in this PR. Other options will be added as part of a separate PR.
Prerequisites:
- Patron + Bookmarks features enabled in `Feature` class
1. Upgrade to `Patron` plan
2. Go to `Profile` -> `Settings`
3. Notice that "Headphone …

Bookmarks - Update headphone controls options display

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/CancelConfirmationViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/HeadphoneAction.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

This updates the headphone controls to be UserSettings and also makes the headphone control settings react to changes in the user subscription to insure it is always up-to-date (see discussion in https://github.com/Automattic/pocket-casts-android/pull/1284#pullrequestreview-1583549610).
This PR is targeting the `feature/sync-settings-refactor` branch (which currently has a PR open to merge to `main`)
1. Make sure the headphone controls update and work as expected.
2. When logged into a Patron account, set the headphone controls to "Add bookmark"
3. Log out of your account
4. Note that the headphone controls are no longer "Add bookmark"
5. Log back into your Patron account
6. Note that the headphone controls have returns to be "Add bookmark" if they were that before (and assuming you …

Update headphone control to be UserSettings

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt

Makes it possible to select text and copy it from the in-app logs viewer.
1. Go to the in-app logs viewer ("Profile" → ⚙️ → "Help & feedback" → logs icon on the top of the screen)
2. Long press somewhere in the logs to start selecting text
https://github.com/Automattic/pocket-casts-android/assets/4656348/f1607b27-19ce-4e4c-b1ba-098540fc6eb1

Enable selecting text in logs

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

The issue is that the `LocalView.current` returns a view with zero width and height. To fix this I have replaced this logic with a `BoxWithConstraints`. 
Before I found the issue I thought it was related to the podcasts in the ViewModel being a list and not a state variable. Whilst these changes didn't fix it I believe they are still worth making. Let me know what you think, I will remove them if you don't agree.
Fixes https://github.com/Automattic/pocket-casts-android/issues/1295
1. Do a refresh install of the app
2. ✅ Verify you are shown the podcast artwork when the app launches
3. Don't sign in and close the dialog
4. Subscribe to a few podcasts
5. Tap on the 'Profile' tab
6. Tap "Set Up Account'
7. ✅ Verify the subscribed podcasts are included in the artwork …

Fix the artwork not loading on the onboarding page

---

app/proguard-rules.pro
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

This change fixes two issues.
1. The new Protocol Buffers don't work after Proguard has run.
2. After your first login if it downloaded any bookmarks they are uploaded to the server again.
1. In `Feature.kt` set the default value for bookmarks to true.
2. Build a release version of the app `./gradlew app:assembleRelease`
4. Install the build
5. Login to a Pocket Casts Plus account
6. Add a bookmark
7. On the 'Profile' tab manually refresh
8. ✅ Verify the refresh is successful
1. Add some bookmarks to a Pocket Casts account
2. Sign out and clear the app storage (or reinstall)
3. Open the App Inspection window
4. Open the Network Inspector
5. Tap Refresh Now
6. ✅ Verify the https://api.pocketcasts.net/sync/update call doesn't send any changes to the server. `"changes":[]`

Fix Protocol Buffers in the release build

---

base.gradle
dependencies.gradle
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt

As we don't use the NDK we don't need to include `sentry-android-ndk`. Removing these libraries reduces the APK from 28.4MB to 23.8MB. 
We have also been contacted by an Automotive partner as these libraries include old C functions which it recommends not using. I thought we could have tried just the library upgrade but if we don't need these anyway maybe it's best to remove them.
Here is the [Sentry documentation](https://docs.sentry.io/platforms/android/configuration/using-ndk/#using-the-sdk-without-the-ndk).
1. Change `modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt` so the developer menu is visible in a release build.
2. Install a release build
3. Go to 'Profile' tab -> settings cog -> Developer
4. Tap 'Report a crash'
5. ✅ …

Remove Sentry NDK

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeListAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt

This PR fixes the bookmark icon visibility on the Podcast detail screen as discussed [here](https://github.com/Automattic/pocket-casts-android/pull/1276#issuecomment-1689321629)
The UserEpisodes was resolved on [1276](https://github.com/Automattic/pocket-casts-android/pull/1276)
Fixes # [1273](https://github.com/Automattic/pocket-casts-android/issues/1273)
1. Login using Paid account and sign as Patron
2. Go to Podcast 
3. Play one episode 
4. Add Bookmark 
5. Go to the the Podcast episode list and check the bookmark is added 
6. Delete bookmark. 
7. Observe the Bookmark icon is deleted

Fix delete icon visibility on podcast detail screen

---

CHANGELOG.md
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

We have many complaints about playback skipping to different positions in an episode unexpectedly (https://github.com/Automattic/pocket-casts-android/issues/157). I think that at least the majority of the times this is happening is because the podcast provider is changing the dynamic ads in the episode. If those ads are of a different length, then our playback position value will end up representing a different part of the episode.
I do not see any straightforward ways to address this, so this PR is attempting to mitigate the issue a bit by checking if the duration of a podcast episode has changed by more than 30 seconds and
1. Presenting a toast message to the user advising them that the duration of the podcast has changed. I figured that this at least gives the listener a clue that …

Log and notify users when episode duration changes unexpectedly

---

CHANGELOG.md
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt

With the 7.45 release we've seen a significant increase in ANRs: https://github.com/Automattic/pocket-casts-android/issues/1314. This PR avoids the ANRs by addressing part of the underlying issue. 
Note that this PR is targeting a new `7.45.1` hotfix branch because I think this should be a hotfix since it is causing thousands of ANRs a day. For that reason, I am keeping this PR small and lean (basically the simplest changes that address the ANRs), and I will open a separate PR that builds on this for a betafix release (https://github.com/Automattic/pocket-casts-android/pull/1316).
This fix is basically just to make sure that we avoid iterating through the multiselect items when we select or deselect all of the multiselect items.
1. Make sure you have a bunch of episodes in your Up Next …

Avoid multiselect ANRs

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt

This displays the Add Bookmark option if the user does not have bookmarks unlocked
Part of https://github.com/Automattic/pocket-casts-android/issues/1307
Prerequisites
- Patron and Bookmarks features enabled
1. Install release build without being logged in
2. Go to `Profile` -> `Settings` -> `Headphone controls`
3. Notice that `Previous` Action is displayed above `Next` action.
4. Tap on `Previous action` or `Next action`
5. ✅ Notice that `Add bookmark` is shown in options
6. Tap on `Add bookmark`
7. ✅ Notice that Upsell flow is shown
8. Dismiss Upsell flow 
9. ✅ Notice that previous value is retained for the action started in step 4 
10. Tap on `Add bookmark` again
11. Complete Upsell flow
12. ✅ Notice that `Add bookmark` option is selected for …

Bookmarks - Update Add Bookmark Headphone Control

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
dependencies.gradle
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/DispatcherModule.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

This avoids ANRs when archiving multiple episodes by wrapping all the db calls into a single transaction.
> **Note**
> Note that this change is targeting the beta branch. Let me know if you think that's not the right call this late in the beta period.
There are a lot of other places where we should consider creating transactions like this, but this is the most significant performance issue I'm seeing so far (by a wide margin), so I kept this PR small (and hopefully safe).
2. Open the Tim Ferriss Show podcast page
3. Tap the three dots
4. Tap Archive All and confirm
5. Observe that the UI locks for <1 second (without this change it would lock the UI on my device for ~30 seconds)

Use transaction when archiving multiple episodes

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This includes a temporary fix for https://a8c.sentry.io/share/issue/a00791f201394715be1cdffda7814fda/ 
> **Warning**
> Targets release/7.46
I have not been able to reproduce the issue. I have converted `notificationPermissionChecker` to be nullable, and attempted `notify(...)` even when `notificationPermissionChecker`  is null to bring back the original implementation. I have also added logs to `Sentry` and `LogBuffer` if it still fails.

Temporary fix for notification permission checker

---

CHANGELOG.md
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt

This avoids some significant ANRs caused by us adding multiple observers for the same lifecycle owner. This feels like a bit of a band-aid, but I'm not seeing that this introduces any new issues and any other way I see to address the ANRs (such as avoiding us trying to add an observer multiple times) feels much riskier, so I'd rather not try them this close to the `7.46` release and instead stick with this simple fix to address the ANRs.
> **Note**
> This PR is targeting to `release/7.46` branch which is due to be released pretty much immediately.
My thinking is that we can work on a fuller fix in https://github.com/Automattic/pocket-casts-android/pull/1316 for the `7.37` release.
Thanks to @emilylaguna for coming up with the steps to reproduce and proposed fix for this. 🤩 
1. Launch the …

Remove previous toolbar action observers when adding a new one

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelperTest.kt
base.gradle
dependencies.gradle
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModelTest.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/di/ReviewModule.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelper.kt

This matches iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/240 and requests in-app review if:
- The user checks Stats and stays there for more than a second after the information appears
- The user has been using the app for more than a week
- The user has a total of playedUpTo in the last 7 days bigger than 2.5 hours
- The request hasn't been made to this user before
Logic to display the review dialog only once and saving review request date matches iOS logic for consistency and future extensibility.
[Optional]
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/12428599/in-app-review.patch) (that reduces playedUpto duration check from 2.5 hours to mins)
2. Build apk and upload to [internal app …

In-app review

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModel.kt

This fixes an import issue (for @IoDispatcher) after merging https://github.com/Automattic/pocket-casts-android/pull/1305 and https://github.com/Automattic/pocket-casts-android/pull/1336  simultaneusly.
Both the branches were green but https://github.com/Automattic/pocket-casts-android/pull/1305 should have been updated with the latest `main` to prevent this issue.
I also added a change log for https://github.com/Automattic/pocket-casts-android/pull/1305 since we're including it in v7.47.

Fix merge issue

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/features/podcasts/src/main/res/layout/fragment_podcast.xml
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModel.kt

This sets up separate multi-select toolbars for episodes and bookmarks instead of reusing the same toolbar and setting it up based on the selected tab on the podcast details screen.
4ef7ddd5c8eff81858bfc00acf2cccf8008bc38a is a cherry pick from an unmerged PR to help with testing.
0. Enable the `Patron` and `Bookmarks` feature
1. Login with a `Patron` account
3. Long press on an episode row
4. ✅ Notice that the episode multi-select toolbar is shown
5. Select a few episodes
6. ✅ Notice that correct episodes are selected
7. Tap on the `Bookmarks` tab
8. Notice that 
- Episodes multi-select toolbar is closed
- Bookmarks multi-select toolbar is shown
9. Select a few bookmarks
10. ✅ Notice that correct bookmarks are selected
11. Tap on the `Episodes` tab
12. ✅ Notice that 
- …

Update multi select toolbars setup

---

CHANGELOG.md
modules/services/localization/src/main/res/values/strings.xml

This updates cloud storage string title from 10GB to 20GB.
> This targets v7.47 beta branch.
It should be sufficient to just check the strings file. 
Old| New
---|---

Update cloud storage limit title

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

One small step toward making sure we use coroutines when hitting the database. This didn't require any changes [at the callsite](https://github.com/Automattic/pocket-casts-android/blob/c46d2c44fa9cd37c1669b4df310976a0e2b4e8cd/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt#L776) since that was already running a coroutine.
2. Subscribe to "The Big Flop"
3. Run the following command: `adb shell am start -a android.media.action.MEDIA_PLAY_FROM_SEARCH -p au.com.shiftyjelly.pocketcasts.debug --es query "Introducing:\ The\ Big\ Flop"`
4. Observe that the episode with that name starts playing.

Make findFirstBySearchQuery a suspended function

---

app/build.gradle

Doing this to make it more obvious when we're using a build of the app that is hitting the staging server.
Verify the app uses the following icons
| debug | debugProd | release |
| --- | --- | --- |
| The `debug` icon has not changed. | | The `release` icon has not changed |
| ![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/17aeae75-47a6-4677-8ec4-69d7b6ae699d) |  ![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/a1c8b66f-f24c-437d-8111-3024cd226759) | ![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/c280cf08-dfa4-4729-862b-b3902cfc89ff) |

Give `debug` and `debugProd` buildTypes different icons

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This updates the star methods to be suspended functions. This avoids us needing to launch new coroutines within the `EpisodeManager`.
As part of this, I moved the tracks event logic into the `EpisodeManagerImpl` to avoid duplicating in all the view models where we update an episode's starred status.
Test starring/unstarring episodes
1. From the media notification
2. From the episode details screen
3. From multiselect on the podcast screen
4. From the now playing screen
5. From the watch app

Make star method a suspended function

---

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt

Although the number of ANRs is lower with `7.46`, they [are still happening](https://a8c.sentry.io/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=ApplicationNotResponding%3A+Background+ANR&project=6711064&query=issue%3APOCKET-CASTS-ANDROID-MR3+release.version%3A7.46&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29), and I haven't been able to reproduce them. With this PR, I'm proposing adding some Sentry breadcrumbs around the `toolbarActions` changes to see if/how those may be contributing to the ANRs.
Based on the stacktraces in Sentry, it seems pretty likely that extra updates to the list of `toolbarActions` are causing the problem, but it's hard to be 100% sure. This will either disprove that theory, or (🤞) give us more …

Add Sentry breadcrumbs when toolbar actions change

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTest.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/PodcastListViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/addtoupnext/ActionRunnerAddToUpNext.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateEpisodeTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/FileStorage.java
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This PR makes the suspended function for finding podcasts by id the preferred method by deprecating the other methods and removing the usages of the other methods where it is easy to do so. I did not remove all usages of the other methods because I wanted to keep this PR reviewable and reduce the risk of regressions. My thinking is that we'll be better off trying to remove the big RxJava chains when we are actually making changes to them because we'll be more familiar with what they're doing then and there will already be a risk of regression at that point since we'll be making changes.
I'm planning to make some more changes similar to this, so let me know if you think any other approach to this makes more sense.
Smoke test interacting with a few podcasts in different ways (playing …

Prefer suspended method for finding podcast by uuid

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This adds the podcast uuid to the support logs when an episode is played because our support team has told us that sometimes it isn't obvious from the logs what podcast an episode comes from. internal ref: pdzxoO-fr-p2#comment-352
I also used "_" as the placeholder for missing values instead of the empty string because I thought that would make it easier to see in the support logs that a value is missing. Let me know if you disagree though.
2. Verify that the relevant support log line starting with "Playback: Play" includes the podcast uuid at the end of the line.

Add podcast uuid to support logs when playing episode

---

CHANGELOG.md
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

It looks like the episode duration diff toast might get shown more than I anticipated, so let's remove it for the time being.
> **Note**
> This PR is targeting `release/7.47`, but I don't think we need to rush out a new beta for this.
1. Play "Monday Morning Podcast 9-4-23" from Bill Burr's Monday Morning Podcast
2. Observe that the logs contain a message about the episode duration changing when you start playing the episode
3. Observe that there is _not_ a toast message shown to the user

Remove toast message when episode duration diff changes

---

modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/FirebaseRemoteFeatureProvider.kt

We're getting [a bunch of events in Sentry](https://a8c.sentry.io/issues/4416441119/events/aa089a13322f4045a1c7c54c0c2205df/) for firebase successfully fetching a remove flag. I'm guessing these are showing up because we're logging this as an error (`Timber.e`). I didn't actually know that error logs got sent to Sentry, so today-i-learned. 
This doesn't really seem like an error, and I don't think we need these in Sentry, so this PR is just changing this to be an `info` log.
- X ] If this is a user-facing change, I have added an entry in CHANGELOG.md

Make log for successful remote flag fetch not an error log

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/ui/PlaybackServiceTest.kt
automotive/src/androidTest/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackServiceTest.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackService.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/DurationOptionsFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/EpisodeOptionsFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/PodcastOptionsFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/TimeOptionsFragment.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

This change adds the recommendations to Automotive. This feature is already available for Android Auto. I made some code changes and added a test to ensure it still worked correctly. There was a bug that you could have the same episode in the list from the Up Next queue and the top filter.
It's hard to test it from the Automotive emulator as I don't know how to trigger it. The code changes to the suggestion method can be tested using Android Auto in Google Maps.
1. Deploy to a physical device
2. Start playing an episode
3. Add another episode to your Up Next
4. Open Google Maps
5. Setup navigation to a location
6. The Pocket Casts mini player should appear
7. Tap on the mini player in Google Maps
8. Tap "Browse Pocket Debug"
9. ✅ Verify your current episode is first, followed by your Up …

Add recommendations to Automotive

---

dependencies.gradle
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/UserEpisodePodcastSubstitute.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/extensions/Podcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncJob.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt

This was an excellent suggestion made in another [PR review](https://github.com/Automattic/pocket-casts-android/pull/1362#discussion_r1319970327). As we often use the user file podcast as a Podcast object, this PR creates one for us. It looks much cleaner and stops the repeating code.
There are lots of changes which are simple enough to just look through but it might be worth testing sync.
1. Sign in to a Plus Pocket Casts account
2. Go to Profile -> Files
3. Add a new file
4. Tap the file row
5. Tap "Upload to Cloud"
6. Tap the file row again
7. Tap "Add to Up Next"
8. Go back to the Profile tab and manually refresh
9. Go to another app and confirm the file is in the Up Next.

Moving the user files podcast substitute.

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarkPage.kt

This PR disables the save bookmark button when the title is blank.
Fixes # 
1. Open player
2. Add bookmark 
3. Delete the default title, 
4. Observe the save bookmark icon is disabled

Disable Save Bookmark Button when bookmark title is blank

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheet.kt

This disables the bookmarks menu on `Files` screen
> **Warning**
> Targets 7.47
1. Open `Profile` -> `Files` 
2. Add a file
3. Tap on a file row
4. Notice that the file details bottom sheet doesn't have a "Bookmarks" menu

Disable bookmarks menu

---

CHANGELOG.md
app/build.gradle
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelperTest.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModelTest.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/FeatureFlagWrapper.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/DefaultReleaseFeatureProvider.kt
modules/services/views/build.gradle
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelper.kt

This puts the in-app-review dialog behind a feature flag and enables it only for a debug build..
> **Warning**
> Targets 7.47
- Make sure that tests run fine and CI is green.
- Optionally, test that the in-app review dialog is not shown for the testing steps in https://github.com/Automattic/pocket-casts-android/pull/1305
- All strings that need to be localized are in `modules/services/localization/src/main/res/values/strings.xml` N/A
- Any jetpack compose components I added or changed are covered by compose previews N/A
- with different themes N/A
- with a landscape orientation N/A
- with the device set to have a large display and font size N/A
- for accessibility with TalkBack N/A

Disable in app review prompt

---

.buildkite/pipeline.yml

We are already using `android` agent for this pipeline, but having it specified in the `.buildkite/pipeline.yml` file will make it easier to programmatically change it.
I am working on a small bash script that will make it easier to test `android-staging` changes such as [this one](https://github.com/wordpress-mobile/WordPress-Android/pull/18773) and this change will help keep that script simple.

Specify android agent in Buildkite pipeline

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt

There is an issue on the podcast page where the view model keeps hold of the flowable which updates the UI state. In the logs you can see it repeatedly outputting the following "Observing podcast 0fb82b10-55ed-0138-3a41-0e94336f7152 changes". It seems to be an issue when the flowable is set up that the old flowable is still there.  
I have changed the logic to just be Rx rather than using asFlow() and disposed of the previous flowable before creating a new one.
1. Set up the logcat filter `package:au.com.shiftyjelly.pocketcasts.debug "Observing podcast"`
2. Go the Podcasts tab 
3. Open a podcast 
4. ✅ Verify a log line similar to `Observing podcast 0fb82b10-55ed-0138-3a41-0e94336f7152 changes` appears.
5. Tap the settings cog
6. Change the "Skip first time" and click OK
7. Tap back to …

On the podcast page reduce the amount of observers

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt

The top ANR in Sentry is the following:
The issue appears at FiltersFragment.checkForSavedFilter() on the `runBlocking` line. This change ahs removed this and switched to Coroutines.
1. Tap on the Filters tab
2. If the list of filters is showing, tap on a filter.
3. Tap on the Podcasts tab
4. Tap on the Filters tab
5. ✅ Verify the filter list of episodes are shown

Remove the FiltersFragment runBlocking code

---

automotive/src/androidTest/java/au/com/shiftyjelly/pocketcasts/AutoPlaybackServiceTest.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/DurationOptionsFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/EpisodeOptionsFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListViewModel.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragmentViewModel.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/PodcastOptionsFragment.kt
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/TimeOptionsFragment.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PlaylistDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

This cherry picks #1383 from `main` branch to `release/7.47`
In order to properly cherry-pick #1383  to `release/7.47`, I also picked `suspend fun findByUuid(...)` methods from `PlaylistManager` and `PlaylistDao` added in #1362 after renaming existing methods to `findByUuidSync(..)`.
I did not pick the entire  #1362 to get minimum required changes to the release branch at this time.
Refer to testing instruction in #1383
1. Tap on the Filters tab
2. If the list of filters is showing, tap on a filter.
3. Tap on the Podcasts tab
4. Tap on the Filters tab
5. :white_check_mark: Verify the filter list of episodes are shown

Cherry pick #1383 to 7.47

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt

Just removing a duplicate log message because I was noticing that we have two of these each time.
> **Note**
> I'm targeting this for `release/7.47` just because this seems like a quite safe change and it will help reduce a bit of noise for us when debugging. Let me know if you think this should target `main` instead.
If CI is good we should be good.

Remove duplicate log message

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/UpdateEpisodeDetailsTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

As part of the investigation into the Android ANR and the Sentry issue "Unable to check episode file details with a head request", I looked into the UpdateEpisodeDetailsTask. I don't believe there are any issues relating to ANRs but there are some improvements that could be made.
This change makes the following improvements:
- Adds a developer menu option to trigger the worker making it easier to test
- Increases the default timeout from 10 to 20 seconds. This matches iOS and will help with the megaphone calls that seem to take around 10 seconds to complete.
- Removes the retry logic. This isn't in iOS and if the job has failed after 20 seconds there is a small chance that it will succeed on a second or third attempt.
- It stops using `Result.failure()` as from my testing it causes the …

Improve the worker with updates the episode file size and content type

---

CHANGELOG.md
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt

Reverts the changes from #1379  
1. CI is 🟢
1. Run the app
2. ✅ Verify Patron does not appear in the upgrade view
3. ✅ Verify Patron does not appear in the account details view
4. ✅ Verify purchasing Plus works

Disables the patron feature

---

base.gradle
dependencies.gradle
modules/services/sharedtest/build.gradle

This updates leak canary to use the latest version, which addresses a bug that was preventing me from using it. 
In addition, I am adding a commented out `debugProdImplementation` declaration just to give a hint about needing that if you're doing debugProd builds since I lost about 10 minute trying to figure out why Leak Canary wasn't working for me.
Lastly, this limits some test dependencies to only show up in tests. Leak Canary was seeing these classes and not running by default because those classes led it to believe that my debug app build actually a running test. This avoids that problem. FWIW, I don't think this would have been a release issue for us at all since proguard would have presumably stripped these classes out anyway on release builds.
1. Uncomment the lead canary …

Update leak canary

---

CHANGELOG.md
base.gradle
dependencies.gradle
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
modules/services/sharedtest/build.gradle
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectHelper.kt

This clears the multiselect listener when destroying the UpNextFragment to avoid retaining a reference to the Fragment.
> **Note**
> This PR builds on #1393. Please merge that PR before this one.
1. Enable Leak Canary
2. Open and close the up next queue from the miniplayer
3. Observe that there is no memory leak
4. Generally smoke test the up next queue screens both from the miniplayer and the full screen player to check for regressions.
| --- | --- |
| <video src="https://github.com/Automattic/pocket-casts-android/assets/4656348/4e568369-8842-49e0-9c1d-a92e49a49995"/> | <video src="https://github.com/Automattic/pocket-casts-android/assets/4656348/4ab21c3e-c577-47f3-9618-5e398737e26d"/> |

Clear multiselect listener when destroying UpNextFragment to avoid memory leak

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/DateTypeConverter.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateShowNotesTask.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/log/LogBuffer.kt

After doing some debugging with the Background Task Inspector, I noticed that when you download multiple episodes at once, the show notes tasks run in parallel. A single queue that caches the show notes seems to be a better approach. If you download multiple episodes from the same podcast the show notes will be cached with the first call, before the same file would be downloaded multiple times until the cache was populated. 
This PR also stops some reports to Sentry, I will comment on them inline.
1. Add the "package:mine  UpdateShowNotesTask"
2. Subscribe to some podcasts
3. Go to a podcast page
4. Long press an episode
5. Press the toolbar overflow menu and select all
6. Tap download in the toolbar
7. ✅ Verify after the first "Worker completed" line, the time taken is much shorter …

Queue show notes downloading

---

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt

When the search page was opened and there was search history, the history was constantly loaded. This was due to the load being in the Compose render loop. I believe the correct approach is to use a `LaunchedEffect` but it would be good to confirm that. The fix only loads the history once when opening the search page. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/1396
1. Open `SearchHistoryViewModel.kt`
2. Go to [line 59](https://github.com/Automattic/pocket-casts-android/blob/93013f4bbd564dacc23dfdbb1a3a0e79302ab0c6/modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModel.kt#L59C5-L59C5)
3. Add `LogBuffer.i("🚨","loadSearchHistory")`
4. Run the app
5. Go to Discover > Tap Search
7. Make sure you have a search …

Stop the search history loading infinitely

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt

There are three places where we have been creating new UpNextFragments:
1. Each time the up next button is tapped on the mini player
2. Each time the up next button is tapped on the full-screen player
3. The full screen player also creates another instance that it uses for when the user swipes up from the bottom of the screen.
This PR removes `#2` and instead has tapping on that up next button just expand the UpNextFragment that already exists and is used when the user swipes up from the bottom of the full screen player.
Ideally, I would like to get rid of `#1` as well, but that seems less straightforward, so this PR is just tackling the simple case.
This because we are storing some state around multi-selection, reducing the number of `UpNextFragment`s that we're creating should help …

Avoid creating new UpNextFragment when tapping up next button on full screen player

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt

This reverts the change in #1395 because it introduces an issue where the bottom sheet will not be opened if from the full screen player you tap the up next button before doing any swipe motions with the bottom sheet. Basically, the bottom sheet doesn't get laid out until it is swiped, and until it is laid out, you cannot programmatically open it (see [Google issue tracker](https://issuetracker.google.com/issues/37090839#c18)).
Because this PR is targeting a release branch, I'm keeping this as a simple revert instead of trying to fix the issue because the fix does not seem super-straightforward.
1. Open the full screen player
2. Do NOT swipe the screen to open the up next queue
3. Tap the up next button on the full screen player to open the up next queue
4. ✅ Observe that the up next …

Revert "Avoid creating new UpNextFragment when tapping up next button"

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt

Have the `PlayerContainerFragment` initiate the addition/removal of the multiSelectHelper's listener as the UpNextFragment is expanded/contracted. This should help make sure that the UpNextFragment on the full screen player always has the right listener attached, regardless of whether a different instance of `UpNextFragment` gets created and destroyed in the meantime.
This avoids the problem where multiselection would not work after swiping up to open the up next screen on the full screen player, if the up next screen had been viewed already by tapping the up next button on either the full screen player or the miniplayer. See the description of #1395 for some more discussion about this.
Note that this PR also contains the changes from #1404 reverting the removal of the creation of new …

Improve multiselect listener handling

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectHelper.kt

This fixes leaks on returning from views where a multi-select toolbar is added at the time when the view is created, along with setting up of multi-select listener and snack bar view anchors.
Multi-select listener and snack bar view anchors are cleaned up on view destroy. 
Test for the below fragments:
`FilterEpisodeListFragment`
`PodcastFragment`
`ProfileEpisodeListFragment`
`CloudFilesFragment`
- With the leak canary enabled, open the fragment screen
- Tap the toolbar back button
- Wait a while 
- Notice that notification doesn't appear due to multi-select

Cleanup multiselect listener and snackbar anchor view

---

wear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/WatchListScreenViewModelTest.kt

Added Unit tests for the WatchListScreenViewmodel
Fixes #

Added WatchListScreenViewModel Unit Tests

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt

This clears reference to `PodcastFragment.itemTouchHelper` when `PodcastFragment` is destroyed.
1. With leak canary enabled,  go to the podcast tab
3. With podcast details open, go to the filters tab and open a filter's episode list
4. Notice that leak is not found
1. Continue from above
2. Go back to the podcast tab -> podcast details tab
3. Perform a few actions from swipe gestures on the podcast episode rows
4. Notice that they work as before
Fixes this leak:

Clear reference to item touch helper in podcast fragment

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/MessageView.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoBookmarksView.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/PlusUpsellViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkUpsellViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/NoBookmarkViewHolder.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/HorizontalLogoText.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt

This updates upsell view to display content based on the tier passed to it. It also updates the upgrade button title to display text based on free trial info. 
Part of https://github.com/Automattic/pocket-casts-android/issues/1307
Prerequisites:
- Feature flag enabled for Patron and Bookmarks
1. Open the app without login
2. Go to bookmarks upsell view
3. ✅ Notice that upsell view is shown for Patron
4. ✅ Notice that upgrade button title is set to "Upgrade to Patron"
I also tested for `Plus`, and included the screenshot. You may skip it as it will be updated based on the Feature tier in the following PR where it will need to be tested again.
Plus | Patron
-----|---

Bookmarks - Update upsell view based on tier

---

base.gradle

This disables Sentry Timber integration temporarily. 
Slack ref: p1695799385962079/1695652459.530499-slack-C028JAG44VD
> **Warning**
> Targets 7.48
1. Add `Timber.e(...)` statement in `SettingsFragmentPage`
```
AboutRow(onClick = {
Timber.e("test", "test disable timber")
openFragment(AboutFragment())
})
```
3. Open `About` page
4. Make sure that the log is not captured in `Sentry`.

Disable Sentry Timber integration temporarily

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

The playback manager `playNextInQueue` method works differently on iOS and Android. On iOS when you ask to play the next episode in the queue, it removes the currently playing episode. But Android puts the current playing episode back on the Up Next queue. It makes more sense to me that the episode is removed from the queue or if you keep saying next episode it will just switch between the two episodes.
Fixes https://github.com/Automattic/pocket-casts-android/issues/1421
1. Add multiple episodes to your Up Next queue
2. Play the current episode
3. Open the full-screen player
4. Long press the skip forward button
5. Tap "Next episode"
6. Open the Up Next
7. ✅ The currently playing episode should of been removed and not put on the Up Next queue …

Remove the playing episode when playing the next in queue

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/BetaFeaturesViewModel.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/ReleaseVersion.kt
modules/services/featureflag/src/test/java/au/com/shiftyjelly/pocketcasts/featureflag/FeatureTest.kt
modules/services/featureflag/src/test/java/au/com/shiftyjelly/pocketcasts/featureflag/ReleaseVersionTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

This cherry picks feature availability changes from #1332. 
1. Make sure that tests are run and CI is green
2. Head over to PR #1419 to test the changes for the bookmarks feature.
1. Make sure that PR #1419 is approved
2. Remove `not ready for merge` label
3. Merge the PR.

Bookmarks: Use feature availablity checks

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/UserEpisodeViewHolder.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFileBottomSheet.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/component/FileStatusIconsView.kt

Part of https://github.com/Automattic/pocket-casts-android/issues/1307
This updates bookmark icon color on episode rows to match the Play button color. 
- Podcast episodes - uses podcast tint color
- Filter episodes - uses playlist color
- Others (Files,  Listening History, Starred, Downloads) - uses `primary_icon_01`
1. Add bookmarks to 
- Podcast episode
- Subscribed podcast episode and add it to a filter
- User file
2. Notice that the bookmark icon is correctly shown on the episode rows with appropriate color
Podcast Episode | User Episode Light Theme | User Episode Rose Theme
----|---|---
Filter Episode 
|-------|

Bookmarks - Update icon color

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt

This is just removing the firebase remote feature flag default to go along with the removal of the feature flag in https://github.com/Automattic/pocket-casts-android/pull/1086.
If CI is happy, I think we're good.

Remove no-longer-used default for search improvements feature flag

---

modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/FirebaseRemoteFeatureProvider.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt

This enables in-app review. It can be turned off using Firebase remote config for the key `in_app_review_enabled`.
> **Warning**
> Targets 7.49
- Test that the in-app review dialog is shown for the testing steps in https://github.com/Automattic/pocket-casts-android/pull/1305
- Turn off the feature in the Firebase remote config for the key `in_app_review_enabled` and publish changes
- Search for `setMinimumFetchIntervalInSeconds(...)` in the code and set to 5s
- Add a `LogBuffer.i(...)` just before line 94 in `StatsViewModel` to print value for `featureFlag.isEnabled(Feature.IN_APP_REVIEW_ENABLED)`
- Install release build
- Open `Profile` -> `Stats`
- Open `Profile` -> `Settings` -> `Help & feedback` -> `Logs` 
- ✅ Notice that the value is `false` for …

Enable in app review

---

CHANGELOG.md
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/FirebaseRemoteFeatureProvider.kt
modules/services/localization/src/main/res/values-en-rGB/strings.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt

> **Warning**
> Targets 7.49
Enables the Patron feature flag and updates the cloud storage limit to 100. 
Right now the cloud storage limit is a static change since this is targeting the frozen branch, but we should update it to a remote one soon.
1. Run the app
2. ✅ Verify Patron appears in the upgrade view
3. ✅ Verify the Patron storage limit is 100 GB
4. ✅ Verify Patron appears in the account details view
5. ✅ Verify purchasing Patron unlocks it and the new app icons

Enables the Patron feature flag

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/NotesViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt

This change addresses some issues loading show notes in the full-screen player. 
One issue fixed is when the show notes were being loaded if the user was offline and the cache wanted to check the server for a new version it would throw an exception and never load the cached version. 
Before the fix:
https://github.com/Automattic/pocket-casts-android/assets/308331/6da96cdc-d280-4ca9-a039-8593b247cf46
Another possible issue that I wasn't able to repeat is that if the playing episode changed quickly it might be possible the wrong show notes could be displayed. The view model would start an Rx flow to update the show notes but not cancel the previous flow. I have rewritten this in Coroutines and cancelled the previous job.
There is still an issue I would like to resolve but I will leave for …

Fixing show notes loading issue

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/DefaultReleaseFeatureProvider.kt

This is removing the no-longer-needed local feature flag for showing the ratings flag since it is no longer being used.
Verify that when viewing the expanded details for a podcast you still see the rating for the podcast.

Remove feature flag for showing ratings

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/LargePageTitle.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderChooserPage.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditPodcastsPage.kt

This is just a small housekeeping change. Before this change the `LargePageTitle` composable was in the `...compose.compasables` package. This PR moves that file to the `...composables` package with the other compose components.
If CI is happy we should be good.

Move LargePageTitle composable to same package as other composables

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt

I noticed during a release build the following warning. 
```
w: [ksp] /Users/philip/git_automattic/pocket-casts-android/modules/services/model/src/main/java/
au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt:123: The query returns some columns 
[published_date, episode_description, ..., upload_task_id] which are not used by 
au.com.shiftyjelly.pocketcasts.models.entity.Bookmark. You can use @ColumnInfo annotation on the 
fields to specify the mapping. You can annotate the method with 
@RewriteQueriesToDropUnusedColumns to direct Room to rewrite your query to avoid fetching unused 
columns.  You can suppress this warning by annotating the method with 
@SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: uuid, 
podcast_uuid, ... , has_custom_image, …
```

Fix bookmark Room warning

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/StarRatingView.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastRatingsViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/ratings/RatingsManagerImpl.kt

As discussed internally, this updates our rating view so that it shows no stars with "No ratings" text when there are no ratings (internal ref: pdeCcb-3ic-p2#comment-2707).
1. Go to a podcast that does not have any ratings (i.e., The Big Dip on the Trending section of Discover)
2. If necessary, expand the podcast details so you can see the rating
3. Observe that the rating shows 5 empty stars and the text "No ratings"

Show no ratings text when no ratings

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/AutoPlayHeader.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt

This refactors `What's new` dialog to be independent of the feature and moves display logic to the view model so that we can reuse the code for `What's new for bookmarks` in a future PR.
1. Fresh install the app 
2. Increment `Settings.WHATS_NEW_VERSION_CODE`
3. Re-install the app
4. Make sure that What's new for AutoPlay is shown and is same as before
Before | After
----|----

Refactor what's new 

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt

The analytic event `pcandroid_filter_multi_select_exited` was getting triggered even when you didn't use the filter multi-select. This change fixes that. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/1380
2. Open any filter
3. Change tabs
4. ✅ Verify you don't see 🔵 Tracked: filter_multi_select_exited ... in the logs
5. Go back to the filter tab
6. ✅ Verify you don't see 🔵 Tracked: filter_multi_select_exited ... in the logs
7. Tap back in the toolbar to go back to the list of filters
8. ✅ Verify you don't see 🔵 Tracked: filter_multi_select_exited ... in the logs
9. Open the filter
10. Close the app
11. ✅ Verify you don't see 🔵 Tracked: filter_multi_select_exited ... in the logs
12. Long press on an episode to go into multi-select mode
13. ✅ Verify you …

Fix the filter page multi-select analytic

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/to/ChapterTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/BindingAdapters.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ChapterProgressCircle.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout-land/adapter_player_header.xml
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt

The next chapter on the full-screen player has a progress circle around it. This was broken recently when I upgraded the chapters tab to Compose. This change fixes that and cleans up some of the chapter code.
Fixes https://github.com/Automattic/pocket-casts-android/issues/1424
1. Play a Podcast with chapters (for example [Upgrade](https://pca.st/upgrade))
2. Advance within the chapter
3. ✅ Verify the full screen player next chapter button progress is working
https://github.com/Automattic/pocket-casts-android/assets/308331/c768e980-d675-418d-94a5-3a817f6e1ee9

Fix chapter progress circle

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt
modules/services/localization/src/main/res/values/strings.xml

This PR adds a Toast message prompting the user to connect to the internet if they try to submit a rating without an internet connection.
1. Make sure the Give Ratings feature toggle is turned on
2. Go to a podcast and tap on the ratings stars
3. Turn on airplane mode
4. Tap "Submit"
5. ✅  Observe that you are left on the give ratings screen and a toast is displayed asking you to connect to the internet
6. Turn off airplane mode
7. Tap "Submit"
8. ✅ Observe that the ratings screen is closed and a placeholder toast message is displayed noting that rating submission has not been implemented yet

Give Ratings: Prompt user to connect to internet when submitting rating

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt
modules/services/localization/src/main/res/values/strings.xml

If a user taps on a podcast's rating, this PR routes the user to the onboarding flow and presents a toast informing them that they must log in to leave a rating.
1. Make sure the rating feature flag is enabled
2. Make sure you're logged out of the app
3. Tap on the star rating of a podcast
4.  ✅ Observe that you are taken to the onboarding flow and presented with a toast informing you that you need to log in
5. Log into the app
6. Tap on the star rating of a podcast
7. ✅  Observe that you are taken to the give rating screen

Require users log in before leaving a rating

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingScreen.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/SwipeableStars.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt

This adds a swipeable star component for giving ratings
1. Open up a podcst with ratings
2. Tap on the rating to open up the Give ratings view
3. ✅ Tapping on a star animates to that number of stars being filled (no half values). You can tap on the left side of the first star to select 0 stars.
4. ✅ Dragging over the stars with your finger will update the stars based on where you drag (it should reflect exactly where your finger is and not animate to your finger's location), and when you release your finger, the filled star state will animate to the nearest half-star.
> **Warning**
> This component is NOT accessible currently. I will address that in a follow-up PR.
https://github.com/Automattic/pocket-casts-android/assets/4656348/645c4a0d-db21-4df5-b7e6-1da5d10e844d

Add component for tapping and swiping on stars

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/whatsnew/WhatsNewViewModelTest.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt

This updates what's new confirm button title and action to show 
If an episode is 
- Selected:  Label: "Try it now", Action: Open Player -> More Menu -> Highlight "Add bookmark"
- Not selected: Label:  "Enable it now",  Action:  Open `Headphone controls` settings
Internal ref: 
p1697115913259019/1697115334.479459-slack-C055BDMU09, 
pdeCcb-25g-p2#comment-2752
1. Install debug build
2. Login with a Plus account
4. Increment `Settings.WHATS_NEW_VERSION_CODE`
5. Reinstall the build
6. ✅ Notice that "What's new" is displayed with "Try it now" button
7. Tap on  "Try it now"
8. ✅ Notice that the full-screen player is opened and shelf bottom sheet is shown highlighting "Add bookmark" item
9. Clear up next queue (or login with Plus account having no upnext queue)
10. Increment …

Bookmarks - What's new confirm button action

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/utils/Util.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedNumbersView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopPodcastView.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowOutlinedButton.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Float.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Int.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/StoryTopPodcast.kt

| 📘 Part of: #1463 | 🎨 Designs: lH66LwxxgG8btQ8NrM0ldx-fi-1599_20385 |
|:---:|:---:|
Adds the 2023 visual for the Top Show Story.
**Animations are not part of this task and will be tackled later.**
1. Make sure you're logged in into an account that has a few episodes listened
2. Go to Profile
3. Tap the EOY image
4. Skip to the third story
5. ✅ Check that the story looks good
- Also check that the ordering is as specified in Figma (lH66LwxxgG8btQ8NrM0ldx-fi-1764_3353)
7. Share the story
8. ✅ The story image asset should look good
1. Login with an account having less than 5 listened shows
2. Repeat Test.1 Step 2-4
3. ✅ Notice that images are omitted at places where a show doesn't exist
Pixel 7 (Normal display) | Pixel 7 (Large Display, Long Title) | Less than 5 listened shows
---|----|--- …

Playback 2023 - Top podcast story

---

Gemfile
Gemfile.lock
fastlane/Fastfile

This PR removes deprecated environment variables from the Fastfile:
- An explicit path is now passed to `android_current_branch_is_hotfix` instead of using the `PROJECT_ROOT_FOLDER` env var

Remove deprecated env vars from Fastfile

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/SignInFragment.kt

This is removing some unused code around the creation of the `SignUpFragment`.  This code was originally added before the app was open sourced in commit 0ebec5f60130444e60efb6c90f93c8a88155fa24, and I missed removing this when I removed some of the related code that was unused in https://github.com/Automattic/pocket-casts-android/commit/9f5fa252a9bd68e8dedbce809fa7de587a052a16.
Test the sign in flow to verify there are no issues, including:
* Creating an account with email
* Signing in by email
* Creating an account with Google
* Signing in with Google

Remove unused SignUpFragment code

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryIntroView.kt
modules/services/localization/src/main/res/values/strings.xml

Just removing the translation for the content description of "Pocket Casts Playback" since we don't want that name to get translated.

Remove translation for Pocket Casts Playback

---

CHANGELOG.md
modules/services/repositories/src/main/AndroidManifest.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt

This updates the app so that instead of just presenting a Toast message asking the user to grant permission for exact alarms, we also prompt them with the screen for updating that permission. This is important because I'm seeing on the Android 14 emulator that the permission is not being granted by default and it is not particularly easy to find the place to update this permission for an app.
> **Note**
> In my testing, the permission was getting automatically granted on Android 13 devices, which surprised me (after reading [the developer documentation](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms) I thought the permission would be denied by default on Android 13 as well, but apparently not). That's better for our users though, so I'm not complaining. …

Request exact alarm permission if it is missing

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt

This makes it so that the EOY banner uses the onboarding flow instead of the old AccountActivity sign in screen.
Related to #1499 (but does not entirely fix that issue since we still have `AccountActivity` code in other places).
2. Tap on the EOY banner on the profile screen
3. ✅ Observe that you are taken to the OnboardingFlow sign in screen (easy to tell because this screen has a Google Sign In option whereas the old AccountActivity screen does not provide that option).
4. Sign in
5. ✅ Observe that after sign in you are taken to the EOY stories
6. Exit the EOY stories
7. Tap on the EOY banner again
8. ✅  Observe that you are taken to the EOY stories
https://github.com/Automattic/pocket-casts-android/assets/4656348/3c861f97-a72c-46bd-8272-21658ad00eb7

Direct EOY banner to use onboarding flow

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/CompletionRateCircle.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/EpisodesStartedAndCompleted.kt
modules/services/repositories/build.gradle
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/StoryCompletionRate.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImplTest.kt

| 📘 Part of: #1463 | 🎨 Designs: lH66LwxxgG8btQ8NrM0ldx-fi-1599_20385 |
|:---:|:---:|
Adds the 2023 visual for the Completion Rate Story.
1. Go to `CompletionRateCircle.kt`
2. Enable Preview
3. ✅ Go over all the different percentages
4. You can also play with the numbers to see if the circle updates accordingly
1. Make sure you're logged in to an account that has a few episodes listened
3. Go to Profile
4. Tap the EOY image
5. Skip to the penultimate story
5. ✅ Check that the story looks good compared to the design
6. Share this story
9. ✅ The story image asset should look good
10. Add Plus plan to the account
11. Go to Profile tab and tap refresh now 
12. ✅ Check the story again, it should show a Plus badge
13. Add Patron plan to the account
14. Go to Profile tab and tap refresh now 
15. …

Playback 2023: Completion rate story

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This fixes an issue where the download of an episode that is being streamed could cause playback to jump back a second or so.
When the app downloads an episode that is currently being streamed we usually (but [not always](https://github.com/Automattic/pocket-casts-android/issues/1509)), reset the player. When doing this, the new player was loading the last position of the episode that was saved to the database, which would often be out-of-date by a second or so.
This fixes that by (1) ensuring that we get the current playing position at the last possible moment before resetting the player, (2) updating the database with that playing position, and (3) ensuring that we fetch the latest episode data from the database before restoring the playback position.
It would be nice if we didn't have …

Avoid audio skip back when a streaming episode is downloaded

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/PaidStoryWallView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryButton.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModelTest.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/whatsnew/WhatsNewViewModelTest.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/UpsellButtonTitle.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/Story.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/StoryCompletionRate.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/StoryYearOverYear.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

| 📘 Part of: #1463 | 🎨 Designs: lH66LwxxgG8btQ8NrM0ldx-fi-1599_20385 |
|:---:|:---:|
Adds paid wall view for Plus Upsell story 
1. Make sure you're logged in to an account that has a few episodes listened
2. Go to Profile
3. Tap the EOY image
4. Skip to the 1st Plus story
5. ✅ Notice you see Upsell button with a blurred background
6. ✅ Notice that Upsell button title is shown correctly based on free trial for Plus (this can also be checked in `PaidStoryWallView.kt `previews)
7.  ✅ Notice that story is paused
8. ✅ Notice that tapping on left on this Upsell story should take to the previous free story
9. ✅ Notice that tapping on right on this Upsell story  should take to the epilogue story skipping plus stories in between
10. ✅ Notice that tapping on close button on this Upsell story should …

Playback 2023: Plus Upsell story

---

CHANGELOG.md
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ChangeEmailViewModel.kt

I moved the ```disposables.clear()``` in the ```onCleared()``` viewmodel to the ```doFinally { }``` in the ```changeEmail()``` function. Clear composite disposables in the ```onCleared()``` inflict the http request canceled by the client upon ```ChangeEmailFragment``` destroyed, since the http request already sent and being processed by server with http canceled by client we lost our response and can't update email in the AccountManager. By moving ```disposables.clear()``` to the ```doFinally{}``` we ensure that the http call not canceled when we navigate from the ```ChangeEmailFragment``` and the disposable cleared upon request finished.
Fixes #1511 
1. login with an email address 
2. Go to ```Profile``` -> ```Account```
3. On the ```Pocket Casts Account``` screen, tap ```Change email …
```

Fix change email handling

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/HistoryManager.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImplTest.kt

| 📘 Part of: #1463 |
|:---:|
This PR adds logic for syncing 2022 and 2023 data.
1. Clean install debug build
2. Make sure you're logged in with a plus account that has a few episodes listened to this year and last year
3. Open stories
4. ✅ You should see in logs `End of Year: Downloading listening history for year xxx` for both 2022, 2023
6. Go to the "Year over Year" story
7. Notice you do not see any upsell button
8. Tap next
9. ✅ You should see the completion rate story
Prerequisites
- Enable EoY Year for release build
- License test account 
_(See Test.2 (Optional) if you want to test it on debug build)_
1. Clean install release build
2. Make sure you're logged in to a license account as a free user that has a few episodes listened to this year and last year
3. Open …

Playback 2023: Sync 2022 and 2023 listening history

---

CHANGELOG.md
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This enables bookmarks for entering Patron early access in `7.52` and for full release in `7.53`.
I think it's worth double-checking that our logic is hitting all the right states for the right releases now that we know the release version. Using release builds with the following versions (specified in [versions.properties](https://github.com/Automattic/pocket-casts-android/blob/main/version.properties)), you should see the following behavior for bookmarks:
| App version | Not signed in | Free          | Plus          | Patron    |
| ---| ---- | ----- | ------ | ------|
| `7.52-rc-1`   | Plus upsell   | Plus upsell   | Available     | Available |
| `7.52`        | Patron upsell | Patron upsell | Patron upsell | Available |
| `7.53-rc-1`   | Plus upsell   | Plus upsell   | Available     | …

Enable bookmarks with Patron early access in 7.52

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt

This fixes user episodes getting removed from up next.
Fixes https://github.com/Automattic/pocket-casts-android/issues/356
1. Device 1
1. Add a local file to the up next queue
1. Sync the device with the server
2. Device 2 
1. Log into the same account as Device 1
2. Sync with the server
3. ✅ Observe that the Up Next queue does not have the downloaded episode
4. Sync with the server again
3. Device 1
1. Sync with the server
2. ✅ Observe that the downloaded episode has disappeared from the Up Next queue
https://github.com/Automattic/pocket-casts-android/assets/1405144/64860cdd-95d9-46fd-bdfc-48465f62c1f1

Fix user episodes getting removed from up next

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerSeekBar.kt
modules/features/player/src/main/res/layout/view_playback_seek_bar.xml

Linked Issue : #116 
1. Open any podcast which has video
2. Then check the seek bar
The full screen video player has some features that could be nice to adopt on Android:

progress bar is made white

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/to/ChapterTest.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt

Change convert ```rountToInt()``` in ```au.com.shiftyjelly.pocketcasts.models.to.Chapter.remainingTime``` to ```toInt()``` so that the minutes not rounded up. For example before when we have ```timeMs``` 1 min 39 s in the ```Now Playing``` tab displayed 2 min but in the ```Chapters``` tab displayed 1 min.
Fixes #1505  
1. Play episode [https://pca.st/ap314mdp](https://pca.st/ap314mdp)
2. In the ```Now Playing``` tab check the chapter length
3. In the ```Chapters``` tab check whether the chapter length same with displayed in the ```Now Playing``` tab.

Fix Chapter Length Calculation Mismatch

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListeningTimeView.kt

| 📘 Part of: #1463 |
|:---:|
This increases listened time font size while keeping subtitle close to the title (https://github.com/Automattic/pocket-casts-android/pull/1495#discussion_r1376655773)
Small Display | Large Display
|----|---|
|<img width=200 src="https://github.com/Automattic/pocket-casts-android/assets/1405144/9abf8708-df48-4564-9f77-6f46ed2f93c2"/>|<img width=200 src="https://github.com/Automattic/pocket-casts-android/assets/1405144/3beb4555-5728-4aca-a8d8-1768f2393ef6"/>|
Tablet
|----|
|<img width=500 src="https://github.com/Automattic/pocket-casts-android/assets/1405144/7d2b887c-a219-449b-a3ea-b36a650721c0"/>|

Playback 2023 - Update listened time font size 

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesFragment.kt

This unlocks portrait orientation after stories dismiss
1. Open stories dialog
2. Rotate device
3. Notice that orientation is locked to portrait
4. Dismiss the dialog
5. Rotate device
6. Notice that orientation can be changed

Unlock orientation after stories dismiss

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt

The problem with current navigation system is that if there are two fragment A and B and we are changing fragment from fragment A to fragment B using `navigator.addFragment` function of MainActivity then onDestroy of A is running after onCreate of B which is not expected 
From the above observation i found that
- The `onDestroy` of `UpNextFragment` is nullifying the multiselect listener of `PodcastFragment` when navigating from `UpNextFragment` to `PodcastFragment`.
- when navigating from `PodcastFragment`  to `PodcastFragment`, when `podcastUuid` is different, is also making the multiselect listener as null
Whenever `onRowLongPress` is invoked I am attaching the multiselect listeners again in `PodcastFragment`
Fixes #1507
https://github.com/Automattic/pocket-casts-android/assets/134276544 …

Fixes Multiselect: Does not work in some cases(#1507)

---

Dangerfile
Gemfile.lock

I have noticed that [this backmerge PR](https://github.com/Automattic/pocket-casts-android/pull/1532), marked with the label `releases`, was still getting warnings. In case of marking PRs as part of a release process, Dangermattic should skip most checks.
This was due to a typo with the label name, and this PR fixes it. I used this chance to also update Dangermattic gem to the latest one, containing a couple of fixes.
You can run `danger` yourself on a PR with warnings and check the results:
```ruby
DANGER_GITHUB_API_TOKEN=<github_token> bundle exec danger pr https://github.com/Automattic/pocket-casts-android/pull/1532
```

Dangermattic: fix release label typo

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt

Updated logic to show Playback Prompt (modal bottom sheet) without clashing with Bookmarks what's new:
1. If the What's New is displayed the Playback Prompt will not be
2. If the user dismisses the announcement (maybe later button), the Playback Prompt will be shown if the user is eligible
3. If the user uses the announcements action button (blue button), the Playback prompt will not be shown until the next launch. At which point only the Playback prompt will be displayed
4. If the user opens the Playback Stories without seeing the prompt, the prompt will no longer display on the next launch
5. If the what's new is not displayed, the Playback prompt will show as it did before.
Profile Badge
- Fixes scenario when the badge is shown and the user first taps another tab before tapping the …

Bookmarks + Playback: Add handling for when both the bookmarks what's new and the playback prompt will show

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/utils/Util.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryListenedNumbersView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryLongestEpisodeView.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt

| 📘 Part of: #1463| 🎨 Designs: lH66LwxxgG8btQ8NrM0ldx-fi-1599_20385 |
|:---:|:---:|
Animates the following stories with ability to pause/ resume animation when story is paused/ resumed:
- *Listened time (2nd story)* (reuses [endless scrolling effect](https://github.com/Automattic/pocket-casts-android/commit/e82c7aafc6dd9154e904d50778e6b2914b41f61c) from previous onboarding flow features list)
- *Longest episode (seventh story)* (just animates offset along x and y axis: [core logic](https://github.com/Automattic/pocket-casts-android/commit/574b9b13af51f167f9eeed5786061041fe391b58#diff-5400c9888d444c9189e25cb92c45b455575c5ed5bad4bf8eb78b66a43a74abeaR93-R122))
For "Top one podcast to top five podcast (third to fourth story)", see my Slack note (p1699771341436249-slack-C041BGTFQ5R). 
1. Make …

Playback 2023 - animations

---

CHANGELOG.md
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

| 📘 Part of: #1463| 
|:---:|
This enables Playback 2023.
1. Install release build
2. Make sure you're logged in to an account that has a few episodes listened
3. Go to Profile 
4. Notice you see End of Year card
** I also enabled remote flag for the feature in https://github.com/Automattic/pocket-casts-android/pull/1537/commits/4cdd3e53ab1bd5d51c1d9926a66bbf32a84279cb and added the key to Firebase console.

Enable Playback 2023

---

base.gradle
gradle/libs.versions.toml
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt

This fixes upsell not showing correctly at times on full-screen player screen bookmarks view
Fixes #1519
1. Log in with a Plus account with bookmarks enabled
2. Open the full-screen player and look at the bookmarks tab
3. Sign out of your Plus account
4. Return to the full-screen player and observe that the bookmarks tab shows the upsell view. Collapse and expand the full-screen again to see that upsell is shown. 
https://github.com/Automattic/pocket-casts-android/assets/1405144/5d1f78f1-1273-4087-a23a-983fa1e311a4

Bookmarks - Fix upsell display

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt

This matches iOS query: https://github.com/Automattic/pocket-casts-ios/pull/1213/commits/8aedf1708010448ccd942402a5d9fd0855341483
1. Make sure you're logged in to an account that has a few episodes listened
3. Go to Profile and tap the End of Year card
4. Go to the completion rate story
5. ✅ Your data should appear correctly

Playback 2023 - Update completion rate query

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt

Fixes add bookmark not showing at times.
** This also adds a small delay when playing at a bookmark position when the selected episode is loading or switching from a different one.
1. Install release build from `release/7.51` branch
2. Play an episode and open full-screen player
3. From the bottom shelf, open more option
4. Rearrange a few shelf items
5. Install release build from this branch
6. Play an episode and open full-screen player
7.  From the bottom shelf, open more option
8. ✅ Notice you see the Add bookmark option
1. Continue from above
2. Add a bookmark for the selected episode
3. (Optionally) Archive it
4. Play an episode from another podcast
5. Select the previous episode to which bookmark was added
6. Tap the bookmark play button for the episode
7. ✅ Notice that the …

Bookmarks - Fix add bookmark not showing at times

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt

This updates the call to play a bookmark to use the suspended `playNowSync` function instead of the asynchronous `playNow` function. This helps make sure that the episode is loaded before we update the playback position. 
With this change I don't think we need the manual delay anymore, but let me know what you think @ashiagr since you're more familiar. We could leave the delay in if you think that is needed.
Without this change, I was seeing that playing a bookmark from an archived episode had a race condition where one of three things would occur:
1. The bookmarked episode is loaded and the playback position on the episode is properly set. This is the happy path.
2. The bookmarked episode is loaded, but the playback position is not set. As a result, the episode is played from the …

Use suspend method when playing bookmarks

---

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

This fixes "user bookmark" sync when bookmark feature is disabled. (p1699988968426399-slack-C02A333D8LQ)
If a user bookmark is synced using a build with the feature enabled, then syncing fails on a build where the feature is disabled and gives this error:
```
SyncProcess: Sync failed
com.squareup.moshi.JsonDataException: Expected a name but was BEGIN_OBJECT at path $.result.changes[0].fields
at com.squareup.moshi.i.m(SourceFile:96)
at au.com.shiftyjelly.pocketcasts.servers.sync.update.SyncUpdateResponseParser.m(SourceFile:20)
at au.com.shiftyjelly.pocketcasts.servers.sync.update.SyncUpdateResponseParser.t(SourceFile:50)
at au.com.shiftyjelly.pocketcasts.servers.sync.update.SyncUpdateResponseParser.fromJson(SourceFile:127)
```
This PR skips parsing user bookmark when the feature is …

Bookmarks - Fix user bookmarks sync when feature is disabled

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfTouchCallback.kt

This fixes an occasional crash on moving a shelf item.
Slack discussion: p1700183407328549-slack-C02A333D8LQ
Sentry issue: https://a8c.sentry.io/share/issue/1dea38e7cea647018dbb4235e0e42942/ 
I was able to reproduce it on the latest debug build after a few attempts and noticed this exception was thrown:
1. Open full-screen player
2. From the bottom shelf, tap more menu
3. On the Rearrange actions screen, move action rows a few times (I was able to reproduce after 10-15 attempts)
4. ✅ Notice that there is no crash

Fix occasional crash on moving player shelf item

---

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

This allows incremental sync of bookmarks when the `delete` value is null.
1. Add a breakpoint at line 254 in `SyncUpdateResponseParser.kt`
2. Install debug app from this branch 
3. Login into web staging server and debug app with the same Plus account.
4. Create a bookmark for an episode on the web (it is important that bookmark is created after login into the app to test incremental syncing)
5. Enable debugging for the app
6. Tap Refresh now under Profile in the app
7.  Make sure that breakpoint added at step 1 is hit
8. Resume from debugging
9. Open the episode in the app to which bookmark was added in step 4
10. Switch to bookmarks tab
11. ✅ Notice that the bookmark added at step 4 is displayed

Allow bookmark incremental sync when delete is null

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/GradientPillar.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/PaidStoryWallView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryButton.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/components/StoryText.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryEpilogueView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopFivePodcastsView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryTopListenedCategoriesView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryYearOverYearView.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/ScrollingRow.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/stories/Story.kt

This addresses quick Playback2023 UI feedback (pdeCcb-3NF-p2)
1. Top 5 shows - Replace publisher with total listening time for the show cbb60986662f47e13dcd26c80aaa368309ac6d05
2. Autoplay speed - Update to 7 seconds 9e4ba1db0ae0c3cef2609ac26ea1781ce004f071
3. Total listening time - Removed the “.” at the end of the heading d6b4e8655ca866fbe73b9e4836603a5e9ab7bb2d
4. Top 4 categories - 
- Add a question mark “?” at the end of the heading d6b4e8655ca866fbe73b9e4836603a5e9ab7bb2d
- Font Size - Incremented so that they still appear correctly on Tablet bff76bc70d5c1198e8a1d0092b03ff229ff4cd7f
[No changes to Weight(Category Title W500, Category SubTitle W600), Font (DM Sans)]
5. Number of shows & episodes - Distance between each artwork made more even 41d52304ed0c38083c6346bae96247b1fc6add1a …

Playback2023 - UI design feedback

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt

This 
- Updates multi-select listener between full-screen player screen and podcast screen (partially fixes p1699662181239419/1699651627.027039-slack-C028JAG44VD, there might be more cases of shared listener)
- Stops collecting flows in the bookmarks view model when the full-screen player is closed 
- Updates theme when bookmark view is opened from Upnext queue
1. Open a podcast with a few bookmarks
2. From the selected podcast, play an episode with a few bookmarks 
3. Open full-screen player and scroll to the bookmarks view
4. Close full-screen player
5. Go to bookmarks tab on the podcast screen
6. Long press on a bookmark
7.  Tap select all 
8. ✅ Notice that all bookmarks are selected
1. Open the app in light theme mode
2. Add a few episodes to Upnext queue
3. Tap on an episode from …

Bookmarks - fixes

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/endofyear/EndOfYearManagerImpl.kt

This catches the exception that gets thrown when the call to download the listening history fails.
Fixes #1553
> [!IMPORTANT]
> I have this PR targeting `release/7.52`
1. Log into an account with some listening history and make sure EOY is available.
2. Make sure the EOY Stories banner is showing on the Profile tab. You might need to listen to 5 minutes of a podcast.
3. Turn on airplane mode
4. Tap the Stories banner on the Profile tab
5. Verify that the stories load (i.e., there is not a crash), and go through each story making sure all the stories have data.

Catch exception if Stories call to load history fails

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt

This fixes podcast edit bookmark action (p1699881209505099/1699879199.445519-slack-C02A333D8LQ)
2. Go to a podcast having bookmarks
3. Go to bookmarks tap
4. Long press a bookmark
5. Tap the edit icon on the multi-select toolbar
6. ✅  Notice that Change bookmark title screen is shown
7. Complete edit action
8. ✅ Notice that bookmark title has been changed

Fix podcast screen edit bookmark action

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/PodcastCacheServerManagerImpl.kt

This has the app check the server for updated episode URLs before playing an episode. This avoids a problem where patreon podcasts would fail to play because the app had an expired URL. This was particularly problematic on the Automotive app because on the Automotive app there was no way to update the URL for an existing episode (refresh would just pull in new episodes). This could also be a problem on the phone app though as the only way to update the URL for an existing episode is to go to the screen for the podcast, which automatically updates all the episodes automatically (but this isn't made apparent to the user in any way).
I initially thought about only getting the URL after we see playback fails, but iOS is fetching all the episode data for a podcast before playback starts …

Fetch latest episode url before playing episode

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt

This PR builds on top of https://github.com/Automattic/pocket-casts-android/pull/1557 and adds checks so that the app doesn't enter into an illegal state. It seems to happen when the player is opened and the childFragmentManager is accessed to get the bookmarks fragment from the `PlayerContainerFragment` before it is attached to the parent.
I was unable to reproduce the issue but I see at least one report [in Sentry](https://a8c.sentry.io/share/issue/651e51c99c89431d92181a0d491de351/).

Handle an illegal state exception 

---

CHANGELOG.md
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/DateTypeConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/SafeDateTypeConverterTest.kt

This PR is adding a type converter that never returns null to address a crash we've seen a sudden increase in [on Sentry](https://a8c.sentry.io/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=IllegalStateException%3A+Expected+non-null+java.util.Date%2C+but+it+was+null.&project=6711064&query=issue%3APOCKET-CASTS-ANDROID-WJ2&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29).
The root of the crash seems to be that a null `Long` is being retrieved from the `podcast_episodes` database table. This should never happen because that column [is not allowed to be null](https://github.com/Automattic/pocket-casts-android/blob/release/7.53/modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt#L26). This …

Use type converter that cannot return null for date to avoid crash

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt

This changes the Bookmarks tab position so that it is shown after the Chapters tab.
(Internal Ref: p1701267305022489/1701225559.781909-slack-C055BDMU095)
2. Play a podcast with chapters like https://pca.st/kfyb6kvc
3. Open the full screen player
4. ✅ Verify the order of the tabs is: Now Playing, Details, Chapters, Bookmarks

Change bookmarks tab order

---

wear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/LoggingInScreenViewModelTest.kt

This PR adds Unit tests for the LoggingInScreenViewmodel. 
Fixes # 
N/A

Adds LoggingInScreenViewModel Unit tests

---

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/utils/Util.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryCompletionRateView.kt
modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/views/stories/StoryEpilogueView.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt

| 📘 Part of: #1463  |
|:---:|
This updates `playing_status` value for completed episodes in the completed episodes query. The values comes as `3` in the json but stored as `2` in the db ([source](https://github.com/Automattic/pocket-casts-android/blob/fa7189474f5a0670d0db475448ddea0ec10a9101/modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodePlayingStatus.kt#L19-L21)).
Additionally, it adds a blurred background for the completion rate story.
> [!WARNING]  
> Targets 7.53
1. Fresh install the app 
2. Log in to a Plus account that has a few episodes listened more than 90% of duration + a few episodes having EpisodePlayingStatus as completed
3. Go to Profile
4. Tap the EOY image
5. Skip to the Completion Rate story
5. ✅ Check that the story completion rate …

Playback2023: Fix completed episodes query 

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

Currently the app crashes if any errors are thrown when we refresh podcast data in the background using `PodcastManagerImpl::refreshPodcastInBackground`. This is why #1572 causes a crash. I don't think there's any reason we would ever want an error when fetching podcasts in the background to crash the app, so this PR catches any exception thrown in that method, and logs the exceptions as errors (which means they'll still get sent to Sentry and show up [like this](https://a8c.sentry.io/discover/pocket-casts-android:92da7c0d37a24705b4862d4dcec4ca4d/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=IllegalStateException%3A+Expected+non-null+java.util.Date%2C+but+it+was+null.&project=6711064&query=issue%3APOCKET-CASTS-ANDROID-R3M&sort=-timestamp&statsPeriod=9 …

Catch exceptions thrown when refreshing podcasts in the background

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt

> [!Warning]
> Targets 7.53
Part of #1572
This adds `@Transaction` annotation for large result select episodes queries.
This is a sample error seen in logs when we were able to reproduce the error:
```
Failed to read row 638, column 0 from a window with 638 rows, 35 columns
E  Failed to read row 638, column 1 from a window with 638 rows, 35 columns
E  Failed to read row 638, column 2 from a window with 638 rows, 35 columns
E  Crash: Fatal crash.
E  java.lang.IllegalStateException: Expected non-null java.util.Date, but it was null.
E  	at au.com.shiftyjelly.pocketcasts.models.db.dao.EpisodeDao_Impl$56.call(EpisodeDao_Impl.java:9496)
E  	at au.com.shiftyjelly.pocketcasts.models.db.dao.EpisodeDao_Impl$56.call(EpisodeDao_Impl.java:9432)
E  	at …
```

Add transaction annotation for large result select episodes queries

---

CHANGELOG.md
modules/features/discover/src/main/res/layout/row_carousel_list.xml

Fix the discover search bar text overflow when the device has a high display zoom set.
Fixes #1464
1. Set device display zoom to a high level
2. Navigate to the Discover tab
3. Check that the "Search podcasts or add RSS URL" text in the top bar has an ellipses instead of wrapping around.

Fix discover search bar text at high device zoom

---

CHANGELOG.md
modules/features/discover/src/main/res/layout/row_carousel_list.xml

Adapts the discover search bar text to the device zoom when the device has a high display zoom set.
1. Set device display zoom to a high level
2. Navigate to the Discover tab
3. Check that the "Search podcasts or add RSS URL" text in the top bar auto-resizes to the device scale

Add autoSizeTextType to discover search bar

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/NotesViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/79.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/UpdateShowNotesTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ImageUrlUpdate.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesManager.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesManagerTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/podcast/ShowNotesResponse.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This adds support for displaying the episode-specific artwork that is sometimes included in a podcast's RSS feed. This information is available to the app from the call to retrieve the show notes that was [implemented already](https://github.com/Automattic/pocket-casts-android/pull/1083).
Fixes #528
Look at why the podcast artwork briefly displays before the episode artwork on the episode screen
3. Open up the podcast screen for "Darknet Diaries"
4. Open the episode details page for an episode
5. ✅  Observe that episode-specific  artwork is displayed instead of the podcast artwork (the first time you do this the podcast artwork may show for a split-second before the episode artwork url is available—that appears to only happen the one time though, visiting other …

Display artwork from podcast feed via show notes endpoint on full-screen player and episodes screens

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt

This is a follow-up to https://github.com/Automattic/pocket-casts-android/pull/1316. That PR contained quite a few changes, and we found other ways to address the ANRs and the worst multi-select issues, so we didn't move forward with it. We still had quite a few multi-select issues though. In particular, in my testing I observed that multi-select state was getting shared (which would cause things like the toolbar displaying the wrong number of selected items, and other multiselect bugs).
I initially tried porting over a few of the changes from #1316, but I found that they were introducing regressions. It turned out that just simply making the `MultiSelectEpisodesHelper` a singleton solved most of the multi-select issues I see.
This _almost_ fixes …

Make MultiSelectEpisodesHelper not a singleton

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt

This PR makes a small improvement to where a user's episode is marked as played (as suggested [here](https://github.com/Automattic/pocket-casts-android/pull/1548#pullrequestreview-1749794111)).
Same as
- #1248

Add markAsPlayed in UserEpisodeManager

---

modules/services/images/src/main/res/color/color_primary_container_60.xml
modules/services/images/src/main/res/drawable/widget_background.xml

This decreases widget background alpha value.

Decrease widget background alpha

---

base.gradle
gradle/libs.versions.toml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

Removing some unused episode query methods. Doing this as a follow-up to https://github.com/Automattic/pocket-casts-android/pull/1589 so that we don't have risky methods that aren't using transactions laying around.
If CI is green, this should be good.

Remove unused episode query methods

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This PR addresses a problem with the skip-forward and skip-back functionality on pixel buds, and fixes #1578.=
I think this is only an issue if the earbuds are [set up to use Google Assistant](https://support.google.com/assistant/answer/9027902?hl=en). At least that's what I've observed when using my usb-c pixel buds which can be used without Google Assistant integration because I only see the issue when the Google Assistant integration is enabled).
I don't have Bluetooth pixel buds to test this, but we have quite a few users reporting this issue with the Bluetooth pixel buds as well. This issue does not appear to occur with regular Bluetooth headphones/speakers in my testing.
I believe this issue is caused by the fact that many of our playback functions in the playback manager launch …

Avoid race conditions with media command events

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/BookmarkDaoTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
app/src/test/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModelTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This makes adjustments to the `Tap to view` action on the `Bookmark added` notification to 
- display the bookmarks on the `Episode` screen instead of the player screen if the `PodcastEpisode` for which the bookmark was added  is not currently playing
- display the bookmarks for the `UserEpisode` if the `UserEpisode` for which the bookmark was added is not currently playing
- display bookmark not found message if the bookmark is deleted
Part of: https://github.com/Automattic/pocket-casts-android/issues/1595
1. Go to `Profile` -> `Settings` -> `Headphone controls`
2. Tap `Next action`
3. Select `Add bookmark`
4. Play any podcast episode
5. Minimize the app
6. Double-tap the headphone to add a bookmark
7. Notice that `Bookmark added` notification is displayed
8. Tap on the notification to …

Bookmarks - Update Tap to view bookmark notification action

---

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/MainActivity.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/extensions/ScalingLazyColumnDefaults.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/authentication/AuthenticationNavGraph.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/component/NowPlayingPager.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeScreenFlow.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/HelpScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsRoutes.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/UrlScreen.kt

This PR is incorporating the `ScalingLazyColumnState.Factory` that was added relatively recently to [horologist](https://github.com/google/horologist). We're adding this because Google has rejected our latest submissions because some of the chips at the top and bottom of the screen cannot be scrolled fully onto the screen.
I cannot recreate this with any of the "top" chips on a scrollable screen, but I can recreate the issue on the bottom chips on some screens. Using `responsive` avoids the issue in every place I've observed it.
Although I haven't observed the issue at the top of the screen at all in my testing, Google's rejections included a screenshot that appeared near the top of the screen, so for any screen with large elements/chips at the top, I am making sure that the default of …

Prevent wear chips from getting cut off by round watch edges

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
modules/features/settings/src/main/res/layout/fragment_settings_appearance.xml
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/images/src/main/res/color/color_primary_container_40.xml
modules/services/images/src/main/res/drawable/widget_background.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt
modules/services/repositories/src/main/res/layout/widget.xml
modules/services/repositories/src/main/res/layout/widget_default_theme.xml
modules/services/repositories/src/main/res/layout/widget_dynamic_colors_theme.xml
modules/services/repositories/src/main/res/values-v31/styles.xml
modules/services/repositories/src/main/res/values/styles.xml
modules/services/repositories/src/main/res/xml/widget.xml

This adds a setting to enable widget dynamic colors for Android 12 and above. It is off by default.
2. Long press the app icon
3. Tap Widgets
4. Drag the widget to the home screen
5. ✅ Notice that the widget colors remain the same as before
6. Open the app
7. Go to `Profile` -> `Settings` -> `Appearance`
8. Scroll down
9. ✅ Notice that you see a setting to enable widget dynamic colors
10. Toggle the switch switch to enable widget dynamic colors
11. ✅ Notice that you see in logs `Tracked: settings_appearance_use_dynamic_colors_widget_toggled, Properties: {"enabled":true,`
12. Return to the home screen where the widget was added
13. ✅ Notice that the widget has dynamic colors based on the wallpaper
14. ✅ Notice that play, skip actions work as before
15. Go back to …

Add setting to enable widget dynamic colors 

---

CHANGELOG.md
app/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffectsDataTest.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffects.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PlaybackEffectsData.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt

This PR fixes an issue where the effects UI on the watch was not updating even though the values were being updated and taking effect. This was because the UI was not detecting that there were changes to the underlying effects.
We might want to add proper equals handling to the `PlaybackEffects` class, but because that could have wide-ranging and hard to anticipate consequences, I instead opted to create a related data class that gives us the behavior we want because that seemed like a simpler and much safer approach.
> [!NOTE]
> I have this PR targeting the `release/7.54` branch.
1. From the watch's now playing screen, tap on the playback effects button
2. Change each of the effects
3. ✅ Confirm that the UI updates to reflect the change
4. ✅ Confirm that if you exit the playback effects …

Fix wear update effects UI not updating

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

This removes the `getPodcastEpisodesListOrderBy` method because I noticed it wasn't being used.
If CI is green we should be good.

Remove unused getPodcastEpisodesListOrderBy method

---

CHANGELOG.md
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/UserEpisodeImage.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/DeleteState.kt
wear/build.gradle.kts
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/episode/EpisodeViewModel.kt

This PR improves the handling of user files on the watch in a few ways:
1. When the file does not have any associated image/color, the episode details screen will not crash. Instead, a white color will be used.
2. When a downloaded episode is removed, we will call `CloudDeleteHelper::deleteEpisode`, which handles the deletion of episodes that are in various different states (uploaded, device only, or both) appropriately.
3. We added a fallback image for when a user episode image URL fails to load
Fixes #1473
1. Install the app onto your watch and log in
4. From the web or another device, add two files to the cloud for the account you're using on your watch
5. Sync your watch
6. Verify that both files have appeared on your watch
7. Tap on each file to open the episode screen for them
8. …

Improve wear handling of user files

---

base.gradle
gradle/libs.versions.toml

Adding the compose-bom to help make our upgrades easier. When the compose BOM was created, Google [noted](https://android-developers.googleblog.com/2022/10/whats-new-in-jetpack-compose.html#:~:text=A%20BOM%20is%20a%20Maven%20module%20that%20declares%20a%20set%20of%20libraries%20with%20their%20versions.%20It%20will%20greatly%20simplify%20the%20way%20you%20define%20Compose%20library%20versions%20in%20your%20Gradle%20dependencies%20block%2C%20especially%20now%20that%20we%20moved%20the%20various%20Jetpack%20Compose%20libraries%20to%20independent%20versioning%20schemes) that it would "greatly simplify the way you define Compose library versions in your Gradle dependencies block, especially now that we [moved the various Jetpack Compose libraries to independent versioning …

Using compose-bom

---

CHANGELOG.md
modules/features/player/src/main/res/layout/fragment_upnext.xml

This PR improves accessibility by adding a 'Close' label description to an unlabeled button
Fixes #1657 
1. Start TalkBack: https://support.google.com/accessibility/android/answer/6007100?hl=en
2. Open Pocket Casts.
3. Queue some episodes to play next
4. On the player near the bottom of the screen, just above the tabs, select the Up Next button near the right edge of the screen to open the Up Next screen
**Expected behavior**: When you tap on the X button the `TalkBack` must say `Close button`
| Up Next Queue | Up Next Screen |
| <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/08e5e1e1-4397-4986-9f34-91c4ecf0e251" height="400"> | <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/4fcd805e-280a-48fa-8cfd-c8aaa919a9c7 …

Set label for close button in up next screen

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/images/CoilManager.kt

> [!WARNING]  
> Targets release/7.54
This prevents large bitmap crash while loading bitmap using Coil by [restricting image size](https://rb.gy/0zlgiu). It can be further improved by adding an interceptor that handles large bitmaps appropriately but I do not want to bring too many changes to a release branch freezing tomorrow.
Relevant Sentry report: https://a8c.sentry.io/share/issue/6d0da9c8e4764e39b3beca1368381184/
The problem it seems is due to setting [Size.ORIGINAL](https://github.com/Automattic/pocket-casts-android/blob/main/modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt#L440) while loading episode artwork from URL which may return a large image. `Size.ORIGINAL` uses unrestricted image dimension, `Size(Dimension.Undefined, …

Fix large bitmap crash

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastEffectsViewModel.kt
modules/features/taskerplugin/build.gradle.kts
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Double.kt
modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/DoubleTest.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt

- We noticed an issue where an incorrect value was displayed in the media notification after changing the playback speed value and restarting the app. This issue was caused by not rounding the speed value. As a result, the default value (1x) was always returned instead of the correct one. This PR addresses this problem by implementing rounding for the speed value.
- Also this PR extracts the rounding logic to an extension function and replace it in order to avoid code duplication
Fixes #1648
3. Tap the effects option on the bottom shelf
4. Change playback speed
5. ✅ Notice that media notification displays the correct playback speed
6. Force stop the app
7. Reopen the app
8. Play the last episode. _You don't need to wait for the episode actual …

Fix Incorrect playback speed shown on the media notification

---

modules/features/player/src/main/res/layout/adapter_player_header.xml

As part of this PR: https://github.com/Automattic/pocket-casts-android/pull/1665 we added a `Scale.FIT` while loading episode artwork to prevent large bitmap OOM error. 
`coil.size.Scale.FIT`
> Fit the image to the view so that both dimensions (width and height) of the image will be equal to or less than the corresponding dimension of the view.
With the `Scale.FIT`, the width and height of the image should be equal to or less than the corresponding dimension of the view. However, the image spreads beyond the view width.
This is also reported here:
https://pocketcastsbeta.slack.com/archives/C013F9S9C2W/p1704702825434209 
To fix this, I added an aspect ratio constraint for the image view. I think it is safe to include this constraint as it is also applied to the landscape layout loading the …

Player: Episode artwork - add image ratio constraint

---

.buildkite/commands/danger-pr-check.sh
.buildkite/pipeline.yml
.github/workflows/run-danger.yml

This PR experiments moving the current Buildkite step setup to GitHub Actions (as discussed on paaHJt-5Qn-p2).
Running on Buildkite is still an option, but it would require a GitHub action (or an intermediate server) to forward to Buildkite Pull Request Events such as "labeled", "unlabeled", "milestoned" and so on. This was implemented as a prototype on https://github.com/woocommerce/woocommerce-android/pull/10385.
If we find problems using GitHub Actions, we can always revert this change and go back to Buildkite, as the setup works in general (just not as fast and as simple as GHA alone).
Make sure CI is green and Danger runs on labels/milestones/reviewers changes as well as on code changes.

Move Danger to GitHub Actions

---

.github/workflows/gradle-wrapper-validation.yml

This reverts https://github.com/Automattic/pocket-casts-android/pull/1683.
At first, the Gradle Wrapper Validation check in both Buildkite and GitHub Actions seemed redundant, specially given GHAs were completely disabled for this repo. But comparing to other repos and discussing with the team, we consider a good idea to have this additional safety layer.
So this PR will add back the Gradle Wrapper Validation, now with the proper Actions configuration.
Just make sure CI is green and the Gradle Wrapper Validation workflow runs successfully on GitHub Actions as well.

Revert "Remove Gradle Wrapper Validation GitHub workflow"

---

app/src/main/AndroidManifest.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt

This PR specifies [foreground service types at runtime](https://developer.android.com/develop/background-work/background-tasks/persistent/how-to/long-running#specify-foreground-service-types-runtime) when calling `setForeground()` or `setForegroundAsync()` which is required if the app targets Android 14.
This is needed at two places, while
1. downloading episodes
2. importing OPML 
To get this working, I also had to [declare the foreground service type in the Android manifest](https://developer.android.com/develop/background-work/background-tasks/persistent/how-to/long-running#declare-foreground-service-types-manifest) for the long-running worker.
Prerequisites: Change `targetSdkVersion` set to 34 in `dependencies.gradle.kts`
2. Open any podcast -> episode
3. Tap …

Android14 - Specify foreground service types

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java
modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/FileUtilTest.kt

This is a preparation PR for migrating [`FileUtil`](https://github.com/Automattic/pocket-casts-android/blob/61fe9bf02411dbb158ec838d2fc4834099e99a4b/modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/FileUtil.java) from Java to Kotlin. Since it is a utility class that is used in multiple areas of code I find it will be easier to verify correctness through automated tests rather than through manual checking of every possible functionality that uses this code.
Some tests seem a bit redundant like `copy()`/`copyFile()`/`copyDirectory()` but I did it to make migration easier. In the migration PR I'll probably make some of these function private and delete tests for them while also migrating code using it to use only a single `copy()` function.
I didn't test for …

Add tests for FileUtil

---

.github/workflows/run-danger.yml

Following up on https://github.com/Automattic/pocket-casts-android/pull/1667, this PR adjusts the GitHub workflow reference to use Dangermattic's main branch.

Adjust GitHub workflow reference to use Dangermattic's main branch

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt

This fixes native share URL handling. 
(Internal Ref: p1704359709586349-slack-C02A333D8LQ)
There were three issues while handling native URLs with scheme `pca.st`:
1. `openNativeSharingUrl(...)` passed podcast UUID instead of the URL to `openPodcastUrl(...)`. `openPodcastUrl(...)` internally called `serverManager.searchForPodcasts(url, ....)`, and returned a wrong podcast with UUID. 
2. After calling `openNativeSharingUrl(...)`, there was no `return` statement, so it also executed `openPodcastUrl(IntentUtil.getUrl(intent))` which opened the correct podcast on top of the wrong podcast.
3. `openNativeSharingUrl(...)` did not handle native share URLs with a single path segment (e.g. https://pca.st/yaoi883d). 
To fix these, I: 
- added a return statement at line 1282
- passed URL instead of …

Fix native share url handling

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
modules/services/localization/src/main/res/values-ar/strings.xml
modules/services/localization/src/main/res/values-de/strings.xml
modules/services/localization/src/main/res/values-en-rGB/strings.xml
modules/services/localization/src/main/res/values-es-rMX/strings.xml
modules/services/localization/src/main/res/values-es/strings.xml
modules/services/localization/src/main/res/values-fr-rCA/strings.xml
modules/services/localization/src/main/res/values-fr/strings.xml
modules/services/localization/src/main/res/values-it/strings.xml
modules/services/localization/src/main/res/values-ja/strings.xml
modules/services/localization/src/main/res/values-ko/strings.xml
modules/services/localization/src/main/res/values-nb/strings.xml
modules/services/localization/src/main/res/values-nl/strings.xml
modules/services/localization/src/main/res/values-pt-rBR/strings.xml
modules/services/localization/src/main/res/values-ru/strings.xml
modules/services/localization/src/main/res/values-sv/strings.xml
modules/services/localization/src/main/res/values-zh-rTW/strings.xml
modules/services/localization/src/main/res/values-zh/strings.xml
modules/services/localization/src/main/res/values/strings.xml

- This PR updates the `Folders` benefit to `Folders & Bookmarks`, `Desktop` to `Desktop & web apps` and `Watch Playback` to `Apple Watch & Wear OS apps`
- Renamed `onboarding_plus_feature_folders_title` to `onboarding_plus_feature_folders_bookmarks_title`
- Apply the [update_plus_benefits.patch](https://github.com/Automattic/pocket-casts-android/files/13918564/update_plus_benefits.patch)
- Log in with a free account
- Play an episode
- Click on the 3 dots
- Try to Bookmark
- You should be able to see the Up sell modal with the updated benefits

Update Bookmarks Plus benefits

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

This PR builds on https://github.com/Automattic/pocket-casts-android/pull/1690. That PR added the first named setting to sync using the new call, and this PR adds the remaining named settings that are currently being synced with the new call. With this change, the app is syncing the same data regardless of whether the sync setting feature flag is turned on or off.
This also adds a few more deprecation annotations for methods that we can remove when we remove the feature flag for this feature.
For all these tests you will need to:
1. Install the app on two devices
2. Log into the same Pocket Casts account on both devices
3.  Turn on sync settings under Profile → ⚙️ → Beta features → Settings Sync
1. Device 1: go to Profile → ⚙️ → General, and update the skip back time to a new value
2. …

Add remaining named settings that currently sync to new named settings sync call

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFlow.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt

This PR
- Adds a source for the following analytics events (internal ref: p1705339364325069/1705194590.257499-slack-C04DL33V5J7):
`select_payment_frequency_next_button_tapped`
`select_payment_frequency_shown`
`select_payment_frequency_dismissed`
- Adds two upsell flow sources:  `overflow_menu`, `bookmarks_shelf_action` 
- Fixes select payment frequency screen display (it should not be shown except from the account details upgrade/ renew/ start free trial view pager where payment frequency needs to be selected) (dc672ef605cbffbcefc300950d5071cbeb9be82f) as the payment frequency (monthly/ yearly) is already selected on the upsell screen. Seems like the condition was slightly modified while removing `PATRON_ENABLED` feature flag here: …

Update tracking source

---

.github/workflows/submit-gradle-dependencies.yml

This PR adds a GitHub Actions job to send Gradle/Maven dependencies to Github Dependency Graph for each push to `main` or `release/*` branch.
By sending those dependencies, we allow Dependabot to scan whether dependencies we use are affected by known vulnerabilities.
Soon, those metrics will be available to visualize on Apps Metrics ([link](https://metrics.a8c-ci.services/grafana/d/f2131a73-89a3-48b9-8d3b-ecc1456347ac/dependabot-security-alerts?orgId=1)).
More about this project can be found internally at paaHJt-5Tn-p2
I verified correctness on [my fork](https://github.com/wzieba/pocket-casts-android). This PR is also a twin of PRs working in other repositories, which are fine. I think manual testing is not necessary.

ci: submit Gradle dependencies to GH dependency graph

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodePlayingStatus.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodePlayingStatusTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt

This is a follow-up to #1703 that updates the new sync call (`/user/sync/update`) to sync episode information. This new call will take the place of the current "/sync/update" call. 
Before this PR, the information that was being synced in the old call that the new call is also syncing is for:
- podcasts
The information that was not _yet_ being synced by the new call is:
- episodes
- folder
- filters
- bookmarks
- stats
This PR is adding syncing of **episode** data to the new call.
For all these tests you will need to:
1. Install the app on two devices
2. Log into the same Pocket Casts account on both devices
3.  Turn on sync settings under Profile → ⚙️ → Beta features → Settings Sync
1. Device 1:
1. Select an episode you have not interacted with before and mark that episode as played from …

Adding incremental sync of episodes with the new endpoint

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/user/UserManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

This PR improves how we determine/set whether a setting should be synced.
Previously, when updating a value and saying it did not need to be synced with something like `.set(value = 1, needsSync = false)`, we were leaving the modifiedAt value (which indicates sync is needed if it is not `null`). This meant that if you called `.set(value = 1, needsSync = true)` and then immediately called (`.set(value = 2, needsSync = false)` the setting of the value to `2` would not overwrite the modifiedAt value and the setting would be synced during the next incremental sync. 
This is a problem, but I think it's just a theoretical problem at this point because I can't think of any way a user could actually get into this scenario. Still improving this handling feels like the thing to do because it feels …

Improve handling of whether a setting should be synced

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfItem.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/res/layout/fragment_podcast.xml
modules/features/podcasts/src/main/res/menu/podcast_menu.xml
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/images/src/main/res/drawable/ic_flag.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/extensions/Fragment.kt
modules/services/ui/src/main/res/values/themes.xml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt

This adds a report violation option in the app behind a feature flag that depends on a non-empty URL in the Firebase Console - remote config.
(Internal ref: pdeCcb-4aS-p2#comment-3197)
> [!WARNING] 
> Targets 7.56 (If it is difficult to include it in today's code-freeze, feel free to include it in the next beta)
1. Edit minimum fetch interval to 5s in `FirebaseModule` inside the app
2. Install the `release build` variant
3. ✅ Notice that there is no report option on the top tool bar
4. Play an episode
5. Go to Player screen
6. Tap more menu on the bottom shelf
7. ✅ Notice that there is no report option 
8. Open Firebase Console and edit `report_violation_url` remote config to any valid URL for the android app
9. Restart the app
10. Open a podcast
11. ✅ Notice that there …

Add report violation option

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateAccountFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateFrequencyAdapter.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateFrequencyFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreatePayNowFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

- This PR does a little refactor for subscriptions with an offer. Currently we have only trial subscription and we want to support another type of offer
- This prepared for an update on the upgrade subscription page. In the next PR I will implement the UI, but for now I replaced the offer strings with `TODO`
git apply [release.patch](https://github.com/Automattic/pocket-casts-android/files/13998087/release.patch)
1. Run the app and login in with a free account that never had a subscription
2. Go to `Podcasts` tab
3. Click on folders
**4. You should see the TODO text on the upgrade Button for Plus/Yearly plan**

Make trial logic generic for offers

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/account/build.gradle.kts
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivityContract.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModel.kt
modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingExitInfo.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt

This displays plus promotion after login for free account to match iOS behavior.
(Internal ref: p1705270282607759-slack-C028JAG44VD)
0. Fresh install release build
1. From the login and sign-up screen, tap `Log in `
2. Enter email/ pwd for a free user and log in
3. ✅ Notice that you see upsell screen 
4. Sign out and clear app storage
5. Restart the app
6. Login using Google for a free user 
7. ✅ Notice that you see upsell screen 
1. Repeat steps from Test.1 for paid user
2. ✅ Notice that you do not see upsell screen 
2. Go to `Profile` tab
3. Tap `Set up account`
4. Tap `Log in `
5. Enter email/ pwd for a free user and log in
6. ✅ Notice that you see upsell screen
7. Dismiss the upsell screen and sign out
8. Repeat steps 2-3
9. Login using Google for a free user 
10. ✅ …

Plus promotion login

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt

This fixes an issue where starring an episode from a full-screen player does not prevent the episode from being archived.
When up next queue's current episode is starred, star status is updated for the episode in the database but the status is not updated for the in-memory up next queue's current episode.
Because of this, [on completion of the episode](https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt#L1115-L1127), when [star status is checked](https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt#L623) while checking if it should be …

Fix starring episode from full-screen player does not prevent episode from being archived

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt

This is part of: #1728 
- This small PR just updates the `purchase_successful`, `purchase_cancelled` and `purchase_failed` events to deprecate `is_free_trial ` property and includes `offer_type ` that can be `none`, `free_trial`, `intro_offer`
- This PR does have the layout updated. This change will be addressed in https://github.com/Automattic/pocket-casts-android/pull/1733
[Screen_recording_20240125_141613.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/340ae821-1291-4984-bad8-124c33646da6)
- git apply [debug_build.patch](https://github.com/Automattic/pocket-casts-android/files/14055979/debug_build.patch)
- run in debug variant
- To see the credit card screen you need to have your email listed in `License testing`
- Login with a free account
- Profile -> Account …

Update: Offer tracks

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsOptionsDialog.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/PodcastGridLayoutType.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Continuation of the sync settings project. This PR adds syncing of the podcasts grid layout.
2. Sign in on both devices with the same account that is subscribed to some podcasts.
4. Sync both devices by going to the Profile tap and tapping `Refresh now` at the bottom.
5. D1: Go to the Podcasts tab.
6. D1: Open the overflow menu.
7. D1: Select the list layout (the one to the right).
8. D1: Sync the device in the Profile tab.
9. D2: Sync the device in the Profile tab.
10. D2: Go to the Podcasts tab. You should see items displayed using the list layout.
11. D2: Open the overflow menu.
12. D2: Select the small grid layout (the one in the middle).
13. D2: Sync the device in the Profile tab.
14. D1: Sync the device in the Profile tab.
15. D1: Go to the Podcasts …

Sync grid layout setting

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/images/RoundedCornersTransformation.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt

This fixes horizontal artwork aspect ratio by using a modified version of Coil's rounded corners image transformation that does not crop to the target size. 
I'm not yet fully sure that removing cropping to the target size during transformation can cause any issues. In Test.3, I tested loading a very large image and noticed that it didn't crash the app. 
Also, it seems another image loading library, [Glide does not crop to the target size](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/TransformationUtils.java#L581) in rounded corner transformation.
Fixes #1719
1. Play this episode with a horizontal artwork: https://pca.st/episode/c7bc3a08-17b7-48c8-b5b9-dbdfd63211f4
3. ✅ Notice that full artwork is …

Fix artwork aspect ratio

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateAccountFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateFrequencyAdapter.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreatePayNowFragment.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/components/ProductAmountVerticalText.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionPriceSection.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/UpsellButtonTitle.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This is part of: #1728
This PR updates two screens with intro offer UI: Upgrade screen page and the Profile Page
- git apply ~~[release.patch](https://github.com/Automattic/pocket-casts-android/files/13998087/release.patch)~~  [new_patch.patch](https://github.com/Automattic/pocket-casts-android/files/14036750/new_patch.patch)
- To be able to see offers make sure the `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` is `true` to enable intro offer
1. Run the app and login in with a free account that never had a subscription
2. Go to `Podcasts` tab
3. Click on folders
1. Run the app and login in with a free account that never had a subscription
2. Go to `Profile` tab
- Make sure the `Feature.INTRO_PLUS_OFFER_ENABLED.defaultValue` is `false` to disable intro offer and see trial offer
1. Run …

Update UI with intro offer

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/OnboardingFlowComposableTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/account/build.gradle.kts
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivity.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingActivityContract.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModel.kt
modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingExitInfo.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/images/RoundedCornersTransformation.kt

This cherry picks changes from #1726 and #1742 to `release/7.56`.
#1726  is included to match iOS in terms of plus promotion display when this experiment is conducted next month: pdeCcb-4mW-p2
#1742 is included to fix an important aspect ratio issue. 
PRs are already tested. Make sure that commits are cherry-picked correctly.

Cherry pick #1726 and #1742

---

.github/workflows/run-danger.yml

Our Danger configuration isn't passed to the GitHub Action runner when a workflow is triggered from a forked repository.
This PR solves this problem by allowing GitHub's own `GITHUB_TOKEN` to be used for running Danger on forked repos.
See https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow

Allow Danger to run on forked repos using GITHUB_TOKEN

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global row action settings.
1. Have to devices D1 and D2.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`/`Row action`.
4. D1: Change the value of `Row action` to `Download`.  
7. D2: Open a podcast.
8. D2: Notice that you have a download action on the row. Tap it to see that an episode downloads.
9. D2: Go to `Profile`/`Settings (cog icon)`/`General`/`Row action`.
10. D2: Change the value of `Row action` to `Play`.
11. D2: Sync the device in the `Profile`.
12. D1: Sync the device in the `Profile`.
13. D1: Open a podcast. …

Sync row action setting

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This adds content type to playback events.
Internal Ref: p1706301363090919/1706229369.681599-slack-C02ATC80MUM
1. Play an episode from `Ted Talks Daily (HD video)` containing video episodes
2. Notice in logs: `Tracked: playback_play, Properties: {...","content_type":"video",`
3. Play an episode from `The Daily`  containing audio episodes
4. Notice in logs: `Tracked: playback_play, Properties: {...","content_type":"audio",`
Notice that content-type is present for other playback events like: pause, skip_back, skip_forward, stop

Add content type to playback events

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/81.json
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/82.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt

This is the continuation of settings sync. This PR syncs individual podcast settings for the up next queue and custom playback effects.
1. Install the app from an older commit. For example 1de83320e0af63e0570634e04e87498d569adf97.
2. Have some podcasts that you're subscribed to.
3. Checkout `update/sync-podcast-settings` branch. Make sure that it is up-to-date.
4. Install the app.
5. Open the app and make sure that app didn't crash and you can still see all of your podcasts without a need to sync the account.
1. Have to devices - D1 and D2.
2. Sign in on both devices with the same account.
3. Sync both devices by going to profile and tapping on `Refresh now`.
4. D1: Open a podcast and go to its settings (cog icon).
5. D1: Enable `Add to Up Next` setting.
6. D1: Sync the device in the …

Sync queue and effects settings for podcasts

---

app/src/main/AndroidManifest.xml

This adds foreground service media playback permission as part of Android 14 target SDK changes. 
1. Temporarily change `targetSdkVersion` to 34 in `dependencies.gradle.kts`
2. Install the app
4. Notice that 
- the episode plays fine
- media notification is displayed in the notification drawer
- there is no log complaining of missing FGS media playback permission:
`Playback: attempted startForeground for state: 6, but that threw an exception we caught: java.lang.SecurityException: Starting FGS with type mediaPlayback callerApp=ProcessRecord{fcfd6af 29813:au.com.shiftyjelly.pocketcasts.debug/u0a1490} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK]`

Android 14 - Add foreground service media playback permission

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/TrimMode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/player/EffectsViewModel.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global playback effects. This setting can be changed in multiple ways: Phone app, Notification center, WearOS app, Tasker app.
Each test requires two devices to check syncing. Sync process looks as follows.
1. Make sure that both devices are synced before starting the test by refreshing apps in the profile.
2. Change the setting on the device 1.
3. Refresh settings on the device 1.
4. Refresh settings on the device 2.
5. Check settings on the device 2.
Settings configuration can be reached by playing a podcast, opening the player, and then opening playback effects. You need to make sure that those are global settings. If settings are local to podcast you'll see a banner at the bottom that allows to `Clear` the …

Sync playback effects setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for swiping episodes.
1. Have to devices D1 and D2.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`/`Up Next swipe`.
4. D1: Change the value of `Up Next swipe` to `Play last`.  
7. D2: Open a podcast.
8. D2: Swipe an episode that is not in your queue all the way to the right. It should be added to the bottom of the queue.
9. D2: Go to `Profile`/`Settings (cog icon)`/`General`/`Up Next swipe`.
10. D2: Change the value of `Up Next swipe` to `Play next`.
11. D2: Sync the device in the `Profile`.
12. D1: Sync …

Sync up next swipe setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PodcastGrouping.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for episode grouping.
It can be confusing that sync setting does not apply automatically to podcasts that are on a device. This is by design. The setting on a synced device applies only to new podcasts. If users want to apply the grouping on a synced device they need to re-trigger the setting.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`/`Podcast episode grouping`.
4. D1: Change the value of the setting. You can dismiss the popup about applying the setting to available podcasts.
6. D2: Sync the device in the …

Sync episode grouping setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/MediaNotificationControlsFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManagerNetworkWatcher.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManagerNetworkWatcherTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global media notification actions.
1. Have two devices D1 and D2 that can display custom notification actions.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`/`Media notification controls`.
4. D1: Toggle the setting. If the setting is enabled reorder the actions.  
7. D2: Play an episode.
8. D2: Open notifications center and notice that your custom actions are applied according to settings.
9. D2: Go to `Profile`/`Settings (cog icon)`/`General`/`Media notification controls` and notice that settings are in sync with D1.
10. …

Sync media notification actions setting

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for keep the screen awake why player is opened and opening player automatically when playing a new episode.
2. In the device settings set screen timeout setting to the lowest possible. For me on Pixel 6 it is 15 seconds.
4. D1: Go to `Profile`/`Settings (cog icon)`/`General`.
5. D1: Toggle `Keep screen awake` to `ON`.
6. D1: Sync the device in the `Profile`.
7. D2: Sync the device in the `Profile`.
8. D2: Play an episode and open the player.
9. D2: Wait for the amount of time set in the second step. Screen should not go black.
10. D2: Minimize the player.
11. D2: …

Sync keep awake and open player settings

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for showing archived episodes.
It can be confusing that sync setting does not apply automatically to podcasts that are on a device. This is by design. The setting on a synced device applies only to new podcasts. If users want to apply it on a synced device they need to re-trigger the setting.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`/`Show archived`.
4. D1: Change the value to `Show`. You can dismiss the popup about applying the setting to available podcasts.
7. D2: …

Sync show archived setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for the intelligent playback.
Intelligent playback rules are defined as follows.
```kotlin
when (paused time since now) {
in (5 minutes)..(1 hour) -> 10 seconds
in (1 hours)..(24 hours) -> 15 seconds
in (24 hours)..(infinity) -> 30 seconds
else -> 0 seconds
}
```
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`.
4. D1: Toggle `Intelligent playback resumption` to `ON`.
7. D2: Play an episode.
8. D2: Pause an episode and note the time that it was paused at.
9. D2: Wait for some …

Sync intelligent playback setting

---

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for the queue auto play.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`.
4. D1: Toggle `Autoplay` to `ON`.
7. D2: Make sure that your queue is empty and play an episode.
8. D2: Scroll the timestamp near the end and let the episode finish.
9. D2: A next episode should start playing automatically.
10. D2: Clear the playback.
11. D2: Go to `Profile`/`Settings (cog icon)`/`General`.
12. D2: Toggle `Autoplay` to `OFF`.
13. D2: Sync the device in the `Profile`.
14. D1: Sync the …

Sync auto play setting

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for showing/hiding playback notification.
There was also a bug where the state of the setting was not represented correctly because we didn't call the setup method. I didn't find an issue for that which makes me think that probably not a lot of people use this feature. But, hey… 🤷‍♂️ 
3. D1: Go to `Profile`/`Settings (cog icon)`/`Notifications`.
4. D1: Toggle `Hide playback notification on pause` to `ON`.
7. D2: Play an episode.
8. D2: Open notifications center and pause an episode. …

Sync hide playback notification setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for tapping items in the queue.
3. D1: Go to `Profile`/`Settings (cog icon)`/`General`.
4. D1: Toggle `Play Up Next episode on tap` to `ON`.
7. D2: Add some episodes to the queue.
8. D2: Open the queue.
9. D2: Tap on an episode in the queue. It should move to the top and start playing.
10. D2: Long press an episode in the queue. It should open its details.
11. D2: Go to `Profile`/`Settings (cog icon)`/`General`.
12. D2: Toggle `Play Up Next episode on tap` to `OFF`.
13. D2: Sync the …

Sync play up next item on tap setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/NotificationsSettingsFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/PlayOverNotificationSetting.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for playing podcasts over notifications.
3. D1: Play your queue.
4. D2: Go to `Profile`/`Settings (cog icon)`/`Notifications`.
5. D2: Change `Play over notifications` to `Duck volume`.
7. D1: Sync the device in the `Profile`.
8. D1: Open an app that can trigger audio notifications. For example you can use Google Maps and start navigation.
9. D1: Once you hear notifications form a different app a podcast should play with lower volume and then come back to a default loudness.
10. D2: Go to `Profile`/`Settings (cog …

Sync play over notifications setting

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt

This sets a sample rate (0.3) for errors in Sentry.
Internal Ref: p1706544857589869-slack-C028JAG44VD
1. Comment `if (isDebug)` condition in `SettingsFragmentPage` so that `DeveloperRow` is visible for the release build
3. Go to `Profile` -> `Settings` -> `Developer`
4. Tap `Report a crash` 10 times
5. Open `Sentry`
6. Select the release in Sentry set in `versions.properties`
7. Look for `Exception: Test crash` and open in `Discover`
8. ✅ Notice that 3 instances are recorded recently (0.3 x 10)

Sentry set sample rate for errors

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoAddSettingsViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/AutoAddUpNextLimitBehaviour.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for auto adding to the queue.
I filed an issue that I discovered related to syncing Up Next settings - #1770.
> [!note]
> I don't think there is a good way to test this setting through the app behavior and this test is only about checking that the settings are synced and hoping that they apply correctly.
3. D1: Go to `Profile`/`Settings (cog icon)`/`Auto add to Up Next`.
4. D1: Change the values of `Auto add limit` and `If limit reached` settings.
7. D2: Go to `Profile`/`Settings (cog …

Sync auto add to Up Next settings

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/settings/SettingsViewModel.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global setting for warning on metered networks. This setting can be changed in multiple ways: Phone app and WearOS app.
To test wear OS you need either a physical device or prepare the app so you can use it with the wearOS emulator.
Build the *release* version of the app with this condition inverted.
```diff
--- a/modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
+++ b/modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
@@ -30,7 +30,7 @@ enum class Feature(
SETTINGS_SYNC(
key = "settings_sync",
title = "Settings Sync",
-        defaultValue = BuildConfig.DEBUG,
+        defaultValue = !BuildConfig.DEBUG,
tier = …
```

Sync warn on metered network setting

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTracker.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing of the global settings for collecting Firebase events.
I was not able to create a reliable test that would really see integration with the Firebase. We could test it with a proxy but I think it would be an overkill. Logs should suffice given that the single entry point for logging analytics is here.
https://github.com/Automattic/pocket-casts-android/blob/700c4f25137fa9f2ecdb34d17b1ccdf8a95eea9f/modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/FirebaseAnalyticsTracker.kt#L263-L269
3. Have the Logcat opened for D2 with this filter …

Sync collecting privacy analytics setting

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/images/PodcastImageLoader.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt

In #1599 , we added episode artwork to the full-screen player and the episode details screen, and we now want to use it in more places in the app. See #1608 for more details. I've added artwork in MiniPlayer, Notification and Widget. 
**Testing the Miniplayer, Notification & Widget**
2. Open up the podcast screen for "Darknet Diaries"
3. Open the episode details page for an episode and see the artwork of episode.
4. When network connection active or inactive, observe the Miniplayer, Notification & Widget artwork loaded from episode if successfully loads, If fails, automatically load the artwork of podcast.

Display Episode Artwork In Miniplayer, Notification & Widget

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/developer/DeveloperPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing of the global settings for enabling crash reports and linking user's account to those reports.
For easier testing I added setting custom messages to triggered crashes.
* This should be tested with a release version of the app.
* You must have the Sentry DSN property set. Otherwise crash reporting won't work and you'll see in the logs this message `WARNING: Sentry DSN gradle property 'pocketcastsSentryDsn' not found. Crash reporting won't work without this`.
* Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14125118/developer.patch).
3. D1: Go to …

Sync crash reporting settings

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing of the global settings for auto adding cloud files to the queue.
3. D1: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
4. D1: Toggle `Auto add to Up Next` setting to `ON`.
7. D2: Go to `Profile`/`Files`
8. D2: Add a file. It should be added automatically to queue.
9. D2: Got to `Overflow menu (three dots)`/`File settings`.
10. D2: Toggle `Auto add to Up Next` setting to `OFF`.
11. D2: Sync the device in the `Profile`.
12. D1: Sync the device in the `Profile`.
13. D1: Go to …

Sync auto add files to queue settings

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

This reduces playback buffering time, particularly `minBufferMs` from 5 to 2 minutes.
Relevant `Sentry` reports:
https://a8c.sentry.io/share/issue/5bfb9279699743558f7a714689b6d9a8
https://a8c.sentry.io/share/issue/81c14ecb62d04670908583246910e1c3
It might be tricky to test it based on different network speeds and episodes selected. 
Make sure that episodes should play fine.
Let's continue to monitor these reports in Sentry and if needed, experiment with the values.

Playback - Reduce buffer time

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

- Since we are going to use  the Google-determined eligibility for intro offer (the same one we have for trial offer) we already have the user eligibility implemented. 
- We are going to display the offer for users that never had this subscription before. This case is this subscription -> `com.pocketcasts.plus.testfreetrialoffer`, but in PRO could be an plus yearly subscription as an example.
- This PR includes just renames and the new subscription product id 
This is part of: https://github.com/Automattic/pocket-casts-android/issues/1728
The user eligibility was already tested for trial offer, but if you want to test it again, I will describe some tests you could do:
**Prerequisites**
1. Setup in app billing sandbox
2. Have the `INTRO_PLUS_OFFER_ENABLED` feature flag with `defaultValue` …

Refactor names for User eligibility for Intro offer

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/ThemeSettingObserver.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ThemeSetting.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt

One of the settings listed for sync project #1739. This PR adds syncing of the global settings for the app theme.
2. On both devices disable `Profile`/`Setting (cog icon)`/`Appearance`/`Use Android Light/Dark Mode`. This setting is not synced and might be problematic during the test.
4. D1: Go to `Profile`/`Setting (cog icon)`/`Appearance`.
5. D1: Change the theme.
6. D1: Sync the device in the `Profile`.
7. D2: Sync the device in the `Profile`.
8. D2: Notice that theme changes. Screen might jump because applying theme in Pocket Casts recreates the Activity.
9. Test this with different themes.

Sync theme setting

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsOptionsDialog.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/BadgeType.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing of the global settings for displaying podcast badges.
To test this you should be subscribed to a mix of different podcasts. There should be unfinished episodes, new episodes that you didn't listen to, and so on. 
3. D1: Go to `Podcasts`/`Overflow menu (three dots)`.
4. D1: Select `Only latest episode` badge type.
7. D2: Go to `Podcasts`.
8. D2: Notice dotted badges on podcasts.
9. D2: Open `Overflow menu (three dots)`.
10. D2: Select `All unfinished` badge type.
11. D2: Sync the device in the `Profile`.
12. …

Sync podcast badges setting

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt

This adds feature flag for Slumber Studios that depends on Firebase remote config `slumber_studios_promo_code` in the release build.
> [!WARNING]
> Targets 7.57
1. `setMinimumFetchIntervalInSeconds` to 5L (5 secs) in `FirebaseModule`
2. Add a log statement at the end of `PocketCastsApplication.onCreate()` that prints `FeatureFlag.isEnabled(Feature.SLUMBER_STUDIOS_PROMO)`
3. Install release build
4. Launch the app
5. ✅ Notice in logs that the feature flag for Slumber Studios is false
1. Set a string value for `slumber_studios_promo_code` in `Firebase` remote config for Android app and publish changes
2. Kill the app
3. Restart the app
4. ✅ Notice in logs that the feature flag for Slumber Studios is true
Important (after tests are completed):
- Reset `slumber_studios_promo_code` in …

Slumber Studios - Add feature flag

---

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing of the global settings specific to automotive app.
Syncing is done in 6eb8327ed7866b8890a18429af2b50c2c0f904a9. Other commits just clean up the code, switch to coroutines, and make the screen reactive to changes during sync.
1. Have two automotive devices D1 and D2.
2. Install `:automotive` app on them.
3. Make sure that both devices are synced before starting the test by refreshing apps in the settings.
4. D1: Go to `Settings (cog icon)`.
5. D1: Toggle `Subscribe to played podcasts` notification `ON`.
6. D1: Tap on `Refresh now`.
7. D2: Tap on `Refresh now`.
8. D2: Play a podcast that you're not subscribed to.
9. D2: Check `Podcasts` tab.
10. D2: Notice that you see that podcast there.
11. D2: Go to `Settings (cog …

Sync automotive settings

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/components/ProductAmountVerticalText.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionPriceSection.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionProductAmountHorizontal.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt

This PR does some UI updates:
1. Updates the size of the price displayed in the upgrade card
2. Updates the Recurring payment message
3. Updates the badges arrangement to be in horizontal 
1. Setup in app billing sandbox
3. Have the `INTRO_PLUS_OFFER_ENABLED` feature flag with `defaultValue` set to `true`
4. Install the release build on device medium / large device
5. Sign-in to Google Play with an account that does not have a purchase history. Make sure it is the primary account in case you have more than one account.
6. Launch the app
7. Go to accounts -> See if the offer badge is displayed on the side of Plus badge
8. Click on `Subscribe to Plus` button -> Select the intro offer -> Check if the text matches with: `"Recurring payment at ${price} after your first year ({end date})"`
9. …

Intro offer: Update upgrade plus modal

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/CreateFilterViewModel.kt

Changes to the name, color, and icon of a filter did not trigger a need to sync the filter.
Closes #1721
1. Have an account with at least one filter.
2. Have to devices D1 and D2.
4. D1: Go to `Filter`/`<YOUR_FILTER>`/`Overflow menu (three dots)`/`Filter settings`.
5. D1: Change the name of the filter.
6. D1: Go back.
7. D1: Sync the device in the `Profile`.
8. D2: Sync the device in the `Profile`.
9. D2: Go to `Filter` and notice that your filter changed the name.
10. D2: Go to `<YOUR_FILTER>`/`Overflow menu (three dots)`/`Filter settings`.
11. D2: Change the color of your filter.
12. D2: Go back.
13. D2: Sync the device in the `Profile`.
14. D1: Sync the device in the `Profile`.
15. D1: …

Sync filters when basic settings change

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/SlumberStudiosHeader.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowOutlinedButton.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowTextButton.kt

This converts Slumber Studios what's new to full modal.
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14176680/patch_whats_new.patch)
2. Install debugProd build
3. Launch the app
4. ✅ Notice what's new for `Slumber Studios` promo is displayed in full modal
5. ✅ Swiping down should resize the modal
6. Tap Cancel
7.  ✅ Modal should dismiss
https://github.com/Automattic/pocket-casts-android/assets/1405144/20eac4b0-5902-4425-b624-aeb438fc6b79
Landscape
Small screen
Since we're merging changes to a frozen branch, the modal can be converted to pop-up again by updating the fullModal variable in the view modal, in case it is needed

Slumber Studios - Full Modal What's new 

---

app/proguard-rules.pro
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/text/HtmlText.kt

This PR
- Prevents modal from closing when confirm action is tapped
- Updates layout after subscribing to Plus
- Makes text body selectable
- Prevents modal from accidental closing on layout tap (so that promo code can be copied)
Prerequisite
- Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14193646/patch-test-promo.patch)
1. Login with license test account having no plan linked with it (free user)
2. Force kill and relaunch the app
3. Slumber Studios - What's New should be shown
4. Tap `Subscribe to Plus`
5. Complete purchase flow
6. ✅ Notice that the text is updated on the modal and promo code is shown
7. Try to select the promo code
8. ✅ Notice that the text is selectable
9. Tap anywhere on the modal body
10. ✅ Notice …

Slumber Studios - What's New Full Flow

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

This PR uses last sync timestamp as a default modification timestamp when the value of a setting modification timestamp is unknown. We do this because we want to make sure that all settings sync when the feature is enabled. Otherwise users would have to re-trigger all of the settings one by one.
Closes #1762 
2. D1: Install the app from c86132a18ae6eebe67b65ccde33f46e9173c7dd1.
3. D1: Sign up with a new account.
4. D1: Subscribe to any podcast.
5. D1: Go to this podcast settings.
6. D1: Enable notifications for this podcast.
7. D1: Set custom playback effects for this podcast.
8. D1: Go to the global settings in the profile.
9. D1: Go to `General`.
10. D1: Change `Row action` setting.
11. D1: Change `Up Next swipe` setting.
12. D1: Change `Podcast episode …

Use last sync time as a default modified at timestamp

---

modules/features/player/src/main/res/layout/adapter_up_next_footer.xml

- The total time remaining string in Up Next was not being displayed correctly for some languages when device has large font size set.
- The solution I implemented was to use 
- See the attached screenshot in #1635 to observe the issue with `androidx.constraintlayout.helper.widget.Flow`, which is not aligning the items horizontally when there is available space; otherwise, it aligns them vertically.
Fixes #1635
- Play around different languages and device font size. I will also depending on the size of the device that you are testing
- You should not see 'Total time remaining' and `Clear queue` with a line break. If they do not fit within the available space, `Total time remaining` should be positioned above `Clear queue`
| English with large font size | English with normal font size | …

Fix: Total time remaining incorrectly displayed for some languages when device large font sizes are set

---

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt

This reverts what's new version code so that beta builds can be released without triggering what's new until we decide to release the new feature.
Nothing to test. Make sure that the version code is reset to a value that was present in `release/7.56`.

Revert what's new version code

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This improves Bluetooth skipping behavior noticed particularly on Pixel A-series buds since last few releases. 
> [!Warning]
> Targets release/7.57
I opted to target the release branch because the changeset is minor, we still have a week before the next release, and it resolves a painful problem experienced by some customers. Let me know if you think otherwise.
In PR #1510, we saved the latest playback position in the database before resetting the player and retrieved it using the `PlaybackManager`'s suspended `play(...`) method. This addressed a potential audio skipping issue after streaming media had been downloaded.
However, this introduced a side effect: when skipping from a Bluetooth device, the subsequent play command might retrieve the episode from a state before the new position …

Improve bluetooth skipping behavior (Pixel A-series buds)

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt

I reverted What's New code to a previous value in https://github.com/Automattic/pocket-casts-android/pull/1820 but I think at this point it will be better to keep the version code incremented and update the display for What's New so that it depends on the remote enabled feature flag for `Slumber Studios` which is what this PR does.
What's New will not be shown until the feature flag for `Slumber Studios` is enabled and we can also release beta builds.
Make sure that the condition to display What's New is updated correctly. 
1. Install release build from release/7.57
2. Install release build from this PR
3. Launch the app
4. What's new should not be shown

Update what's new display condition

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsPageViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/HeadphoneAction.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for headphone controls.
> [!note]
> 
> [!note]
> I added these tests before staging got fixed with podcasts API. I think they are sufficient but you can test with the real feature as well instead of just checking settings.
3. D1: Go to `Profile`/`Settings (cog icon)`/`Headphone controls`.
4. D1: Change `Previous action` to `Skip forward`.
6. D2: Sync the device …

Sync headphones actions settings

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt

Part of #1807 
This displays placeholder checkboxes for chapters (UI will be fine-tuned later).
1. Open podcast https://pca.st/upgrade
2. Play an episode from the podcast
3. Open full-screen player
4. Go to the `Chapters` tab
5. Notice that checkboxes are shown for chapters
6. Notice that you can select/unselect chapters (values are not persisted though)
1. Go to `Profile` -> `Settings` -> `Beta features`
2. Set `Deselect Chapters` toggle to off
3. Kill the app and reopen
4. Repeat steps 1-4 from Test.1 
5. Notice that checkboxes are not shown for chapters
Feature enabled
https://github.com/Automattic/pocket-casts-android/assets/1405144/6e4a4e2a-0aea-4899-8c37-e94ca268d062
Feature disabled

Deselect Chapters - Display checkboxes

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/BookmarksSortTypeDefault.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/BookmarksSortTypeForPodcast.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for bookmark sorting options.
> [!note]
> 
> [!note]
> You need to test it with a Patron account.
4. D1: Play an episode and create some bookmarks for it.
5. D1: Open the player.
6. D1: Go to `Bookmarks` tab.
7. D1: Tap on the `overflow menu (three dots)`.
8. D1: Change `Sort by` setting.
9. D1: Sync the device in the `Profile`.
10. D2: Sync the device in the `Profile`.
11. D2: Open the player.
12. D2: …

Sync bookmark sorting settings

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/SettingsAppearanceViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for dark Up Next queue theme.
> [!note]
> 
4. D1: Play an episode so that the mini player opens. You can pause playback after that.
5. D1: Go to `Profile`/`Settings (cog icon)`/`Appearance`.
6. D1: Change the theme to something light.
7. D1: Toggle `Use Dark Up Next Theme` setting `OFF`.
8. D1: Sync the device in the `Profile`.
9. D2: Sync the device in the `Profile`.
10. D2: Tap on the queue icon on …

Sync dark up next theme setting

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesViewModel.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/CloudFilesManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesViewModel.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for cloud files sorting order.
I had to refactor and change old code a bit because migrating to `UserSetting` from `get()/set()` functions removed a need for a `BehaviorRelay` and we can use `Flow` instead.
I also removed redundant `SortOrder` from `CloudFilesFragment` and moved missing properties to `Settings.CloudSortOrder`.
> [!note]
> 
3. D1: Add some custom files in `Profile`/`Files`.
4. D2: Go to …

Sync cloud files sorting order setting

---

.github/workflows/run-danger.yml
Dangerfile

Based on some [changes](https://github.com/Automattic/pocket-casts-ios/pull/1418#discussion_r1484240656) we implemented in the Pocket Casts iOS repo, I'm porting them here as well.
The changes basically some optimizations when running against a Draft PR, avoiding running some of the checks.

PR Checks: Improve Draft PR workflow

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/ThemeSettingObserver.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ThemeSetting.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/theme/Theme.kt

One of the settings listed for sync project #1739. This PR adds syncing to the global settings for system theme controls.
> [!note]
> 
3. D1: Go to `Profile`/`Settings (cog icon)`/`Appearance`.
4. D1: Toggle `Use Android Light/Dark Mode` to `OFF`.
7. D2: Notice that the app doesn't follow Android's Light/Dark Mode.
8. D2: Go to `Profile`/`Settings (cog icon)`/`Appearance`.
9. D2: Set `Classic` theme (this will …

Sync system theme settings

---

app/src/test/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModelTest.kt
base.gradle
gradle/libs.versions.toml
modules/features/account/src/test/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingActivityViewModelTest.kt
modules/features/endofyear/src/test/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModelTest.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModelTest.kt
wear/build.gradle.kts

While working on automating proto generation in #1831 I encountered a problem with Java compatibility. This PR switches our Java target and compatibility versions to 17. I had to fix some of the tests because we were mocking final classes and it is no longer possible with newer versions of JDK. There are some discussions on Mockito project about it with potential solutions like switching to MockK. But I think it is much simpler, and better, to not mock unnecessary objects.
CI checks should be enough. You can smoke test the apps.

Update JDK to 17

---

CHANGELOG.md

- This adds the CHANGELOG update for the #1815 fix

Update CHANGELOG.md with missing item

---

automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsPreferenceFragment.kt

We had a bug on automotive. We updated a wrong setting when `Auto play` preference was changed.
1. Sign in to Automotive app.
2. Go to Settings.
3. Toggle `Auto Play` setting.
4. Go back to the main screen.
5. Go back to Settings.
6. `Auto Play` setting should keep its value.

Use correct setting when changing auto play preference

---

CHANGELOG.md
modules/features/search/src/main/res/layout/fragment_search.xml

- Add missing content description to back button in Search for accessibility
Closes #1711
- Follow the steps described in https://github.com/Automattic/pocket-casts-android/issues/1711

[Accessibility] - Add missing content description to back button in Search

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveViewModel.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/85.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/protobuf/src/main/proto/sync_api.proto
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt

One of the settings listed for sync project #1739. This PR adds syncing to the podcast settings for auto archive configuration.
> [!note]
> 
I won't provide step by step instructions here as the auto archive controls consist of 4 separate settings. You should check if auto archiving configuration syncs correctly. You can reach them under `Podcasts`/`podcast`/`Settings (cog icon)`/`Auto archive`.

Sync auto archive podcast settings

---

gradle/libs.versions.toml

JDK 17 with sealed classes has issues with R8 on Android Gradle Plugin below `8.2.0`.
Internal ref: paaHJt-68S-p2
Build the release version of the app with `./gradlew :app:assembleRelease`. The build should be successful.

Update AGP to 8.2.2

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastSettingsFragment.kt

The podcast settings  screen could become unresponsive when navigating from and back to it. It was because we were nulling out the preferences. This is a mistake. Preferences do not hold references to views. Instead they fetch them by IDs every time.
Closes #1770
1. Open a podcast.
2. Go to the podcast settings by tapping on a cog icon.
3. Enable `Add to Up Next`.
4. Change the `Position` setting.
5. Open a different screen. For example tap on `Auto archive` or `Global settings`.
6. Go back.
7. Change the `Position` setting.
8. The state on screen should reflect the position correctly.

Fix podcast setting screen becoming unresponsive

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/PodcastGroupingTypeConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/PodcastGrouping.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/PodcastGroupingTypeConverterTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/protobuf/src/main/proto/sync_api.proto
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/podcast/PodcastViewModel.kt

One of the settings listed for sync project #1739. This PR adds syncing to the podcast setting for grouping episodes.
I also added a converter for `PodcastGrouping` type so it is recognized by the database and we can use it directly.
> [!note]
> 
2. Sign in with an account and have multiple podcasts added.
4. D1: Go to `Podcasts` and open a podcast.
5. D1: Tap on `Overflow menu (three dots)`.
6. D1: Change `Group episodes` setting.
7. D1: Sync the device in the `Profile`.
8. D2: Sync the device …

 Sync episode grouping podcast setting

---

fastlane/Fastfile

[`AndroidVersionFile`](https://github.com/wordpress-mobile/release-toolkit/blob/6c808e522c63a87458417d1d00803c8d50e23b59/lib/fastlane/plugin/wpmreleasetoolkit/versioning/files/android_version_file.rb#L26-L33) defined in the release-toolkit repo does not have `read_release_version` method defined. When trying to finalize the release I'm getting this error.
```
[04:51:00]: Error in your Fastfile at line 482
[04:51:00]:     480:      def release_is_hotfix?
[04:51:00]:     481:        # Read the current release version from the .xcconfig file and parse it into an AppVersion object
[04:51:00]:  => 482:        current_version = VERSION_FORMATTER.parse(VERSION_FILE.read_release_version)
[04:51:00]:     483:        # Calculate and return whether the release version is a hotfix
[04:51:00]: …
```

Use read_version_name to get app version

---

gradle/libs.versions.toml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This adds a remote control to our sync settings feature flag.
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14310308/sync_flag.patch).
2. Install release version of the app.
3. Open the app and go to the settings.
4. Open `Beta features`.
5. `Settings Sync` flag should be disabled.
6. Close the app.
7. Go to the [Firebase remote config](https://console.firebase.google.com/project/singular-vector-91401/config).
8. Change the `settings_sync` flag on Android to `true` and publish the changes.
9. Open the app and go to the settings.
10. Open `Beta features`.
11. `Settings Sync` flag should be enabled.
12. Close the app.
13. Go to the [Firebase remote config](https://console.firebase.google.com/project/singular-vector-91401/config).
14. Change the …

Enable remote flag for settings sync

---

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/protobuf/src/main/proto/sync_api.proto
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt

One of the settings listed for sync project #1739. This PR adds syncing to the podcast setting for showing archived episodes.
Closes #1739
> [!note]
> 
2. Sign in with an account and have multiple podcasts added.
4. D1: Go to `Podcasts` and open a podcast.
5. D1: Tap on `Show archived`. It should change to `Hide archived`.
6. D1: Sync the device in the `Profile`.
7. D2: Sync the device in the `Profile`.
8. D2: Go to the same podcast that you've just edited.
9. D2: Notice that the `Hide archived` …

Sync show archived podcast setting

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
base.gradle
modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/adapters/InstantAdapter.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

After much deliberation we decided to use epoch as a default timestamp. It doesn't have issues that `lastSyncTime` introduces and we won't have to deal with enabling or disabling syncing per device.
I added a simple `Instant` JSON adapter to avoid mapping. It doesn't do anything special and just delegates to `Date` adapter provided by Moshi. I didn't add any tests for it since it is a simple delegation.
3. D1: Go to `Podcasts`/`Some podcast`/`Settings (cog icon)`/`Playback effects`.
4. D1: Modify`Playback effects` settings.
5. D1: Go to `Profile`/`Settings (cog icon)`/`General`.
6. D1: Modify `Skip forward time` setting.
7. D1: Sync the device in the …

Use epoch as a fallback modification timestamp

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
modules/features/taskerplugin/src/main/java/au/com/shiftyjelly/pocketcasts/taskerplugin/controlplayback/ActionRunnerControlPlayback.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChaptersTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

Part of #1807 
Handles skipping chapters when they are deselected. 
(It doesn't add select at least one chapter condition yet.)
1. Play an episode having chapters from https://pca.st/upgrade
2. On the full player, go to "Chapters" tab and deselect some chapters
3. Go back to the "Now Playing Tab"
4. Use the chapter controls to move forward/backwards 
5. ✅ Notice that the chapters you unselected are not played
1. Play an episode having chapters from https://pca.st/upgrade
2. On the full player, go to "Chapters" tab and deselect some chapters
3. Go back to the "Now Playing Tab"
4. Tap on the seek bar at different positions
6. ✅ Notice that the chapters you unselected are not played
1. Play an episode having chapters from https://pca.st/upgrade
2. On the full player, go to "Chapters" tab and …

Deselect Chapters: Skip to selected chapter

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt

- The **skip forward** and **skip backward** buttons in the widget were not functioning as expected when the `previous action` and `next action` on the headphone control was set to `Add bookmark`.
- This issue occurred because when we clicked on these widget buttons, we were handling them in the `MediaSession` in the same place where we react to headphone taps. Therefore, this PR now handles the widget skip forward and skip backward clicks in `PodcastWidget` instead.
Closes #1832
1. Log in with Plus/Patron user
2. Go to Settings -> Headphone controls -> Make sure `Previous action` is set to `Skip back`
3. Go to Settings -> Headphone controls -> Make sure `Next action` is set to `Skip forward`
4. Play a podcast
5. Put the app in background
6. Hold the app to add the widget
7. Tap on Skip …

Fix: Widget uses custom Headphone controls instead of skipping

---

.buildkite/pipeline.yml
app/build.gradle.kts
automotive/build.gradle.kts
wear/build.gradle.kts

Internal communication link: pdnsEh-1wk-p2
This PR adds another job in the CI pipeline, to run release build variant to verify the R8 obfuscation process.
My assumptions:
- Locally, we don't ever want to send code mappings to Sentry. We want to do this only from CI
- I don't want to change the default behavior of "always sending code mappings when release variant is built", to not modify release flow we use now
Assert `./gradlew assembleRelease --dry-run | grep uploadSentry` doesn't return any tasks.
Let's simulate release build:
assert `CI=true ./gradlew assembleRelease --dry-run | grep uploadSentry` returns 3 tasks for each releasable module in the app:
```
:app:uploadSentryProguardMappingsRelease SKIPPED
:automotive:uploadSentryProguardMappingsRelease SKIPPED …
```

Assemble release apk on CI

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Add syncing support for deleting cloud files after playing them.
> [!note]
> You need to test this with a Plus account.
3. D1: Add a local file.
4. D1: Upload this file to cloud.
5. D2: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
6. D2: Toggle `Delete cloud file` setting `ON`.
7. D2: Sync the device in the Profile.
8. D1: Sync the device in the Profile.
9. D1: Play the cloud file and let it finish.
10. D1: Check that the played file is no longer in cloud files.
11. D1: Upload the file to the cloud again.
12. D2: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
13. D2: Toggle `Delete cloud file` setting `OFF`. …

Sync delete cloud files after playing setting

---

gradle/libs.versions.toml

And hilt helpers to 1.1.0
This PR bumps Dagger/Hilt dependencies to complete the `ksp` migration.
CI test should be enough. You can also run and smoke test basic features of the app.

build: bump Dagger/Hilt to 2.50

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Add syncing of the global setting to auto-download on metered networks and auto-download when charging.
> [!note]
> This should be tested with staging. Use `debug` variant instead of `debugProd`.
3. D1: Go to `Profile`/`Settings (cog icon)`/`Auto download`.
4. D1: Toggle `Only on unmetered WiFi` setting `OFF`.
5. D1: Toggle `Only when charging` setting `ON`.
6. D1: Sync the device in the Profile.
7. D2: Sync the device in the Profile.
8. D2: Go to `Profile`/`Settings (cog icon)`/`Auto download`.
9. D2: `Only on unmetered WiFi` setting should be `OFF`.
10. D2: `Only when charging` setting should be `ON`.
11. D2: Toggle `Only when charging` setting `OFF`.
12. …

Sync auto download condition settings

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersHeader.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChaptersTest.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/FeatureFlagWrapper.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/InMemoryFeatureProvider.kt

Part of #1807 
Toggle the chapter selection/deselection.
(This is not the final design)
These are podcasts with chapters you can use to test:
* Upgrade: https://pca.st/upgrade
* Clublife: https://pca.st/rLzZCv
2. Run the app
4. Play any episode with chapters
5. Go to the `Chapters` tab
6. ✅ You should see a header indicating the number of chapters and a button to "Skip chapters"
7. Tap "Skip chapters"
8. ✅ You can now select/deselect chapters
9. Tap "Done"
10. ✅ The number of chapters and hidden chapters should be correctly updated and hidden chapters don't appear on the listing
11. Leave some chapters deselected
13. Go to `Profile` > `Settings` > Beta Features > `Deselect Chapters` and turn it off
14. Kill the app and restart
15. Open `Chapters` tab again
16. ✅ All chapters should be …

Deselect Chapters -  Add skip chapter header

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/view/LockableBottomSheetBehavior.kt
app/src/main/res/layout/activity_main.xml
modules/features/player/src/main/res/layout/fragment_player_container.xml
modules/services/views/src/main/java/com/google/android/material/bottomsheet/ViewPager2AwareBottomSheetBehavior.kt
modules/services/views/src/main/res/values/strings.xml

`BottomSheetBehavior` from the Material library doesn't work with `ViewPager2`. Whenever it attempts to find a nested scrolling child it always grabs the first view that it finds. This means that if there are multiple scrolling pages the other ones can become unresponsive to scroll events.
Closes #1752 
> [!note]
> You need to test this with a Patron account.
> [!note]
> Test this with an episode with a longer description like this one: https://pca.st/episode/c0f9ad0a-cf24-4cd6-a7c4-67591e59ae06
1. Add multiple bookmarks to an episode. You should have enough of them to fill more than 1 screen.
2. Play that episode and open up a player.
3. Switch the active tab to `Bookmarks`.
4. Bookmarks content should be scrollable.
5. You should be able to close the player with a drag motion from the …

Add a bottom sheet behavior compatible with ViewPager2

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Add syncing support for deleting local files after playing them.
3. D1: Add a local file.
4. D2: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
5. D2: Toggle `Delete local file` setting `ON`.
6. D2: Sync the device in the Profile.
7. D1: Sync the device in the Profile.
8. D1: Play a local file and let it finish.
9. D1: Check that the played file is no longer in local files.
10. D1: Add a local file.
11. D2: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
12. D2: Toggle `Delete local file` setting `OFF`.
13. D2: Sync the device in the Profile.
14. D1: Sync the device in the Profile.
15. D1: Play a local file and …

Sync delete local files after playing setting

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AutoDownloadSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Add syncing of the global setting to auto-download up next items when added to the queue
> [!note]
> This should be tested with staging. Use `debug` variant instead of `debugProd`.
3. D1: Go to `Profile`/`Settings (cog icon)`/`Auto download`.
4. D1: Toggle `Episodes added to Up Next` setting `ON`.
5. D1: Sync the device in the Profile.
6. D2: Sync the device in the Profile.
7. D2: Add some episodes to the Up Next.
8. D2: Go to `Profile`/`Downloads`.
9. D2: Notice that just added episodes are there.
10. D2: Go to `Profile`/`Settings (cog icon)`/`Auto download`.
11. D2: Toggle `Episodes added to Up Next` setting `OFF`.
12. D2: Sync the device in the Profile. …

Sync auto download when added to up next setting

---

CHANGELOG.md
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/TimePlayButton.kt

Remembering displayed bookmark timestamp in a composable causes issues with `ViewHolder` and `RecyclerView`. A composable can use previously remembered timestamp in some cases. I'm not sure why it was remembered in the first place but I suspect we wanted to avoid clock cycles for this computation which isn't heavy anyway.
Closes #1824
> [!note]
> Because it is impossible to prove a negative you need to test it and assume correctness with some confidence after enough tries.
See a video in #1824 for more context.
1. Create multiple bookmarks within an episode. It will be helpful to name the bookmark after a creation timestamp.
2. Go to Bookmarks tab of the podcast.
3. Notice timestamps should be correct.
4. Change sorting multiple times.
5. Bookmark timestamp should always correspond to …

Do not remember formatted bookmark timestamp

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt

In #1785 I introduced a bug where an incorrect intent action was assigned to the `Download` notification action.
I'm not adding a changelog entry because the bug was introduced in `7.58` which isn't in production yet.
Closes #1877
1. Have notifications enabled for a podcast.
2. Have a `Download` action available as one of the notification actions.
3. Go to `Profile`/`Settings (cog icon)`/`Developer`.
4. Tap on `Trigger new episode notification` and wait for notification.
5. Open the notification center and tap on `Download` action.
6. The episode should download.

Use a correct intent action when tapping download on notification

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
modules/features/player/src/main/res/layout/adapter_player_header.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt

This PR adds navigation from the `Now Playing` tab to a podcast directly.
Closes #1644 
1. Play an episode without any chapters.
2. Open the player.
3. Tap on the podcast title.
5. The app should navigate to the podcast.
https://github.com/Automattic/pocket-casts-android/assets/30936061/7519db18-77b8-44b3-8322-e540f6c3d140

Add navigation to podcast from the player screen

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Add syncing of the global setting to auto-upload and auto-download cloud files only on unmetered networks.
> [!note]
> This should be tested with staging. Use `debug` variant instead of `debugProd`.
> [!note]
> This should be tested with a Plus account.
3. D1: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
4. D1: Toggle `Only On WiFi` setting `OFF`.
5. D1: Sync the device in the Profile.
6. D2: Sync the device in the Profile.
7. D2: Go to `Profile`/`Files`/`Overflow menu (three dots)`/`File settings`.
8. D2: `Only On WiFi` setting should be `OFF`.
9. D2: Toggle `Only On WiFi` setting `ON`.
10. D2: Sync the device in the Profile.
11. …

Sync cloud auto download and upload on wifi setting

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersHeader.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/onboarding/OnboardingUpgradeSource.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt
modules/services/model/build.gradle.kts
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/to/ChaptersTest.kt
modules/services/sharedtest/build.gradle.kts
modules/services/sharedtest/src/main/java/au/com/shiftyjelly/pocketcasts/sharedtest/InMemoryFeatureFlagRule.kt

Part of: #1807 
This adds purchase flow for the deselect chapters feature.
Prerequisites
- Licence testing account
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14403634/plus.patch)
3. Login with a free license testing account
4. Play an episode with chapters (e.g. https://pca.st/upgrade)
5. Open the player screen and go to `Chapters`
6. ✅ Notice that you see a plus icon next to `Skip chapters` in the header
7. Tap `Skip chapters`
8. ✅ Notice that the upsell flow starts
9. Purchase Plus monthly plan and complete upsell flow
10. ✅ Notice that chapters with checkboxes are shown with a `Done` button at the top
1. Continue from above (logged in as Plus)
2. Apply [this …

Deselect Chapters - Add purchase flow

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/87.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Power.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

- This is part of the Playback Skipping project: Prevent the playback position from skipping while listening to a streaming episode by fully downloading it
- The goal of this PR is to prevent the unexpected playback skipping that our users reported. According to some investigations we did in the past, we believe this is related to ads insertion so our approach to fix this is to implement a cache system by triggering a download when the user begins streaming an episode switching from the streaming episode to the downloaded episode once the download completes.
- Project thread internal reference: `pdeCcb-4ux-p2`
- Playback skipping section from: `pdeCcb-4gS-p2`
- Slack thread: `p1708533677908569-slack-C05RR9P9RAT`
- #1865
> [!note]
> While you are testing, you might encounter the existing …

Configure app to cache episodes when playing

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This disables `Deselect Chapters` remote feature flag so that unfinished work is not enabled when we enable it in the future through the remote feature flag.
I'll enable it again when the feature is ready.

Deselect Chapters - Disable remote feature flag

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersHeader.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
modules/services/localization/src/main/res/values/strings.xml

Part of: #1807 
Updates design for deselecting chapters and adds a few tweaks.
1. Login with a paid account
2. Play any episode with chapters
3. Open the player and go to Chapters
4. Toggle the chapter selection
5. ✅ Compare what you see with the designs in Figma (hHFpI1RtnW4TRb448Q4Don-fi-4383_27080) (notice that checkboxes are still square instead of round which is more of a style for iOS) 
6. Deselect all chapters
7. ✅ On the latest selected chapter you should see a message when you try to deselect
@david-gonzalez-a8c, I've kept checkboxes as squares instead of round to remain consistent with checkboxes at other places. Let us know if you think otherwise.

Deselect chapter - Update design

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivityViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt

The Slumber benefit is available only for:
1. Lifetime subscriptions
2. Yearly subscriptions
This PR changes this behavior in:
1. The Upgrade modal
2. The What's new
- License test account (initially with lifetime access)
1. Update `Settings.WHATS_NEW_VERSION_CODE` to 9117
2. Install release build and launch the app
4. Notice you do not see what's new dialog
5. Login with a Lifetime paid account
6. Update `Settings.WHATS_NEW_VERSION_CODE` to 9118
7. Set `setMinimumFetchIntervalInSeconds` to 5 secs in `FirebaseModule`
8. Reinstall release and launch the app
9. You should see the What's New with promo code
10. Remove Lifetime access from the account
1. Update `Settings.WHATS_NEW_VERSION_CODE` to 9119
2. Reinstall release and launch the app
3. Tap the upgrade button
4. Toggle …

Show slumber studios yearly only

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfFragment.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/ShelfItem.kt

Reporting custom user episodes doesn't make much sense. This PR hides the report flag for user episodes and uses different subtitle depending on the episode that is being currently played.
Closes #1788
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14416815/report.patch).
2. Play a podcast episode.
3. Open the player.
4. Tap on the shelf items overflow menu.
5. Report item should be present.
6. Edit the shelf.
7. You should see `Report` item with `Report inappropriate content` subtitle.
8. No other item should have any subtitles.
9. Move `Report` item to `Shortcut on player` section.
10. Go back to the player.
11. `Report` item should be in the shortcuts.
12. Play a custom file.
13. Open the player.
14. `Report` item should not be present.
15. Tap on the …

Hide report shelf item for user episodes

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/ChaptersViewModelTest.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

Part of: #1807
- Adds tracks
- Fixes skipping issue noticed here: https://github.com/Automattic/pocket-casts-android/pull/1886#pullrequestreview-1903028979
1. Login with a paid account
2. Play any episode with chapters (e.g. https://pca.st/upgrade)
4. Open the player and go to Chapters
5. Toggle the chapter selection on
6. ✅ `Tracked: deselect_chapters_toggled_on` should be tracked
7. Deselect 3 chapters
8. ✅ `deselect_chapters_chapter_deselected` should be tracked with `podcast_uuid` and `episode_uuid`
9. Tap Done
8. ✅ `Tracked: deselect_chapters_toggled_off ["number_of_deselected_chapters": 3]` should be tracked
10. Toggle chapter selection again
11. Select a chapter that was deselected
12. ✅ `deselect_chapters_chapter_selected` should be tracked with `podcast_uuid` and `episode_uuid` …

Deselect Chapters - Tracks

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

Disabling this flag for the next release so we can control it better during the release cycles.

Remove Firebase source for settings sync flag

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
modules/services/images/src/main/res/drawable/ic_tick_circle_filled.xml
modules/services/localization/src/main/res/values/strings.xml

Part of: #1807 | Design:  hHFpI1RtnW4TRb448Q4Don-fi-4383%3A26935 
To keep it consistent with the iOS app (https://github.com/Automattic/pocket-casts-ios/pull/1467), "Skip chapters" feature is shown in the features list even when the upgrade source is skip chapters. This will be addressed separately along with changes for bookmarks and folders. 
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14444007/plus_feature.patch) and install `debugProg` build
2. Login to an account without `Plus`/`Patron`
3. Play any episode with chapters (E.g. from podcast: https://pca.st/upgrade)
4. Open the player and go to `Chapters` 
5. Tap `Skip chapters`
6. ✅ You should see the upgrade landing view with a custom title and `Skip chapters` among the features in the `Plus` feature …

Deselect Chapters - Add to list of features

---

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

I'm targeting `7.59` but it might as well go into `7.60`. It doesn't really matter and depends only on if we manage to merge before we trigger the next release.
> [!note]
> This should be tested with staging. Use `debug` variant instead of `debugProd`.
3. D1: Play an episode with RSS artwork like [this one](https://pca.st/8674dclc).
4. D2: Go to `Profile/`Settings (cog icon)`/`Appearance`.
5. D2: Toggle `Use embedded RSS artwork` setting `OFF`.
6. D2: Sync the device in the Profile.
7. D1: Sync the device in the Profile.
8. D1: Artwork in the mini player should change to the podcast artwork.
9. D2: Toggle `Use embedded RSS artwork` setting `ON`.
10. D2: Sync …

Sync RSS artwork setting

---

modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/89.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Power.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

- This PR reverts #1878
>[!note]
> I am not going to delete the `automatically_cached` column from `podcast_episodes` table on this PR
- Play some episodes and make sure we are not caching them anymore

Revert custom cache system implementation

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

First added in #1848 and then removed in #1897. After checking how Firebase remote config works (internal ref: p1709632000625969-slack-C028JAG44VD) we can safely add it back and control the flag based on release versions.
No need to test it but you can follow steps from #1848 if you want to.

Add remote config for settings sync flag

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadError.kt
modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadErrorTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadResult.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/ResponseValidationResult.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Network.kt

This PR adds more properties to `episode_download_failed` event. I'm targeting `7.59` because the PR has very low risk and it will be better to collect these properties as soon as possible so we can decide how to approach improvements.
Currently, `Inside the FBI` podcast blocks our user agent so we can use it to test `403` error.
1. Open [`Inside the FBI`](https://pca.st/ljzvpptr) podcast.
2. Open any episode details.
3. Try to download the episode.
4. You should see something like below in the logs.
```
🔵 Tracked: episode_download_failed, Properties: {"reason":"status_code","episode_uuid":"bf8e6b69-f5c5-42db-b2e7-ac9bfb820b52","podcast_uuid":"2fbc99a0-8828-0138-ee3a-0acc26574db2","duration":227,"http_status_code":403,"content_type":"text\/html; …
```

Improve episode download failure analytics

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

- This is to implement episodes caching using exoplayer instead of creating our own cache system https://github.com/Automattic/pocket-casts-android/pull/1878
- For reference: https://developer.android.com/media/media3/exoplayer/network-stacks#caching
This is part of #1865
> [!note]
> To test this PR I will to have the local `CACHE_PLAYING_EPISODE` feature flag enabled.
- Do playback regression tests such as play episodes, downloaded episodes and uploaded episodes
- Try to apply playback effects
- During my tests, I observed an improvement when I switched from one episode to another that I had played before, thanks to the cache. 👌
- You can use the device explore see the cache downloaded by Exoplayer. `Android studio -> Device explore -> …

Configure app to cache episodes when playing using Exoplayer Cache

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadError.kt
modules/services/analytics/src/test/kotlin/au/com/shiftyjelly/pocketcasts/analytics/EpisodeDownloadErrorTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadResult.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt

Follow-up to #1912. This aligns episode failure event with the latest design:
* Properties are optional.
* Added `file_size` property.
You can repeat the test from #1912 but code review should be enough.

Align download failure event with the latest design

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
base.gradle
gradle/libs.versions.toml
modules/features/shared/build.gradle.kts
modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/DownloadStatisticsReporter.kt
modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/DownloadStatisticsReporterTest.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsTrackerWrapper.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/EpisodeAnalytics.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/InstantConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/EpisodeDownloadFailureStatistics.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/InstantConverterTest.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/SafeDateTypeConverterTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/Annotations.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

This adds an event for tracking how many stale downloads users have during app startup.
Currently, `Inside the FBI` podcast blocks our user agent so we can use it to test `403` error.
1. Open [`Inside the FBI`](https://pca.st/ljzvpptr) podcast.
2. Try to download some of the episodes.
3. Download episodes from some other podcast.
4. Close the app.
5. Open the app again.
6. You should see something like below in the logs. `failed_download_count` should match the number of episodes that failed to be downloaded. `oldest_failed_download` and `newest_failed_download` should match timestamps of when you tried to download the episodes.
```
🔵 Tracked: episode_downloads_stale, Properties: {"failed_download_count":3,"newest_failed_download":"2024-03-08T09:19:28.451Z","oldest_failed_download":"2024-0 …
```

Add stale downloads analytics event

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/discover/src/main/res/layout/row_carousel_list.xml
modules/features/discover/src/main/res/layout/row_categories_redesign.xml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

- This PR moves the categories from bottom to the top of Discover.
- Hides the search bar from carousel and displays above of categories.
This is part of the categories redesign. You can find references and figma here in our internal reference: `pdeCcb-4tv-p2`.
> [!note]
> This is not the final design. The new design will be implemented in different pull requests to make it easier to review
> [!note]
> This feature is behind the local feature flag `CATEGORIES_REDESIGN`
1. You should see the Discover tab with the current implementation in prod without any change
1. The categories should be displayed at the top below of the search bar
[Screen_recording_20240308_143124.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/3f03f52a-7fc8-435a-ad87-ae868d514ee3)

[Categories Redesign] - Display categories at the top

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
modules/features/player/src/main/res/layout/view_mini_player.xml

This PR migrates the mini player from data binding to view binding.
Please carefully smoke test the mini player. Tap all the buttons, navigate to full player or “up next” queue. Play episodes from different podcasts and observe if the colors of control buttons and seek bars are as expected.

Migrate mini player from data binding

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectHelper.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt

As a part of hack week I had to refactor multi-selection tool to use `Activity` instead of `FragmentManager`. This enables more navigation options from multi-selection context menu. I think it would nice to land it regardless of my project.
Smoke test mult-selection in different contexts: podcast episodes, bookmarks, user files.

Use activity instead of fragment manager for multi-selection

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt
modules/features/player/src/main/res/layout/fragment_notes.xml
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt

This PR migrates the notes/details screen from data binding to view binding.
Please smoke test the notes/details screen on player. Assert the values are displayed as before this PR.

Migrate notes from data binding

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
modules/features/player/src/main/res/layout/fragment_sleep.xml

This PR migrates "sleep" part of player view from data binding to view binding.
Please carefully smoke test the sleep view in player - tap all the buttons, change sleep duration, open-close the dialog, tap "end of episode" etc.

Migrate Sleep from data binding

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt

This increases player release timeout from default `500ms` to `750ms` using remote config field `player_release_time_out_ms`.
Reports in Sentry include a variety of devices with 53% low-end devices in the last 90 days for this error:
[Search for `error.value:"Player release timed out."` in Discover]
It would be interesting to increase player release time-out slightly as suggested [here](https://rb.gy/7hav6r) and monitor to see if it makes any difference. 
1. `setMinimumFetchIntervalInSeconds` to 5L (5 secs) in `FirebaseModule`
2. Add a log statement at the end of `PocketCastsApplication.onCreate()` that prints `settings.getPlayerReleaseTimeOutMs()`
3. Install release build
4. Launch the app
5. ✅ Notice in logs that the release time out is 750.
6. Play a few episodes.  ✅ Notice that they …

Player update release time out

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoriesListRowAdapter.kt

- After https://github.com/Automattic/pocket-casts-android/pull/1930 tapping on categories stopped working when `CATEGORIES_REDESIGN` feature flag is `OFF`. This PR fixes this issue
- With the feature flag OFF try to tap on some category
- The category view should be opened

[Fix] Categories tapping

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/features/podcasts/src/main/res/layout/fragment_episode_container.xml

This PR migrates episode container from data binding to view binding.
Open episode, verify if icons are in the expected color and star icon changes when you tap on it.

Migrate episode container from data binding

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/features/podcasts/src/main/res/layout-land/fragment_episode.xml
modules/features/podcasts/src/main/res/layout/fragment_episode.xml
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt

This PR migrates episode details view from data binding to view binding.
Please smoke test the episode details view. Verify that the same content is displayed as on `main`. Verify both layouts - portrait and landscape.

Migrate episode from data binding

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/res/layout-land/view_podcast_header_top.xml
modules/features/podcasts/src/main/res/layout/adapter_podcast_header.xml
modules/features/podcasts/src/main/res/layout/view_podcast_header_top.xml

This PR migrates top header view on podcast details from data binding to view binding.
Please smoke test the top header on episode details. Check portrait and landscape layouts, verify subscribed vs. not subscribed states, check if icons change if the podcast is/is not in a folder or if it has an alarm.

Migrate podcast header top from data binding

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

This adds a new tag `playedUpTo` while tracking `Illegal playback state encountered`.  In some situations (like playback stuck bufferring) it could be helpful to know the approximate playback position in an episode when the playback error occurs.
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14588445/playback_error.patch) to through a playback error
3. Play the episode >= 10sec for few times
4. ✅ Notice that the new tag is shown in Sentry `playedUpTo` in Tag summary on the right side

Add playedUpTo tag for illegal playback state error

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/res/layout/fragment_podcast.xml

This PR migrates podcast view from data binding to view binding.
Please smoke test podcast fragment. Focus on 3 states: loading, loaded and error. I've used this snippet to help reproducing those 3 states:
<details><summary>PATCH to alternate between loaded and error states on each open of podcast details</summary>
```PATCH
Subject: [PATCH] feat: remove data binding from `fragment_podcast`
---
Index: modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
IDEA …
```

Migrate podcast fragment from data binding

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/90.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/ChapterIndicesConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/ChapterIndices.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/protobuf/src/main/proto/sync_api.proto
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/PodcastEpisodesResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

Part of: #1807 
**Blocked by backend changes**
Adds sync to the chapter deselection (`for podcast episodes only`).
Podcast with chapters you can use to test:
* Upgrade: https://pca.st/upgrade
> [!WARNING]
> Do not merge this PR until Sync API changes are merged
Prerequisite:
- Local Sync API setup
- Checkout Sync API project branch `feature/deselect-chapters-save-update`
- Apply [add_deselected_chapters_to_legacy_sync_record.patch](https://github.com/Automattic/pocket-casts-android/files/14534318/add_deselected_chapters_to_legacy_sync_record.patch) to Sync API project (I'll sync with Leandro to apply these changes)
- Point `SERVER_API_URL` in `pocket-casts-android` `base.gradle` to the local Sync API server
- Paid account
Since we added a new field `deselected_chapters_modified` to db, …

Deselect Chapters - Sync

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChaptersViewModel.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/90.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/ChapterIndicesConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/ChapterIndices.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/UserEpisode.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/protobuf/src/main/proto/sync_api.proto
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SubscribeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/PodcastEpisodesResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

Part of: #1807 
Due to syncing not being available for user files on v1, we won't enable deselecting chapters on user files.
Corresponding iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/1498
Podcast with chapters you can use to test:
* Upgrade: https://pca.st/upgrade
Download an episode with chapters and save it on your computer.
1. Drag and drop the file to your simulator
2. Add it to Profile -> Files
3. Play it
4. Go to the Chapters tab
5. ✅ You should not see the "Skip Chapters" header
6. Play a "podcast episode" that has chapters
7. Go to Chapters tab
8. ✅ You should see the "Skip Chapters" header
https://github.com/Automattic/pocket-casts-android/assets/1405144/55178cbb-2174-43f6-ac27-cb69985f3479

Deselect Chapters - Disable for user files 

---

modules/features/podcasts/build.gradle.kts

Related to #1908 
This tiny PR disables data binding in `podcasts` module.
It's just about build - passed checks from CI makes this PR safe to merge.

Disable data binding in podcasts module

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt

This reduces the recomposition count for the bookmarks page.
- Login as a paid user 
- Play an episode having bookmarks
- Open full-screen player
- Switch to the `Bookmarks` tab
- ✅ Notice in Android Studio Layout Manager that the recomposition count doesn't increment on episode progress changes
- Go to playing episode's Podcast details -> Bookmarks tab
- Update bookmark title for the playing episode bookmark
- ✅ Notice that the title is changed on Player -> Bookmarks tab
N/A

Reduce recomposition count

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/ViewExtensions.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/services/views/build.gradle.kts
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewDataBindings.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/ViewExtensions.kt

This PR migrates removes unused binding adapters and disables data binding in views module
Not needed. This PR affects only build - if CI checks are green, this PR should be good to merge.

Remove unused binding adapters. Disable data binding in views module. 

---

modules/features/search/build.gradle.kts
modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt
modules/features/search/src/main/res/layout/fragment_search.xml

This PR migrates search view from data binding to view binding and disables data binding in whole `search` module.
Please smoke test search. Assert that in search in `Discover` there's higher top padding than in search in `Podcasts` tabs.

Migrate search fragment from data binding. Disable data binding in search module.

---

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/NamedSettings.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

Removes any auto download related settings from the sync process.
I don't think there's a need to test it. Code review should be fine. However, you can test if any settings from the `Auto download` and `Files Settings/Plus features` sections do not sync.

Do not sync any auto download related settings

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewFragment.kt

Tapping `Got It` on "What's New" popup closed the app instead of closing the dialog. This fixes it.
1. Sign in with a Patron account.
2. Install the app with [this patch](https://github.com/Automattic/pocket-casts-android/files/14648532/what-new.patch).
3. Open the app.
4. Tap on `Got It` in the popup.
5. The app should not close.
https://github.com/Automattic/pocket-casts-android/assets/30936061/7d165499-5506-4ab5-bbe6-68a499ebcb52

Fix What's New closing the app

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessTest.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerShowNotesManager.kt

Chapters are available in one of two forms. Either they are directly embedded in show notes, or show notes contain an URL for chapters. Fetching chapters from an URL can take substantial time and we shouldn't wait for them to be fetched before we display show notes.
This PR prepares our show notes processing for chapters by making the processing flow asynchronous.
1. Clear the storage in the app.
2. Enable `Use embedded RSS artwork` setting.
3. Play an episode like [this one](https://pca.st/7oix2d93) with an episode artwork.
4. Episode artwork should be displayed in the app.

Process show notes asynchronously

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/91.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/di/ModelModule.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/DbChapter.kt

This PR prepares database to support chapters podcast tag.
1. Install the app from b9569496f3c6476e67f9aecaebf4778c52b526e6.
2. Sync the app.
3. Install the app from `task/chapters-db` branch.
4. Open the app.
5. It should not crash and you should keep all your synced data.
1. Install the app from `task/chapters-db` branch.
2. Open the app.
3. It should not crash.

Add database model for chapters

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt

Web has alphabetical sort ordering for episodes. We also have it in the code but never used it. This PR adds it to the UI.
Also this PR improves the alphabetical sorting order for English titles and matches it with Web. Instead of doing dummy sorting we exclude `a`, `an`, and `the` articles from sorting. So for example `The Big Bad Wolf` isn't treated as staring with `The` but with `Big`.
1. Subscribe to a podcast.
2. Sort episodes by `A-Z`.
3. Check that the episodes are sorted alphabetically. English articles at the beginning of titles shouldn't be included in sorting.
4. Change sorting order to `Z-A`.
5. Check that the episodes are sorted alphabetically in a reversed order. English articles at the beginning of titles shouldn't be included in sorting.
| Settings | A-Z sorting |
| - | - …

Add alphabetical sort order for podcast episodes

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponse.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

Chapters syncing was broken for the old sync. Modification timestamp was sent as a `Date.toString()` instead of milliseconds.
> [!note]
> Test this with Patron account.
1. Go to `Profile`/`Settings`/`Beta features`.
2. Disable `Settings Sync`.
3. Play an episodes like [this one](https://pca.st/cb8an86i) with chapters.
4. Deselect some chapters.
5. Go back to `Profile` and sync the account.
6. There should be no errors.

Fix chapters syncing

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/chapters/ChapterRow.kt

When chapters were in a selection mode tapping on titles played them instead of toggling selection. This PR changes it.
> [!note]
> Test this with Patron account.
1. Play an episode with chapters like [this one](https://pca.st/cb8an86i).
2. Tap on chapter titles and make sure that the playback switches to them.
3. Go to chapters edit mode.
4. Tap on titles and make sure that selection toggles.
5. Tap on check-boxes and make sure that selection toggles.
https://github.com/Automattic/pocket-casts-android/assets/30936061/6345b5e6-4194-48e9-bc4d-ea9a74ec620b

Toggle chapter selection on title click

---

CHANGELOG.md
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt

Cancellation web link was incorrect.
1. Sign in with an account that has a purchased (not gifted) Plus or Patron.
2. Go `Profile`/`Account`.
3. Tap on `Cancel subscription`.
4. You should be redirected to support page.
https://github.com/Automattic/pocket-casts-android/assets/30936061/14bed6d3-5a13-40bb-a418-3775b883cb61

Fix cancellation info link

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/LargeListRowAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/SmallListRowAdapter.kt

- Make sure we send the existing tracks to the new design
- I also did a small refactor. Changed the visibility of `fromListId` to private
Have the new discover redesign enabled in Beta features
1. Go to Discover
2. Select a Category from the category pill
3. You see `Tracked: discover_category_shown, Properties: {"name":"[category name here]","region":"[region]","id":"[category id]" ...` ✅
4. Clear category filter
5. Tap on `All categories` button to open the category bottom sheet dialog
6. Select a Category
7. You see `Tracked: discover_category_shown, Properties: {"name":"[category name here]","region":"[region]","id":"[category id]" ...` ✅
8. At the top you can see the most popular podcasts filtered by the category that you selected
9. Click on any podcast of this section
10. You see …

Discover redesign - Tracks

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/servers/ShareServerManagerImplTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/list/ListServerManager.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/list/ListServerManagerImpl.kt

Some playlist shared in newsletter could not be opened because of the leading slash character in the path segment.
Internal ref: p1711552213427409-slack-C028JAG44VD
Even though the `7.60` release is coming soon I think it is safe to add this change because it is non-intrusive and it is rather important.
1. Install the app.
2. Enable opening all links in the app (see screenshots).
3. On your device go to [this newsletter](https://mailchi.mp/pocketcasts.com/january-2024).
4. Scroll to the bottom.
5. In the Explorers and Wanderers section tap `Open this playlist`.
6. The app should intercept the link and open the playlist.
| Open links | Playlist |
| - | - |
| ![Screenshot_20240328_082835](https://github.com/Automattic/pocket-casts-android/assets/30936061/30bdfca6-1b86-4f3a-ae1c-9b85eea890fa) …

Sanitize share list URL path segment

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt

- This pull request changes the way we handle cases where both an introductory offer and a trial are available. The app was treating the Plus Yearly subscription as a monthly subscription, which resulted in the offer not being displayed.
- Currently we have `intro offer` activated and `trial` activated.
- If the `INTRO_PLUS_OFFER_ENABLED` feature flag is enabled we should display the intro offer
- The intro offer is not available for India, South Africa and Brazil
> [!note]
> I always have **a lot of cache** issues when I am testing subscriptions, so even If I clear the play store cache, reinstall pocket casts app I still can't see the offer after I updated it in Play Store.
- Apply [subscription_test.patch](https://github.com/Automattic/pocket-casts-android/files/14779592/subscription_tes …

Filter offers when have more than one available

---

gradle_build_cache.gradle.kts
settings.gradle.kts

This PR enables Gradle Remote Build Cache on CI, to reduce build times.
Not needed - as PR is built on CI, this change is safe to merge.

build: apply Gradle Enterprise plugin. Enable remote build cache on CI

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt
modules/services/localization/src/main/res/values/strings.xml
version.properties

Do not display "Skip Chapters" under Patron and change copies to "Preselect chapters".
This pull request is to match the [recent iOS change.](https://github.com/Automattic/pocket-casts-ios/pull/1588)

[Deselect Chapters] Remove it from Patron and update copies

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/entity/PodcastTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/92.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/update/SyncUpdateResponseParser.kt

Our app's logic relies on home folder UUID being `null` when sorting or doing other operations. However, there are way to update podcasts with the home folder UUID. I changed the behavior of `Podcast` entity to prevent this. Ideally, I'd prefer to make the property not nullable but there's too much internal logic assuming that `null == homeFolderUuid`. Trying to change it in this PR would probably introduce more bugs than not.
1. Set podcast sorting order by `Episode release date`.
2. Disable `Sync settings` feature flag.
3. Subscribe to a podcast.
4. Check that the podcast is displayed in the `Podcasts` tab.
5. Refresh the profile.
6. Enable `Sync settings` feature flag.
7. Refresh the profile.
8. The subscribed podcast should be displayed in the `Podcasts` tab.

Do not allow to set podcast folder UUID to home folder UUID

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt

This adds a bookmarks menu in the Profile screen and displays an empty bookmarks view on tap.
It is added behind a local feature flag.
2. Go to the Profile tab
3. ✅ Notice that there's a bookmarks menu
4. Tap on it
5. ✅ Notice that an empty bookmarks screen is opened
6. ✅ Notice that `profile_bookmarks_shown` is shown in logs
7. Go back either by tapping the back arrow or swiping gesture
8. ✅ Notice that the screen closes
9. Go to Profile -> Settings -> Beta features
10. Disable Account bookmarks feature
11. Restart the app
12. Go to the Profile tab
13. ✅ Notice that there's no bookmarks menu

Profile Bookmarks - Add menu and show empty screen

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/core/ui/widget/PodcastWidget.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidgetReceiver.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetReceiver.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/SmallPlayerWidgetReceiver.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/di/WidgetEntryPoint.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

This PR adds installation widget events. All other events like play/pause are already tracked in the app by using `SourceView.WIDGET_PLAYER_X` sources.
1. Add widget of any type to the home screen.
2. You should see in the logs an analytics event. `🔵 Tracked: widget_installed, Properties: {"widget_type":"player_small"`
3. Remove that widget from the home screen.
4. You should see in the logs an analytics event. `🔵 Tracked: widget_uninstalled, Properties: {"widget_type":"player_small"`.
5. Check that only the first widget of a particular type added to the home screen triggers `widget_installed` event, and only the last widget of a particular type removed from the home screen triggers `widget_uninstalled` event.

Add widget installation analytics

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastListFragment.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DiscoverModel.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/DisplayStyle.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/ExpandedStyle.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListWebService.kt

- [Backend is now returning](https://github.com/Automattic/pocket-casts-node-server/pull/626) categories at the top and the most popular categories id, so we don't need to move categories at the top and sort the categories using hardcoded id. 
- This PR removes the hardcoded category sort -> 3e26ebca5b4d85277b8fb6042f3d12badb48d8dc
- Also removes the hardcoded category position update -> 62a12e28107cea233d71b5d0f34b72c5958b9f47
- Go to `Beta Features` -> Make sure `Podcasts by category shown in discover view` is enabled. In case it's not enabled you should toggle this feature `on` and restart the app
- Go to `Discover`
- Make sure that categories are displayed at the top ✅
- Make sure you have `All categories` and then you see `True crime`, `Comedy`, `Society & Culture`, `History`, …

Remove hardcoded categories setup

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/entity/ChapterIndicesTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt

This prevents unnecessary playback state updates for chapter indices under two conditions:
1. When chapters in playback state for the current episode are not yet loaded
2. When before and after deselected chapter indices are the same but in a different order
1. Login with Patron account
3. Play an episode with chapters
4. Deselect a chapter 
5. Sync deselected chapter indices by tapping Refresh now in settings
6. Restart the app (so that the episode with chapters remains selected but chapters are not loaded for it)
7. Put a breakpoint at line 894 and 902 in MainActivity
8. Go to Profile and tap Refresh now
9. Notice that the breakpoint at 894 is hit but not at line 902
I added equality tests in  `ChapterIndicesTest` and noticed that chapter indices with the same but unordered items were …

Fix playback state chapter indices update

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarkAction.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBookmarksHelper.kt

This adds a share option for bookmarks.
- Start the app using a user with a Patron Account on a device
- If you still don't have any Bookmarks please create some on the account on multiple podcasts
- Go a podcast with bookmarks
- Open Bookmarks tab for the podcast
- Tap on the options button
- Select one bookmark
- Tap on Share
- Copy the link
- Open the link that you copied from the other device on device browser
- Tap on Open In Pocket Casts
- Check that the link is opened on the correct Podcast -> Episode -> Time location
- Repeat the test above on the other locations where Bookmarks list are shown
- Player full screen, tab bookmarks
- Episode detail, tab bookmarks  
https://github.com/Automattic/pocket-casts-android/assets/1405144/72ccd3dd-6f7b-4167-af4e-7138ce2fcd7f

Bookmark share

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
modules/features/discover/src/main/res/drawable/category_pill_background.xml
modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
modules/features/discover/src/main/res/layout/row_category_pills.xml

- It just updates both text and background color for search bar and list of category pills
- Internal slack reference: pocket-casts-design p1712595053116089
- Play around the themes and see how they look like in discover view for search bar and category pills menu
| Light | Dark | Rosé |
|-------|------|------|
| <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/0be76404-b75d-44e2-84cc-d6c18db93284" height="400"> | <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/96ff932c-35e3-4d4f-a612-ab76dfefe918" height="400"> | <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/69c56631-539f-4024-b0da-0fde545101f6" height="400"> |
| Indigo | Extra Dark | Dark Contrast |
|-------|------|------|
| <img …

Update search bar colors for new category design

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt

This fixes the play button sometimes showing incorrect drawable in the mini-player. 
Fixes #2017
2. Tap the play button in the mini-player a few times
3. Notice that the play button displays a drawable that matches the actual play state
https://github.com/Automattic/pocket-casts-android/assets/1405144/1bd4faed-428b-4e3d-8ccf-6c0ec46ec6c7

Fix play button drawable update

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksSortByDialog.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeListAdapter.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UserEpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/helper/ProfileBookmark.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Bookmark.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/model/BookmarksSortTypeForProfile.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/UserEpisodeManager.kt

This displays bookmarks on the Profile screen and allows sorting them.
1. Start the app with an user that has Plus or Patron active
3. Go to profile
4. Scroll down and check if you see a Bookmarks option
5. Tap on Bookmarks
6. Check if the list of your bookmarks is seen ( if you never set a bookmark you should see an empty view that says how to set it)
7. Tap the bookmark play button and check if it starts playing the bookmark episode at the bookmark timestamp
8. Check if sort option works
- Tap on the more button on the top right
- Tap on Sort By
- Switch between different sort orders and check if it works correctly
9. Check if delete works
- Tap on more button again
- Tap on select bookmarks
- Select some bookmarks
- Tap on the delete icon ( trash button)
- Confirm the deletion
- Check …

Profile bookmarks - Display & Sort

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt

This PR makes `ChaptersManager` a single source of truth for chapters. Previously we juggled between embedded and remote chapters during playback. Now chapters are always saved to the database and database provides it to the playback manager.
Closes #2018 
Test chapters and chapters selection. You should be able to select chapters, skip chapters, and so on.

Save embedded chapters in the database

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncSettingsTask.kt

This PR addresses two things.
1. Update local setting values only if remote timestamp is greater than the local one. Previously it was greater or equal.
2. Use `EPOCH +1 millisecond` as a default timestamp when syncing. This is to prevent a scenario where users sync their devices with settings changed before we started tracking modification timestamp, and then they switch to a new device. This way we compare local `EPOCH` to `EPOCH +1` which will update.
Do some regressions tests for named settings syncing.

 Update settings only if remote timestamp is greater than the local one

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

This PR addresses couple of things.
1. Update podcast settings **only if** remote timestamp is greater than the local one. Previously we updated it always. I'm not sure why it was designed this way. But new approach follows the pattern that we have for named settings.
2. Use `EPOCH +1` logic for updates. This is described in #2035.
3. Fix some of the syncing bugs.
1. `showArchivedModified` was updating to `showNotificationsModified`.
2. `autoArchive` was sending modification timestamp for `overrideGlobalEffects`.
Do some regression tests for syncing podcast settings. Focus especially on trim mode, auto archive, and showing archived.

Update podcast setting only if remote timestamp is greater than local one

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/NoBookmarksInSearchView.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/search/BookmarkSearchHandler.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/search/BookmarkSearchHandlerTest.kt
modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModelTest.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt

This adds search to the profile bookmarks screen.
1. Start the app with a user that has Plus or Patron active and a few bookmarks
3. Go to profile
4. Scroll down and check if you see a Bookmarks option
5. Tap on Bookmarks
6. Notice that the screen now has a search field
7. Search for a bookmark or episode title 
8. Notice that search results are filtered based on searched term or display a no bookmark view
https://github.com/Automattic/pocket-casts-android/assets/1405144/f7209ff9-86b7-4b88-b3ac-00b5fcd8a226

Profile bookmarks - Add search

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PocketCastsLogo.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
modules/features/widgets/src/main/res/xml/large_player_widget.xml
modules/services/images/src/main/res/drawable/ic_widget_play.xml
modules/services/images/src/main/res/drawable/ic_widget_skip_back.xml
modules/services/images/src/main/res/drawable/ic_widget_skip_forward.xml

Align design with most of the feedback. Internal ref: pdeCcb-4VF-p2#comment-3893
1. Increases padding on the widgets.
2. Uses different icon set for play, skip back, and skip forward.
3. Makes buttons and Pocket Casts logo smaller.
4. Makes text fonts smaller.
5. Makes titles for queued episodes two lines high.
6. Add padding to the top and the bottom of the large player controls.
It doesn't make buttons background white, and it doesn't make Pocket Casts logo lines white. Adding it wouldn't work with dynamic themes and I'm waiting for the feedback on it (see the internal ref).
It also doesn't implement empty states yet as I'm waiting for the feedback on this as well.
Add widgets to your home screen and inspect the designs. Internal ref: Lkt7fuf9Nq3XvfAFPCfpTD-fi-1044_7170

Align widgets with design feedback

---

fastlane/Fastfile

Instrumented tests stopped running after the `Nexus5` emulator was deprecated from Firebase, causing the CI step to fail. This PR updates the emulator used in Firebase tests as well as the SDK version so that tests can run.
| Before | 
|--------|
| <img width="1152" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/42008628/7b66e25e-b99d-4d07-8706-89fac1f25033"> |
| <img width="1080" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/42008628/cb01e1d3-180a-4d13-9b44-f5fba82532b8"> | 
| After | 
|--------|
| <img width="1152" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/42008628/13af5ed7-9771-4c22-a10f-51023edbcfe0"> |
| <img width="1080" alt="image" src="https://github.com/Automattic/pocket-casts-android/assets/ …

Update Firebase emulator model

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/search/BookmarkSearchHandler.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt

This trims the search term before setting it to search handler.
1. Start the app with a user that has Plus or Patron active and a few bookmarks
2. Go to profile
3. Scroll down and tap on Bookmarks
4. Notice that the screen now has a search field
5. Search for a bookmark or episode title with spaces before and at the end
6. Notice that spaces are ignored during search
https://github.com/Automattic/pocket-casts-android/assets/1405144/decb233a-1fe1-4f80-a0e1-c881a1e7a6a6

Trim search term 

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
modules/features/player/src/main/res/layout-land/adapter_player_header.xml

Landscape player layout was missing chapter artwork, podcast title, and was mishandling video playback. This PR fixes this.
Closes #2015
Test the player in landscape mode
| Old episode | New episode |
| - | - |
| ![old-episode](https://github.com/Automattic/pocket-casts-android/assets/30936061/8fa97c71-eabe-46a9-a9b6-df725241c526) | ![new-episode](https://github.com/Automattic/pocket-casts-android/assets/30936061/954535f2-3f6c-4d74-90a9-d093fe5cac96) |
| Old chapters | New chapters |
| - | - |
| ![old-chapter](https://github.com/Automattic/pocket-casts-android/assets/30936061/812b32a7-a281-4da3-97dd-8ad724a5348d) | ![Screenshot_20240412_085803](https://github.com/Automattic/pocket-casts-android/assets/30936061/d87837db-657a-4612-9021-28a8459c9e62) |
| Old video | New video |
| - | - |
| …

Improve landscape player layout

---

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This removes local feature flag for profile bookmarks.
1. Install release build
2. Login with a paid account having few bookmarks
3. Go to the Profile tab
4. ✅ Notice that there's a bookmarks menu
5. Tap on it
6. ✅ Notice that account's all bookmarks are shown

Remove feature flag for profile bookmarks

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt

This PR implements a mechanism to restart the sleep timer whenever the user restarts playback within 5 minutes.
- The sleep timer will restart with the same configuration as before same time initially set or end of episode
- If playing after more than 5 minutes, the sleep timer should not restart
While I was working on this, I have found two issues that I reported here:
- https://github.com/Automattic/pocket-casts-android/issues/2045
- https://github.com/Automattic/pocket-casts-android/issues/2047
1. Run the app
2. Add 5 to 10 podcasts to your Up Next
3. Play something
4. Open the full player, tap the sleep timer icon (zZz), select X minutes (You can select 1 minute using the last option)
5. After X minutes the playback should stop
6. Tap play again
7. ✅ The sleep timer should restart …

Sleep Timer: automatically restart if playback is resumed within 5 minutes

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
fastlane/Fastfile
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImplTest.kt

This is a hotfix that accounts for a possibility that a chapter can have 0 duration.
I cherry picked 90d55e3f8c24bb080456ee372bcc108bcb1d9f79 to fix this. Otherwise I'd have to make the same fix in two places and fight merging conflicts. This way we have a fix in a single place that is covered by unit tests.
When doing the review you should focus on e2f9419b0883d1bc802af2b9ef2cd4622acaf0d7 and 4da7135e96cd900efdcfe8ecfa2676970f092026.
Closes #2059
Closes #2056
1. Play an episode from https://pca.st/v0UDSh.
2. It should not crash.
3. Check that you can interact with chapters. Chapters are gibberish. They come from the episode metadata. Maybe it is a bug in our chapters processing but this is what we currently get from the `EpisodeFileMetadata`.
1. Subscribe to a podcast with chapters from …

Fix crash when chapters have 0 length durations

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/preferences/UserSettingTest.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/UserSetting.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

There are issues on iOS when using `epoch +1 millisecond` as a default sync timestamps. This PR changes it to `epoch +1 second` to align with iOS.
No need to test it. CI checks and automated tests are enough.

Use epoch +1 second as a default sync timestamp

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerReceiver.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt

- This PR adds the ability to restart the sleep timer If a playback is going on with a timer and the user shakes the device
- This works with both foreground and background app.
- This applies for when the sleep timer was set with a time
1. Run the app
2. Play something
3. Open the full player, tap the sleep timer icon (zZz), select X minutes (You can select 1 minute using the last option)
4. Shake your device
5. ✅ The sleep timer should restart with X minutes you set
6. ✅ You should see the toast with `Sleep timer restarted after device shake` message
7. ✅ Ensure `🔵 Tracked: player_sleep_timer_restarted ["time": "shaking_phone"]` is tracked
1. Run the app
2. Play something
3. Open the full player, tap the sleep timer icon (zZz), select X minutes (You can select 1 minute using the last …

Sleep timer: Restart timer when shaking phone

---

fastlane/Fastfile

As discussed in Slack in p1713279787498399/1713274980.521569-slack-CC7L49W13
When running the `new_beta_release` lane, the lane started by checking out `main` then printing a prompt based on the values of the `versions.properties` file's state in `main`. While in practice the code would bump the version in the version file based on the the values of the version file's state in the `release/*` branch where the bump will happen.
While most of the time those two states of the version file are the same (because we usually back-merge `release/*` into `main` after every new beta), this can lead to inconsistencies and misleading prompt, in particular:
- If, during the previous beta, the PR back-merging `release/*` to `main` was not merged
- Or If there has been a hotfix happening, in which case …

[Tooling] Fix `new_beta_release` prompt, which can be misleading after a hotfix

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeContainerFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt

`getLong()` on a bundle returns `0` if the argument is missing. This causes playback reset when `EpisodeContainerFragment` is opened. Ideally we wouldn't be using primitives in bundles and switch to `Parcelable` to have a single argument property like here.
https://github.com/Automattic/pocket-casts-android/blob/7367e4b6624fe654058baaeb2ff01566811bda2b/modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/PodcastSelectFragment.kt#L280-L285
However I don't want to introduce too large of a change to fix this bug.
The easiest way to test it is through a widget.
1. Add a medium widget to your home screen.
2. Play an episode.
3. Tap on an image in the widget.
4. The playback should not reset.

Do not take timestamp argument if it is missing

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt

When large player widget was too big for the current screen it was clipped both at the top and the bottom. While we can't control the grid size that will be applied by the system due to different screen sizes we can control content of the widget. This PR pushes the content to the bottom so only queue part is initially clipped if anything must be clipped.
> [!note]
> Use a device that would clip content vertically. You can use a small screen device or scale your device screen size. I tested it with this emulator:
> `Resolution (px): 720 x 1280`
> `Resolution (dp): 360 x 640`
1. Add a large widget and noticed that it is clipped only at the bottom.
2. Test that you can resize the widget.
| Old | New |
| - | - |
| ![Screenshot_20240417_115539](https://github.com/Automattic/pocket-casts-android …

Push large widget content to the bottom

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

- This implements audio fade out when we have a sleep time set
- The fade out starts when sleep timer has 5 seconds left
- This does not apply to end of episode sleep timer case
1. Run the app
2. Play something
3. Open the full player, tap the sleep timer icon (zZz), select X minutes (You can select 1 minute using the last option)
4. Wait until sleep timer has 5 seconds left
5. ✅ Audio should start fading out until end episode
1. Run the app
2. Play something
3. Open the full player, tap the sleep timer icon (zZz), select end of episode
4. Seek episode to almost the end
5. Wait for the episode end
6. ✅ You should not hear any fade out
[Screen_recording_20240416_140608.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/94191fd3-4045-410a-b5f0-36d1e94efff5)
cc: …

Sleep timer: Start fading out audio when sleep timer has 5 seconds left

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt

- [Automatic sleep timer](https://github.com/Automattic/pocket-casts-android/pull/2048) was not working when the sleep timer dialog was open
- This is because we were cancel the sleep timer restart variables when cleaning up sleep timer in `timeLeftInSecs`. We should only cancel sleep timer restart when we actual canceled the sleep timer
1. Run the app
2. Play something
3. Open the full player, tap the sleep timer icon (zZz), select X minutes (You can select 1 minute using the last option)
4. Tap on sleep timer icon (zZz) again to open the sleep timer dialog
5. Wait for the sleep timer to finish with the dialog open
6. Close the sleep timer dialog and play the episode again right after that
7. ✅ The sleep timer should restart with X minutes you set
- If you want to smoke test the whole …

Sleep Timer: Fix automatic restart when sleep timer dialog is open

---

modules/features/widgets/src/main/res/xml/medium_player_widget.xml

In my testing `3x1` medium widget didn't look well. The playback controls were always cutoff at the end. However we had this report (p1713353378687969-slack-C02A333D8LQ) from a user. Apparently `3x1` looks nice on their device. See the screenshot below.
1. Add the medium widget to you home screen.
2. The widget should be added as 4x1 or anything that doesn't cut the content off.
3. You should be able to resize it horizontally. It is ok if it is cut off. On some devices it won't be.

Allow medium widget to be resized to 3x1

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

- This PR fixes: End of episode (sleep timer) option was not being preserved after switching to another episode from Up Next
Fixes #2047
1. Add at least two episodes to Up Next
2. Go Settings -> General -> Have `Play up next episode on tap` enabled
3. Set `End of Episode` in `Sleep timer`
4. Open the Sleep timer again
5. You will see the `End of episode` option is set ✅
6. Open Up next queue
7. Tap on another episode
8. Open the Sleep timer again
9. You should see the `End of episode` option is set ✅

Fix: End of episode option is not being preserved when switching to another episode from Up Next

---

modules/features/discover/src/main/res/layout/row_most_popular_podcasts.xml

Adding padding top in most popular section that was missing
1. Have redesign beta feature enabled
3. Select a category
4. Check if the most popular in [category] has padding top
|<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/fd70829a-74a0-40fe-80db-185187bbf9a9" width=400> |<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/85e6365a-d9b5-46dc-802b-166e3b66e407" width=400> |

Fix: Most Popular section missing padding top

---

modules/services/repositories/src/main/AndroidManifest.xml
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDrawerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt

While removing old widget I accidentally removed provider for images from the manifest. 0db5ee4e8ce14516e2bedfa7236ee46a36d4499e brings it back which fixes images low resolution.
2362845cf6c1f2b9762282e0ea2330a29fc01ef1 improves media notification center by making it react dynamically to `Use episode artwork` setting. Previously it was updated only during play/pause cycle. Now it reacts to settings toggle.
Closes #2087
1. Play any episode.
2. Look at Media Notification.
3. Image should not be low resolution.
1. Play any episode with an episode cover.
2. Toggle `Use episode artwork` setting in the settings.
3. Check that Media Notification reacts to the setting.

Fix media center low resolution image preview

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/93.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/Chapters.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/DbChapter.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/ChapterManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shownotes/ShowNotesProcessor.kt

This PR changes embedded chapters to be prioritized over remote ones. This is needed because ads injection can make remote chapter timestamps invalid.
Closes #2093 
1. Fresh install the app from 06b94680454297485ed455f091bc4d5291fedd9a.
2. Play [this episode](https://pca.st/vg3xvczk) until you see chapters.
3. Update the app with changes from `task/prioritize-embedded-chapters`.
4. Open the app.
5. Run `SELECT * FROM episode_chapters WHERE episode_uuid IS 'dc063c76-b585-43c2-80b2-6413fa334a30'` in Database Inspector. You should see chapters with `is_embedded` equal to `0`.
6. Play the episode from the 2nd step.
7. After a while query from 6th step should show that `is_embedded` is equal to `1`.
8. Make sure that the you can see chapters and some of the chapters have custom artwork.

Prioritize embedded chapters

---

modules/features/widgets/src/debug/AndroidManifest.xml
modules/features/widgets/src/debugProd/AndroidManifest.xml
modules/features/widgets/src/main/AndroidManifest.xml

For easier widgets development include them by default in debug builds.
1. Check that new widgets are not available in the `release` variant.
2. Check that new widgets are available in the `debug` variant.
3. Check that new widgets are available in the `debugProd` variant.

Include widgets in debug builds

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/94.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/TrendingPodcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt

We need to save trending podcasts in the database for the top secret project to display them in the UI.
Internal ref: pdeCcb-520-p2
2. Go to trending.
3. Query `SELECT * FROM trending_podcasts` in the App Inspection tool.
4. You should see some podcasts.

Save trending podcasts in the database

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
modules/features/discover/src/main/res/layout/item_most_popular_podcasts.xml
modules/features/discover/src/main/res/layout/row_category_pills.xml

- Adds subscribe button to podcasts listed in most popular section
- Removes the header background color in discover view
- Updates category cancel pill menu format 
1. Run the app
3. ✅ Header must be white for default theme
4. Select a category
5. ✅ You should see the subscribe button in the podcast from most popular section
6. Tap on subscribe button
7. ✅ You should be subscribed to this podcast
|<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/d2deda80-dcf7-454e-9be0-4852294a5288" width="300"> |<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/ac2b2a22-2f7b-40c5-9deb-0014fd5e05f5" width="300"> | 
| Light | Dark |
|<img …

Add subscribe button to most popular section and search bar color updates

---

Gemfile
Gemfile.lock

Update `release-toolkit` from `10.0.0` to `11.0.1`, in particular to get the fix for `To call another action from an action use 'other_action.git_submodule_update' instead` error.
Same as https://github.com/Automattic/pocket-casts-android/pull/2055, but targeting `release/7.62` branch.

[Tooling] Update `release-toolkit` to `11.0.1` in `release/7.62` branch

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt

Account for 192cd483900eff8558aac0c3188d5006a115ce6c during migration.
`7.63-rc-1` will use `9224` which means that `7.63` will be at least `9225`.
Internal ref: p1714157442745779/1714153209.768229-slack-CC7L49W13
Verify in Play Console that `7.62` uses `9223` version code.

Account for updated prod version during settings migration

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/res/layout/fragment_bookmarks_container.xml

This fixes toolbar/ title colors for profile bookmarks screen.
1. Login using a paid account having a few bookmarks for podcasts and user files
3. Go to `Profile` and tap `Bookmarks`
5. ✅ Notice that the title and navigation icon are shown properly for the bookmark screen
6. Go to `Profile` -> `Files` and tap a user file
4. Tap Bookmarks from the bottom sheet dialog
8. ✅ Notice that the title and navigation icon are shown properly for the bookmark screen
** Status bar icon color is incorrect for the light-themed bookmarks container for cloud files. It is tracked under a separate issue https://github.com/Automattic/pocket-casts-android/issues/2127.

Fix toolbar and title colors for profile bookmarks

---

CHANGELOG.md
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt

Sorting by `Episode release date` did not account for podcasts that have `folder_uuid` set but folders with that ID no longer exist. I'm not sure how such a state can occur. Possibly some syncing issue or non-transactional updates that fail or are interrupted. Regardless, we should make sure that all podcasts are visible.
We do a similar thing for other types of sorting here so it only makes sense to do it for the release date.
https://github.com/Automattic/pocket-casts-android/blob/8275b2d3c006df19ebfcd7eabc345235bbc94967/modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastsViewModel.kt#L149-L152
Bug ref: https://pocketcastsbeta.slack.com/archives/C013F9S9C2W/p1714234988836729
2. Run `UPDATE podcasts SET folder_uuid = …

Include podcasts with corrupted folders when sorting by release date

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
app/src/main/res/layout/activity_main.xml
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksContainerFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudSettingsFragment.kt
modules/features/profile/src/main/res/layout/fragment_account_details.xml
modules/features/profile/src/main/res/layout/fragment_profile.xml
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AutoDownloadSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/ManualCleanupFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/CloseOnTabSwitch.kt
modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
modules/services/ui/src/main/res/transition/slide_in.xml
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/extensions/Toolbar.kt

Part of: #2081 
This updates profile navigation from the profile menu.
2. Tap Profile menu
3. ✅ Notice that Profile screen opens with a close button
4. Tap on close button
5. ✅ Notice that Profile screen is closed
6. Re open Profile screen
7. Navigate to another screen from Profile screen
8.  ✅ Notice fragments are added as follows:
- Added over tabs
- Account Details
- Help & feedback
- Setttings
- Stats
- Added behind tabs so that playing an episode from these screen is reflected on the mini player
- Downloads
- Files
- Starred
- Bookmarks
These are removed from back stack on switching to another tab to prevent weired state noticed in https://github.com/Automattic/pocket-casts-android/pull/2102#pullrequestreview-2019549512.
1. Turn off `Show Up Next in tab bar` feature …

Update profile navigation

---

CHANGELOG.md
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/AddFileActivity.kt

While unifying artwork loading in #1987 I accidentally changed the value whether artwork should be extracted from files when adding them. This fixes it.
Closes #2122
1. Add a file with an embedded artwork like [this one](https://www.podtrac.com/pts/redirect.mp3/traffic.libsyn.com/secure/upgrade/upgrade418.mp3).
2. Make sure that the artwork is visible when file is being added.
3. File in the files list should show the artwork.
| Adding | Listing |
| - | - |
| ![Screenshot_20240428-205609](https://github.com/Automattic/pocket-casts-android/assets/30936061/1c52dbd4-059c-4b70-9e25-3f9aa3ac6944) | ![Screenshot_20240428-205601](https://github.com/Automattic/pocket-casts-android/assets/30936061/caebb2fd-0d29-40f9-9216-17dcc1646a04) |

Extract embedded image from a file when uploading it

---

CHANGELOG.md
modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeListAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/EpisodeViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/UserEpisodeViewHolder.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/cloud/CloudFilesFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AppearanceSettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/EpisodeArtworkConfigurationFragment.kt
modules/features/settings/src/main/res/layout/fragment_settings_appearance.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/Settings.kt
modules/services/localization/src/main/res/values/strings.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/FilesScreen.kt
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/ui/downloads/DownloadsScreen.kt

Add an advances user setting for controlling episode artwork.
Internal ref: p1714032295029379-slack-C05RR9P9RAT
1. Go to appearance settings.
2. Go to `Advanced episode artwork settings`.
3. Enable the setting.
4. Disable all customizations.
5. Check one by one that each customization enables episode artwork in its context.
| Settings | Advanced settings |
| - | - |
| ![Screenshot_20240425-162108](https://github.com/Automattic/pocket-casts-android/assets/30936061/51e9affb-0dd5-4c44-ac5b-e6c6c5931785) | ![Screenshot_20240425-162115](https://github.com/Automattic/pocket-casts-android/assets/30936061/6c290feb-7467-4727-bb0f-3f6bb9630e6e) |

Toggle episode artwork in different sections

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/BookmarksViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt

This fixes bookmarks episode title display. Episode title should not be displayed for Episode and Player bookmarks screens where bookmarks are shown only for the selected episode.
1. Login with a paid account having a few bookmarks
2. Open bookmarks from different sources: `Episode`, `Player`, `Podcast` and `Profile`
3. ✅  Notice that the episode title is shown for Podcast and Profile bookmarks
4. ✅ Notice that the episode title is not shown for Episode and Player bookmarks
Episode | Player | Podcast | Profile
---|---|----|----

Fix bookmarks episode title display

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/NonScalingText.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PocketCastsLogo.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt
modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_opaque.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_oneline_transparent.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_opaque.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_bold_dynamic_twolines_transparent.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_opaque.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_oneline_transparent.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_opaque.xml
modules/features/widgets/src/main/res/layout/non_scaling_text_regular_dynamic_twolines_transparent.xml
modules/features/widgets/src/main/res/values/colors.xml

This PR changes new widgets theming from primary to secondary colors. Our custom dark theme uses a bit different red color for logo and darker background for buttons but I aligned this with David.
I've also simplified handling colors by introducing `WidgetTheme` type.
Internal ref: Lkt7fuf9Nq3XvfAFPCfpTD-fi-1422_1732
1. Add widgets to the home screen.
2. Test them with different themes and wallpapers.
| Non-dynamic Light | Non-dynamic dark | Dynamic light | Dynamic dark |
| ![empty-custom-light](https://github.com/Automattic/pocket-casts-android/assets/30936061/96f2ddf0-338f-48e0-aa17-a34f1a687dff) | ![empty-custom-dark](https://github.com/Automattic/pocket-casts-android/assets/30936061/14a778b5-5c97-470c-95a7-064b157fdf43) | …

Update widget themes to use secondary colors

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/GlanceModifierExtensions.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/MediumPlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlayButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackControls.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/RounderCornerBox.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipBackButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SkipForwardButton.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt

Android below SDK 31 does not support rounding corners from the Kotlin code. It has to be done with XML. I added `RounderCornerBox` composable that decides whether to handle it from the code or from the XML.
1. Install the app on a device below SDK 31.
2. Add widgets to the home screen.
3. They should have rounded corners.
Do regression tests of widgets on devices with different SDK versions.
| - | - |
| ![before](https://github.com/Automattic/pocket-casts-android/assets/30936061/e5955307-9592-47ce-bc6b-6fbf66608ada) | ![after](https://github.com/Automattic/pocket-casts-android/assets/30936061/8412ac83-9c40-4a06-8462-1a768c3e59d5) |

Add rounded corners on Android SDK < 31

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/LargePlayerWidget.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
modules/features/widgets/src/main/res/xml/large_player_widget.xml

Make large widget queue content resize to the available height.
Do regression tests of large widget with different widget sizes and different queue states.
https://github.com/Automattic/pocket-casts-android/assets/30936061/f3bd0c47-e8ae-49da-a847-4958695af348

Resize large widget to available height

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/PlaybackControls.kt

Reverts order of buttons in playback controls.
1. Add large and medium widgets.
2. Check that the order of playback control buttons is: `skip back`, `play/pause`, `skip forward`.

Revert order of widget playback buttons

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/res/layout/row_category_ad.xml

- This PR sends `discover_list_impression ` and `discover_list_podcast_tap ` to Firebase
- Also adds subscribe button to category ad 
```
- discover_list_impression with the parameter “list_id”. When the user views the list on the screen (it must be visible to the user).
- discover_list_podcast_tap with parameters “list_id” and “podcast_uuid”. When a podcast in a discover list is tapped.
``` 
> [!NOTE]  
> `discover_list_impression` is tracked once per session following the existing logic 
> [!IMPORTANT]  
> Currently `Sports` category has an ad set in Stagging. These ads are not available to every category selected
1. Run the app
2. Select `Sports` category
3. ✅ Ensure 🔵 Tracked: `discover_category_shown, Properties: {"name":"Sports","region":"your_region","id":14,` is tracked
4. ✅ …

Fix: Send ads event to firebase and Add subscribe button to category ad

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt

Need to take into account `7.62.1` version code bump for artwork settings migration.
Verify in Play Console that `7.62.1` uses `9225` version code.

Account for 7.62.1 when migrating artwork settings

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
modules/features/podcasts/src/main/res/menu/podcasts_menu.xml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This adds a feature flag for the search bar in the Podcasts tab.
1. Open the Podcasts tab
2. ✅ Notice that the search bar is visible below the toolbar
3. Turn off `PODCASTS_TAB_SEARCH_BAR` feature flag under `Profile` -> `Settings` -> `Beta features`
4. Kill and restart the app
5. ✅ Notice that search bar is replaced by search menu
FF Enabled | FF Disabled
---|----

Add feature flag for search bar in Podcasts tab

---

modules/features/discover/src/main/res/layout/row_carousel_list.xml
modules/features/discover/src/main/res/layout/row_category_pills.xml
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
modules/features/podcasts/src/main/res/menu/podcasts_menu.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

This reduces search bar height.
1. Open profile tab
2. Notice that search bar height is reduced
Before | After | 
----|---|
After with text | After with text large size
----|---

Search bar reduce height

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/MiniPlayer.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt
modules/features/player/src/main/res/layout/view_mini_player.xml
modules/services/localization/src/main/res/values/strings.xml

Part of #2081 
This adds an empty-state mini-player.
P.S.:  The scope of this PR is only to display the empty-state mini-player. UI will be fine-tuned as part of design changes.
** I considered renaming "Close and clear Up Next" mini-player long press menu item to "Clear Up Next" as the mini-player is always visible. But "Clear Up Next" appears to be the same as "Clear Queue" on the Up Next screen which retains the current playing episode and only clears the Up Next queue.  But right now, the menu option clears even the now-playing episode. I'll check about the intended behavior and update this part.
1. Fresh install the app 
2. ✅ Notice that an empty-state mini-player is shown
3. ✅ Notice that nothing happens on tap, long press, and drag on the empty-state mini-player  
4. Go to Discover …

Add empty state mini player

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
modules/features/discover/src/main/res/drawable/category_clear_all_pill_background.xml
modules/features/discover/src/main/res/drawable/category_pill_background.xml
modules/features/discover/src/main/res/drawable/category_pill_selected_background.xml
modules/features/discover/src/main/res/drawable/search_with_category_pills_background.xml
modules/features/discover/src/main/res/layout/fragment_discover.xml
modules/features/discover/src/main/res/layout/row_category_pills.xml

- This just removes the border color from search and makes the icon and text in search lighter to match with the existing search in Podcasts tab
- Just check if the search bar colors in discover matches with the same colors from podcasts tab
- You can try with different themes
| Discover Before Changes |
|--------|
|<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/5ebb6fe9-3761-442c-a32e-291f46dedb0a" width="400"> |  
| Discover after changes | Podcasts tab to compare |
|<img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/4acedc12-4c6e-40c1-93a2-678d0d2d77c5" width="400"> | <img src="https://github.com/Automattic/pocket-casts-android/assets/42220351/dda8f9cc-be7b-4964-9027-ceb1709cec2a" width="400"> |

Update Search bar colors in Discover

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt

- Updates status bar color for discover tab
- The status bar cor should match with discover header color with `Show up next tab bar` feature flag enabled and disabled
- I tested using Pixel 7
1. Run the app with `Show Up Next in tab bar` enabled
2. ✅ Check if the Status Bar color matches with the discover header color
3. Try with different themes
4. Disable `Show Up Next in tab bar`
5. Restart the app
6. ✅ Check if the Status Bar color matches with the discover header color
7. Try with different themes
|![Screenshot_20240501_100550](https://github.com/Automattic/pocket-casts-android/assets/42220351/4de86638-d620-4fe6-a749-5b6853b1fbf6) |![Screenshot_20240501_100627](https://github.com/Automattic/pocket-casts-android/assets/42220351/323a7fc7-3118-47c4- …

Update status bar for discover

---

CHANGELOG.md
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout/fragment_sleep.xml
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt

- This adds the ability to select multiple chapters for sleep time
- Important: Since we have episodes with chapters and episodes without chapters, we are going to treat an episode without chapters as a single chapter.
- In this version, every time a user switches to another chapter or episode, we will decrease the number of chapters left before sleep.
1. Run the app
2. Add 5/6 episodes to Up next. Try to add episodes that contain chapters and others that don't
3. Open the full player, tap the sleep timer icon (zZz)
4. Select X chapters for sleep timer
5. ✅ Ensure 🔵 Tracked: player_sleep_timer_enabled, Properties: {"time":"end_of_chapter","number_of_chapters": X
6. Tap the sleep timer icon (zZz) again
7.  ✅  You should see `Sleeping in X chapters` message and the cancel button
8. If your …

Sleep Timer: Add the option to select the number of chapters

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
automotive/build.gradle.kts
automotive/src/main/AndroidManifest.xml
automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveApplication.kt
base.gradle
dependencies.gradle.kts
gradle/libs.versions.toml
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/privacy/UserAnalyticsSettings.kt
modules/services/analytics/build.gradle.kts
modules/services/crashlogging/build.gradle.kts
modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/utils/build.gradle.kts
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SentryHelper.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/crashlogging/PocketCastsCrashLoggingDataProvider.kt
settings.gradle.kts
wear/build.gradle.kts
wear/src/main/AndroidManifest.xml
wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/PocketCastsWearApplication.kt

This PR introduces a new module, `crashlogging`, and "feeds" `PocketCastsCrashLoggingDataProvider` with data needed to initialize and operate `CrashLogging` object later. 
> [!NOTE]
> Note: This is a PR aiming at a feature branch.
To see more context on the changes, please see commits messages - I've tried to explain my reasoning and arguments there.
Not needed - we'll test the integration later.

Introduce `CrashLoggingDataProvider`

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragment.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsFragment.kt
modules/services/ui/src/main/res/transition/slide_in.xml

This removes recent transitions added for Up Next in Tab Bar changes. These are being removed in the main branch  as we move to 5-items tab bar but looking at this Sentry error, it might be good to remove them from beta as well:
https://a8c.sentry.io/share/issue/2a1d0cefd3b14b6b9fee9927ede258b6/
>  java.lang.IllegalArgumentException: Transition false for fragment b{2ca715d} (4bc7dd78-8572-4e64-8eb9-74bdfe258b4c id=0x7f0a03d1 tag=au.com.shiftyjelly.pocketcasts.navigator|rf.b|DETACHABLE|c4b300a3-65a8-4f7e-8431-34e0654fbf77|) is not a valid framework Transition or AndroidX Transition

Remove recent screen transitions from 7.63 beta

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/layout/fragment_sleep.xml
modules/services/localization/src/main/res/values/strings.xml

- This updates the custom time row label to format the time to hours and minutes instead of minutes
- This is to match the iOS behavior. See internal slack reference: `pocket-casts-sleep-timer-p1714744437357789?thread_ts=1714737001.530139&cid=C071416NWE9`
2. Open Sleep timer
3. Click on Custom minute as you can see in the video below
4. ✅ Ensure the label is formatted as 1 minute, x minutes, 1 hour, x hours or x hours and y minutes
Feel free to smoke the sleep timer custom time
[Screen_recording_20240503_120704.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/00284181-b30e-4fa0-910c-d222bbcf6cda)

Sleep Timer: Update custom time row label

---

modules/features/discover/src/main/res/layout/row_category_ad.xml

- Removes the description line limit
- This implements the same single podcast row view
1. Run the app in debugProd
2. Tap on `True Crime` category
3. See the ad description has more than 2 lines
I mocked the description to see how it will look like with long description

Do not truncate ads description

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt

Need to take into account `7.62.2` version code bump for artwork settings migration.
Verify in Play Console that `7.62.2` uses `9229` version code and that `7.63-rc-3` uses `9227` version code.

Account for 7.62.2 when migrating artwork settings

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/EpisodeImage.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/SmallPlayer.kt

Some launchers allow to resize widgets regardless of the configuration. This can lead to unexpected results for the small widget.
I also started using size for fetching artwork to account for big widget sizes.
1. Install Nova Launcher.
2. Add the small widget to the Nova's home screen and play something.
3. Resize the widget and check that it looks correctly.
| - | - |
| ![1-before](https://github.com/Automattic/pocket-casts-android/assets/30936061/46d05923-beeb-45d7-b98d-5828ea337496) | ![1-after](https://github.com/Automattic/pocket-casts-android/assets/30936061/5d784767-2152-41c6-ab18-1674e1e075cb) |
| - | - |
| ![2-before](https://github.com/Automattic/pocket-casts-android/assets/30936061/bbe724b0-8387-4ca4-aad7-992a37f05f39) | …

Select min dimension for small widget

---

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

- This is to avoid UI inconsistencies caused by delays in feature flag synchronization
- See: p1715062226510869-slack-C02A333D8LQ
- Code review is enough.

Enable categories redesign feature flag by default

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt

This PR addresses an issue with our manual refresh task, which implements a 15-second throttle in pull-to-refresh scenarios. Previously, we did not dispatch a "refreshed" state upon task completion due to this throttling mechanism. Additionally, throttling is disabled in debug builds, rendering this bug non-reproducible in those environments.
I have prepared a patch that enables throttling in debug builds to facilitate testing of this fix.
Closes #2153
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/15219568/refresh.patch).
2. Install the app.
3. Go to the podcasts tab.
4. Pull to refresh and wait for the sync to finish.
5. Pull to refresh again.
6. Spinner should disappear.

Dispatch refresh state when refresh task is throttled

---

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/FirebaseAnalyticsTracker.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt

We do not want to send `ForegroundServiceStartNotAllowedException` to Sentry due to quota limits. See: p1715090579752019-slack-C028JAG44VD
> [!note]
> Test with SDK 31 or higher
2. Play something.
3. Pause it.
4. Kill the app and remove all Pocket Cast notifications.
5. Wait a for a minute or so.
6. Execute this ADB command `adb shell am broadcast -a au.com.shiftyjelly.pocketcasts.action.PLAY au.com.shiftyjelly.pocketcasts.debug`.
7. Playback will start for a couple of seconds and the it might stop due to OS restrictions.
8. You should see following in the logs.
```
Playback: attempted startForeground for state: 3, but that threw an exception we caught: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to …
```

Do not send background restricions errors to Sentry

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/viewmodel/DiscoverViewModel.kt
modules/features/discover/src/main/res/layout-h560dp/item_carousel.xml
modules/features/discover/src/main/res/layout/item_carousel.xml
modules/features/discover/src/main/res/layout/row_carousel_list.xml
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListRepository.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/server/ListWebService.kt

- Remove categories redesign feature flag. See: p1715084766395629/1715062226.510869-slack-C02A333D8LQ
- Deprecate `/discover/{platform}/content.json` to use `/discover/{platform}/content_v2.json`. See: p1715085882399969/1715084981.108589-slack-C029BMW150R
1.  Run the app
2. Tap on Sign in Button
3. Create an account
4. ✅ In Find your favorite podcasts screen, ensure you get the `Featured` and categories list
1. Run the app
2. Go to discover
3. ✅ Ensure categories are displayed at the top
- Since we need to remove all old endpoint usages, I had to do it for the suspend function too: https://github.com/Automattic/pocket-casts-android/commit/f51a85e939e3d17f64dce0e153e28ed8e146c48b, but I can't find a way to test it. This is being called only in …

Remove categories redesign feature flag and discover endpoint clean up

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt

- Adds `discover_categories_picker_shown`, `discover_categories_picker_closed` and `discover_ad_category_subscribed` tracks events
- Updates `discover_category_close_button_tapped` and `discover_ad_category_tapped` to include properties
- https://github.com/Automattic/pocket-casts-webplayer/pull/2664
Closes #2188
> [!NOTE]  
> We have only Music category with ads configured for this week
1. Go to Discover
2. Tap on `All categories`
3. ✅ Ensure 🔵 Tracked: `discover_categories_picker_shown, Properties: {"region":"fr"` is tracked 
4. Dismiss category list
5. ✅ Ensure 🔵 Tracked: `discover_categories_picker_closed, Properties: {"region":"fr"` is tracked 
7. Open the categories list again and tap on Music from drop down list
8. ✅ Ensure 🔵 Tracked: `discover_categories_picker_pick, Properties: …

Update discover events tracks to match with Web Player

---

modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FiltersFragment.kt
modules/features/filters/src/main/res/layout/fragment_filters.xml
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextAdapter.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextEpisodeViewHolder.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt
modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/features/player/src/main/res/color/player_button_text_color.xml
modules/features/player/src/main/res/layout/adapter_up_next.xml
modules/features/player/src/main/res/layout/adapter_up_next_footer.xml
modules/features/player/src/main/res/layout/adapter_up_next_playing.xml
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/CountBadge.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/AppBarLayout.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseFragment.kt

Part of: #2081 
Figma Design: G60UqxPhTynbalo0Vfr1NC-fi-1584_17364
This applies following updates to the Up Next screen:
1. Add divider between queue items
2. Update queue item background color to match existing screen background **
3. Add image shadow so that (white) thumbnails are shown properly on certain themes like `Light Contrast`
4. Update header title to include episode count
5. Update Clear Queue dialog theme
6. Update Clear Queue text color to `primary_interactive_01`
** Existing screen background is still `primary_ui_04` instead of `primary_ui_01`. I have to apply an appropriate theme to the Now Playing item before I switch to the new background color.
*** Font sizes and styles for texts shown in Figma are not yet applied as they need to be used throughout the app. They're kept …

Up Next design updates

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

Episodes were being archived after playing even when global settings was set to never and podcasts wasn't technically overriding the value. Some users were affected by it during settings sync test.
Internal ref: p1713427004164729-slack-C02A333D8LQ
2. Go to global auto archive settings and set `Archive played episodes` to `Never`.
3. Run `UPDATE podcasts SET auto_archive_played_after = 1, override_global_archive = 0` in the `Database Inspector`.
4. Play an episode from any podcast.
5. Skip to the end.
6. Podcast should not be archived.
Test that episode playback respects all custom auto archive settings. Both global and podcast specific ones. You might want to clear you DB after the previous test before conducting this test.

Fix auto archiving episodes

---

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt

As a precaution before batching goes to production I'm putting batch size behind remote configuration. This will allow us to bring back the old behavior by increasing batch size if somethings doesn't behave as expected.
> [!note]
> Test this with the `release` variant.
1. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/15264364/batch.patch).
2. Go to the Firebase remote config.
3. Change `refresh_podcasts_batch_size` to a negative number.
4. Install and open the app.
5. Go to podcasts tab.
6. Pull to refresh a couple of times. Be cautious of #2164 that is not fixed in `7.63` so you'll need to do 20 seconds pauses between refreshes including the one that happens on app init.
7. You shouldn't observe anything special. Podcasts should refresh. 
8. Change …

Fetch episodes refresh batch size from remote config

---

modules/features/podcasts/src/main/res/layout/fragment_podcasts.xml
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
modules/services/localization/src/main/res/values/strings.xml

- The scroll bar on the podcasts page is now on the side of the screen.
- Adds elevation to folder
Partly Fixes https://github.com/Automattic/pocket-casts-android/issues/2193
Scrollbar 
Scrollbar
1. Subscribe to lots of podcasts
2. Go to the podcasts grid
3. Scroll the page
Folder Image
1. Create a folder and subscribe to a podcast
2. Go to the podcasts list
3. Compare the drop shadow on the podcast artwork and a folder (I changed the color to White in the captured screenshot)
https://github.com/Automattic/pocket-casts-android/assets/1405144/daa8e4cc-5ad1-44a2-af1c-0b0c05e91acc
Folder Image

Up Next - Minor tweaks

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerHeader.kt

Large player widget header padding was a little bit too big.
Internal ref: Lkt7fuf9Nq3XvfAFPCfpTD-fi-1530_3473
Reviewing screenshots should be enough but you can test the large widget.
| - | - |
| ![before](https://github.com/Automattic/pocket-casts-android/assets/30936061/1f8f95b7-6abb-4cac-9583-61a61b65fe33) | ![after](https://github.com/Automattic/pocket-casts-android/assets/30936061/90e621fb-41e1-45bc-b6e6-f7666455b64c) |

Make large widget header padding smaller

---

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt

This fixes folder badge overlay getting cropped due to changes in https://github.com/Automattic/pocket-casts-android/pull/2204
1. Create a folder and subscribe to a podcast
2. Go to the podcasts list
3. Enable badge
4. Compare the drop shadow on the podcast artwork and a folder 
5. Notice that badge is not cropped

Move badge overlay outside card view

---

CHANGELOG.md
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

Enabled FF for Up Next in tab bar.
Make sure that `upnext_in_tab_bar` feature flag has correct values in `Feature.kt` and in Firebase remote config.

Enable up next in tab bar

---

modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/WidgetTheme.kt

This PR makes button background in dark mode a bit darker.
Internal ref: Lkt7fuf9Nq3XvfAFPCfpTD-fi-1530_3435
1. Add widgets to the home screen and set their theme to non-dynamic dark.
2. The button's background color should match the designs.
| - | - |
| ![before](https://github.com/Automattic/pocket-casts-android/assets/30936061/b87ae91b-7a65-4fd4-a1d5-3461e3062a7e) | ![after](https://github.com/Automattic/pocket-casts-android/assets/30936061/a15df405-6dfb-49fa-aee0-14d30730ed91) |

Change widget's button background color

---

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt
modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt

- This PR sets the Yearly subscription as default selected by removing the existing logic to select the last selected subscription
- See: p1715362112981289/1715288540.470539-slack-C028JAG44VD
> [!NOTE]  
> You may encounter a Play Store caching issue when attempting to check your subscriptions. If you receive a message indicating that you don't have any subscriptions, you will need to clear the cache for both the Play Store and Pocket Casts app
Closes #2209
1. `git apply` [subscription.patch](https://github.com/Automattic/pocket-casts-android/files/15294065/subscription.patch)
2. Run the app in `debugProd`
3. Login with a free account that never had any subscription before
4. Have this account logged in Play Store
5. ✅ Ensure every upsell we have opens with `Yearly Subscription` selected …

Set yearly subscription as default selected

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/PlayerWidgetManager.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/data/LargePlayerWidgetState.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayer.kt
modules/features/widgets/src/main/kotlin/au/com/shiftyjelly/pocketcasts/widget/ui/LargePlayerQueue.kt

Make large widget content not scrollable.
1. Add at least 10 episodes to your queue.
2. Add large widget to your home screen.
3. Make sure that the queue is not scrollable in the widget.
4. When you resize the widget the number of displayed items should adapt to the size.

Make large widget non-scrollable

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CategoryPillListAdapter.kt

- The text color of `All categories` something was not getting set with the correct color when subscribing to podcasts
> [!NOTE]  
> We have only Music category with ads configured for this week
Closes: #2198
1. Go to Discover.
2. Select a category from All categories that has add.
3. Tap on subscription button.
4. Close the categories.
5. Select a category from All categories that has add again.
6. Tap on subscription button again.
7. Close the categories.
8. All categories title must have the correct color. You can compare with the others pills colors
See the video in #2198

Fix: All categories text color sometimes getting painted with wrong color

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditColorPage.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderListRow.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt

The folder label was being hidden off the image, this change improves this. This could look better but as we have the beta it's a quick fix. Thanks for your advice @MiSikora, I will give a constraint layout a try for a future version.
There's still an issue that the folder size is smaller than the podcast artwork but a fix for that will be in a separate pull request.
1. Add a folder
2. Check the folder label in the three podcast layouts: large grid, small grid, and list.
| --- | --- |
| ![Screenshot_20240514_173220](https://github.com/Automattic/pocket-casts-android/assets/308331/72534b6c-3256-440b-bd58-5170c52ff43c) | ![Screenshot_20240514_172750](https://github.com/Automattic/pocket-casts-android/assets/308331/45a407db-9108-4e4d-8486-9684208fce2b) |
| …

Improve the folder label position

---

modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectEpisodesHelper.kt

When removing Up Next queue, message will always 0 count even tho the queue is successfully removed. This is due to mutable list is already cleared outside of the coroutine scopr. Now it will use the temporary list instead of the mutableL lst.
Fixes #1918 
1. Open your Up Next, make sure the queue is not empty.
2. Activate multi select and select episode you want to remove
3. Remove them, now it should show the correct amount of removed queue instead of 0.

fix wrong Up Next removal message

---

.buildkite/pipeline.yml
.github/workflows/run-danger.yml
Dangerfile

This PR uses the new Linter Agent on Buildkite to run the Danger jobs.
Because Danger will now run on Buildkite, this PR uses a new GitHub Actions workflow (see https://github.com/Automattic/dangermattic/pull/64 for more details) to retry the Buildkite jobs when the PR state (such as the milestone and labels) changes.

[Tooling] Run Danger on the Linter Agent

---

modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/MostPopularPodcastsAdapter.kt
modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/RemainingPodcastsAdapter.kt

- This PR fixes the pages jumps issue when you subscribe to a podcast from the filtered podcasts list
- While I was working on this issue I also noticed the most popular section had the same problem, so I addressed to this PR
Fixes #2199
1. Go to Discover
2. Filter a category
3. Subscribe to any podcast from Most Popular in [category] section
4. ✅ Ensure the list does not "jump"
5. Go to the remaining category list and scroll a bit
6. Try to subscribe to any podcast from this section
7. ✅ Ensure the list does not "jump"
[Screen_recording_20240514_080806.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/193f6503-0747-4816-8771-983091ff370f)

Fix: Subscribe to a podcast makes the page jumps after a few seconds

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/folder/FolderImage.kt
modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/UiUtil.kt

This fixes the folder size issue on the Samsung Fold in landscape. 
The issue was that the logic was still assuming a navigation drawer was displayed on larger devices, which hasn't been the case for a while. I have removed this logic. I realised that it's probably best to try just filling the available space instead of using an exact size with the folders. This worked, which makes me wonder why we were setting it in the past. Hopefully, I haven't broken anything in the process. Please let me know if you can think of anything. 
The change has also fixed the slight folder size issue on a regular sized phone.
Fixes https://github.com/Automattic/pocket-casts-android/issues/2228
1. Create an emulator with the virtual configuration of a Pixel Fold (if you haven't already)
2. Put the emulator …

Fix folder size on large screens

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt

This fixes status page crash.
1. Go to Profile -> Help & feedback -> Status page
2. ✅ Notice that it loads properly
3. Tap Run now, wait till status is shown
4. Scroll the screen
5. ✅ Notice that the content can be scrolled properly
6. Test on landscape mode
https://github.com/Automattic/pocket-casts-android/assets/1405144/d34e6de4-4e1f-4a8a-8952-91c5ebcc63c5

Fix status page crash

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerCacheUtil.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt

This improves ExoPlayer cache initialization and error handling.
Instead of releasing the `simpleCache` variable every time the player is released, it is stored in a static variable. Considering the current architecture of the app, where `ExoPlayer` can be released and initiated multiple times, this approach is worth using for intermediate caching ([ref](https://rb.gy/vmjs89)).
This resolves the following crash:
https://a8c.sentry.io/share/issue/2f8bcf549be04fb9bcaffd8a223d4681/
I could reproduce the crash by hitting play on a few episodes simultaneously. The cache variable tried to re-initialize while being locked during release, causing the crash.
We are utilizing the built-in caching feature of ExoPlayer. Testing the caching mechanism itself is not required. A few things we can try:
1. …

ExoPlayer Cache: Improve error handling

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherNewEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt

This sync new releases with Nova Launcher. Unfortunately, at the moment Nova doesn't support displaying them so the only verification we can do is through the logs. We will revisit testing once we have a Nova build that handles more use cases.
1. Install this version of the Nova Launcher: p1715685124487099-slack-C028JAG44VD
2. Install Pocket Casts.
3. Open the app and be subscribed to podcasts where you have new episodes that are at most 2 weeks old.
5. Verify in the logs that new episodes are synced.
```
Nova Launcher sync complete. Success: [Subscribed podcasts: 25, New episodes: 56], Failure: []
```
6. If you notice the message below in the logs. Maximize and minimize the app again. It can happen if Nova fails to fetch verification signatures.
```
Nova Launcher …
```

Sync new releases with Nova Launcher

---

CHANGELOG.md
app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParser.kt
modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParserTest.kt

- This PR fixes the timestamp parsing when opening Pocket Casts from shared URL. It will support:
```
https://pca.st/sb2ksvqv?t=28,60
Either one or both parameters may be omitted, with the begin time defaulting to 0 seconds and the end time defaulting to the duration of the source media
t=10,20   # => results in the time interval [10,20)
t=,20     # => results in the time interval [0,20)
t=10      # => results in the time interval [10,end)
```
```
https://pca.st/y0ebrkcc?t=1:02:03
hh:mm:ss.fraction - Either be specified as seconds, with an optional fractional part to indicate miliseconds, or as colon-separated hours, minutes and seconds (again with an optional fraction). Minutes and seconds must be specified as exactly two digits, hours and fractional seconds can be any number of digits …
```

Fix: Android doesn't handle timestamp parameter in share links properly

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherTrendingPodcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt

This sync trending podcasts with Nova Launcher. Unfortunately, at the moment Nova doesn't support displaying them so the only verification we can do is through the logs. We will revisit testing once we have a Nova build that handles more use cases.
1. Install this version of the Nova Launcher: p1715685124487099-slack-C028JAG44VD
2. Install Pocket Casts.
3. Open the app and visit Discover page.
5. Verify in the logs that trending podcasts are synced.
```
Nova Launcher sync complete. Success: [Subscribed podcasts: 25, Trending podcasts: 79, New episodes: 57], Failure: []
```
6. If you notice the message below in the logs. Maximize and minimize the app again. It can happen if Nova fails to fetch verification signatures.
```
Nova Launcher sync failed …
```

 Sync trending podcasts Nova Launcher

---

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/viewmodel/PlayerViewModel.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt

This is to help us to investigate this opened issue: https://github.com/Automattic/pocket-casts-android/issues/2219
Code review should be enough

Sleep timer: Add logs 

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt

Applies podcasts grid padding when the user installs the app for the first time and has not interacted with the mini-player yet.
Fixes https://github.com/Automattic/pocket-casts-android/issues/2248
1. Checkout 7.64 tag
2. Put a breakpoint at line 202
3. Fresh install the app
4. Go to Podcasts tab
5. ✅ Notice that breakpoint is not hit
6. Go to Discover tab and subscribe to a few podcasts
7. Go to Podcasts tab
8. ✅ Notice that breakpoint is still not hit and out grid padding is not applied
9. Checkout this branch
10. Put a breakpoint at line 362
11. Fresh install the app
12. Go to Podcasts tab
13. ✅ Notice that breakpoint is hit
14. Repeat steps 6-7
15. ✅ Notice that breakpoint is hit and outer grid padding is applied
16. Switch between grid and list view
17. ✅ Notice that the outer …

Update bottom inset on application start

---

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/FolderViewHolder.kt

This temporarily fixes folder flickering when switching between tabs.
Fixes #1661
1. Login with a paid account
2. Create two folders of different colors and add podcasts to them. 
3. Switch between Podcasts tab and another tab
4. ✅  Notice there's no flickering in the folders
**Before**
https://github.com/Automattic/pocket-casts-android/assets/1405144/5d152c36-c9a2-4c8c-a535-ccc65883b556
**After**
https://github.com/Automattic/pocket-casts-android/assets/1405144/9b62551d-b5bf-4d40-bb83-acb02d617f9f

Fix folder flickering

---

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/VersionMigrationsJob.kt

This enabled dynamic colors for widgets by default.
> [!note]
> Test this with Android 12+
1. Clean install the app.
2. Add large widget.
3. Notice that it is themed to your home screen palette.
4. Go to settings and disable dynamic colors for widgets.
5. Close the app.
6. The widget should not be themed.
7. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/15339429/dynamic.patch).
8. Install the app with the patch.
9. The widget should be themed.
10. Go to settings and disable dynamic colors.
11. Close the app.
12. The widget should not be themed.

Enable dynamic widget colors by default

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/EpisodeDaoTest.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/EpisodeDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherInProgressEpisode.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt

This sync in progress episodes with Nova Launcher. Unfortunately, at the moment Nova doesn't support displaying them so the only verification we can do is through the logs. We will revisit testing once we have a Nova build that handles more use cases.
1. Install this version of the Nova Launcher: p1715685124487099-slack-C028JAG44VD
2. Install Pocket Casts.
3. Open the app and play some episodes from different podcasts and make sure they are not archived.
5. Verify in the logs that in-progress episodes are synced.
```
Nova Launcher sync complete. Success: [Subscribed podcasts: 25, Trending podcasts: 79, New episodes: 56, In progress episodes: 8], Failure: []
```
6. If you notice the message below in the logs. Maximize and minimize the app again. It can happen if Nova …

Sync in progress episodes with Nova Launcher

---

CHANGELOG.md
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt

Parent PR: https://github.com/Automattic/pocket-casts-android/pull/2242
This changes the "Cache playing episode" feature flag key so that enabling the flag does not enable the feature for previous versions, and sets the default value to true. It can be turned off through the Firebase remote config.
Ensure that values updated are correct.

Change cache playing episode feature flag key

---

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PlaylistManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt

Looking at this ANR in Play console, 
`au.com.shiftyjelly.pocketcasts.repositories.shortcuts.PocketCastsShortcuts$update$1.invokeSuspend`
an ANR is triggered at line 52 of `PocketCastsShortcuts`
https://github.com/Automattic/pocket-casts-android/blob/7926889cfad24dc4902bad3640a2355a35fb774e/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/shortcuts/PocketCastsShortcuts.kt#L52
While I cannot reproduce this ANR, logging the call source and moving the line outside the main thread, without disrupting the functionality, might help.
This may also explain why there was a freezer binder transaction on 5/18/24, 12:55  in latest logs shared in: https://github.com/Automattic/pocket-casts-android/issues/2225#issuecomment-2119086065 
``` …
```

Shortcuts ANR

---

CHANGELOG.md
dependencies.gradle.kts

This PR bumps minimum sdk version to `24`. It was discussed here: https://github.com/Automattic/pocket-casts-android/pull/2182#discussion_r1592655462
I don't think testing is necessary.

Bump min sdk version to 24

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt

The podcast or episode artwork doesn't show in Tesla cars when only the artwork URL is set in the media session metadata. If the artwork is set in a bitmap it's displayed. 
Fixes https://github.com/Automattic/pocket-casts-android/issues/2237
This is a hard one to test without a car but it would be good to check that using the bitmap doesn't break other places where we use the artwork. 
1. Tap play on an episode
2. ✅ Verify the notification shade artwork is correct and not low-resolution
3. Start an Android Auto head unit
```
cd /Applications/android-sdk/extras/google/auto/ (or wherever your Android SDK folder is located)
chmod +x ./desktop-head-unit
./desktop-head-unit --usb
```
4. ✅ Verify the playing screen has the correct artwork

Fix Tesla artwork issue

---

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/StorageSettingsPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/StorageSettingsViewModel.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/FixDownloadsWorker.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelper.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelperImpl.kt

A follow up to #2244. After reviewing OPML imports I wanted to move episodes fixing to notifications as well to make it a more familiar experience.
Also, the process is now much faster (about 2 orders of magnitude) because UI updates are less frequent which doesn't block database operations as much.
2. Download some episodes.
3. Go to `Profile`/`Downloads` and confirm that you see the episodes.
4. Go back to `Profile`.
5. Execute this query `UPDATE podcast_episodes SET downloaded_file_path = NULL, episode_status = 0`.
6. Go to `Profile`/`Downloads` and confirm that you don't see any episodes.
7. Go to `Settings`/`Storage & data use`.
8. Tap on `Fix downloads`.
9. Wait until process finishes. You should get a notification about it.
10. Go to `Profile`/`Downloads` and …

Move fixing downloads to a background task

---

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/ExoPlayerCacheUtil.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/config/FirebaseConfig.kt
modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/providers/FirebaseRemoteFeatureProvider.kt

This gets the Exoplayer cache size from remote config (increased from 50 to 100 MB).
1. Search for `setMinimumFetchIntervalInSeconds`(...) in the code and set to 5s
2. Add a LogBuffer.i(...) just before line 29 in `ExoPlayerCacheUtil` to print value for `FeatureFlag.isEnabled(Feature.CACHE_PLAYING_EPISODE)` and `firebaseRemoteConfig
.getLong(FirebaseConfig.EXOPLAYER_CACHE_SIZE_IN_MB)`
4. Install release build
5. Open the app
6. Play an episode
7. Open `Profile` -> `Settings` -> `Help & feedback` -> `Logs`
8. ✅ Notice that correct values are printed
9. Uninstall the build

Get Exoplayer cache size from remote config

---

CHANGELOG.md
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt

When sleep timer end of episode was triggered the app was moving to the next episode instead of keeping on the last listened one. This PR fixes this issue
End of chapter never had this behavior of keeping on the same chapter. Since the implementation for this a more complicated I won't address this on a beta PR. Also, it needs to be aligned with iOS
Fixes #2266 
1. Add some episodes to up next
2. Set end of episode
3. When the sleep timer stops the episode, make sure the app keep on the same episode
You can also smoke test the Sleep Timer feature
https://github.com/Automattic/pocket-casts-android/assets/42220351/9432ecdc-ec56-4774-ad6f-2171b5e4e8a8

Fix: Sleep timer end of an episode is not pausing before right before the end 

---

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/PodcastDaoTest.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/CatalogFactory.kt
modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherSyncWorker.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/NovaLauncherRecentlyPlayedPodcast.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/nova/NovaLauncherManagerImpl.kt

This recently played podcasts with Nova Launcher. Unfortunately, at the moment Nova doesn't support displaying them so the only verification we can do is through the logs. We will revisit testing once we have a Nova build that handles more use cases.
1. Install this version of the Nova Launcher: p1715685124487099-slack-C028JAG44VD
2. Install Pocket Casts.
3. Open the app and play some episodes from different podcasts.
5. Verify in the logs that recently played poccasts are synced.
```
Nova Launcher sync complete. Success: [Subscribed podcasts: 25, Recently played podcasts: 38, Trending podcasts: 79, New episodes: 56, In progress episodes: 8], Failure: []
```
6. If you notice the message below in the logs. Maximize and minimize the app again. It can happen if Nova …

Sync recently played podcasts with the Nova Launcher

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/AdvancedSettingsPage.kt
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModel.kt
modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/viewmodel/AdvancedSettingsViewModelTest.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt

Now that we have an `Advanced Settings` section, I'm re-proposing an option to allow more seek accuracy (earlier PR: https://github.com/Automattic/pocket-casts-android/pull/733).
It is not enabled by default, as [more accuracy comes at the cost of slower seeking](https://developer.android.com/media/media3/exoplayer/troubleshooting#why-is-seeking-inaccurate-in-some-mp3-files), particularly for large mp3 files. However, with this advanced setting, and with a stronger warning as advised here: https://github.com/Automattic/pocket-casts-android/pull/733#discussion_r1089262870), users will have a choice to prioritize accuracy over speed.
Fixes #744
Requires at least two approvals to merge this PR.
Steps to reproduce
0. Disable `Beta features` -> `Cache playing episode`, kill and restart the app …

Add advanced setting to allow more seek accuracy

---

CHANGELOG.md
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabaseTest.kt
app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/AutoArchiveTest.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAdapter.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveFragment.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastAutoArchiveViewModel.kt
modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt
modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/95.json
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/converter/AutoArchiveLimitTypeConverter.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/PodcastDao.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/Podcast.kt
modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/AutoArchiveLimit.kt
modules/services/model/src/test/java/au/com/shiftyjelly/pocketcasts/models/converter/AutoArchiveLimitTypeConverterTest.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/EpisodeManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt

Episode archive limit is another setting that got hit by sync test. In the app we used `null` to represent `No episode limit`. A sync value for this state is `0`.
Internal ref: p1716451879995699-slack-C02A333D8LQ
1. Install the app from 201c539b50c42a0ff918a72b557e921a2dfb2f88
2. Subscribe to at least 6 podcasts.
3. Execute this query: `UPDATE podcasts SET auto_archive_episode_limit = 0, override_global_archive = 1`.
4. Open one of the podcasts.
5. You should see `Limited to 0 most recent episodes`.
6. Go to podcast settings and change auto archive episode limit to `No limit`.
7. Go to other 4 podcasts and select other limits. Leave one podcast in the state from the query.
8. Install the app from this branch.
9. Check podcasts settings and make sure that these the setting you set are …

Constraint episode archive limit

---

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/OpmlImportTask.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/opml/PreProcessOpmlFile.kt
modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/opml/PreProcessOpmlFileTest.kt

- Add missing uni tests for #2260
- Code review should be enough

Add unit tests for pre process OPML file

---

CHANGELOG.md
modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/PlaybackSettingsFragment.kt
modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
modules/services/localization/src/main/res/values/strings.xml
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimer.kt
modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SleepTimerRestartWhenShakingDevice.kt

- This PR lets the user disable/enable the auto sleep timer restart and shake device to restart sleep timer
- Adds two events for when toggling the two news sleep timer config
- For context: p1716464798386719-slack-C071416NWE9
````
Tracked: settings_general_shake_to_reset_sleep_timer_toggled, Properties: {“enabled”:boolean
Tracked: settings_general_auto_sleep_timer_restart_toggled, Properties: {“enabled”:boolean
````
1. Go to settings -> General -> Make sure you have `Auto Restart Sleep Timer` enabled
2. Add some episodes to Up Next
4. Set Sleep timer. It could be end of episode, end of time or end of chapter
5. If you set to end of time, wait until the sleep timer is triggered
6. When the sleep timer stops the episode you tap to play it again with 5 minutes
7. ✅ Make …

Adding sleep timer config to general
