modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/ResetPasswordFragment.kt
…Manager
Please include a summary of the changes and the related issue.
Fixes # (issue)
=> Do Not Merge – Only here to trigger CI on 373

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ChaptersFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/NotesFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerContainerFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
| 📘 Project: #261  |
|:---:|
Corresponding iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/289
This adds the basic events to the full screen player view: 
- `player_shown`: When the full screen player is displayed to the user
- `player_dismissed`: When the user dismisses the full screen player
- `player_tab_selected`: When one of the tabs at the top of the player view is selected
- `player_show_notes_link_tapped`: When the user taps a link in the player show notes
- `player_chapter_selected`: When the user selects a chapter from the chapter list tab
- `player_previous_chapter_tapped`: When the user taps the chapter back button
- `player_next_chapter_tapped`: When the user taps the chapter forward button
1. Play an episode if you don't have one playing already
2. Tap the mini …
=> Track player events

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/AutomotiveSettingsActivity.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt, modules/features/filters/src/main/java/au/com/shiftyjelly/pocketcasts/filters/FilterEpisodeListFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerClickListener.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/UpNextFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/ProfileEpisodeListFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragmentViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/EpisodeViewSource.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/helper/FragmentHostListener.kt
| 📘 Project: #261 | 
|:---:|
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/297
This adds events to the Episode Detail view:
- `episode_detail_shown`:  When the episode details view is displayed to the user
- `episode_detail_show_notes_link_tapped`: When the user taps a link from the show notes section
- `episode_detail_podcast_name_tapped`: When the user taps the podcast name link/button
- `episode_detail_dismissed`: When the episode details view is dismissed
2. Tap on the Podcasts tab
3. Select a podcast
4. Tap on an episode
5. ✅ `🔵 Tracked: episode_detail_shown ["source": "podcast_screen"]`
6. Tap on a link that's located in the show notes
7. ✅ `🔵 Tracked: episode_detail_show_notes_link_tapped ["episode_uuid": "UUID", "source": "podcast_screen"]` - Where …
=> Track episode details events

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt, version.properties
=> Merge release/7.24 into main

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/file/StorageOptions.kt
We had a couple of spotless issues that made it to the main branch. This is just fixing those.
=> Fix spotless issues

modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, version.properties
=> Merge release/7.25 into main

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt, modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesPage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowButton.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowOutlinedButton.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/RowTextButton.kt
| --- |
This change tries to match the design of the "Continue with Google" button. I have also updated the other buttons on the onboarding login page at the same time.
1. Open the app when not logged into an account
2. ✅ Verify the buttons are similar to the design
=> Onboarding Flow: Continue with Google button

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt
| --- |
This PR is updating the button the recommendations screen to display "Continue" if the user is subscribed to any podcasts. Previously, it was only updated from "Not Now" to "Continue" if the user was subscribed to one of the trending podcasts.
This was first noticed by @adamzelinski in [his design feedback](https://github.com/Automattic/pocket-casts-android/issues/524#issuecomment-1347960181).
> **Warning**
> This PR is targeting the `release/7.29` branch.
1. Open the onboarding recommendations screen without being subscribed to any podcasts
2. ✅ Observe that the button text is "Not Now"
3. Tap the search button, perform a search, and subscribe to 1 podcast
4. Return to the onboarding recommendations screen
5. ✅ Observe that the button text is "Continue"
6. …
=> Onboarding: Use continue button if subscribed to any podcast

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt
| --- |
> **Note**
> This PR builds on #675 
Adds "Featured" section to the Recommendations page
Take a look at the testing instructions in #675 and make sure the Featured section behaves appropriately.
=> Add featured podcasts to recommended page

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/AccountAuth.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingFlowComposable.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginGooglePage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/OnboardingLoginOrSignUpPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingForgotPasswordViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingLoginOrSignUpViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ResetPasswordViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/accountmanager/PocketCastsAccountAuthenticator.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/AccountConstants.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/model/AuthResultModel.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/forgotpassword/ForgotPasswordRequest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/forgotpassword/ForgotPasswordResponse.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/login/LoginGoogleRequest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/login/LoginTokenRequest.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/login/LoginTokenResponse.kt
This change does the following:
- takes the Google id token and sends it to our sync server
- adds logic to handle refresh and access tokens
- updates the forgotten password call to use Retrofit
I recommend using an actual device as I found it more reliable than an emulator with the Google Sign-In framework.
It would be good to test both using the staging and production servers as they are running different code and we will be releasing the Android app before the updated server code is released to production.
1. Change SINGLE_SIGN_ON_ENABLED in base.gradle to `true`
2. Make sure the Build Variant is 'debug'
1. Clean install the app
2. Tap 'Continue with Google'
3. Pick your Google account with an email that exists in the app
4. ✅ Verify you are taken into the app and on the profile tab …
=> Setup Google SSO server call

modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, version.properties
=> Update `main` with 7.30 release

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectAction.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectBottomSheet.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectTouchCallback.kt
This adds events to the "multi select view" that appears when the user
`multi_select_view_overflow_menu_shown`: When the user taps the more button (... or ︙) button
`multi_select_view_overflow_menu_rearrange_started`: When the user taps the Edit button and the overflow menu enters rearrange mode
`multi_select_view_overflow_menu_rearrange_action_moved`: When the user moves an action in during a rearrange
`multi_select_view_overflow_menu_rearrange_finished`: When the user exits the rearrange mode
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/296
2. Tap on the Podcasts tab
3. Select a Podcast
4. Tap and hold to enter the multi select mode
5. Tap the ... button
6. ✅ Verify you see `🔵 Tracked: multi_select_view_overflow_menu_shown ["source": "podcast_screen"]` …
=> Track multi select view events

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/recommendations/OnboardingRecommendationsSearchViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingRecommendationsStartPageViewModel.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/CarouselListRowAdapter.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/DiscoverFragment.kt, modules/features/discover/src/main/java/au/com/shiftyjelly/pocketcasts/discover/view/PodcastGridListFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/episode/EpisodeFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/PodcastFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreatePodcastsPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListCreateViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/share/ShareListIncomingViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastSettingsViewModel.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsSource.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SharePodcastHelper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt
iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/324
- `share_podcasts_shown`: When the share podcasts select podcasts view is displayed to the user
- `share_podcasts_podcasts_selected`: When the user taps the next button
- `share_podcasts_list_publish_started`: When the user taps the publish button and the publish request starts
- `share_podcasts_list_publish_succeeded`: When the list publish succeeds
- `share_podcasts_list_publish_failed`: When the list publish fails
- `incoming_share_list_shown`: When the user is shown Shared List view
- `incoming_share_list_subscribed_all`: When the user taps the "Subscribe All" button
Part of iOS PR: https://github.com/Automattic/pocket-casts-ios/pull/293
- `podcast_shared`: When a podcast is shared
iOS PR: …
=> Track podcast subscribed and shared events

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This cherry picks #757 from `main`  to `release/7.32`.
=> Cherry pick to 7.32

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/SearchHistoryDaoTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/discover/src/main/res/layout/row_carousel_list.xml, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchViewModel.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/adapter/SearchPodcastViewHolder.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryClearAllConfirmationDialog.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryPage.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModel.kt, modules/features/search/src/main/res/layout/fragment_search.xml, modules/features/search/src/test/java/au/com/shiftyjelly/pocketcasts/search/searchhistory/SearchHistoryViewModelTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/SearchBar.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/schemas/au.com.shiftyjelly.pocketcasts.models.db.AppDatabase/74.json, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/SearchHistoryDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/SearchHistoryItem.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/to/SearchHistoryEntry.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/searchhistory/SearchHistoryManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/searchhistory/SearchHistoryManagerImpl.kt, modules/services/ui/src/main/java/au/com/shiftyjelly/pocketcasts/ui/di/DispatcherModule.kt
Part of #752
This includes search history design improvements to match the specs: 8JZyr1ZkWiGn3kSjJYvpoZ-fi-160%3A5856
APK for design review attached in pdeCcb-1iH-p2#comment-1675.
Light Theme | Different Theme | Large font
---|----|---
|Landscape mode|
|----|
|<img width=700 src="https://user-images.githubusercontent.com/1405144/218472003-2cc10c62-b204-4d97-9083-a0e2a9f794d5.png"/>|
=> Search history: Design review

README.md
Just bringing the directory structure section of the readme up to date.
=> Update directory structure in readme

modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, version.properties
=> Merge release/7.35 into main

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CastingPlayer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/CompositePlayer.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackService.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactory.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlayerFactoryImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AutoConverter.kt
Basic functionality for switching to `CastPlayer` when casting. Lots of work left to do here though.
Fixes # 
Check that you can cast audio to another device from the app. Some basic playback controls are also generally working.
=> Media3: Basic castplayer functionality

modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt, version.properties
Includes https://github.com/Automattic/pocket-casts-android/pull/900 that fixes downloading cloud files in beta.
=> Merge 7.37-rc-3 to main

modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, version.properties
=> Merge release/7.37 into main

dependencies.gradle
This appends "w" to Wear OS app version name to differentiate it from the default app.
=> Update wear os app version name

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt
This PR stops syncing the listening history on the watch because we do not use or display the listening history in the watch app. This will help save data and help improve the watch's [slow login times](https://github.com/Automattic/pocket-casts-android/issues/1047).
Login to a fresh install of the watch and verify that the watch hasn't lost any functionality.
Also, login on a fresh install of the phone app and verify that the account's listening history is fetched.
=> Do not sync listening history on watch

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt
This avoids widget configuration on wear os. `AppWidgetManager.getInstance` returns null on wear os, so this was throwing a null pointer exception before. That wasn't a problem really because we immediately caught the exception, but it clutters up the logs, so it seems better to avoid that unnecessary work on the watch.
* Run the watch app and verify that when you play a podcast without this PR you see a null pointer exception from `WidgetManagerImpl`, but that with this PR you do not see that exception.
* Run the phone app and verify that the pocket casts home screen widget still works as expected.
=> Avoid widget setup on wear

modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, version.properties
=> 7.40 release merge

modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchFragment.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchHandler.kt, modules/features/search/src/main/java/au/com/shiftyjelly/pocketcasts/search/SearchInlineResultsPage.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
With the search improvements available in production, this removes the remote feature flag check for the feature.
To test:
1. Make sure CI is green.
2. Smoke test that the search feature is functioning well.
=> Remove search improvements feature flag

app/src/test/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderEditViewModelTest.kt, app/src/test/java/au/com/shiftyjelly/pocketcasts/utils/MainCoroutineRule.kt
Refactored FolderEditViewModelTest with the MainCoroutine Rule
Fixes # 
N/A
=> Main Coroutine Rule Cleanup

wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/networking/PocketCastsNetworkingRules.kt, wear/src/test/kotlin/au/com/shiftyjelly/pocketcasts/wear/networking/PocketCastsNetworkingRulesTest.kt
This fixes a bug where episodes would not be downloaded over Bluetooth. This meant that if you started downloading an episode on wifi, then lost your wifi connection, the download would stop until the wifi connection was regained.
I believe this will improve the situation reported in https://github.com/Automattic/pocket-casts-android/issues/1113, but there may be more to do here so I'm leaving that issue open.
> **Warning**
> This PR is targeting the `release/7.41` branch
Verify that downloads follow these rules:
- If a wifi network is available, it uses that, otherwise
- If a cellular network is available, it uses that; otherwise
- It uses BT if available
The last bullet is the most important. Verify that if you only have a Bluetooth connection you can download an episode.
Note that …
=> Enable watch to use bluetooth to download episodes

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/SimplePlayer.kt
This reduces buffer time for the watch app.
1. Try playing an episode on a slow network in watch app
2. Notice that it starts playing sooner
=> Use reduced buffer for watch app

app/src/test/java/au/com/shiftyjelly/pocketcasts/analytics/AppLifecycleAnalyticsTest.kt, modules/features/shared/build.gradle, modules/features/shared/src/main/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserver.kt, modules/features/shared/src/test/java/au/com/shiftyjelly/pocketcasts/shared/AppLifecycleObserverTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AppLifecycleAnalytics.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt
This updates the auto play setting to only default to true for new installations.
For all these tests, the up next queue needs to be empty.
1. Install a build from this PR with the [version code](https://github.com/Automattic/pocket-casts-android/blob/dc7084f631248d0c65d5d37c1ad1b57d539c9ccc/base.gradle#L23) set to 1
2. Verify that the auto play setting is enabled
3. Upgrade the installation by Installing a build from this PR with the [version code](https://github.com/Automattic/pocket-casts-android/blob/dc7084f631248d0c65d5d37c1ad1b57d539c9ccc/base.gradle#L23) set to 2
4. Verify that the auto play setting is still enabled
1. Install a build from this PR with the [version code](https://github.com/Automattic/pocket-casts-android/blob/dc7084f631248d0c65d5d37c1ad1b57d539c9ccc/base.gradle#L23) …
=> Default autoplay on for new installations only

modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt, modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/providers/DefaultReleaseFeatureProvider.kt, modules/services/localization/src/main/res/values/strings.xml
Adds the bookmarks feature flag and only enables it in debug while we work on the feature.
3. Go to Profile > Settings cog > Beta features
4. ✅ Verify the feature flag is listed there
=> Bookmarks: Adds the feature flag

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/BookmarkDao.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/entity/BaseEpisode.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryModule.kt
This adds a bookmarks data manager to help access the bookmark DAO. I have added some methods but we might need more as we add the feature.
There isn't much to test here. If it passes the tests it should be good to start using.
=> Bookmarks: Add a data manager

modules/services/localization/src/main/res/values-ar/strings.xml, modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-en-rGB/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nb/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, version.properties
=> Merge release/7.43 into main

modules/services/localization/src/main/res/values/strings.xml
While getting the English UK translations up to 100%, I noticed some fixes in the string.xml file.
=> Fixing the localization file

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HeadphoneControlsSettingsFragment.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/MediaSessionManager.kt
Sorry @ashiagr, I told you completely the wrong thing in our meeting yesterday. This PR changes it back to what you had previously.
=> Changed media controls after headset testing

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt
This reverts refresh interval to original values (temporarily changed in #1290)
=> Fix refresh interval

modules/features/settings/src/main/AndroidManifest.xml, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpActivity.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/HelpFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/LogsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/SettingsFragmentPage.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/status/StatusFragment.kt
This fixes docsbot not loading issue
p1693818175061479-slack-C02A333D8LQ
1. Launch the app 
2. Go to `Profile` -> `Help & feedback`
3. Tap on Help button (in red) at the bottom right corner
4. Notice that the docsbot loads
=> Fix docsbot not loading

.github/ISSUE_TEMPLATE/bug_report.yml
I added a description on the issue template to make it easier for someone new to find the current app version when reporting a bug 
Fixes # N/A
=> Added Description to find app version

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
This change reduces the time it takes to record a Track event. It seems like when a member variable is used that has a property accessed by a `get()` each time it's used, the value is recalculated. The variable `paidSubscription` was called multiple times and this calls `settings.cachedSubscriptionStatus`. The cachedSubscriptionStatus seems to be quite slow so now the result is cached.
1. Filter logcat by Tracked
2. ✅ Verify the analytics include the Track event properties.
=> Improved performance of recording a Track event

modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/TracksAnalyticsTracker.kt
We add the Tracks events on the main thread. It seems like a good idea to push this onto a background thread so the library or our code to build the event doesn't hold up the UI.
1. Tap areas of the app
2. Check the events are being output in logcat
=> Move the Tracks record event off the main thread

CHANGELOG.md, modules/services/featureflag/src/main/java/au/com/shiftyjelly/pocketcasts/featureflag/Feature.kt
Enables the Patron feature flag
1. Run the app
2. ✅ Verify Patron appears in the upgrade view
3. ✅ Verify Patron appears in the account details view
4. ✅ Verify purchasing Patron unlocks it and the new app icons
=> Enables the Patron Feature Flag

dependencies.gradle
This updates play billing library version to 5.2.1. Ref: pdeCcb-3t4-p2
Prerequisites
1. Login with a free account
2. Subscribe to Plus
3. ✅  Notice that the subscription succeeds
=> Update billing client version

automotive/build.gradle, base.gradle, dependencies.gradle, gradle/libs.versions.toml
As part of our tech debt, this PR gives a small example of how the libraries will be migrated to the version catalog. If this is approved I will raise some more PRs to complete this.
1. Full clean and build the app
2. ✅ Verify the app still runs
=> Starting migrating libraries to the version catalog

automotive/build.gradle, base.gradle, dependencies.gradle, gradle/libs.versions.toml, modules/features/account/build.gradle, modules/features/cartheme/build.gradle, modules/services/analytics/build.gradle, modules/services/model/build.gradle, modules/services/sharedtest/build.gradle, wear/build.gradle
This is the final part of the tech debt migration to move to a version catalog that Google recommends.
1. Build and run the app
2. ✅ Verify there are no new warnings in the build output.
3. ✅ Verify there are no exceptions in logcat.
4. Login to an active sync account.
5. ✅ Verify the podcast and episode sync data is working. 
6. ✅ Verify the listen history is populated. (Check the Work Manager jobs are successful.)
7. ✅ Verify on the Profile tab that the refresh has been successful.
8. ✅ Verify there are no exceptions in logcat.
=> Migrating libraries to the version catalog

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellView.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModel.kt, modules/features/player/src/test/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/components/UpsellViewModelTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/whatsnew/WhatsNewViewModel.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/whatsnew/WhatsNewViewModelTest.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/UpsellButtonTitle.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This extracts
- Free trial flow for subscription tier to `SubscriptionManager` 
- `UpsellButtonTitle` composable 
1. CI should be green
2. Optionally, check that bookmark views and what's new dialog display upsell button appropriately
What's New | Bookmarks
-----|-----
=> Extract free trial info

modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt
This increments whats new version code.
> **Warning**
Targets 7.52
1. Launch the app from a previous version 
2. ✅ Verify you see the What's New
=> Update whats new version code

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelperTest.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModel.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/stats/StatsViewModelTest.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/review/InAppReviewHelper.kt
- This is part of #1672
- This PR removes In app review feature flag
Closes: #1673
=> Remove In app review feature flag

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureItem.kt, modules/services/localization/src/main/res/values-ar/strings.xml, modules/services/localization/src/main/res/values-de/strings.xml, modules/services/localization/src/main/res/values-en-rGB/strings.xml, modules/services/localization/src/main/res/values-es-rMX/strings.xml, modules/services/localization/src/main/res/values-es/strings.xml, modules/services/localization/src/main/res/values-fr-rCA/strings.xml, modules/services/localization/src/main/res/values-fr/strings.xml, modules/services/localization/src/main/res/values-it/strings.xml, modules/services/localization/src/main/res/values-ja/strings.xml, modules/services/localization/src/main/res/values-ko/strings.xml, modules/services/localization/src/main/res/values-nb/strings.xml, modules/services/localization/src/main/res/values-nl/strings.xml, modules/services/localization/src/main/res/values-pt-rBR/strings.xml, modules/services/localization/src/main/res/values-ru/strings.xml, modules/services/localization/src/main/res/values-sv/strings.xml, modules/services/localization/src/main/res/values-zh-rTW/strings.xml, modules/services/localization/src/main/res/values-zh/strings.xml, modules/services/localization/src/main/res/values/strings.xml
- This minor PR is to address suggestions from #1695
- Feel free to follow the instructions from #1695
=> Bookmarks benefits strings updates

.github/workflows/submit-gradle-dependencies.yml
It's supplemental PR to #1710 . In the previous PR I forgot that there are more deliverables in this project that only the mobile app. This PR fixes that.
No need for manual tests, I've verified this on fork.
=> Submit `wear` and `automotive`  dependencies to GitHub as well

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt
Fixes formatting in the `main` branch.
=> Fix formatting

modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateAccountFragment.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateFrequencyAdapter.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreateFrequencyFragment.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/CreatePayNowFragment.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/components/ProductAmountVerticalText.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeBottomSheet.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/ProfileUpgradeBanner.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionPriceSection.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/SubscriptionProductAmountHorizontal.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeFeatureCard.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/CreateAccountViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeBottomSheetViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/ProfileUpgradeBannerViewModel.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/AccountDetailsViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/buttons/UpsellButtonTitle.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/images/SubscriptionBadge.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- This PR merge all intro offer changes to `main`
- All changes was already tested in the PRs to `feature/intro-plus-offer`
- The feature is behind `INTRO_PLUS_OFFER_ENABLED` FF
=> Intro offer: Merge changes to main

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Part of #1807 
This adds a remote + local feature flag for the "Deselect Chapters" feature.
1. `setMinimumFetchIntervalInSeconds` to 5L (5 secs) in `FirebaseModule`
2. Add a log statement in `SettingsFragmentPage` > line 100 on click of About page that prints `FeatureFlag.isEnabled(Feature.DESELECT_CHAPTERS)`
3. Install release build
4. Launch the app 
5. Go to Profile -> Settings and tap About
6. ✅ Notice in logs that the feature flag for deselect chapters is false
1. Set `deselect_chapters` to true in `Firebase` remote config for Android app and publish changes
2. Kill the app
3. Restart the app
4. Go to Profile -> Settings and tap About
5. ✅ Notice in logs that the feature flag for deselect chapters is true
Important (after tests are completed):
- Reset `deselect_chapters` to false in …
=> Add feature flag

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
Until now, we allowed users to upgrade to a more expensive tier like `Plus` to `Patron` using the `Upgrade to Patron` option on the `Pocket Casts Account` page.
There can now be scenarios when users can switch between billing plans within the same tier (e.g. from the What's New announcement where a monthly plan user can be prompted to change their subscription to avail a yearly benefit). 
This PR applies subscription replacement modes for such scenarios.
1. Install release build and launch the app
2. Login with a license testing free account
3. Go to `Profile` -> `Account` 
4. Tap `Subscribe to Plus` and subscribe to the monthly Plus plan
5. Apply [this patch](https://github.com/Automattic/pocket-casts-android/files/14457456/Update_replacement_mode.patch) that displays What's New on every …
=> Subscription - Update replacement mode

gradle/libs.versions.toml
In #1814 I updated some of the dependencies including Kotlin coroutines. There is a bug in the current version that causes crashes on some Android devices. See: https://github.com/Kotlin/kotlinx.coroutines/issues/3820
`1.8.1-Beta` release should fix the issue according to [this comment](https://github.com/Kotlin/kotlinx.coroutines/issues/3820#issuecomment-1992695284).
Smoke test the app.
=> Upgrade coroutines to `1.8.1-Beta`

modules/features/player/build.gradle.kts, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/BindingAdapters.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/binding/ViewExtensions.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerBottomSheet.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoFragment.kt, modules/features/player/src/main/res/layout/view_player_bottom_sheet.xml
This PR disables data binding in `player` module.
Not needed - as the app builds on CI, we're good.
=> Disable data binding in `player` module

app/build.gradle.kts, automotive/build.gradle.kts, wear/build.gradle.kts
Closes: #1908 
This PR disables data binding in the project. No testing is needed, as CI checks **should** be fine. If you want a double check, please checkout this PR and run `./gradlew assembleRelease --rerun-tasks`.
=> Disable data binding in the project 🎉

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Update `CATEGORIES_REDESIGN` feature flag
- Code review and CI should be fine
=> [Categories Redesign] Update feature flag

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt
Fixes #1997
This fixes an occasional episode re-download issue after the download task is canceled. 
It appears that sometimes re-starting a download for an archived episode enters into this part of the code:
https://github.com/Automattic/pocket-casts-android/blob/34b2a8b4e77062ae9903bc7835b825a97fa6ad8d/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt#L144-L148
which is handled here where the canceled download task is not cleared in the DB:
https://github.com/Automattic/pocket-casts-android/blob/34b2a8b4e77062ae9903bc7835b825a97fa6ad8d/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt#L196-L211
As a result, the flow enters into this part where …
=> Cleanup download task for cancelled episode download

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/models/db/ChapterDaoTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/ChapterDao.kt
Follow up to #2098. Just a sanity check to make sure that we don't clear chapters.
I added a test so green CI is enough.
=> Do not replace chapters if new ones are empty

version.properties
- Fix version code and version name
Play Store:
=> Fix version code and version name

version.properties
=> Fix version code for 7.62.2

build.gradle.kts, modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt, modules/services/servers/build.gradle.kts, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt
This PR brings Performance Monitoring integration to the app.
1. Apply below PATCH or manually change values
<details>
<summary>
PATCH
</summary>
```PATCH
Subject: [PATCH] Verify network state when enqueuing encrypted logs
If event is fatal (meaning: crash), do not send encrypted logs immediately because it won't likely finish. Encrypted logs will be sent on the next app start
---
Index: modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingD …
```
=> Introduce performance monitoring

app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParser.kt, modules/services/utils/src/test/java/au/com/shiftyjelly/pocketcasts/utils/SharingUrlTimestampParserTest.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/activity/WebViewActivity.kt
Since our app doesn't have capabilities to play clips of episodes we need to redirect to a web view. And web view allows to play the full episode in the app.
Internal refs: pdeCcb-3RS-p2#comment-4181, pdeCcb-3RS-p2#comment-4169 
> [!note]
> Before starting the test make sure in the settings that the app is able to intercept the links.
1. Install the app and sign in.
3. Send intent via ADB with start and end timestamps. For example: `adb shell am start -a android.intent.action.VIEW -d https://pca.st/y0ebrkcc\?t=20,60`.
4. App should intercept the link and open it in a web view.
5. You should be able to play the clip.
6. Tap on the `Full episode in Pocket Casts` button.
7. The episode should start playing in the app from the start timestamp. …
=> Open clip links in a web view

Gemfile.lock
This PR updates our tooling dependencies with the newest PATCH versions to address https://github.com/Automattic/pocket-casts-android/security/dependabot/50
Fixes # 
Not needed
=> Bump `rexml` to `3.2.8` and `wpmreleasetoolkit` to `11.0.2`

automotive/src/main/AndroidManifest.xml, automotive/src/main/res/xml/automotive_app_desc.xml
This includes media meta-data needed for Automotive media app.
Internal reference: pdeCcb-5BU-p2#comment-4343
CI should be green.
=> Include media meta-data needed for automotive media app

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/StoriesViewModel.kt
`StoriesViewModel` used `kotlin.concurrent.fixedRateTimer` which creates `Timer` running on the main coroutine dispatcher. I'm not entirely sure why there was a race condition and why tests for the view model were flaky but you can see it, for example, [here](https://buildkite.com/automattic/pocket-casts-android/builds/6609#018f8163-5ef6-4984-867d-88708c5c9706).
```
Exception in thread "Timer-12" java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize. For tests Dispatchers.setMain from kotlinx-coroutines-test module can be used
at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:111)
at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:92)
at …
```
=> Do not use Timer in StoriesViewModel

gradle/libs.versions.toml, modules/features/taskerplugin/build.gradle.kts
This updates Tasker plugin from 0.4.6 to 0.4.10
Fixes #2354
1. Login to Pocket Casts debugProd application with filters
2. Install and open MacroDroid application
3. Create Macro
4. Add `Action` -> `Applications` -> `Tasker/Locale Plugin `-> `Pocket Debug`
5. Select Event Type "Play Filters" for testing.
6. Select Filter
7. Click on the created Action
8. Test Action
9. ✅ Notice Pocket Casts starts playing filter episodes
MacroDroid
https://github.com/Automattic/pocket-casts-android/assets/1405144/92e746dd-4895-4e05-bdda-43874e613230
(This test is optional. See the video for this test.)
1. Login to Pocket Casts debugProd application
2. Install and open Tasker application
3. Go to Tasks tab and create a task
4. Add `Action` -> `Pocket Debug` ->  `Pocket Casts Query Podcast Episodes`
5. …
=> Bump Tasker plugin

app/src/main/java/au/com/shiftyjelly/pocketcasts/di/AppModule.kt, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/di/AutomotiveAppModule.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipAnalytics.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ClipPlayer.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipFragment.kt, modules/features/clip/src/main/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModel.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/FakeClipPlayer.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/FakeTracker.kt, modules/features/clip/src/test/kotlin/au/com/shiftyjelly/pocketcasts/clip/ShareClipViewModelTest.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShareFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/ShelfBottomSheet.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/SourceView.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareActionProvider.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/dialog/ShareDialog.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/di/WearAppModule.kt
This PR implements clip analytics.
Verify these events: https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=A596:AA600
=> Add analytics to clip sharing

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/AppDatabase.kt
Adds "if not exists" clause to create table query
- Smoke test db migration
=> Update transcript create table query

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/SwipeableStars.kt
- Sets minimum rating to 1 star
Fixes #2422
Make sure `GIVE_RATINGS` feature flag is enabled
1. Open a podcast that you listened any episode before
2. Tap to Rate the podcast
3. Try to rate with zero star or either half star
4. ✅ Ensure you have at least one star selected
[Screen_recording_20240703_142818.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/bf55b5cc-7185-4e0d-a540-dd97d82c9b29)
=> [Give Rating] Set Minimum rating to 1 star

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/GiveRatingFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/components/ratings/SwipeableStars.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/GiveRatingViewModel.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/PodcastRatingAdd.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServer.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt
- This PR adds the ability to rate a podcast calling the API
- See: p1720438636666779-slack-C077XU4GF9D
1. Run the app in `debug`
3. Listen to at least 2 episodes from this podcast (scroll to almost the end of the episode)
4. Tap to rate
5. If you have a success response you will see something like `{
"podcastUuid": "3c5900ab-dc52-4af2-bed8-f488f3e565ce",
"modifiedAt": "2024-07-08T23:12:13.658Z",
"podcastRating": 3
}` as response. 
6. Ensure you see the toast with `Thank you for rating!` message
7. Otherwise, you should see a toast with `Could not rate this podcast` message
[Screen_recording_20240708_201733.webm](https://github.com/Automattic/pocket-casts-android/assets/42220351/e272d3f5-b73a-46e5-b26f-43cef13be026)
=> [Give Rating] Add rate podcast

modules/features/nova/src/main/kotlin/au/com/shiftyjelly/pocketcasts/nova/NovaLauncherBridge.kt
=> Fix Nova Launcher logs

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Add a FF for the Reimagine Sharing project.
=> Add reimagine sharing flag

modules/features/sharing/src/main/kotlin/au/com/shiftyjelly/pocketcasts/sharing/ShareViewModel.kt
Reading playback timestamp changes from player is more accurate since updates there are more frequent than in the database. This allows for better granularity when sharing an episode timestamp.
Smoke test sharing podcast, episode, and episode timestamps from the player.
=> Make timestamp sharing more accurate

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Enable remote FF
code review should be enough
=> [Kids] Enable remote FF

modules/features/kids/build.gradle.kts, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsBottomSheetDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/KidsSendFeedbackDialog.kt, modules/features/kids/src/main/java/au/com/shiftyjelly/pocketcasts/kids/viewmodel/KidsSendFeedbackViewModel.kt, modules/features/kids/src/test/java/au/com/shiftyjelly/pocketcasts/KidsSendFeedbackViewModelTest.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileFragment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt
- Add tracks for kids profile
Fixes #2552
- Have kids feature flag enabled
- Verify [these events](https://docs.google.com/spreadsheets/d/107jqrutZhU0fVZJ19SBqxxVKbV2NWSdQC9MFYdLiAxc/edit?gid=0#gid=0&range=548:556) and make sure they are tracked
https://github.com/user-attachments/assets/69b17452-0b76-40a6-b401-000c58d3d3a6
=> [Kids Profile] Add tracks

modules/services/localization/src/main/res/values/strings.xml
- Updates what's new title and text for Give Ratings
- See: p1723115634468679/1722365320.671129-slack-C077XU4GF9D
1. Apply [whats_new.patch](https://github.com/user-attachments/files/16548888/whats_new.patch)
2. Check the what's new
=> [Give Rating] Update whats new texts

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Remove the remote feature flag from version 7.70 since the complete version will be available only in version 7.71
- Code review is fine
=> [Kids Profile] Remove remote feature flag

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/transcripts/TranscriptPage.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/extensions/Modifier.kt
This improves loading large transcripts. 
Loading an entire annotated text in the `Compose` text view was inefficient.  During search implementation, it became more apparent due to styling for highlighting search results. To address this, this PR adopts a `LazyColumn` for text rendering.
I'll submit search implementation PRs on top of this PR.
1. Load large transcript (E.g. for episode https://pca.st/1iofzvym with ~4 hrs duration)
2. ✅ Notice that UI does not block while setting large text
3. Scroll the text
4. ✅ Notice that the scrollbar works properly 
After
https://github.com/user-attachments/assets/f2e653d8-dc63-49b3-b465-994552497309
Before (notice lag at timestamp 0:06)
https://github.com/user-attachments/assets/89cb437b-a1e7-479f-9323-e6b5ffae27cd
=> Transcipts - Display text using LazyColumn

fastlane/Fastfile
So the comment will be at the top. Internal context: p1723720447403789/1723600178.303059-slack-C028JAG44VD
=> Comment on PR just after prototype builds job starts

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProviderTest.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/OnboardingUpgradeFeaturesPage.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/onboarding/upgrade/UpgradeLayout.kt, modules/features/account/src/main/java/au/com/shiftyjelly/pocketcasts/account/viewmodel/OnboardingUpgradeFeaturesViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/di/TrackerModule.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Experiment.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/ExperimentProvider.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/experiments/Variation.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This change adds an A/A test to make sure we have the Firebase A/B testing setup correctly.
Fixes https://github.com/Automattic/pocket-casts-android/issues/2609
1. Apply the following patch [test.patch](https://github.com/user-attachments/files/16638238/test.patch)
2. Change the variant to `release`
3. Tap on the Profile tab
4. Tap settings
5. Tap 'Pocket Casts Plus'
✅ Verify in the logs the experiment and variation are output
```
Experiment PaywallAATest, variation Control
```
=> Add A/A test

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Just adds the remote feature flag for kids profile
Fixes #2608
=> [Kids Profile] Add remote Feature flag

CHANGELOG.md
Adds changelog for transcripts
=> Transcripts - Add changelog

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcessTest.kt, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/servers/account/SyncAccountTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/di/AppModule.kt, automotive/src/main/java/au/com/shiftyjelly/pocketcasts/di/AutomotiveAppModule.kt, base.gradle, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/Annotations.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/di/RepositoryProviderModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/task/DownloadEpisodeTask.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/Interceptors.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/ServerManager.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/InterceptorModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/di/ServersModule.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServerManager.kt, wear/src/main/kotlin/au/com/shiftyjelly/pocketcasts/wear/di/WearNetworkModule.kt
Our current `OkHttp` client dependency injection configuration needs some improvement. We don't share the dispatcher between multiple clients, we have unused clients, and navigating the `ServersModule` has become challenging due to the extensive DI configuration. To address these issues, I've made the following changes:
- **Moved interceptor configuration**: All interceptor configurations have been relocated to a separate `InterceptorsModule`.
- **Removed unused clients**: Cleaned up the code by removing clients that are no longer in use.
- **Simplified qualifier annotations**: Consolidated the annotations by replacing `@TranscriptsCache`, `@TranscriptsClientBuilder`, and `@TranscriptsClient` with a single `@Transcripts` annotation.
- **Shared connection pool**: Most clients now share the …
=> Clean up OkHttp configuration

modules/services/localization/src/main/res/values/strings.xml
https://github.com/Automattic/pocket-casts-android/pull/2745#issuecomment-2316152061
=> Fix a typo

build.gradle.kts, modules/services/repositories/build.gradle.kts
A small follow up to dependencies cleanup. I didn't account for Mockito Android being incorrectly reported and Protobuf kotlinlite got out of sync due to merges.
CI checks are enough.
=> Clean up dependencies config

.buildkite/shared-pipeline-vars
To fix not sending `sarif` files on the main branch.
Follow up to #2828
=> Bump CI toolkit to 3.6.1

.buildkite/shared-pipeline-vars
If fix will work correctly, I'll follow up with the semver version
=> Apply fix for not sending sarif file on the main branch

gradle/libs.versions.toml, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/viewmodel/PodcastViewModel.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/Theme.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/bookmark/BookmarkHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/download/DownloadManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsThread.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/TokenErrorNotification.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/widget/WidgetManagerImpl.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/Util.kt, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/extensions/Context.kt
Android Studio recommended upgrading the Android Gradle Plugin, so this change does that. As this is a minor upgrade, I haven't involved the Apps Infrastructure team. 
Build the project and check it runs. 
`./gradlew clean assemble`
=> Upgrade AGP to 8.6.0

.github/dependabot.yml
This will make sure that our GH Actions dependencies are also up to date.
N/A
=> Include GH Actions in Dependabot updates

modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/ExportSettingsFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/helper/OpmlExporter.kt
- Remove the deprecated usage of `onActivityResult` from OPML files import code
- Remove unused OPML export files code
- Smoke test OPML files import and export
- You can use this file p1705580029359379/1705580020.681289-slack-C02A333D8LQ, but feel free to use yours.
=> [Tech Debt] Remove deprecated code from OPML files import code

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Add remote feature flag for Paywall Experiment, in order to manage this feature in `7.74`
- The feature was added here https://github.com/Automattic/pocket-casts-android/pull/2871
- You can also check the name of the feature flag in firebase to see that matches with the local one
=> [Paywall Experiment] Add remote feature flag

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralGuestPassCardView.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassBannerCard.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassError.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsIconWithTooltip.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassViewModel.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModel.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassViewModelTest.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassViewModelTest.kt, modules/features/referrals/src/test/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsViewModelTest.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/ReferralProductDetails.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/ReferralsOfferInfo.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/Subscription.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionPricingPhase.kt, modules/services/repositories/src/debug/kotlin/com/android/billingclient/api/ProductDetailsModule.kt, modules/services/repositories/src/debugProd/kotlin/com/android/billingclient/api/ProductDetailsModule.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralOfferInfoProvider.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralOfferInfoProviderTest.kt
This displays offer duration and price on referral screens using hard-coded test product id and offer id.
1. Launch the `debugProd` or `debug` build variant
2. Login with a paid account
3. Go to the profile screen
4. ✅ Notice that referral screens are populated using play store offer info
6. Change currency price or currency code in `yearlyTestPlusProduct` of `ProductDetailsModule` of the installed build variant
7.  Go to the profile screen and tap the referral  banner
8. ✅ Notice that currency price and code are displayed correctly 
9. Remove `yearlyTestPlusProduct` or change its `productId`/ `offerId` in `ProductDetailsModule` of the installed build variant
10. Reinstall the app
11. ✅ Notice that referral icon and the banner are not shown if the product or offer does not exist in …
=> Use Play Store referrals info

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/AccountManagerStatusInfo.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/sync/AccountManagerStatusInfoTest.kt
- I wrote unit tests when I was working on this PR https://github.com/Automattic/pocket-casts-android/pull/2943, but since I had to change the approach, the unit tests should not be there anymore. So I am adding here in a separate PR
- CI 🟢 and code review should be fine
=> [Tech Debt] Add unit tests for Account manager 

modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/AutoDownloadLimitSetting.kt
- Removes All Latest Option
- Context: p1728629479247849-slack-C07QMC2GB1B
Fixes #3002
=> [Auto Downloading] Remove All Latest Option 

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/PodcastManagerImpl.kt
- Currently, we have the auto download feature, which downloads all new episodes from a podcast
- After we added the new flag `Limit Downloads` here https://github.com/Automattic/pocket-casts-android/pull/2980, we want to start limiting the number of episodes that are downloaded after a podcast releases new episode if the user has auto download feature enabled
> [!NOTE]  
> I will double check and handle in another PR if it's necessary to sort the already build list of episodes by publish date. They all already sorted in my test, but I wanted to check this
Fixes #3031
1. To start testing this, we need to update our developer tools so we can modify the behavior of `Delete First Episodes` to delete 10 episodes instead of just 1. So, you can apply this …
=> [Auto Downloading] Use Auto Download Limit when auto download episodes in new releases

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/NumberOfShowsStory.kt
This updates Number of Shows story UI to align it with the new design.
Figma: lH66LwxxgG8btQ8NrM0ldx-fi-3434_13444
Start PB24 and verify Number of Shows story.
https://github.com/user-attachments/assets/76b94f46-d657-4007-9383-08c5ad7fa09e
=> Update Number of Shows story design

app/src/main/AndroidManifest.xml, automotive/src/main/AndroidManifest.xml, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/db/dao/UpNextChangeDao.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/jobs/JobIds.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueue.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/UpNextQueueImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/SyncManagerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/UpNextSyncWorker.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncService.kt, modules/services/servers/src/main/java/au/com/shiftyjelly/pocketcasts/servers/sync/SyncServiceManager.kt, wear/src/main/AndroidManifest.xml
This migrates `UpNextSyncJob` to a worker. While migrating, I converted methods that were only used by the up-next sync worker to suspended in separate commits so it is easier to review the changes by commits. 
Part of #3009
1. Login with a paid account on the web player and Android app
2. Add a few episodes to your `UpNext` queue in the Android app
3. ✅ Notice that up next count updates correctly in the mini-player
4. Tap refresh in the `Profile` tab
5. Reload web player
6. ✅ Notice that `UpNext` queue is synced properly in the web player
7. Add an episode from web player to `UpNext` queue
8. Tap refresh in the `Profile` tab on Android app
9. ✅ Notice that `UpNext` queue is synced properly in the Android app
1. Open `UpNext` screen
2. Long press any episode from the `UpNext` queue so …
=> Migrate `UpNextSyncJob` to worker

app/build.gradle.kts, app/src/main/java/au/com/shiftyjelly/pocketcasts/PocketCastsApplication.kt
This PR removes Nova integration point so the code doesn't end up in the final APK.
Context: pdeCcb-520-p2#comment-5832
=> Remove Nova integration point

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This updates the changelog for Referrals.
=> Referrals: Update changelog

modules/features/endofyear/src/main/java/au/com/shiftyjelly/pocketcasts/endofyear/ui/CompletionRateStory.kt
Part of feedback from #3169
>  Can we animate this screen in a similar way to the ratings screen? (the bars animating from the bottom up)
1. Start PB24 as a paid user.
2. Go to the Completion Rate story.
3. Verify the animation.
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/6d809513-d98c-4ec5-9642-7f76c6ee8cd4"></td>
<td><img src="https://github.com/user-attachments/assets/c6cd104d-e2e7-43b8-8a8c-d2d7630dec8d"></td>
<td><img src="https://github.com/user-attachments/assets/07a944ce-230d-406e-a055-6301ae7de706"></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/561739bb-993f-49cf-9f95-e72bb1c50b00"></td>
<td><img src="https://github.com/user-attachments/assets/64693853-74ea-40ad-bf19-c9000bf5d110"></td>
<td><img …
=> Update completion rate story animation

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Enable the remote feature flag for this feature
Fixes #3096
- Code review is fine
=> [Project] Manage Downloaded Episodes - Enable remote feature flag

CHANGELOG.md
Release notes used wrong indentation.
=> Fix release notes formatting

CHANGELOG.md, lint.xml, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerSeekBar.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackManager.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/PlaybackState.kt
This cherry-picks #3217 and #3219 into the v7.77 release. It would be good to include these changes with the changes to custom playback effects in beta.
=> Cherry pick #3217 and #3219 into 7.77

modules/services/localization/src/main/res/values/strings.xml
This updates referral share message. I'll include the image in another PR.
1. Tap referral icon on Profile tab
2. Tap Share Guest Pass
3. Share using email
4. ✅ Notice that the share message is updated to the one mentioned in p1732059551376689-slack-C07HDV91FBQ
=> Update referral share message

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileHeader.kt, modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/ProfileStats.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
Aligns the design with iOS. See: p1732063286691349-slack-C05RR9P9RAT
Verify profile header UI.
| - | - |
| ![bef](https://github.com/user-attachments/assets/2aea198a-8711-4c98-8211-727cf4541e34) | ![af](https://github.com/user-attachments/assets/0b060522-81f9-4c67-89e8-55d424024567) |
=> Update profile header UI

gradle/libs.versions.toml
See: p1733825245718549-slack-C028JAG44VD
=> Revert "Bump androidx.constraintlayout:constraintlayout-compose from 1.0.1 to 1.1.0"

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/playback/auto/AlbumArtContentProvider.kt
Our current implementation of providing artwork to media notifications crashes the OS on Android 15. The issue arises because we always try to convert image paths to URLs, which is not applicable for embedded artwork. This throws an `IllegalArgumentException` when attempting to convert a URI's path to a URL. This wasn't an issue before because the OS handled it gracefully, but Android 15 apparently changed the implementation and shuts down when an exception is thrown from a `ContentProvider` while getting a file descriptor.
This PR addresses the issue by adding more safeguards and checking whether the data can be processed, preventing exceptions from being thrown Additionally, I wrapped everything in a `runCatching` block to ensure that even if something fails, we do not crash but simply …
=> Do not use local files for ParcelFileDescriptor

modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsClaimGuestPassPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassError.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsGuestPassFragment.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsInvalidOfferPage.kt, modules/features/referrals/src/main/kotlin/au/com/shiftyjelly/pocketcasts/referrals/ReferralsSendGuestPassPage.kt, modules/services/ui/src/main/res/values/themes.xml, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/multiselect/MultiSelectToolbar.kt
This change adds support for edge-to-edge to the Referrals page.
**Send a referral code**
1. Login as a Plus user
2. Go to the Profile tab
3. Tap the gift icon
4. ✅ Verify the top and bottom of the content isn't hidden by the status or navigation bar
**Claim a referral code**
1. Open the claim screen `adb shell am start -a android.intent.action.VIEW -c android.intent.category.BROWSABLE -d "https://pocket-casts-main-development.mystagingwebsite.com/redeem/abc"`
2. ✅ Verify the top and bottom of the content isn't hidden by the status or navigation bar
| --- | --- |
| ![before-send](https://github.com/user-attachments/assets/c4bd64d9-d876-40d7-83c2-6c335ddebec0) | ![after-send](https://github.com/user-attachments/assets/66fc35b4-d233-4c87-b0dc-87a4e733ad27) | 
| …
=> Fix Referrals edge-to-edge

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/BillingClientWrapper.kt
In https://github.com/Automattic/pocket-casts-android/pull/3441 I changed how billing client is set up. However, I didn't know that once the connection is dropped it cannot be recreated and a new clients needs to be initialized. This PR fixes this mistake by managing the client state.
I'll probably end up cherry-picking this change onto `7.81` beta.
I can't provide any reliable tests for this one. Just smoke test usual IAP things like purchasing a subscription, etc.
=> Recreate billing client if connection fails

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/bookmark/BookmarksPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcast/adapter/BookmarkViewHolder.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/bookmark/BookmarkRow.kt, modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/components/TextStyles.kt
- This fixes some smalls design issues for Bookmarks screen
- Round the corners of the artwork
- Reduce the line height for the bookmark title
- Add Placeholder for Bookmark icon
- Figma: Io7PCz1H1hmOgEE9eljoYW-fi-2036_44518
- I will create another GH issue to address the more actions button to toolbar since I faced with some issues to move it here
Fixes #2147
1. Create some bookmarks
2. Go to Profile -> Bookmarks
3. Check the updated screen
| ![before](https://github.com/user-attachments/assets/4b6d1297-81d6-4013-a382-797101e9375e) | ![after](https://github.com/user-attachments/assets/d9198d06-411f-4125-966d-6493595a2b7e) |
=> Bookmarks Tweaks

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/SubscriptionManagerImpl.kt
This fixes 2 issues:
* Undelivered purchase failure events.
* Multiple attempts to acknowledge a purchase.
This is done by keeping a temporary reference in a concurrent hash set until we're done processing it.
It's hard to give any reliable steps. Smoke testing purchases should be enough.
=> Improve purchase failure events

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPaywallBottomSheet.kt
- Just fixes the source
- Code review is fine
=> [Suggested Folders] Fix Suggested Folders Paywall Source

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This enables Firebase connection for the Winback FF.
I won't merge it until we're certain about the release version.
=> Connect winback remote feature flag

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/support/Support.kt
This PR adds auto-play settings to the Support logs.
Context: p1739524600986019-slack-C06EHRAPW12
Try different auto-play configurations and check logs for each of them.
* Auto-play enabled and disabled.
* Different sources: podcasts, filters, downloads, etc.
You should see something like this in the logs:
```
Auto-play settings
Is enabled? true
Latest source: Downloads
```
=> Add auto-play setting to Support logs

version.properties
There is a merge issue with the "Merge release/7.83 into main" I hope this will fix that.
=> Fix the 7.83-rc-2 merge issue

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/subscription/BillingClientWrapper.kt
We have [reports](https://a8c.sentry.io/issues/6238390148/?project=6711064) of crashes due to the Billing Client connection dispatch. I'm not exactly sure why this happens since dispatch is wrapped with the `isActive` check to prevent this exact scenario. It appears that `onBillingSetupFinished()` and `onBillingServiceDisconnected`() can run in parallel causing the continuation to be resumed multiple times.
Smoke test buying a subscription.
=> Wrap Billing client connection dispatch in try/catch

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Adds remote feature flag
- Updates CHANGELOG
=> [Suggested Folders] Add Remote feature flag

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFolders.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersPage.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/localization/src/main/res/values/strings.xml
- Adds the how it works dialog
- I am proposing some changes for the How it works label color. You can check on this link below. When I get feedback from Dom I will update here.
- See: p1740643726953609/1740626371.709879-slack-C08BRS7N9UL
1. Have paid account with followed podcasts
2. Open Suggested folders screen
3. See the How it works ✅
4. Tap on it
5. Should open how it works dialog ✅
[Screen_recording_20250227_140048.webm](https://github.com/user-attachments/assets/0a3edf40-5f8a-4f97-99ae-bfbf1926de31)
=> [Suggested Folders] Add How it Works

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
- Since we are still working on more required changes. I need to revert this #3670 to remove the remote feature flag and add it back again once finish all tasks
Code review should is fine
=> [Suggested Folders] Revert remote FF

CHANGELOG.md, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsOptionsDialog.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/PodcastsSortType.kt
This reorders existing podcasts' sorting options based on their popularity. **
Figma: 4F4PokoLUFmOl5eIT57B5z-fi-20_1824
P2: pdeCcb-8t7-p2
** It appears to be a harmless change. Including it in `7.85` should be okay without putting it behind a feature flag.
1. Install fresh app
2. Go to Podcasts tab
3. Tap on toolbar more menu
4. Tap on `Sort by` in the more options
5. ✅ Notice that sort options are arranged as per Figma and P2 post linked above
6. ✅ Notice that `Date added` is still the `default` option
7. (Optional) Login with a Plus account having folders
8. (Optional) Tap a folder in Podcasts tab
9. (Optional) Open `Sort by` from more menu for folders
10. (Optional) Notice that the sort options are arranged in the same order as for podcasts 
Podcasts | Folders
---|----
=> Update podcast sorting options order

.buildkite/shared-pipeline-vars
Project Thread: paaHJt-7Tl-p2
Tested Via: [BKCIPL##173](https://github.com/Automattic/a8c-ci-toolkit-buildkite-plugin/pull/173) -> [PCAndroid#3747 ](https://github.com/Automattic/pocket-casts-android/pull/3747)
---
With this version of `a8c-ci-toolkit`, prior to initiating the merged manifest generation for the `head` branch, the `base` branch changes are merged into `head` branch.
As reported already (p1741594194983279/1740493471.859349-slack-C030U03RC8Y), on some PRs ([example](https://github.com/Automattic/pocket-casts-android/pull/3743)), version code/name changes are detected because the head branch wasn't synced with the base branch. In order to avoid such false positives, this change merges the base branch into the head prior to generating the head manifest. This way, comparing the …
=> [AndroidManifest] Improve Merged Manifest Diff

modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/podcasts/PodcastsFragment.kt
- I found this NPE [issue](https://a8c.sentry.io/issues/6426461267/?project=6711064&query=release%3Aau.com.shiftyjelly.pocketcasts%407.85-rc-1%2B9323%20error.unhandled%3Atrue&referrer=issue-stream&sort=freq&stream_index=6) in Beta `7.85-rc1`. Based on the stack trace, it seems that ViewModel states (e.g., `viewModel.folderState`) were being accessed before the ViewModel was fully initialized. To fix this, I have moved the ViewModel observable states from `onCreateView()` to `onViewCreated()` to ensure the ViewModel is ready before observation.
- See my investigation here: p1742479101910589-slack-C07J5LNP4SF
- I could not reproduce this issue, but you can smoke tests the `Podcasts` tab. Also Folders and `Smart Folders` feature.
=> Attempt to fix NPE in Podcasts tab

modules/features/profile/src/main/java/au/com/shiftyjelly/pocketcasts/profile/winback/WinbackViewModel.kt, modules/services/model/src/main/java/au/com/shiftyjelly/pocketcasts/models/type/SubscriptionMapper.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/referrals/ReferralOfferInfoProviderTest.kt
Cherry-pick changes from https://github.com/Automattic/pocket-casts-android/pull/3802
=> Cherry-pick changes from #3802

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/video/VideoView.kt
(cherry picked from https://github.com/Automattic/pocket-casts-android/pull/3823)
=> Temporary fix for video not playing in landscape mode (#3823)

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
Feature flag configuration for the account creation project. 
=> Add account creation encouragement feature flag

modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
A small change to add the recommendations feature flag.
Not much to test here but you could check the feature is on the Settings -> Beta features page.
=> Add recommendations feature flag

modules/services/localization/src/main/res/values/strings.xml
Change to the titles in 2 pages of the Winback flow.
Designs: G22KfZwL1Gv5yyxdTheF9H-fi-1007_4467
=> Update winback pages title copies

CHANGELOG.md, modules/services/utils/src/main/java/au/com/shiftyjelly/pocketcasts/utils/featureflag/Feature.kt
This connects the local feature flag with the remote one for the account encouragement project.
=> Enable account encouragement feature flag

app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactoryTest.kt, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/SuggestedFoldersViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsFragment.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsScreen.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/NotificationsSettingsViewModel.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/components/NotificationPreferenceCategory.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/data/NotificationsPreferencesRepositoryImpl.kt, modules/features/settings/src/main/java/au/com/shiftyjelly/pocketcasts/settings/notifications/model/NotificationPreferenceType.kt, modules/features/settings/src/test/java/au/com/shiftyjelly/pocketcasts/settings/settings/NotificationsPreferencesRepositoryImplTest.kt, modules/services/analytics/src/main/java/au/com/shiftyjelly/pocketcasts/analytics/AnalyticsEvent.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLink.kt, modules/services/deeplink/src/main/kotlin/au/com/shiftyjelly/pocketcasts/deeplink/DeepLinkFactory.kt, modules/services/localization/src/main/res/values/strings.xml, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/Settings.kt, modules/services/preferences/src/main/java/au/com/shiftyjelly/pocketcasts/preferences/SettingsImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculator.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelper.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationHelperImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationScheduler.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationSchedulerImpl.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationType.kt, modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationWorker.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/notification/NotificationDelayCalculatorTest.kt
This PR adds the 'Features & Tips' section to the notification settings screen. It also schedules a notification to promote our current feature, smart folders. Later releases will promote other features, so we'll need to manually update what we want to show to users.
0. apply [features_notifications.patch](https://github.com/user-attachments/files/20441083/features_notifications.patch), build the app
2. Allow notifications, don't log in and don't follow any podcasts
3. Navigate to Settings -> Notifications
4. Wait for at least 10 seconds
5. Now turn off Features and tips
6. Sign in with an account that follows many podcasts
7. Go to Settings -> Notifications
8. Enable Features and Tips again
9. Wait for 10 seconds
10. Tap on it
11. Now go back to Notification settings …
=> [Notifications Revamp] New features and tips

modules/services/compose/src/main/java/au/com/shiftyjelly/pocketcasts/compose/ad/AdBanner.kt
Internal ref: p1749071961248199-slack-C08U02AG7C5
| - | - |
| <img width="411" alt="Screenshot 2025-06-05 at 12 03 15" src="https://github.com/user-attachments/assets/c75effde-6348-4ce8-80ac-c00cd0e45e01" /> | <img width="411" alt="Screenshot 2025-06-05 at 12 03 20" src="https://github.com/user-attachments/assets/acbd1491-70b0-4e66-b515-f612a9daafe1" /> |
=> Change AdBanner options icon

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/EpisodeTitles.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/nowplaying/PlayerControls.kt, modules/features/player/src/main/res/layout/view_playback_seek_bar.xml, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/TranscriptFragment.kt, modules/features/transcripts/src/main/kotlin/au/com/shiftyjelly/pocketcasts/transcripts/ui/TranscriptLines.kt, modules/services/ui/src/main/res/values-sw600dp/dimens.xml, modules/services/ui/src/main/res/values/dimens.xml
This restructures player's composable functions to smaller pieces in order to make it easier to read and introduce horizontal player UI more easily.
Smoke test player UI and transcripts.
=> Refactor player UI functions

modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/PlayerHeaderFragment.kt
This is a follow-up to #4193 where it was set to auto-merge and I didn't address the feedback because of that.
=> Remove unused launched effect

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImpl.kt, modules/services/repositories/src/test/java/au/com/shiftyjelly/pocketcasts/repositories/podcast/SmartPlaylistManagerImplTest.kt
=> Fix flaky test

modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/data/PodcastSync.kt
This change prevents the sync process from failing if subscribing to a podcast fails. Instead, syncing will continue, matching the behavior of the old sync process. The issue was discovered during staging sync, where some podcasts were missing, but it is entirely possible for such calls to just fail.
Relates to PCDROID-119
=> Fix syncing individual podcasts

app/build.gradle.kts, app/src/androidTest/java/au/com/shiftyjelly/pocketcasts/localization/helper/LocalisationTests.kt, app/src/main/AndroidManifest.xml, app/src/main/java/au/com/shiftyjelly/pocketcasts/ui/MainActivity.kt, automotive/build.gradle.kts, build.gradle.kts, dependencies.gradle.kts, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/EffectsFragment.kt, modules/features/player/src/main/java/au/com/shiftyjelly/pocketcasts/player/view/SleepFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderChooserFragment.kt, modules/features/podcasts/src/main/java/au/com/shiftyjelly/pocketcasts/podcasts/view/folders/FolderCreateFragment.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/component/NumericStepper.kt, modules/services/views/src/main/java/au/com/shiftyjelly/pocketcasts/views/fragments/BaseDialogFragment.kt, wear/build.gradle.kts
This updates the target SDK and compile SDK to 36. I separated the target SDK configuration in Gradle across different platforms, since they are unrelated concepts. In the past, updating the SDK for all platforms at once caused issues on platforms that didn’t support it.
Smoke test the app on Mobile, Wear, and Automotive with the latest Android OS.
=> Support target SDK 36
